#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(99)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
*b=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (c->remove(343)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (c->remove(41)) << std::endl;
*b=*a;
*a=*c;
a->printPretty();
b->printPretty();
*a=*a;
std::cout << (c->remove(5)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->insert(200)) << std::endl;
a->printPretty();
*c=*b;
std::cout << (d->insert(427)) << std::endl;
d->printPretty();
std::cout << (d->remove(367)) << std::endl;
c->printPretty();
b->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (c->insert(37)) << std::endl;
c->printPretty();
*b=*c;
b->printPretty();
*e=*a;
*d=*a;
*e=*a;
*b=*d;
e->printPretty();
std::cout << (e->remove(182)) << std::endl;
std::cout << (c->remove(37)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
*a=*b;
*d=*b;
std::cout << (e->insert(114)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (c->remove(103)) << std::endl;
e->printPretty();
*d=*c;
*e=*b;
c->printPretty();
std::cout << (b->insert(379)) << std::endl;
a->printPretty();
*e=*b;
std::cout << (b->insert(366)) << std::endl;
b->printPretty();
std::cout << (a->insert(95)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
b->printPretty();
std::cout << (c->insert(260)) << std::endl;
e->printPretty();
std::cout << (e->remove(485)) << std::endl;
e->printPretty();
std::cout << (c->remove(30)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (a->remove(33)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
b->printPretty();
std::cout << (e->insert(296)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
*e=*e;
std::cout << (b->remove(366)) << std::endl;
*a=*b;
*c=*e;
*c=*b;
std::cout << (a->insert(379)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (e->remove(218)) << std::endl;
std::cout << (b->insert(379)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
d->printPretty();
std::cout << (b->insert(272)) << std::endl;
std::cout << (b->insert(379)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (b->remove(330)) << std::endl;
*c=*e;
std::cout << (c->insert(296)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
*b=*e;
std::cout << (a->remove(379)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
*d=*b;
std::cout << (d->remove(296)) << std::endl;
std::cout << (a->remove(456)) << std::endl;
b->printPretty();
c->printPretty();
a->printPretty();
std::cout << (a->remove(328)) << std::endl;
*d=*b;
std::cout << (b->insert(258)) << std::endl;
c->printPretty();
std::cout << (b->remove(296)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
d->printPretty();
std::cout << (c->insert(296)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
std::cout << (e->remove(48)) << std::endl;
std::cout << (b->remove(60)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (e->remove(486)) << std::endl;
std::cout << (d->remove(296)) << std::endl;
*b=*b;
std::cout << (c->insert(91)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
*d=*c;
std::cout << (c->insert(91)) << std::endl;
std::cout << (c->insert(296)) << std::endl;
e->printPretty();
std::cout << (a->remove(319)) << std::endl;
std::cout << (c->remove(296)) << std::endl;
e->printPretty();
std::cout << (b->insert(16)) << std::endl;
std::cout << (d->remove(238)) << std::endl;
c->printPretty();
d->printPretty();
a->printPretty();
*b=*e;
d->printPretty();
std::cout << (b->remove(236)) << std::endl;
d->printPretty();
*d=*b;
*b=*e;
std::cout << (b->remove(58)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
std::cout << (b->remove(236)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
d->printPretty();
std::cout << (e->remove(236)) << std::endl;
std::cout << (b->remove(398)) << std::endl;
*b=*b;
std::cout << (c->remove(91)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
std::cout << (c->remove(119)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (b->remove(4)) << std::endl;
*c=*b;
*b=*c;
std::cout << (a->insert(407)) << std::endl;
std::cout << (d->insert(187)) << std::endl;
std::cout << (c->remove(375)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
b->printPretty();
std::cout << (a->insert(297)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
e->printPretty();
std::cout << (a->remove(271)) << std::endl;
*c=*d;
std::cout << (a->insert(297)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
*a=*d;
std::cout << (c->remove(187)) << std::endl;
*e=*a;
*c=*b;
std::cout << (b->remove(375)) << std::endl;
e->printPretty();
*b=*d;
*d=*a;
std::cout << (c->remove(375)) << std::endl;
*a=*c;
std::cout << (a->remove(381)) << std::endl;
std::cout << (c->insert(26)) << std::endl;
c->printPretty();
std::cout << (a->insert(299)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (c->insert(453)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (c->insert(26)) << std::endl;
std::cout << (c->remove(26)) << std::endl;
*a=*d;
std::cout << (c->remove(442)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
*a=*b;
std::cout << (c->remove(178)) << std::endl;
*a=*a;
a->printPretty();
std::cout << (b->insert(497)) << std::endl;
std::cout << (a->remove(138)) << std::endl;
*d=*a;
std::cout << (b->insert(497)) << std::endl;
b->printPretty();
std::cout << (b->remove(497)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
*d=*c;
*b=*a;
std::cout << (d->insert(374)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->insert(343)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
b->printPretty();
e->printPretty();
*a=*c;
std::cout << (b->insert(473)) << std::endl;
std::cout << (a->remove(73)) << std::endl;
std::cout << (b->insert(473)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
*d=*e;
e->printPretty();
std::cout << (d->insert(245)) << std::endl;
d->printPretty();
*e=*a;
std::cout << (e->remove(392)) << std::endl;
e->printPretty();
std::cout << (e->insert(463)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (e->remove(453)) << std::endl;
*c=*a;
e->printPretty();
*d=*d;
std::cout << (d->insert(245)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
e->printPretty();
std::cout << (a->insert(443)) << std::endl;
b->printPretty();
*e=*e;
std::cout << (e->remove(463)) << std::endl;
*b=*b;
std::cout << (d->remove(136)) << std::endl;
*c=*c;
*d=*d;
std::cout << (e->remove(467)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (c->remove(289)) << std::endl;
*a=*e;
std::cout << (c->insert(463)) << std::endl;
std::cout << (b->remove(289)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
e->printPretty();
std::cout << (e->remove(49)) << std::endl;
std::cout << (d->remove(112)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->insert(93)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
e->printPretty();
b->printPretty();
*a=*a;
std::cout << (b->remove(35)) << std::endl;
d->printPretty();
e->printPretty();
e->printPretty();
std::cout << (a->insert(67)) << std::endl;
a->printPretty();
std::cout << (e->insert(172)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (c->insert(351)) << std::endl;
std::cout << (b->insert(168)) << std::endl;
c->printPretty();
std::cout << (d->insert(187)) << std::endl;
std::cout << (a->remove(67)) << std::endl;
*b=*c;
std::cout << (d->insert(187)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
e->printPretty();
std::cout << (a->remove(500)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
*c=*b;
std::cout << (a->insert(324)) << std::endl;
e->printPretty();
std::cout << (b->insert(462)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
std::cout << (e->insert(172)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
std::cout << (d->remove(142)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (d->insert(434)) << std::endl;
std::cout << (e->remove(139)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
*c=*b;
std::cout << (a->remove(351)) << std::endl;
std::cout << (d->insert(434)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
b->printPretty();
std::cout << (d->remove(214)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (e->insert(172)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
b->printPretty();
std::cout << (b->insert(462)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
*d=*d;
std::cout << (e->insert(21)) << std::endl;
std::cout << (e->insert(85)) << std::endl;
*d=*c;
std::cout << (e->remove(380)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
*e=*b;
*b=*a;
std::cout << (a->remove(5)) << std::endl;
std::cout << (e->remove(284)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
a->printPretty();
std::cout << (e->remove(274)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (d->insert(443)) << std::endl;
*d=*b;
*a=*c;
std::cout << (b->remove(322)) << std::endl;
std::cout << (e->remove(154)) << std::endl;
std::cout << (a->insert(107)) << std::endl;
std::cout << (a->insert(148)) << std::endl;
*a=*a;
std::cout << (c->remove(27)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (d->insert(217)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (e->insert(192)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (d->insert(192)) << std::endl;
std::cout << (e->remove(382)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
e->printPretty();
std::cout << (c->remove(416)) << std::endl;
std::cout << (d->insert(114)) << std::endl;
d->printPretty();
std::cout << (c->insert(462)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->remove(4)) << std::endl;
a->printPretty();
std::cout << (a->insert(462)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
*a=*d;
std::cout << (d->insert(462)) << std::endl;
std::cout << (e->remove(462)) << std::endl;
std::cout << (b->remove(189)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
*d=*d;
std::cout << (e->insert(269)) << std::endl;
b->printPretty();
std::cout << (d->insert(466)) << std::endl;
std::cout << (c->insert(350)) << std::endl;
std::cout << (c->remove(350)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
a->printPretty();
e->printPretty();
d->printPretty();
b->printPretty();
std::cout << (d->remove(102)) << std::endl;
*d=*e;
*c=*a;
std::cout << (c->insert(246)) << std::endl;
*e=*e;
a->printPretty();
*e=*d;
std::cout << (e->remove(269)) << std::endl;
*b=*b;
std::cout << (b->remove(18)) << std::endl;
std::cout << (d->remove(269)) << std::endl;
d->printPretty();
std::cout << (d->insert(153)) << std::endl;
e->printPretty();
std::cout << (a->insert(91)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (d->remove(153)) << std::endl;
std::cout << (e->remove(222)) << std::endl;
*a=*e;
std::cout << (c->insert(282)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
e->printPretty();
*a=*a;
d->printPretty();
std::cout << (c->insert(282)) << std::endl;
d->printPretty();
std::cout << (a->insert(46)) << std::endl;
*c=*e;
std::cout << (e->remove(414)) << std::endl;
std::cout << (d->insert(409)) << std::endl;
*c=*b;
std::cout << (d->insert(409)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (d->insert(409)) << std::endl;
*d=*b;
*b=*c;
*c=*d;
std::cout << (a->insert(46)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (e->insert(335)) << std::endl;
*d=*b;
*d=*a;
std::cout << (d->insert(182)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
e->printPretty();
std::cout << (d->insert(211)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
*a=*c;
std::cout << (d->remove(46)) << std::endl;
e->printPretty();
std::cout << (e->insert(41)) << std::endl;
*b=*b;
std::cout << (d->remove(211)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (b->insert(442)) << std::endl;
std::cout << (d->insert(57)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
*b=*e;
c->printPretty();
a->printPretty();
*c=*d;
std::cout << (c->insert(182)) << std::endl;
a->printPretty();
std::cout << (d->remove(173)) << std::endl;
*a=*e;
std::cout << (e->remove(41)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
*d=*a;
std::cout << (b->insert(41)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
c->printPretty();
e->printPretty();
d->printPretty();
*e=*c;
std::cout << (b->insert(106)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(182)) << std::endl;
std::cout << (d->insert(335)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
c->printPretty();
std::cout << (d->insert(114)) << std::endl;
*a=*b;
*c=*e;
std::cout << (c->insert(57)) << std::endl;
a->printPretty();
std::cout << (b->remove(41)) << std::endl;
*b=*d;
std::cout << (d->insert(497)) << std::endl;
std::cout << (d->remove(269)) << std::endl;
c->printPretty();
std::cout << (a->remove(385)) << std::endl;
std::cout << (e->remove(477)) << std::endl;
*c=*d;
std::cout << (d->remove(189)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (d->remove(218)) << std::endl;
d->printPretty();
std::cout << (b->remove(41)) << std::endl;
std::cout << (b->remove(335)) << std::endl;
std::cout << (a->remove(410)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
a->printPretty();
std::cout << (b->remove(114)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
std::cout << (c->insert(287)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
*e=*e;
std::cout << (e->insert(485)) << std::endl;
std::cout << (a->insert(374)) << std::endl;
*e=*b;
std::cout << (b->insert(262)) << std::endl;
a->printPretty();
std::cout << (d->insert(231)) << std::endl;
std::cout << (d->insert(207)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
std::cout << (a->insert(464)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
*d=*a;
std::cout << (a->insert(106)) << std::endl;
*b=*b;
e->printPretty();
*b=*e;
std::cout << (d->insert(244)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
std::cout << (b->insert(57)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (b->insert(106)) << std::endl;
std::cout << (a->remove(309)) << std::endl;
*d=*d;
std::cout << (e->remove(445)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (d->remove(335)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
b->printPretty();
c->printPretty();
*a=*e;
std::cout << (a->remove(81)) << std::endl;
*d=*a;
std::cout << (a->insert(265)) << std::endl;
std::cout << (a->remove(265)) << std::endl;
*e=*c;
std::cout << (e->insert(484)) << std::endl;
*b=*a;
std::cout << (c->remove(281)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
*b=*b;
b->printPretty();
std::cout << (c->insert(370)) << std::endl;
*d=*d;
std::cout << (b->insert(447)) << std::endl;
e->printPretty();
std::cout << (d->remove(155)) << std::endl;
b->printPretty();
std::cout << (b->remove(447)) << std::endl;
*c=*d;
std::cout << (d->insert(183)) << std::endl;
d->printPretty();
std::cout << (c->insert(166)) << std::endl;
a->printPretty();
std::cout << (d->insert(443)) << std::endl;
*c=*e;
std::cout << (c->remove(370)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (e->insert(374)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->insert(245)) << std::endl;
*c=*a;
std::cout << (d->insert(183)) << std::endl;
*a=*b;
*c=*b;
std::cout << (a->remove(175)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
*d=*d;
b->printPretty();
e->printPretty();
*d=*a;
*e=*e;
d->printPretty();
*a=*e;
*c=*e;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
*a=*e;
std::cout << (a->remove(430)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
std::cout << (a->insert(412)) << std::endl;
*d=*e;
e->printPretty();
std::cout << (e->remove(374)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
*e=*d;
std::cout << (b->insert(19)) << std::endl;
b->printPretty();
std::cout << (d->insert(370)) << std::endl;
*a=*b;
*b=*a;
*a=*c;
std::cout << (b->remove(19)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
*b=*b;
*d=*d;
*c=*c;
std::cout << (c->insert(464)) << std::endl;
b->printPretty();
std::cout << (a->insert(374)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
d->printPretty();
std::cout << (b->remove(293)) << std::endl;
b->printPretty();
std::cout << (c->insert(370)) << std::endl;
c->printPretty();
std::cout << (e->remove(64)) << std::endl;
e->printPretty();
std::cout << (a->insert(484)) << std::endl;
a->printPretty();
std::cout << (b->remove(153)) << std::endl;
*b=*e;
std::cout << (b->remove(62)) << std::endl;
std::cout << (a->insert(374)) << std::endl;
std::cout << (b->remove(374)) << std::endl;
std::cout << (b->insert(353)) << std::endl;
std::cout << (b->insert(484)) << std::endl;
*e=*a;
*b=*c;
std::cout << (d->insert(335)) << std::endl;
std::cout << (e->remove(370)) << std::endl;
std::cout << (c->insert(374)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
d->printPretty();
*a=*e;
std::cout << (e->insert(168)) << std::endl;
e->printPretty();
return 0;
}
