#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
a->printPretty();
std::cout << (a->insert(168)) << std::endl;
std::cout << (a->insert(168)) << std::endl;
std::cout << (a->remove(168)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
std::cout << (a->remove(345)) << std::endl;
std::cout << (a->insert(125)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(334)) << std::endl;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (c->insert(259)) << std::endl;
b->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*a=*d;
std::cout << (d->remove(234)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
*e=*b;
std::cout << (a->remove(191)) << std::endl;
c->printPretty();
std::cout << (d->insert(120)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (a->remove(50)) << std::endl;
*d=*b;
std::cout << (d->remove(23)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
a->printPretty();
*e=*d;
a->printPretty();
std::cout << (b->remove(367)) << std::endl;
c->printPretty();
std::cout << (d->insert(10)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(238)) << std::endl;
std::cout << (d->insert(109)) << std::endl;
d->printPretty();
std::cout << (c->remove(259)) << std::endl;
*b=*a;
std::cout << (e->remove(454)) << std::endl;
d->printPretty();
c->printPretty();
a->printPretty();
std::cout << (b->remove(312)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (e->insert(168)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (b->insert(372)) << std::endl;
*a=*b;
std::cout << (d->remove(285)) << std::endl;
*c=*a;
b->printPretty();
e->printPretty();
c->printPretty();
std::cout << (c->insert(169)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
*b=*c;
std::cout << (a->remove(372)) << std::endl;
*d=*e;
std::cout << (d->remove(109)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
*d=*b;
std::cout << (e->insert(283)) << std::endl;
std::cout << (d->remove(372)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (c->remove(188)) << std::endl;
std::cout << (e->insert(281)) << std::endl;
a->printPretty();
std::cout << (d->remove(169)) << std::endl;
e->printPretty();
std::cout << (d->insert(358)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
std::cout << (e->insert(253)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (c->insert(255)) << std::endl;
d->printPretty();
std::cout << (e->remove(109)) << std::endl;
*a=*c;
std::cout << (d->remove(358)) << std::endl;
std::cout << (e->remove(283)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
*b=*d;
std::cout << (a->insert(251)) << std::endl;
*d=*a;
std::cout << (a->remove(251)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
*b=*a;
std::cout << (a->insert(125)) << std::endl;
std::cout << (b->remove(372)) << std::endl;
std::cout << (a->remove(255)) << std::endl;
std::cout << (c->remove(358)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (c->insert(255)) << std::endl;
*a=*a;
std::cout << (e->remove(358)) << std::endl;
*e=*c;
b->printPretty();
*d=*d;
*a=*c;
std::cout << (c->remove(216)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (d->remove(372)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
*b=*b;
std::cout << (a->insert(57)) << std::endl;
c->printPretty();
std::cout << (b->remove(147)) << std::endl;
*a=*c;
*a=*b;
std::cout << (d->insert(255)) << std::endl;
*d=*c;
std::cout << (d->insert(388)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
d->printPretty();
std::cout << (c->remove(388)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (d->remove(388)) << std::endl;
*d=*b;
std::cout << (e->insert(363)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
*e=*d;
std::cout << (e->insert(48)) << std::endl;
std::cout << (e->insert(210)) << std::endl;
a->printPretty();
std::cout << (d->remove(358)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
*e=*e;
std::cout << (e->remove(48)) << std::endl;
*a=*d;
std::cout << (c->remove(372)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (d->insert(386)) << std::endl;
*c=*a;
std::cout << (e->remove(17)) << std::endl;
std::cout << (e->insert(495)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (d->insert(335)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
std::cout << (a->remove(251)) << std::endl;
std::cout << (b->remove(10)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->remove(362)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (d->remove(335)) << std::endl;
std::cout << (a->insert(177)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (d->remove(56)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
d->printPretty();
std::cout << (e->remove(108)) << std::endl;
std::cout << (e->remove(210)) << std::endl;
*a=*c;
std::cout << (b->remove(13)) << std::endl;
std::cout << (c->remove(216)) << std::endl;
*e=*c;
*b=*b;
std::cout << (b->insert(358)) << std::endl;
std::cout << (b->insert(104)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
*a=*c;
*b=*d;
*c=*d;
*c=*b;
std::cout << (e->remove(406)) << std::endl;
*a=*d;
*d=*b;
std::cout << (d->remove(465)) << std::endl;
*b=*d;
std::cout << (d->insert(358)) << std::endl;
c->printPretty();
std::cout << (b->insert(3)) << std::endl;
*c=*a;
std::cout << (c->insert(358)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
*a=*a;
std::cout << (d->insert(333)) << std::endl;
std::cout << (c->insert(87)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (d->insert(463)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
std::cout << (b->remove(3)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
*a=*b;
*c=*b;
std::cout << (e->remove(500)) << std::endl;
a->printPretty();
std::cout << (b->insert(226)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (d->insert(63)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (a->insert(244)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
*e=*d;
std::cout << (d->remove(500)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
*d=*d;
std::cout << (d->remove(222)) << std::endl;
std::cout << (b->remove(380)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
std::cout << (e->insert(443)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
e->printPretty();
std::cout << (c->remove(26)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (c->remove(358)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
std::cout << (a->remove(335)) << std::endl;
*c=*b;
std::cout << (d->remove(46)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
a->printPretty();
std::cout << (a->insert(500)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
std::cout << (c->remove(492)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
std::cout << (a->remove(500)) << std::endl;
*b=*b;
d->printPretty();
std::cout << (a->insert(96)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
std::cout << (d->remove(457)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (b->insert(295)) << std::endl;
e->printPretty();
std::cout << (c->insert(500)) << std::endl;
b->printPretty();
std::cout << (a->insert(463)) << std::endl;
std::cout << (a->insert(443)) << std::endl;
*c=*b;
std::cout << (c->insert(236)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
b->printPretty();
std::cout << (a->remove(269)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
b->printPretty();
std::cout << (b->remove(37)) << std::endl;
*a=*c;
std::cout << (a->remove(465)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
std::cout << (a->remove(99)) << std::endl;
std::cout << (e->remove(443)) << std::endl;
b->printPretty();
std::cout << (c->remove(295)) << std::endl;
std::cout << (d->insert(221)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
std::cout << (a->remove(236)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
std::cout << (a->remove(260)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (b->remove(239)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (e->insert(346)) << std::endl;
c->printPretty();
std::cout << (d->insert(358)) << std::endl;
*b=*d;
*b=*d;
std::cout << (b->insert(140)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
std::cout << (e->insert(493)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
std::cout << (e->insert(429)) << std::endl;
std::cout << (d->insert(278)) << std::endl;
a->printPretty();
std::cout << (c->insert(190)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
*d=*b;
std::cout << (a->insert(463)) << std::endl;
*b=*b;
std::cout << (b->remove(124)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
*e=*c;
std::cout << (b->insert(120)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->remove(236)) << std::endl;
e->printPretty();
std::cout << (c->remove(284)) << std::endl;
std::cout << (a->insert(190)) << std::endl;
c->printPretty();
d->printPretty();
d->printPretty();
std::cout << (c->insert(335)) << std::endl;
std::cout << (d->remove(63)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
std::cout << (d->remove(358)) << std::endl;
d->printPretty();
std::cout << (b->remove(16)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
*c=*e;
std::cout << (a->insert(463)) << std::endl;
std::cout << (e->remove(463)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (e->remove(492)) << std::endl;
std::cout << (e->remove(315)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
std::cout << (d->insert(276)) << std::endl;
b->printPretty();
std::cout << (a->insert(358)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
std::cout << (e->remove(408)) << std::endl;
*c=*b;
*e=*d;
d->printPretty();
b->printPretty();
std::cout << (a->insert(264)) << std::endl;
std::cout << (c->remove(63)) << std::endl;
e->printPretty();
std::cout << (b->remove(430)) << std::endl;
d->printPretty();
std::cout << (e->remove(463)) << std::endl;
std::cout << (c->insert(256)) << std::endl;
*a=*c;
std::cout << (e->insert(190)) << std::endl;
*b=*a;
*c=*d;
std::cout << (b->insert(389)) << std::endl;
*d=*a;
std::cout << (a->remove(120)) << std::endl;
std::cout << (b->insert(256)) << std::endl;
std::cout << (e->remove(295)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
std::cout << (e->insert(190)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
e->printPretty();
std::cout << (e->remove(190)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (b->remove(120)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
b->printPretty();
std::cout << (a->remove(392)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (b->insert(256)) << std::endl;
b->printPretty();
std::cout << (c->insert(64)) << std::endl;
std::cout << (b->insert(429)) << std::endl;
d->printPretty();
std::cout << (d->insert(353)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (d->remove(120)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (c->remove(295)) << std::endl;
*e=*d;
std::cout << (d->insert(358)) << std::endl;
std::cout << (c->remove(147)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (a->insert(65)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
*b=*b;
std::cout << (c->remove(63)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (a->insert(403)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
std::cout << (b->remove(3)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (e->insert(429)) << std::endl;
c->printPretty();
d->printPretty();
a->printPretty();
c->printPretty();
b->printPretty();
std::cout << (d->remove(248)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (c->insert(64)) << std::endl;
std::cout << (b->remove(63)) << std::endl;
std::cout << (b->remove(16)) << std::endl;
std::cout << (e->insert(131)) << std::endl;
std::cout << (b->insert(63)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
c->printPretty();
std::cout << (b->insert(389)) << std::endl;
d->printPretty();
std::cout << (d->remove(272)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (b->insert(184)) << std::endl;
e->printPretty();
std::cout << (e->remove(480)) << std::endl;
*e=*e;
std::cout << (e->insert(341)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
std::cout << (b->remove(284)) << std::endl;
std::cout << (d->insert(256)) << std::endl;
b->printPretty();
std::cout << (c->remove(358)) << std::endl;
std::cout << (e->remove(339)) << std::endl;
std::cout << (b->remove(40)) << std::endl;
*d=*b;
*d=*d;
d->printPretty();
std::cout << (a->insert(384)) << std::endl;
*d=*d;
std::cout << (e->insert(395)) << std::endl;
*a=*e;
std::cout << (a->remove(78)) << std::endl;
*c=*b;
*d=*b;
std::cout << (a->insert(138)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
d->printPretty();
std::cout << (c->insert(123)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (e->insert(395)) << std::endl;
*c=*c;
std::cout << (d->insert(29)) << std::endl;
*d=*d;
std::cout << (d->insert(389)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
*a=*a;
std::cout << (d->remove(114)) << std::endl;
std::cout << (c->remove(373)) << std::endl;
*d=*d;
std::cout << (b->insert(366)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
std::cout << (e->insert(215)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
*d=*d;
std::cout << (a->insert(353)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
c->printPretty();
std::cout << (b->insert(312)) << std::endl;
std::cout << (b->remove(256)) << std::endl;
*a=*a;
std::cout << (e->remove(131)) << std::endl;
d->printPretty();
*e=*d;
*c=*a;
std::cout << (b->insert(293)) << std::endl;
std::cout << (d->insert(389)) << std::endl;
*b=*d;
std::cout << (a->remove(138)) << std::endl;
*b=*c;
std::cout << (e->insert(86)) << std::endl;
e->printPretty();
std::cout << (d->remove(411)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (c->insert(226)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
std::cout << (d->insert(63)) << std::endl;
std::cout << (c->insert(121)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
e->printPretty();
std::cout << (b->insert(353)) << std::endl;
std::cout << (e->insert(308)) << std::endl;
e->printPretty();
std::cout << (a->remove(392)) << std::endl;
b->printPretty();
std::cout << (c->insert(429)) << std::endl;
*c=*a;
std::cout << (c->insert(276)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
*a=*d;
b->printPretty();
std::cout << (b->remove(429)) << std::endl;
std::cout << (c->remove(363)) << std::endl;
e->printPretty();
std::cout << (b->remove(395)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (c->remove(276)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (c->insert(72)) << std::endl;
std::cout << (b->remove(125)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
std::cout << (c->remove(442)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
std::cout << (e->remove(2)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->insert(324)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
std::cout << (b->insert(38)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
d->printPretty();
std::cout << (b->remove(93)) << std::endl;
*a=*d;
std::cout << (d->insert(106)) << std::endl;
std::cout << (b->insert(5)) << std::endl;
std::cout << (d->remove(280)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
a->printPretty();
*b=*a;
b->printPretty();
*c=*b;
std::cout << (a->insert(429)) << std::endl;
d->printPretty();
*b=*c;
std::cout << (b->insert(226)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
*c=*b;
*c=*a;
d->printPretty();
*a=*d;
std::cout << (b->remove(381)) << std::endl;
*d=*a;
std::cout << (d->insert(43)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
std::cout << (a->insert(317)) << std::endl;
*d=*d;
std::cout << (c->insert(358)) << std::endl;
c->printPretty();
std::cout << (a->remove(306)) << std::endl;
*d=*b;
std::cout << (b->insert(389)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (c->insert(2)) << std::endl;
std::cout << (b->remove(130)) << std::endl;
std::cout << (c->insert(63)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (b->remove(51)) << std::endl;
*e=*c;
std::cout << (e->remove(143)) << std::endl;
std::cout << (d->insert(2)) << std::endl;
std::cout << (b->remove(348)) << std::endl;
d->printPretty();
std::cout << (c->remove(389)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
*d=*b;
std::cout << (a->insert(469)) << std::endl;
c->printPretty();
std::cout << (e->remove(337)) << std::endl;
std::cout << (e->insert(412)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
*d=*b;
std::cout << (a->insert(76)) << std::endl;
std::cout << (e->remove(383)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
c->printPretty();
std::cout << (a->remove(317)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
d->printPretty();
std::cout << (e->remove(312)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
*c=*a;
std::cout << (c->insert(320)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
*e=*e;
std::cout << (a->remove(242)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
e->printPretty();
std::cout << (b->remove(484)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
*b=*d;
std::cout << (d->insert(29)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
c->printPretty();
c->printPretty();
*a=*e;
std::cout << (a->remove(429)) << std::endl;
*e=*e;
std::cout << (d->insert(144)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->insert(184)) << std::endl;
std::cout << (c->remove(215)) << std::endl;
c->printPretty();
*b=*a;
c->printPretty();
std::cout << (c->insert(381)) << std::endl;
*d=*b;
*e=*e;
*c=*d;
*a=*e;
std::cout << (c->remove(189)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
*b=*b;
*a=*c;
std::cout << (e->remove(63)) << std::endl;
*b=*a;
std::cout << (d->remove(179)) << std::endl;
a->printPretty();
*a=*c;
b->printPretty();
*e=*b;
b->printPretty();
std::cout << (c->insert(197)) << std::endl;
std::cout << (d->insert(2)) << std::endl;
std::cout << (c->insert(456)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
d->printPretty();
std::cout << (e->insert(345)) << std::endl;
c->printPretty();
std::cout << (b->remove(29)) << std::endl;
std::cout << (e->remove(91)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (e->insert(192)) << std::endl;
b->printPretty();
std::cout << (d->remove(58)) << std::endl;
a->printPretty();
std::cout << (d->insert(389)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->insert(451)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
std::cout << (b->remove(63)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (c->insert(63)) << std::endl;
*a=*a;
std::cout << (b->remove(192)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (e->remove(495)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
std::cout << (c->remove(63)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
std::cout << (c->insert(389)) << std::endl;
c->printPretty();
*d=*e;
std::cout << (b->remove(412)) << std::endl;
*c=*c;
std::cout << (e->remove(109)) << std::endl;
std::cout << (e->remove(412)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (e->insert(91)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
std::cout << (e->remove(160)) << std::endl;
c->printPretty();
std::cout << (b->remove(389)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
std::cout << (d->insert(428)) << std::endl;
std::cout << (e->insert(2)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
c->printPretty();
std::cout << (d->remove(139)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
d->printPretty();
std::cout << (e->insert(284)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
return 0;
}
