#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(49)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(322)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (d->remove(479)) << std::endl;
*a=*a;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->insert(151)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
d->printPretty();
std::cout << (b->insert(308)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
b->printPretty();
std::cout << (b->insert(308)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
e->printPretty();
std::cout << (a->insert(216)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (a->insert(290)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
*b=*c;
std::cout << (d->insert(146)) << std::endl;
std::cout << (d->remove(287)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
c->printPretty();
std::cout << (a->insert(290)) << std::endl;
std::cout << (a->insert(290)) << std::endl;
std::cout << (a->remove(290)) << std::endl;
a->printPretty();
std::cout << (e->remove(383)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (e->remove(57)) << std::endl;
*e=*c;
a->printPretty();
b->printPretty();
std::cout << (a->insert(347)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
std::cout << (e->remove(374)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
std::cout << (d->insert(146)) << std::endl;
e->printPretty();
std::cout << (e->insert(121)) << std::endl;
std::cout << (c->insert(139)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
*b=*c;
e->printPretty();
*c=*c;
*e=*a;
std::cout << (a->remove(65)) << std::endl;
*c=*e;
*c=*d;
d->printPretty();
std::cout << (c->insert(146)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->remove(347)) << std::endl;
b->printPretty();
std::cout << (b->insert(8)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
*c=*b;
d->printPretty();
c->printPretty();
*c=*c;
*c=*c;
*c=*a;
*d=*b;
c->printPretty();
std::cout << (d->remove(139)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->remove(304)) << std::endl;
e->printPretty();
std::cout << (d->remove(8)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (e->remove(194)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (c->remove(403)) << std::endl;
d->printPretty();
std::cout << (b->insert(8)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
b->printPretty();
std::cout << (d->remove(460)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (d->insert(400)) << std::endl;
*d=*b;
std::cout << (c->insert(361)) << std::endl;
std::cout << (e->remove(445)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
*e=*e;
std::cout << (b->insert(396)) << std::endl;
*b=*c;
std::cout << (a->remove(180)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (c->remove(9)) << std::endl;
c->printPretty();
*d=*d;
std::cout << (e->remove(244)) << std::endl;
*c=*d;
*c=*c;
std::cout << (d->remove(499)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
*c=*c;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (e->insert(483)) << std::endl;
a->printPretty();
std::cout << (a->remove(113)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (e->remove(347)) << std::endl;
a->printPretty();
*a=*a;
std::cout << (a->remove(474)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (c->insert(151)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
*e=*b;
std::cout << (d->insert(62)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
*b=*c;
std::cout << (d->remove(62)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->insert(151)) << std::endl;
std::cout << (c->remove(151)) << std::endl;
std::cout << (e->insert(361)) << std::endl;
c->printPretty();
std::cout << (e->insert(361)) << std::endl;
std::cout << (c->insert(204)) << std::endl;
std::cout << (a->remove(438)) << std::endl;
std::cout << (e->insert(361)) << std::endl;
std::cout << (c->insert(367)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
*e=*d;
std::cout << (d->remove(290)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
std::cout << (c->remove(423)) << std::endl;
std::cout << (b->insert(389)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
std::cout << (e->insert(13)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
e->printPretty();
std::cout << (d->remove(136)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
*a=*c;
std::cout << (c->remove(204)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
*c=*c;
std::cout << (c->insert(367)) << std::endl;
b->printPretty();
*c=*a;
*c=*c;
d->printPretty();
std::cout << (e->insert(13)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
std::cout << (a->remove(204)) << std::endl;
*a=*e;
std::cout << (a->remove(13)) << std::endl;
std::cout << (a->insert(88)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
*c=*b;
std::cout << (b->remove(389)) << std::endl;
std::cout << (b->remove(16)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
*d=*d;
d->printPretty();
std::cout << (a->insert(88)) << std::endl;
a->printPretty();
*d=*d;
b->printPretty();
std::cout << (c->insert(16)) << std::endl;
std::cout << (e->remove(209)) << std::endl;
std::cout << (a->remove(162)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
std::cout << (e->remove(13)) << std::endl;
*c=*c;
std::cout << (a->insert(462)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
*c=*e;
std::cout << (e->insert(423)) << std::endl;
*a=*e;
std::cout << (d->remove(379)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (a->insert(146)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
*c=*b;
*b=*b;
*a=*b;
e->printPretty();
std::cout << (d->insert(229)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (c->insert(467)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
b->printPretty();
*b=*e;
std::cout << (e->remove(302)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
*a=*d;
std::cout << (b->remove(498)) << std::endl;
std::cout << (b->remove(82)) << std::endl;
std::cout << (b->remove(51)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
*b=*d;
std::cout << (b->insert(414)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
e->printPretty();
std::cout << (e->insert(423)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
d->printPretty();
std::cout << (c->insert(106)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
c->printPretty();
std::cout << (e->remove(423)) << std::endl;
*d=*a;
std::cout << (c->insert(264)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (d->insert(96)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (d->remove(276)) << std::endl;
std::cout << (a->insert(78)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
*a=*b;
std::cout << (d->insert(96)) << std::endl;
std::cout << (d->insert(241)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
*c=*b;
std::cout << (d->insert(79)) << std::endl;
*b=*b;
*a=*b;
*d=*e;
std::cout << (a->insert(264)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
std::cout << (d->insert(180)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
*d=*b;
*b=*a;
e->printPretty();
std::cout << (a->insert(124)) << std::endl;
std::cout << (e->remove(94)) << std::endl;
std::cout << (b->insert(96)) << std::endl;
std::cout << (d->remove(494)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
*c=*d;
std::cout << (b->remove(96)) << std::endl;
std::cout << (a->remove(124)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (b->insert(414)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
std::cout << (d->insert(425)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
c->printPretty();
std::cout << (c->remove(218)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
std::cout << (a->insert(45)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (e->remove(476)) << std::endl;
std::cout << (c->insert(229)) << std::endl;
*c=*a;
std::cout << (a->remove(40)) << std::endl;
*d=*c;
std::cout << (c->insert(445)) << std::endl;
std::cout << (d->remove(149)) << std::endl;
std::cout << (c->remove(414)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
*b=*b;
c->printPretty();
c->printPretty();
std::cout << (c->insert(230)) << std::endl;
a->printPretty();
std::cout << (a->remove(414)) << std::endl;
std::cout << (b->insert(78)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
*b=*e;
std::cout << (d->insert(121)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (c->remove(445)) << std::endl;
*b=*e;
std::cout << (b->insert(10)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (a->insert(462)) << std::endl;
c->printPretty();
std::cout << (e->insert(359)) << std::endl;
std::cout << (b->remove(10)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
*c=*e;
*a=*b;
std::cout << (d->remove(78)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
e->printPretty();
std::cout << (a->insert(186)) << std::endl;
std::cout << (e->remove(60)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (d->remove(414)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
*d=*d;
std::cout << (a->remove(186)) << std::endl;
*a=*b;
b->printPretty();
c->printPretty();
*e=*c;
*e=*d;
std::cout << (b->insert(477)) << std::endl;
*c=*c;
std::cout << (e->remove(7)) << std::endl;
std::cout << (d->insert(450)) << std::endl;
std::cout << (b->remove(477)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (e->remove(440)) << std::endl;
std::cout << (c->remove(433)) << std::endl;
b->printPretty();
std::cout << (d->remove(121)) << std::endl;
std::cout << (d->remove(50)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (c->insert(60)) << std::endl;
d->printPretty();
std::cout << (b->remove(60)) << std::endl;
*a=*e;
std::cout << (b->remove(483)) << std::endl;
std::cout << (b->remove(186)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
std::cout << (d->remove(317)) << std::endl;
std::cout << (d->insert(450)) << std::endl;
*d=*b;
std::cout << (d->insert(461)) << std::endl;
d->printPretty();
std::cout << (a->remove(338)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
d->printPretty();
std::cout << (c->remove(60)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
std::cout << (a->remove(121)) << std::endl;
*b=*a;
std::cout << (b->insert(444)) << std::endl;
*c=*d;
std::cout << (c->insert(8)) << std::endl;
e->printPretty();
std::cout << (c->insert(120)) << std::endl;
std::cout << (c->remove(461)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->insert(461)) << std::endl;
std::cout << (c->remove(121)) << std::endl;
std::cout << (e->remove(121)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (c->remove(120)) << std::endl;
std::cout << (c->remove(8)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
std::cout << (e->remove(84)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
c->printPretty();
std::cout << (e->insert(30)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
b->printPretty();
std::cout << (d->remove(104)) << std::endl;
*b=*a;
std::cout << (b->remove(229)) << std::endl;
*d=*e;
std::cout << (e->remove(229)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (b->remove(485)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (a->remove(229)) << std::endl;
std::cout << (a->insert(398)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (e->remove(204)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(204)) << std::endl;
d->printPretty();
std::cout << (e->insert(401)) << std::endl;
b->printPretty();
std::cout << (d->insert(107)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
b->printPretty();
std::cout << (a->remove(281)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
*e=*e;
std::cout << (c->insert(184)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
*e=*a;
std::cout << (a->insert(398)) << std::endl;
std::cout << (c->insert(233)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (d->remove(384)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
*c=*b;
std::cout << (d->remove(397)) << std::endl;
std::cout << (d->insert(73)) << std::endl;
c->printPretty();
std::cout << (c->insert(392)) << std::endl;
*e=*a;
d->printPretty();
e->printPretty();
a->printPretty();
*d=*a;
std::cout << (c->remove(299)) << std::endl;
e->printPretty();
std::cout << (e->insert(231)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
d->printPretty();
std::cout << (e->remove(372)) << std::endl;
*d=*e;
std::cout << (a->remove(11)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
std::cout << (a->insert(105)) << std::endl;
std::cout << (c->remove(242)) << std::endl;
b->printPretty();
std::cout << (b->remove(230)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
std::cout << (c->remove(425)) << std::endl;
std::cout << (d->remove(318)) << std::endl;
*c=*d;
std::cout << (e->remove(232)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
std::cout << (e->insert(231)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
e->printPretty();
std::cout << (e->insert(336)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
std::cout << (c->insert(231)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
*e=*e;
std::cout << (b->insert(444)) << std::endl;
std::cout << (c->insert(105)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->remove(330)) << std::endl;
a->printPretty();
std::cout << (c->remove(204)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
b->printPretty();
std::cout << (d->remove(204)) << std::endl;
a->printPretty();
std::cout << (c->remove(105)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (e->insert(134)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
c->printPretty();
std::cout << (c->insert(330)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
*e=*d;
std::cout << (b->remove(289)) << std::endl;
*a=*a;
std::cout << (a->remove(105)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
e->printPretty();
std::cout << (e->remove(267)) << std::endl;
*e=*b;
std::cout << (e->insert(276)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (d->remove(4)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (d->remove(231)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
std::cout << (a->insert(496)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (d->insert(210)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (a->insert(365)) << std::endl;
std::cout << (c->remove(435)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
b->printPretty();
std::cout << (e->remove(202)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
*d=*d;
*d=*c;
*b=*d;
std::cout << (b->insert(31)) << std::endl;
std::cout << (d->remove(346)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (b->remove(330)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
*b=*d;
std::cout << (d->insert(310)) << std::endl;
std::cout << (b->insert(225)) << std::endl;
*a=*d;
std::cout << (a->remove(444)) << std::endl;
std::cout << (c->remove(217)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
b->printPretty();
std::cout << (b->insert(465)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
*d=*a;
std::cout << (d->insert(114)) << std::endl;
*b=*e;
std::cout << (a->insert(143)) << std::endl;
std::cout << (c->insert(213)) << std::endl;
std::cout << (d->remove(115)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (a->remove(365)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
c->printPretty();
std::cout << (c->remove(421)) << std::endl;
*c=*b;
std::cout << (b->insert(204)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
std::cout << (c->remove(115)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->remove(231)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (c->remove(387)) << std::endl;
std::cout << (c->remove(370)) << std::endl;
*d=*c;
std::cout << (c->remove(333)) << std::endl;
std::cout << (d->remove(204)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
*b=*c;
std::cout << (e->insert(319)) << std::endl;
std::cout << (d->remove(281)) << std::endl;
std::cout << (e->remove(336)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (e->insert(102)) << std::endl;
std::cout << (a->insert(352)) << std::endl;
*e=*a;
*c=*c;
std::cout << (a->insert(143)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (a->remove(284)) << std::endl;
std::cout << (d->remove(469)) << std::endl;
e->printPretty();
std::cout << (b->insert(136)) << std::endl;
c->printPretty();
std::cout << (d->insert(468)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->insert(87)) << std::endl;
std::cout << (c->remove(345)) << std::endl;
std::cout << (c->insert(157)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
std::cout << (b->remove(204)) << std::endl;
std::cout << (b->insert(43)) << std::endl;
std::cout << (a->remove(89)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
*e=*d;
b->printPretty();
*c=*a;
a->printPretty();
std::cout << (d->remove(450)) << std::endl;
*d=*b;
std::cout << (c->remove(143)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
*b=*e;
*c=*b;
std::cout << (d->insert(281)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
std::cout << (e->insert(20)) << std::endl;
e->printPretty();
std::cout << (c->insert(468)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
std::cout << (a->insert(67)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
std::cout << (a->remove(276)) << std::endl;
a->printPretty();
std::cout << (e->insert(197)) << std::endl;
a->printPretty();
std::cout << (a->insert(143)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (e->remove(197)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
std::cout << (a->insert(45)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (c->remove(169)) << std::endl;
std::cout << (b->remove(244)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
*b=*b;
c->printPretty();
*e=*b;
b->printPretty();
std::cout << (c->remove(143)) << std::endl;
*c=*d;
std::cout << (d->insert(43)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
*a=*e;
std::cout << (d->remove(423)) << std::endl;
*a=*b;
std::cout << (c->remove(360)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
std::cout << (a->remove(109)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
std::cout << (d->remove(228)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (c->insert(468)) << std::endl;
std::cout << (e->insert(122)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (a->remove(468)) << std::endl;
*a=*b;
*c=*c;
c->printPretty();
std::cout << (d->insert(183)) << std::endl;
std::cout << (a->insert(468)) << std::endl;
std::cout << (c->insert(468)) << std::endl;
b->printPretty();
std::cout << (e->remove(240)) << std::endl;
*b=*d;
std::cout << (d->insert(43)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(374)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (a->insert(181)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->remove(206)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
std::cout << (c->remove(468)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(4)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
*d=*b;
std::cout << (e->insert(99)) << std::endl;
std::cout << (a->insert(210)) << std::endl;
*b=*a;
std::cout << (b->remove(181)) << std::endl;
std::cout << (b->insert(269)) << std::endl;
c->printPretty();
std::cout << (a->insert(210)) << std::endl;
std::cout << (d->remove(247)) << std::endl;
a->printPretty();
return 0;
}
