#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (b->remove(227)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*b=*c;
std::cout << (c->insert(69)) << std::endl;
std::cout << (c->insert(224)) << std::endl;
c->printPretty();
std::cout << (a->remove(301)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*a=*c;
std::cout << (c->remove(224)) << std::endl;
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->remove(255)) << std::endl;
std::cout << (d->remove(349)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
std::cout << (c->remove(199)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
b->printPretty();
std::cout << (d->remove(325)) << std::endl;
std::cout << (e->remove(162)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (a->insert(69)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->insert(26)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
std::cout << (a->remove(26)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (c->remove(346)) << std::endl;
std::cout << (d->remove(389)) << std::endl;
*c=*d;
*b=*a;
*b=*a;
std::cout << (a->remove(270)) << std::endl;
c->printPretty();
c->printPretty();
*c=*b;
e->printPretty();
std::cout << (e->remove(191)) << std::endl;
*b=*e;
std::cout << (c->insert(217)) << std::endl;
std::cout << (e->remove(41)) << std::endl;
d->printPretty();
std::cout << (a->insert(224)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (c->remove(224)) << std::endl;
std::cout << (a->remove(227)) << std::endl;
*e=*d;
*a=*e;
*a=*c;
std::cout << (c->remove(217)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (a->remove(378)) << std::endl;
*d=*c;
std::cout << (b->remove(282)) << std::endl;
b->printPretty();
*b=*c;
a->printPretty();
c->printPretty();
*c=*a;
a->printPretty();
b->printPretty();
*a=*c;
std::cout << (e->remove(131)) << std::endl;
std::cout << (c->remove(5)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (a->remove(217)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
*a=*b;
a->printPretty();
c->printPretty();
std::cout << (a->insert(324)) << std::endl;
std::cout << (a->insert(324)) << std::endl;
std::cout << (a->remove(70)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
*b=*c;
std::cout << (c->remove(2)) << std::endl;
*d=*e;
std::cout << (c->remove(212)) << std::endl;
*c=*e;
std::cout << (b->insert(217)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
std::cout << (e->insert(139)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
std::cout << (e->insert(139)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
*d=*a;
std::cout << (a->remove(168)) << std::endl;
*b=*c;
std::cout << (b->insert(132)) << std::endl;
*c=*c;
d->printPretty();
*d=*e;
std::cout << (c->insert(157)) << std::endl;
*b=*e;
std::cout << (a->remove(389)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
std::cout << (e->remove(139)) << std::endl;
c->printPretty();
std::cout << (a->remove(301)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
std::cout << (c->remove(208)) << std::endl;
a->printPretty();
*b=*d;
std::cout << (b->remove(139)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (a->insert(476)) << std::endl;
std::cout << (d->remove(159)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
std::cout << (e->insert(455)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
std::cout << (d->insert(139)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
a->printPretty();
std::cout << (a->insert(166)) << std::endl;
*b=*e;
std::cout << (a->insert(430)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (c->insert(411)) << std::endl;
*a=*b;
std::cout << (c->insert(172)) << std::endl;
std::cout << (d->insert(139)) << std::endl;
std::cout << (e->insert(373)) << std::endl;
*d=*e;
a->printPretty();
*e=*d;
*a=*a;
*a=*e;
std::cout << (b->insert(284)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (e->insert(308)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (d->insert(446)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
c->printPretty();
std::cout << (c->remove(172)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
std::cout << (e->insert(418)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
c->printPretty();
std::cout << (e->insert(308)) << std::endl;
std::cout << (a->insert(122)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
std::cout << (a->remove(118)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
b->printPretty();
std::cout << (c->remove(379)) << std::endl;
std::cout << (b->insert(348)) << std::endl;
std::cout << (e->insert(418)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (e->insert(308)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
*e=*d;
std::cout << (a->remove(483)) << std::endl;
c->printPretty();
std::cout << (c->insert(360)) << std::endl;
std::cout << (a->insert(122)) << std::endl;
e->printPretty();
std::cout << (d->insert(446)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
a->printPretty();
std::cout << (d->insert(446)) << std::endl;
std::cout << (d->insert(446)) << std::endl;
e->printPretty();
std::cout << (e->remove(416)) << std::endl;
std::cout << (a->remove(281)) << std::endl;
*a=*c;
std::cout << (d->insert(446)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
e->printPretty();
std::cout << (c->remove(360)) << std::endl;
*a=*b;
std::cout << (b->insert(284)) << std::endl;
e->printPretty();
*d=*b;
*d=*b;
std::cout << (d->insert(284)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
std::cout << (e->remove(55)) << std::endl;
a->printPretty();
std::cout << (a->insert(232)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
std::cout << (d->remove(447)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
b->printPretty();
std::cout << (b->insert(284)) << std::endl;
std::cout << (e->insert(290)) << std::endl;
std::cout << (b->remove(348)) << std::endl;
b->printPretty();
std::cout << (a->insert(284)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
std::cout << (d->remove(348)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->insert(348)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (e->remove(290)) << std::endl;
*b=*c;
std::cout << (e->insert(261)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
std::cout << (d->remove(354)) << std::endl;
d->printPretty();
std::cout << (c->insert(406)) << std::endl;
*e=*b;
*b=*a;
d->printPretty();
std::cout << (c->remove(342)) << std::endl;
*b=*c;
*c=*d;
std::cout << (b->remove(258)) << std::endl;
c->printPretty();
std::cout << (d->insert(260)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
*b=*e;
*c=*a;
std::cout << (a->remove(348)) << std::endl;
*c=*b;
*b=*c;
d->printPretty();
a->printPretty();
std::cout << (c->remove(439)) << std::endl;
std::cout << (d->remove(376)) << std::endl;
d->printPretty();
std::cout << (b->remove(121)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
e->printPretty();
std::cout << (a->remove(108)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (e->remove(156)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
std::cout << (b->remove(40)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(331)) << std::endl;
std::cout << (a->remove(110)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
a->printPretty();
std::cout << (e->insert(58)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
e->printPretty();
std::cout << (c->remove(406)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
std::cout << (d->remove(260)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
*e=*e;
std::cout << (a->insert(301)) << std::endl;
std::cout << (b->insert(93)) << std::endl;
std::cout << (c->remove(4)) << std::endl;
e->printPretty();
std::cout << (b->insert(469)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
b->printPretty();
std::cout << (b->insert(242)) << std::endl;
std::cout << (e->remove(346)) << std::endl;
d->printPretty();
std::cout << (d->remove(226)) << std::endl;
a->printPretty();
std::cout << (c->remove(418)) << std::endl;
*c=*e;
std::cout << (c->remove(126)) << std::endl;
std::cout << (b->remove(5)) << std::endl;
a->printPretty();
std::cout << (d->remove(220)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
std::cout << (a->insert(485)) << std::endl;
a->printPretty();
std::cout << (c->remove(331)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (b->remove(195)) << std::endl;
std::cout << (a->remove(485)) << std::endl;
std::cout << (c->insert(58)) << std::endl;
std::cout << (a->remove(301)) << std::endl;
std::cout << (b->insert(469)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
std::cout << (c->remove(291)) << std::endl;
std::cout << (c->remove(58)) << std::endl;
std::cout << (c->remove(406)) << std::endl;
d->printPretty();
std::cout << (e->insert(485)) << std::endl;
*a=*c;
std::cout << (b->remove(142)) << std::endl;
std::cout << (d->insert(95)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (e->insert(485)) << std::endl;
b->printPretty();
std::cout << (a->remove(170)) << std::endl;
std::cout << (c->insert(219)) << std::endl;
std::cout << (b->insert(93)) << std::endl;
d->printPretty();
std::cout << (a->remove(125)) << std::endl;
e->printPretty();
c->printPretty();
b->printPretty();
*e=*d;
*e=*d;
std::cout << (e->remove(284)) << std::endl;
std::cout << (c->remove(219)) << std::endl;
c->printPretty();
std::cout << (b->insert(93)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
std::cout << (b->insert(67)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (b->insert(30)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (a->insert(437)) << std::endl;
*e=*e;
*e=*b;
std::cout << (d->remove(239)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
*e=*c;
std::cout << (c->remove(190)) << std::endl;
a->printPretty();
e->printPretty();
*e=*b;
std::cout << (b->insert(67)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->remove(67)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (e->remove(346)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
std::cout << (e->insert(254)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (d->remove(368)) << std::endl;
*e=*b;
std::cout << (a->insert(239)) << std::endl;
std::cout << (e->insert(242)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (d->remove(138)) << std::endl;
std::cout << (e->insert(309)) << std::endl;
d->printPretty();
std::cout << (b->insert(136)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
std::cout << (a->remove(226)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (d->insert(412)) << std::endl;
c->printPretty();
std::cout << (a->insert(22)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
std::cout << (a->insert(107)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
b->printPretty();
std::cout << (d->remove(232)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
std::cout << (c->remove(468)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
*d=*e;
std::cout << (c->remove(242)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
b->printPretty();
std::cout << (d->remove(432)) << std::endl;
std::cout << (e->remove(75)) << std::endl;
std::cout << (d->insert(235)) << std::endl;
*d=*c;
std::cout << (a->remove(107)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
a->printPretty();
std::cout << (c->remove(192)) << std::endl;
std::cout << (e->remove(367)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
*d=*d;
std::cout << (b->remove(432)) << std::endl;
std::cout << (e->remove(30)) << std::endl;
std::cout << (e->remove(432)) << std::endl;
*e=*a;
std::cout << (e->insert(198)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
std::cout << (d->remove(490)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
std::cout << (c->remove(45)) << std::endl;
*e=*b;
std::cout << (a->insert(47)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (c->remove(78)) << std::endl;
std::cout << (b->remove(219)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
std::cout << (b->insert(335)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
*b=*d;
std::cout << (d->remove(49)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
b->printPretty();
std::cout << (c->insert(491)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
*e=*b;
std::cout << (a->insert(22)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (e->remove(86)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
*e=*e;
*d=*e;
std::cout << (d->remove(104)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->remove(192)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
*e=*e;
*c=*d;
*b=*b;
std::cout << (a->insert(47)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
std::cout << (c->insert(182)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
*a=*b;
std::cout << (e->remove(104)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
b->printPretty();
*b=*c;
a->printPretty();
*a=*c;
std::cout << (c->remove(385)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
*a=*d;
d->printPretty();
b->printPretty();
c->printPretty();
std::cout << (b->remove(226)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
*b=*c;
std::cout << (c->remove(127)) << std::endl;
b->printPretty();
std::cout << (c->insert(14)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
*e=*a;
*d=*c;
std::cout << (b->remove(316)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
std::cout << (a->remove(318)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
b->printPretty();
std::cout << (c->insert(101)) << std::endl;
b->printPretty();
std::cout << (b->remove(323)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
std::cout << (c->remove(88)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
c->printPretty();
std::cout << (d->remove(14)) << std::endl;
b->printPretty();
std::cout << (e->insert(437)) << std::endl;
b->printPretty();
std::cout << (e->remove(437)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
e->printPretty();
std::cout << (b->remove(495)) << std::endl;
a->printPretty();
std::cout << (c->insert(101)) << std::endl;
b->printPretty();
std::cout << (b->insert(357)) << std::endl;
std::cout << (c->remove(101)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (a->remove(196)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
*e=*d;
std::cout << (d->insert(94)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
*b=*c;
a->printPretty();
c->printPretty();
std::cout << (d->insert(94)) << std::endl;
std::cout << (d->remove(94)) << std::endl;
*b=*d;
std::cout << (d->remove(376)) << std::endl;
*d=*c;
*a=*e;
std::cout << (c->insert(60)) << std::endl;
*b=*c;
e->printPretty();
*c=*a;
std::cout << (d->remove(330)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (a->remove(327)) << std::endl;
std::cout << (a->remove(456)) << std::endl;
c->printPretty();
*a=*e;
d->printPretty();
std::cout << (b->insert(213)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (e->insert(60)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
c->printPretty();
std::cout << (e->remove(213)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
*c=*d;
std::cout << (d->insert(397)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (e->remove(60)) << std::endl;
std::cout << (b->insert(213)) << std::endl;
std::cout << (b->remove(213)) << std::endl;
*c=*d;
std::cout << (d->insert(455)) << std::endl;
std::cout << (d->insert(244)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
std::cout << (a->remove(443)) << std::endl;
std::cout << (d->insert(244)) << std::endl;
*b=*a;
b->printPretty();
*b=*b;
*e=*a;
std::cout << (d->insert(455)) << std::endl;
std::cout << (d->remove(335)) << std::endl;
std::cout << (d->insert(361)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
d->printPretty();
std::cout << (a->remove(444)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
d->printPretty();
a->printPretty();
*b=*b;
d->printPretty();
std::cout << (e->remove(147)) << std::endl;
*b=*d;
std::cout << (b->remove(361)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (b->insert(244)) << std::endl;
*c=*a;
std::cout << (c->remove(188)) << std::endl;
d->printPretty();
std::cout << (d->remove(352)) << std::endl;
*d=*e;
std::cout << (c->remove(155)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (e->insert(224)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
std::cout << (e->remove(283)) << std::endl;
d->printPretty();
std::cout << (a->insert(283)) << std::endl;
d->printPretty();
std::cout << (b->remove(244)) << std::endl;
std::cout << (c->remove(280)) << std::endl;
std::cout << (e->insert(224)) << std::endl;
std::cout << (a->remove(367)) << std::endl;
c->printPretty();
std::cout << (a->remove(283)) << std::endl;
*e=*c;
*d=*b;
a->printPretty();
*b=*b;
std::cout << (b->remove(21)) << std::endl;
std::cout << (e->insert(411)) << std::endl;
*d=*a;
std::cout << (e->remove(238)) << std::endl;
*c=*d;
std::cout << (c->remove(60)) << std::endl;
std::cout << (a->remove(410)) << std::endl;
*c=*e;
std::cout << (e->insert(411)) << std::endl;
std::cout << (e->remove(225)) << std::endl;
std::cout << (c->insert(411)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
std::cout << (e->insert(334)) << std::endl;
c->printPretty();
*c=*b;
*b=*b;
std::cout << (d->remove(160)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
d->printPretty();
std::cout << (a->remove(101)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
*b=*a;
std::cout << (b->remove(363)) << std::endl;
a->printPretty();
std::cout << (e->insert(73)) << std::endl;
c->printPretty();
std::cout << (d->insert(298)) << std::endl;
std::cout << (d->insert(298)) << std::endl;
std::cout << (d->remove(298)) << std::endl;
std::cout << (e->insert(478)) << std::endl;
std::cout << (e->insert(88)) << std::endl;
std::cout << (e->insert(203)) << std::endl;
*e=*c;
e->printPretty();
c->printPretty();
d->printPretty();
e->printPretty();
std::cout << (a->remove(195)) << std::endl;
*b=*e;
c->printPretty();
c->printPretty();
*e=*a;
c->printPretty();
e->printPretty();
b->printPretty();
d->printPretty();
*a=*c;
std::cout << (d->insert(429)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (d->insert(429)) << std::endl;
return 0;
}
