#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(214)) << std::endl;
std::cout << (a->insert(214)) << std::endl;
a->printPretty();
std::cout << (a->insert(214)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(260)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->insert(113)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (d->insert(412)) << std::endl;
std::cout << (b->insert(276)) << std::endl;
std::cout << (c->insert(40)) << std::endl;
std::cout << (b->remove(6)) << std::endl;
a->printPretty();
std::cout << (a->insert(96)) << std::endl;
std::cout << (b->remove(304)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (b->insert(412)) << std::endl;
b->printPretty();
std::cout << (e->insert(84)) << std::endl;
std::cout << (b->insert(220)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (b->remove(276)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->remove(122)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
std::cout << (e->remove(247)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
*e=*e;
*c=*a;
std::cout << (d->insert(96)) << std::endl;
std::cout << (d->insert(178)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
*b=*d;
std::cout << (d->remove(473)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
a->printPretty();
std::cout << (c->insert(280)) << std::endl;
d->printPretty();
std::cout << (c->remove(280)) << std::endl;
std::cout << (b->remove(236)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->insert(417)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
*a=*e;
std::cout << (a->insert(258)) << std::endl;
std::cout << (e->remove(84)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (e->insert(379)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
std::cout << (a->insert(101)) << std::endl;
*a=*e;
std::cout << (e->remove(189)) << std::endl;
std::cout << (a->remove(379)) << std::endl;
std::cout << (d->insert(178)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
*c=*e;
*b=*b;
std::cout << (d->remove(418)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (d->insert(270)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
*c=*c;
std::cout << (e->insert(379)) << std::endl;
b->printPretty();
std::cout << (e->insert(258)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
e->printPretty();
std::cout << (c->remove(379)) << std::endl;
std::cout << (b->insert(73)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
e->printPretty();
*d=*d;
a->printPretty();
std::cout << (a->remove(258)) << std::endl;
b->printPretty();
std::cout << (c->insert(258)) << std::endl;
*e=*b;
*e=*e;
std::cout << (c->remove(214)) << std::endl;
*b=*d;
std::cout << (b->remove(107)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
std::cout << (d->remove(178)) << std::endl;
b->printPretty();
a->printPretty();
*a=*e;
e->printPretty();
std::cout << (b->insert(245)) << std::endl;
b->printPretty();
std::cout << (b->remove(106)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
b->printPretty();
*a=*c;
*c=*c;
a->printPretty();
std::cout << (b->remove(245)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
*e=*e;
std::cout << (d->insert(276)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
c->printPretty();
std::cout << (d->remove(276)) << std::endl;
*c=*d;
std::cout << (e->remove(81)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
*c=*b;
std::cout << (b->remove(130)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
*c=*a;
*c=*d;
std::cout << (e->insert(329)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
d->printPretty();
std::cout << (e->insert(274)) << std::endl;
std::cout << (d->remove(160)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
a->printPretty();
std::cout << (d->insert(305)) << std::endl;
std::cout << (c->insert(216)) << std::endl;
*b=*a;
*c=*a;
*c=*e;
std::cout << (b->remove(174)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (c->remove(461)) << std::endl;
std::cout << (e->insert(73)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
*a=*e;
*d=*d;
*a=*d;
std::cout << (a->remove(262)) << std::endl;
*b=*e;
std::cout << (d->remove(262)) << std::endl;
std::cout << (a->remove(270)) << std::endl;
*b=*b;
std::cout << (a->remove(293)) << std::endl;
b->printPretty();
std::cout << (b->remove(315)) << std::endl;
*b=*a;
std::cout << (c->insert(84)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
a->printPretty();
std::cout << (e->insert(401)) << std::endl;
std::cout << (a->insert(4)) << std::endl;
*c=*a;
a->printPretty();
std::cout << (d->remove(267)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
a->printPretty();
std::cout << (b->insert(305)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->remove(483)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (d->remove(58)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(84)) << std::endl;
a->printPretty();
std::cout << (b->insert(308)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (e->remove(401)) << std::endl;
*d=*a;
*a=*b;
*d=*d;
b->printPretty();
e->printPretty();
*e=*e;
std::cout << (d->remove(229)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->insert(85)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (b->remove(482)) << std::endl;
std::cout << (a->remove(305)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
std::cout << (d->remove(111)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (e->remove(360)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
std::cout << (e->insert(318)) << std::endl;
std::cout << (a->insert(82)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
a->printPretty();
std::cout << (b->remove(305)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (c->insert(305)) << std::endl;
*a=*e;
std::cout << (c->remove(305)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (c->remove(4)) << std::endl;
a->printPretty();
a->printPretty();
a->printPretty();
*a=*e;
*b=*b;
std::cout << (d->remove(152)) << std::endl;
b->printPretty();
b->printPretty();
*c=*e;
a->printPretty();
*c=*c;
std::cout << (a->insert(111)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (a->remove(80)) << std::endl;
c->printPretty();
std::cout << (e->insert(170)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
std::cout << (d->insert(305)) << std::endl;
*a=*c;
std::cout << (c->remove(374)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
*a=*a;
*b=*a;
*e=*e;
std::cout << (a->insert(363)) << std::endl;
*d=*b;
std::cout << (e->insert(22)) << std::endl;
std::cout << (d->insert(468)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (e->insert(111)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (e->insert(28)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
std::cout << (a->insert(273)) << std::endl;
std::cout << (c->remove(318)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
std::cout << (a->remove(329)) << std::endl;
std::cout << (b->insert(303)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
a->printPretty();
std::cout << (a->insert(273)) << std::endl;
*c=*c;
*d=*c;
std::cout << (e->insert(167)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
std::cout << (e->remove(159)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (a->remove(291)) << std::endl;
*d=*d;
std::cout << (e->remove(427)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (d->remove(351)) << std::endl;
*d=*c;
std::cout << (e->remove(329)) << std::endl;
std::cout << (b->remove(245)) << std::endl;
std::cout << (d->insert(298)) << std::endl;
c->printPretty();
std::cout << (b->remove(382)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (b->insert(28)) << std::endl;
std::cout << (a->insert(179)) << std::endl;
std::cout << (b->remove(329)) << std::endl;
std::cout << (a->remove(274)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (b->insert(170)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
*d=*b;
b->printPretty();
std::cout << (c->insert(12)) << std::endl;
std::cout << (c->remove(12)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (c->insert(431)) << std::endl;
std::cout << (e->remove(108)) << std::endl;
c->printPretty();
e->printPretty();
b->printPretty();
*e=*d;
std::cout << (e->remove(73)) << std::endl;
e->printPretty();
std::cout << (c->remove(410)) << std::endl;
a->printPretty();
std::cout << (d->remove(170)) << std::endl;
std::cout << (e->insert(151)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
std::cout << (b->remove(416)) << std::endl;
*e=*c;
std::cout << (b->remove(318)) << std::endl;
*c=*c;
std::cout << (a->remove(298)) << std::endl;
std::cout << (c->remove(349)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
a->printPretty();
std::cout << (c->insert(201)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(307)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
c->printPretty();
std::cout << (e->insert(111)) << std::endl;
std::cout << (a->remove(329)) << std::endl;
std::cout << (b->insert(73)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
std::cout << (d->remove(427)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(222)) << std::endl;
std::cout << (c->remove(443)) << std::endl;
b->printPretty();
std::cout << (d->insert(318)) << std::endl;
e->printPretty();
*b=*d;
std::cout << (c->remove(78)) << std::endl;
std::cout << (d->remove(476)) << std::endl;
a->printPretty();
std::cout << (d->remove(73)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
std::cout << (c->remove(341)) << std::endl;
b->printPretty();
std::cout << (c->insert(402)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
std::cout << (d->insert(255)) << std::endl;
e->printPretty();
*e=*c;
*e=*c;
d->printPretty();
std::cout << (d->insert(119)) << std::endl;
*d=*a;
std::cout << (b->remove(419)) << std::endl;
e->printPretty();
std::cout << (e->remove(201)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
c->printPretty();
std::cout << (c->insert(439)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
std::cout << (e->insert(402)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (d->insert(181)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
*c=*e;
std::cout << (b->remove(380)) << std::endl;
std::cout << (b->remove(185)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
b->printPretty();
std::cout << (b->insert(22)) << std::endl;
b->printPretty();
std::cout << (a->remove(196)) << std::endl;
std::cout << (b->remove(485)) << std::endl;
b->printPretty();
d->printPretty();
*a=*e;
std::cout << (d->remove(181)) << std::endl;
*c=*a;
a->printPretty();
e->printPretty();
b->printPretty();
std::cout << (b->remove(167)) << std::endl;
c->printPretty();
std::cout << (d->insert(157)) << std::endl;
*e=*a;
*b=*d;
*c=*d;
std::cout << (d->remove(294)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (d->insert(266)) << std::endl;
*a=*d;
std::cout << (d->insert(157)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (e->insert(439)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
d->printPretty();
std::cout << (e->insert(163)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (e->remove(303)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (a->remove(34)) << std::endl;
std::cout << (a->insert(439)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
*c=*d;
e->printPretty();
*a=*c;
std::cout << (d->remove(157)) << std::endl;
*b=*e;
a->printPretty();
*b=*d;
std::cout << (c->remove(55)) << std::endl;
*c=*c;
std::cout << (b->remove(266)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
*b=*c;
std::cout << (b->insert(433)) << std::endl;
std::cout << (e->remove(12)) << std::endl;
std::cout << (b->insert(433)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
c->printPretty();
std::cout << (b->remove(157)) << std::endl;
*b=*b;
a->printPretty();
std::cout << (e->remove(280)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->insert(310)) << std::endl;
c->printPretty();
std::cout << (e->insert(199)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (c->insert(439)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (c->insert(258)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
a->printPretty();
std::cout << (b->insert(13)) << std::endl;
std::cout << (a->insert(157)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (d->insert(157)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
std::cout << (b->remove(266)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
*a=*b;
std::cout << (d->insert(266)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
*a=*e;
std::cout << (d->remove(43)) << std::endl;
std::cout << (d->remove(134)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (d->remove(98)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (d->insert(266)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
b->printPretty();
std::cout << (a->insert(291)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
std::cout << (b->remove(490)) << std::endl;
*e=*c;
std::cout << (e->remove(287)) << std::endl;
*d=*d;
std::cout << (e->insert(111)) << std::endl;
std::cout << (c->remove(268)) << std::endl;
std::cout << (a->remove(291)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
a->printPretty();
std::cout << (c->insert(449)) << std::endl;
std::cout << (d->insert(397)) << std::endl;
e->printPretty();
std::cout << (b->remove(433)) << std::endl;
d->printPretty();
std::cout << (e->insert(258)) << std::endl;
std::cout << (c->insert(188)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (a->insert(311)) << std::endl;
b->printPretty();
std::cout << (c->insert(379)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (d->remove(111)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
b->printPretty();
e->printPretty();
c->printPretty();
*e=*c;
*a=*c;
std::cout << (e->remove(90)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
*e=*a;
d->printPretty();
a->printPretty();
std::cout << (c->insert(69)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (a->remove(115)) << std::endl;
e->printPretty();
std::cout << (c->insert(308)) << std::endl;
std::cout << (a->insert(249)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
*c=*b;
std::cout << (c->insert(17)) << std::endl;
d->printPretty();
std::cout << (c->insert(227)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
a->printPretty();
std::cout << (d->insert(346)) << std::endl;
c->printPretty();
std::cout << (b->insert(452)) << std::endl;
*d=*c;
std::cout << (d->remove(481)) << std::endl;
e->printPretty();
std::cout << (a->remove(299)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (b->insert(461)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
std::cout << (e->remove(28)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
e->printPretty();
std::cout << (c->remove(227)) << std::endl;
a->printPretty();
std::cout << (c->insert(439)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (c->remove(439)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (e->insert(55)) << std::endl;
std::cout << (b->remove(400)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->insert(17)) << std::endl;
std::cout << (b->remove(173)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (b->remove(89)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
*e=*d;
*e=*a;
std::cout << (b->insert(109)) << std::endl;
std::cout << (a->remove(188)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
std::cout << (a->insert(157)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
*e=*a;
std::cout << (b->insert(183)) << std::endl;
d->printPretty();
std::cout << (c->insert(141)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
*b=*e;
std::cout << (e->insert(157)) << std::endl;
*b=*a;
std::cout << (c->remove(332)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (a->remove(191)) << std::endl;
a->printPretty();
std::cout << (a->remove(439)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->remove(386)) << std::endl;
e->printPretty();
std::cout << (d->insert(444)) << std::endl;
*d=*b;
b->printPretty();
d->printPretty();
std::cout << (e->insert(112)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (b->remove(141)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (d->insert(141)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (a->insert(249)) << std::endl;
std::cout << (b->remove(419)) << std::endl;
*e=*e;
std::cout << (a->insert(299)) << std::endl;
b->printPretty();
std::cout << (a->insert(448)) << std::endl;
std::cout << (b->insert(482)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
d->printPretty();
std::cout << (b->insert(151)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
*e=*e;
std::cout << (b->remove(364)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
*a=*e;
std::cout << (b->remove(151)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (c->remove(141)) << std::endl;
d->printPretty();
std::cout << (c->insert(270)) << std::endl;
d->printPretty();
e->printPretty();
*d=*e;
std::cout << (c->remove(359)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
*c=*e;
std::cout << (a->remove(343)) << std::endl;
*b=*c;
std::cout << (d->remove(157)) << std::endl;
std::cout << (a->insert(249)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
std::cout << (c->insert(97)) << std::endl;
std::cout << (b->remove(314)) << std::endl;
std::cout << (c->remove(258)) << std::endl;
*e=*d;
std::cout << (c->insert(449)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
std::cout << (c->remove(495)) << std::endl;
std::cout << (d->insert(249)) << std::endl;
b->printPretty();
std::cout << (d->remove(439)) << std::endl;
e->printPretty();
std::cout << (a->insert(71)) << std::endl;
*a=*d;
d->printPretty();
d->printPretty();
*d=*e;
b->printPretty();
std::cout << (a->insert(179)) << std::endl;
std::cout << (b->remove(100)) << std::endl;
std::cout << (e->insert(439)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
std::cout << (a->insert(494)) << std::endl;
*c=*c;
*a=*b;
std::cout << (b->remove(266)) << std::endl;
std::cout << (d->remove(282)) << std::endl;
d->printPretty();
std::cout << (d->insert(193)) << std::endl;
std::cout << (c->insert(160)) << std::endl;
std::cout << (a->remove(409)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
c->printPretty();
b->printPretty();
*a=*c;
std::cout << (d->remove(388)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
*d=*a;
std::cout << (d->remove(449)) << std::endl;
std::cout << (e->remove(112)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
*a=*b;
*b=*a;
std::cout << (c->remove(71)) << std::endl;
std::cout << (c->remove(405)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
std::cout << (c->remove(359)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (d->remove(359)) << std::endl;
std::cout << (b->insert(417)) << std::endl;
a->printPretty();
std::cout << (a->insert(112)) << std::endl;
b->printPretty();
std::cout << (e->remove(241)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
*b=*a;
std::cout << (b->insert(435)) << std::endl;
std::cout << (b->insert(112)) << std::endl;
*d=*a;
std::cout << (e->insert(224)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
return 0;
}
