#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
std::cout << (a->remove(119)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
std::cout << (a->insert(98)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
std::cout << (a->insert(180)) << std::endl;
std::cout << (a->insert(98)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (a->insert(86)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
*c=*a;
b->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (b->insert(480)) << std::endl;
e->printPretty();
std::cout << (b->insert(382)) << std::endl;
*b=*c;
a->printPretty();
std::cout << (c->remove(359)) << std::endl;
std::cout << (d->insert(348)) << std::endl;
std::cout << (b->remove(232)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
*e=*c;
std::cout << (d->remove(348)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
e->printPretty();
std::cout << (e->remove(234)) << std::endl;
b->printPretty();
*c=*c;
c->printPretty();
d->printPretty();
e->printPretty();
*a=*d;
c->printPretty();
std::cout << (b->insert(352)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (c->insert(98)) << std::endl;
std::cout << (d->remove(193)) << std::endl;
std::cout << (e->insert(217)) << std::endl;
a->printPretty();
std::cout << (e->remove(40)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
*e=*a;
std::cout << (e->remove(394)) << std::endl;
*a=*c;
*d=*c;
std::cout << (c->remove(86)) << std::endl;
std::cout << (b->remove(180)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
*e=*b;
std::cout << (b->insert(86)) << std::endl;
a->printPretty();
std::cout << (a->insert(460)) << std::endl;
a->printPretty();
std::cout << (b->insert(86)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (b->remove(98)) << std::endl;
*e=*d;
std::cout << (a->insert(86)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (b->remove(273)) << std::endl;
std::cout << (e->insert(98)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
std::cout << (e->remove(98)) << std::endl;
std::cout << (c->remove(98)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (e->insert(409)) << std::endl;
*e=*a;
std::cout << (d->remove(98)) << std::endl;
std::cout << (b->remove(260)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
*e=*b;
std::cout << (c->remove(460)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
std::cout << (e->insert(124)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
d->printPretty();
std::cout << (c->insert(31)) << std::endl;
b->printPretty();
std::cout << (e->insert(359)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
a->printPretty();
std::cout << (d->remove(86)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
std::cout << (c->remove(267)) << std::endl;
std::cout << (e->insert(124)) << std::endl;
std::cout << (c->insert(134)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->insert(201)) << std::endl;
std::cout << (e->remove(124)) << std::endl;
b->printPretty();
std::cout << (e->remove(86)) << std::endl;
std::cout << (e->remove(284)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
std::cout << (d->insert(499)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (a->insert(190)) << std::endl;
*a=*c;
std::cout << (d->insert(1)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (b->insert(359)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
*d=*c;
std::cout << (b->insert(489)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->insert(392)) << std::endl;
std::cout << (c->remove(31)) << std::endl;
std::cout << (c->insert(134)) << std::endl;
*e=*a;
d->printPretty();
std::cout << (a->insert(392)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
c->printPretty();
std::cout << (c->remove(294)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->insert(392)) << std::endl;
std::cout << (e->insert(392)) << std::endl;
c->printPretty();
std::cout << (d->remove(134)) << std::endl;
std::cout << (e->insert(303)) << std::endl;
*b=*c;
std::cout << (c->insert(105)) << std::endl;
std::cout << (b->remove(201)) << std::endl;
std::cout << (b->insert(66)) << std::endl;
c->printPretty();
std::cout << (a->remove(262)) << std::endl;
std::cout << (d->insert(383)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
*d=*e;
a->printPretty();
a->printPretty();
*d=*d;
*c=*c;
*e=*c;
std::cout << (d->insert(233)) << std::endl;
*b=*c;
std::cout << (d->remove(201)) << std::endl;
*e=*d;
*a=*c;
*e=*b;
std::cout << (c->remove(134)) << std::endl;
*c=*b;
std::cout << (d->insert(31)) << std::endl;
b->printPretty();
std::cout << (b->remove(105)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
*b=*d;
std::cout << (d->insert(374)) << std::endl;
*e=*d;
std::cout << (c->remove(215)) << std::endl;
a->printPretty();
std::cout << (d->insert(403)) << std::endl;
*a=*c;
std::cout << (e->insert(233)) << std::endl;
std::cout << (b->insert(392)) << std::endl;
std::cout << (e->remove(374)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
*e=*c;
std::cout << (c->insert(176)) << std::endl;
std::cout << (c->insert(407)) << std::endl;
std::cout << (d->remove(100)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (b->insert(177)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
a->printPretty();
std::cout << (a->insert(295)) << std::endl;
*c=*e;
*c=*b;
std::cout << (c->insert(278)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (c->insert(325)) << std::endl;
*c=*b;
*d=*c;
*d=*d;
a->printPretty();
std::cout << (e->remove(134)) << std::endl;
std::cout << (c->insert(272)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (e->remove(201)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (b->remove(392)) << std::endl;
std::cout << (e->insert(412)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (a->remove(269)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
std::cout << (c->remove(160)) << std::endl;
a->printPretty();
c->printPretty();
*e=*e;
*a=*b;
std::cout << (e->remove(292)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
std::cout << (e->insert(412)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
std::cout << (a->insert(177)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
*e=*d;
std::cout << (a->insert(160)) << std::endl;
std::cout << (a->insert(136)) << std::endl;
std::cout << (e->remove(177)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
std::cout << (b->remove(177)) << std::endl;
std::cout << (d->insert(48)) << std::endl;
*d=*e;
std::cout << (a->insert(233)) << std::endl;
std::cout << (a->remove(136)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (b->remove(31)) << std::endl;
std::cout << (c->remove(31)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (d->insert(303)) << std::endl;
e->printPretty();
std::cout << (a->insert(376)) << std::endl;
*d=*c;
std::cout << (e->insert(234)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
*c=*d;
std::cout << (d->remove(122)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
e->printPretty();
std::cout << (b->remove(500)) << std::endl;
e->printPretty();
std::cout << (d->insert(31)) << std::endl;
b->printPretty();
d->printPretty();
d->printPretty();
std::cout << (e->insert(190)) << std::endl;
std::cout << (a->remove(68)) << std::endl;
std::cout << (a->remove(5)) << std::endl;
*d=*b;
std::cout << (c->insert(460)) << std::endl;
std::cout << (a->insert(177)) << std::endl;
*a=*b;
std::cout << (c->remove(163)) << std::endl;
c->printPretty();
std::cout << (b->insert(2)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
*b=*e;
std::cout << (a->insert(303)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (b->remove(31)) << std::endl;
*b=*c;
*a=*d;
std::cout << (e->remove(86)) << std::endl;
std::cout << (e->insert(303)) << std::endl;
*e=*a;
std::cout << (d->remove(260)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
std::cout << (c->remove(98)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (b->insert(31)) << std::endl;
std::cout << (b->insert(173)) << std::endl;
std::cout << (d->remove(282)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
*e=*e;
std::cout << (d->insert(303)) << std::endl;
std::cout << (a->insert(164)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
std::cout << (d->remove(79)) << std::endl;
std::cout << (b->insert(31)) << std::endl;
*b=*a;
std::cout << (e->remove(197)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (d->remove(303)) << std::endl;
std::cout << (e->insert(75)) << std::endl;
*a=*d;
std::cout << (a->insert(475)) << std::endl;
*b=*b;
*e=*b;
std::cout << (d->remove(265)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (c->insert(164)) << std::endl;
std::cout << (b->remove(120)) << std::endl;
a->printPretty();
std::cout << (b->insert(303)) << std::endl;
*d=*a;
std::cout << (e->remove(233)) << std::endl;
std::cout << (b->insert(164)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (c->insert(193)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (b->insert(10)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
std::cout << (d->insert(233)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
*a=*d;
std::cout << (a->remove(475)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
a->printPretty();
std::cout << (e->remove(393)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->remove(10)) << std::endl;
*c=*a;
std::cout << (c->remove(240)) << std::endl;
*c=*d;
std::cout << (b->remove(233)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
*c=*e;
std::cout << (b->insert(160)) << std::endl;
std::cout << (e->insert(438)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
a->printPretty();
std::cout << (b->insert(160)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (d->remove(475)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
*d=*d;
*e=*a;
b->printPretty();
std::cout << (e->insert(22)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (a->remove(233)) << std::endl;
std::cout << (b->remove(160)) << std::endl;
*e=*d;
std::cout << (b->insert(448)) << std::endl;
*e=*c;
std::cout << (a->remove(164)) << std::endl;
std::cout << (c->remove(135)) << std::endl;
*e=*d;
std::cout << (b->remove(453)) << std::endl;
d->printPretty();
std::cout << (d->remove(235)) << std::endl;
e->printPretty();
std::cout << (b->insert(448)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (c->insert(303)) << std::endl;
d->printPretty();
d->printPretty();
d->printPretty();
e->printPretty();
std::cout << (a->insert(441)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->remove(441)) << std::endl;
std::cout << (b->insert(208)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
c->printPretty();
std::cout << (e->insert(387)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->remove(336)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
c->printPretty();
std::cout << (b->insert(138)) << std::endl;
*a=*c;
std::cout << (a->insert(219)) << std::endl;
std::cout << (c->remove(341)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
*c=*c;
std::cout << (d->insert(196)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
*c=*a;
a->printPretty();
a->printPretty();
std::cout << (c->remove(431)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (d->insert(142)) << std::endl;
d->printPretty();
std::cout << (c->insert(459)) << std::endl;
c->printPretty();
std::cout << (e->insert(11)) << std::endl;
b->printPretty();
std::cout << (b->remove(363)) << std::endl;
c->printPretty();
e->printPretty();
*d=*b;
std::cout << (e->insert(196)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
*a=*e;
std::cout << (b->insert(6)) << std::endl;
*a=*a;
std::cout << (c->remove(357)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (e->remove(70)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
std::cout << (c->remove(375)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
std::cout << (e->insert(188)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (c->insert(129)) << std::endl;
e->printPretty();
std::cout << (d->insert(19)) << std::endl;
std::cout << (e->remove(11)) << std::endl;
std::cout << (a->remove(164)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (c->remove(106)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (d->insert(499)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
e->printPretty();
*a=*a;
std::cout << (b->remove(138)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (e->insert(429)) << std::endl;
*d=*e;
std::cout << (d->remove(164)) << std::endl;
*e=*d;
*d=*c;
std::cout << (e->remove(392)) << std::endl;
std::cout << (a->remove(243)) << std::endl;
std::cout << (d->insert(344)) << std::endl;
std::cout << (d->remove(89)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
std::cout << (d->remove(39)) << std::endl;
e->printPretty();
std::cout << (c->insert(284)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
*b=*b;
*d=*c;
std::cout << (e->remove(429)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (c->remove(447)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
*d=*b;
std::cout << (e->remove(404)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(284)) << std::endl;
*a=*b;
std::cout << (c->remove(19)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (b->remove(284)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (b->insert(208)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (a->insert(221)) << std::endl;
*e=*d;
std::cout << (b->insert(208)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (a->insert(48)) << std::endl;
a->printPretty();
*e=*d;
*c=*b;
std::cout << (c->insert(235)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
std::cout << (d->insert(387)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
*b=*e;
std::cout << (c->remove(6)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (c->remove(51)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
*c=*b;
std::cout << (d->insert(6)) << std::endl;
*c=*c;
std::cout << (d->remove(284)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
a->printPretty();
std::cout << (e->remove(492)) << std::endl;
std::cout << (d->insert(117)) << std::endl;
*a=*d;
a->printPretty();
c->printPretty();
d->printPretty();
std::cout << (a->remove(241)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
*e=*d;
std::cout << (c->remove(93)) << std::endl;
std::cout << (c->insert(364)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (d->remove(235)) << std::endl;
std::cout << (e->remove(272)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (d->remove(6)) << std::endl;
std::cout << (d->insert(387)) << std::endl;
std::cout << (c->remove(94)) << std::endl;
*d=*c;
*c=*b;
std::cout << (d->insert(284)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
*b=*d;
std::cout << (b->insert(39)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
std::cout << (a->insert(457)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (e->insert(152)) << std::endl;
b->printPretty();
std::cout << (c->insert(150)) << std::endl;
std::cout << (d->remove(317)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
std::cout << (d->remove(51)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (a->insert(425)) << std::endl;
*d=*b;
std::cout << (a->remove(84)) << std::endl;
b->printPretty();
std::cout << (a->remove(156)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
std::cout << (e->insert(402)) << std::endl;
std::cout << (c->insert(6)) << std::endl;
std::cout << (b->insert(31)) << std::endl;
*c=*c;
std::cout << (d->insert(112)) << std::endl;
std::cout << (e->remove(6)) << std::endl;
std::cout << (e->remove(402)) << std::endl;
a->printPretty();
std::cout << (a->insert(473)) << std::endl;
std::cout << (e->remove(208)) << std::endl;
a->printPretty();
std::cout << (d->insert(284)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
e->printPretty();
std::cout << (e->remove(396)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
std::cout << (c->insert(364)) << std::endl;
std::cout << (a->remove(333)) << std::endl;
*d=*a;
e->printPretty();
*b=*d;
b->printPretty();
*c=*d;
std::cout << (d->insert(448)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
*d=*c;
std::cout << (a->insert(173)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
c->printPretty();
std::cout << (a->remove(37)) << std::endl;
std::cout << (c->remove(308)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(117)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
std::cout << (d->insert(118)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
*e=*d;
std::cout << (b->insert(117)) << std::endl;
*a=*b;
std::cout << (a->remove(233)) << std::endl;
*b=*e;
std::cout << (c->insert(196)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
*d=*b;
std::cout << (a->insert(6)) << std::endl;
e->printPretty();
std::cout << (c->remove(81)) << std::endl;
*b=*a;
std::cout << (a->remove(66)) << std::endl;
a->printPretty();
std::cout << (a->remove(210)) << std::endl;
a->printPretty();
std::cout << (c->remove(82)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
*b=*a;
std::cout << (e->insert(468)) << std::endl;
d->printPretty();
std::cout << (b->remove(235)) << std::endl;
b->printPretty();
*d=*c;
*c=*d;
std::cout << (d->remove(56)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
std::cout << (b->remove(117)) << std::endl;
*e=*d;
*d=*d;
b->printPretty();
std::cout << (a->insert(6)) << std::endl;
c->printPretty();
std::cout << (a->insert(235)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (c->remove(138)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
std::cout << (b->remove(376)) << std::endl;
*d=*d;
std::cout << (c->insert(491)) << std::endl;
*c=*e;
*e=*c;
std::cout << (e->remove(126)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (d->insert(196)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
std::cout << (e->remove(6)) << std::endl;
std::cout << (d->insert(100)) << std::endl;
a->printPretty();
std::cout << (e->remove(425)) << std::endl;
std::cout << (b->remove(435)) << std::endl;
std::cout << (c->remove(321)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (a->insert(124)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
b->printPretty();
std::cout << (c->insert(360)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (a->remove(124)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
std::cout << (d->remove(425)) << std::endl;
std::cout << (b->remove(490)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
*d=*c;
a->printPretty();
e->printPretty();
std::cout << (c->insert(413)) << std::endl;
std::cout << (c->remove(34)) << std::endl;
std::cout << (b->remove(30)) << std::endl;
std::cout << (b->remove(202)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
std::cout << (a->remove(299)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (b->remove(93)) << std::endl;
b->printPretty();
*a=*b;
*d=*c;
c->printPretty();
*a=*a;
*a=*d;
std::cout << (a->insert(413)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
std::cout << (c->insert(6)) << std::endl;
b->printPretty();
std::cout << (b->remove(252)) << std::endl;
std::cout << (d->remove(17)) << std::endl;
std::cout << (a->remove(480)) << std::endl;
std::cout << (c->remove(117)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (d->remove(196)) << std::endl;
std::cout << (c->remove(223)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->insert(117)) << std::endl;
*b=*a;
std::cout << (c->insert(425)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
*b=*d;
return 0;
}
