#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(92)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
*b=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (b->insert(293)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (b->insert(7)) << std::endl;
*c=*b;
std::cout << (d->insert(466)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
*b=*a;
std::cout << (b->insert(92)) << std::endl;
std::cout << (e->insert(464)) << std::endl;
*e=*d;
std::cout << (a->insert(241)) << std::endl;
c->printPretty();
std::cout << (c->insert(302)) << std::endl;
std::cout << (d->insert(168)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
b->printPretty();
std::cout << (a->insert(481)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
std::cout << (e->insert(331)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
b->printPretty();
std::cout << (c->remove(7)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (d->insert(185)) << std::endl;
b->printPretty();
*b=*e;
b->printPretty();
d->printPretty();
std::cout << (a->remove(92)) << std::endl;
std::cout << (c->remove(302)) << std::endl;
c->printPretty();
std::cout << (a->remove(189)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
std::cout << (e->insert(158)) << std::endl;
c->printPretty();
std::cout << (d->insert(185)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
d->printPretty();
std::cout << (e->insert(466)) << std::endl;
*c=*c;
std::cout << (b->remove(466)) << std::endl;
*e=*a;
std::cout << (b->remove(481)) << std::endl;
std::cout << (d->remove(168)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
*b=*d;
std::cout << (a->insert(36)) << std::endl;
std::cout << (c->remove(37)) << std::endl;
std::cout << (b->remove(185)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (e->insert(310)) << std::endl;
*b=*b;
std::cout << (d->remove(487)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
*a=*d;
std::cout << (e->insert(86)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (c->insert(35)) << std::endl;
std::cout << (e->insert(481)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
*e=*b;
std::cout << (a->remove(481)) << std::endl;
*b=*a;
*c=*a;
*d=*b;
std::cout << (b->insert(241)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
std::cout << (e->insert(311)) << std::endl;
std::cout << (e->insert(466)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
std::cout << (c->remove(396)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
d->printPretty();
std::cout << (b->remove(241)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (e->remove(14)) << std::endl;
c->printPretty();
d->printPretty();
b->printPretty();
std::cout << (d->insert(220)) << std::endl;
std::cout << (e->remove(413)) << std::endl;
std::cout << (b->insert(476)) << std::endl;
a->printPretty();
std::cout << (b->insert(450)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(486)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (d->remove(243)) << std::endl;
c->printPretty();
std::cout << (a->insert(363)) << std::endl;
e->printPretty();
std::cout << (a->remove(246)) << std::endl;
*e=*b;
std::cout << (d->remove(238)) << std::endl;
std::cout << (c->remove(213)) << std::endl;
*d=*a;
std::cout << (c->insert(391)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
*c=*c;
*c=*a;
std::cout << (c->remove(203)) << std::endl;
std::cout << (c->insert(363)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (a->insert(103)) << std::endl;
*d=*d;
std::cout << (e->remove(479)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (e->remove(433)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
d->printPretty();
std::cout << (c->remove(199)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(489)) << std::endl;
d->printPretty();
std::cout << (c->remove(438)) << std::endl;
std::cout << (c->insert(363)) << std::endl;
std::cout << (c->insert(363)) << std::endl;
b->printPretty();
d->printPretty();
b->printPretty();
std::cout << (e->remove(489)) << std::endl;
*b=*d;
std::cout << (d->remove(340)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
std::cout << (d->insert(224)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
d->printPretty();
std::cout << (b->insert(182)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (a->remove(281)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
*a=*e;
*e=*d;
*e=*b;
std::cout << (e->insert(341)) << std::endl;
std::cout << (d->remove(224)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (a->insert(185)) << std::endl;
std::cout << (a->remove(185)) << std::endl;
std::cout << (d->remove(464)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
*b=*a;
std::cout << (b->remove(319)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (d->remove(363)) << std::endl;
*c=*e;
std::cout << (c->insert(181)) << std::endl;
std::cout << (e->insert(363)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (d->remove(339)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->remove(88)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (b->remove(262)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
a->printPretty();
std::cout << (c->insert(182)) << std::endl;
*d=*b;
std::cout << (e->remove(363)) << std::endl;
*a=*b;
std::cout << (d->insert(272)) << std::endl;
b->printPretty();
b->printPretty();
a->printPretty();
e->printPretty();
std::cout << (a->remove(317)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (a->insert(91)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
c->printPretty();
c->printPretty();
e->printPretty();
std::cout << (a->insert(219)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
*b=*a;
std::cout << (e->insert(451)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
*c=*c;
d->printPretty();
c->printPretty();
std::cout << (c->insert(181)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
*c=*a;
*d=*a;
b->printPretty();
e->printPretty();
std::cout << (c->insert(152)) << std::endl;
a->printPretty();
std::cout << (e->insert(453)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
std::cout << (c->remove(91)) << std::endl;
c->printPretty();
e->printPretty();
*c=*c;
std::cout << (b->remove(322)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
std::cout << (b->remove(390)) << std::endl;
std::cout << (a->insert(70)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (b->remove(113)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (a->remove(53)) << std::endl;
std::cout << (e->remove(3)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
std::cout << (e->insert(409)) << std::endl;
std::cout << (e->remove(453)) << std::endl;
std::cout << (d->remove(91)) << std::endl;
std::cout << (b->remove(91)) << std::endl;
std::cout << (d->insert(130)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
std::cout << (d->insert(130)) << std::endl;
std::cout << (d->insert(130)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
c->printPretty();
std::cout << (d->remove(130)) << std::endl;
*e=*a;
std::cout << (d->insert(408)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
std::cout << (d->insert(408)) << std::endl;
a->printPretty();
std::cout << (e->insert(438)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
*b=*a;
std::cout << (a->insert(221)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (e->remove(228)) << std::endl;
std::cout << (d->insert(305)) << std::endl;
*a=*a;
std::cout << (a->insert(481)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->remove(358)) << std::endl;
std::cout << (d->remove(408)) << std::endl;
b->printPretty();
std::cout << (e->insert(152)) << std::endl;
std::cout << (b->insert(46)) << std::endl;
a->printPretty();
std::cout << (a->remove(197)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->remove(318)) << std::endl;
std::cout << (a->remove(130)) << std::endl;
std::cout << (d->remove(305)) << std::endl;
*a=*a;
std::cout << (a->remove(494)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
e->printPretty();
std::cout << (b->insert(340)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (c->insert(219)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
*a=*b;
std::cout << (d->remove(377)) << std::endl;
std::cout << (c->remove(213)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
d->printPretty();
std::cout << (c->insert(358)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (b->insert(340)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
*e=*c;
std::cout << (e->remove(309)) << std::endl;
std::cout << (b->remove(187)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (d->remove(5)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (c->remove(297)) << std::endl;
std::cout << (d->insert(341)) << std::endl;
c->printPretty();
std::cout << (a->insert(228)) << std::endl;
d->printPretty();
std::cout << (d->remove(39)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (e->insert(481)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
std::cout << (d->remove(63)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
*a=*d;
*b=*e;
*e=*e;
*d=*a;
std::cout << (d->remove(21)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
a->printPretty();
*c=*c;
*b=*e;
std::cout << (d->insert(299)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (e->remove(297)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
*c=*e;
std::cout << (d->insert(341)) << std::endl;
*d=*e;
e->printPretty();
std::cout << (c->remove(323)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
*d=*d;
std::cout << (a->insert(468)) << std::endl;
e->printPretty();
std::cout << (a->insert(264)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (e->remove(341)) << std::endl;
std::cout << (c->remove(216)) << std::endl;
*e=*d;
std::cout << (c->insert(250)) << std::endl;
*b=*e;
*c=*d;
std::cout << (c->insert(238)) << std::endl;
std::cout << (a->remove(45)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
*a=*a;
std::cout << (b->remove(361)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (e->remove(238)) << std::endl;
d->printPretty();
std::cout << (c->insert(238)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (c->remove(238)) << std::endl;
*b=*c;
std::cout << (a->insert(264)) << std::endl;
std::cout << (d->remove(459)) << std::endl;
*b=*b;
std::cout << (d->remove(64)) << std::endl;
*a=*d;
std::cout << (d->remove(54)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (a->insert(52)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
a->printPretty();
b->printPretty();
e->printPretty();
std::cout << (a->insert(52)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
b->printPretty();
*e=*e;
e->printPretty();
std::cout << (e->insert(423)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (c->insert(88)) << std::endl;
std::cout << (c->remove(88)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
*a=*b;
std::cout << (a->remove(462)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
*e=*d;
std::cout << (d->insert(328)) << std::endl;
b->printPretty();
std::cout << (d->remove(103)) << std::endl;
*a=*a;
std::cout << (d->remove(328)) << std::endl;
*b=*b;
std::cout << (a->remove(444)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
c->printPretty();
std::cout << (e->insert(465)) << std::endl;
std::cout << (b->insert(256)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->remove(249)) << std::endl;
std::cout << (e->insert(328)) << std::endl;
std::cout << (c->insert(32)) << std::endl;
*d=*d;
*c=*b;
d->printPretty();
*b=*a;
std::cout << (d->remove(481)) << std::endl;
std::cout << (c->insert(256)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
d->printPretty();
std::cout << (b->remove(442)) << std::endl;
*c=*c;
std::cout << (b->insert(396)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (a->insert(260)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (b->insert(33)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
b->printPretty();
std::cout << (c->insert(194)) << std::endl;
*c=*b;
std::cout << (d->insert(260)) << std::endl;
a->printPretty();
std::cout << (d->insert(189)) << std::endl;
std::cout << (d->insert(466)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
*e=*d;
std::cout << (d->remove(427)) << std::endl;
*d=*b;
std::cout << (a->insert(255)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (d->remove(33)) << std::endl;
std::cout << (b->remove(105)) << std::endl;
*e=*d;
std::cout << (a->insert(129)) << std::endl;
std::cout << (c->insert(396)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
b->printPretty();
std::cout << (c->insert(33)) << std::endl;
std::cout << (a->insert(255)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
std::cout << (b->insert(345)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->remove(250)) << std::endl;
*c=*a;
std::cout << (a->remove(351)) << std::endl;
*a=*c;
std::cout << (b->remove(376)) << std::endl;
*b=*a;
std::cout << (c->remove(133)) << std::endl;
std::cout << (c->insert(354)) << std::endl;
std::cout << (c->insert(417)) << std::endl;
*d=*b;
std::cout << (e->remove(194)) << std::endl;
std::cout << (b->remove(454)) << std::endl;
*c=*d;
*d=*e;
std::cout << (e->remove(452)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
*a=*b;
std::cout << (b->insert(129)) << std::endl;
b->printPretty();
std::cout << (a->insert(31)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (b->remove(260)) << std::endl;
std::cout << (e->insert(204)) << std::endl;
std::cout << (d->insert(396)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
std::cout << (c->insert(489)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
std::cout << (c->insert(35)) << std::endl;
d->printPretty();
std::cout << (e->remove(204)) << std::endl;
*c=*d;
std::cout << (c->insert(93)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
c->printPretty();
std::cout << (c->insert(93)) << std::endl;
c->printPretty();
std::cout << (b->remove(489)) << std::endl;
a->printPretty();
std::cout << (a->remove(30)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
*d=*b;
d->printPretty();
*e=*b;
std::cout << (b->remove(79)) << std::endl;
b->printPretty();
std::cout << (d->insert(303)) << std::endl;
e->printPretty();
std::cout << (d->remove(255)) << std::endl;
std::cout << (c->remove(484)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (d->insert(394)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
std::cout << (c->insert(62)) << std::endl;
std::cout << (a->insert(163)) << std::endl;
std::cout << (e->insert(85)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
a->printPretty();
std::cout << (d->remove(85)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (a->insert(43)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
d->printPretty();
std::cout << (c->remove(93)) << std::endl;
*c=*b;
std::cout << (b->remove(129)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
*d=*c;
e->printPretty();
*d=*b;
*b=*d;
std::cout << (c->insert(283)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
*a=*d;
std::cout << (e->remove(152)) << std::endl;
std::cout << (e->remove(85)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (d->insert(468)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
std::cout << (d->insert(468)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
std::cout << (d->insert(301)) << std::endl;
std::cout << (e->remove(147)) << std::endl;
e->printPretty();
std::cout << (c->insert(85)) << std::endl;
std::cout << (b->remove(74)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
b->printPretty();
*d=*e;
*b=*c;
std::cout << (c->insert(476)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
*c=*b;
std::cout << (d->remove(360)) << std::endl;
*c=*c;
std::cout << (c->remove(283)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->insert(81)) << std::endl;
*d=*a;
std::cout << (b->insert(100)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (e->remove(369)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
*c=*a;
std::cout << (a->remove(453)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
std::cout << (c->insert(72)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
b->printPretty();
std::cout << (a->remove(181)) << std::endl;
a->printPretty();
std::cout << (c->insert(427)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
*c=*c;
b->printPretty();
*e=*d;
std::cout << (d->insert(435)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
std::cout << (e->remove(27)) << std::endl;
std::cout << (c->remove(85)) << std::endl;
*a=*e;
std::cout << (a->remove(269)) << std::endl;
*a=*c;
std::cout << (d->remove(233)) << std::endl;
std::cout << (d->remove(85)) << std::endl;
std::cout << (a->remove(255)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (a->remove(279)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
*d=*d;
std::cout << (a->remove(184)) << std::endl;
*a=*a;
*d=*e;
*e=*d;
std::cout << (e->remove(353)) << std::endl;
std::cout << (a->insert(198)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (c->insert(340)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
*c=*c;
std::cout << (e->insert(424)) << std::endl;
c->printPretty();
std::cout << (b->remove(90)) << std::endl;
std::cout << (e->remove(64)) << std::endl;
std::cout << (b->insert(138)) << std::endl;
*b=*e;
std::cout << (e->insert(85)) << std::endl;
std::cout << (a->remove(38)) << std::endl;
b->printPretty();
std::cout << (b->remove(242)) << std::endl;
std::cout << (b->remove(16)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
std::cout << (c->remove(5)) << std::endl;
*a=*b;
*b=*e;
c->printPretty();
std::cout << (c->remove(175)) << std::endl;
*e=*e;
std::cout << (c->insert(72)) << std::endl;
std::cout << (b->insert(424)) << std::endl;
*a=*a;
std::cout << (c->remove(72)) << std::endl;
d->printPretty();
std::cout << (c->insert(427)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
std::cout << (b->insert(120)) << std::endl;
std::cout << (e->remove(424)) << std::endl;
std::cout << (b->remove(120)) << std::endl;
*a=*e;
std::cout << (c->remove(247)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (a->insert(90)) << std::endl;
std::cout << (c->remove(373)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
std::cout << (d->insert(251)) << std::endl;
std::cout << (e->insert(254)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
std::cout << (d->remove(64)) << std::endl;
std::cout << (d->insert(251)) << std::endl;
d->printPretty();
std::cout << (c->insert(94)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (e->remove(159)) << std::endl;
*e=*b;
b->printPretty();
*c=*b;
*e=*a;
*d=*e;
std::cout << (e->insert(90)) << std::endl;
std::cout << (d->remove(131)) << std::endl;
*e=*b;
*d=*d;
b->printPretty();
std::cout << (d->insert(332)) << std::endl;
std::cout << (b->insert(30)) << std::endl;
std::cout << (c->remove(85)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
std::cout << (d->insert(153)) << std::endl;
std::cout << (e->remove(97)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (e->remove(85)) << std::endl;
std::cout << (b->remove(30)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
c->printPretty();
std::cout << (c->insert(195)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
return 0;
}
