#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (a->insert(279)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->insert(279)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (a->insert(279)) << std::endl;
*b=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->insert(279)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
std::cout << (a->remove(279)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (c->insert(316)) << std::endl;
std::cout << (d->remove(279)) << std::endl;
std::cout << (c->remove(316)) << std::endl;
e->printPretty();
std::cout << (c->insert(41)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (e->insert(386)) << std::endl;
*d=*c;
std::cout << (e->insert(386)) << std::endl;
b->printPretty();
*d=*b;
*e=*e;
std::cout << (e->insert(386)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (a->insert(87)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
e->printPretty();
d->printPretty();
*b=*d;
*b=*b;
*d=*e;
std::cout << (d->insert(386)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
std::cout << (a->remove(41)) << std::endl;
c->printPretty();
*e=*b;
e->printPretty();
std::cout << (b->insert(62)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
*e=*b;
std::cout << (c->remove(59)) << std::endl;
*d=*a;
*d=*e;
*d=*b;
std::cout << (d->remove(211)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (d->remove(467)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (e->remove(358)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
a->printPretty();
std::cout << (c->remove(41)) << std::endl;
*e=*d;
std::cout << (a->remove(159)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
*c=*b;
std::cout << (b->remove(62)) << std::endl;
*b=*e;
std::cout << (e->remove(62)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (b->remove(132)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (b->remove(498)) << std::endl;
std::cout << (d->insert(369)) << std::endl;
*b=*d;
c->printPretty();
std::cout << (e->remove(438)) << std::endl;
b->printPretty();
std::cout << (b->remove(62)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
*b=*d;
std::cout << (c->insert(319)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
*a=*a;
*e=*c;
std::cout << (a->remove(59)) << std::endl;
std::cout << (b->remove(149)) << std::endl;
*c=*a;
e->printPretty();
c->printPretty();
std::cout << (c->insert(95)) << std::endl;
d->printPretty();
std::cout << (d->insert(62)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
std::cout << (b->insert(345)) << std::endl;
d->printPretty();
std::cout << (c->remove(95)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
*a=*e;
std::cout << (e->remove(62)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
c->printPretty();
*a=*c;
*a=*c;
std::cout << (a->remove(77)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
a->printPretty();
std::cout << (b->remove(485)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
d->printPretty();
std::cout << (c->remove(448)) << std::endl;
d->printPretty();
std::cout << (b->remove(327)) << std::endl;
std::cout << (c->insert(410)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
*b=*c;
std::cout << (d->insert(369)) << std::endl;
*e=*a;
std::cout << (d->remove(339)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
*b=*d;
std::cout << (b->insert(62)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(371)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (b->remove(156)) << std::endl;
std::cout << (d->remove(371)) << std::endl;
d->printPretty();
std::cout << (e->remove(247)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (e->insert(436)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (d->remove(49)) << std::endl;
std::cout << (c->insert(42)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
*e=*c;
*d=*b;
std::cout << (b->remove(110)) << std::endl;
std::cout << (a->insert(419)) << std::endl;
c->printPretty();
std::cout << (c->insert(436)) << std::endl;
*c=*a;
std::cout << (c->remove(419)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (d->insert(110)) << std::endl;
std::cout << (c->insert(110)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
std::cout << (b->insert(384)) << std::endl;
std::cout << (a->insert(419)) << std::endl;
std::cout << (e->insert(260)) << std::endl;
c->printPretty();
std::cout << (b->insert(384)) << std::endl;
std::cout << (c->insert(110)) << std::endl;
*a=*b;
*b=*a;
std::cout << (b->remove(316)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
*b=*d;
std::cout << (c->insert(402)) << std::endl;
d->printPretty();
std::cout << (d->remove(394)) << std::endl;
d->printPretty();
std::cout << (e->insert(457)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (e->remove(436)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
std::cout << (e->insert(260)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (c->remove(402)) << std::endl;
e->printPretty();
std::cout << (b->remove(212)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
std::cout << (a->remove(285)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
std::cout << (b->insert(74)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
std::cout << (a->remove(110)) << std::endl;
std::cout << (e->remove(54)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (a->remove(367)) << std::endl;
std::cout << (c->insert(110)) << std::endl;
*c=*b;
std::cout << (d->insert(284)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
d->printPretty();
std::cout << (d->insert(110)) << std::endl;
c->printPretty();
std::cout << (d->insert(173)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
std::cout << (b->insert(74)) << std::endl;
*c=*a;
std::cout << (b->remove(397)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
*b=*c;
std::cout << (a->insert(250)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->insert(285)) << std::endl;
*c=*a;
std::cout << (d->insert(196)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
*b=*a;
std::cout << (e->insert(285)) << std::endl;
std::cout << (c->insert(370)) << std::endl;
*d=*b;
std::cout << (a->remove(250)) << std::endl;
e->printPretty();
std::cout << (a->remove(321)) << std::endl;
*c=*d;
*a=*b;
*b=*b;
std::cout << (e->insert(153)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (a->remove(451)) << std::endl;
*c=*c;
std::cout << (e->remove(353)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
std::cout << (d->remove(320)) << std::endl;
std::cout << (b->insert(453)) << std::endl;
std::cout << (b->remove(453)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
b->printPretty();
std::cout << (c->remove(250)) << std::endl;
std::cout << (e->insert(131)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->remove(255)) << std::endl;
d->printPretty();
std::cout << (e->remove(131)) << std::endl;
std::cout << (b->remove(162)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (e->insert(48)) << std::endl;
std::cout << (e->insert(82)) << std::endl;
d->printPretty();
std::cout << (e->insert(48)) << std::endl;
std::cout << (d->insert(72)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
*e=*a;
std::cout << (c->insert(163)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
std::cout << (d->remove(72)) << std::endl;
*b=*a;
std::cout << (b->remove(303)) << std::endl;
std::cout << (e->remove(312)) << std::endl;
*e=*d;
std::cout << (d->remove(38)) << std::endl;
std::cout << (e->insert(77)) << std::endl;
std::cout << (d->remove(25)) << std::endl;
std::cout << (e->remove(413)) << std::endl;
std::cout << (e->insert(77)) << std::endl;
e->printPretty();
std::cout << (d->remove(77)) << std::endl;
std::cout << (a->insert(402)) << std::endl;
*a=*d;
*c=*e;
b->printPretty();
std::cout << (e->remove(77)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
e->printPretty();
c->printPretty();
a->printPretty();
std::cout << (c->remove(290)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
std::cout << (d->insert(374)) << std::endl;
c->printPretty();
std::cout << (a->insert(287)) << std::endl;
std::cout << (e->remove(55)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (d->remove(418)) << std::endl;
std::cout << (d->insert(374)) << std::endl;
std::cout << (d->remove(207)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
*c=*b;
std::cout << (e->remove(315)) << std::endl;
std::cout << (e->insert(382)) << std::endl;
d->printPretty();
std::cout << (b->remove(410)) << std::endl;
d->printPretty();
*e=*b;
a->printPretty();
c->printPretty();
b->printPretty();
std::cout << (e->insert(113)) << std::endl;
std::cout << (c->insert(410)) << std::endl;
std::cout << (d->remove(374)) << std::endl;
std::cout << (a->remove(287)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
a->printPretty();
*c=*b;
e->printPretty();
std::cout << (a->insert(348)) << std::endl;
e->printPretty();
std::cout << (c->remove(197)) << std::endl;
std::cout << (e->remove(113)) << std::endl;
a->printPretty();
std::cout << (b->remove(197)) << std::endl;
e->printPretty();
std::cout << (c->remove(139)) << std::endl;
*b=*a;
std::cout << (a->insert(188)) << std::endl;
c->printPretty();
std::cout << (d->insert(471)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
a->printPretty();
*c=*a;
*d=*b;
std::cout << (e->insert(14)) << std::endl;
std::cout << (d->insert(348)) << std::endl;
d->printPretty();
std::cout << (b->insert(13)) << std::endl;
std::cout << (d->insert(375)) << std::endl;
std::cout << (d->insert(292)) << std::endl;
std::cout << (d->remove(292)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
std::cout << (c->insert(292)) << std::endl;
std::cout << (e->remove(160)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
std::cout << (c->insert(188)) << std::endl;
std::cout << (c->remove(188)) << std::endl;
std::cout << (c->insert(21)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
*d=*a;
std::cout << (e->insert(208)) << std::endl;
std::cout << (c->insert(21)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (b->insert(13)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
std::cout << (d->insert(292)) << std::endl;
std::cout << (d->remove(292)) << std::endl;
*b=*a;
std::cout << (a->remove(188)) << std::endl;
std::cout << (d->remove(89)) << std::endl;
*b=*b;
std::cout << (a->remove(297)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (b->remove(188)) << std::endl;
*b=*c;
std::cout << (d->remove(252)) << std::endl;
*e=*c;
std::cout << (e->remove(292)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
std::cout << (d->remove(225)) << std::endl;
c->printPretty();
std::cout << (a->insert(292)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
b->printPretty();
std::cout << (c->remove(263)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (d->remove(188)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(292)) << std::endl;
std::cout << (b->insert(208)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
std::cout << (b->insert(428)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
std::cout << (e->insert(75)) << std::endl;
d->printPretty();
*c=*c;
*d=*e;
std::cout << (e->remove(444)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
std::cout << (a->insert(135)) << std::endl;
std::cout << (a->remove(56)) << std::endl;
*b=*e;
std::cout << (d->insert(14)) << std::endl;
std::cout << (a->remove(21)) << std::endl;
std::cout << (e->remove(336)) << std::endl;
*b=*d;
std::cout << (e->insert(21)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (d->remove(89)) << std::endl;
b->printPretty();
std::cout << (d->insert(75)) << std::endl;
std::cout << (a->remove(292)) << std::endl;
std::cout << (d->insert(38)) << std::endl;
std::cout << (a->insert(135)) << std::endl;
*c=*d;
std::cout << (b->remove(61)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
*d=*b;
std::cout << (d->insert(459)) << std::endl;
std::cout << (d->insert(488)) << std::endl;
a->printPretty();
std::cout << (c->insert(204)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
*b=*a;
*c=*b;
*c=*d;
a->printPretty();
std::cout << (d->remove(98)) << std::endl;
std::cout << (e->insert(338)) << std::endl;
*b=*d;
*a=*c;
std::cout << (b->remove(36)) << std::endl;
std::cout << (e->remove(21)) << std::endl;
std::cout << (d->remove(397)) << std::endl;
e->printPretty();
std::cout << (b->remove(277)) << std::endl;
e->printPretty();
std::cout << (d->remove(56)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (e->insert(136)) << std::endl;
b->printPretty();
std::cout << (b->insert(432)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->remove(47)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
std::cout << (a->insert(202)) << std::endl;
*b=*c;
*a=*e;
std::cout << (d->insert(75)) << std::endl;
std::cout << (b->remove(197)) << std::endl;
std::cout << (a->remove(179)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
*b=*e;
*d=*c;
std::cout << (e->insert(75)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
*a=*d;
std::cout << (b->insert(336)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (d->insert(174)) << std::endl;
std::cout << (b->remove(459)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (e->remove(317)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (a->remove(404)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (e->remove(162)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
std::cout << (a->insert(136)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
d->printPretty();
std::cout << (e->insert(28)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
std::cout << (d->remove(336)) << std::endl;
std::cout << (a->remove(75)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
b->printPretty();
std::cout << (d->remove(16)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
e->printPretty();
std::cout << (a->remove(305)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
b->printPretty();
std::cout << (a->remove(254)) << std::endl;
std::cout << (b->remove(21)) << std::endl;
std::cout << (c->insert(75)) << std::endl;
c->printPretty();
std::cout << (b->insert(136)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (c->remove(136)) << std::endl;
d->printPretty();
std::cout << (e->insert(230)) << std::endl;
std::cout << (a->remove(290)) << std::endl;
std::cout << (c->remove(21)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
std::cout << (e->insert(28)) << std::endl;
e->printPretty();
c->printPretty();
*e=*e;
*a=*d;
std::cout << (c->remove(75)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
*c=*d;
std::cout << (d->remove(315)) << std::endl;
b->printPretty();
std::cout << (d->remove(355)) << std::endl;
d->printPretty();
std::cout << (b->remove(459)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
e->printPretty();
std::cout << (e->insert(88)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
std::cout << (a->insert(21)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (e->remove(28)) << std::endl;
std::cout << (b->insert(210)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->insert(244)) << std::endl;
std::cout << (c->remove(21)) << std::endl;
std::cout << (e->remove(414)) << std::endl;
*c=*e;
std::cout << (e->insert(136)) << std::endl;
std::cout << (a->remove(462)) << std::endl;
std::cout << (d->insert(459)) << std::endl;
*a=*c;
*e=*d;
std::cout << (c->insert(443)) << std::endl;
std::cout << (c->remove(11)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
std::cout << (d->insert(117)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
*e=*d;
d->printPretty();
std::cout << (a->insert(252)) << std::endl;
c->printPretty();
std::cout << (a->remove(390)) << std::endl;
*d=*b;
std::cout << (e->insert(459)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
*d=*c;
std::cout << (b->remove(136)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
std::cout << (e->insert(338)) << std::endl;
std::cout << (b->remove(488)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
d->printPretty();
std::cout << (a->remove(261)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
b->printPretty();
std::cout << (c->remove(9)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (a->insert(322)) << std::endl;
*e=*a;
*d=*e;
*a=*a;
*a=*c;
*e=*d;
std::cout << (c->remove(19)) << std::endl;
std::cout << (a->remove(67)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
std::cout << (c->insert(8)) << std::endl;
std::cout << (e->remove(21)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
std::cout << (a->remove(336)) << std::endl;
std::cout << (a->remove(252)) << std::endl;
*a=*a;
std::cout << (a->remove(435)) << std::endl;
c->printPretty();
std::cout << (c->insert(252)) << std::endl;
std::cout << (d->insert(252)) << std::endl;
b->printPretty();
std::cout << (a->remove(448)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
c->printPretty();
std::cout << (a->insert(458)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->insert(19)) << std::endl;
std::cout << (a->remove(88)) << std::endl;
*d=*c;
std::cout << (d->insert(182)) << std::endl;
b->printPretty();
std::cout << (a->remove(487)) << std::endl;
std::cout << (d->remove(459)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (b->remove(202)) << std::endl;
*b=*b;
std::cout << (d->remove(21)) << std::endl;
*c=*e;
std::cout << (c->remove(488)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (a->insert(311)) << std::endl;
*a=*e;
std::cout << (b->remove(488)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (b->insert(244)) << std::endl;
*b=*e;
std::cout << (a->remove(8)) << std::endl;
std::cout << (a->remove(469)) << std::endl;
std::cout << (a->insert(88)) << std::endl;
c->printPretty();
std::cout << (b->remove(389)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (c->insert(493)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
a->printPretty();
std::cout << (d->insert(48)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->insert(459)) << std::endl;
std::cout << (b->insert(75)) << std::endl;
std::cout << (c->insert(476)) << std::endl;
*d=*a;
*d=*e;
std::cout << (a->remove(418)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->remove(48)) << std::endl;
c->printPretty();
std::cout << (b->insert(14)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
b->printPretty();
*b=*d;
a->printPretty();
*c=*a;
std::cout << (c->remove(252)) << std::endl;
std::cout << (a->remove(480)) << std::endl;
*b=*b;
std::cout << (d->remove(197)) << std::endl;
std::cout << (a->insert(136)) << std::endl;
a->printPretty();
*d=*a;
b->printPretty();
std::cout << (c->remove(30)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
std::cout << (a->insert(392)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
return 0;
}
