#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
b->printPretty();
*a=*a;
std::cout << (a->remove(379)) << std::endl;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (c->remove(275)) << std::endl;
std::cout << (c->insert(254)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*c=*c;
b->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
e->printPretty();
std::cout << (a->remove(349)) << std::endl;
*c=*a;
std::cout << (d->remove(419)) << std::endl;
a->printPretty();
std::cout << (d->remove(137)) << std::endl;
std::cout << (a->remove(462)) << std::endl;
a->printPretty();
e->printPretty();
b->printPretty();
b->printPretty();
d->printPretty();
std::cout << (d->insert(132)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
*e=*d;
b->printPretty();
b->printPretty();
std::cout << (c->remove(89)) << std::endl;
std::cout << (e->remove(123)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
*e=*e;
c->printPretty();
std::cout << (a->insert(181)) << std::endl;
c->printPretty();
std::cout << (e->insert(132)) << std::endl;
std::cout << (a->remove(479)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->insert(244)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (c->remove(209)) << std::endl;
*a=*d;
c->printPretty();
*b=*e;
std::cout << (c->remove(380)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
*c=*b;
*e=*d;
std::cout << (c->remove(132)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
*b=*a;
std::cout << (e->insert(132)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (b->insert(378)) << std::endl;
std::cout << (d->insert(132)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
a->printPretty();
std::cout << (a->insert(169)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
std::cout << (b->remove(132)) << std::endl;
std::cout << (e->remove(132)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
e->printPretty();
e->printPretty();
e->printPretty();
std::cout << (d->insert(132)) << std::endl;
std::cout << (e->insert(3)) << std::endl;
b->printPretty();
std::cout << (c->insert(208)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (c->remove(43)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (e->insert(372)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
e->printPretty();
std::cout << (c->remove(47)) << std::endl;
std::cout << (a->remove(132)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
b->printPretty();
std::cout << (d->insert(132)) << std::endl;
std::cout << (b->remove(377)) << std::endl;
std::cout << (e->insert(293)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
a->printPretty();
std::cout << (d->remove(440)) << std::endl;
std::cout << (b->remove(90)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (c->remove(4)) << std::endl;
*a=*d;
std::cout << (b->remove(300)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
*c=*a;
std::cout << (a->insert(132)) << std::endl;
std::cout << (e->insert(378)) << std::endl;
std::cout << (a->remove(132)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
*d=*d;
std::cout << (d->remove(132)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
std::cout << (e->remove(85)) << std::endl;
*b=*a;
std::cout << (b->remove(32)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
e->printPretty();
std::cout << (a->remove(16)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
b->printPretty();
std::cout << (c->remove(132)) << std::endl;
std::cout << (b->insert(335)) << std::endl;
a->printPretty();
*a=*c;
std::cout << (b->insert(449)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (a->remove(488)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
b->printPretty();
std::cout << (a->remove(183)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->insert(39)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
*c=*e;
std::cout << (c->insert(465)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
a->printPretty();
std::cout << (b->remove(335)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (c->insert(495)) << std::endl;
d->printPretty();
std::cout << (c->remove(230)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
*c=*c;
std::cout << (c->remove(247)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
std::cout << (a->insert(437)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
*c=*e;
std::cout << (a->remove(437)) << std::endl;
*b=*a;
std::cout << (d->remove(350)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
std::cout << (c->insert(216)) << std::endl;
*c=*c;
*e=*a;
std::cout << (d->insert(222)) << std::endl;
*d=*b;
std::cout << (e->insert(117)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
*e=*c;
std::cout << (e->insert(216)) << std::endl;
std::cout << (d->remove(185)) << std::endl;
std::cout << (e->insert(216)) << std::endl;
std::cout << (a->insert(90)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
std::cout << (b->remove(117)) << std::endl;
std::cout << (c->insert(452)) << std::endl;
std::cout << (c->remove(216)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (e->remove(81)) << std::endl;
*e=*d;
std::cout << (e->insert(35)) << std::endl;
std::cout << (c->insert(452)) << std::endl;
std::cout << (a->insert(90)) << std::endl;
std::cout << (a->remove(424)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
*a=*c;
std::cout << (e->remove(410)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
std::cout << (a->remove(456)) << std::endl;
a->printPretty();
*d=*a;
c->printPretty();
std::cout << (c->insert(452)) << std::endl;
*c=*b;
c->printPretty();
*e=*d;
std::cout << (d->remove(452)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
std::cout << (e->remove(452)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->insert(260)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
*c=*b;
std::cout << (a->insert(489)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
std::cout << (d->remove(42)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (e->insert(303)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
b->printPretty();
std::cout << (e->insert(303)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
*e=*d;
*b=*b;
*a=*b;
std::cout << (c->remove(489)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
*e=*a;
std::cout << (c->insert(424)) << std::endl;
e->printPretty();
b->printPretty();
*c=*b;
*a=*b;
std::cout << (d->insert(85)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
a->printPretty();
std::cout << (b->insert(369)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (b->insert(390)) << std::endl;
*e=*d;
std::cout << (a->insert(226)) << std::endl;
std::cout << (a->remove(226)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (e->remove(456)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
*e=*e;
*d=*e;
std::cout << (b->remove(390)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (b->insert(32)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
d->printPretty();
std::cout << (c->insert(44)) << std::endl;
std::cout << (b->remove(120)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (e->insert(226)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (e->insert(202)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (e->insert(62)) << std::endl;
std::cout << (b->insert(133)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (a->remove(46)) << std::endl;
*d=*e;
std::cout << (d->remove(268)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (a->remove(92)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
a->printPretty();
std::cout << (c->insert(422)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
c->printPretty();
std::cout << (d->insert(226)) << std::endl;
std::cout << (d->insert(226)) << std::endl;
std::cout << (e->insert(349)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (b->remove(341)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (b->insert(299)) << std::endl;
e->printPretty();
std::cout << (b->insert(32)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
std::cout << (a->insert(65)) << std::endl;
a->printPretty();
std::cout << (e->remove(202)) << std::endl;
std::cout << (e->insert(138)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
std::cout << (b->remove(355)) << std::endl;
*a=*d;
*e=*d;
*e=*c;
std::cout << (b->remove(53)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
std::cout << (d->remove(226)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
std::cout << (b->insert(32)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
*d=*e;
std::cout << (a->remove(36)) << std::endl;
std::cout << (e->remove(133)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->remove(32)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->insert(330)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
std::cout << (a->insert(226)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->insert(133)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
std::cout << (a->remove(183)) << std::endl;
*a=*a;
std::cout << (e->remove(390)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (d->insert(32)) << std::endl;
std::cout << (d->remove(408)) << std::endl;
d->printPretty();
std::cout << (e->remove(226)) << std::endl;
std::cout << (a->remove(226)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
std::cout << (c->remove(215)) << std::endl;
b->printPretty();
std::cout << (a->insert(207)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
*a=*b;
std::cout << (b->remove(487)) << std::endl;
*a=*e;
b->printPretty();
std::cout << (a->insert(125)) << std::endl;
std::cout << (c->remove(429)) << std::endl;
std::cout << (b->insert(299)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (d->remove(23)) << std::endl;
*e=*d;
*a=*d;
a->printPretty();
std::cout << (e->remove(32)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
*d=*a;
std::cout << (b->remove(219)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
std::cout << (a->insert(133)) << std::endl;
std::cout << (d->insert(330)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
b->printPretty();
*d=*b;
*c=*d;
*b=*d;
c->printPretty();
std::cout << (e->remove(133)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (c->remove(441)) << std::endl;
std::cout << (e->remove(139)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (b->remove(11)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
b->printPretty();
std::cout << (a->remove(303)) << std::endl;
*a=*d;
std::cout << (b->insert(175)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
*e=*b;
std::cout << (a->insert(401)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
d->printPretty();
*a=*c;
c->printPretty();
*b=*a;
std::cout << (b->remove(222)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
b->printPretty();
std::cout << (e->remove(126)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (e->remove(183)) << std::endl;
*c=*d;
*d=*a;
std::cout << (e->remove(175)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (a->insert(131)) << std::endl;
std::cout << (c->insert(99)) << std::endl;
a->printPretty();
std::cout << (a->remove(131)) << std::endl;
e->printPretty();
d->printPretty();
*c=*c;
std::cout << (d->insert(247)) << std::endl;
*d=*d;
*b=*d;
*b=*d;
*c=*e;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
*d=*d;
std::cout << (a->insert(222)) << std::endl;
d->printPretty();
std::cout << (b->remove(247)) << std::endl;
std::cout << (d->remove(247)) << std::endl;
*d=*b;
*d=*b;
std::cout << (d->remove(368)) << std::endl;
*b=*d;
b->printPretty();
*c=*a;
std::cout << (e->remove(238)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (c->remove(1)) << std::endl;
e->printPretty();
std::cout << (a->remove(99)) << std::endl;
std::cout << (e->remove(73)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (a->insert(247)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
*a=*b;
*c=*d;
a->printPretty();
*b=*e;
*a=*d;
std::cout << (d->insert(75)) << std::endl;
std::cout << (e->insert(480)) << std::endl;
*e=*b;
std::cout << (c->insert(487)) << std::endl;
std::cout << (c->remove(16)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
e->printPretty();
std::cout << (c->insert(487)) << std::endl;
*d=*e;
std::cout << (c->remove(139)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
*d=*d;
std::cout << (e->remove(99)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
c->printPretty();
std::cout << (b->insert(115)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
b->printPretty();
std::cout << (b->insert(251)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (a->insert(211)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
d->printPretty();
d->printPretty();
e->printPretty();
d->printPretty();
std::cout << (d->remove(192)) << std::endl;
*b=*e;
std::cout << (b->insert(115)) << std::endl;
*d=*e;
std::cout << (d->remove(251)) << std::endl;
std::cout << (d->insert(275)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
a->printPretty();
std::cout << (d->remove(115)) << std::endl;
a->printPretty();
std::cout << (e->insert(461)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
std::cout << (e->insert(398)) << std::endl;
*c=*e;
std::cout << (d->insert(246)) << std::endl;
std::cout << (b->remove(368)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
*b=*c;
std::cout << (a->insert(322)) << std::endl;
std::cout << (c->remove(8)) << std::endl;
std::cout << (b->insert(251)) << std::endl;
std::cout << (b->insert(480)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
*c=*a;
std::cout << (b->insert(339)) << std::endl;
std::cout << (d->remove(321)) << std::endl;
a->printPretty();
e->printPretty();
e->printPretty();
std::cout << (b->remove(167)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
std::cout << (b->remove(480)) << std::endl;
std::cout << (b->insert(335)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
std::cout << (a->remove(43)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (c->remove(85)) << std::endl;
std::cout << (e->insert(281)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (d->remove(151)) << std::endl;
std::cout << (a->insert(72)) << std::endl;
*e=*c;
std::cout << (e->remove(469)) << std::endl;
std::cout << (d->remove(146)) << std::endl;
std::cout << (c->insert(275)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
a->printPretty();
std::cout << (c->remove(328)) << std::endl;
std::cout << (d->remove(112)) << std::endl;
std::cout << (c->remove(275)) << std::endl;
a->printPretty();
std::cout << (c->insert(246)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
d->printPretty();
std::cout << (d->insert(497)) << std::endl;
std::cout << (c->remove(449)) << std::endl;
a->printPretty();
std::cout << (d->insert(246)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
c->printPretty();
std::cout << (c->insert(487)) << std::endl;
*a=*c;
std::cout << (c->remove(434)) << std::endl;
std::cout << (c->remove(142)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
*b=*e;
std::cout << (a->insert(445)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
*e=*d;
std::cout << (d->remove(246)) << std::endl;
b->printPretty();
std::cout << (d->remove(288)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (d->remove(275)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
b->printPretty();
std::cout << (e->insert(246)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
e->printPretty();
std::cout << (e->insert(246)) << std::endl;
std::cout << (c->remove(392)) << std::endl;
std::cout << (a->remove(112)) << std::endl;
a->printPretty();
std::cout << (d->remove(125)) << std::endl;
std::cout << (e->insert(98)) << std::endl;
std::cout << (d->insert(467)) << std::endl;
*d=*c;
std::cout << (c->insert(155)) << std::endl;
std::cout << (b->insert(112)) << std::endl;
*b=*b;
std::cout << (b->insert(275)) << std::endl;
std::cout << (e->insert(275)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (d->remove(487)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
*b=*e;
std::cout << (b->remove(375)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
*b=*c;
std::cout << (b->insert(451)) << std::endl;
std::cout << (e->remove(275)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
a->printPretty();
std::cout << (e->insert(432)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (c->insert(290)) << std::endl;
std::cout << (e->remove(98)) << std::endl;
std::cout << (c->insert(422)) << std::endl;
b->printPretty();
std::cout << (c->remove(290)) << std::endl;
e->printPretty();
std::cout << (a->insert(2)) << std::endl;
std::cout << (e->remove(432)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (b->remove(164)) << std::endl;
*e=*e;
std::cout << (e->remove(189)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
e->printPretty();
std::cout << (e->remove(246)) << std::endl;
std::cout << (e->remove(396)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->remove(104)) << std::endl;
*b=*b;
std::cout << (c->insert(422)) << std::endl;
*d=*c;
a->printPretty();
std::cout << (e->insert(361)) << std::endl;
std::cout << (b->insert(233)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
std::cout << (a->insert(445)) << std::endl;
b->printPretty();
std::cout << (d->remove(331)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
e->printPretty();
std::cout << (d->remove(78)) << std::endl;
c->printPretty();
e->printPretty();
*b=*a;
std::cout << (b->remove(294)) << std::endl;
d->printPretty();
std::cout << (a->remove(205)) << std::endl;
std::cout << (c->insert(493)) << std::endl;
std::cout << (a->insert(247)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
a->printPretty();
std::cout << (b->remove(372)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
std::cout << (c->remove(422)) << std::endl;
std::cout << (d->remove(422)) << std::endl;
std::cout << (e->insert(51)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
std::cout << (a->remove(287)) << std::endl;
*d=*b;
std::cout << (e->insert(361)) << std::endl;
*e=*c;
return 0;
}
