#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(229)) << std::endl;
std::cout << (a->remove(405)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
*b=*a;
std::cout << (a->remove(249)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
*a=*a;
a->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
*d=*a;
c->printPretty();
std::cout << (b->remove(240)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
b->printPretty();
d->printPretty();
*c=*d;
std::cout << (e->insert(227)) << std::endl;
std::cout << (c->insert(307)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
a->printPretty();
std::cout << (a->insert(411)) << std::endl;
*c=*d;
std::cout << (b->remove(403)) << std::endl;
std::cout << (d->insert(226)) << std::endl;
std::cout << (e->insert(227)) << std::endl;
*b=*a;
std::cout << (c->insert(230)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (c->remove(230)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
*a=*a;
std::cout << (b->insert(215)) << std::endl;
*b=*b;
std::cout << (a->insert(152)) << std::endl;
*a=*a;
std::cout << (a->insert(318)) << std::endl;
b->printPretty();
e->printPretty();
*d=*b;
*e=*e;
e->printPretty();
std::cout << (a->insert(21)) << std::endl;
std::cout << (b->insert(215)) << std::endl;
e->printPretty();
std::cout << (d->remove(411)) << std::endl;
a->printPretty();
std::cout << (a->insert(152)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
e->printPretty();
std::cout << (d->remove(421)) << std::endl;
std::cout << (a->remove(35)) << std::endl;
*d=*c;
std::cout << (c->insert(401)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
b->printPretty();
std::cout << (a->insert(375)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
*a=*d;
std::cout << (e->insert(227)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
e->printPretty();
std::cout << (e->insert(177)) << std::endl;
std::cout << (b->insert(225)) << std::endl;
*a=*e;
b->printPretty();
b->printPretty();
std::cout << (e->remove(227)) << std::endl;
*d=*d;
*e=*b;
e->printPretty();
a->printPretty();
b->printPretty();
std::cout << (d->insert(197)) << std::endl;
*e=*d;
c->printPretty();
*a=*c;
std::cout << (b->remove(411)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (e->insert(197)) << std::endl;
*a=*b;
std::cout << (d->remove(197)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
std::cout << (a->remove(309)) << std::endl;
*a=*a;
std::cout << (e->remove(197)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (a->remove(300)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->insert(225)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (e->insert(178)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
*b=*e;
std::cout << (b->insert(178)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
d->printPretty();
std::cout << (b->remove(178)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
d->printPretty();
e->printPretty();
c->printPretty();
*b=*a;
std::cout << (e->insert(242)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
std::cout << (a->insert(225)) << std::endl;
*c=*b;
std::cout << (a->remove(497)) << std::endl;
std::cout << (e->remove(78)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
*b=*b;
*b=*a;
std::cout << (a->insert(52)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (e->insert(406)) << std::endl;
*c=*b;
std::cout << (e->insert(234)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
std::cout << (a->insert(298)) << std::endl;
std::cout << (b->remove(42)) << std::endl;
b->printPretty();
std::cout << (c->insert(156)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
*d=*b;
std::cout << (e->insert(93)) << std::endl;
c->printPretty();
std::cout << (d->insert(215)) << std::endl;
*c=*d;
*e=*e;
*c=*a;
std::cout << (e->remove(234)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
std::cout << (e->remove(108)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
c->printPretty();
std::cout << (a->remove(270)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
std::cout << (b->insert(303)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (d->remove(225)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
std::cout << (a->remove(225)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->remove(271)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (a->remove(215)) << std::endl;
*d=*e;
*a=*c;
*e=*c;
std::cout << (b->remove(264)) << std::endl;
*d=*d;
std::cout << (d->remove(178)) << std::endl;
std::cout << (b->remove(225)) << std::endl;
std::cout << (d->insert(179)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
std::cout << (c->insert(11)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (d->insert(68)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
std::cout << (a->insert(298)) << std::endl;
std::cout << (a->remove(38)) << std::endl;
a->printPretty();
std::cout << (e->insert(153)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (a->insert(172)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (b->remove(393)) << std::endl;
std::cout << (b->insert(318)) << std::endl;
a->printPretty();
std::cout << (e->remove(236)) << std::endl;
*b=*e;
std::cout << (d->remove(103)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
*e=*a;
std::cout << (b->remove(298)) << std::endl;
d->printPretty();
std::cout << (b->insert(215)) << std::endl;
*c=*a;
*c=*d;
std::cout << (b->remove(153)) << std::endl;
a->printPretty();
*a=*d;
*a=*a;
std::cout << (a->remove(136)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
std::cout << (e->insert(172)) << std::endl;
*d=*a;
std::cout << (d->remove(56)) << std::endl;
*d=*e;
*a=*b;
std::cout << (c->remove(254)) << std::endl;
d->printPretty();
std::cout << (e->remove(56)) << std::endl;
std::cout << (e->remove(392)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
e->printPretty();
std::cout << (e->remove(42)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->remove(56)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (e->insert(9)) << std::endl;
*b=*c;
d->printPretty();
std::cout << (a->insert(9)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
std::cout << (e->remove(130)) << std::endl;
std::cout << (b->remove(93)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
c->printPretty();
std::cout << (c->insert(406)) << std::endl;
std::cout << (e->insert(225)) << std::endl;
*b=*c;
*c=*d;
*d=*d;
std::cout << (b->insert(406)) << std::endl;
std::cout << (d->remove(93)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (a->insert(334)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
e->printPretty();
std::cout << (a->insert(126)) << std::endl;
c->printPretty();
std::cout << (a->insert(395)) << std::endl;
std::cout << (a->insert(334)) << std::endl;
d->printPretty();
std::cout << (d->insert(470)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
std::cout << (c->remove(392)) << std::endl;
a->printPretty();
std::cout << (d->insert(470)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
std::cout << (b->remove(68)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
std::cout << (b->insert(93)) << std::endl;
std::cout << (c->insert(423)) << std::endl;
std::cout << (e->insert(194)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (e->insert(196)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
e->printPretty();
std::cout << (a->remove(82)) << std::endl;
std::cout << (c->remove(457)) << std::endl;
std::cout << (b->insert(242)) << std::endl;
std::cout << (e->insert(165)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
*d=*d;
std::cout << (e->insert(196)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
a->printPretty();
std::cout << (b->remove(327)) << std::endl;
std::cout << (c->remove(242)) << std::endl;
c->printPretty();
std::cout << (e->remove(262)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
a->printPretty();
std::cout << (c->remove(6)) << std::endl;
std::cout << (b->insert(242)) << std::endl;
*c=*d;
std::cout << (a->insert(270)) << std::endl;
*b=*a;
std::cout << (b->insert(322)) << std::endl;
std::cout << (b->remove(222)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
std::cout << (e->insert(308)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
std::cout << (b->insert(238)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
b->printPretty();
std::cout << (e->remove(409)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
std::cout << (a->remove(302)) << std::endl;
a->printPretty();
std::cout << (b->insert(262)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
std::cout << (e->remove(462)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->insert(172)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
std::cout << (a->insert(9)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (d->insert(68)) << std::endl;
b->printPretty();
std::cout << (e->insert(308)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (a->insert(60)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
std::cout << (c->remove(406)) << std::endl;
std::cout << (c->remove(414)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
e->printPretty();
std::cout << (b->remove(448)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
*a=*c;
std::cout << (d->insert(68)) << std::endl;
c->printPretty();
std::cout << (e->remove(225)) << std::endl;
*a=*d;
*a=*b;
std::cout << (e->remove(270)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
std::cout << (b->remove(334)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (b->remove(215)) << std::endl;
a->printPretty();
std::cout << (a->remove(275)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (d->insert(38)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
std::cout << (e->insert(495)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(172)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (a->remove(366)) << std::endl;
std::cout << (a->remove(215)) << std::endl;
std::cout << (a->remove(238)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
std::cout << (e->insert(22)) << std::endl;
d->printPretty();
std::cout << (b->insert(9)) << std::endl;
std::cout << (c->remove(60)) << std::endl;
*d=*e;
std::cout << (d->remove(495)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
d->printPretty();
std::cout << (c->remove(9)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (a->remove(334)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
*d=*c;
std::cout << (d->insert(418)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (d->remove(62)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (e->insert(215)) << std::endl;
*d=*d;
d->printPretty();
*b=*d;
std::cout << (a->insert(281)) << std::endl;
*c=*a;
*d=*c;
a->printPretty();
std::cout << (a->insert(477)) << std::endl;
std::cout << (c->remove(370)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
std::cout << (c->insert(199)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
std::cout << (e->insert(495)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
*d=*a;
std::cout << (b->insert(318)) << std::endl;
c->printPretty();
std::cout << (a->insert(247)) << std::endl;
c->printPretty();
std::cout << (d->insert(322)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
e->printPretty();
std::cout << (c->remove(270)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (c->insert(57)) << std::endl;
std::cout << (e->insert(308)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
e->printPretty();
std::cout << (a->insert(395)) << std::endl;
e->printPretty();
std::cout << (d->remove(225)) << std::endl;
*b=*d;
std::cout << (a->insert(341)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->insert(12)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (e->remove(215)) << std::endl;
b->printPretty();
std::cout << (d->remove(375)) << std::endl;
*b=*a;
std::cout << (d->remove(270)) << std::endl;
std::cout << (b->remove(225)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(270)) << std::endl;
a->printPretty();
std::cout << (c->insert(357)) << std::endl;
c->printPretty();
std::cout << (b->remove(42)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
a->printPretty();
e->printPretty();
*e=*d;
std::cout << (b->insert(9)) << std::endl;
*d=*d;
std::cout << (c->remove(281)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->remove(42)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (d->remove(213)) << std::endl;
*b=*c;
std::cout << (d->insert(209)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
std::cout << (b->remove(377)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
std::cout << (b->remove(149)) << std::endl;
*d=*b;
*b=*e;
std::cout << (a->insert(184)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
*a=*d;
std::cout << (e->remove(37)) << std::endl;
std::cout << (a->remove(270)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->insert(391)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
*a=*d;
e->printPretty();
a->printPretty();
*e=*c;
std::cout << (b->insert(477)) << std::endl;
std::cout << (d->insert(252)) << std::endl;
d->printPretty();
std::cout << (e->remove(395)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
std::cout << (a->remove(286)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->insert(117)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (e->insert(357)) << std::endl;
std::cout << (d->remove(168)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
*d=*c;
std::cout << (e->remove(31)) << std::endl;
std::cout << (c->remove(9)) << std::endl;
std::cout << (a->insert(102)) << std::endl;
*d=*e;
std::cout << (c->insert(164)) << std::endl;
std::cout << (c->remove(341)) << std::endl;
std::cout << (e->remove(125)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
std::cout << (c->remove(247)) << std::endl;
std::cout << (d->remove(240)) << std::endl;
std::cout << (e->remove(322)) << std::endl;
std::cout << (b->insert(429)) << std::endl;
b->printPretty();
std::cout << (b->remove(132)) << std::endl;
*c=*e;
std::cout << (c->remove(42)) << std::endl;
c->printPretty();
*b=*d;
std::cout << (b->remove(340)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
e->printPretty();
*c=*e;
a->printPretty();
std::cout << (a->insert(323)) << std::endl;
e->printPretty();
std::cout << (b->insert(341)) << std::endl;
std::cout << (c->remove(281)) << std::endl;
*a=*e;
*d=*c;
a->printPretty();
std::cout << (d->insert(225)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
e->printPretty();
std::cout << (e->remove(54)) << std::endl;
d->printPretty();
std::cout << (b->remove(247)) << std::endl;
*e=*e;
*e=*d;
std::cout << (d->remove(360)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
std::cout << (c->insert(270)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
*d=*b;
std::cout << (c->remove(477)) << std::endl;
std::cout << (e->insert(77)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
a->printPretty();
std::cout << (a->insert(54)) << std::endl;
a->printPretty();
b->printPretty();
b->printPretty();
std::cout << (b->insert(281)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (b->insert(421)) << std::endl;
*c=*c;
std::cout << (d->remove(233)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
*d=*b;
std::cout << (a->remove(115)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
std::cout << (c->insert(229)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (b->remove(235)) << std::endl;
std::cout << (c->insert(247)) << std::endl;
std::cout << (c->remove(296)) << std::endl;
std::cout << (c->insert(252)) << std::endl;
std::cout << (d->remove(440)) << std::endl;
*b=*e;
std::cout << (a->remove(436)) << std::endl;
*e=*a;
std::cout << (d->insert(477)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
std::cout << (b->remove(354)) << std::endl;
std::cout << (e->insert(341)) << std::endl;
e->printPretty();
e->printPretty();
a->printPretty();
std::cout << (b->remove(203)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (e->insert(218)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
*a=*e;
*b=*a;
b->printPretty();
std::cout << (d->insert(442)) << std::endl;
std::cout << (c->insert(163)) << std::endl;
*b=*d;
std::cout << (e->remove(117)) << std::endl;
*e=*d;
std::cout << (d->remove(15)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->insert(270)) << std::endl;
b->printPretty();
std::cout << (c->remove(392)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
*b=*b;
std::cout << (b->insert(442)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
std::cout << (e->remove(270)) << std::endl;
*c=*a;
std::cout << (e->remove(117)) << std::endl;
*d=*d;
std::cout << (b->insert(442)) << std::endl;
std::cout << (c->remove(247)) << std::endl;
c->printPretty();
std::cout << (b->insert(281)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
*e=*e;
std::cout << (e->insert(493)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
std::cout << (b->remove(421)) << std::endl;
std::cout << (a->insert(117)) << std::endl;
*c=*b;
*e=*b;
std::cout << (c->remove(117)) << std::endl;
d->printPretty();
std::cout << (b->insert(248)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (e->insert(225)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
c->printPretty();
std::cout << (c->remove(366)) << std::endl;
std::cout << (c->insert(477)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
*b=*c;
c->printPretty();
*b=*b;
*d=*c;
*a=*b;
std::cout << (b->insert(357)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
*c=*c;
std::cout << (d->insert(192)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
*d=*c;
std::cout << (c->remove(270)) << std::endl;
std::cout << (c->insert(442)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
*a=*e;
std::cout << (c->insert(480)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
std::cout << (b->remove(324)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
c->printPretty();
std::cout << (a->insert(63)) << std::endl;
std::cout << (e->insert(295)) << std::endl;
d->printPretty();
std::cout << (b->remove(225)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
std::cout << (e->insert(117)) << std::endl;
*d=*b;
std::cout << (d->insert(242)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
c->printPretty();
std::cout << (b->insert(208)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
d->printPretty();
std::cout << (e->insert(153)) << std::endl;
d->printPretty();
std::cout << (a->remove(141)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
std::cout << (b->insert(168)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
std::cout << (d->insert(448)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (d->insert(319)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (b->remove(168)) << std::endl;
a->printPretty();
*e=*e;
*c=*d;
std::cout << (b->remove(8)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
*c=*d;
*b=*c;
return 0;
}
