#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
std::cout << (a->remove(128)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->remove(341)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (b->remove(252)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (a->remove(23)) << std::endl;
a->printPretty();
std::cout << (b->insert(158)) << std::endl;
a->printPretty();
std::cout << (b->remove(380)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
b->printPretty();
std::cout << (b->insert(158)) << std::endl;
a->printPretty();
std::cout << (a->insert(158)) << std::endl;
d->printPretty();
d->printPretty();
*b=*c;
std::cout << (d->insert(245)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (a->insert(158)) << std::endl;
std::cout << (c->remove(455)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
d->printPretty();
std::cout << (a->insert(158)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
*b=*d;
*c=*a;
std::cout << (b->remove(348)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
e->printPretty();
std::cout << (d->insert(242)) << std::endl;
std::cout << (c->insert(248)) << std::endl;
std::cout << (a->insert(426)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
e->printPretty();
std::cout << (e->remove(469)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
e->printPretty();
std::cout << (d->insert(82)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (c->remove(158)) << std::endl;
*a=*e;
c->printPretty();
a->printPretty();
d->printPretty();
std::cout << (d->insert(486)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->remove(403)) << std::endl;
*b=*e;
std::cout << (b->remove(41)) << std::endl;
b->printPretty();
std::cout << (d->insert(486)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (c->remove(248)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (b->remove(165)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (c->remove(165)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
e->printPretty();
std::cout << (a->remove(235)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->insert(437)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
d->printPretty();
*e=*a;
d->printPretty();
std::cout << (c->insert(437)) << std::endl;
*a=*e;
std::cout << (c->remove(483)) << std::endl;
*a=*d;
*e=*e;
std::cout << (d->insert(424)) << std::endl;
std::cout << (a->remove(203)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->remove(487)) << std::endl;
b->printPretty();
std::cout << (b->remove(151)) << std::endl;
*b=*e;
std::cout << (d->insert(149)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (d->insert(149)) << std::endl;
*d=*c;
*d=*e;
*a=*b;
std::cout << (b->remove(102)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
*d=*d;
e->printPretty();
*c=*a;
std::cout << (c->remove(151)) << std::endl;
*c=*a;
std::cout << (c->insert(431)) << std::endl;
std::cout << (b->insert(74)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
c->printPretty();
std::cout << (c->insert(438)) << std::endl;
e->printPretty();
std::cout << (c->insert(133)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (e->insert(120)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (c->insert(431)) << std::endl;
std::cout << (e->insert(246)) << std::endl;
*d=*b;
std::cout << (d->insert(295)) << std::endl;
std::cout << (a->remove(433)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (d->insert(74)) << std::endl;
std::cout << (d->insert(366)) << std::endl;
std::cout << (d->insert(366)) << std::endl;
std::cout << (a->remove(127)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (e->remove(238)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
std::cout << (d->insert(74)) << std::endl;
*d=*b;
std::cout << (d->remove(101)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
*a=*a;
std::cout << (a->remove(159)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (d->insert(265)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
std::cout << (e->remove(31)) << std::endl;
*b=*c;
std::cout << (a->remove(398)) << std::endl;
*e=*d;
std::cout << (b->remove(211)) << std::endl;
std::cout << (d->insert(118)) << std::endl;
*d=*b;
*a=*b;
*e=*e;
*a=*d;
std::cout << (a->insert(214)) << std::endl;
std::cout << (e->remove(74)) << std::endl;
*b=*a;
*b=*d;
std::cout << (b->insert(438)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
*b=*e;
c->printPretty();
*a=*d;
std::cout << (e->remove(55)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
*e=*d;
std::cout << (d->insert(431)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
d->printPretty();
std::cout << (a->remove(294)) << std::endl;
*d=*b;
*b=*d;
std::cout << (c->remove(36)) << std::endl;
d->printPretty();
std::cout << (c->remove(431)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
std::cout << (b->remove(482)) << std::endl;
std::cout << (e->remove(283)) << std::endl;
*c=*c;
*b=*e;
std::cout << (b->remove(151)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
*b=*c;
d->printPretty();
std::cout << (a->remove(38)) << std::endl;
c->printPretty();
std::cout << (a->insert(420)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
std::cout << (e->insert(133)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (d->insert(434)) << std::endl;
std::cout << (d->insert(5)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
a->printPretty();
std::cout << (d->remove(64)) << std::endl;
std::cout << (b->insert(76)) << std::endl;
*c=*a;
std::cout << (e->insert(438)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
*b=*d;
*e=*b;
std::cout << (e->insert(186)) << std::endl;
d->printPretty();
*d=*d;
a->printPretty();
std::cout << (e->remove(401)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
std::cout << (d->insert(5)) << std::endl;
c->printPretty();
*a=*e;
*c=*e;
std::cout << (a->remove(5)) << std::endl;
std::cout << (a->remove(349)) << std::endl;
std::cout << (c->insert(88)) << std::endl;
*c=*e;
c->printPretty();
c->printPretty();
std::cout << (a->insert(434)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (a->remove(104)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
a->printPretty();
std::cout << (d->insert(39)) << std::endl;
std::cout << (c->remove(220)) << std::endl;
*c=*b;
std::cout << (c->insert(239)) << std::endl;
b->printPretty();
std::cout << (c->insert(65)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
std::cout << (c->insert(434)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (d->remove(265)) << std::endl;
*b=*d;
std::cout << (e->insert(434)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
*e=*d;
std::cout << (c->insert(142)) << std::endl;
d->printPretty();
std::cout << (b->insert(53)) << std::endl;
std::cout << (d->remove(39)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
b->printPretty();
std::cout << (b->remove(192)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (d->insert(68)) << std::endl;
std::cout << (b->remove(5)) << std::endl;
std::cout << (b->remove(349)) << std::endl;
std::cout << (c->insert(272)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
*a=*a;
std::cout << (e->remove(84)) << std::endl;
e->printPretty();
e->printPretty();
*d=*d;
c->printPretty();
*a=*b;
std::cout << (d->insert(223)) << std::endl;
std::cout << (b->remove(464)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
std::cout << (d->remove(5)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
std::cout << (e->insert(194)) << std::endl;
*e=*d;
std::cout << (d->remove(68)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
c->printPretty();
std::cout << (a->insert(434)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
*c=*e;
std::cout << (d->remove(90)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
*e=*c;
std::cout << (c->remove(434)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
*c=*b;
std::cout << (d->insert(223)) << std::endl;
*c=*e;
std::cout << (b->insert(402)) << std::endl;
*d=*c;
std::cout << (e->insert(53)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (a->insert(114)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
std::cout << (b->insert(428)) << std::endl;
e->printPretty();
std::cout << (e->remove(53)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
b->printPretty();
std::cout << (c->insert(434)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
*b=*b;
std::cout << (c->insert(114)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
std::cout << (a->insert(39)) << std::endl;
*e=*a;
std::cout << (e->insert(39)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
b->printPretty();
std::cout << (a->remove(223)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
std::cout << (d->remove(318)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
std::cout << (a->insert(496)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(229)) << std::endl;
*a=*c;
std::cout << (e->insert(434)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (a->insert(188)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
std::cout << (c->insert(434)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (b->remove(68)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
std::cout << (b->insert(307)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
*e=*d;
std::cout << (d->insert(223)) << std::endl;
*c=*c;
std::cout << (a->remove(188)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
std::cout << (b->remove(70)) << std::endl;
std::cout << (a->insert(369)) << std::endl;
e->printPretty();
std::cout << (b->insert(307)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
e->printPretty();
std::cout << (c->remove(114)) << std::endl;
std::cout << (c->insert(198)) << std::endl;
d->printPretty();
std::cout << (b->remove(89)) << std::endl;
*c=*b;
std::cout << (d->insert(271)) << std::endl;
std::cout << (e->remove(487)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
std::cout << (c->insert(434)) << std::endl;
*c=*b;
std::cout << (c->insert(294)) << std::endl;
std::cout << (c->insert(229)) << std::endl;
*c=*e;
std::cout << (b->insert(122)) << std::endl;
d->printPretty();
*a=*a;
*a=*a;
d->printPretty();
std::cout << (b->insert(39)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (e->insert(223)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
*c=*c;
std::cout << (d->insert(271)) << std::endl;
std::cout << (d->insert(177)) << std::endl;
*e=*e;
std::cout << (a->insert(49)) << std::endl;
b->printPretty();
std::cout << (d->insert(470)) << std::endl;
std::cout << (b->remove(320)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
std::cout << (e->insert(39)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (d->remove(177)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
std::cout << (a->insert(346)) << std::endl;
std::cout << (a->remove(355)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
b->printPretty();
std::cout << (a->remove(346)) << std::endl;
e->printPretty();
std::cout << (a->insert(237)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
std::cout << (e->insert(140)) << std::endl;
c->printPretty();
std::cout << (b->insert(53)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(492)) << std::endl;
std::cout << (b->remove(74)) << std::endl;
std::cout << (a->insert(34)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (c->remove(39)) << std::endl;
*a=*d;
std::cout << (d->remove(244)) << std::endl;
std::cout << (d->insert(493)) << std::endl;
std::cout << (e->remove(130)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (e->insert(434)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
*b=*c;
std::cout << (c->insert(223)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (c->insert(53)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
*d=*c;
b->printPretty();
*e=*d;
a->printPretty();
a->printPretty();
std::cout << (a->remove(470)) << std::endl;
std::cout << (e->insert(434)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (e->remove(360)) << std::endl;
d->printPretty();
std::cout << (b->insert(33)) << std::endl;
*e=*c;
std::cout << (c->insert(223)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
std::cout << (b->remove(168)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
c->printPretty();
std::cout << (a->insert(71)) << std::endl;
*c=*e;
std::cout << (c->remove(399)) << std::endl;
std::cout << (b->remove(243)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (e->remove(96)) << std::endl;
c->printPretty();
std::cout << (d->remove(53)) << std::endl;
*a=*e;
*e=*a;
d->printPretty();
*b=*d;
*d=*c;
*d=*a;
std::cout << (e->insert(53)) << std::endl;
std::cout << (c->remove(223)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (a->remove(343)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (d->insert(361)) << std::endl;
*c=*c;
std::cout << (b->insert(382)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (d->remove(434)) << std::endl;
std::cout << (c->remove(12)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (b->insert(223)) << std::endl;
*a=*c;
std::cout << (a->remove(404)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
*e=*a;
*e=*d;
b->printPretty();
d->printPretty();
std::cout << (e->remove(53)) << std::endl;
std::cout << (c->remove(363)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->remove(230)) << std::endl;
std::cout << (b->insert(382)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
*e=*c;
std::cout << (b->remove(368)) << std::endl;
std::cout << (c->insert(47)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
a->printPretty();
std::cout << (b->remove(382)) << std::endl;
std::cout << (b->remove(458)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
*a=*b;
*d=*e;
std::cout << (d->remove(101)) << std::endl;
std::cout << (c->insert(107)) << std::endl;
*d=*e;
std::cout << (d->remove(311)) << std::endl;
d->printPretty();
std::cout << (a->insert(465)) << std::endl;
std::cout << (c->insert(199)) << std::endl;
std::cout << (a->remove(465)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (a->insert(204)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
std::cout << (b->remove(127)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->insert(59)) << std::endl;
a->printPretty();
std::cout << (b->remove(133)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
*d=*c;
*d=*a;
c->printPretty();
std::cout << (b->insert(283)) << std::endl;
std::cout << (d->remove(204)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
*e=*b;
std::cout << (c->insert(449)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (c->remove(199)) << std::endl;
*d=*d;
std::cout << (e->insert(406)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
std::cout << (a->remove(127)) << std::endl;
b->printPretty();
std::cout << (c->insert(486)) << std::endl;
e->printPretty();
std::cout << (b->insert(223)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
std::cout << (a->insert(24)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
b->printPretty();
std::cout << (d->remove(395)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
b->printPretty();
std::cout << (d->remove(330)) << std::endl;
*c=*d;
std::cout << (a->insert(125)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->remove(406)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
std::cout << (d->insert(66)) << std::endl;
c->printPretty();
e->printPretty();
*e=*a;
std::cout << (e->remove(407)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
std::cout << (a->insert(102)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
*a=*a;
*c=*e;
d->printPretty();
std::cout << (c->remove(55)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (b->insert(163)) << std::endl;
std::cout << (e->remove(252)) << std::endl;
std::cout << (a->insert(251)) << std::endl;
*d=*e;
std::cout << (e->remove(295)) << std::endl;
*c=*b;
std::cout << (a->insert(434)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (b->remove(103)) << std::endl;
a->printPretty();
std::cout << (b->insert(163)) << std::endl;
e->printPretty();
std::cout << (d->insert(381)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
std::cout << (d->insert(458)) << std::endl;
std::cout << (d->remove(458)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
std::cout << (c->remove(58)) << std::endl;
std::cout << (d->insert(434)) << std::endl;
std::cout << (a->remove(204)) << std::endl;
std::cout << (b->insert(225)) << std::endl;
b->printPretty();
std::cout << (e->insert(35)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
*e=*c;
c->printPretty();
std::cout << (c->remove(163)) << std::endl;
d->printPretty();
std::cout << (c->insert(221)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
a->printPretty();
*e=*c;
*e=*d;
std::cout << (d->remove(134)) << std::endl;
*d=*b;
*b=*a;
std::cout << (a->insert(177)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
*e=*a;
std::cout << (a->remove(223)) << std::endl;
c->printPretty();
*a=*c;
std::cout << (b->remove(264)) << std::endl;
*a=*e;
std::cout << (b->insert(125)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
std::cout << (d->insert(163)) << std::endl;
*c=*a;
std::cout << (a->insert(24)) << std::endl;
*b=*e;
std::cout << (a->remove(436)) << std::endl;
std::cout << (b->insert(24)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
std::cout << (d->insert(50)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
*b=*d;
std::cout << (d->remove(191)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
std::cout << (c->insert(248)) << std::endl;
std::cout << (b->remove(110)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (b->remove(328)) << std::endl;
e->printPretty();
std::cout << (a->remove(376)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
d->printPretty();
std::cout << (a->remove(372)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
std::cout << (c->insert(129)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
b->printPretty();
std::cout << (d->remove(163)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
std::cout << (c->insert(129)) << std::endl;
*b=*b;
std::cout << (c->insert(406)) << std::endl;
*a=*b;
std::cout << (c->remove(129)) << std::endl;
*b=*b;
std::cout << (b->remove(283)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
*e=*e;
std::cout << (e->remove(295)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
std::cout << (a->remove(172)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
return 0;
}
