#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(73)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
a->printPretty();
*e=*a;
std::cout << (c->remove(133)) << std::endl;
c->printPretty();
std::cout << (d->insert(10)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->insert(452)) << std::endl;
std::cout << (e->insert(123)) << std::endl;
b->printPretty();
std::cout << (d->insert(10)) << std::endl;
std::cout << (e->remove(123)) << std::endl;
*c=*e;
*a=*a;
std::cout << (d->remove(30)) << std::endl;
e->printPretty();
*d=*a;
e->printPretty();
std::cout << (a->remove(452)) << std::endl;
*d=*e;
*c=*b;
c->printPretty();
std::cout << (d->remove(322)) << std::endl;
e->printPretty();
std::cout << (c->remove(452)) << std::endl;
*e=*a;
std::cout << (e->insert(99)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
b->printPretty();
std::cout << (c->insert(144)) << std::endl;
e->printPretty();
std::cout << (a->remove(459)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(150)) << std::endl;
std::cout << (c->remove(348)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (c->insert(144)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (a->insert(71)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (a->remove(409)) << std::endl;
b->printPretty();
std::cout << (b->remove(92)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (e->remove(118)) << std::endl;
c->printPretty();
std::cout << (e->insert(105)) << std::endl;
c->printPretty();
std::cout << (a->insert(71)) << std::endl;
*e=*e;
std::cout << (d->remove(131)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
std::cout << (d->remove(3)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (a->insert(391)) << std::endl;
*e=*e;
std::cout << (d->insert(381)) << std::endl;
std::cout << (a->insert(71)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
std::cout << (b->insert(452)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
*d=*e;
*c=*a;
*a=*b;
std::cout << (d->remove(290)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
*b=*a;
std::cout << (a->remove(452)) << std::endl;
std::cout << (b->insert(452)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
*c=*a;
std::cout << (e->insert(105)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->insert(452)) << std::endl;
*b=*c;
*d=*e;
e->printPretty();
std::cout << (a->remove(90)) << std::endl;
std::cout << (b->remove(112)) << std::endl;
b->printPretty();
std::cout << (d->remove(99)) << std::endl;
b->printPretty();
c->printPretty();
*d=*b;
std::cout << (d->insert(271)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
std::cout << (a->remove(337)) << std::endl;
d->printPretty();
*a=*c;
*b=*d;
std::cout << (d->insert(379)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (d->remove(271)) << std::endl;
std::cout << (b->remove(447)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
*c=*a;
std::cout << (c->remove(271)) << std::endl;
*e=*b;
a->printPretty();
c->printPretty();
std::cout << (c->remove(379)) << std::endl;
std::cout << (e->remove(388)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
*c=*b;
*c=*b;
std::cout << (b->insert(271)) << std::endl;
b->printPretty();
*b=*a;
*e=*b;
std::cout << (c->remove(320)) << std::endl;
std::cout << (c->remove(199)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
*d=*a;
std::cout << (d->remove(365)) << std::endl;
std::cout << (c->insert(271)) << std::endl;
std::cout << (d->insert(489)) << std::endl;
d->printPretty();
std::cout << (a->remove(107)) << std::endl;
std::cout << (c->insert(271)) << std::endl;
std::cout << (b->remove(343)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
e->printPretty();
std::cout << (e->insert(412)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
*c=*a;
std::cout << (d->remove(379)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
d->printPretty();
std::cout << (b->remove(423)) << std::endl;
std::cout << (e->remove(408)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
a->printPretty();
std::cout << (e->insert(298)) << std::endl;
std::cout << (c->remove(361)) << std::endl;
std::cout << (a->remove(236)) << std::endl;
std::cout << (a->remove(379)) << std::endl;
b->printPretty();
b->printPretty();
*c=*a;
std::cout << (a->remove(13)) << std::endl;
std::cout << (d->remove(432)) << std::endl;
a->printPretty();
std::cout << (b->insert(379)) << std::endl;
std::cout << (e->insert(412)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
std::cout << (d->insert(84)) << std::endl;
std::cout << (d->remove(84)) << std::endl;
*a=*c;
*a=*b;
a->printPretty();
std::cout << (e->remove(135)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
*c=*a;
std::cout << (e->insert(412)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (a->insert(242)) << std::endl;
b->printPretty();
std::cout << (c->remove(379)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
e->printPretty();
*d=*c;
d->printPretty();
std::cout << (a->insert(242)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
std::cout << (d->insert(227)) << std::endl;
a->printPretty();
std::cout << (d->insert(438)) << std::endl;
*a=*a;
*c=*b;
std::cout << (d->insert(271)) << std::endl;
*e=*c;
std::cout << (d->insert(157)) << std::endl;
c->printPretty();
std::cout << (e->insert(379)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
e->printPretty();
*a=*e;
std::cout << (b->remove(379)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (e->remove(132)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
std::cout << (a->remove(136)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
*a=*a;
std::cout << (b->remove(266)) << std::endl;
std::cout << (e->insert(244)) << std::endl;
d->printPretty();
std::cout << (a->insert(395)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
b->printPretty();
std::cout << (a->insert(395)) << std::endl;
std::cout << (e->insert(244)) << std::endl;
std::cout << (b->remove(330)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
std::cout << (a->remove(379)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
*a=*d;
std::cout << (d->remove(431)) << std::endl;
std::cout << (c->remove(309)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (a->insert(379)) << std::endl;
d->printPretty();
std::cout << (e->remove(325)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
std::cout << (e->remove(69)) << std::endl;
e->printPretty();
std::cout << (a->insert(1)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
c->printPretty();
std::cout << (a->insert(379)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
a->printPretty();
std::cout << (b->insert(227)) << std::endl;
c->printPretty();
*d=*e;
std::cout << (b->remove(227)) << std::endl;
*d=*a;
std::cout << (a->insert(1)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
*b=*b;
*c=*c;
std::cout << (c->insert(271)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->remove(98)) << std::endl;
std::cout << (d->insert(361)) << std::endl;
*b=*e;
*b=*a;
std::cout << (d->remove(1)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
std::cout << (c->remove(271)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
c->printPretty();
*c=*c;
b->printPretty();
std::cout << (b->insert(7)) << std::endl;
std::cout << (d->insert(361)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (a->remove(38)) << std::endl;
std::cout << (a->remove(379)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
std::cout << (b->remove(7)) << std::endl;
*e=*c;
std::cout << (d->insert(311)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
std::cout << (b->insert(379)) << std::endl;
*e=*c;
std::cout << (e->remove(320)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
c->printPretty();
std::cout << (a->insert(1)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (d->remove(311)) << std::endl;
*b=*d;
std::cout << (e->remove(482)) << std::endl;
*d=*b;
*e=*d;
*b=*d;
std::cout << (e->insert(361)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
*a=*e;
*b=*c;
*b=*d;
std::cout << (e->insert(361)) << std::endl;
d->printPretty();
std::cout << (d->remove(284)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (e->remove(122)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (c->remove(422)) << std::endl;
*d=*b;
std::cout << (b->insert(5)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
*e=*b;
std::cout << (b->insert(203)) << std::endl;
std::cout << (c->remove(110)) << std::endl;
*c=*c;
std::cout << (a->insert(361)) << std::endl;
std::cout << (d->remove(379)) << std::endl;
*c=*e;
std::cout << (d->insert(10)) << std::endl;
std::cout << (e->insert(5)) << std::endl;
std::cout << (e->insert(98)) << std::endl;
std::cout << (b->insert(98)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
std::cout << (b->insert(98)) << std::endl;
*d=*d;
std::cout << (e->insert(68)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->insert(42)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
*e=*e;
std::cout << (c->insert(210)) << std::endl;
*d=*a;
std::cout << (d->insert(394)) << std::endl;
std::cout << (c->insert(116)) << std::endl;
*c=*a;
std::cout << (d->insert(22)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (c->insert(98)) << std::endl;
std::cout << (b->remove(98)) << std::endl;
std::cout << (d->remove(394)) << std::endl;
*c=*b;
std::cout << (a->remove(493)) << std::endl;
*a=*d;
std::cout << (c->remove(80)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
std::cout << (b->insert(73)) << std::endl;
a->printPretty();
std::cout << (d->remove(493)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
b->printPretty();
std::cout << (b->remove(5)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
c->printPretty();
std::cout << (d->remove(79)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (c->remove(272)) << std::endl;
std::cout << (a->insert(98)) << std::endl;
std::cout << (e->remove(98)) << std::endl;
c->printPretty();
d->printPretty();
d->printPretty();
std::cout << (b->remove(73)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
*c=*d;
std::cout << (c->insert(22)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (c->insert(483)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
e->printPretty();
std::cout << (e->remove(299)) << std::endl;
*c=*b;
*e=*e;
std::cout << (e->insert(361)) << std::endl;
*b=*e;
std::cout << (d->remove(98)) << std::endl;
d->printPretty();
std::cout << (b->remove(361)) << std::endl;
std::cout << (a->remove(443)) << std::endl;
c->printPretty();
std::cout << (e->insert(117)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
a->printPretty();
std::cout << (a->insert(379)) << std::endl;
std::cout << (a->insert(391)) << std::endl;
e->printPretty();
d->printPretty();
*c=*d;
std::cout << (e->remove(117)) << std::endl;
e->printPretty();
a->printPretty();
b->printPretty();
d->printPretty();
std::cout << (a->insert(379)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
std::cout << (c->insert(313)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
std::cout << (d->remove(351)) << std::endl;
*b=*c;
std::cout << (b->insert(42)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
c->printPretty();
e->printPretty();
*c=*b;
std::cout << (a->remove(31)) << std::endl;
std::cout << (b->insert(342)) << std::endl;
*b=*c;
std::cout << (e->remove(134)) << std::endl;
std::cout << (d->insert(11)) << std::endl;
std::cout << (d->insert(11)) << std::endl;
std::cout << (b->remove(313)) << std::endl;
e->printPretty();
std::cout << (a->remove(493)) << std::endl;
*c=*e;
std::cout << (a->remove(117)) << std::endl;
std::cout << (a->insert(105)) << std::endl;
std::cout << (a->remove(22)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
c->printPretty();
*d=*b;
*a=*b;
std::cout << (c->insert(220)) << std::endl;
std::cout << (e->insert(26)) << std::endl;
std::cout << (b->remove(215)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (e->insert(26)) << std::endl;
*b=*a;
std::cout << (d->insert(488)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
*a=*c;
c->printPretty();
*b=*c;
std::cout << (c->remove(361)) << std::endl;
std::cout << (c->remove(220)) << std::endl;
*c=*e;
std::cout << (b->remove(361)) << std::endl;
e->printPretty();
std::cout << (b->insert(220)) << std::endl;
*a=*c;
std::cout << (d->insert(42)) << std::endl;
*d=*e;
std::cout << (b->remove(164)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
std::cout << (b->insert(220)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
std::cout << (a->insert(361)) << std::endl;
*a=*b;
*c=*c;
*b=*d;
std::cout << (c->insert(137)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->insert(58)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
std::cout << (c->remove(361)) << std::endl;
std::cout << (a->insert(482)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
std::cout << (a->insert(482)) << std::endl;
b->printPretty();
std::cout << (d->insert(78)) << std::endl;
std::cout << (b->remove(301)) << std::endl;
std::cout << (e->remove(231)) << std::endl;
*b=*e;
std::cout << (c->insert(331)) << std::endl;
std::cout << (d->remove(58)) << std::endl;
e->printPretty();
std::cout << (b->remove(137)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
*b=*c;
*a=*a;
*d=*c;
*a=*b;
e->printPretty();
*b=*d;
std::cout << (e->insert(361)) << std::endl;
c->printPretty();
std::cout << (a->remove(331)) << std::endl;
*a=*b;
*d=*d;
std::cout << (e->insert(26)) << std::endl;
std::cout << (d->insert(331)) << std::endl;
d->printPretty();
*c=*a;
*b=*a;
std::cout << (e->remove(130)) << std::endl;
c->printPretty();
std::cout << (d->insert(137)) << std::endl;
std::cout << (c->remove(222)) << std::endl;
*e=*b;
*a=*e;
b->printPretty();
std::cout << (a->insert(322)) << std::endl;
std::cout << (e->remove(137)) << std::endl;
std::cout << (e->remove(86)) << std::endl;
std::cout << (a->remove(26)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
a->printPretty();
std::cout << (b->remove(20)) << std::endl;
d->printPretty();
std::cout << (c->remove(40)) << std::endl;
std::cout << (a->insert(137)) << std::endl;
*a=*a;
std::cout << (c->insert(137)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (c->insert(26)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(260)) << std::endl;
std::cout << (e->insert(252)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (c->insert(182)) << std::endl;
*e=*e;
std::cout << (c->insert(133)) << std::endl;
e->printPretty();
std::cout << (d->remove(486)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (a->insert(171)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->remove(214)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
std::cout << (e->remove(26)) << std::endl;
std::cout << (e->insert(252)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
a->printPretty();
std::cout << (a->insert(249)) << std::endl;
std::cout << (e->insert(252)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
std::cout << (b->insert(220)) << std::endl;
std::cout << (e->insert(331)) << std::endl;
std::cout << (b->insert(26)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
std::cout << (e->remove(252)) << std::endl;
c->printPretty();
c->printPretty();
e->printPretty();
std::cout << (c->insert(160)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (c->remove(439)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
*d=*a;
*c=*c;
std::cout << (d->insert(497)) << std::endl;
*b=*c;
std::cout << (b->remove(300)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (a->remove(249)) << std::endl;
std::cout << (e->remove(413)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
*b=*d;
*a=*e;
std::cout << (c->insert(73)) << std::endl;
*c=*d;
std::cout << (b->insert(258)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
std::cout << (d->insert(311)) << std::endl;
*c=*d;
*e=*a;
*a=*e;
std::cout << (c->remove(311)) << std::endl;
*a=*d;
std::cout << (c->remove(249)) << std::endl;
*e=*d;
std::cout << (e->remove(238)) << std::endl;
std::cout << (d->remove(171)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
*a=*c;
std::cout << (a->remove(300)) << std::endl;
std::cout << (e->remove(161)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
*c=*e;
std::cout << (c->insert(249)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (d->insert(331)) << std::endl;
std::cout << (a->remove(171)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
std::cout << (e->insert(396)) << std::endl;
std::cout << (c->insert(418)) << std::endl;
a->printPretty();
std::cout << (a->insert(359)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (e->insert(437)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
std::cout << (e->insert(331)) << std::endl;
std::cout << (c->remove(344)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
std::cout << (b->remove(497)) << std::endl;
d->printPretty();
std::cout << (c->remove(162)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
std::cout << (d->insert(374)) << std::endl;
std::cout << (b->remove(249)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
*d=*b;
std::cout << (e->remove(497)) << std::endl;
e->printPretty();
std::cout << (d->insert(258)) << std::endl;
*a=*a;
std::cout << (d->insert(396)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
std::cout << (d->insert(425)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (b->insert(488)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
a->printPretty();
std::cout << (e->insert(311)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
std::cout << (d->remove(171)) << std::endl;
std::cout << (a->insert(217)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->insert(469)) << std::endl;
*a=*b;
*b=*e;
std::cout << (e->insert(142)) << std::endl;
std::cout << (e->insert(361)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
std::cout << (e->insert(233)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
*b=*d;
std::cout << (e->insert(233)) << std::endl;
std::cout << (e->remove(87)) << std::endl;
std::cout << (a->remove(424)) << std::endl;
*c=*a;
std::cout << (e->remove(478)) << std::endl;
std::cout << (e->insert(376)) << std::endl;
std::cout << (a->remove(331)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
std::cout << (e->remove(311)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (b->remove(180)) << std::endl;
std::cout << (a->insert(124)) << std::endl;
std::cout << (a->insert(302)) << std::endl;
e->printPretty();
std::cout << (c->remove(488)) << std::endl;
c->printPretty();
std::cout << (c->remove(258)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
b->printPretty();
std::cout << (c->insert(322)) << std::endl;
*d=*e;
*d=*b;
std::cout << (b->remove(381)) << std::endl;
a->printPretty();
std::cout << (b->remove(322)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
b->printPretty();
std::cout << (a->remove(322)) << std::endl;
c->printPretty();
std::cout << (d->insert(396)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (a->remove(54)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
*d=*e;
std::cout << (a->insert(190)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (b->remove(286)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->remove(138)) << std::endl;
std::cout << (e->insert(233)) << std::endl;
d->printPretty();
std::cout << (a->remove(396)) << std::endl;
e->printPretty();
std::cout << (b->insert(196)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
std::cout << (d->remove(437)) << std::endl;
*a=*b;
*e=*b;
std::cout << (c->remove(1)) << std::endl;
*e=*d;
b->printPretty();
*c=*d;
b->printPretty();
std::cout << (e->insert(449)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (b->remove(171)) << std::endl;
std::cout << (a->remove(136)) << std::endl;
std::cout << (b->remove(396)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
*a=*b;
std::cout << (a->remove(196)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
b->printPretty();
std::cout << (b->remove(488)) << std::endl;
std::cout << (a->remove(292)) << std::endl;
c->printPretty();
std::cout << (e->insert(396)) << std::endl;
*a=*b;
std::cout << (b->remove(74)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (e->insert(334)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
d->printPretty();
return 0;
}
