#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
*a=*a;
std::cout << (a->insert(409)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
a->printPretty();
std::cout << (a->insert(223)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
*a=*c;
std::cout << (c->remove(84)) << std::endl;
*a=*c;
std::cout << (b->insert(333)) << std::endl;
std::cout << (a->insert(463)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
std::cout << (c->remove(156)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
*b=*b;
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (c->remove(283)) << std::endl;
std::cout << (b->remove(333)) << std::endl;
std::cout << (c->remove(443)) << std::endl;
std::cout << (d->remove(333)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (c->insert(409)) << std::endl;
d->printPretty();
std::cout << (e->insert(409)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (c->remove(309)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
std::cout << (d->insert(30)) << std::endl;
e->printPretty();
std::cout << (c->insert(470)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (d->remove(130)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
c->printPretty();
b->printPretty();
*a=*e;
*b=*c;
std::cout << (a->insert(223)) << std::endl;
std::cout << (c->remove(136)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
std::cout << (b->insert(303)) << std::endl;
std::cout << (a->insert(239)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
*a=*e;
std::cout << (a->remove(391)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (e->insert(409)) << std::endl;
std::cout << (b->insert(134)) << std::endl;
c->printPretty();
*a=*e;
std::cout << (b->remove(196)) << std::endl;
a->printPretty();
std::cout << (e->insert(223)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
*b=*e;
std::cout << (e->remove(223)) << std::endl;
e->printPretty();
*b=*a;
b->printPretty();
*a=*e;
std::cout << (e->insert(409)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
std::cout << (d->insert(30)) << std::endl;
std::cout << (e->remove(73)) << std::endl;
std::cout << (e->remove(238)) << std::endl;
std::cout << (c->remove(281)) << std::endl;
c->printPretty();
d->printPretty();
b->printPretty();
*d=*d;
std::cout << (d->remove(324)) << std::endl;
std::cout << (d->insert(490)) << std::endl;
*d=*b;
std::cout << (d->insert(409)) << std::endl;
std::cout << (a->remove(435)) << std::endl;
*c=*e;
std::cout << (a->remove(409)) << std::endl;
std::cout << (d->remove(112)) << std::endl;
e->printPretty();
std::cout << (d->insert(184)) << std::endl;
std::cout << (b->remove(288)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
*a=*e;
std::cout << (c->insert(438)) << std::endl;
b->printPretty();
std::cout << (d->remove(288)) << std::endl;
*e=*b;
*e=*e;
std::cout << (e->remove(459)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (c->remove(409)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
std::cout << (b->remove(409)) << std::endl;
std::cout << (b->insert(223)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (d->insert(208)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
std::cout << (b->insert(223)) << std::endl;
d->printPretty();
std::cout << (b->insert(230)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
e->printPretty();
std::cout << (e->insert(357)) << std::endl;
std::cout << (e->remove(242)) << std::endl;
b->printPretty();
std::cout << (e->insert(223)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (d->remove(379)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (c->remove(403)) << std::endl;
std::cout << (d->remove(487)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (d->remove(223)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
std::cout << (a->remove(409)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
d->printPretty();
*e=*b;
e->printPretty();
std::cout << (c->remove(100)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
d->printPretty();
std::cout << (e->remove(265)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
*a=*a;
std::cout << (e->insert(116)) << std::endl;
std::cout << (b->remove(160)) << std::endl;
b->printPretty();
std::cout << (a->remove(44)) << std::endl;
*d=*c;
*a=*d;
std::cout << (a->remove(263)) << std::endl;
*b=*c;
std::cout << (b->insert(170)) << std::endl;
a->printPretty();
std::cout << (e->insert(223)) << std::endl;
e->printPretty();
std::cout << (d->insert(465)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->insert(439)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
*c=*c;
std::cout << (c->remove(439)) << std::endl;
std::cout << (e->remove(230)) << std::endl;
a->printPretty();
std::cout << (e->remove(116)) << std::endl;
std::cout << (d->insert(489)) << std::endl;
e->printPretty();
std::cout << (b->remove(439)) << std::endl;
*d=*d;
std::cout << (d->insert(489)) << std::endl;
c->printPretty();
std::cout << (d->remove(489)) << std::endl;
*b=*a;
*e=*c;
std::cout << (a->insert(177)) << std::endl;
*a=*b;
std::cout << (d->insert(465)) << std::endl;
b->printPretty();
std::cout << (d->insert(465)) << std::endl;
*d=*d;
std::cout << (b->remove(354)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
*b=*a;
*a=*a;
std::cout << (a->remove(82)) << std::endl;
e->printPretty();
c->printPretty();
b->printPretty();
d->printPretty();
std::cout << (d->insert(232)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
std::cout << (d->remove(465)) << std::endl;
b->printPretty();
std::cout << (b->remove(212)) << std::endl;
std::cout << (c->insert(410)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->insert(53)) << std::endl;
e->printPretty();
a->printPretty();
*e=*e;
std::cout << (c->remove(410)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->insert(184)) << std::endl;
std::cout << (a->insert(60)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
*b=*d;
std::cout << (c->remove(277)) << std::endl;
b->printPretty();
std::cout << (c->insert(272)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (a->remove(327)) << std::endl;
a->printPretty();
std::cout << (a->remove(60)) << std::endl;
b->printPretty();
std::cout << (d->remove(184)) << std::endl;
d->printPretty();
std::cout << (b->remove(473)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (c->remove(272)) << std::endl;
*c=*a;
std::cout << (d->remove(232)) << std::endl;
c->printPretty();
std::cout << (a->insert(489)) << std::endl;
std::cout << (d->insert(420)) << std::endl;
std::cout << (c->insert(64)) << std::endl;
std::cout << (a->insert(183)) << std::endl;
std::cout << (a->insert(183)) << std::endl;
c->printPretty();
std::cout << (a->insert(97)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (c->remove(413)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
std::cout << (a->insert(183)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
e->printPretty();
std::cout << (a->insert(489)) << std::endl;
*c=*e;
*d=*e;
std::cout << (b->remove(370)) << std::endl;
*a=*d;
*c=*e;
a->printPretty();
std::cout << (b->insert(444)) << std::endl;
c->printPretty();
*a=*d;
*c=*d;
std::cout << (c->remove(401)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->insert(287)) << std::endl;
*e=*d;
std::cout << (e->insert(287)) << std::endl;
std::cout << (e->remove(287)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (b->insert(184)) << std::endl;
*b=*c;
std::cout << (a->remove(418)) << std::endl;
*a=*c;
*d=*d;
std::cout << (d->remove(203)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (b->insert(50)) << std::endl;
*b=*d;
c->printPretty();
c->printPretty();
std::cout << (d->insert(111)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
std::cout << (b->insert(383)) << std::endl;
d->printPretty();
e->printPretty();
a->printPretty();
*e=*a;
std::cout << (c->remove(385)) << std::endl;
std::cout << (c->remove(20)) << std::endl;
*c=*e;
std::cout << (b->remove(90)) << std::endl;
*a=*c;
e->printPretty();
*b=*d;
b->printPretty();
*c=*d;
*d=*a;
d->printPretty();
std::cout << (a->insert(184)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
std::cout << (e->insert(278)) << std::endl;
std::cout << (a->insert(198)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
*a=*a;
std::cout << (b->insert(444)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
std::cout << (c->insert(136)) << std::endl;
*d=*e;
*d=*c;
std::cout << (c->remove(449)) << std::endl;
std::cout << (c->insert(232)) << std::endl;
std::cout << (c->remove(38)) << std::endl;
*a=*e;
std::cout << (d->insert(232)) << std::endl;
std::cout << (c->remove(456)) << std::endl;
e->printPretty();
std::cout << (c->remove(136)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
std::cout << (e->insert(482)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
b->printPretty();
std::cout << (b->remove(182)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
*e=*c;
*b=*d;
c->printPretty();
std::cout << (d->remove(16)) << std::endl;
std::cout << (e->insert(176)) << std::endl;
std::cout << (b->insert(73)) << std::endl;
e->printPretty();
*a=*b;
a->printPretty();
a->printPretty();
std::cout << (e->remove(111)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
e->printPretty();
std::cout << (c->remove(41)) << std::endl;
*e=*c;
std::cout << (c->insert(444)) << std::endl;
std::cout << (c->remove(111)) << std::endl;
a->printPretty();
std::cout << (c->insert(232)) << std::endl;
*b=*c;
std::cout << (d->remove(111)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
*b=*d;
std::cout << (e->remove(399)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (a->insert(111)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
*b=*c;
std::cout << (b->remove(497)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
b->printPretty();
std::cout << (c->remove(195)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
std::cout << (b->remove(286)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (c->insert(132)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (e->remove(68)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
*a=*d;
std::cout << (c->remove(83)) << std::endl;
*a=*a;
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->remove(117)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (c->insert(209)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (c->insert(423)) << std::endl;
std::cout << (e->remove(475)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (b->insert(315)) << std::endl;
*d=*d;
std::cout << (e->insert(325)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (b->insert(227)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
*e=*d;
std::cout << (b->remove(456)) << std::endl;
a->printPretty();
*e=*d;
std::cout << (d->insert(396)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (c->remove(82)) << std::endl;
e->printPretty();
std::cout << (d->remove(295)) << std::endl;
std::cout << (e->remove(396)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (b->insert(254)) << std::endl;
std::cout << (a->remove(200)) << std::endl;
std::cout << (b->remove(333)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
std::cout << (d->insert(200)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
c->printPretty();
std::cout << (d->insert(184)) << std::endl;
*d=*d;
std::cout << (c->insert(107)) << std::endl;
d->printPretty();
std::cout << (d->remove(312)) << std::endl;
std::cout << (a->insert(4)) << std::endl;
*e=*e;
std::cout << (b->insert(389)) << std::endl;
std::cout << (c->remove(232)) << std::endl;
*c=*e;
*b=*a;
std::cout << (d->remove(429)) << std::endl;
std::cout << (b->remove(4)) << std::endl;
std::cout << (d->remove(20)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (e->insert(377)) << std::endl;
*c=*b;
std::cout << (d->insert(184)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
std::cout << (b->insert(43)) << std::endl;
std::cout << (e->remove(115)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (e->remove(382)) << std::endl;
*a=*d;
std::cout << (a->remove(240)) << std::endl;
std::cout << (c->insert(274)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (d->remove(232)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (c->remove(274)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
std::cout << (b->remove(43)) << std::endl;
e->printPretty();
*d=*d;
std::cout << (e->insert(16)) << std::endl;
*a=*a;
b->printPretty();
e->printPretty();
std::cout << (a->insert(62)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->remove(377)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
a->printPretty();
std::cout << (a->remove(232)) << std::endl;
std::cout << (e->remove(16)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
*b=*a;
std::cout << (b->remove(200)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (d->remove(200)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
e->printPretty();
std::cout << (c->remove(426)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (c->remove(23)) << std::endl;
std::cout << (c->insert(15)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (d->remove(296)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
c->printPretty();
c->printPretty();
*b=*a;
std::cout << (d->insert(444)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
std::cout << (d->remove(418)) << std::endl;
a->printPretty();
c->printPretty();
c->printPretty();
d->printPretty();
*d=*a;
std::cout << (d->insert(449)) << std::endl;
std::cout << (c->insert(15)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (c->remove(268)) << std::endl;
d->printPretty();
std::cout << (d->remove(307)) << std::endl;
std::cout << (a->remove(200)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
c->printPretty();
std::cout << (e->remove(301)) << std::endl;
std::cout << (c->remove(15)) << std::endl;
*d=*e;
std::cout << (b->remove(76)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
std::cout << (c->insert(252)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
*b=*b;
std::cout << (c->remove(252)) << std::endl;
d->printPretty();
std::cout << (d->remove(184)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
std::cout << (b->remove(362)) << std::endl;
std::cout << (a->insert(96)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
*e=*c;
std::cout << (a->remove(444)) << std::endl;
std::cout << (b->remove(251)) << std::endl;
std::cout << (b->insert(22)) << std::endl;
*c=*b;
std::cout << (e->insert(332)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
e->printPretty();
std::cout << (d->insert(306)) << std::endl;
a->printPretty();
std::cout << (b->insert(449)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (c->remove(486)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
d->printPretty();
std::cout << (c->remove(200)) << std::endl;
*e=*c;
c->printPretty();
std::cout << (b->insert(22)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
*a=*d;
std::cout << (b->remove(246)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (b->remove(396)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
*e=*a;
std::cout << (d->remove(306)) << std::endl;
*e=*a;
std::cout << (a->insert(286)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
e->printPretty();
std::cout << (b->remove(449)) << std::endl;
*b=*e;
std::cout << (b->insert(270)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
c->printPretty();
std::cout << (c->insert(391)) << std::endl;
e->printPretty();
std::cout << (a->remove(184)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
b->printPretty();
std::cout << (a->insert(6)) << std::endl;
e->printPretty();
std::cout << (e->remove(370)) << std::endl;
*c=*d;
std::cout << (a->insert(306)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (b->remove(270)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
*a=*b;
std::cout << (b->remove(184)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
std::cout << (b->remove(180)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (b->insert(48)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
*c=*b;
std::cout << (b->remove(48)) << std::endl;
e->printPretty();
*e=*c;
b->printPretty();
std::cout << (b->remove(357)) << std::endl;
std::cout << (a->remove(22)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->insert(51)) << std::endl;
*e=*a;
std::cout << (d->insert(208)) << std::endl;
c->printPretty();
std::cout << (e->remove(75)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (b->remove(49)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
std::cout << (b->insert(306)) << std::endl;
c->printPretty();
b->printPretty();
*c=*d;
std::cout << (b->insert(306)) << std::endl;
*a=*d;
*a=*d;
std::cout << (c->insert(184)) << std::endl;
*d=*e;
*e=*c;
e->printPretty();
std::cout << (d->remove(184)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
*b=*d;
std::cout << (a->remove(208)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
e->printPretty();
std::cout << (d->remove(234)) << std::endl;
*a=*b;
std::cout << (e->insert(184)) << std::endl;
*a=*c;
std::cout << (e->insert(136)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (b->remove(298)) << std::endl;
a->printPretty();
d->printPretty();
*c=*a;
std::cout << (a->insert(475)) << std::endl;
std::cout << (e->insert(398)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
*c=*b;
std::cout << (e->insert(357)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (e->insert(398)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
std::cout << (b->remove(391)) << std::endl;
a->printPretty();
a->printPretty();
*c=*c;
*c=*b;
*e=*a;
d->printPretty();
std::cout << (e->remove(357)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
*b=*d;
std::cout << (c->insert(497)) << std::endl;
b->printPretty();
std::cout << (e->insert(34)) << std::endl;
d->printPretty();
std::cout << (c->remove(497)) << std::endl;
d->printPretty();
std::cout << (d->insert(124)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
*c=*b;
std::cout << (d->insert(324)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
std::cout << (b->insert(379)) << std::endl;
std::cout << (d->insert(124)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (e->insert(240)) << std::endl;
return 0;
}
