#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(460)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->insert(410)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
std::cout << (a->remove(410)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (a->remove(11)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (a->remove(308)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (d->insert(469)) << std::endl;
std::cout << (a->remove(308)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (a->remove(236)) << std::endl;
*e=*e;
*b=*d;
std::cout << (a->insert(213)) << std::endl;
std::cout << (a->insert(169)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
std::cout << (c->remove(217)) << std::endl;
b->printPretty();
std::cout << (a->insert(400)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (c->remove(465)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (d->remove(96)) << std::endl;
std::cout << (c->insert(384)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
std::cout << (c->remove(384)) << std::endl;
*c=*d;
std::cout << (b->insert(114)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
std::cout << (c->insert(268)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (c->insert(268)) << std::endl;
e->printPretty();
std::cout << (c->insert(337)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
d->printPretty();
std::cout << (b->remove(114)) << std::endl;
c->printPretty();
std::cout << (c->remove(239)) << std::endl;
*e=*b;
c->printPretty();
*c=*e;
*b=*c;
std::cout << (d->remove(88)) << std::endl;
b->printPretty();
*e=*b;
*b=*b;
*c=*d;
std::cout << (d->insert(109)) << std::endl;
c->printPretty();
std::cout << (a->insert(236)) << std::endl;
a->printPretty();
std::cout << (e->insert(333)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
std::cout << (c->remove(435)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
*b=*b;
std::cout << (a->insert(277)) << std::endl;
*c=*c;
*d=*d;
*c=*d;
std::cout << (d->insert(109)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (a->remove(236)) << std::endl;
*e=*d;
std::cout << (c->insert(161)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
*d=*d;
std::cout << (e->insert(490)) << std::endl;
std::cout << (a->remove(152)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
d->printPretty();
std::cout << (e->insert(149)) << std::endl;
std::cout << (d->remove(109)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (c->remove(212)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
std::cout << (b->remove(188)) << std::endl;
*b=*d;
std::cout << (c->insert(280)) << std::endl;
*e=*d;
std::cout << (e->remove(373)) << std::endl;
*e=*e;
*e=*c;
std::cout << (c->remove(197)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
a->printPretty();
*d=*a;
a->printPretty();
std::cout << (d->remove(71)) << std::endl;
a->printPretty();
std::cout << (c->insert(280)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
b->printPretty();
d->printPretty();
c->printPretty();
std::cout << (c->insert(412)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
std::cout << (e->remove(161)) << std::endl;
*a=*a;
std::cout << (c->insert(26)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
*b=*b;
std::cout << (d->insert(91)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
a->printPretty();
std::cout << (b->insert(300)) << std::endl;
std::cout << (c->insert(26)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
*c=*e;
std::cout << (e->insert(280)) << std::endl;
std::cout << (c->insert(109)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
a->printPretty();
std::cout << (c->remove(495)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->remove(109)) << std::endl;
c->printPretty();
std::cout << (c->insert(280)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
*d=*b;
std::cout << (a->insert(252)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
*b=*b;
std::cout << (b->insert(419)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
*d=*b;
std::cout << (b->remove(457)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
*d=*c;
*b=*c;
std::cout << (b->remove(320)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
b->printPretty();
std::cout << (a->insert(252)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
e->printPretty();
std::cout << (e->insert(473)) << std::endl;
c->printPretty();
std::cout << (c->remove(280)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
c->printPretty();
std::cout << (e->remove(280)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
e->printPretty();
std::cout << (d->remove(445)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
std::cout << (c->insert(106)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
*b=*c;
std::cout << (d->remove(88)) << std::endl;
std::cout << (c->insert(80)) << std::endl;
std::cout << (d->insert(436)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (d->remove(448)) << std::endl;
std::cout << (b->remove(428)) << std::endl;
e->printPretty();
std::cout << (a->remove(335)) << std::endl;
std::cout << (a->remove(402)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
std::cout << (e->remove(473)) << std::endl;
d->printPretty();
std::cout << (e->insert(96)) << std::endl;
std::cout << (b->remove(18)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
std::cout << (c->insert(255)) << std::endl;
std::cout << (b->remove(320)) << std::endl;
*e=*d;
std::cout << (c->remove(106)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (d->remove(197)) << std::endl;
c->printPretty();
a->printPretty();
*d=*c;
d->printPretty();
std::cout << (e->insert(335)) << std::endl;
b->printPretty();
std::cout << (d->remove(255)) << std::endl;
std::cout << (e->insert(206)) << std::endl;
c->printPretty();
std::cout << (b->insert(73)) << std::endl;
b->printPretty();
std::cout << (a->remove(262)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
*c=*c;
std::cout << (b->remove(453)) << std::endl;
*e=*c;
std::cout << (b->remove(79)) << std::endl;
*b=*c;
std::cout << (a->insert(311)) << std::endl;
std::cout << (a->insert(311)) << std::endl;
*e=*b;
std::cout << (c->insert(80)) << std::endl;
std::cout << (d->remove(320)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
*b=*d;
*e=*a;
std::cout << (d->remove(346)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
*c=*e;
std::cout << (e->insert(191)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
*c=*b;
std::cout << (e->insert(143)) << std::endl;
*e=*e;
*d=*a;
*a=*e;
std::cout << (a->insert(24)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
std::cout << (c->remove(394)) << std::endl;
*b=*a;
*d=*c;
std::cout << (a->remove(311)) << std::endl;
std::cout << (e->remove(143)) << std::endl;
*a=*b;
std::cout << (c->remove(346)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->remove(191)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
b->printPretty();
std::cout << (c->remove(217)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
std::cout << (d->remove(346)) << std::endl;
*b=*d;
std::cout << (b->remove(127)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
std::cout << (c->remove(217)) << std::endl;
b->printPretty();
std::cout << (c->insert(366)) << std::endl;
std::cout << (d->remove(226)) << std::endl;
std::cout << (b->insert(157)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
*c=*e;
std::cout << (a->remove(452)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
c->printPretty();
std::cout << (e->insert(311)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
std::cout << (c->remove(275)) << std::endl;
*b=*a;
std::cout << (e->remove(170)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
std::cout << (d->remove(38)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
*b=*a;
b->printPretty();
*e=*a;
*d=*d;
std::cout << (a->remove(311)) << std::endl;
std::cout << (b->insert(311)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
d->printPretty();
std::cout << (a->insert(498)) << std::endl;
*e=*d;
std::cout << (e->insert(260)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (c->remove(141)) << std::endl;
*c=*d;
std::cout << (b->remove(105)) << std::endl;
*b=*e;
std::cout << (b->insert(285)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
*d=*d;
std::cout << (a->insert(167)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
*e=*a;
std::cout << (a->insert(88)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (e->remove(428)) << std::endl;
std::cout << (e->insert(1)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->insert(252)) << std::endl;
*e=*a;
std::cout << (a->remove(259)) << std::endl;
std::cout << (b->insert(14)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (c->insert(344)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (c->remove(344)) << std::endl;
e->printPretty();
std::cout << (d->insert(475)) << std::endl;
*e=*e;
std::cout << (b->insert(108)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
std::cout << (d->remove(474)) << std::endl;
std::cout << (d->remove(475)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
std::cout << (e->insert(88)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
std::cout << (c->insert(295)) << std::endl;
std::cout << (d->remove(276)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
std::cout << (e->insert(1)) << std::endl;
*e=*c;
std::cout << (e->insert(118)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
e->printPretty();
std::cout << (e->insert(433)) << std::endl;
std::cout << (c->insert(295)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->remove(8)) << std::endl;
std::cout << (e->insert(203)) << std::endl;
std::cout << (d->remove(93)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->insert(216)) << std::endl;
a->printPretty();
std::cout << (b->insert(492)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
*d=*c;
*b=*a;
std::cout << (c->insert(436)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (c->insert(295)) << std::endl;
b->printPretty();
std::cout << (b->insert(498)) << std::endl;
*d=*d;
*a=*d;
*a=*d;
std::cout << (e->insert(85)) << std::endl;
std::cout << (d->remove(376)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
std::cout << (c->remove(295)) << std::endl;
std::cout << (b->remove(112)) << std::endl;
*b=*c;
std::cout << (d->insert(295)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (c->remove(188)) << std::endl;
c->printPretty();
std::cout << (b->remove(14)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (c->remove(332)) << std::endl;
std::cout << (e->remove(295)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (e->insert(177)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
std::cout << (d->remove(434)) << std::endl;
e->printPretty();
e->printPretty();
b->printPretty();
*c=*a;
*e=*d;
e->printPretty();
std::cout << (c->insert(379)) << std::endl;
std::cout << (e->insert(193)) << std::endl;
*b=*a;
std::cout << (b->remove(14)) << std::endl;
a->printPretty();
*b=*d;
std::cout << (c->insert(1)) << std::endl;
*e=*a;
std::cout << (d->remove(312)) << std::endl;
*e=*e;
std::cout << (b->remove(295)) << std::endl;
*b=*e;
b->printPretty();
*e=*d;
std::cout << (c->remove(366)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
*a=*e;
std::cout << (b->remove(97)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
c->printPretty();
std::cout << (a->remove(172)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
std::cout << (b->insert(443)) << std::endl;
b->printPretty();
std::cout << (e->remove(295)) << std::endl;
*e=*b;
std::cout << (c->remove(14)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
*d=*d;
std::cout << (e->insert(1)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
c->printPretty();
std::cout << (d->insert(47)) << std::endl;
*a=*e;
std::cout << (e->remove(443)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (b->remove(147)) << std::endl;
std::cout << (d->remove(204)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
a->printPretty();
std::cout << (a->remove(157)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
std::cout << (e->insert(1)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
*c=*e;
std::cout << (a->insert(203)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
std::cout << (d->remove(91)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
std::cout << (e->remove(1)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
e->printPretty();
std::cout << (d->remove(51)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
std::cout << (e->remove(175)) << std::endl;
std::cout << (e->remove(339)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
d->printPretty();
std::cout << (c->insert(1)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->remove(363)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (a->insert(203)) << std::endl;
*e=*a;
std::cout << (c->insert(72)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
*a=*c;
std::cout << (a->insert(339)) << std::endl;
std::cout << (d->remove(358)) << std::endl;
*e=*e;
std::cout << (d->insert(91)) << std::endl;
std::cout << (b->insert(379)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
*e=*a;
std::cout << (b->insert(14)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
c->printPretty();
*b=*e;
*d=*a;
a->printPretty();
std::cout << (a->remove(369)) << std::endl;
a->printPretty();
std::cout << (c->remove(1)) << std::endl;
std::cout << (a->insert(248)) << std::endl;
c->printPretty();
*d=*c;
e->printPretty();
std::cout << (c->insert(72)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (e->remove(1)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
a->printPretty();
std::cout << (a->insert(53)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
*e=*e;
std::cout << (a->remove(284)) << std::endl;
*e=*c;
*c=*b;
*c=*a;
*d=*b;
std::cout << (e->insert(467)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (e->remove(272)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
std::cout << (d->insert(369)) << std::endl;
*c=*d;
std::cout << (a->insert(72)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
std::cout << (c->remove(146)) << std::endl;
*e=*d;
std::cout << (a->remove(318)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (e->insert(187)) << std::endl;
std::cout << (a->remove(72)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
c->printPretty();
*b=*d;
*b=*a;
c->printPretty();
*d=*a;
b->printPretty();
std::cout << (a->insert(248)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
*d=*a;
std::cout << (a->insert(387)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->insert(1)) << std::endl;
d->printPretty();
std::cout << (e->remove(374)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (a->remove(11)) << std::endl;
std::cout << (e->insert(127)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
*d=*c;
std::cout << (a->remove(148)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (d->insert(1)) << std::endl;
d->printPretty();
std::cout << (e->remove(471)) << std::endl;
c->printPretty();
std::cout << (c->insert(222)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
*d=*a;
std::cout << (a->remove(271)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
c->printPretty();
std::cout << (a->remove(325)) << std::endl;
*d=*b;
*d=*c;
b->printPretty();
*a=*a;
std::cout << (d->insert(1)) << std::endl;
std::cout << (b->remove(468)) << std::endl;
std::cout << (e->remove(1)) << std::endl;
e->printPretty();
std::cout << (a->insert(53)) << std::endl;
*b=*e;
std::cout << (e->insert(127)) << std::endl;
e->printPretty();
std::cout << (a->insert(72)) << std::endl;
*b=*a;
std::cout << (a->insert(387)) << std::endl;
d->printPretty();
std::cout << (e->insert(127)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
*b=*d;
std::cout << (a->insert(53)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
std::cout << (e->insert(127)) << std::endl;
b->printPretty();
std::cout << (e->insert(389)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
std::cout << (a->insert(453)) << std::endl;
*d=*b;
*e=*c;
std::cout << (c->insert(43)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
std::cout << (e->insert(1)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (d->remove(456)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
*e=*c;
std::cout << (e->insert(75)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
c->printPretty();
std::cout << (c->remove(53)) << std::endl;
std::cout << (c->insert(222)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
a->printPretty();
std::cout << (b->insert(457)) << std::endl;
std::cout << (d->remove(225)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
*b=*a;
*e=*c;
std::cout << (b->remove(300)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
std::cout << (d->insert(119)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
*e=*b;
std::cout << (b->remove(439)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
std::cout << (c->insert(43)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
*e=*a;
std::cout << (a->insert(113)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
*d=*a;
std::cout << (a->remove(300)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
std::cout << (d->insert(314)) << std::endl;
std::cout << (c->insert(97)) << std::endl;
d->printPretty();
std::cout << (b->insert(379)) << std::endl;
*b=*b;
std::cout << (b->insert(248)) << std::endl;
std::cout << (a->remove(268)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
std::cout << (e->remove(287)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (e->remove(276)) << std::endl;
std::cout << (d->remove(249)) << std::endl;
std::cout << (b->remove(431)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
std::cout << (e->insert(248)) << std::endl;
c->printPretty();
d->printPretty();
*d=*e;
std::cout << (a->remove(115)) << std::endl;
std::cout << (a->remove(248)) << std::endl;
std::cout << (d->remove(205)) << std::endl;
e->printPretty();
std::cout << (b->remove(276)) << std::endl;
e->printPretty();
std::cout << (c->insert(1)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
*e=*e;
std::cout << (b->insert(380)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (e->remove(300)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
std::cout << (d->insert(277)) << std::endl;
*e=*e;
*d=*a;
std::cout << (b->insert(87)) << std::endl;
*b=*b;
*d=*e;
std::cout << (e->remove(453)) << std::endl;
*a=*b;
std::cout << (a->remove(282)) << std::endl;
*b=*d;
*e=*a;
std::cout << (e->insert(244)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (e->insert(65)) << std::endl;
std::cout << (a->remove(353)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
return 0;
}
