#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(13)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
std::cout << (a->insert(358)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
*b=*a;
std::cout << (a->insert(285)) << std::endl;
a->printPretty();
std::cout << (b->remove(358)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
std::cout << (a->insert(485)) << std::endl;
std::cout << (b->insert(13)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (b->remove(13)) << std::endl;
*c=*c;
std::cout << (b->remove(329)) << std::endl;
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (e->insert(141)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (c->insert(367)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
d->printPretty();
std::cout << (d->remove(478)) << std::endl;
*b=*e;
std::cout << (a->insert(285)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->insert(358)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
std::cout << (b->remove(329)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
*c=*d;
*a=*b;
*a=*c;
std::cout << (c->remove(229)) << std::endl;
e->printPretty();
d->printPretty();
c->printPretty();
a->printPretty();
std::cout << (c->remove(142)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
std::cout << (a->insert(326)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
a->printPretty();
std::cout << (d->remove(132)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (c->insert(485)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
*c=*d;
*c=*e;
c->printPretty();
std::cout << (b->insert(56)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
*e=*e;
std::cout << (c->insert(194)) << std::endl;
*e=*b;
std::cout << (b->insert(148)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
std::cout << (b->insert(476)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
std::cout << (a->insert(326)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (d->insert(55)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
d->printPretty();
std::cout << (e->remove(148)) << std::endl;
std::cout << (c->insert(295)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
e->printPretty();
std::cout << (c->remove(164)) << std::endl;
std::cout << (c->remove(94)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
*c=*b;
std::cout << (e->remove(186)) << std::endl;
*a=*a;
std::cout << (b->remove(115)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->insert(498)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->insert(404)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
std::cout << (e->insert(57)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
e->printPretty();
std::cout << (a->insert(485)) << std::endl;
*a=*d;
std::cout << (b->remove(476)) << std::endl;
std::cout << (e->remove(416)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
d->printPretty();
std::cout << (b->insert(460)) << std::endl;
*b=*b;
std::cout << (e->insert(272)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
std::cout << (b->remove(409)) << std::endl;
d->printPretty();
std::cout << (c->remove(476)) << std::endl;
*a=*d;
std::cout << (c->insert(141)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
std::cout << (a->insert(485)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
c->printPretty();
std::cout << (d->remove(307)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
*b=*b;
std::cout << (d->insert(485)) << std::endl;
b->printPretty();
std::cout << (d->insert(285)) << std::endl;
e->printPretty();
std::cout << (d->remove(373)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
a->printPretty();
std::cout << (e->remove(435)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
std::cout << (e->remove(57)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
std::cout << (e->insert(272)) << std::endl;
std::cout << (d->insert(235)) << std::endl;
a->printPretty();
std::cout << (a->insert(284)) << std::endl;
*e=*c;
std::cout << (d->remove(153)) << std::endl;
std::cout << (a->remove(229)) << std::endl;
d->printPretty();
std::cout << (b->insert(460)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (c->remove(429)) << std::endl;
*b=*b;
std::cout << (c->insert(251)) << std::endl;
*b=*c;
std::cout << (d->insert(358)) << std::endl;
*a=*d;
std::cout << (a->remove(329)) << std::endl;
std::cout << (b->remove(430)) << std::endl;
d->printPretty();
std::cout << (d->remove(320)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
*a=*e;
std::cout << (c->insert(443)) << std::endl;
std::cout << (b->insert(43)) << std::endl;
*b=*d;
std::cout << (d->remove(285)) << std::endl;
std::cout << (d->insert(334)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
std::cout << (c->remove(251)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
std::cout << (e->insert(458)) << std::endl;
std::cout << (b->insert(359)) << std::endl;
std::cout << (b->remove(329)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (c->remove(284)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
std::cout << (d->remove(228)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
std::cout << (b->insert(32)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
std::cout << (c->insert(82)) << std::endl;
*a=*b;
*a=*b;
*d=*c;
*a=*c;
std::cout << (e->remove(170)) << std::endl;
std::cout << (e->remove(251)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->remove(223)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
*c=*b;
std::cout << (e->remove(25)) << std::endl;
*c=*a;
*d=*b;
std::cout << (b->remove(404)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
*a=*c;
std::cout << (b->insert(279)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (e->remove(388)) << std::endl;
std::cout << (b->insert(485)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (c->remove(199)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
*b=*c;
b->printPretty();
c->printPretty();
std::cout << (d->remove(314)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
*c=*c;
std::cout << (e->insert(458)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
d->printPretty();
std::cout << (d->remove(55)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
std::cout << (a->remove(32)) << std::endl;
std::cout << (d->remove(280)) << std::endl;
a->printPretty();
std::cout << (a->remove(416)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
a->printPretty();
std::cout << (c->remove(141)) << std::endl;
*c=*d;
*e=*c;
std::cout << (a->insert(404)) << std::endl;
a->printPretty();
std::cout << (c->insert(358)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (b->insert(82)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (e->remove(384)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (e->remove(218)) << std::endl;
std::cout << (d->insert(292)) << std::endl;
*e=*b;
*a=*e;
std::cout << (d->remove(292)) << std::endl;
std::cout << (e->insert(82)) << std::endl;
std::cout << (c->insert(6)) << std::endl;
e->printPretty();
*b=*d;
std::cout << (d->remove(34)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
*d=*b;
std::cout << (d->insert(359)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
c->printPretty();
std::cout << (e->remove(82)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
*d=*b;
*e=*e;
d->printPretty();
c->printPretty();
std::cout << (b->remove(36)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
*a=*d;
*d=*e;
std::cout << (b->insert(36)) << std::endl;
std::cout << (a->remove(72)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
e->printPretty();
std::cout << (b->insert(34)) << std::endl;
std::cout << (d->remove(218)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(74)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (b->remove(275)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (b->remove(321)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
*e=*d;
std::cout << (a->remove(217)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
std::cout << (c->remove(365)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
*c=*e;
std::cout << (e->insert(425)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
d->printPretty();
std::cout << (b->insert(359)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
std::cout << (a->remove(32)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (b->insert(359)) << std::endl;
d->printPretty();
std::cout << (b->insert(220)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (e->insert(443)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
e->printPretty();
std::cout << (b->remove(247)) << std::endl;
*d=*b;
*d=*a;
std::cout << (a->insert(205)) << std::endl;
std::cout << (c->insert(305)) << std::endl;
d->printPretty();
*b=*c;
std::cout << (d->insert(407)) << std::endl;
b->printPretty();
std::cout << (e->remove(359)) << std::endl;
std::cout << (a->remove(394)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
std::cout << (d->insert(235)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (a->insert(313)) << std::endl;
c->printPretty();
std::cout << (c->remove(255)) << std::endl;
a->printPretty();
std::cout << (d->remove(34)) << std::endl;
std::cout << (a->insert(479)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
*e=*d;
std::cout << (b->remove(257)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (a->insert(404)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (b->insert(443)) << std::endl;
a->printPretty();
std::cout << (d->remove(205)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
std::cout << (d->insert(15)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
d->printPretty();
std::cout << (c->remove(141)) << std::endl;
e->printPretty();
std::cout << (b->remove(305)) << std::endl;
e->printPretty();
*d=*b;
*b=*e;
std::cout << (e->insert(495)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
c->printPretty();
*d=*d;
b->printPretty();
b->printPretty();
std::cout << (d->remove(56)) << std::endl;
std::cout << (d->insert(141)) << std::endl;
b->printPretty();
std::cout << (b->remove(220)) << std::endl;
e->printPretty();
std::cout << (c->remove(425)) << std::endl;
*b=*d;
std::cout << (b->remove(336)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
std::cout << (a->insert(141)) << std::endl;
*c=*a;
std::cout << (e->remove(382)) << std::endl;
std::cout << (c->remove(485)) << std::endl;
std::cout << (e->insert(330)) << std::endl;
*e=*d;
std::cout << (e->remove(445)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
std::cout << (a->remove(34)) << std::endl;
c->printPretty();
std::cout << (a->remove(479)) << std::endl;
a->printPretty();
std::cout << (d->remove(141)) << std::endl;
*b=*c;
*e=*a;
*e=*c;
std::cout << (a->insert(424)) << std::endl;
b->printPretty();
std::cout << (b->insert(149)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (c->remove(313)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
*d=*d;
*a=*b;
std::cout << (e->insert(413)) << std::endl;
std::cout << (c->remove(449)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
a->printPretty();
std::cout << (e->remove(432)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
std::cout << (b->remove(149)) << std::endl;
e->printPretty();
std::cout << (b->remove(363)) << std::endl;
std::cout << (e->remove(126)) << std::endl;
*d=*b;
std::cout << (c->remove(46)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
b->printPretty();
std::cout << (a->insert(112)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(209)) << std::endl;
std::cout << (a->insert(313)) << std::endl;
std::cout << (c->remove(363)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (d->insert(36)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (d->remove(36)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
*b=*a;
std::cout << (a->remove(374)) << std::endl;
std::cout << (e->remove(486)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
*e=*e;
std::cout << (b->insert(227)) << std::endl;
a->printPretty();
std::cout << (d->remove(485)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
e->printPretty();
std::cout << (d->insert(36)) << std::endl;
std::cout << (c->remove(141)) << std::endl;
*a=*d;
std::cout << (b->insert(77)) << std::endl;
*a=*c;
e->printPretty();
*d=*c;
std::cout << (c->remove(395)) << std::endl;
c->printPretty();
a->printPretty();
*b=*c;
std::cout << (a->insert(235)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
std::cout << (c->remove(358)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
*e=*b;
std::cout << (c->insert(171)) << std::endl;
std::cout << (c->remove(365)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
std::cout << (d->insert(486)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
*b=*b;
std::cout << (e->remove(231)) << std::endl;
*e=*c;
*a=*a;
std::cout << (d->insert(486)) << std::endl;
e->printPretty();
std::cout << (a->remove(479)) << std::endl;
e->printPretty();
*d=*d;
std::cout << (d->remove(73)) << std::endl;
std::cout << (e->remove(34)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (c->remove(359)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
std::cout << (a->insert(99)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
b->printPretty();
std::cout << (b->insert(46)) << std::endl;
*b=*a;
std::cout << (a->remove(358)) << std::endl;
b->printPretty();
b->printPretty();
*c=*c;
std::cout << (d->remove(285)) << std::endl;
std::cout << (a->insert(464)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
std::cout << (d->insert(479)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (c->remove(82)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
std::cout << (b->remove(347)) << std::endl;
std::cout << (e->remove(285)) << std::endl;
b->printPretty();
std::cout << (b->remove(285)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
*a=*c;
std::cout << (d->insert(34)) << std::endl;
*b=*a;
std::cout << (d->remove(363)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->insert(171)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (b->insert(270)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (a->insert(285)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (a->insert(28)) << std::endl;
std::cout << (d->insert(235)) << std::endl;
std::cout << (e->insert(60)) << std::endl;
std::cout << (e->remove(60)) << std::endl;
d->printPretty();
std::cout << (b->remove(199)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->insert(103)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
d->printPretty();
std::cout << (e->insert(69)) << std::endl;
std::cout << (b->remove(486)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
a->printPretty();
std::cout << (e->insert(385)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
std::cout << (a->remove(438)) << std::endl;
std::cout << (a->insert(337)) << std::endl;
*c=*e;
std::cout << (c->remove(359)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
c->printPretty();
std::cout << (e->insert(399)) << std::endl;
std::cout << (a->insert(34)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
*d=*d;
std::cout << (d->remove(36)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (e->remove(2)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
*d=*d;
std::cout << (e->remove(359)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
std::cout << (e->remove(129)) << std::endl;
c->printPretty();
std::cout << (c->remove(36)) << std::endl;
std::cout << (a->remove(296)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
*c=*c;
std::cout << (d->insert(217)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
std::cout << (c->remove(291)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (d->remove(158)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
std::cout << (b->insert(171)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
e->printPretty();
std::cout << (a->remove(382)) << std::endl;
a->printPretty();
b->printPretty();
*b=*c;
std::cout << (b->insert(459)) << std::endl;
std::cout << (a->remove(276)) << std::endl;
*a=*c;
*c=*b;
std::cout << (c->remove(232)) << std::endl;
a->printPretty();
std::cout << (b->insert(85)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
a->printPretty();
*e=*e;
c->printPretty();
std::cout << (d->remove(218)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
a->printPretty();
std::cout << (b->remove(259)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (d->insert(405)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
e->printPretty();
std::cout << (b->insert(459)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
*b=*a;
std::cout << (d->remove(496)) << std::endl;
std::cout << (d->insert(144)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (c->insert(69)) << std::endl;
e->printPretty();
std::cout << (b->remove(359)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (c->insert(181)) << std::endl;
b->printPretty();
std::cout << (e->insert(171)) << std::endl;
std::cout << (a->remove(331)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (d->insert(144)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
std::cout << (b->remove(171)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
std::cout << (a->insert(424)) << std::endl;
*c=*b;
d->printPretty();
d->printPretty();
*a=*e;
std::cout << (e->insert(97)) << std::endl;
std::cout << (a->remove(243)) << std::endl;
e->printPretty();
std::cout << (d->insert(201)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
e->printPretty();
std::cout << (d->remove(25)) << std::endl;
a->printPretty();
std::cout << (e->remove(97)) << std::endl;
b->printPretty();
*e=*e;
*c=*c;
std::cout << (c->remove(399)) << std::endl;
*e=*c;
std::cout << (b->insert(271)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
std::cout << (e->insert(63)) << std::endl;
a->printPretty();
std::cout << (d->insert(459)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (b->insert(49)) << std::endl;
c->printPretty();
std::cout << (d->insert(399)) << std::endl;
std::cout << (d->insert(73)) << std::endl;
std::cout << (e->remove(486)) << std::endl;
*e=*c;
*e=*a;
std::cout << (e->remove(171)) << std::endl;
std::cout << (e->remove(69)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
std::cout << (e->insert(303)) << std::endl;
std::cout << (d->insert(337)) << std::endl;
e->printPretty();
std::cout << (e->insert(253)) << std::endl;
std::cout << (e->insert(303)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (e->remove(316)) << std::endl;
std::cout << (e->remove(486)) << std::endl;
*a=*b;
std::cout << (b->insert(329)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->insert(88)) << std::endl;
std::cout << (e->insert(385)) << std::endl;
*d=*d;
std::cout << (b->insert(178)) << std::endl;
std::cout << (b->remove(309)) << std::endl;
std::cout << (e->insert(388)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
*a=*a;
*d=*a;
std::cout << (a->insert(49)) << std::endl;
std::cout << (e->remove(405)) << std::endl;
b->printPretty();
std::cout << (b->remove(420)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
*c=*d;
std::cout << (a->insert(399)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
b->printPretty();
std::cout << (b->remove(137)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
std::cout << (a->remove(351)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
c->printPretty();
std::cout << (a->insert(420)) << std::endl;
std::cout << (a->remove(203)) << std::endl;
d->printPretty();
std::cout << (c->insert(235)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (a->insert(171)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
std::cout << (a->remove(171)) << std::endl;
c->printPretty();
std::cout << (d->insert(85)) << std::endl;
*d=*a;
std::cout << (a->insert(171)) << std::endl;
*d=*d;
*b=*b;
b->printPretty();
std::cout << (e->insert(385)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
std::cout << (a->remove(171)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
d->printPretty();
std::cout << (d->insert(420)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
std::cout << (c->insert(271)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (d->remove(89)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
b->printPretty();
std::cout << (a->insert(69)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
std::cout << (e->insert(88)) << std::endl;
std::cout << (b->insert(49)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
*e=*a;
std::cout << (c->remove(486)) << std::endl;
return 0;
}
