#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(102)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
a->printPretty();
*a=*b;
*a=*a;
std::cout << (b->remove(398)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (b->remove(8)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (d->insert(372)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (d->insert(74)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
*d=*b;
*e=*d;
b->printPretty();
*b=*d;
std::cout << (e->remove(485)) << std::endl;
std::cout << (b->insert(254)) << std::endl;
std::cout << (a->remove(8)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
std::cout << (c->remove(116)) << std::endl;
std::cout << (a->remove(460)) << std::endl;
std::cout << (c->insert(136)) << std::endl;
e->printPretty();
std::cout << (d->insert(451)) << std::endl;
std::cout << (b->remove(40)) << std::endl;
e->printPretty();
*a=*e;
*c=*c;
a->printPretty();
std::cout << (a->insert(259)) << std::endl;
*d=*a;
std::cout << (d->remove(259)) << std::endl;
*a=*d;
std::cout << (b->remove(358)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->insert(350)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
std::cout << (b->remove(350)) << std::endl;
std::cout << (c->insert(347)) << std::endl;
std::cout << (a->remove(269)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
*a=*b;
std::cout << (a->insert(10)) << std::endl;
std::cout << (c->remove(228)) << std::endl;
std::cout << (a->remove(254)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (a->remove(10)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
std::cout << (c->remove(349)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
c->printPretty();
*b=*d;
*e=*b;
*e=*d;
*c=*c;
std::cout << (c->insert(347)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (e->remove(224)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
*b=*d;
std::cout << (d->remove(128)) << std::endl;
d->printPretty();
std::cout << (d->insert(384)) << std::endl;
c->printPretty();
*e=*d;
*c=*e;
std::cout << (d->remove(384)) << std::endl;
e->printPretty();
std::cout << (d->remove(229)) << std::endl;
std::cout << (a->insert(72)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
c->printPretty();
std::cout << (c->remove(384)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
std::cout << (a->insert(43)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (b->insert(384)) << std::endl;
a->printPretty();
std::cout << (c->remove(486)) << std::endl;
*e=*e;
*c=*a;
std::cout << (a->insert(384)) << std::endl;
a->printPretty();
std::cout << (c->remove(82)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->insert(384)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
*c=*e;
std::cout << (d->insert(165)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
c->printPretty();
a->printPretty();
d->printPretty();
std::cout << (a->insert(497)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
*e=*b;
std::cout << (c->insert(456)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
e->printPretty();
*a=*e;
d->printPretty();
std::cout << (d->insert(285)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
std::cout << (d->insert(321)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (b->remove(384)) << std::endl;
std::cout << (b->remove(174)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->insert(182)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
a->printPretty();
std::cout << (b->remove(259)) << std::endl;
a->printPretty();
*d=*e;
std::cout << (d->insert(384)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (e->remove(453)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
a->printPretty();
std::cout << (a->remove(42)) << std::endl;
std::cout << (d->insert(468)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (c->remove(333)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
d->printPretty();
std::cout << (a->remove(341)) << std::endl;
std::cout << (a->remove(5)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
d->printPretty();
std::cout << (a->insert(384)) << std::endl;
std::cout << (e->insert(458)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (c->insert(411)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (e->insert(370)) << std::endl;
std::cout << (c->remove(319)) << std::endl;
std::cout << (c->remove(138)) << std::endl;
*a=*a;
std::cout << (b->remove(444)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (e->remove(385)) << std::endl;
std::cout << (e->insert(458)) << std::endl;
a->printPretty();
d->printPretty();
*b=*c;
std::cout << (b->remove(300)) << std::endl;
*a=*c;
std::cout << (c->remove(153)) << std::endl;
std::cout << (c->remove(384)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
c->printPretty();
std::cout << (c->remove(262)) << std::endl;
*c=*d;
*b=*e;
std::cout << (d->insert(411)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
a->printPretty();
std::cout << (e->insert(458)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
a->printPretty();
std::cout << (b->remove(242)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (a->remove(153)) << std::endl;
*a=*d;
std::cout << (e->insert(315)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (a->insert(411)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
*c=*c;
std::cout << (c->insert(484)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (a->insert(39)) << std::endl;
std::cout << (e->remove(166)) << std::endl;
std::cout << (c->remove(86)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
a->printPretty();
std::cout << (b->remove(458)) << std::endl;
std::cout << (b->insert(370)) << std::endl;
b->printPretty();
std::cout << (e->remove(41)) << std::endl;
std::cout << (e->insert(458)) << std::endl;
std::cout << (a->insert(39)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
std::cout << (c->remove(101)) << std::endl;
d->printPretty();
*c=*e;
std::cout << (c->insert(301)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
c->printPretty();
std::cout << (c->insert(388)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (c->remove(212)) << std::endl;
std::cout << (b->insert(335)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (c->remove(111)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
std::cout << (e->insert(413)) << std::endl;
std::cout << (e->remove(74)) << std::endl;
*e=*d;
std::cout << (c->insert(384)) << std::endl;
std::cout << (a->insert(411)) << std::endl;
*a=*c;
std::cout << (d->remove(182)) << std::endl;
c->printPretty();
std::cout << (b->insert(265)) << std::endl;
std::cout << (a->insert(191)) << std::endl;
a->printPretty();
e->printPretty();
c->printPretty();
*d=*e;
std::cout << (b->insert(379)) << std::endl;
std::cout << (b->remove(370)) << std::endl;
c->printPretty();
std::cout << (c->remove(370)) << std::endl;
a->printPretty();
std::cout << (c->insert(388)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
*e=*e;
std::cout << (c->insert(14)) << std::endl;
std::cout << (d->insert(441)) << std::endl;
b->printPretty();
std::cout << (b->remove(429)) << std::endl;
*a=*e;
std::cout << (c->remove(383)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (c->insert(356)) << std::endl;
std::cout << (b->insert(379)) << std::endl;
std::cout << (a->insert(441)) << std::endl;
std::cout << (e->remove(170)) << std::endl;
*d=*d;
*e=*e;
*a=*d;
c->printPretty();
std::cout << (b->insert(491)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
d->printPretty();
std::cout << (d->insert(262)) << std::endl;
d->printPretty();
std::cout << (c->remove(388)) << std::endl;
std::cout << (c->insert(244)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (a->remove(342)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
*b=*a;
std::cout << (c->remove(118)) << std::endl;
std::cout << (b->insert(220)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (c->insert(236)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
std::cout << (c->remove(244)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
d->printPretty();
std::cout << (b->remove(411)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
d->printPretty();
std::cout << (a->insert(418)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
c->printPretty();
std::cout << (c->insert(213)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
std::cout << (c->remove(384)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (c->insert(49)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
std::cout << (b->remove(441)) << std::endl;
std::cout << (e->insert(182)) << std::endl;
std::cout << (d->remove(423)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->insert(1)) << std::endl;
c->printPretty();
std::cout << (b->remove(300)) << std::endl;
std::cout << (e->insert(37)) << std::endl;
*c=*d;
std::cout << (d->insert(411)) << std::endl;
*b=*e;
std::cout << (d->insert(149)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
std::cout << (d->remove(428)) << std::endl;
std::cout << (c->insert(411)) << std::endl;
*c=*e;
std::cout << (e->insert(491)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
*a=*a;
std::cout << (c->remove(234)) << std::endl;
*b=*d;
a->printPretty();
*b=*a;
*b=*d;
std::cout << (e->insert(53)) << std::endl;
b->printPretty();
a->printPretty();
*b=*d;
*e=*d;
*d=*b;
std::cout << (b->insert(182)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (a->insert(441)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
std::cout << (d->remove(109)) << std::endl;
std::cout << (d->insert(71)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (e->insert(182)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
std::cout << (a->remove(418)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
e->printPretty();
std::cout << (d->remove(463)) << std::endl;
std::cout << (e->insert(353)) << std::endl;
a->printPretty();
std::cout << (d->remove(16)) << std::endl;
b->printPretty();
std::cout << (c->remove(243)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->insert(207)) << std::endl;
std::cout << (a->insert(2)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
*c=*e;
std::cout << (e->insert(411)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
std::cout << (d->remove(149)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (c->remove(485)) << std::endl;
*d=*c;
std::cout << (e->insert(82)) << std::endl;
e->printPretty();
std::cout << (e->insert(35)) << std::endl;
a->printPretty();
std::cout << (e->insert(161)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
std::cout << (e->insert(330)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (a->remove(411)) << std::endl;
a->printPretty();
std::cout << (d->insert(264)) << std::endl;
std::cout << (c->remove(143)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
std::cout << (d->remove(12)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
std::cout << (a->insert(441)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
b->printPretty();
*d=*e;
std::cout << (d->insert(404)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
*b=*d;
b->printPretty();
a->printPretty();
*a=*d;
*c=*b;
std::cout << (c->insert(161)) << std::endl;
std::cout << (a->remove(82)) << std::endl;
std::cout << (b->remove(344)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
c->printPretty();
std::cout << (c->insert(337)) << std::endl;
c->printPretty();
*d=*c;
*c=*c;
std::cout << (a->remove(6)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
std::cout << (c->insert(147)) << std::endl;
std::cout << (d->remove(411)) << std::endl;
d->printPretty();
std::cout << (c->insert(404)) << std::endl;
*a=*a;
std::cout << (b->insert(158)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->remove(82)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (d->remove(347)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
std::cout << (d->insert(459)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
c->printPretty();
std::cout << (b->insert(221)) << std::endl;
std::cout << (a->remove(424)) << std::endl;
a->printPretty();
std::cout << (a->remove(186)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
std::cout << (c->remove(35)) << std::endl;
b->printPretty();
std::cout << (b->insert(404)) << std::endl;
*a=*a;
std::cout << (d->insert(182)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
d->printPretty();
std::cout << (b->insert(152)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
std::cout << (a->insert(441)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
*c=*e;
b->printPretty();
b->printPretty();
b->printPretty();
std::cout << (c->insert(330)) << std::endl;
d->printPretty();
std::cout << (e->remove(382)) << std::endl;
*a=*b;
c->printPretty();
a->printPretty();
std::cout << (b->insert(374)) << std::endl;
std::cout << (a->remove(443)) << std::endl;
std::cout << (b->remove(374)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
*a=*a;
std::cout << (c->insert(187)) << std::endl;
std::cout << (b->insert(457)) << std::endl;
std::cout << (d->remove(459)) << std::endl;
e->printPretty();
std::cout << (b->remove(19)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
b->printPretty();
std::cout << (b->remove(107)) << std::endl;
std::cout << (c->insert(230)) << std::endl;
c->printPretty();
std::cout << (b->insert(234)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
std::cout << (b->insert(152)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
*b=*a;
std::cout << (a->insert(73)) << std::endl;
std::cout << (d->insert(447)) << std::endl;
a->printPretty();
std::cout << (a->insert(161)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
*e=*e;
std::cout << (a->remove(235)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
std::cout << (e->remove(205)) << std::endl;
c->printPretty();
std::cout << (b->insert(2)) << std::endl;
std::cout << (e->insert(441)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
std::cout << (e->remove(1)) << std::endl;
std::cout << (e->remove(491)) << std::endl;
*c=*b;
std::cout << (b->insert(441)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
*a=*d;
c->printPretty();
*b=*e;
std::cout << (d->insert(262)) << std::endl;
*e=*c;
b->printPretty();
*c=*c;
std::cout << (b->remove(35)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
std::cout << (c->insert(483)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
std::cout << (a->remove(194)) << std::endl;
e->printPretty();
e->printPretty();
*b=*b;
c->printPretty();
std::cout << (e->insert(406)) << std::endl;
e->printPretty();
std::cout << (e->remove(266)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
std::cout << (e->remove(262)) << std::endl;
d->printPretty();
std::cout << (b->insert(441)) << std::endl;
std::cout << (e->remove(477)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
std::cout << (a->insert(35)) << std::endl;
std::cout << (b->insert(281)) << std::endl;
std::cout << (a->insert(141)) << std::endl;
d->printPretty();
std::cout << (d->insert(93)) << std::endl;
*c=*c;
std::cout << (e->insert(269)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
*e=*a;
*b=*c;
*e=*e;
std::cout << (a->remove(82)) << std::endl;
std::cout << (c->remove(258)) << std::endl;
b->printPretty();
std::cout << (d->remove(182)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
d->printPretty();
std::cout << (c->insert(2)) << std::endl;
*d=*a;
std::cout << (e->remove(439)) << std::endl;
e->printPretty();
d->printPretty();
d->printPretty();
*e=*b;
std::cout << (e->insert(266)) << std::endl;
e->printPretty();
std::cout << (b->remove(2)) << std::endl;
std::cout << (d->remove(111)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (b->remove(1)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
b->printPretty();
std::cout << (c->remove(266)) << std::endl;
e->printPretty();
std::cout << (b->remove(404)) << std::endl;
std::cout << (c->remove(483)) << std::endl;
std::cout << (b->insert(262)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
std::cout << (b->remove(272)) << std::endl;
e->printPretty();
std::cout << (b->insert(353)) << std::endl;
std::cout << (a->remove(230)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
std::cout << (d->insert(412)) << std::endl;
std::cout << (a->insert(200)) << std::endl;
std::cout << (d->remove(468)) << std::endl;
e->printPretty();
std::cout << (a->remove(76)) << std::endl;
*b=*c;
std::cout << (a->insert(336)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
*c=*e;
std::cout << (c->remove(463)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
std::cout << (d->insert(218)) << std::endl;
std::cout << (e->insert(398)) << std::endl;
e->printPretty();
*a=*a;
std::cout << (e->insert(158)) << std::endl;
b->printPretty();
std::cout << (e->remove(211)) << std::endl;
std::cout << (e->insert(221)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
*e=*c;
*d=*c;
std::cout << (e->remove(148)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (d->insert(182)) << std::endl;
std::cout << (a->remove(315)) << std::endl;
std::cout << (e->insert(409)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (e->insert(409)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
std::cout << (b->remove(337)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
*c=*e;
*b=*c;
std::cout << (a->insert(173)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
e->printPretty();
std::cout << (d->insert(330)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
std::cout << (a->insert(20)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
*d=*b;
std::cout << (b->insert(189)) << std::endl;
b->printPretty();
std::cout << (b->remove(76)) << std::endl;
std::cout << (d->insert(205)) << std::endl;
*a=*b;
std::cout << (c->remove(466)) << std::endl;
a->printPretty();
std::cout << (e->insert(37)) << std::endl;
std::cout << (c->remove(221)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
e->printPretty();
std::cout << (c->insert(404)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (e->insert(353)) << std::endl;
d->printPretty();
std::cout << (c->insert(2)) << std::endl;
std::cout << (c->remove(321)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
b->printPretty();
std::cout << (b->remove(2)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->insert(258)) << std::endl;
std::cout << (b->remove(199)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
std::cout << (c->remove(386)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
*c=*c;
*c=*d;
std::cout << (a->remove(132)) << std::endl;
std::cout << (d->insert(267)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (b->remove(262)) << std::endl;
*a=*d;
*e=*e;
std::cout << (e->insert(131)) << std::endl;
std::cout << (a->insert(49)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
std::cout << (b->insert(259)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
std::cout << (d->remove(484)) << std::endl;
std::cout << (c->remove(2)) << std::endl;
std::cout << (d->remove(490)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
e->printPretty();
std::cout << (e->insert(88)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
std::cout << (b->remove(180)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
*a=*b;
std::cout << (a->insert(35)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->insert(330)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
d->printPretty();
std::cout << (c->remove(411)) << std::endl;
std::cout << (d->insert(124)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
*e=*b;
std::cout << (b->remove(325)) << std::endl;
std::cout << (a->insert(483)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
*e=*d;
*c=*a;
std::cout << (d->remove(182)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (e->insert(275)) << std::endl;
std::cout << (a->insert(186)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
*a=*d;
std::cout << (c->insert(436)) << std::endl;
d->printPretty();
std::cout << (b->remove(434)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
std::cout << (e->remove(266)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
return 0;
}
