#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(161)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(234)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (a->remove(305)) << std::endl;
*b=*b;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
b->printPretty();
std::cout << (c->remove(267)) << std::endl;
c->printPretty();
std::cout << (d->insert(263)) << std::endl;
*c=*e;
std::cout << (b->insert(82)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
std::cout << (e->remove(24)) << std::endl;
*a=*e;
c->printPretty();
std::cout << (d->insert(263)) << std::endl;
std::cout << (e->insert(289)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
*c=*c;
std::cout << (e->remove(361)) << std::endl;
std::cout << (b->remove(82)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
b->printPretty();
std::cout << (a->remove(247)) << std::endl;
std::cout << (c->insert(118)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (c->insert(15)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
std::cout << (c->remove(118)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (b->insert(272)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (b->insert(474)) << std::endl;
a->printPretty();
std::cout << (b->insert(272)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (a->remove(319)) << std::endl;
std::cout << (c->remove(16)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
*b=*b;
std::cout << (e->insert(500)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
*d=*c;
std::cout << (e->remove(500)) << std::endl;
std::cout << (a->remove(110)) << std::endl;
*c=*a;
*d=*b;
std::cout << (d->remove(474)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
d->printPretty();
std::cout << (e->remove(28)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
std::cout << (a->remove(299)) << std::endl;
std::cout << (e->insert(34)) << std::endl;
std::cout << (d->remove(272)) << std::endl;
e->printPretty();
std::cout << (a->remove(187)) << std::endl;
a->printPretty();
std::cout << (b->remove(58)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->insert(54)) << std::endl;
e->printPretty();
std::cout << (d->insert(54)) << std::endl;
*b=*a;
std::cout << (b->remove(347)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (d->remove(321)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
*b=*c;
*c=*b;
std::cout << (b->remove(345)) << std::endl;
std::cout << (a->remove(222)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
a->printPretty();
*b=*a;
*a=*c;
std::cout << (b->insert(411)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
c->printPretty();
e->printPretty();
*e=*b;
a->printPretty();
std::cout << (c->insert(345)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (c->insert(261)) << std::endl;
std::cout << (e->insert(411)) << std::endl;
*a=*e;
std::cout << (e->insert(443)) << std::endl;
*b=*e;
std::cout << (d->insert(277)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
*d=*e;
std::cout << (a->remove(411)) << std::endl;
std::cout << (a->insert(65)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (a->remove(65)) << std::endl;
e->printPretty();
std::cout << (d->remove(205)) << std::endl;
*d=*c;
*e=*a;
std::cout << (a->insert(61)) << std::endl;
std::cout << (c->remove(15)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (b->remove(484)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (a->remove(61)) << std::endl;
std::cout << (b->remove(130)) << std::endl;
*d=*a;
*b=*c;
b->printPretty();
std::cout << (b->insert(498)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
*a=*c;
*b=*b;
*c=*a;
std::cout << (b->remove(266)) << std::endl;
*d=*d;
std::cout << (c->remove(122)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
std::cout << (b->remove(113)) << std::endl;
*a=*e;
std::cout << (a->remove(112)) << std::endl;
*e=*e;
std::cout << (a->insert(421)) << std::endl;
std::cout << (d->remove(253)) << std::endl;
*e=*d;
std::cout << (e->remove(116)) << std::endl;
std::cout << (c->remove(261)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
e->printPretty();
*c=*b;
std::cout << (c->remove(80)) << std::endl;
std::cout << (b->insert(381)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
*d=*d;
*a=*d;
std::cout << (e->remove(60)) << std::endl;
std::cout << (c->insert(498)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (b->insert(345)) << std::endl;
std::cout << (d->insert(341)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
*e=*e;
std::cout << (c->remove(107)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
*a=*d;
std::cout << (b->remove(119)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*e=*c;
std::cout << (a->insert(49)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
std::cout << (c->remove(443)) << std::endl;
*d=*b;
*e=*e;
std::cout << (b->remove(104)) << std::endl;
*d=*c;
std::cout << (b->remove(398)) << std::endl;
c->printPretty();
*e=*b;
*c=*e;
std::cout << (a->insert(49)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
*a=*e;
*a=*c;
std::cout << (e->remove(35)) << std::endl;
std::cout << (b->insert(381)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
std::cout << (c->insert(256)) << std::endl;
d->printPretty();
std::cout << (e->insert(311)) << std::endl;
std::cout << (c->insert(256)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (a->remove(250)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (d->remove(272)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
*e=*e;
std::cout << (e->remove(4)) << std::endl;
*e=*e;
*d=*b;
std::cout << (e->insert(345)) << std::endl;
std::cout << (b->insert(120)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
b->printPretty();
std::cout << (b->insert(381)) << std::endl;
std::cout << (c->remove(383)) << std::endl;
std::cout << (c->remove(345)) << std::endl;
std::cout << (e->remove(430)) << std::endl;
b->printPretty();
c->printPretty();
*c=*e;
std::cout << (e->remove(261)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
*b=*b;
a->printPretty();
std::cout << (d->remove(381)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
d->printPretty();
std::cout << (c->remove(311)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
a->printPretty();
*b=*c;
b->printPretty();
std::cout << (d->remove(27)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
c->printPretty();
std::cout << (d->remove(422)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
std::cout << (e->insert(217)) << std::endl;
*d=*b;
std::cout << (e->insert(217)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
std::cout << (a->remove(353)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
std::cout << (b->insert(381)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
std::cout << (a->remove(212)) << std::endl;
*e=*b;
std::cout << (b->insert(289)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->remove(208)) << std::endl;
std::cout << (b->remove(289)) << std::endl;
*b=*d;
std::cout << (d->insert(482)) << std::endl;
*e=*a;
std::cout << (d->remove(482)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
std::cout << (b->remove(396)) << std::endl;
c->printPretty();
std::cout << (c->insert(345)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (a->insert(273)) << std::endl;
e->printPretty();
std::cout << (d->remove(369)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
std::cout << (d->insert(209)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
*e=*b;
std::cout << (b->insert(482)) << std::endl;
std::cout << (b->insert(338)) << std::endl;
std::cout << (a->remove(260)) << std::endl;
std::cout << (a->insert(484)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (a->insert(411)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
d->printPretty();
std::cout << (e->remove(247)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
std::cout << (e->insert(344)) << std::endl;
*d=*c;
std::cout << (a->remove(273)) << std::endl;
d->printPretty();
std::cout << (b->remove(216)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (e->remove(97)) << std::endl;
*b=*e;
std::cout << (d->remove(177)) << std::endl;
std::cout << (d->insert(498)) << std::endl;
*c=*a;
std::cout << (e->remove(168)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
b->printPretty();
*a=*c;
*a=*a;
std::cout << (c->insert(125)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
*b=*c;
std::cout << (d->insert(431)) << std::endl;
std::cout << (b->insert(486)) << std::endl;
std::cout << (c->insert(71)) << std::endl;
*e=*a;
std::cout << (c->remove(40)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (c->remove(340)) << std::endl;
a->printPretty();
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
*a=*a;
std::cout << (b->insert(392)) << std::endl;
c->printPretty();
c->printPretty();
c->printPretty();
std::cout << (b->remove(330)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
e->printPretty();
std::cout << (a->remove(284)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
std::cout << (c->remove(100)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
*b=*a;
std::cout << (b->insert(345)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
d->printPretty();
std::cout << (a->remove(482)) << std::endl;
a->printPretty();
std::cout << (c->remove(357)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
*b=*a;
*d=*c;
std::cout << (d->insert(380)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (b->insert(60)) << std::endl;
std::cout << (e->remove(306)) << std::endl;
*a=*d;
std::cout << (d->insert(466)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
*e=*a;
std::cout << (d->remove(125)) << std::endl;
*a=*b;
*c=*a;
std::cout << (d->insert(419)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
std::cout << (a->insert(345)) << std::endl;
std::cout << (a->remove(261)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
std::cout << (b->insert(90)) << std::endl;
*c=*e;
std::cout << (c->remove(380)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
std::cout << (c->remove(340)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (d->insert(377)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (b->remove(416)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
*b=*a;
std::cout << (d->remove(490)) << std::endl;
b->printPretty();
std::cout << (d->insert(497)) << std::endl;
std::cout << (c->remove(138)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
e->printPretty();
std::cout << (c->insert(125)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
*a=*d;
std::cout << (c->insert(15)) << std::endl;
std::cout << (d->remove(284)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (c->remove(125)) << std::endl;
*d=*b;
*e=*a;
std::cout << (b->remove(345)) << std::endl;
std::cout << (a->insert(275)) << std::endl;
e->printPretty();
std::cout << (b->remove(322)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (e->insert(380)) << std::endl;
*c=*c;
*b=*d;
std::cout << (d->insert(220)) << std::endl;
std::cout << (b->insert(345)) << std::endl;
c->printPretty();
*d=*e;
b->printPretty();
std::cout << (e->remove(497)) << std::endl;
std::cout << (e->remove(286)) << std::endl;
std::cout << (a->remove(315)) << std::endl;
*b=*a;
std::cout << (a->remove(100)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
*e=*d;
std::cout << (c->insert(14)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
*c=*a;
*d=*e;
std::cout << (e->insert(284)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
std::cout << (c->remove(71)) << std::endl;
std::cout << (c->remove(303)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
d->printPretty();
std::cout << (c->remove(345)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
*c=*d;
std::cout << (e->remove(261)) << std::endl;
std::cout << (d->remove(484)) << std::endl;
std::cout << (e->insert(408)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
e->printPretty();
std::cout << (e->remove(270)) << std::endl;
*a=*a;
std::cout << (b->insert(279)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
b->printPretty();
std::cout << (c->insert(360)) << std::endl;
*e=*e;
std::cout << (e->remove(449)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->remove(377)) << std::endl;
c->printPretty();
*a=*d;
c->printPretty();
std::cout << (d->insert(236)) << std::endl;
*e=*c;
std::cout << (a->insert(68)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
std::cout << (a->insert(342)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
*a=*a;
std::cout << (b->insert(145)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*c=*a;
std::cout << (c->insert(345)) << std::endl;
d->printPretty();
std::cout << (d->remove(123)) << std::endl;
*e=*c;
std::cout << (b->insert(279)) << std::endl;
std::cout << (a->insert(68)) << std::endl;
std::cout << (a->remove(453)) << std::endl;
std::cout << (b->remove(471)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
a->printPretty();
std::cout << (e->insert(63)) << std::endl;
std::cout << (c->remove(31)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
e->printPretty();
std::cout << (c->remove(71)) << std::endl;
std::cout << (b->insert(162)) << std::endl;
std::cout << (a->insert(351)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (e->insert(68)) << std::endl;
*e=*c;
a->printPretty();
std::cout << (a->remove(459)) << std::endl;
std::cout << (a->insert(93)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
*c=*e;
std::cout << (b->remove(177)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
std::cout << (e->remove(119)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (a->remove(179)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (e->remove(173)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
d->printPretty();
std::cout << (a->insert(71)) << std::endl;
std::cout << (c->remove(377)) << std::endl;
std::cout << (e->remove(236)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
std::cout << (c->insert(67)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
*c=*b;
std::cout << (b->remove(162)) << std::endl;
std::cout << (c->remove(345)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (d->insert(179)) << std::endl;
*e=*a;
*b=*e;
*d=*e;
std::cout << (b->remove(377)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
e->printPretty();
std::cout << (b->insert(342)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
a->printPretty();
std::cout << (d->insert(245)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (a->insert(284)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (b->remove(342)) << std::endl;
*b=*d;
std::cout << (a->remove(203)) << std::endl;
c->printPretty();
std::cout << (d->insert(308)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
e->printPretty();
*a=*a;
std::cout << (c->remove(305)) << std::endl;
std::cout << (a->insert(377)) << std::endl;
std::cout << (b->remove(342)) << std::endl;
std::cout << (c->insert(466)) << std::endl;
*a=*e;
std::cout << (e->insert(377)) << std::endl;
std::cout << (b->remove(185)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
std::cout << (b->remove(71)) << std::endl;
*b=*e;
std::cout << (d->insert(466)) << std::endl;
std::cout << (d->insert(71)) << std::endl;
std::cout << (c->remove(403)) << std::endl;
*d=*d;
std::cout << (d->remove(93)) << std::endl;
c->printPretty();
std::cout << (e->insert(380)) << std::endl;
std::cout << (a->remove(68)) << std::endl;
*d=*a;
std::cout << (c->insert(490)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
b->printPretty();
std::cout << (c->remove(92)) << std::endl;
*a=*d;
std::cout << (b->remove(466)) << std::endl;
std::cout << (c->insert(71)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
*a=*d;
std::cout << (d->remove(466)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
b->printPretty();
std::cout << (d->insert(380)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (d->remove(459)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (d->remove(385)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->remove(155)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
std::cout << (d->remove(79)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (d->remove(124)) << std::endl;
std::cout << (e->remove(98)) << std::endl;
std::cout << (d->remove(317)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
*b=*c;
std::cout << (b->insert(275)) << std::endl;
c->printPretty();
std::cout << (a->remove(20)) << std::endl;
std::cout << (c->insert(162)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (d->remove(93)) << std::endl;
c->printPretty();
*c=*a;
e->printPretty();
std::cout << (d->insert(353)) << std::endl;
b->printPretty();
std::cout << (b->insert(184)) << std::endl;
std::cout << (e->insert(265)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
*a=*e;
std::cout << (a->remove(93)) << std::endl;
*d=*e;
std::cout << (e->remove(284)) << std::endl;
*b=*d;
std::cout << (b->remove(342)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
std::cout << (d->insert(380)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
std::cout << (b->remove(68)) << std::endl;
*c=*b;
std::cout << (e->remove(377)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->insert(284)) << std::endl;
std::cout << (b->remove(391)) << std::endl;
a->printPretty();
std::cout << (c->remove(93)) << std::endl;
*a=*a;
std::cout << (a->remove(103)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
*e=*e;
std::cout << (b->remove(272)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
std::cout << (d->insert(71)) << std::endl;
std::cout << (c->remove(55)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
b->printPretty();
std::cout << (b->insert(265)) << std::endl;
std::cout << (a->insert(466)) << std::endl;
*a=*b;
std::cout << (b->remove(284)) << std::endl;
e->printPretty();
std::cout << (a->remove(351)) << std::endl;
std::cout << (e->remove(112)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
std::cout << (c->insert(151)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
*c=*b;
std::cout << (a->insert(284)) << std::endl;
c->printPretty();
std::cout << (d->remove(182)) << std::endl;
std::cout << (a->remove(170)) << std::endl;
d->printPretty();
std::cout << (e->insert(307)) << std::endl;
b->printPretty();
*d=*d;
a->printPretty();
e->printPretty();
std::cout << (b->remove(380)) << std::endl;
*e=*a;
std::cout << (d->insert(170)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
std::cout << (a->insert(320)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
std::cout << (e->insert(143)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
c->printPretty();
std::cout << (d->remove(170)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (b->remove(272)) << std::endl;
d->printPretty();
std::cout << (d->remove(351)) << std::endl;
e->printPretty();
std::cout << (a->insert(265)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
std::cout << (e->remove(265)) << std::endl;
std::cout << (e->insert(466)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (a->remove(71)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
b->printPretty();
std::cout << (c->insert(424)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
a->printPretty();
std::cout << (d->remove(391)) << std::endl;
std::cout << (c->remove(71)) << std::endl;
a->printPretty();
std::cout << (d->remove(377)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (b->remove(328)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
*a=*b;
std::cout << (a->insert(93)) << std::endl;
std::cout << (c->remove(302)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
std::cout << (a->insert(170)) << std::endl;
std::cout << (c->remove(377)) << std::endl;
std::cout << (b->remove(454)) << std::endl;
std::cout << (e->insert(377)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
std::cout << (c->remove(4)) << std::endl;
std::cout << (d->remove(93)) << std::endl;
*b=*b;
std::cout << (e->remove(143)) << std::endl;
*e=*c;
std::cout << (d->insert(71)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (c->remove(424)) << std::endl;
*a=*e;
std::cout << (d->insert(265)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
*a=*a;
std::cout << (d->remove(265)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (b->remove(429)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
*e=*e;
std::cout << (c->insert(351)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
std::cout << (b->insert(417)) << std::endl;
return 0;
}
