#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(419)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(26)) << std::endl;
b->printPretty();
*a=*a;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->insert(458)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
c->printPretty();
*a=*a;
a->printPretty();
std::cout << (a->remove(159)) << std::endl;
*c=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (b->remove(477)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
b->printPretty();
std::cout << (a->insert(136)) << std::endl;
std::cout << (c->insert(168)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
*d=*b;
d->printPretty();
*b=*a;
*c=*c;
c->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (c->insert(339)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (b->remove(458)) << std::endl;
std::cout << (e->remove(168)) << std::endl;
b->printPretty();
d->printPretty();
*a=*d;
d->printPretty();
std::cout << (e->remove(89)) << std::endl;
a->printPretty();
std::cout << (a->remove(288)) << std::endl;
b->printPretty();
e->printPretty();
e->printPretty();
std::cout << (a->remove(99)) << std::endl;
std::cout << (e->remove(339)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
std::cout << (b->remove(26)) << std::endl;
c->printPretty();
*b=*d;
b->printPretty();
d->printPretty();
b->printPretty();
std::cout << (c->remove(168)) << std::endl;
std::cout << (a->remove(4)) << std::endl;
e->printPretty();
*a=*a;
std::cout << (d->remove(308)) << std::endl;
c->printPretty();
*d=*e;
*d=*d;
*a=*e;
*b=*d;
*a=*c;
std::cout << (c->insert(483)) << std::endl;
*e=*c;
e->printPretty();
std::cout << (c->insert(477)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (e->remove(483)) << std::endl;
*d=*b;
d->printPretty();
*a=*a;
*b=*a;
std::cout << (c->insert(483)) << std::endl;
*b=*d;
*c=*c;
d->printPretty();
std::cout << (a->insert(154)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
*d=*e;
std::cout << (e->remove(62)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
*a=*e;
std::cout << (c->remove(483)) << std::endl;
std::cout << (e->remove(474)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
e->printPretty();
std::cout << (e->remove(463)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->insert(216)) << std::endl;
a->printPretty();
e->printPretty();
*b=*e;
d->printPretty();
std::cout << (c->insert(216)) << std::endl;
d->printPretty();
std::cout << (c->insert(119)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->remove(206)) << std::endl;
*e=*b;
*c=*a;
*b=*d;
*d=*c;
b->printPretty();
std::cout << (c->remove(10)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->remove(74)) << std::endl;
*c=*e;
std::cout << (d->insert(440)) << std::endl;
std::cout << (d->remove(274)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
d->printPretty();
std::cout << (d->insert(226)) << std::endl;
d->printPretty();
std::cout << (c->insert(109)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->remove(451)) << std::endl;
std::cout << (d->remove(226)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (e->insert(425)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
e->printPretty();
std::cout << (d->insert(440)) << std::endl;
std::cout << (e->remove(195)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (a->insert(413)) << std::endl;
*d=*e;
std::cout << (e->insert(36)) << std::endl;
std::cout << (b->insert(329)) << std::endl;
*c=*e;
std::cout << (a->remove(418)) << std::endl;
std::cout << (d->insert(52)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
std::cout << (b->insert(329)) << std::endl;
std::cout << (b->remove(329)) << std::endl;
*e=*e;
std::cout << (e->insert(488)) << std::endl;
*c=*e;
*b=*a;
a->printPretty();
std::cout << (d->insert(45)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
std::cout << (b->remove(471)) << std::endl;
std::cout << (d->remove(50)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
*d=*a;
*b=*e;
*c=*c;
std::cout << (e->insert(488)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
e->printPretty();
std::cout << (a->remove(413)) << std::endl;
*a=*a;
std::cout << (c->remove(36)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (b->remove(214)) << std::endl;
std::cout << (b->remove(316)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
*d=*b;
*d=*d;
*b=*a;
std::cout << (a->remove(240)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
b->printPretty();
std::cout << (a->insert(429)) << std::endl;
*b=*a;
std::cout << (c->insert(488)) << std::endl;
std::cout << (b->insert(429)) << std::endl;
a->printPretty();
std::cout << (c->remove(177)) << std::endl;
*c=*a;
std::cout << (d->insert(101)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
d->printPretty();
std::cout << (d->remove(200)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (c->remove(429)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
std::cout << (b->insert(429)) << std::endl;
*c=*c;
std::cout << (c->insert(396)) << std::endl;
std::cout << (b->remove(429)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (b->remove(266)) << std::endl;
std::cout << (c->remove(396)) << std::endl;
*b=*c;
*a=*e;
std::cout << (e->insert(255)) << std::endl;
a->printPretty();
std::cout << (b->insert(259)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (d->remove(101)) << std::endl;
std::cout << (b->remove(259)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
*a=*a;
std::cout << (e->remove(394)) << std::endl;
std::cout << (b->insert(348)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (b->remove(27)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
std::cout << (b->remove(348)) << std::endl;
std::cout << (e->insert(256)) << std::endl;
b->printPretty();
std::cout << (a->remove(205)) << std::endl;
b->printPretty();
*a=*a;
std::cout << (d->remove(384)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
*d=*c;
std::cout << (a->insert(461)) << std::endl;
*c=*b;
std::cout << (e->remove(424)) << std::endl;
*d=*b;
std::cout << (e->insert(186)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (c->insert(292)) << std::endl;
std::cout << (e->insert(256)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (b->remove(190)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (e->insert(360)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
std::cout << (d->remove(287)) << std::endl;
std::cout << (b->insert(493)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
*e=*d;
*e=*b;
d->printPretty();
e->printPretty();
e->printPretty();
c->printPretty();
std::cout << (a->insert(493)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
b->printPretty();
std::cout << (e->remove(493)) << std::endl;
*d=*d;
std::cout << (a->insert(170)) << std::endl;
*d=*a;
std::cout << (d->remove(368)) << std::endl;
std::cout << (e->remove(413)) << std::endl;
*b=*e;
std::cout << (c->remove(252)) << std::endl;
e->printPretty();
std::cout << (e->remove(500)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (e->remove(78)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
std::cout << (d->insert(424)) << std::endl;
e->printPretty();
std::cout << (c->remove(419)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
d->printPretty();
std::cout << (c->insert(238)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
std::cout << (d->remove(424)) << std::endl;
*d=*c;
std::cout << (a->insert(472)) << std::endl;
b->printPretty();
std::cout << (d->remove(374)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
std::cout << (a->remove(384)) << std::endl;
std::cout << (d->remove(238)) << std::endl;
std::cout << (c->insert(354)) << std::endl;
std::cout << (d->insert(32)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
std::cout << (d->insert(32)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
*b=*e;
c->printPretty();
*b=*b;
c->printPretty();
*d=*d;
std::cout << (a->insert(472)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
std::cout << (d->insert(32)) << std::endl;
*e=*d;
std::cout << (d->insert(257)) << std::endl;
std::cout << (a->insert(472)) << std::endl;
*a=*a;
*a=*d;
a->printPretty();
*c=*c;
std::cout << (b->insert(250)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (d->remove(257)) << std::endl;
*b=*c;
std::cout << (c->remove(238)) << std::endl;
*b=*a;
std::cout << (e->remove(32)) << std::endl;
std::cout << (e->remove(473)) << std::endl;
std::cout << (a->insert(473)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
*d=*d;
std::cout << (e->insert(43)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
*a=*a;
std::cout << (b->insert(473)) << std::endl;
std::cout << (c->insert(354)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (a->remove(32)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (a->insert(257)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
std::cout << (e->insert(227)) << std::endl;
*d=*b;
std::cout << (d->insert(274)) << std::endl;
*b=*d;
std::cout << (d->insert(473)) << std::endl;
*c=*c;
std::cout << (c->insert(43)) << std::endl;
std::cout << (a->remove(345)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (a->remove(252)) << std::endl;
std::cout << (c->remove(43)) << std::endl;
std::cout << (a->remove(257)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (a->remove(194)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
std::cout << (c->remove(447)) << std::endl;
d->printPretty();
std::cout << (e->remove(227)) << std::endl;
*e=*b;
*c=*e;
std::cout << (c->insert(274)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
std::cout << (b->insert(267)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
std::cout << (b->insert(133)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->remove(274)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
*e=*a;
std::cout << (c->insert(395)) << std::endl;
std::cout << (d->insert(274)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
std::cout << (e->remove(187)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
std::cout << (d->insert(430)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
std::cout << (d->insert(397)) << std::endl;
*c=*b;
std::cout << (a->remove(14)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (d->insert(397)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
a->printPretty();
std::cout << (e->remove(132)) << std::endl;
std::cout << (c->remove(174)) << std::endl;
c->printPretty();
std::cout << (a->insert(422)) << std::endl;
std::cout << (e->remove(473)) << std::endl;
*a=*e;
std::cout << (a->insert(453)) << std::endl;
std::cout << (a->remove(38)) << std::endl;
*a=*a;
std::cout << (a->insert(453)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (b->remove(217)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
std::cout << (b->remove(133)) << std::endl;
std::cout << (e->remove(446)) << std::endl;
std::cout << (a->remove(315)) << std::endl;
std::cout << (c->insert(54)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
std::cout << (e->remove(74)) << std::endl;
a->printPretty();
std::cout << (a->insert(240)) << std::endl;
*c=*b;
std::cout << (b->insert(69)) << std::endl;
d->printPretty();
std::cout << (a->insert(453)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
*e=*e;
std::cout << (a->insert(8)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
c->printPretty();
*b=*c;
d->printPretty();
std::cout << (b->remove(257)) << std::endl;
std::cout << (d->insert(80)) << std::endl;
b->printPretty();
std::cout << (b->insert(251)) << std::endl;
*b=*e;
std::cout << (e->remove(247)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
std::cout << (a->remove(483)) << std::endl;
*e=*d;
std::cout << (d->remove(397)) << std::endl;
*c=*c;
std::cout << (c->insert(385)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (e->remove(80)) << std::endl;
std::cout << (d->remove(3)) << std::endl;
*c=*c;
std::cout << (a->remove(127)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
b->printPretty();
std::cout << (a->insert(74)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->remove(473)) << std::endl;
e->printPretty();
d->printPretty();
d->printPretty();
e->printPretty();
b->printPretty();
std::cout << (e->insert(118)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
*a=*d;
std::cout << (a->remove(96)) << std::endl;
std::cout << (a->insert(170)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (d->remove(224)) << std::endl;
std::cout << (e->insert(85)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->remove(455)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
*e=*c;
std::cout << (e->insert(319)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
*a=*a;
std::cout << (d->insert(85)) << std::endl;
a->printPretty();
std::cout << (d->remove(274)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
a->printPretty();
std::cout << (b->remove(268)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (e->insert(319)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
std::cout << (c->remove(103)) << std::endl;
d->printPretty();
std::cout << (b->remove(491)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (a->insert(85)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (b->insert(319)) << std::endl;
b->printPretty();
std::cout << (d->remove(407)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (a->remove(215)) << std::endl;
std::cout << (e->remove(319)) << std::endl;
d->printPretty();
std::cout << (d->insert(85)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (e->remove(224)) << std::endl;
d->printPretty();
std::cout << (c->insert(178)) << std::endl;
e->printPretty();
d->printPretty();
*d=*b;
std::cout << (c->insert(429)) << std::endl;
b->printPretty();
c->printPretty();
*b=*d;
std::cout << (d->insert(67)) << std::endl;
*c=*a;
std::cout << (c->insert(365)) << std::endl;
std::cout << (e->remove(87)) << std::endl;
*b=*d;
std::cout << (a->remove(480)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
c->printPretty();
std::cout << (a->remove(188)) << std::endl;
*a=*b;
std::cout << (d->insert(319)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (a->remove(163)) << std::endl;
e->printPretty();
*e=*d;
d->printPretty();
c->printPretty();
std::cout << (a->insert(115)) << std::endl;
std::cout << (d->insert(393)) << std::endl;
*b=*c;
std::cout << (c->remove(315)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
c->printPretty();
std::cout << (a->remove(244)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (c->insert(336)) << std::endl;
std::cout << (e->insert(67)) << std::endl;
std::cout << (e->remove(67)) << std::endl;
c->printPretty();
std::cout << (e->insert(319)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
e->printPretty();
std::cout << (a->insert(194)) << std::endl;
*b=*c;
std::cout << (b->insert(130)) << std::endl;
*c=*e;
std::cout << (b->insert(416)) << std::endl;
e->printPretty();
*d=*c;
e->printPretty();
std::cout << (e->insert(295)) << std::endl;
std::cout << (e->remove(319)) << std::endl;
std::cout << (a->insert(328)) << std::endl;
std::cout << (c->remove(319)) << std::endl;
std::cout << (e->insert(295)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
std::cout << (e->insert(311)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
std::cout << (b->insert(267)) << std::endl;
std::cout << (d->remove(32)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (b->insert(187)) << std::endl;
*c=*c;
std::cout << (b->remove(274)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
std::cout << (b->insert(45)) << std::endl;
d->printPretty();
std::cout << (b->remove(45)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
std::cout << (b->insert(168)) << std::endl;
*c=*c;
std::cout << (e->remove(470)) << std::endl;
a->printPretty();
std::cout << (e->remove(295)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
std::cout << (e->remove(311)) << std::endl;
std::cout << (e->remove(90)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
*b=*b;
*a=*b;
std::cout << (b->insert(168)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
*d=*b;
std::cout << (b->insert(156)) << std::endl;
*d=*b;
*d=*d;
a->printPretty();
c->printPretty();
std::cout << (d->insert(187)) << std::endl;
e->printPretty();
d->printPretty();
a->printPretty();
a->printPretty();
std::cout << (e->insert(152)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (b->insert(225)) << std::endl;
*d=*a;
std::cout << (d->remove(187)) << std::endl;
std::cout << (e->remove(347)) << std::endl;
*b=*a;
std::cout << (e->insert(152)) << std::endl;
std::cout << (b->remove(187)) << std::endl;
d->printPretty();
std::cout << (c->remove(180)) << std::endl;
std::cout << (a->insert(187)) << std::endl;
std::cout << (d->insert(118)) << std::endl;
c->printPretty();
std::cout << (d->remove(414)) << std::endl;
std::cout << (b->insert(168)) << std::endl;
*d=*c;
std::cout << (d->remove(104)) << std::endl;
std::cout << (b->remove(168)) << std::endl;
a->printPretty();
std::cout << (d->insert(234)) << std::endl;
c->printPretty();
std::cout << (a->remove(168)) << std::endl;
*e=*b;
std::cout << (a->insert(168)) << std::endl;
*e=*c;
*e=*c;
std::cout << (d->insert(298)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(257)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
e->printPretty();
std::cout << (b->remove(188)) << std::endl;
std::cout << (d->insert(221)) << std::endl;
e->printPretty();
std::cout << (b->remove(384)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
std::cout << (d->remove(298)) << std::endl;
d->printPretty();
std::cout << (b->remove(211)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
c->printPretty();
std::cout << (c->remove(409)) << std::endl;
*a=*c;
std::cout << (a->remove(240)) << std::endl;
e->printPretty();
std::cout << (d->insert(221)) << std::endl;
std::cout << (b->remove(149)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
std::cout << (c->remove(168)) << std::endl;
*c=*d;
*e=*d;
std::cout << (d->remove(221)) << std::endl;
*a=*b;
std::cout << (d->remove(500)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
a->printPretty();
std::cout << (b->remove(333)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->insert(389)) << std::endl;
std::cout << (a->insert(455)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (c->insert(221)) << std::endl;
*b=*a;
std::cout << (c->insert(221)) << std::endl;
std::cout << (b->insert(455)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
std::cout << (c->remove(221)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
return 0;
}
