#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->insert(199)) << std::endl;
std::cout << (b->remove(199)) << std::endl;
std::cout << (a->insert(70)) << std::endl;
std::cout << (a->remove(70)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->insert(39)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
b->printPretty();
std::cout << (a->insert(302)) << std::endl;
*a=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
c->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*d=*a;
d->printPretty();
std::cout << (e->insert(116)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
std::cout << (b->remove(329)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
std::cout << (a->insert(51)) << std::endl;
*d=*c;
*a=*e;
a->printPretty();
*e=*b;
*a=*c;
std::cout << (d->remove(7)) << std::endl;
e->printPretty();
c->printPretty();
e->printPretty();
std::cout << (c->remove(13)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (d->remove(89)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
std::cout << (a->remove(185)) << std::endl;
*d=*c;
*c=*c;
*e=*a;
std::cout << (d->remove(42)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (e->insert(5)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
std::cout << (b->remove(459)) << std::endl;
std::cout << (a->remove(365)) << std::endl;
std::cout << (a->remove(194)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
std::cout << (d->insert(155)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
std::cout << (b->insert(243)) << std::endl;
std::cout << (d->insert(155)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
*c=*b;
b->printPretty();
*a=*b;
d->printPretty();
std::cout << (d->remove(10)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
*b=*a;
*b=*d;
std::cout << (d->remove(133)) << std::endl;
std::cout << (d->insert(252)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
a->printPretty();
std::cout << (d->remove(279)) << std::endl;
std::cout << (d->insert(252)) << std::endl;
d->printPretty();
*d=*b;
e->printPretty();
std::cout << (d->remove(155)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
e->printPretty();
std::cout << (e->insert(231)) << std::endl;
std::cout << (c->insert(468)) << std::endl;
*b=*c;
std::cout << (e->remove(17)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
*a=*a;
std::cout << (d->remove(141)) << std::endl;
e->printPretty();
std::cout << (b->insert(468)) << std::endl;
c->printPretty();
std::cout << (e->insert(399)) << std::endl;
std::cout << (a->remove(243)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->remove(399)) << std::endl;
std::cout << (c->insert(87)) << std::endl;
a->printPretty();
std::cout << (e->remove(169)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
*b=*e;
std::cout << (a->insert(378)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
*d=*c;
std::cout << (e->remove(404)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
std::cout << (d->remove(246)) << std::endl;
b->printPretty();
std::cout << (a->remove(97)) << std::endl;
*e=*e;
std::cout << (e->insert(231)) << std::endl;
*d=*e;
std::cout << (c->remove(236)) << std::endl;
*c=*b;
std::cout << (e->remove(231)) << std::endl;
std::cout << (c->insert(231)) << std::endl;
e->printPretty();
std::cout << (a->insert(116)) << std::endl;
std::cout << (e->insert(323)) << std::endl;
std::cout << (d->insert(378)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
std::cout << (b->remove(241)) << std::endl;
*c=*b;
std::cout << (d->insert(231)) << std::endl;
std::cout << (a->remove(214)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
c->printPretty();
std::cout << (d->insert(278)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
std::cout << (d->remove(231)) << std::endl;
*c=*a;
std::cout << (c->remove(373)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
c->printPretty();
std::cout << (c->remove(378)) << std::endl;
std::cout << (c->insert(198)) << std::endl;
std::cout << (b->remove(496)) << std::endl;
std::cout << (c->remove(198)) << std::endl;
a->printPretty();
std::cout << (c->insert(179)) << std::endl;
std::cout << (a->insert(163)) << std::endl;
std::cout << (d->insert(278)) << std::endl;
d->printPretty();
std::cout << (a->insert(150)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->remove(8)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (b->insert(37)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (c->remove(483)) << std::endl;
e->printPretty();
*d=*a;
c->printPretty();
std::cout << (c->remove(116)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
std::cout << (d->remove(231)) << std::endl;
std::cout << (b->remove(137)) << std::endl;
e->printPretty();
a->printPretty();
*e=*d;
std::cout << (c->insert(430)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
b->printPretty();
std::cout << (b->insert(37)) << std::endl;
std::cout << (b->insert(37)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
std::cout << (d->remove(186)) << std::endl;
*d=*c;
std::cout << (d->insert(363)) << std::endl;
std::cout << (b->insert(37)) << std::endl;
a->printPretty();
std::cout << (a->remove(121)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
c->printPretty();
std::cout << (a->insert(137)) << std::endl;
std::cout << (d->remove(464)) << std::endl;
std::cout << (e->remove(349)) << std::endl;
b->printPretty();
std::cout << (b->insert(79)) << std::endl;
std::cout << (e->remove(71)) << std::endl;
*a=*e;
std::cout << (c->remove(459)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
d->printPretty();
std::cout << (a->remove(202)) << std::endl;
*c=*a;
std::cout << (d->insert(363)) << std::endl;
std::cout << (c->remove(137)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
*e=*a;
std::cout << (b->remove(229)) << std::endl;
a->printPretty();
std::cout << (b->remove(182)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (b->insert(37)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (c->insert(233)) << std::endl;
std::cout << (e->remove(124)) << std::endl;
std::cout << (b->insert(416)) << std::endl;
std::cout << (c->remove(31)) << std::endl;
std::cout << (b->remove(158)) << std::endl;
std::cout << (b->remove(430)) << std::endl;
std::cout << (b->insert(58)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
std::cout << (b->remove(398)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
d->printPretty();
std::cout << (d->insert(35)) << std::endl;
std::cout << (c->insert(422)) << std::endl;
*a=*b;
std::cout << (a->remove(88)) << std::endl;
std::cout << (e->remove(90)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
e->printPretty();
std::cout << (a->remove(183)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (c->insert(233)) << std::endl;
a->printPretty();
std::cout << (d->remove(35)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
b->printPretty();
e->printPretty();
*d=*b;
*e=*e;
*b=*b;
std::cout << (b->insert(159)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
std::cout << (a->remove(34)) << std::endl;
std::cout << (a->insert(165)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (e->remove(58)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
*e=*d;
std::cout << (b->insert(480)) << std::endl;
std::cout << (d->remove(379)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
std::cout << (c->remove(341)) << std::endl;
c->printPretty();
std::cout << (b->remove(79)) << std::endl;
*e=*c;
e->printPretty();
std::cout << (d->remove(414)) << std::endl;
std::cout << (a->remove(231)) << std::endl;
*e=*b;
std::cout << (a->remove(291)) << std::endl;
std::cout << (b->remove(355)) << std::endl;
std::cout << (b->remove(416)) << std::endl;
std::cout << (b->insert(426)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
*d=*d;
std::cout << (a->insert(58)) << std::endl;
e->printPretty();
*e=*e;
*a=*a;
std::cout << (c->remove(247)) << std::endl;
std::cout << (b->insert(41)) << std::endl;
std::cout << (e->remove(356)) << std::endl;
std::cout << (b->remove(426)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
*c=*d;
*e=*b;
*a=*e;
std::cout << (e->remove(33)) << std::endl;
*a=*d;
std::cout << (b->remove(124)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
std::cout << (a->insert(392)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (c->insert(356)) << std::endl;
*e=*a;
std::cout << (e->remove(13)) << std::endl;
c->printPretty();
std::cout << (c->insert(257)) << std::endl;
b->printPretty();
e->printPretty();
b->printPretty();
std::cout << (b->insert(231)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
*d=*e;
*b=*c;
*e=*b;
std::cout << (e->insert(413)) << std::endl;
*b=*e;
*e=*e;
std::cout << (a->insert(114)) << std::endl;
std::cout << (e->remove(96)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
*b=*b;
std::cout << (c->insert(484)) << std::endl;
c->printPretty();
*d=*c;
std::cout << (c->insert(326)) << std::endl;
b->printPretty();
std::cout << (c->remove(58)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
*b=*a;
std::cout << (c->remove(79)) << std::endl;
std::cout << (b->insert(74)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
std::cout << (d->remove(58)) << std::endl;
*e=*c;
std::cout << (b->insert(79)) << std::endl;
std::cout << (e->remove(225)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
b->printPretty();
std::cout << (a->insert(350)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (b->remove(231)) << std::endl;
std::cout << (d->insert(411)) << std::endl;
std::cout << (a->remove(356)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (d->remove(484)) << std::endl;
std::cout << (a->insert(374)) << std::endl;
std::cout << (e->insert(70)) << std::endl;
std::cout << (a->remove(58)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
e->printPretty();
std::cout << (c->insert(350)) << std::endl;
std::cout << (c->insert(410)) << std::endl;
*e=*c;
std::cout << (d->remove(31)) << std::endl;
std::cout << (e->remove(410)) << std::endl;
std::cout << (c->remove(346)) << std::endl;
c->printPretty();
std::cout << (a->remove(374)) << std::endl;
std::cout << (e->remove(231)) << std::endl;
std::cout << (b->insert(173)) << std::endl;
std::cout << (a->insert(79)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
a->printPretty();
d->printPretty();
*c=*d;
std::cout << (b->remove(182)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
*c=*e;
*e=*b;
std::cout << (e->insert(427)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
b->printPretty();
std::cout << (b->remove(70)) << std::endl;
e->printPretty();
std::cout << (d->remove(443)) << std::endl;
*b=*b;
std::cout << (e->insert(316)) << std::endl;
d->printPretty();
std::cout << (e->remove(54)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (e->remove(70)) << std::endl;
std::cout << (a->remove(187)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
b->printPretty();
std::cout << (c->remove(317)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
d->printPretty();
std::cout << (c->insert(368)) << std::endl;
std::cout << (e->insert(333)) << std::endl;
*b=*b;
std::cout << (b->insert(413)) << std::endl;
*a=*b;
std::cout << (c->insert(231)) << std::endl;
*b=*e;
std::cout << (b->remove(377)) << std::endl;
b->printPretty();
std::cout << (d->remove(79)) << std::endl;
std::cout << (c->remove(386)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
std::cout << (c->insert(22)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (a->remove(72)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
b->printPretty();
std::cout << (b->remove(321)) << std::endl;
*a=*e;
std::cout << (e->remove(413)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
std::cout << (d->insert(493)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
std::cout << (b->remove(333)) << std::endl;
c->printPretty();
std::cout << (c->insert(37)) << std::endl;
*a=*d;
std::cout << (a->insert(356)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
*a=*b;
std::cout << (e->insert(58)) << std::endl;
*b=*b;
std::cout << (b->insert(316)) << std::endl;
a->printPretty();
std::cout << (e->remove(231)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
std::cout << (a->insert(173)) << std::endl;
std::cout << (e->insert(49)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
*e=*e;
std::cout << (d->remove(276)) << std::endl;
std::cout << (b->remove(427)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
*b=*c;
e->printPretty();
std::cout << (b->remove(118)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (d->remove(43)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
std::cout << (d->remove(356)) << std::endl;
std::cout << (a->remove(37)) << std::endl;
std::cout << (c->insert(318)) << std::endl;
*b=*b;
*d=*d;
std::cout << (e->remove(37)) << std::endl;
std::cout << (d->remove(231)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
std::cout << (c->remove(413)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (c->remove(350)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
*e=*b;
std::cout << (e->insert(79)) << std::endl;
std::cout << (d->remove(493)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (e->insert(143)) << std::endl;
b->printPretty();
std::cout << (d->insert(257)) << std::endl;
*c=*d;
std::cout << (a->insert(145)) << std::endl;
std::cout << (e->insert(259)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
a->printPretty();
std::cout << (d->remove(90)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (a->insert(173)) << std::endl;
std::cout << (b->insert(41)) << std::endl;
std::cout << (a->remove(356)) << std::endl;
d->printPretty();
std::cout << (a->remove(361)) << std::endl;
std::cout << (d->remove(231)) << std::endl;
*d=*a;
std::cout << (b->remove(79)) << std::endl;
std::cout << (c->insert(411)) << std::endl;
std::cout << (d->insert(114)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
c->printPretty();
std::cout << (a->remove(413)) << std::endl;
std::cout << (d->remove(179)) << std::endl;
std::cout << (a->insert(173)) << std::endl;
*e=*d;
*a=*d;
std::cout << (b->insert(254)) << std::endl;
std::cout << (b->insert(144)) << std::endl;
std::cout << (d->insert(427)) << std::endl;
std::cout << (e->remove(413)) << std::endl;
std::cout << (b->remove(485)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
*a=*b;
std::cout << (c->remove(411)) << std::endl;
std::cout << (e->remove(189)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
std::cout << (c->insert(244)) << std::endl;
std::cout << (b->remove(153)) << std::endl;
*e=*a;
std::cout << (e->insert(144)) << std::endl;
std::cout << (d->insert(10)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (c->remove(244)) << std::endl;
std::cout << (d->remove(58)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (c->remove(425)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
std::cout << (e->remove(24)) << std::endl;
d->printPretty();
std::cout << (a->remove(254)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (b->insert(68)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
std::cout << (c->remove(291)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (b->remove(316)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
*c=*a;
*b=*a;
std::cout << (b->remove(148)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
std::cout << (a->insert(144)) << std::endl;
a->printPretty();
std::cout << (d->remove(277)) << std::endl;
std::cout << (d->remove(144)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
d->printPretty();
std::cout << (e->insert(343)) << std::endl;
std::cout << (b->insert(58)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
std::cout << (b->insert(144)) << std::endl;
std::cout << (c->remove(251)) << std::endl;
e->printPretty();
std::cout << (c->remove(51)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
std::cout << (d->remove(58)) << std::endl;
std::cout << (c->remove(58)) << std::endl;
std::cout << (e->remove(110)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
std::cout << (a->insert(254)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
d->printPretty();
std::cout << (a->remove(131)) << std::endl;
*d=*b;
b->printPretty();
std::cout << (c->remove(288)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
*a=*b;
*c=*c;
d->printPretty();
e->printPretty();
std::cout << (a->remove(458)) << std::endl;
std::cout << (a->insert(144)) << std::endl;
*d=*e;
c->printPretty();
std::cout << (c->insert(500)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
std::cout << (a->remove(57)) << std::endl;
std::cout << (a->remove(41)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
std::cout << (c->remove(44)) << std::endl;
d->printPretty();
std::cout << (d->insert(343)) << std::endl;
std::cout << (b->insert(57)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
*e=*d;
*a=*a;
e->printPretty();
std::cout << (a->insert(251)) << std::endl;
*d=*d;
std::cout << (d->insert(267)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
std::cout << (b->insert(37)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
std::cout << (a->remove(316)) << std::endl;
b->printPretty();
std::cout << (c->insert(37)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (a->insert(120)) << std::endl;
*e=*c;
std::cout << (d->remove(277)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
*a=*d;
std::cout << (c->insert(378)) << std::endl;
std::cout << (b->remove(316)) << std::endl;
std::cout << (a->insert(20)) << std::endl;
std::cout << (a->insert(58)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (a->remove(454)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (b->insert(41)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (b->remove(231)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (b->remove(41)) << std::endl;
a->printPretty();
std::cout << (b->remove(57)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
std::cout << (b->insert(350)) << std::endl;
*e=*e;
c->printPretty();
d->printPretty();
std::cout << (e->insert(279)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*e=*e;
std::cout << (a->remove(500)) << std::endl;
b->printPretty();
std::cout << (b->insert(22)) << std::endl;
std::cout << (e->insert(22)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
*d=*e;
*e=*e;
std::cout << (e->remove(144)) << std::endl;
std::cout << (a->remove(231)) << std::endl;
std::cout << (e->insert(41)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
e->printPretty();
*c=*b;
std::cout << (b->insert(376)) << std::endl;
*c=*b;
std::cout << (a->remove(350)) << std::endl;
std::cout << (a->remove(316)) << std::endl;
std::cout << (d->remove(340)) << std::endl;
std::cout << (a->insert(144)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
*e=*a;
std::cout << (c->remove(277)) << std::endl;
b->printPretty();
std::cout << (b->remove(144)) << std::endl;
*d=*b;
std::cout << (a->insert(151)) << std::endl;
*b=*a;
std::cout << (c->remove(299)) << std::endl;
*a=*a;
*b=*a;
std::cout << (c->remove(103)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
std::cout << (e->insert(22)) << std::endl;
std::cout << (b->insert(22)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (e->insert(57)) << std::endl;
std::cout << (e->insert(37)) << std::endl;
std::cout << (d->remove(79)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (b->insert(239)) << std::endl;
std::cout << (e->remove(285)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
c->printPretty();
std::cout << (c->remove(350)) << std::endl;
std::cout << (b->remove(239)) << std::endl;
*c=*b;
std::cout << (c->insert(303)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->insert(37)) << std::endl;
*c=*d;
std::cout << (e->insert(37)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (d->remove(290)) << std::endl;
*e=*e;
std::cout << (e->remove(41)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (a->remove(478)) << std::endl;
*b=*c;
std::cout << (b->remove(115)) << std::endl;
*c=*b;
std::cout << (a->insert(63)) << std::endl;
std::cout << (d->remove(358)) << std::endl;
*a=*e;
std::cout << (c->insert(277)) << std::endl;
c->printPretty();
std::cout << (c->remove(277)) << std::endl;
std::cout << (e->remove(341)) << std::endl;
std::cout << (d->remove(323)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (d->remove(251)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
d->printPretty();
*d=*b;
a->printPretty();
*a=*d;
e->printPretty();
std::cout << (a->insert(251)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
b->printPretty();
std::cout << (a->remove(358)) << std::endl;
std::cout << (a->remove(37)) << std::endl;
std::cout << (e->insert(304)) << std::endl;
return 0;
}
