#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(443)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
std::cout << (a->insert(231)) << std::endl;
std::cout << (a->insert(436)) << std::endl;
b->printPretty();
b->printPretty();
*b=*b;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
b->printPretty();
std::cout << (a->insert(306)) << std::endl;
std::cout << (c->insert(179)) << std::endl;
*c=*c;
std::cout << (a->remove(436)) << std::endl;
a->printPretty();
std::cout << (c->remove(323)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
c->printPretty();
std::cout << (c->remove(252)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (d->insert(143)) << std::endl;
*a=*a;
std::cout << (d->remove(143)) << std::endl;
std::cout << (d->insert(240)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (a->insert(384)) << std::endl;
std::cout << (a->remove(169)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
std::cout << (b->remove(424)) << std::endl;
std::cout << (d->remove(238)) << std::endl;
*b=*d;
std::cout << (a->insert(384)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (d->remove(17)) << std::endl;
std::cout << (d->insert(240)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
std::cout << (a->insert(272)) << std::endl;
*a=*c;
std::cout << (c->remove(179)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
std::cout << (d->remove(240)) << std::endl;
std::cout << (a->insert(179)) << std::endl;
c->printPretty();
a->printPretty();
*d=*c;
*b=*d;
std::cout << (e->insert(387)) << std::endl;
std::cout << (c->insert(18)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
std::cout << (a->remove(179)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
*a=*a;
std::cout << (b->insert(319)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
*a=*e;
std::cout << (b->insert(283)) << std::endl;
*a=*b;
std::cout << (b->remove(319)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
*c=*e;
std::cout << (b->insert(401)) << std::endl;
std::cout << (d->insert(244)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
e->printPretty();
std::cout << (a->insert(484)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
std::cout << (d->remove(381)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
e->printPretty();
std::cout << (b->remove(401)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (e->insert(425)) << std::endl;
*c=*c;
std::cout << (e->remove(425)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
std::cout << (e->insert(452)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
std::cout << (a->remove(247)) << std::endl;
a->printPretty();
std::cout << (c->insert(442)) << std::endl;
std::cout << (c->insert(84)) << std::endl;
std::cout << (e->remove(452)) << std::endl;
std::cout << (d->insert(251)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
*b=*c;
std::cout << (c->insert(442)) << std::endl;
std::cout << (e->remove(154)) << std::endl;
b->printPretty();
std::cout << (c->insert(84)) << std::endl;
std::cout << (b->remove(8)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (c->remove(395)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
*d=*c;
std::cout << (c->remove(302)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
*d=*a;
std::cout << (c->remove(387)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (d->remove(319)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
*a=*e;
std::cout << (e->remove(150)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
std::cout << (b->remove(10)) << std::endl;
std::cout << (e->remove(34)) << std::endl;
std::cout << (a->insert(156)) << std::endl;
e->printPretty();
c->printPretty();
d->printPretty();
*b=*d;
std::cout << (c->insert(442)) << std::endl;
std::cout << (c->insert(146)) << std::endl;
*e=*a;
std::cout << (a->remove(165)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->insert(84)) << std::endl;
std::cout << (e->insert(156)) << std::endl;
*d=*d;
std::cout << (d->insert(169)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
std::cout << (a->insert(156)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
std::cout << (c->remove(126)) << std::endl;
std::cout << (d->insert(437)) << std::endl;
*d=*a;
std::cout << (e->insert(156)) << std::endl;
std::cout << (b->insert(169)) << std::endl;
std::cout << (c->remove(217)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (d->remove(18)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
*b=*a;
std::cout << (e->remove(156)) << std::endl;
std::cout << (a->insert(165)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->insert(147)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (c->insert(147)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
std::cout << (b->remove(137)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
std::cout << (d->insert(4)) << std::endl;
std::cout << (a->remove(18)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
std::cout << (c->insert(60)) << std::endl;
*c=*e;
std::cout << (b->remove(226)) << std::endl;
std::cout << (c->remove(492)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
b->printPretty();
std::cout << (c->insert(184)) << std::endl;
c->printPretty();
std::cout << (b->insert(206)) << std::endl;
e->printPretty();
std::cout << (b->remove(89)) << std::endl;
e->printPretty();
std::cout << (c->remove(282)) << std::endl;
std::cout << (c->remove(253)) << std::endl;
*e=*b;
std::cout << (b->insert(18)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (d->insert(138)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
c->printPretty();
std::cout << (c->insert(176)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
std::cout << (a->insert(453)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (a->insert(361)) << std::endl;
c->printPretty();
*b=*b;
b->printPretty();
std::cout << (e->remove(357)) << std::endl;
std::cout << (b->remove(18)) << std::endl;
std::cout << (a->remove(453)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
std::cout << (a->remove(486)) << std::endl;
*d=*a;
std::cout << (e->insert(147)) << std::endl;
*e=*a;
std::cout << (e->insert(464)) << std::endl;
std::cout << (c->remove(221)) << std::endl;
b->printPretty();
d->printPretty();
b->printPretty();
c->printPretty();
std::cout << (e->insert(361)) << std::endl;
a->printPretty();
*e=*b;
d->printPretty();
*c=*d;
*e=*a;
std::cout << (e->remove(388)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (a->remove(243)) << std::endl;
a->printPretty();
std::cout << (b->insert(471)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
std::cout << (a->remove(115)) << std::endl;
std::cout << (e->insert(146)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (c->remove(361)) << std::endl;
*e=*e;
std::cout << (e->remove(146)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->insert(406)) << std::endl;
std::cout << (d->remove(174)) << std::endl;
std::cout << (e->remove(31)) << std::endl;
*b=*b;
std::cout << (b->insert(357)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
c->printPretty();
*d=*d;
std::cout << (b->insert(471)) << std::endl;
e->printPretty();
std::cout << (b->remove(471)) << std::endl;
a->printPretty();
*a=*c;
c->printPretty();
a->printPretty();
std::cout << (a->remove(110)) << std::endl;
*e=*a;
std::cout << (b->insert(489)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (c->remove(207)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (b->remove(489)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (a->insert(399)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
c->printPretty();
std::cout << (a->remove(293)) << std::endl;
std::cout << (e->insert(77)) << std::endl;
std::cout << (c->remove(55)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
std::cout << (c->remove(120)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->remove(296)) << std::endl;
*e=*e;
std::cout << (b->insert(448)) << std::endl;
*c=*b;
std::cout << (a->insert(399)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
e->printPretty();
std::cout << (a->remove(312)) << std::endl;
*e=*a;
std::cout << (e->remove(480)) << std::endl;
*a=*d;
std::cout << (c->remove(485)) << std::endl;
b->printPretty();
std::cout << (a->remove(216)) << std::endl;
b->printPretty();
std::cout << (d->remove(69)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (e->insert(113)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
std::cout << (e->remove(113)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (c->insert(108)) << std::endl;
d->printPretty();
std::cout << (d->remove(57)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
*c=*e;
std::cout << (c->insert(399)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(453)) << std::endl;
std::cout << (c->remove(43)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
a->printPretty();
std::cout << (e->insert(175)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
*c=*b;
std::cout << (c->insert(169)) << std::endl;
*e=*d;
std::cout << (c->remove(245)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (b->insert(353)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
*c=*c;
*c=*e;
std::cout << (c->insert(320)) << std::endl;
std::cout << (e->remove(477)) << std::endl;
*b=*b;
std::cout << (b->insert(478)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
*b=*c;
std::cout << (e->insert(204)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (e->remove(204)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (e->remove(122)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(355)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
*e=*e;
std::cout << (b->insert(320)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (c->remove(119)) << std::endl;
std::cout << (b->remove(477)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (c->remove(122)) << std::endl;
std::cout << (d->remove(275)) << std::endl;
*e=*b;
std::cout << (d->insert(42)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
std::cout << (b->remove(320)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->insert(452)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (a->remove(226)) << std::endl;
std::cout << (d->remove(42)) << std::endl;
std::cout << (e->insert(11)) << std::endl;
*e=*a;
std::cout << (b->insert(62)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (c->insert(323)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
std::cout << (a->remove(452)) << std::endl;
a->printPretty();
std::cout << (b->insert(416)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->insert(206)) << std::endl;
std::cout << (e->insert(452)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (e->insert(452)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->insert(464)) << std::endl;
std::cout << (e->remove(452)) << std::endl;
*e=*b;
*c=*d;
*e=*e;
std::cout << (a->insert(225)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (d->remove(122)) << std::endl;
std::cout << (a->remove(225)) << std::endl;
b->printPretty();
*c=*a;
a->printPretty();
std::cout << (d->remove(382)) << std::endl;
e->printPretty();
std::cout << (e->remove(209)) << std::endl;
*e=*e;
std::cout << (e->remove(54)) << std::endl;
*d=*e;
*b=*b;
std::cout << (d->insert(124)) << std::endl;
std::cout << (c->remove(405)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
*c=*a;
b->printPretty();
e->printPretty();
*d=*d;
std::cout << (d->insert(419)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (a->remove(284)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
std::cout << (b->insert(416)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
*e=*d;
*c=*a;
std::cout << (c->remove(419)) << std::endl;
*e=*a;
std::cout << (e->remove(419)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
c->printPretty();
std::cout << (c->insert(206)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
*a=*b;
std::cout << (e->remove(7)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
b->printPretty();
std::cout << (b->insert(62)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (a->remove(320)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
*b=*b;
*b=*a;
*e=*b;
std::cout << (b->remove(101)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->insert(73)) << std::endl;
b->printPretty();
std::cout << (e->remove(168)) << std::endl;
std::cout << (c->remove(124)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
d->printPretty();
std::cout << (e->insert(209)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
*b=*a;
std::cout << (a->insert(478)) << std::endl;
std::cout << (d->remove(21)) << std::endl;
e->printPretty();
std::cout << (d->remove(419)) << std::endl;
std::cout << (d->insert(73)) << std::endl;
e->printPretty();
std::cout << (a->remove(271)) << std::endl;
*e=*b;
std::cout << (a->insert(425)) << std::endl;
std::cout << (b->remove(209)) << std::endl;
std::cout << (c->insert(269)) << std::endl;
std::cout << (e->insert(206)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (c->insert(338)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
std::cout << (b->insert(461)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
*e=*b;
std::cout << (e->remove(329)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
std::cout << (b->insert(382)) << std::endl;
e->printPretty();
*a=*a;
e->printPretty();
e->printPretty();
std::cout << (c->remove(282)) << std::endl;
b->printPretty();
c->printPretty();
b->printPretty();
std::cout << (e->insert(425)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
std::cout << (c->insert(105)) << std::endl;
std::cout << (c->insert(416)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
b->printPretty();
std::cout << (b->insert(295)) << std::endl;
c->printPretty();
std::cout << (a->insert(178)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
c->printPretty();
std::cout << (c->remove(416)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
std::cout << (b->insert(27)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (c->remove(406)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
std::cout << (e->insert(338)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
a->printPretty();
b->printPretty();
b->printPretty();
std::cout << (d->remove(367)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (b->remove(254)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
*d=*a;
std::cout << (c->remove(211)) << std::endl;
*e=*a;
std::cout << (e->insert(209)) << std::endl;
*b=*c;
*a=*a;
b->printPretty();
std::cout << (b->remove(165)) << std::endl;
std::cout << (b->remove(124)) << std::endl;
*e=*c;
c->printPretty();
std::cout << (e->insert(165)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
*c=*b;
std::cout << (e->insert(184)) << std::endl;
std::cout << (e->insert(124)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
std::cout << (a->insert(209)) << std::endl;
*e=*d;
std::cout << (c->insert(169)) << std::endl;
*b=*b;
*d=*d;
std::cout << (b->remove(24)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
std::cout << (d->remove(271)) << std::endl;
std::cout << (a->remove(230)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (e->remove(209)) << std::endl;
*a=*c;
std::cout << (e->insert(297)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
*d=*e;
std::cout << (e->remove(425)) << std::endl;
*e=*e;
std::cout << (d->remove(206)) << std::endl;
c->printPretty();
std::cout << (c->remove(403)) << std::endl;
a->printPretty();
e->printPretty();
*d=*b;
std::cout << (e->insert(102)) << std::endl;
std::cout << (a->insert(362)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
std::cout << (c->remove(427)) << std::endl;
d->printPretty();
std::cout << (c->insert(169)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
std::cout << (a->insert(169)) << std::endl;
*c=*e;
std::cout << (b->insert(123)) << std::endl;
std::cout << (d->insert(209)) << std::endl;
*c=*d;
std::cout << (c->insert(206)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
b->printPretty();
c->printPretty();
b->printPretty();
std::cout << (a->insert(192)) << std::endl;
*d=*e;
std::cout << (a->insert(377)) << std::endl;
std::cout << (e->remove(178)) << std::endl;
std::cout << (c->remove(146)) << std::endl;
*e=*d;
std::cout << (d->insert(310)) << std::endl;
std::cout << (b->remove(425)) << std::endl;
std::cout << (e->remove(206)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
*a=*e;
std::cout << (e->remove(266)) << std::endl;
std::cout << (d->insert(206)) << std::endl;
c->printPretty();
std::cout << (c->remove(425)) << std::endl;
*c=*d;
std::cout << (a->insert(178)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
std::cout << (c->insert(403)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
std::cout << (d->insert(75)) << std::endl;
std::cout << (e->remove(62)) << std::endl;
c->printPretty();
std::cout << (c->remove(372)) << std::endl;
d->printPretty();
std::cout << (e->insert(478)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
e->printPretty();
std::cout << (b->insert(206)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
*a=*e;
a->printPretty();
*c=*b;
std::cout << (e->remove(323)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
a->printPretty();
std::cout << (a->remove(478)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->insert(206)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (d->insert(319)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
b->printPretty();
std::cout << (c->remove(123)) << std::endl;
std::cout << (c->insert(118)) << std::endl;
e->printPretty();
std::cout << (c->remove(209)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
*d=*d;
std::cout << (b->insert(206)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
a->printPretty();
std::cout << (d->insert(206)) << std::endl;
e->printPretty();
std::cout << (b->remove(346)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (d->insert(206)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (c->remove(352)) << std::endl;
a->printPretty();
*b=*c;
d->printPretty();
std::cout << (a->insert(209)) << std::endl;
e->printPretty();
std::cout << (a->insert(478)) << std::endl;
std::cout << (b->remove(95)) << std::endl;
*c=*e;
std::cout << (c->remove(272)) << std::endl;
std::cout << (b->remove(206)) << std::endl;
std::cout << (e->insert(377)) << std::endl;
c->printPretty();
std::cout << (e->insert(178)) << std::endl;
*c=*d;
*a=*c;
d->printPretty();
std::cout << (a->insert(245)) << std::endl;
e->printPretty();
std::cout << (d->insert(115)) << std::endl;
*a=*d;
std::cout << (b->remove(118)) << std::endl;
std::cout << (a->insert(30)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
return 0;
}
