#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
std::cout << (a->remove(123)) << std::endl;
std::cout << (a->insert(328)) << std::endl;
*b=*b;
std::cout << (b->insert(328)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->insert(391)) << std::endl;
*b=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->remove(112)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
*d=*a;
std::cout << (b->insert(328)) << std::endl;
b->printPretty();
*e=*e;
std::cout << (e->remove(347)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
std::cout << (a->insert(429)) << std::endl;
std::cout << (a->insert(391)) << std::endl;
std::cout << (e->remove(128)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
b->printPretty();
std::cout << (b->insert(328)) << std::endl;
a->printPretty();
std::cout << (c->insert(46)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (b->insert(328)) << std::endl;
std::cout << (a->insert(10)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
*e=*b;
std::cout << (d->remove(111)) << std::endl;
std::cout << (b->insert(240)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
std::cout << (e->remove(328)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
b->printPretty();
std::cout << (b->insert(328)) << std::endl;
std::cout << (a->insert(429)) << std::endl;
*b=*e;
std::cout << (a->remove(226)) << std::endl;
std::cout << (c->remove(461)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
a->printPretty();
std::cout << (b->remove(455)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
*d=*b;
c->printPretty();
d->printPretty();
std::cout << (b->insert(19)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
std::cout << (e->remove(162)) << std::endl;
*a=*c;
std::cout << (d->insert(261)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
b->printPretty();
std::cout << (b->insert(49)) << std::endl;
std::cout << (c->remove(141)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (e->insert(40)) << std::endl;
std::cout << (b->remove(49)) << std::endl;
b->printPretty();
std::cout << (c->remove(164)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
*c=*a;
std::cout << (c->insert(289)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (c->insert(324)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
*a=*a;
b->printPretty();
d->printPretty();
std::cout << (b->insert(19)) << std::endl;
*b=*d;
std::cout << (a->remove(300)) << std::endl;
*c=*d;
*a=*c;
std::cout << (d->remove(261)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (c->remove(261)) << std::endl;
*a=*d;
std::cout << (e->remove(410)) << std::endl;
b->printPretty();
std::cout << (d->insert(348)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
std::cout << (d->insert(348)) << std::endl;
d->printPretty();
std::cout << (c->remove(196)) << std::endl;
std::cout << (d->remove(348)) << std::endl;
a->printPretty();
std::cout << (e->insert(19)) << std::endl;
std::cout << (e->remove(341)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
*e=*e;
std::cout << (e->insert(19)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->insert(343)) << std::endl;
std::cout << (c->insert(274)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
e->printPretty();
std::cout << (d->remove(412)) << std::endl;
*b=*d;
std::cout << (d->remove(230)) << std::endl;
e->printPretty();
std::cout << (e->insert(343)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (b->remove(424)) << std::endl;
std::cout << (c->remove(274)) << std::endl;
*e=*e;
std::cout << (e->insert(347)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (e->remove(96)) << std::endl;
std::cout << (c->insert(347)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
std::cout << (c->insert(347)) << std::endl;
std::cout << (a->remove(127)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
*e=*d;
std::cout << (e->remove(489)) << std::endl;
*a=*b;
std::cout << (d->insert(185)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->remove(369)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
*a=*e;
std::cout << (c->insert(347)) << std::endl;
*c=*c;
std::cout << (c->remove(86)) << std::endl;
*c=*d;
a->printPretty();
*e=*e;
std::cout << (a->insert(267)) << std::endl;
std::cout << (b->insert(94)) << std::endl;
*b=*b;
std::cout << (a->insert(479)) << std::endl;
*a=*b;
c->printPretty();
*a=*b;
e->printPretty();
std::cout << (d->insert(185)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (a->remove(268)) << std::endl;
*c=*c;
std::cout << (c->remove(172)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
*c=*a;
std::cout << (a->remove(378)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
std::cout << (c->remove(296)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
*d=*d;
std::cout << (b->insert(423)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (b->remove(222)) << std::endl;
std::cout << (d->remove(185)) << std::endl;
*e=*d;
std::cout << (b->remove(423)) << std::endl;
std::cout << (a->remove(180)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
*a=*a;
std::cout << (e->insert(326)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
d->printPretty();
std::cout << (a->remove(32)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
*e=*a;
std::cout << (b->insert(94)) << std::endl;
std::cout << (d->remove(42)) << std::endl;
*d=*e;
*a=*d;
std::cout << (b->insert(474)) << std::endl;
b->printPretty();
std::cout << (b->remove(94)) << std::endl;
std::cout << (b->insert(232)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->insert(398)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
std::cout << (b->remove(474)) << std::endl;
std::cout << (a->insert(398)) << std::endl;
*a=*a;
*d=*c;
std::cout << (a->remove(13)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
e->printPretty();
std::cout << (a->remove(233)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (b->insert(232)) << std::endl;
*c=*c;
std::cout << (e->remove(116)) << std::endl;
std::cout << (d->insert(300)) << std::endl;
std::cout << (b->remove(431)) << std::endl;
std::cout << (d->remove(196)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (e->insert(92)) << std::endl;
e->printPretty();
std::cout << (d->insert(232)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
std::cout << (b->insert(232)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
c->printPretty();
b->printPretty();
d->printPretty();
*a=*e;
a->printPretty();
std::cout << (e->insert(189)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (c->insert(173)) << std::endl;
std::cout << (e->remove(189)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
e->printPretty();
std::cout << (b->remove(412)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (d->remove(372)) << std::endl;
*c=*e;
*a=*e;
e->printPretty();
*b=*b;
std::cout << (b->remove(232)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
e->printPretty();
std::cout << (d->remove(458)) << std::endl;
*c=*c;
std::cout << (a->insert(210)) << std::endl;
std::cout << (b->remove(410)) << std::endl;
*c=*d;
std::cout << (c->remove(402)) << std::endl;
b->printPretty();
std::cout << (a->insert(210)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (a->remove(248)) << std::endl;
std::cout << (a->remove(222)) << std::endl;
*e=*a;
std::cout << (c->remove(100)) << std::endl;
std::cout << (d->remove(9)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
*a=*c;
std::cout << (c->remove(141)) << std::endl;
*e=*a;
std::cout << (b->insert(150)) << std::endl;
std::cout << (a->remove(428)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
std::cout << (a->insert(141)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
a->printPretty();
std::cout << (c->insert(418)) << std::endl;
a->printPretty();
std::cout << (e->remove(21)) << std::endl;
std::cout << (a->remove(141)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
*a=*d;
*c=*b;
*c=*e;
*a=*d;
std::cout << (e->insert(232)) << std::endl;
b->printPretty();
std::cout << (d->remove(232)) << std::endl;
std::cout << (d->insert(224)) << std::endl;
std::cout << (c->insert(172)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
std::cout << (c->insert(285)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
*c=*e;
*d=*b;
std::cout << (a->insert(232)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
*a=*b;
std::cout << (c->remove(232)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
*c=*c;
std::cout << (d->remove(481)) << std::endl;
*a=*a;
std::cout << (e->remove(290)) << std::endl;
std::cout << (d->insert(41)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (d->remove(358)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (a->remove(51)) << std::endl;
e->printPretty();
std::cout << (a->remove(348)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (c->remove(442)) << std::endl;
c->printPretty();
*b=*b;
*d=*e;
std::cout << (c->insert(131)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
*d=*c;
std::cout << (c->insert(131)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
std::cout << (d->remove(148)) << std::endl;
*d=*a;
*b=*b;
std::cout << (c->insert(387)) << std::endl;
b->printPretty();
*c=*d;
b->printPretty();
*a=*d;
std::cout << (a->remove(67)) << std::endl;
std::cout << (d->remove(296)) << std::endl;
*a=*e;
*d=*e;
std::cout << (a->remove(254)) << std::endl;
std::cout << (a->insert(406)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
e->printPretty();
std::cout << (d->remove(424)) << std::endl;
*a=*c;
std::cout << (d->insert(78)) << std::endl;
std::cout << (a->insert(500)) << std::endl;
*e=*e;
std::cout << (e->remove(481)) << std::endl;
std::cout << (e->insert(360)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
*d=*e;
*a=*e;
std::cout << (d->remove(437)) << std::endl;
*a=*d;
*a=*c;
*c=*d;
*b=*b;
a->printPretty();
a->printPretty();
std::cout << (e->remove(360)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (c->insert(370)) << std::endl;
std::cout << (c->insert(370)) << std::endl;
*e=*e;
std::cout << (a->remove(344)) << std::endl;
*d=*b;
std::cout << (b->insert(126)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
std::cout << (c->remove(188)) << std::endl;
std::cout << (e->remove(265)) << std::endl;
*d=*b;
std::cout << (c->insert(17)) << std::endl;
*a=*b;
std::cout << (d->remove(394)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (d->remove(388)) << std::endl;
*c=*c;
std::cout << (d->insert(209)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->remove(394)) << std::endl;
std::cout << (e->remove(201)) << std::endl;
std::cout << (e->insert(32)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
std::cout << (a->remove(370)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
std::cout << (c->remove(406)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
*c=*d;
std::cout << (c->remove(303)) << std::endl;
std::cout << (c->remove(115)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (d->remove(69)) << std::endl;
std::cout << (a->insert(125)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (a->remove(108)) << std::endl;
*b=*c;
std::cout << (a->remove(303)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(43)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
std::cout << (a->remove(125)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*d=*d;
std::cout << (d->remove(126)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
std::cout << (a->remove(12)) << std::endl;
*e=*d;
a->printPretty();
a->printPretty();
std::cout << (a->insert(394)) << std::endl;
e->printPretty();
std::cout << (d->insert(356)) << std::endl;
std::cout << (e->insert(356)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
*e=*e;
*a=*a;
*b=*d;
std::cout << (c->remove(211)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
std::cout << (c->remove(17)) << std::endl;
std::cout << (c->insert(394)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
*a=*e;
b->printPretty();
*b=*e;
d->printPretty();
std::cout << (c->insert(409)) << std::endl;
std::cout << (a->insert(60)) << std::endl;
*c=*a;
std::cout << (b->remove(376)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
std::cout << (b->remove(327)) << std::endl;
*c=*b;
std::cout << (c->remove(356)) << std::endl;
std::cout << (c->remove(207)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
std::cout << (a->remove(293)) << std::endl;
a->printPretty();
std::cout << (d->remove(493)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
*d=*c;
*b=*b;
std::cout << (b->insert(369)) << std::endl;
std::cout << (c->insert(415)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
*b=*e;
*c=*b;
std::cout << (c->remove(355)) << std::endl;
*b=*b;
std::cout << (e->insert(312)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->insert(79)) << std::endl;
std::cout << (a->insert(79)) << std::endl;
c->printPretty();
std::cout << (a->remove(79)) << std::endl;
*a=*e;
std::cout << (a->insert(326)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
c->printPretty();
std::cout << (c->remove(413)) << std::endl;
*a=*e;
std::cout << (b->remove(413)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
c->printPretty();
std::cout << (a->remove(138)) << std::endl;
std::cout << (a->insert(20)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
std::cout << (e->remove(312)) << std::endl;
*d=*d;
*b=*a;
std::cout << (c->insert(337)) << std::endl;
*d=*e;
e->printPretty();
std::cout << (d->remove(413)) << std::endl;
std::cout << (c->insert(312)) << std::endl;
a->printPretty();
std::cout << (c->remove(303)) << std::endl;
std::cout << (e->remove(356)) << std::endl;
std::cout << (d->remove(417)) << std::endl;
a->printPretty();
std::cout << (c->remove(337)) << std::endl;
e->printPretty();
std::cout << (a->remove(172)) << std::endl;
std::cout << (e->remove(413)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (b->insert(107)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
b->printPretty();
e->printPretty();
e->printPretty();
std::cout << (b->insert(68)) << std::endl;
a->printPretty();
*e=*b;
c->printPretty();
std::cout << (e->remove(356)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
std::cout << (e->insert(20)) << std::endl;
c->printPretty();
std::cout << (c->insert(48)) << std::endl;
*b=*a;
*d=*d;
std::cout << (d->insert(356)) << std::endl;
std::cout << (e->insert(108)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
*a=*d;
*a=*d;
*e=*e;
std::cout << (a->insert(356)) << std::endl;
std::cout << (e->remove(312)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
d->printPretty();
d->printPretty();
c->printPretty();
std::cout << (d->insert(356)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
std::cout << (e->remove(20)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
e->printPretty();
std::cout << (e->remove(107)) << std::endl;
*b=*c;
std::cout << (a->insert(356)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
*d=*b;
*b=*e;
d->printPretty();
*c=*e;
a->printPretty();
e->printPretty();
b->printPretty();
std::cout << (d->insert(240)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (b->insert(277)) << std::endl;
c->printPretty();
*a=*b;
*a=*b;
std::cout << (e->remove(108)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
c->printPretty();
std::cout << (b->insert(277)) << std::endl;
*b=*b;
*d=*c;
std::cout << (d->insert(108)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
a->printPretty();
std::cout << (c->insert(108)) << std::endl;
a->printPretty();
*c=*d;
e->printPretty();
std::cout << (c->remove(108)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
std::cout << (a->insert(123)) << std::endl;
*e=*b;
std::cout << (d->remove(355)) << std::endl;
std::cout << (b->remove(287)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
d->printPretty();
std::cout << (c->insert(459)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
*e=*b;
std::cout << (c->remove(243)) << std::endl;
std::cout << (c->remove(288)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
std::cout << (a->remove(33)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (b->remove(277)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (c->remove(459)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (b->insert(312)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
std::cout << (b->remove(314)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
*b=*d;
std::cout << (a->remove(68)) << std::endl;
std::cout << (a->insert(123)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
std::cout << (d->insert(68)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
b->printPretty();
std::cout << (d->insert(80)) << std::endl;
a->printPretty();
std::cout << (a->remove(17)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
*e=*b;
std::cout << (e->insert(164)) << std::endl;
d->printPretty();
std::cout << (d->insert(392)) << std::endl;
std::cout << (d->remove(108)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->remove(150)) << std::endl;
std::cout << (a->remove(123)) << std::endl;
std::cout << (e->remove(133)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
*e=*c;
std::cout << (d->remove(68)) << std::endl;
a->printPretty();
std::cout << (e->insert(311)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
std::cout << (e->insert(191)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
*e=*c;
std::cout << (b->insert(392)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
std::cout << (d->insert(80)) << std::endl;
std::cout << (d->remove(352)) << std::endl;
std::cout << (d->remove(212)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
c->printPretty();
std::cout << (e->remove(41)) << std::endl;
std::cout << (b->remove(121)) << std::endl;
*c=*e;
*c=*c;
std::cout << (e->remove(404)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
c->printPretty();
std::cout << (b->remove(32)) << std::endl;
*a=*c;
std::cout << (a->insert(95)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (c->remove(108)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
d->printPretty();
std::cout << (b->remove(312)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
return 0;
}
