#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (c->insert(151)) << std::endl;
*b=*a;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
d->printPretty();
*c=*a;
b->printPretty();
*b=*d;
std::cout << (c->insert(388)) << std::endl;
*b=*c;
std::cout << (c->insert(388)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
*c=*a;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
d->printPretty();
e->printPretty();
std::cout << (d->insert(285)) << std::endl;
b->printPretty();
std::cout << (e->remove(388)) << std::endl;
e->printPretty();
std::cout << (b->remove(388)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (b->remove(144)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
std::cout << (b->insert(272)) << std::endl;
std::cout << (e->remove(435)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (a->insert(163)) << std::endl;
*a=*d;
std::cout << (d->remove(108)) << std::endl;
*d=*e;
std::cout << (e->insert(125)) << std::endl;
*b=*d;
std::cout << (e->remove(125)) << std::endl;
*a=*c;
*b=*d;
std::cout << (b->insert(125)) << std::endl;
*a=*d;
std::cout << (d->insert(319)) << std::endl;
std::cout << (c->remove(272)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (d->insert(319)) << std::endl;
*a=*d;
std::cout << (e->insert(413)) << std::endl;
std::cout << (e->insert(415)) << std::endl;
std::cout << (d->remove(455)) << std::endl;
*c=*e;
std::cout << (c->insert(282)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
std::cout << (c->remove(282)) << std::endl;
b->printPretty();
std::cout << (c->insert(415)) << std::endl;
std::cout << (b->remove(52)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
*d=*d;
std::cout << (a->insert(213)) << std::endl;
*e=*a;
std::cout << (e->insert(127)) << std::endl;
std::cout << (a->remove(213)) << std::endl;
*c=*a;
std::cout << (a->insert(125)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->remove(455)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
*e=*a;
std::cout << (b->remove(305)) << std::endl;
std::cout << (a->insert(138)) << std::endl;
std::cout << (a->insert(453)) << std::endl;
d->printPretty();
std::cout << (d->remove(191)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (a->insert(171)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (b->remove(414)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
std::cout << (a->remove(136)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
*b=*b;
std::cout << (a->insert(125)) << std::endl;
std::cout << (e->remove(125)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(189)) << std::endl;
std::cout << (b->insert(232)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (c->remove(210)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (a->remove(138)) << std::endl;
std::cout << (c->remove(319)) << std::endl;
std::cout << (c->remove(455)) << std::endl;
std::cout << (e->remove(170)) << std::endl;
std::cout << (e->insert(140)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
b->printPretty();
std::cout << (a->remove(319)) << std::endl;
std::cout << (b->remove(125)) << std::endl;
std::cout << (e->remove(319)) << std::endl;
*d=*a;
std::cout << (d->insert(171)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (b->insert(350)) << std::endl;
*d=*b;
std::cout << (a->remove(444)) << std::endl;
std::cout << (e->insert(140)) << std::endl;
std::cout << (e->remove(281)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
std::cout << (b->remove(350)) << std::endl;
b->printPretty();
*d=*b;
*d=*b;
std::cout << (c->insert(307)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (a->insert(240)) << std::endl;
*c=*b;
std::cout << (a->remove(366)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->insert(133)) << std::endl;
std::cout << (a->remove(307)) << std::endl;
b->printPretty();
e->printPretty();
b->printPretty();
a->printPretty();
std::cout << (a->remove(240)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
*e=*d;
std::cout << (e->insert(312)) << std::endl;
a->printPretty();
*a=*b;
*d=*a;
a->printPretty();
std::cout << (d->remove(232)) << std::endl;
*c=*c;
std::cout << (e->insert(338)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (a->remove(125)) << std::endl;
std::cout << (a->insert(496)) << std::endl;
std::cout << (a->remove(496)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
*c=*c;
*d=*b;
std::cout << (e->remove(312)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
*c=*e;
c->printPretty();
*d=*e;
c->printPretty();
std::cout << (d->insert(75)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
std::cout << (d->insert(256)) << std::endl;
std::cout << (b->insert(296)) << std::endl;
std::cout << (c->remove(232)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
std::cout << (a->remove(389)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
e->printPretty();
a->printPretty();
*b=*b;
e->printPretty();
e->printPretty();
std::cout << (a->insert(232)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
a->printPretty();
std::cout << (b->remove(258)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
b->printPretty();
std::cout << (d->insert(75)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
c->printPretty();
d->printPretty();
a->printPretty();
*a=*e;
std::cout << (e->insert(232)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
*b=*e;
std::cout << (b->insert(232)) << std::endl;
*b=*e;
std::cout << (a->insert(232)) << std::endl;
b->printPretty();
std::cout << (e->insert(108)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
std::cout << (b->insert(282)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
std::cout << (a->insert(337)) << std::endl;
e->printPretty();
std::cout << (d->insert(256)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
*b=*e;
*e=*b;
std::cout << (a->insert(283)) << std::endl;
std::cout << (e->insert(163)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (b->remove(91)) << std::endl;
std::cout << (a->remove(337)) << std::endl;
c->printPretty();
std::cout << (a->remove(99)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
std::cout << (c->remove(341)) << std::endl;
std::cout << (d->insert(303)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
std::cout << (e->insert(158)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
std::cout << (e->remove(158)) << std::endl;
std::cout << (c->remove(214)) << std::endl;
std::cout << (e->remove(108)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (a->remove(283)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (a->insert(190)) << std::endl;
e->printPretty();
std::cout << (e->insert(232)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
e->printPretty();
std::cout << (a->remove(262)) << std::endl;
*d=*a;
std::cout << (d->insert(315)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (d->remove(428)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
std::cout << (d->insert(315)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
*d=*e;
std::cout << (a->remove(422)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (d->remove(458)) << std::endl;
e->printPretty();
b->printPretty();
*c=*e;
*e=*c;
std::cout << (e->remove(467)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
d->printPretty();
std::cout << (c->insert(141)) << std::endl;
std::cout << (b->insert(232)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (a->remove(114)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
std::cout << (a->insert(472)) << std::endl;
std::cout << (e->remove(240)) << std::endl;
*a=*e;
std::cout << (e->insert(372)) << std::endl;
*b=*c;
c->printPretty();
*d=*d;
*e=*a;
c->printPretty();
std::cout << (a->remove(1)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
std::cout << (a->remove(92)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
*c=*e;
std::cout << (b->insert(105)) << std::endl;
*b=*c;
b->printPretty();
std::cout << (c->insert(204)) << std::endl;
*b=*a;
std::cout << (b->remove(318)) << std::endl;
std::cout << (a->remove(310)) << std::endl;
std::cout << (b->remove(171)) << std::endl;
std::cout << (e->insert(229)) << std::endl;
*d=*a;
std::cout << (e->remove(190)) << std::endl;
std::cout << (c->insert(204)) << std::endl;
*e=*b;
std::cout << (c->remove(204)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (d->insert(367)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->remove(130)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
std::cout << (e->insert(381)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
e->printPretty();
std::cout << (d->insert(367)) << std::endl;
a->printPretty();
d->printPretty();
c->printPretty();
std::cout << (b->insert(19)) << std::endl;
a->printPretty();
std::cout << (b->insert(418)) << std::endl;
std::cout << (c->remove(8)) << std::endl;
std::cout << (a->remove(226)) << std::endl;
std::cout << (d->insert(498)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
*a=*d;
std::cout << (b->insert(418)) << std::endl;
std::cout << (c->remove(115)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (e->insert(381)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
b->printPretty();
std::cout << (b->insert(126)) << std::endl;
std::cout << (e->insert(381)) << std::endl;
b->printPretty();
std::cout << (e->remove(381)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
a->printPretty();
*e=*a;
std::cout << (b->insert(126)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
*d=*c;
std::cout << (d->remove(258)) << std::endl;
std::cout << (e->remove(367)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (d->remove(61)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
std::cout << (b->remove(186)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (c->remove(65)) << std::endl;
std::cout << (d->remove(418)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
std::cout << (e->remove(187)) << std::endl;
e->printPretty();
std::cout << (a->insert(367)) << std::endl;
std::cout << (e->insert(173)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (b->remove(236)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
d->printPretty();
std::cout << (b->remove(52)) << std::endl;
std::cout << (a->insert(377)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (a->insert(377)) << std::endl;
*b=*d;
*b=*b;
std::cout << (a->remove(377)) << std::endl;
*e=*e;
std::cout << (e->insert(289)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
std::cout << (a->insert(438)) << std::endl;
std::cout << (c->insert(418)) << std::endl;
*e=*e;
std::cout << (c->remove(418)) << std::endl;
d->printPretty();
a->printPretty();
*a=*d;
std::cout << (a->insert(336)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
*c=*c;
a->printPretty();
*c=*b;
*c=*a;
std::cout << (a->remove(336)) << std::endl;
std::cout << (e->insert(67)) << std::endl;
*e=*e;
*b=*e;
d->printPretty();
std::cout << (b->insert(15)) << std::endl;
std::cout << (b->insert(299)) << std::endl;
*e=*d;
std::cout << (b->remove(104)) << std::endl;
std::cout << (d->insert(128)) << std::endl;
b->printPretty();
*b=*c;
c->printPretty();
std::cout << (c->insert(336)) << std::endl;
*b=*c;
std::cout << (a->insert(274)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
std::cout << (a->remove(274)) << std::endl;
std::cout << (b->remove(480)) << std::endl;
std::cout << (e->insert(324)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
std::cout << (e->remove(324)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (c->remove(70)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
a->printPretty();
std::cout << (a->insert(222)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(45)) << std::endl;
d->printPretty();
std::cout << (c->remove(336)) << std::endl;
c->printPretty();
*c=*d;
*b=*c;
std::cout << (d->insert(409)) << std::endl;
*e=*c;
std::cout << (a->insert(222)) << std::endl;
std::cout << (b->remove(458)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->insert(139)) << std::endl;
d->printPretty();
*a=*e;
std::cout << (a->remove(169)) << std::endl;
std::cout << (e->remove(298)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (c->remove(108)) << std::endl;
std::cout << (a->remove(140)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (e->remove(354)) << std::endl;
e->printPretty();
std::cout << (e->remove(45)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
*b=*d;
*c=*d;
std::cout << (c->insert(253)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (b->insert(253)) << std::endl;
std::cout << (a->remove(45)) << std::endl;
std::cout << (b->remove(321)) << std::endl;
d->printPretty();
std::cout << (c->remove(456)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
*e=*b;
std::cout << (a->remove(128)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (c->insert(303)) << std::endl;
c->printPretty();
std::cout << (e->insert(45)) << std::endl;
*c=*a;
std::cout << (b->remove(9)) << std::endl;
std::cout << (e->insert(483)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
c->printPretty();
std::cout << (d->insert(16)) << std::endl;
e->printPretty();
*d=*c;
e->printPretty();
std::cout << (b->insert(353)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
c->printPretty();
std::cout << (d->insert(229)) << std::endl;
std::cout << (e->remove(483)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
b->printPretty();
std::cout << (e->remove(45)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (a->insert(150)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
*c=*a;
std::cout << (b->insert(253)) << std::endl;
*b=*a;
std::cout << (a->insert(150)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
std::cout << (b->remove(384)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (e->remove(376)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (b->remove(499)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
std::cout << (b->insert(384)) << std::endl;
b->printPretty();
std::cout << (b->remove(189)) << std::endl;
std::cout << (b->remove(384)) << std::endl;
std::cout << (c->remove(23)) << std::endl;
d->printPretty();
std::cout << (b->remove(102)) << std::endl;
std::cout << (d->remove(27)) << std::endl;
std::cout << (a->insert(177)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (a->insert(55)) << std::endl;
b->printPretty();
std::cout << (a->remove(55)) << std::endl;
*e=*a;
std::cout << (d->remove(163)) << std::endl;
*a=*c;
*e=*b;
*b=*e;
std::cout << (b->remove(150)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (c->insert(160)) << std::endl;
*a=*d;
std::cout << (e->insert(150)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
*e=*c;
a->printPretty();
e->printPretty();
e->printPretty();
std::cout << (e->remove(472)) << std::endl;
std::cout << (c->insert(160)) << std::endl;
*a=*e;
std::cout << (d->remove(294)) << std::endl;
b->printPretty();
std::cout << (b->remove(94)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
*b=*c;
std::cout << (b->remove(90)) << std::endl;
std::cout << (b->insert(472)) << std::endl;
std::cout << (b->remove(365)) << std::endl;
std::cout << (a->remove(83)) << std::endl;
c->printPretty();
std::cout << (b->remove(148)) << std::endl;
std::cout << (b->remove(486)) << std::endl;
std::cout << (a->insert(148)) << std::endl;
std::cout << (b->remove(83)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
*b=*a;
a->printPretty();
d->printPretty();
std::cout << (b->remove(395)) << std::endl;
std::cout << (e->remove(121)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
*a=*d;
*e=*c;
std::cout << (e->remove(150)) << std::endl;
std::cout << (c->remove(160)) << std::endl;
*d=*d;
std::cout << (e->insert(473)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (c->insert(241)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
d->printPretty();
std::cout << (b->insert(160)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
*b=*e;
std::cout << (b->remove(473)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
std::cout << (d->insert(244)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
b->printPretty();
std::cout << (b->insert(430)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (b->remove(484)) << std::endl;
std::cout << (a->insert(272)) << std::endl;
a->printPretty();
e->printPretty();
*e=*a;
std::cout << (c->remove(242)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
std::cout << (d->insert(464)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (a->insert(251)) << std::endl;
a->printPretty();
std::cout << (c->remove(241)) << std::endl;
std::cout << (a->insert(443)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->insert(151)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
std::cout << (d->insert(91)) << std::endl;
std::cout << (b->remove(225)) << std::endl;
b->printPretty();
std::cout << (e->remove(272)) << std::endl;
*a=*c;
std::cout << (c->insert(428)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->insert(217)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (c->insert(151)) << std::endl;
b->printPretty();
std::cout << (d->remove(91)) << std::endl;
*e=*d;
std::cout << (d->insert(464)) << std::endl;
*b=*a;
std::cout << (d->remove(464)) << std::endl;
std::cout << (d->insert(72)) << std::endl;
std::cout << (c->remove(147)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (e->remove(287)) << std::endl;
e->printPretty();
std::cout << (e->insert(259)) << std::endl;
b->printPretty();
std::cout << (e->insert(67)) << std::endl;
std::cout << (e->insert(259)) << std::endl;
std::cout << (b->insert(472)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
*c=*d;
std::cout << (c->insert(245)) << std::endl;
std::cout << (b->insert(168)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (e->remove(209)) << std::endl;
std::cout << (d->insert(72)) << std::endl;
std::cout << (b->remove(83)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
return 0;
}
