#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
b->printPretty();
std::cout << (b->remove(361)) << std::endl;
*b=*b;
std::cout << (a->remove(67)) << std::endl;
a->printPretty();
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*d=*a;
a->printPretty();
std::cout << (e->insert(372)) << std::endl;
b->printPretty();
std::cout << (e->remove(372)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
std::cout << (d->insert(107)) << std::endl;
*c=*a;
std::cout << (d->insert(107)) << std::endl;
a->printPretty();
std::cout << (d->insert(107)) << std::endl;
*b=*e;
c->printPretty();
*c=*a;
e->printPretty();
std::cout << (d->insert(345)) << std::endl;
c->printPretty();
std::cout << (e->remove(335)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (e->insert(219)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
*d=*c;
std::cout << (b->insert(404)) << std::endl;
std::cout << (b->remove(284)) << std::endl;
*d=*d;
std::cout << (d->insert(212)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
e->printPretty();
std::cout << (b->remove(131)) << std::endl;
e->printPretty();
std::cout << (c->insert(183)) << std::endl;
std::cout << (c->insert(183)) << std::endl;
a->printPretty();
std::cout << (a->insert(324)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
std::cout << (d->insert(212)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
std::cout << (d->remove(212)) << std::endl;
std::cout << (c->remove(446)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
a->printPretty();
std::cout << (a->remove(324)) << std::endl;
b->printPretty();
std::cout << (b->remove(177)) << std::endl;
*b=*e;
std::cout << (e->remove(274)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
d->printPretty();
*e=*a;
std::cout << (c->insert(76)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (d->remove(17)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
*e=*d;
std::cout << (c->remove(421)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
std::cout << (a->insert(52)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
*a=*c;
std::cout << (a->insert(183)) << std::endl;
e->printPretty();
std::cout << (a->remove(183)) << std::endl;
*a=*c;
std::cout << (d->insert(364)) << std::endl;
std::cout << (a->insert(183)) << std::endl;
std::cout << (c->remove(183)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
std::cout << (a->remove(183)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
*a=*d;
std::cout << (c->remove(152)) << std::endl;
e->printPretty();
e->printPretty();
*c=*d;
std::cout << (d->remove(140)) << std::endl;
*a=*b;
*a=*a;
*a=*a;
std::cout << (a->remove(219)) << std::endl;
std::cout << (e->remove(186)) << std::endl;
std::cout << (c->insert(467)) << std::endl;
std::cout << (a->insert(111)) << std::endl;
std::cout << (e->remove(336)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
*d=*a;
*a=*a;
std::cout << (b->remove(473)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
*c=*a;
*c=*c;
std::cout << (e->remove(123)) << std::endl;
std::cout << (e->remove(449)) << std::endl;
std::cout << (e->remove(55)) << std::endl;
std::cout << (b->insert(326)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
c->printPretty();
e->printPretty();
b->printPretty();
a->printPretty();
std::cout << (d->insert(332)) << std::endl;
*e=*c;
a->printPretty();
d->printPretty();
std::cout << (c->insert(332)) << std::endl;
std::cout << (a->insert(407)) << std::endl;
std::cout << (c->remove(121)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
std::cout << (d->remove(46)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
*c=*c;
*c=*b;
*c=*e;
e->printPretty();
std::cout << (e->insert(332)) << std::endl;
std::cout << (c->insert(405)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
*a=*d;
std::cout << (c->insert(299)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
*d=*b;
std::cout << (c->insert(170)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (d->remove(336)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
std::cout << (d->insert(430)) << std::endl;
e->printPretty();
std::cout << (a->insert(353)) << std::endl;
std::cout << (a->insert(484)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
d->printPretty();
std::cout << (e->insert(115)) << std::endl;
*a=*c;
std::cout << (b->insert(219)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
*c=*d;
std::cout << (e->remove(143)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
*c=*a;
std::cout << (d->insert(402)) << std::endl;
b->printPretty();
std::cout << (b->insert(332)) << std::endl;
a->printPretty();
std::cout << (b->insert(219)) << std::endl;
b->printPretty();
std::cout << (b->insert(288)) << std::endl;
*c=*d;
std::cout << (d->insert(31)) << std::endl;
*a=*b;
std::cout << (d->remove(410)) << std::endl;
std::cout << (c->remove(104)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
std::cout << (e->remove(221)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (b->insert(188)) << std::endl;
*d=*e;
*c=*b;
std::cout << (c->insert(339)) << std::endl;
std::cout << (b->remove(74)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (d->insert(393)) << std::endl;
std::cout << (b->remove(42)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (b->remove(55)) << std::endl;
*a=*b;
std::cout << (b->remove(92)) << std::endl;
*b=*b;
std::cout << (d->insert(48)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
b->printPretty();
std::cout << (e->remove(288)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (b->remove(188)) << std::endl;
std::cout << (e->remove(326)) << std::endl;
std::cout << (d->insert(153)) << std::endl;
*c=*e;
std::cout << (e->insert(393)) << std::endl;
std::cout << (b->remove(288)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
*a=*c;
std::cout << (c->insert(332)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
e->printPretty();
std::cout << (c->insert(277)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (e->insert(393)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (d->insert(393)) << std::endl;
a->printPretty();
std::cout << (c->remove(219)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (d->insert(153)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
*d=*e;
*e=*e;
std::cout << (e->remove(219)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (b->insert(5)) << std::endl;
std::cout << (b->insert(487)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (c->insert(290)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (d->insert(455)) << std::endl;
*c=*a;
std::cout << (a->remove(269)) << std::endl;
std::cout << (d->remove(318)) << std::endl;
a->printPretty();
std::cout << (b->insert(393)) << std::endl;
c->printPretty();
std::cout << (a->remove(219)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (e->insert(393)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
d->printPretty();
std::cout << (b->insert(87)) << std::endl;
*e=*d;
std::cout << (e->insert(459)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
std::cout << (b->insert(261)) << std::endl;
std::cout << (d->remove(393)) << std::endl;
*a=*d;
*a=*e;
std::cout << (b->remove(487)) << std::endl;
d->printPretty();
std::cout << (c->remove(112)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->remove(167)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
*e=*b;
std::cout << (e->insert(178)) << std::endl;
std::cout << (a->remove(455)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (c->remove(101)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
*d=*b;
std::cout << (b->remove(441)) << std::endl;
d->printPretty();
std::cout << (e->remove(110)) << std::endl;
std::cout << (b->insert(87)) << std::endl;
b->printPretty();
std::cout << (d->insert(24)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (e->remove(393)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
std::cout << (b->insert(5)) << std::endl;
b->printPretty();
std::cout << (b->remove(163)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
b->printPretty();
*d=*e;
*b=*d;
std::cout << (b->insert(178)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
a->printPretty();
a->printPretty();
c->printPretty();
a->printPretty();
*a=*b;
d->printPretty();
std::cout << (d->insert(78)) << std::endl;
std::cout << (b->remove(377)) << std::endl;
std::cout << (b->remove(219)) << std::endl;
c->printPretty();
std::cout << (c->remove(438)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
std::cout << (c->remove(391)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
std::cout << (b->insert(261)) << std::endl;
e->printPretty();
*e=*c;
std::cout << (d->insert(133)) << std::endl;
*a=*a;
std::cout << (b->remove(261)) << std::endl;
std::cout << (c->insert(49)) << std::endl;
e->printPretty();
std::cout << (a->remove(306)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
std::cout << (b->remove(178)) << std::endl;
*b=*b;
std::cout << (b->remove(87)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (a->insert(5)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
std::cout << (b->insert(191)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (e->insert(312)) << std::endl;
*b=*b;
std::cout << (d->insert(361)) << std::endl;
std::cout << (e->remove(30)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (a->insert(5)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
*c=*a;
std::cout << (b->remove(68)) << std::endl;
*a=*e;
std::cout << (b->insert(348)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
std::cout << (c->remove(186)) << std::endl;
c->printPretty();
std::cout << (a->remove(219)) << std::endl;
std::cout << (b->insert(202)) << std::endl;
std::cout << (a->remove(140)) << std::endl;
std::cout << (d->insert(393)) << std::endl;
std::cout << (b->remove(5)) << std::endl;
*d=*b;
std::cout << (a->remove(416)) << std::endl;
std::cout << (c->remove(87)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
*a=*e;
std::cout << (e->remove(80)) << std::endl;
b->printPretty();
std::cout << (c->insert(399)) << std::endl;
std::cout << (a->insert(20)) << std::endl;
*d=*a;
std::cout << (e->remove(63)) << std::endl;
d->printPretty();
std::cout << (d->insert(245)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
c->printPretty();
std::cout << (b->remove(348)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
std::cout << (c->insert(296)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
std::cout << (b->insert(387)) << std::endl;
std::cout << (b->remove(358)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (d->insert(171)) << std::endl;
a->printPretty();
std::cout << (d->remove(171)) << std::endl;
c->printPretty();
*b=*e;
d->printPretty();
std::cout << (e->insert(312)) << std::endl;
*a=*c;
std::cout << (d->insert(401)) << std::endl;
std::cout << (e->insert(100)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
b->printPretty();
std::cout << (e->remove(193)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (d->insert(103)) << std::endl;
*e=*a;
*e=*e;
d->printPretty();
a->printPretty();
*a=*b;
std::cout << (c->insert(192)) << std::endl;
*a=*d;
std::cout << (a->insert(384)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (c->insert(332)) << std::endl;
std::cout << (a->remove(384)) << std::endl;
*b=*a;
std::cout << (a->insert(422)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (c->insert(68)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
std::cout << (d->insert(393)) << std::endl;
*c=*a;
std::cout << (d->remove(103)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (b->remove(64)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
*b=*c;
e->printPretty();
std::cout << (b->insert(476)) << std::endl;
*e=*c;
std::cout << (e->insert(466)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
a->printPretty();
std::cout << (c->remove(49)) << std::endl;
*d=*d;
*d=*d;
d->printPretty();
std::cout << (e->remove(466)) << std::endl;
a->printPretty();
std::cout << (c->remove(211)) << std::endl;
*c=*d;
std::cout << (a->remove(312)) << std::endl;
*a=*e;
std::cout << (e->insert(263)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
std::cout << (a->insert(219)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (c->insert(263)) << std::endl;
std::cout << (e->insert(162)) << std::endl;
std::cout << (b->insert(401)) << std::endl;
*e=*c;
std::cout << (c->remove(263)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
std::cout << (a->insert(345)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
b->printPretty();
std::cout << (b->insert(470)) << std::endl;
std::cout << (e->remove(94)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
*a=*e;
*b=*b;
c->printPretty();
std::cout << (a->remove(404)) << std::endl;
std::cout << (b->insert(220)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (d->insert(130)) << std::endl;
*a=*a;
*e=*c;
std::cout << (c->insert(20)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (a->remove(263)) << std::endl;
std::cout << (a->remove(20)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
*e=*b;
std::cout << (c->remove(20)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(404)) << std::endl;
e->printPretty();
std::cout << (d->insert(130)) << std::endl;
std::cout << (b->insert(263)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (d->remove(65)) << std::endl;
*c=*b;
e->printPretty();
e->printPretty();
std::cout << (d->remove(22)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
std::cout << (e->remove(208)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (c->insert(206)) << std::endl;
std::cout << (b->remove(286)) << std::endl;
std::cout << (c->remove(401)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
std::cout << (d->remove(282)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (d->insert(219)) << std::endl;
std::cout << (c->insert(103)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (b->remove(267)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (e->insert(403)) << std::endl;
std::cout << (e->remove(160)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (b->insert(470)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
*e=*c;
a->printPretty();
*d=*e;
std::cout << (b->insert(219)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
std::cout << (d->insert(219)) << std::endl;
std::cout << (e->insert(421)) << std::endl;
*a=*d;
a->printPretty();
std::cout << (e->remove(273)) << std::endl;
*d=*c;
std::cout << (a->remove(294)) << std::endl;
std::cout << (e->remove(489)) << std::endl;
std::cout << (c->insert(387)) << std::endl;
d->printPretty();
std::cout << (e->remove(48)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
*e=*b;
*b=*b;
std::cout << (b->remove(220)) << std::endl;
*c=*d;
*d=*d;
b->printPretty();
std::cout << (b->insert(331)) << std::endl;
*e=*b;
std::cout << (d->remove(263)) << std::endl;
*e=*e;
std::cout << (b->insert(206)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
c->printPretty();
std::cout << (d->insert(422)) << std::endl;
std::cout << (b->remove(247)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (d->remove(269)) << std::endl;
std::cout << (a->insert(72)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
a->printPretty();
std::cout << (d->insert(206)) << std::endl;
std::cout << (c->insert(103)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
std::cout << (e->insert(331)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
std::cout << (d->remove(20)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
*b=*b;
*d=*a;
*e=*e;
std::cout << (c->insert(413)) << std::endl;
std::cout << (d->insert(18)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
std::cout << (a->insert(311)) << std::endl;
e->printPretty();
*d=*b;
*c=*e;
std::cout << (b->remove(422)) << std::endl;
std::cout << (d->remove(20)) << std::endl;
a->printPretty();
std::cout << (e->remove(103)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
std::cout << (e->insert(360)) << std::endl;
std::cout << (d->remove(393)) << std::endl;
std::cout << (e->remove(393)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
std::cout << (b->remove(366)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (a->insert(53)) << std::endl;
*b=*b;
*c=*c;
e->printPretty();
b->printPretty();
std::cout << (b->insert(91)) << std::endl;
*e=*c;
b->printPretty();
*d=*d;
b->printPretty();
std::cout << (e->remove(263)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
*e=*a;
*a=*c;
std::cout << (e->remove(219)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
c->printPretty();
std::cout << (d->remove(422)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (e->insert(46)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
std::cout << (d->remove(71)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
c->printPretty();
std::cout << (c->remove(476)) << std::endl;
std::cout << (c->remove(219)) << std::endl;
d->printPretty();
std::cout << (c->remove(429)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
*b=*d;
std::cout << (b->insert(225)) << std::endl;
std::cout << (e->insert(210)) << std::endl;
*b=*d;
*e=*c;
a->printPretty();
std::cout << (c->remove(16)) << std::endl;
*a=*b;
*c=*c;
std::cout << (c->insert(493)) << std::endl;
std::cout << (b->insert(470)) << std::endl;
std::cout << (a->remove(276)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (d->remove(282)) << std::endl;
*d=*e;
std::cout << (d->remove(442)) << std::endl;
std::cout << (c->insert(307)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
b->printPretty();
*d=*e;
std::cout << (d->insert(206)) << std::endl;
*c=*c;
std::cout << (e->remove(401)) << std::endl;
*b=*c;
std::cout << (e->remove(20)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (a->remove(20)) << std::endl;
std::cout << (a->insert(105)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
*d=*c;
std::cout << (e->remove(393)) << std::endl;
std::cout << (a->insert(343)) << std::endl;
std::cout << (e->remove(139)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
b->printPretty();
std::cout << (c->remove(105)) << std::endl;
std::cout << (c->remove(343)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (e->remove(48)) << std::endl;
std::cout << (e->insert(263)) << std::endl;
*a=*a;
std::cout << (d->remove(100)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
std::cout << (d->insert(493)) << std::endl;
*d=*b;
std::cout << (e->remove(331)) << std::endl;
std::cout << (b->remove(230)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
std::cout << (b->insert(24)) << std::endl;
std::cout << (d->insert(51)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
*d=*c;
a->printPretty();
*d=*c;
b->printPretty();
b->printPretty();
e->printPretty();
b->printPretty();
*e=*e;
*b=*c;
std::cout << (c->remove(142)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
a->printPretty();
std::cout << (b->insert(206)) << std::endl;
a->printPretty();
std::cout << (d->insert(265)) << std::endl;
e->printPretty();
std::cout << (e->remove(389)) << std::endl;
std::cout << (b->remove(20)) << std::endl;
*a=*e;
std::cout << (b->remove(200)) << std::endl;
std::cout << (a->insert(206)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
*d=*c;
d->printPretty();
*a=*d;
return 0;
}
