#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(218)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
*a=*a;
a->printPretty();
*b=*a;
std::cout << (a->remove(341)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->insert(85)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
b->printPretty();
std::cout << (a->remove(85)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*c=*c;
b->printPretty();
std::cout << (b->insert(281)) << std::endl;
*c=*c;
std::cout << (c->insert(278)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
b->printPretty();
std::cout << (c->remove(7)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (e->insert(42)) << std::endl;
*b=*b;
std::cout << (e->remove(343)) << std::endl;
std::cout << (b->remove(281)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
e->printPretty();
std::cout << (b->remove(209)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
std::cout << (e->insert(437)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (e->remove(62)) << std::endl;
*d=*a;
a->printPretty();
c->printPretty();
e->printPretty();
a->printPretty();
std::cout << (e->insert(26)) << std::endl;
b->printPretty();
std::cout << (b->remove(144)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
std::cout << (b->remove(64)) << std::endl;
std::cout << (e->insert(398)) << std::endl;
d->printPretty();
*b=*c;
*c=*d;
*e=*e;
e->printPretty();
*c=*d;
std::cout << (b->remove(205)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
*e=*d;
*d=*e;
std::cout << (c->insert(104)) << std::endl;
*c=*e;
*d=*c;
*d=*c;
std::cout << (a->remove(376)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->insert(74)) << std::endl;
b->printPretty();
*e=*d;
std::cout << (d->insert(452)) << std::endl;
c->printPretty();
std::cout << (e->remove(345)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (d->remove(498)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
std::cout << (b->remove(31)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (e->insert(141)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
*c=*c;
*c=*e;
b->printPretty();
std::cout << (b->remove(417)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
a->printPretty();
std::cout << (c->insert(500)) << std::endl;
std::cout << (d->remove(320)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
e->printPretty();
std::cout << (e->remove(79)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
b->printPretty();
std::cout << (e->insert(36)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (a->insert(453)) << std::endl;
std::cout << (d->remove(296)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (e->remove(147)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
*c=*c;
*c=*a;
std::cout << (e->remove(141)) << std::endl;
std::cout << (e->insert(380)) << std::endl;
std::cout << (b->remove(284)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (c->remove(35)) << std::endl;
c->printPretty();
e->printPretty();
c->printPretty();
std::cout << (b->insert(265)) << std::endl;
e->printPretty();
std::cout << (a->insert(36)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (e->insert(266)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
b->printPretty();
std::cout << (e->insert(280)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
*a=*b;
std::cout << (a->insert(91)) << std::endl;
*d=*b;
std::cout << (a->insert(383)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (e->remove(329)) << std::endl;
*e=*b;
std::cout << (c->remove(139)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
e->printPretty();
*c=*a;
*c=*d;
std::cout << (a->insert(265)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
*d=*b;
std::cout << (b->remove(265)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
a->printPretty();
std::cout << (a->remove(439)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
c->printPretty();
std::cout << (b->insert(204)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
d->printPretty();
std::cout << (c->remove(64)) << std::endl;
c->printPretty();
std::cout << (b->insert(204)) << std::endl;
*d=*d;
std::cout << (d->insert(256)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
*a=*c;
std::cout << (e->insert(322)) << std::endl;
std::cout << (e->remove(322)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (e->insert(335)) << std::endl;
*e=*e;
*a=*a;
std::cout << (d->insert(265)) << std::endl;
b->printPretty();
*a=*d;
*b=*e;
std::cout << (a->remove(277)) << std::endl;
c->printPretty();
std::cout << (a->insert(215)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (e->remove(265)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (c->insert(265)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
*a=*c;
*e=*d;
*d=*e;
std::cout << (b->remove(62)) << std::endl;
std::cout << (e->remove(265)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
std::cout << (b->insert(335)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
std::cout << (b->remove(43)) << std::endl;
std::cout << (c->remove(77)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (a->remove(265)) << std::endl;
std::cout << (a->remove(370)) << std::endl;
std::cout << (c->insert(130)) << std::endl;
*d=*d;
std::cout << (d->insert(370)) << std::endl;
*b=*a;
d->printPretty();
*d=*d;
*a=*c;
std::cout << (b->insert(469)) << std::endl;
std::cout << (b->remove(5)) << std::endl;
*d=*e;
*a=*e;
*a=*e;
std::cout << (e->insert(211)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
a->printPretty();
std::cout << (a->insert(297)) << std::endl;
b->printPretty();
*c=*b;
*a=*d;
std::cout << (d->insert(23)) << std::endl;
std::cout << (c->insert(469)) << std::endl;
*c=*a;
std::cout << (d->insert(19)) << std::endl;
*c=*c;
std::cout << (d->remove(395)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
*c=*e;
std::cout << (b->remove(469)) << std::endl;
std::cout << (a->insert(157)) << std::endl;
*b=*b;
std::cout << (c->remove(211)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
*b=*c;
*e=*d;
e->printPretty();
std::cout << (d->insert(451)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
*d=*d;
*e=*c;
*b=*d;
std::cout << (a->insert(157)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
e->printPretty();
e->printPretty();
d->printPretty();
std::cout << (c->remove(106)) << std::endl;
d->printPretty();
*d=*b;
d->printPretty();
std::cout << (c->insert(310)) << std::endl;
std::cout << (d->remove(451)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
*c=*d;
*e=*e;
b->printPretty();
b->printPretty();
std::cout << (e->insert(476)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
std::cout << (a->insert(233)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
b->printPretty();
std::cout << (c->insert(23)) << std::endl;
std::cout << (d->insert(410)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
std::cout << (b->insert(451)) << std::endl;
std::cout << (d->remove(23)) << std::endl;
*c=*b;
std::cout << (e->insert(64)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
b->printPretty();
std::cout << (e->insert(64)) << std::endl;
std::cout << (e->insert(64)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->remove(38)) << std::endl;
std::cout << (b->insert(26)) << std::endl;
*b=*c;
std::cout << (e->insert(476)) << std::endl;
std::cout << (a->remove(328)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
*a=*a;
std::cout << (c->insert(23)) << std::endl;
std::cout << (b->insert(389)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
*a=*e;
std::cout << (b->insert(389)) << std::endl;
std::cout << (a->insert(64)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (a->remove(356)) << std::endl;
d->printPretty();
std::cout << (e->remove(113)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (a->remove(64)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (e->remove(205)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
d->printPretty();
std::cout << (c->remove(451)) << std::endl;
*c=*e;
std::cout << (e->remove(302)) << std::endl;
std::cout << (a->insert(275)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
c->printPretty();
std::cout << (b->remove(405)) << std::endl;
std::cout << (a->insert(275)) << std::endl;
std::cout << (a->remove(123)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (a->insert(235)) << std::endl;
std::cout << (a->insert(275)) << std::endl;
std::cout << (e->remove(41)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
*e=*a;
std::cout << (a->remove(144)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
std::cout << (c->remove(158)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
std::cout << (a->insert(275)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
*a=*d;
std::cout << (c->remove(217)) << std::endl;
std::cout << (e->remove(490)) << std::endl;
std::cout << (b->remove(59)) << std::endl;
*c=*d;
std::cout << (a->insert(148)) << std::endl;
*e=*a;
*d=*a;
std::cout << (c->remove(373)) << std::endl;
a->printPretty();
*c=*a;
std::cout << (c->remove(261)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
b->printPretty();
std::cout << (d->insert(35)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
e->printPretty();
std::cout << (c->remove(159)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
std::cout << (e->remove(479)) << std::endl;
*b=*d;
std::cout << (b->remove(35)) << std::endl;
c->printPretty();
std::cout << (a->insert(253)) << std::endl;
c->printPretty();
std::cout << (d->remove(103)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
std::cout << (a->insert(348)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
std::cout << (b->insert(220)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (d->insert(79)) << std::endl;
e->printPretty();
std::cout << (e->insert(396)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (c->insert(181)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
e->printPretty();
std::cout << (b->remove(364)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
std::cout << (a->insert(429)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (d->remove(79)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
*c=*e;
std::cout << (b->remove(441)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
std::cout << (a->insert(137)) << std::endl;
std::cout << (b->remove(148)) << std::endl;
std::cout << (d->remove(429)) << std::endl;
d->printPretty();
std::cout << (a->insert(419)) << std::endl;
*b=*e;
*b=*e;
*b=*c;
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->remove(201)) << std::endl;
c->printPretty();
std::cout << (c->insert(396)) << std::endl;
c->printPretty();
std::cout << (d->remove(148)) << std::endl;
*c=*a;
std::cout << (e->insert(95)) << std::endl;
b->printPretty();
std::cout << (c->remove(143)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (a->remove(418)) << std::endl;
std::cout << (e->remove(58)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (e->insert(64)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
std::cout << (e->remove(396)) << std::endl;
b->printPretty();
std::cout << (c->insert(358)) << std::endl;
*e=*c;
std::cout << (c->insert(73)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (a->remove(351)) << std::endl;
std::cout << (b->remove(148)) << std::endl;
d->printPretty();
*b=*e;
*e=*d;
e->printPretty();
std::cout << (d->remove(44)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
b->printPretty();
std::cout << (d->insert(109)) << std::endl;
a->printPretty();
std::cout << (b->insert(137)) << std::endl;
std::cout << (e->remove(374)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
*d=*e;
std::cout << (b->remove(450)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (e->insert(35)) << std::endl;
*a=*d;
std::cout << (a->remove(3)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
*d=*c;
std::cout << (b->insert(419)) << std::endl;
b->printPretty();
std::cout << (a->remove(172)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
std::cout << (d->insert(370)) << std::endl;
std::cout << (a->remove(35)) << std::endl;
std::cout << (b->remove(468)) << std::endl;
std::cout << (d->insert(276)) << std::endl;
std::cout << (e->insert(417)) << std::endl;
std::cout << (c->insert(75)) << std::endl;
*b=*b;
std::cout << (c->insert(350)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (c->remove(35)) << std::endl;
std::cout << (e->remove(326)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (e->insert(360)) << std::endl;
std::cout << (b->remove(221)) << std::endl;
*a=*a;
std::cout << (a->insert(331)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
std::cout << (d->remove(85)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
std::cout << (a->insert(122)) << std::endl;
*b=*a;
*b=*e;
*b=*c;
std::cout << (b->remove(238)) << std::endl;
std::cout << (e->remove(493)) << std::endl;
std::cout << (a->remove(174)) << std::endl;
std::cout << (c->insert(417)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (e->remove(225)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
a->printPretty();
std::cout << (e->remove(360)) << std::endl;
std::cout << (b->remove(417)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
std::cout << (d->remove(417)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
c->printPretty();
std::cout << (c->remove(442)) << std::endl;
c->printPretty();
c->printPretty();
d->printPretty();
b->printPretty();
*a=*e;
*c=*d;
*a=*a;
std::cout << (a->insert(220)) << std::endl;
e->printPretty();
std::cout << (b->insert(269)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (b->remove(220)) << std::endl;
std::cout << (d->remove(188)) << std::endl;
*a=*a;
std::cout << (b->remove(269)) << std::endl;
b->printPretty();
std::cout << (a->insert(245)) << std::endl;
*b=*e;
*b=*b;
e->printPretty();
std::cout << (a->remove(220)) << std::endl;
a->printPretty();
std::cout << (e->remove(326)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (d->insert(359)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
*b=*a;
std::cout << (e->remove(205)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
std::cout << (a->remove(475)) << std::endl;
c->printPretty();
std::cout << (c->remove(375)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
c->printPretty();
std::cout << (a->insert(47)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
std::cout << (c->remove(100)) << std::endl;
std::cout << (d->insert(116)) << std::endl;
c->printPretty();
std::cout << (e->remove(367)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (a->remove(35)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
std::cout << (d->insert(95)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (b->insert(353)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (b->insert(393)) << std::endl;
d->printPretty();
std::cout << (c->remove(125)) << std::endl;
*c=*d;
std::cout << (b->remove(393)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
std::cout << (c->remove(417)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
*e=*c;
*c=*c;
std::cout << (d->remove(366)) << std::endl;
std::cout << (b->insert(317)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (a->insert(210)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
std::cout << (b->remove(297)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
d->printPretty();
std::cout << (a->insert(477)) << std::endl;
std::cout << (c->remove(261)) << std::endl;
std::cout << (e->insert(191)) << std::endl;
*d=*a;
c->printPretty();
std::cout << (e->remove(237)) << std::endl;
*e=*a;
*a=*c;
b->printPretty();
std::cout << (c->insert(387)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
*e=*c;
std::cout << (a->insert(66)) << std::endl;
*b=*e;
std::cout << (a->insert(447)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (d->remove(393)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
*e=*c;
std::cout << (a->insert(107)) << std::endl;
std::cout << (b->insert(457)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
*e=*d;
std::cout << (d->insert(307)) << std::endl;
*a=*e;
std::cout << (c->insert(112)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
*c=*c;
*c=*a;
std::cout << (d->insert(227)) << std::endl;
std::cout << (d->insert(412)) << std::endl;
d->printPretty();
std::cout << (e->insert(235)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (d->insert(307)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
c->printPretty();
std::cout << (c->remove(475)) << std::endl;
*d=*c;
std::cout << (c->insert(31)) << std::endl;
std::cout << (e->insert(47)) << std::endl;
std::cout << (e->remove(47)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
b->printPretty();
std::cout << (a->remove(307)) << std::endl;
*e=*c;
std::cout << (c->remove(307)) << std::endl;
std::cout << (a->insert(485)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
d->printPretty();
std::cout << (b->insert(89)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
d->printPretty();
std::cout << (b->remove(201)) << std::endl;
d->printPretty();
b->printPretty();
*e=*e;
*e=*c;
a->printPretty();
std::cout << (a->remove(485)) << std::endl;
std::cout << (b->insert(112)) << std::endl;
*b=*b;
std::cout << (b->insert(283)) << std::endl;
std::cout << (c->remove(268)) << std::endl;
*b=*a;
std::cout << (c->insert(31)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
std::cout << (b->insert(210)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
std::cout << (c->remove(284)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
std::cout << (a->insert(147)) << std::endl;
std::cout << (a->remove(151)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (c->insert(31)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
std::cout << (e->insert(47)) << std::endl;
*e=*d;
std::cout << (a->insert(85)) << std::endl;
d->printPretty();
std::cout << (b->insert(47)) << std::endl;
*e=*c;
std::cout << (a->remove(85)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
*c=*a;
std::cout << (d->remove(47)) << std::endl;
std::cout << (d->remove(207)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
a->printPretty();
std::cout << (a->remove(210)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
*c=*a;
std::cout << (a->remove(112)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
a->printPretty();
std::cout << (c->insert(47)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
*e=*b;
std::cout << (b->insert(128)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
e->printPretty();
std::cout << (a->remove(277)) << std::endl;
std::cout << (e->remove(210)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
*e=*c;
std::cout << (d->insert(215)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
*d=*e;
*e=*e;
std::cout << (a->insert(403)) << std::endl;
*c=*b;
std::cout << (e->insert(47)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (c->remove(304)) << std::endl;
b->printPretty();
std::cout << (e->remove(326)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
std::cout << (b->insert(25)) << std::endl;
*a=*b;
std::cout << (c->insert(103)) << std::endl;
std::cout << (c->insert(170)) << std::endl;
std::cout << (b->remove(380)) << std::endl;
std::cout << (c->remove(210)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
*e=*a;
std::cout << (b->remove(25)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
*d=*b;
std::cout << (b->insert(210)) << std::endl;
return 0;
}
