#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
a->printPretty();
std::cout << (a->remove(367)) << std::endl;
b->printPretty();
std::cout << (a->remove(263)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (a->insert(94)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->insert(242)) << std::endl;
*b=*c;
d->printPretty();
a->printPretty();
e->printPretty();
e->printPretty();
std::cout << (a->remove(317)) << std::endl;
a->printPretty();
*e=*a;
*d=*a;
*c=*c;
*e=*c;
*b=*d;
d->printPretty();
e->printPretty();
*a=*a;
std::cout << (c->remove(236)) << std::endl;
std::cout << (d->remove(318)) << std::endl;
b->printPretty();
std::cout << (c->insert(218)) << std::endl;
*d=*b;
*d=*a;
std::cout << (e->remove(77)) << std::endl;
std::cout << (d->insert(432)) << std::endl;
*a=*d;
std::cout << (e->insert(362)) << std::endl;
*a=*d;
std::cout << (d->remove(432)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (a->insert(108)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
*a=*d;
std::cout << (a->remove(312)) << std::endl;
b->printPretty();
std::cout << (d->remove(65)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
*c=*c;
*b=*a;
*d=*a;
std::cout << (e->remove(362)) << std::endl;
std::cout << (a->remove(266)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
b->printPretty();
std::cout << (e->insert(157)) << std::endl;
e->printPretty();
std::cout << (d->remove(459)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (a->insert(380)) << std::endl;
c->printPretty();
a->printPretty();
*a=*e;
std::cout << (e->insert(69)) << std::endl;
*d=*e;
std::cout << (a->insert(157)) << std::endl;
a->printPretty();
std::cout << (a->remove(157)) << std::endl;
*c=*e;
std::cout << (b->remove(109)) << std::endl;
*d=*e;
b->printPretty();
*d=*d;
std::cout << (e->remove(69)) << std::endl;
std::cout << (e->remove(157)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
*e=*d;
std::cout << (e->remove(143)) << std::endl;
std::cout << (b->insert(78)) << std::endl;
std::cout << (e->insert(161)) << std::endl;
e->printPretty();
d->printPretty();
*a=*c;
std::cout << (e->remove(154)) << std::endl;
std::cout << (d->insert(28)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
std::cout << (e->insert(161)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
std::cout << (a->insert(157)) << std::endl;
d->printPretty();
std::cout << (e->insert(171)) << std::endl;
std::cout << (c->remove(474)) << std::endl;
a->printPretty();
std::cout << (c->insert(69)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
*d=*c;
std::cout << (a->remove(482)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
a->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(157)) << std::endl;
std::cout << (e->remove(157)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
e->printPretty();
std::cout << (e->insert(171)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
*c=*b;
std::cout << (a->insert(157)) << std::endl;
c->printPretty();
std::cout << (d->remove(341)) << std::endl;
std::cout << (a->insert(125)) << std::endl;
b->printPretty();
std::cout << (e->remove(8)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (b->remove(347)) << std::endl;
b->printPretty();
std::cout << (d->remove(300)) << std::endl;
std::cout << (b->remove(48)) << std::endl;
*a=*d;
*d=*a;
std::cout << (d->remove(157)) << std::endl;
*a=*e;
std::cout << (d->remove(489)) << std::endl;
std::cout << (d->remove(149)) << std::endl;
std::cout << (a->insert(396)) << std::endl;
d->printPretty();
std::cout << (e->insert(69)) << std::endl;
*d=*c;
std::cout << (c->insert(176)) << std::endl;
b->printPretty();
std::cout << (b->remove(450)) << std::endl;
d->printPretty();
std::cout << (a->insert(396)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->remove(272)) << std::endl;
*a=*a;
b->printPretty();
e->printPretty();
a->printPretty();
std::cout << (e->insert(248)) << std::endl;
c->printPretty();
std::cout << (b->remove(63)) << std::endl;
d->printPretty();
std::cout << (d->remove(78)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (b->remove(188)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
*d=*d;
d->printPretty();
std::cout << (e->insert(276)) << std::endl;
e->printPretty();
std::cout << (d->insert(140)) << std::endl;
std::cout << (c->insert(467)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
*d=*e;
std::cout << (c->insert(467)) << std::endl;
std::cout << (d->remove(171)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
*a=*b;
std::cout << (d->remove(236)) << std::endl;
std::cout << (a->remove(418)) << std::endl;
std::cout << (d->insert(205)) << std::endl;
*d=*d;
std::cout << (a->remove(182)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (e->insert(15)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
*b=*a;
d->printPretty();
*b=*d;
std::cout << (e->remove(99)) << std::endl;
*e=*c;
std::cout << (d->insert(248)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (b->remove(400)) << std::endl;
std::cout << (c->remove(175)) << std::endl;
std::cout << (d->remove(205)) << std::endl;
std::cout << (a->remove(341)) << std::endl;
std::cout << (e->insert(1)) << std::endl;
std::cout << (b->remove(209)) << std::endl;
a->printPretty();
std::cout << (c->remove(474)) << std::endl;
*a=*c;
std::cout << (a->insert(95)) << std::endl;
*d=*d;
*e=*a;
std::cout << (d->insert(34)) << std::endl;
c->printPretty();
std::cout << (e->insert(95)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
b->printPretty();
std::cout << (a->remove(95)) << std::endl;
std::cout << (d->insert(248)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
*b=*b;
std::cout << (a->insert(373)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (d->insert(276)) << std::endl;
*b=*c;
*b=*b;
std::cout << (a->remove(373)) << std::endl;
std::cout << (d->remove(276)) << std::endl;
*a=*b;
std::cout << (e->insert(95)) << std::endl;
std::cout << (d->insert(489)) << std::endl;
e->printPretty();
std::cout << (c->remove(51)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (e->insert(240)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->insert(240)) << std::endl;
std::cout << (b->remove(328)) << std::endl;
std::cout << (e->remove(358)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->remove(179)) << std::endl;
std::cout << (a->insert(16)) << std::endl;
a->printPretty();
std::cout << (a->insert(16)) << std::endl;
std::cout << (d->insert(449)) << std::endl;
std::cout << (d->insert(70)) << std::endl;
*c=*d;
std::cout << (d->remove(463)) << std::endl;
std::cout << (d->remove(449)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
*e=*c;
*b=*e;
std::cout << (b->insert(283)) << std::endl;
std::cout << (b->remove(468)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (d->insert(419)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
a->printPretty();
c->printPretty();
b->printPretty();
std::cout << (e->insert(69)) << std::endl;
a->printPretty();
std::cout << (a->remove(16)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
*e=*a;
std::cout << (b->remove(94)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (c->insert(248)) << std::endl;
e->printPretty();
std::cout << (e->insert(205)) << std::endl;
std::cout << (d->insert(199)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
std::cout << (b->remove(256)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (d->remove(119)) << std::endl;
*a=*a;
std::cout << (a->insert(422)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->insert(422)) << std::endl;
*a=*a;
std::cout << (d->remove(350)) << std::endl;
std::cout << (d->remove(34)) << std::endl;
*d=*a;
std::cout << (a->insert(235)) << std::endl;
std::cout << (d->remove(417)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
std::cout << (c->remove(34)) << std::endl;
d->printPretty();
std::cout << (d->remove(235)) << std::endl;
*b=*c;
*d=*a;
*b=*d;
*b=*c;
std::cout << (d->insert(427)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
a->printPretty();
std::cout << (a->insert(423)) << std::endl;
*c=*d;
std::cout << (c->remove(235)) << std::endl;
*b=*b;
std::cout << (e->remove(205)) << std::endl;
std::cout << (b->insert(457)) << std::endl;
*c=*d;
*c=*c;
std::cout << (b->remove(238)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
c->printPretty();
std::cout << (c->insert(7)) << std::endl;
*c=*c;
std::cout << (b->remove(69)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
c->printPretty();
std::cout << (a->insert(423)) << std::endl;
*e=*a;
std::cout << (e->insert(422)) << std::endl;
std::cout << (b->insert(50)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (a->remove(218)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (a->insert(247)) << std::endl;
*a=*d;
std::cout << (c->insert(422)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
*c=*a;
a->printPretty();
std::cout << (b->insert(449)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (a->insert(216)) << std::endl;
a->printPretty();
std::cout << (a->insert(472)) << std::endl;
std::cout << (e->remove(102)) << std::endl;
*e=*c;
std::cout << (d->insert(68)) << std::endl;
std::cout << (a->insert(391)) << std::endl;
d->printPretty();
std::cout << (c->insert(39)) << std::endl;
std::cout << (d->insert(382)) << std::endl;
*c=*a;
std::cout << (c->insert(196)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
*a=*a;
a->printPretty();
std::cout << (b->insert(385)) << std::endl;
*e=*c;
std::cout << (d->remove(474)) << std::endl;
*e=*c;
std::cout << (b->insert(248)) << std::endl;
std::cout << (c->insert(216)) << std::endl;
std::cout << (c->remove(394)) << std::endl;
*e=*e;
std::cout << (b->insert(269)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
*a=*b;
std::cout << (b->remove(249)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
e->printPretty();
std::cout << (b->insert(416)) << std::endl;
std::cout << (c->remove(391)) << std::endl;
std::cout << (a->remove(92)) << std::endl;
std::cout << (d->remove(288)) << std::endl;
*e=*d;
std::cout << (e->insert(427)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
std::cout << (c->insert(325)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (a->insert(350)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
*b=*e;
std::cout << (d->remove(273)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
std::cout << (e->remove(336)) << std::endl;
*b=*c;
std::cout << (e->remove(382)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
std::cout << (e->insert(301)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
e->printPretty();
std::cout << (e->remove(301)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
std::cout << (c->insert(130)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (c->remove(216)) << std::endl;
std::cout << (c->remove(262)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
*d=*e;
std::cout << (b->remove(495)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
std::cout << (b->remove(196)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
c->printPretty();
std::cout << (b->remove(214)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
std::cout << (b->insert(342)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (e->insert(202)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->remove(205)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
b->printPretty();
std::cout << (c->insert(399)) << std::endl;
*c=*e;
std::cout << (a->remove(235)) << std::endl;
*c=*e;
std::cout << (d->remove(367)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
c->printPretty();
std::cout << (e->insert(500)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
std::cout << (a->insert(386)) << std::endl;
std::cout << (b->remove(327)) << std::endl;
*c=*e;
std::cout << (c->remove(422)) << std::endl;
std::cout << (d->insert(427)) << std::endl;
std::cout << (c->insert(60)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
c->printPretty();
*b=*c;
*d=*c;
std::cout << (e->remove(68)) << std::endl;
std::cout << (b->remove(241)) << std::endl;
*c=*e;
std::cout << (b->insert(463)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
e->printPretty();
b->printPretty();
*e=*e;
std::cout << (d->insert(202)) << std::endl;
std::cout << (a->remove(427)) << std::endl;
std::cout << (a->insert(196)) << std::endl;
std::cout << (e->insert(378)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
std::cout << (b->insert(136)) << std::endl;
*d=*c;
std::cout << (a->remove(180)) << std::endl;
*c=*b;
std::cout << (a->insert(386)) << std::endl;
c->printPretty();
std::cout << (d->insert(265)) << std::endl;
std::cout << (b->remove(202)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (b->remove(500)) << std::endl;
std::cout << (b->remove(91)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
d->printPretty();
*b=*e;
std::cout << (b->remove(322)) << std::endl;
b->printPretty();
std::cout << (e->remove(283)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
std::cout << (a->remove(89)) << std::endl;
std::cout << (c->remove(2)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
std::cout << (b->insert(202)) << std::endl;
std::cout << (d->remove(427)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (e->insert(292)) << std::endl;
b->printPretty();
std::cout << (a->remove(472)) << std::endl;
e->printPretty();
*a=*d;
a->printPretty();
e->printPretty();
d->printPretty();
d->printPretty();
e->printPretty();
b->printPretty();
std::cout << (a->remove(360)) << std::endl;
*b=*a;
*a=*d;
std::cout << (c->insert(38)) << std::endl;
std::cout << (a->insert(60)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
std::cout << (a->insert(367)) << std::endl;
std::cout << (b->remove(154)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->insert(367)) << std::endl;
*d=*c;
std::cout << (d->insert(68)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (d->insert(202)) << std::endl;
b->printPretty();
std::cout << (d->insert(146)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (a->remove(191)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (a->remove(455)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
b->printPretty();
std::cout << (d->remove(136)) << std::endl;
std::cout << (c->insert(455)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
*a=*c;
std::cout << (e->remove(251)) << std::endl;
*e=*e;
std::cout << (d->insert(68)) << std::endl;
std::cout << (e->insert(378)) << std::endl;
d->printPretty();
std::cout << (d->remove(60)) << std::endl;
std::cout << (a->remove(463)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
e->printPretty();
std::cout << (d->remove(202)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (a->remove(309)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
*a=*c;
std::cout << (d->insert(488)) << std::endl;
*d=*b;
*d=*d;
e->printPretty();
*b=*b;
std::cout << (d->remove(375)) << std::endl;
c->printPretty();
std::cout << (b->insert(463)) << std::endl;
*c=*d;
d->printPretty();
std::cout << (a->insert(455)) << std::endl;
b->printPretty();
std::cout << (c->remove(60)) << std::endl;
e->printPretty();
std::cout << (a->insert(136)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
*a=*b;
std::cout << (c->insert(136)) << std::endl;
*d=*a;
std::cout << (b->insert(235)) << std::endl;
*b=*d;
std::cout << (d->insert(357)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (b->remove(60)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
std::cout << (c->insert(396)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (e->insert(370)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
std::cout << (b->insert(427)) << std::endl;
b->printPretty();
std::cout << (a->remove(60)) << std::endl;
std::cout << (c->insert(396)) << std::endl;
*c=*a;
std::cout << (a->remove(255)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
std::cout << (d->insert(136)) << std::endl;
std::cout << (e->insert(455)) << std::endl;
c->printPretty();
*b=*e;
e->printPretty();
b->printPretty();
std::cout << (a->insert(68)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (d->remove(111)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
e->printPretty();
std::cout << (c->remove(99)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (a->insert(348)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
*d=*a;
std::cout << (c->insert(399)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
*a=*e;
std::cout << (c->remove(26)) << std::endl;
std::cout << (d->insert(136)) << std::endl;
std::cout << (e->insert(370)) << std::endl;
std::cout << (a->remove(500)) << std::endl;
std::cout << (a->insert(68)) << std::endl;
std::cout << (a->insert(179)) << std::endl;
*e=*d;
std::cout << (a->insert(37)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
b->printPretty();
*e=*d;
*a=*d;
std::cout << (d->insert(500)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (a->remove(136)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (d->remove(202)) << std::endl;
b->printPretty();
std::cout << (c->insert(410)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (b->insert(500)) << std::endl;
std::cout << (d->remove(115)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
std::cout << (e->insert(202)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
*b=*a;
std::cout << (b->remove(399)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (b->remove(500)) << std::endl;
std::cout << (e->insert(429)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
std::cout << (d->insert(348)) << std::endl;
std::cout << (b->insert(373)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
c->printPretty();
std::cout << (c->remove(202)) << std::endl;
*a=*b;
*c=*a;
*a=*b;
std::cout << (c->insert(61)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
std::cout << (d->remove(207)) << std::endl;
b->printPretty();
std::cout << (d->remove(481)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
e->printPretty();
std::cout << (e->remove(354)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
std::cout << (e->insert(127)) << std::endl;
*c=*b;
*a=*b;
std::cout << (e->remove(101)) << std::endl;
std::cout << (c->remove(373)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
d->printPretty();
std::cout << (e->insert(429)) << std::endl;
e->printPretty();
std::cout << (d->insert(348)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
*e=*b;
std::cout << (b->insert(463)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
*a=*e;
*d=*d;
*a=*c;
std::cout << (a->remove(448)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
*a=*b;
return 0;
}
