#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
std::cout << (a->insert(273)) << std::endl;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->remove(224)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (d->insert(348)) << std::endl;
std::cout << (a->insert(273)) << std::endl;
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (b->insert(150)) << std::endl;
*c=*d;
*d=*d;
std::cout << (b->remove(150)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
*e=*a;
std::cout << (a->insert(280)) << std::endl;
std::cout << (a->remove(329)) << std::endl;
c->printPretty();
std::cout << (c->remove(310)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->remove(348)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
*c=*d;
std::cout << (a->remove(324)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
e->printPretty();
std::cout << (c->insert(179)) << std::endl;
d->printPretty();
std::cout << (a->insert(329)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
*b=*a;
std::cout << (b->insert(329)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
*a=*d;
*a=*d;
std::cout << (b->insert(329)) << std::endl;
std::cout << (c->remove(348)) << std::endl;
d->printPretty();
std::cout << (c->remove(145)) << std::endl;
std::cout << (a->remove(273)) << std::endl;
std::cout << (b->insert(334)) << std::endl;
*a=*a;
*b=*c;
*c=*d;
std::cout << (a->insert(256)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
std::cout << (e->remove(175)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
*d=*b;
std::cout << (e->remove(322)) << std::endl;
std::cout << (c->remove(348)) << std::endl;
std::cout << (d->remove(179)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
a->printPretty();
std::cout << (d->remove(83)) << std::endl;
d->printPretty();
std::cout << (a->remove(256)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
std::cout << (a->insert(348)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (c->remove(153)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
a->printPretty();
std::cout << (a->remove(315)) << std::endl;
std::cout << (a->insert(100)) << std::endl;
std::cout << (a->insert(100)) << std::endl;
std::cout << (b->remove(456)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
*d=*b;
*a=*a;
*a=*d;
d->printPretty();
std::cout << (a->insert(497)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (c->remove(345)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
std::cout << (a->insert(273)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(273)) << std::endl;
b->printPretty();
std::cout << (d->insert(47)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (b->insert(345)) << std::endl;
*c=*d;
std::cout << (e->insert(150)) << std::endl;
*b=*e;
std::cout << (c->insert(21)) << std::endl;
std::cout << (c->insert(47)) << std::endl;
std::cout << (b->remove(400)) << std::endl;
std::cout << (a->remove(356)) << std::endl;
std::cout << (e->insert(292)) << std::endl;
std::cout << (e->insert(292)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (e->remove(223)) << std::endl;
std::cout << (a->remove(345)) << std::endl;
*d=*d;
std::cout << (c->remove(86)) << std::endl;
a->printPretty();
std::cout << (d->remove(165)) << std::endl;
c->printPretty();
std::cout << (a->remove(378)) << std::endl;
c->printPretty();
std::cout << (c->remove(51)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (a->remove(112)) << std::endl;
std::cout << (a->insert(342)) << std::endl;
*b=*a;
std::cout << (c->insert(11)) << std::endl;
c->printPretty();
b->printPretty();
a->printPretty();
std::cout << (d->insert(47)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
std::cout << (a->insert(342)) << std::endl;
c->printPretty();
std::cout << (c->remove(104)) << std::endl;
b->printPretty();
std::cout << (b->remove(21)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
*c=*e;
std::cout << (b->remove(479)) << std::endl;
d->printPretty();
std::cout << (d->remove(467)) << std::endl;
c->printPretty();
std::cout << (a->remove(99)) << std::endl;
b->printPretty();
std::cout << (a->remove(342)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (e->remove(150)) << std::endl;
a->printPretty();
std::cout << (a->insert(293)) << std::endl;
std::cout << (b->remove(203)) << std::endl;
*c=*a;
std::cout << (e->insert(459)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
std::cout << (e->insert(487)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
*a=*a;
std::cout << (b->remove(342)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
std::cout << (b->insert(59)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
std::cout << (c->remove(47)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
*b=*c;
std::cout << (d->insert(345)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
a->printPretty();
std::cout << (d->remove(345)) << std::endl;
std::cout << (a->insert(15)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
*b=*e;
d->printPretty();
std::cout << (d->remove(342)) << std::endl;
std::cout << (c->remove(419)) << std::endl;
b->printPretty();
*a=*b;
std::cout << (c->remove(21)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (e->insert(301)) << std::endl;
std::cout << (a->remove(419)) << std::endl;
*c=*d;
std::cout << (e->insert(394)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
b->printPretty();
c->printPretty();
*a=*b;
std::cout << (c->insert(27)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
*e=*d;
std::cout << (e->insert(163)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (b->remove(459)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
c->printPretty();
std::cout << (e->remove(163)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
d->printPretty();
std::cout << (a->remove(369)) << std::endl;
*d=*b;
std::cout << (c->remove(163)) << std::endl;
b->printPretty();
std::cout << (d->insert(298)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
a->printPretty();
std::cout << (c->insert(51)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
*c=*a;
std::cout << (a->insert(459)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
*b=*c;
*b=*a;
std::cout << (c->remove(375)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
*d=*a;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
*b=*e;
std::cout << (a->insert(487)) << std::endl;
*d=*b;
*b=*e;
e->printPretty();
std::cout << (c->insert(309)) << std::endl;
std::cout << (b->remove(422)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
*d=*d;
std::cout << (d->remove(435)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
*b=*b;
std::cout << (c->remove(309)) << std::endl;
*b=*c;
std::cout << (d->insert(273)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
std::cout << (b->remove(487)) << std::endl;
std::cout << (d->insert(466)) << std::endl;
*c=*c;
std::cout << (d->insert(273)) << std::endl;
*c=*d;
*a=*b;
std::cout << (c->remove(466)) << std::endl;
b->printPretty();
std::cout << (a->insert(419)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (d->remove(451)) << std::endl;
std::cout << (b->insert(62)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
*e=*e;
std::cout << (e->insert(153)) << std::endl;
std::cout << (c->remove(422)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
std::cout << (e->insert(416)) << std::endl;
std::cout << (d->remove(278)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
a->printPretty();
std::cout << (c->insert(273)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->insert(384)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
d->printPretty();
std::cout << (c->remove(24)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
c->printPretty();
std::cout << (b->remove(286)) << std::endl;
d->printPretty();
std::cout << (a->remove(419)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
*a=*c;
d->printPretty();
d->printPretty();
std::cout << (e->remove(183)) << std::endl;
std::cout << (d->remove(422)) << std::endl;
std::cout << (b->remove(244)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (c->remove(25)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
e->printPretty();
std::cout << (e->remove(416)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
std::cout << (b->remove(272)) << std::endl;
std::cout << (b->remove(419)) << std::endl;
*b=*e;
d->printPretty();
std::cout << (d->insert(182)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (e->insert(55)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
std::cout << (e->insert(55)) << std::endl;
std::cout << (a->insert(426)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
a->printPretty();
std::cout << (e->insert(293)) << std::endl;
*d=*b;
std::cout << (d->insert(106)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
std::cout << (c->remove(37)) << std::endl;
std::cout << (d->remove(449)) << std::endl;
e->printPretty();
std::cout << (d->insert(207)) << std::endl;
*e=*e;
e->printPretty();
std::cout << (e->remove(55)) << std::endl;
*b=*d;
*d=*b;
std::cout << (d->remove(151)) << std::endl;
*c=*a;
a->printPretty();
*d=*d;
b->printPretty();
std::cout << (c->insert(426)) << std::endl;
std::cout << (a->remove(426)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
std::cout << (b->remove(31)) << std::endl;
std::cout << (d->insert(207)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
*c=*b;
*d=*e;
*b=*d;
d->printPretty();
b->printPretty();
b->printPretty();
std::cout << (c->remove(103)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
*a=*a;
*e=*e;
std::cout << (d->insert(310)) << std::endl;
*d=*c;
std::cout << (e->remove(431)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
e->printPretty();
std::cout << (d->remove(106)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (c->remove(53)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
*e=*c;
*a=*a;
std::cout << (d->insert(487)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
e->printPretty();
*d=*b;
*c=*a;
std::cout << (c->insert(97)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->insert(431)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
d->printPretty();
std::cout << (c->insert(97)) << std::endl;
c->printPretty();
d->printPretty();
*b=*a;
c->printPretty();
*d=*d;
std::cout << (c->insert(97)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
std::cout << (c->remove(119)) << std::endl;
*b=*b;
std::cout << (e->remove(218)) << std::endl;
std::cout << (c->insert(97)) << std::endl;
std::cout << (d->remove(351)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
std::cout << (b->insert(27)) << std::endl;
std::cout << (c->remove(97)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
*e=*d;
std::cout << (d->insert(431)) << std::endl;
*d=*b;
std::cout << (d->remove(394)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (e->remove(293)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (e->remove(269)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (a->insert(499)) << std::endl;
d->printPretty();
std::cout << (e->remove(463)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
*d=*b;
d->printPretty();
*c=*e;
*e=*b;
std::cout << (b->insert(27)) << std::endl;
*c=*e;
std::cout << (c->insert(425)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (d->insert(27)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
c->printPretty();
*d=*e;
*c=*b;
std::cout << (a->insert(46)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
*b=*e;
std::cout << (d->remove(362)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
std::cout << (a->remove(46)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
std::cout << (e->remove(178)) << std::endl;
*b=*b;
e->printPretty();
c->printPretty();
std::cout << (c->remove(251)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
*e=*c;
std::cout << (b->insert(483)) << std::endl;
std::cout << (c->remove(27)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
*a=*b;
std::cout << (e->remove(56)) << std::endl;
std::cout << (c->remove(353)) << std::endl;
std::cout << (a->insert(27)) << std::endl;
std::cout << (e->remove(27)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
std::cout << (d->remove(49)) << std::endl;
std::cout << (e->remove(143)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
d->printPretty();
std::cout << (b->insert(141)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
*d=*c;
std::cout << (a->insert(416)) << std::endl;
*d=*e;
std::cout << (d->insert(167)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (b->remove(313)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->insert(353)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
*b=*c;
std::cout << (a->insert(106)) << std::endl;
std::cout << (e->remove(401)) << std::endl;
a->printPretty();
std::cout << (a->remove(106)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
*d=*b;
std::cout << (a->remove(416)) << std::endl;
e->printPretty();
std::cout << (c->remove(200)) << std::endl;
c->printPretty();
b->printPretty();
c->printPretty();
std::cout << (d->remove(83)) << std::endl;
std::cout << (d->insert(75)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (a->remove(107)) << std::endl;
std::cout << (a->insert(63)) << std::endl;
std::cout << (c->remove(111)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
b->printPretty();
*c=*b;
*a=*c;
*e=*c;
std::cout << (a->remove(215)) << std::endl;
*c=*d;
std::cout << (d->insert(75)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
e->printPretty();
std::cout << (d->insert(141)) << std::endl;
c->printPretty();
std::cout << (d->insert(75)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
std::cout << (a->remove(454)) << std::endl;
*e=*b;
std::cout << (d->remove(219)) << std::endl;
b->printPretty();
std::cout << (b->insert(387)) << std::endl;
std::cout << (c->remove(139)) << std::endl;
*c=*c;
std::cout << (b->insert(387)) << std::endl;
std::cout << (a->remove(335)) << std::endl;
std::cout << (e->remove(493)) << std::endl;
*c=*e;
std::cout << (c->remove(111)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
std::cout << (c->insert(397)) << std::endl;
d->printPretty();
std::cout << (d->insert(75)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (d->insert(75)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
*b=*c;
std::cout << (a->insert(154)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
*d=*e;
std::cout << (c->remove(437)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (c->remove(308)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
*b=*c;
*b=*e;
d->printPretty();
c->printPretty();
std::cout << (d->insert(152)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (c->remove(436)) << std::endl;
std::cout << (d->insert(67)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (b->remove(85)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
*d=*c;
std::cout << (c->insert(28)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (e->insert(71)) << std::endl;
std::cout << (a->insert(337)) << std::endl;
*a=*e;
std::cout << (c->insert(465)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
std::cout << (a->insert(418)) << std::endl;
a->printPretty();
std::cout << (d->remove(95)) << std::endl;
a->printPretty();
std::cout << (c->insert(465)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
d->printPretty();
std::cout << (a->remove(132)) << std::endl;
std::cout << (b->remove(500)) << std::endl;
*e=*e;
*c=*b;
b->printPretty();
std::cout << (c->remove(277)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
*c=*d;
std::cout << (a->insert(377)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (e->remove(500)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (b->remove(193)) << std::endl;
*d=*e;
*c=*e;
*d=*d;
d->printPretty();
d->printPretty();
std::cout << (e->remove(278)) << std::endl;
c->printPretty();
*b=*a;
*a=*a;
std::cout << (e->remove(425)) << std::endl;
d->printPretty();
std::cout << (b->insert(71)) << std::endl;
std::cout << (e->remove(24)) << std::endl;
std::cout << (d->remove(71)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
std::cout << (d->remove(353)) << std::endl;
std::cout << (a->insert(466)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
*b=*e;
std::cout << (a->insert(377)) << std::endl;
b->printPretty();
std::cout << (c->remove(71)) << std::endl;
std::cout << (a->insert(500)) << std::endl;
e->printPretty();
std::cout << (a->insert(418)) << std::endl;
*e=*c;
std::cout << (a->remove(346)) << std::endl;
*b=*b;
std::cout << (a->remove(193)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (b->remove(237)) << std::endl;
*d=*b;
std::cout << (d->remove(71)) << std::endl;
*d=*b;
c->printPretty();
b->printPretty();
std::cout << (d->insert(176)) << std::endl;
c->printPretty();
*b=*d;
std::cout << (d->insert(71)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
*d=*c;
std::cout << (b->remove(176)) << std::endl;
std::cout << (e->remove(475)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
*a=*d;
c->printPretty();
e->printPretty();
*a=*e;
std::cout << (b->insert(71)) << std::endl;
std::cout << (d->remove(265)) << std::endl;
std::cout << (c->remove(265)) << std::endl;
c->printPretty();
std::cout << (c->insert(5)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
a->printPretty();
a->printPretty();
c->printPretty();
std::cout << (d->remove(240)) << std::endl;
std::cout << (b->remove(71)) << std::endl;
d->printPretty();
std::cout << (c->insert(5)) << std::endl;
std::cout << (a->remove(57)) << std::endl;
std::cout << (c->insert(5)) << std::endl;
*d=*b;
std::cout << (c->remove(5)) << std::endl;
*a=*e;
e->printPretty();
*d=*c;
std::cout << (b->remove(59)) << std::endl;
*a=*d;
e->printPretty();
*d=*c;
std::cout << (a->insert(17)) << std::endl;
std::cout << (a->insert(19)) << std::endl;
*e=*c;
b->printPretty();
*e=*a;
std::cout << (b->insert(28)) << std::endl;
std::cout << (a->remove(396)) << std::endl;
std::cout << (d->insert(147)) << std::endl;
std::cout << (b->remove(28)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
*e=*e;
std::cout << (d->insert(87)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
return 0;
}
