#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(93)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
b->printPretty();
*a=*a;
std::cout << (a->remove(435)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->insert(154)) << std::endl;
*c=*a;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
a->printPretty();
a->printPretty();
*b=*d;
std::cout << (a->remove(154)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (b->insert(154)) << std::endl;
std::cout << (b->remove(154)) << std::endl;
std::cout << (e->remove(133)) << std::endl;
e->printPretty();
std::cout << (c->remove(340)) << std::endl;
std::cout << (d->insert(300)) << std::endl;
std::cout << (c->remove(12)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
a->printPretty();
std::cout << (d->insert(114)) << std::endl;
*a=*b;
std::cout << (c->insert(373)) << std::endl;
std::cout << (e->insert(133)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (d->insert(360)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
std::cout << (b->remove(55)) << std::endl;
e->printPretty();
std::cout << (e->insert(178)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
*c=*e;
std::cout << (b->insert(124)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (c->remove(139)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
e->printPretty();
std::cout << (b->insert(83)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
std::cout << (e->remove(133)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
*d=*e;
std::cout << (a->insert(26)) << std::endl;
std::cout << (d->insert(275)) << std::endl;
*c=*d;
*b=*c;
b->printPretty();
std::cout << (e->remove(464)) << std::endl;
std::cout << (e->remove(238)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (e->remove(178)) << std::endl;
std::cout << (e->insert(376)) << std::endl;
c->printPretty();
std::cout << (d->insert(178)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->remove(117)) << std::endl;
*a=*a;
*c=*d;
std::cout << (b->remove(275)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
std::cout << (d->remove(474)) << std::endl;
*b=*a;
std::cout << (b->insert(368)) << std::endl;
std::cout << (a->remove(26)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (d->remove(178)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
*b=*c;
std::cout << (e->remove(376)) << std::endl;
*d=*c;
*a=*b;
a->printPretty();
std::cout << (b->remove(40)) << std::endl;
std::cout << (c->insert(416)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (e->remove(154)) << std::endl;
*c=*a;
std::cout << (a->insert(62)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
*a=*b;
std::cout << (a->insert(54)) << std::endl;
*e=*b;
std::cout << (c->remove(283)) << std::endl;
*b=*d;
*e=*d;
std::cout << (b->insert(283)) << std::endl;
std::cout << (e->insert(426)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
e->printPretty();
*b=*e;
b->printPretty();
std::cout << (a->insert(54)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
*b=*d;
*a=*e;
e->printPretty();
e->printPretty();
std::cout << (a->remove(463)) << std::endl;
std::cout << (d->remove(198)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
d->printPretty();
std::cout << (c->remove(40)) << std::endl;
c->printPretty();
b->printPretty();
*b=*e;
std::cout << (c->insert(414)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (c->insert(368)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
a->printPretty();
std::cout << (c->insert(96)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
std::cout << (c->insert(40)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
std::cout << (a->remove(117)) << std::endl;
b->printPretty();
std::cout << (c->remove(202)) << std::endl;
std::cout << (b->remove(20)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
*c=*b;
std::cout << (e->remove(426)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
a->printPretty();
std::cout << (d->insert(255)) << std::endl;
*a=*a;
std::cout << (a->insert(178)) << std::endl;
*a=*b;
std::cout << (e->remove(24)) << std::endl;
d->printPretty();
std::cout << (a->insert(201)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
*d=*e;
std::cout << (a->insert(425)) << std::endl;
std::cout << (d->insert(288)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (c->remove(359)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
std::cout << (e->remove(154)) << std::endl;
std::cout << (b->insert(363)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (d->remove(283)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
c->printPretty();
std::cout << (a->insert(500)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
std::cout << (d->insert(303)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
a->printPretty();
std::cout << (c->insert(426)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
std::cout << (b->remove(178)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
*c=*d;
std::cout << (e->remove(288)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (e->insert(283)) << std::endl;
std::cout << (b->remove(500)) << std::endl;
e->printPretty();
std::cout << (b->remove(87)) << std::endl;
std::cout << (b->insert(263)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
std::cout << (c->insert(402)) << std::endl;
d->printPretty();
std::cout << (d->remove(426)) << std::endl;
std::cout << (d->insert(303)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
std::cout << (d->insert(178)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (b->insert(425)) << std::endl;
*d=*c;
*d=*a;
*d=*d;
*a=*b;
*a=*a;
std::cout << (e->remove(142)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
*e=*a;
*e=*b;
std::cout << (d->insert(11)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
std::cout << (b->insert(426)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (c->insert(201)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
*d=*a;
std::cout << (c->insert(154)) << std::endl;
std::cout << (a->remove(162)) << std::endl;
std::cout << (b->insert(396)) << std::endl;
std::cout << (e->remove(178)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
*a=*e;
std::cout << (d->insert(223)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (a->insert(141)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (a->insert(189)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (c->remove(201)) << std::endl;
std::cout << (d->remove(433)) << std::endl;
*b=*b;
std::cout << (c->remove(379)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
b->printPretty();
std::cout << (e->insert(485)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
std::cout << (a->insert(201)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (e->remove(195)) << std::endl;
c->printPretty();
*a=*e;
std::cout << (d->remove(23)) << std::endl;
std::cout << (e->insert(380)) << std::endl;
std::cout << (e->remove(388)) << std::endl;
std::cout << (a->remove(252)) << std::endl;
std::cout << (a->insert(485)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->remove(500)) << std::endl;
std::cout << (b->remove(174)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
e->printPretty();
std::cout << (c->remove(435)) << std::endl;
*a=*e;
std::cout << (d->insert(283)) << std::endl;
std::cout << (b->insert(189)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
c->printPretty();
std::cout << (c->insert(378)) << std::endl;
e->printPretty();
std::cout << (d->insert(283)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
c->printPretty();
std::cout << (c->insert(248)) << std::endl;
*c=*c;
std::cout << (e->insert(460)) << std::endl;
std::cout << (c->insert(323)) << std::endl;
std::cout << (a->remove(201)) << std::endl;
std::cout << (d->insert(418)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
a->printPretty();
std::cout << (e->insert(426)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
*e=*d;
std::cout << (a->insert(433)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
e->printPretty();
std::cout << (a->insert(342)) << std::endl;
*b=*a;
std::cout << (d->insert(178)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (d->remove(178)) << std::endl;
std::cout << (d->remove(283)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->remove(426)) << std::endl;
std::cout << (a->remove(433)) << std::endl;
e->printPretty();
std::cout << (a->insert(97)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
c->printPretty();
std::cout << (d->insert(115)) << std::endl;
std::cout << (c->remove(381)) << std::endl;
*d=*b;
b->printPretty();
std::cout << (c->remove(213)) << std::endl;
*c=*a;
*a=*e;
std::cout << (c->remove(331)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
e->printPretty();
std::cout << (b->remove(330)) << std::endl;
*c=*c;
std::cout << (a->remove(425)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (c->remove(302)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (c->remove(295)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (e->remove(201)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
std::cout << (e->insert(34)) << std::endl;
std::cout << (c->insert(382)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (e->insert(175)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
std::cout << (e->remove(283)) << std::endl;
b->printPretty();
std::cout << (e->remove(34)) << std::endl;
a->printPretty();
std::cout << (d->remove(396)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
a->printPretty();
std::cout << (c->remove(390)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
*c=*c;
std::cout << (c->insert(440)) << std::endl;
std::cout << (d->insert(314)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
c->printPretty();
std::cout << (a->insert(140)) << std::endl;
std::cout << (b->remove(396)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
std::cout << (d->remove(318)) << std::endl;
*b=*e;
std::cout << (d->remove(189)) << std::endl;
*b=*b;
std::cout << (a->remove(178)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
std::cout << (e->insert(315)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
d->printPretty();
std::cout << (e->insert(175)) << std::endl;
*d=*c;
*a=*a;
std::cout << (b->remove(223)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
*c=*d;
std::cout << (b->insert(34)) << std::endl;
std::cout << (c->remove(419)) << std::endl;
c->printPretty();
std::cout << (c->remove(440)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
std::cout << (a->remove(140)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
std::cout << (a->insert(484)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
*d=*e;
std::cout << (a->insert(196)) << std::endl;
std::cout << (c->insert(127)) << std::endl;
*a=*a;
std::cout << (a->remove(484)) << std::endl;
std::cout << (d->remove(175)) << std::endl;
std::cout << (a->insert(283)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
*b=*c;
std::cout << (a->remove(175)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (a->remove(217)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (a->remove(459)) << std::endl;
*b=*c;
std::cout << (b->remove(317)) << std::endl;
std::cout << (b->remove(220)) << std::endl;
*c=*e;
std::cout << (b->insert(426)) << std::endl;
std::cout << (b->remove(8)) << std::endl;
c->printPretty();
std::cout << (e->insert(178)) << std::endl;
a->printPretty();
std::cout << (d->insert(12)) << std::endl;
*b=*a;
std::cout << (c->remove(426)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (b->insert(283)) << std::endl;
d->printPretty();
std::cout << (d->remove(223)) << std::endl;
*b=*e;
std::cout << (a->insert(223)) << std::endl;
std::cout << (e->remove(324)) << std::endl;
std::cout << (e->insert(315)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->remove(59)) << std::endl;
*c=*e;
std::cout << (a->remove(141)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
e->printPretty();
std::cout << (d->insert(12)) << std::endl;
c->printPretty();
std::cout << (d->remove(315)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
std::cout << (a->insert(99)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
*e=*c;
*c=*c;
a->printPretty();
c->printPretty();
std::cout << (b->insert(315)) << std::endl;
*b=*a;
std::cout << (c->remove(178)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
*c=*a;
std::cout << (b->insert(76)) << std::endl;
*c=*d;
std::cout << (b->remove(245)) << std::endl;
e->printPretty();
std::cout << (e->insert(178)) << std::endl;
std::cout << (c->remove(192)) << std::endl;
std::cout << (a->insert(242)) << std::endl;
a->printPretty();
std::cout << (c->remove(12)) << std::endl;
*e=*a;
std::cout << (e->remove(452)) << std::endl;
c->printPretty();
std::cout << (b->insert(201)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (d->insert(418)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
std::cout << (e->remove(336)) << std::endl;
std::cout << (a->remove(172)) << std::endl;
b->printPretty();
std::cout << (d->remove(283)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
std::cout << (d->remove(283)) << std::endl;
*a=*a;
std::cout << (b->insert(94)) << std::endl;
std::cout << (a->insert(283)) << std::endl;
*e=*a;
std::cout << (c->insert(418)) << std::endl;
std::cout << (a->insert(99)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
e->printPretty();
std::cout << (e->remove(137)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
std::cout << (b->insert(415)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
std::cout << (b->insert(438)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
*a=*d;
std::cout << (a->remove(178)) << std::endl;
std::cout << (d->insert(178)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (a->remove(155)) << std::endl;
*d=*c;
std::cout << (d->remove(418)) << std::endl;
*b=*e;
std::cout << (a->remove(483)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
e->printPretty();
std::cout << (b->remove(426)) << std::endl;
std::cout << (d->remove(179)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
*b=*e;
std::cout << (d->insert(301)) << std::endl;
std::cout << (c->insert(418)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (a->insert(218)) << std::endl;
*a=*c;
*a=*c;
std::cout << (c->remove(301)) << std::endl;
std::cout << (b->insert(76)) << std::endl;
d->printPretty();
std::cout << (e->insert(94)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (e->remove(201)) << std::endl;
std::cout << (a->insert(19)) << std::endl;
std::cout << (a->remove(99)) << std::endl;
*d=*a;
std::cout << (a->remove(178)) << std::endl;
std::cout << (c->insert(495)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (d->insert(301)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
std::cout << (d->remove(124)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
*a=*b;
std::cout << (e->remove(415)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->insert(298)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->remove(238)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
std::cout << (c->remove(495)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
a->printPretty();
std::cout << (b->insert(94)) << std::endl;
std::cout << (d->remove(74)) << std::endl;
e->printPretty();
std::cout << (d->remove(458)) << std::endl;
*b=*c;
std::cout << (e->insert(151)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
*c=*c;
std::cout << (c->remove(78)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
std::cout << (d->remove(178)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (c->insert(449)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
c->printPretty();
e->printPretty();
d->printPretty();
*c=*c;
b->printPretty();
std::cout << (a->remove(20)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
*c=*a;
std::cout << (e->insert(426)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
c->printPretty();
std::cout << (a->remove(99)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
e->printPretty();
std::cout << (e->insert(394)) << std::endl;
std::cout << (e->insert(67)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
std::cout << (e->remove(283)) << std::endl;
std::cout << (a->remove(353)) << std::endl;
std::cout << (b->insert(318)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
d->printPretty();
std::cout << (c->insert(318)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (a->remove(200)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
std::cout << (e->insert(210)) << std::endl;
std::cout << (c->remove(318)) << std::endl;
*b=*a;
std::cout << (b->insert(466)) << std::endl;
std::cout << (e->remove(67)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
std::cout << (d->insert(380)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
*d=*d;
std::cout << (b->remove(93)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
std::cout << (b->remove(98)) << std::endl;
c->printPretty();
std::cout << (c->insert(387)) << std::endl;
d->printPretty();
std::cout << (a->remove(454)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (d->remove(261)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (c->insert(367)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->insert(242)) << std::endl;
std::cout << (e->insert(412)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
*b=*d;
d->printPretty();
*e=*b;
*e=*d;
a->printPretty();
*c=*c;
std::cout << (e->insert(463)) << std::endl;
std::cout << (b->insert(301)) << std::endl;
std::cout << (c->insert(387)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
std::cout << (e->insert(418)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
b->printPretty();
std::cout << (b->remove(19)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (c->insert(457)) << std::endl;
std::cout << (e->insert(13)) << std::endl;
a->printPretty();
std::cout << (e->remove(19)) << std::endl;
std::cout << (e->remove(463)) << std::endl;
*b=*b;
std::cout << (d->remove(9)) << std::endl;
*d=*b;
std::cout << (c->remove(491)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
*c=*b;
*b=*e;
std::cout << (b->insert(418)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
*c=*e;
std::cout << (e->remove(304)) << std::endl;
d->printPretty();
*d=*c;
d->printPretty();
*d=*c;
std::cout << (d->remove(320)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (a->remove(173)) << std::endl;
*e=*e;
*e=*c;
std::cout << (d->remove(323)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
d->printPretty();
std::cout << (e->remove(401)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
std::cout << (a->remove(426)) << std::endl;
std::cout << (e->remove(262)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (b->remove(301)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
e->printPretty();
std::cout << (b->insert(13)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (e->remove(242)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (b->remove(467)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
c->printPretty();
std::cout << (a->remove(426)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
*c=*a;
std::cout << (d->remove(446)) << std::endl;
std::cout << (c->insert(160)) << std::endl;
e->printPretty();
std::cout << (e->remove(456)) << std::endl;
a->printPretty();
std::cout << (b->insert(197)) << std::endl;
a->printPretty();
std::cout << (c->insert(223)) << std::endl;
*e=*c;
std::cout << (b->insert(380)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (c->remove(127)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
*a=*b;
std::cout << (a->remove(395)) << std::endl;
std::cout << (c->insert(377)) << std::endl;
*a=*b;
*b=*c;
std::cout << (b->insert(291)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
a->printPretty();
std::cout << (a->remove(109)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
*a=*a;
std::cout << (b->insert(415)) << std::endl;
*c=*b;
std::cout << (a->remove(253)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
*e=*e;
std::cout << (c->remove(291)) << std::endl;
*d=*e;
std::cout << (c->insert(113)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (e->insert(201)) << std::endl;
std::cout << (d->insert(277)) << std::endl;
std::cout << (e->remove(154)) << std::endl;
std::cout << (c->remove(160)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (a->remove(418)) << std::endl;
*e=*e;
std::cout << (d->insert(79)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
std::cout << (e->remove(130)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
std::cout << (b->remove(98)) << std::endl;
std::cout << (b->remove(160)) << std::endl;
return 0;
}
