#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (c->insert(33)) << std::endl;
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->remove(407)) << std::endl;
std::cout << (d->insert(233)) << std::endl;
*b=*c;
std::cout << (a->insert(490)) << std::endl;
std::cout << (d->insert(233)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
d->printPretty();
*b=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (e->insert(265)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (d->remove(490)) << std::endl;
std::cout << (b->remove(417)) << std::endl;
*a=*c;
std::cout << (c->remove(72)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
a->printPretty();
std::cout << (a->remove(210)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (e->remove(265)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (b->insert(226)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
*b=*a;
std::cout << (b->insert(33)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
d->printPretty();
std::cout << (b->insert(234)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
*c=*c;
std::cout << (b->remove(455)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
std::cout << (e->insert(382)) << std::endl;
*e=*d;
*b=*d;
std::cout << (e->insert(389)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
std::cout << (e->remove(414)) << std::endl;
d->printPretty();
e->printPretty();
a->printPretty();
d->printPretty();
*b=*c;
std::cout << (c->remove(202)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
std::cout << (d->remove(324)) << std::endl;
b->printPretty();
std::cout << (c->remove(477)) << std::endl;
d->printPretty();
*e=*e;
b->printPretty();
*e=*c;
std::cout << (a->insert(241)) << std::endl;
*c=*b;
b->printPretty();
std::cout << (a->insert(241)) << std::endl;
*a=*d;
std::cout << (e->remove(172)) << std::endl;
std::cout << (e->insert(287)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
*c=*a;
std::cout << (d->remove(197)) << std::endl;
*a=*a;
std::cout << (e->insert(287)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
*c=*c;
std::cout << (e->insert(342)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
std::cout << (b->insert(202)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
e->printPretty();
std::cout << (c->insert(147)) << std::endl;
std::cout << (a->remove(350)) << std::endl;
c->printPretty();
std::cout << (c->remove(147)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->insert(147)) << std::endl;
*d=*a;
std::cout << (c->insert(203)) << std::endl;
std::cout << (b->insert(202)) << std::endl;
std::cout << (d->insert(147)) << std::endl;
*d=*b;
c->printPretty();
*c=*b;
std::cout << (d->insert(202)) << std::endl;
std::cout << (c->insert(318)) << std::endl;
c->printPretty();
std::cout << (c->remove(261)) << std::endl;
std::cout << (a->insert(435)) << std::endl;
std::cout << (e->insert(287)) << std::endl;
std::cout << (e->remove(287)) << std::endl;
*c=*c;
std::cout << (c->insert(202)) << std::endl;
e->printPretty();
std::cout << (b->remove(290)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
*e=*e;
std::cout << (d->remove(202)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (a->remove(435)) << std::endl;
std::cout << (a->insert(147)) << std::endl;
std::cout << (c->insert(318)) << std::endl;
a->printPretty();
std::cout << (a->insert(147)) << std::endl;
b->printPretty();
std::cout << (a->insert(197)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
*e=*c;
std::cout << (b->insert(23)) << std::endl;
*b=*c;
std::cout << (a->insert(197)) << std::endl;
std::cout << (b->insert(318)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
b->printPretty();
std::cout << (a->remove(197)) << std::endl;
std::cout << (e->remove(428)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
c->printPretty();
std::cout << (c->remove(202)) << std::endl;
*e=*d;
*c=*a;
std::cout << (b->insert(265)) << std::endl;
d->printPretty();
e->printPretty();
e->printPretty();
std::cout << (c->insert(183)) << std::endl;
c->printPretty();
std::cout << (b->remove(463)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
e->printPretty();
std::cout << (c->insert(99)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
*b=*e;
std::cout << (d->remove(154)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
std::cout << (a->insert(283)) << std::endl;
*c=*b;
e->printPretty();
*a=*a;
std::cout << (c->insert(319)) << std::endl;
b->printPretty();
std::cout << (c->insert(319)) << std::endl;
e->printPretty();
std::cout << (a->remove(283)) << std::endl;
*a=*d;
*e=*b;
std::cout << (c->remove(237)) << std::endl;
std::cout << (c->remove(77)) << std::endl;
std::cout << (a->insert(30)) << std::endl;
std::cout << (c->remove(319)) << std::endl;
*b=*a;
std::cout << (e->remove(356)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
*e=*c;
std::cout << (e->remove(149)) << std::endl;
*c=*b;
std::cout << (a->remove(266)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (e->insert(29)) << std::endl;
std::cout << (b->remove(30)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
d->printPretty();
std::cout << (a->remove(30)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
std::cout << (d->remove(59)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (e->remove(293)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
b->printPretty();
std::cout << (d->insert(29)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (c->insert(293)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->insert(188)) << std::endl;
*e=*a;
std::cout << (e->remove(149)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
b->printPretty();
std::cout << (d->insert(29)) << std::endl;
*d=*b;
std::cout << (b->remove(379)) << std::endl;
a->printPretty();
*c=*b;
*d=*d;
std::cout << (c->insert(317)) << std::endl;
std::cout << (e->insert(63)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (e->insert(73)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
*d=*e;
std::cout << (a->insert(377)) << std::endl;
*c=*b;
std::cout << (e->insert(189)) << std::endl;
c->printPretty();
std::cout << (b->insert(80)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
std::cout << (a->insert(377)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (b->remove(111)) << std::endl;
std::cout << (a->insert(377)) << std::endl;
std::cout << (c->remove(485)) << std::endl;
*d=*c;
*d=*a;
std::cout << (e->remove(425)) << std::endl;
std::cout << (a->remove(453)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
e->printPretty();
std::cout << (d->insert(377)) << std::endl;
*a=*d;
std::cout << (b->remove(250)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
*e=*b;
*b=*a;
std::cout << (a->insert(377)) << std::endl;
std::cout << (a->insert(377)) << std::endl;
std::cout << (a->insert(54)) << std::endl;
*c=*c;
std::cout << (a->remove(54)) << std::endl;
*a=*d;
std::cout << (e->remove(229)) << std::endl;
c->printPretty();
std::cout << (c->remove(19)) << std::endl;
std::cout << (d->insert(95)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
std::cout << (d->insert(374)) << std::endl;
std::cout << (b->insert(139)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
std::cout << (e->remove(480)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
a->printPretty();
std::cout << (a->remove(238)) << std::endl;
d->printPretty();
std::cout << (a->insert(213)) << std::endl;
e->printPretty();
std::cout << (a->remove(170)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (c->insert(233)) << std::endl;
*b=*d;
*c=*e;
std::cout << (d->insert(485)) << std::endl;
a->printPretty();
std::cout << (c->remove(63)) << std::endl;
*b=*b;
*e=*d;
std::cout << (c->remove(256)) << std::endl;
*a=*d;
*d=*b;
std::cout << (b->remove(169)) << std::endl;
c->printPretty();
std::cout << (e->insert(169)) << std::endl;
std::cout << (c->remove(441)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
a->printPretty();
std::cout << (e->remove(377)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
std::cout << (e->insert(169)) << std::endl;
std::cout << (a->remove(250)) << std::endl;
e->printPretty();
std::cout << (a->remove(377)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
std::cout << (d->insert(479)) << std::endl;
std::cout << (a->remove(158)) << std::endl;
std::cout << (a->remove(485)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
*a=*c;
std::cout << (e->remove(169)) << std::endl;
b->printPretty();
std::cout << (d->insert(135)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
std::cout << (b->insert(377)) << std::endl;
*b=*e;
*c=*a;
std::cout << (e->remove(213)) << std::endl;
std::cout << (c->insert(150)) << std::endl;
b->printPretty();
std::cout << (e->insert(219)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
*d=*b;
std::cout << (a->remove(370)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
*e=*d;
*d=*d;
e->printPretty();
e->printPretty();
std::cout << (a->insert(422)) << std::endl;
b->printPretty();
std::cout << (c->remove(325)) << std::endl;
a->printPretty();
*e=*d;
b->printPretty();
*c=*e;
std::cout << (b->remove(379)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(234)) << std::endl;
std::cout << (e->remove(234)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->insert(345)) << std::endl;
std::cout << (a->insert(360)) << std::endl;
*b=*e;
*e=*e;
std::cout << (a->insert(58)) << std::endl;
*e=*c;
*c=*a;
a->printPretty();
*c=*e;
*e=*a;
std::cout << (a->remove(58)) << std::endl;
*e=*e;
std::cout << (e->insert(422)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (a->remove(360)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
std::cout << (d->remove(320)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*d=*c;
std::cout << (c->insert(345)) << std::endl;
e->printPretty();
std::cout << (d->insert(345)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
*b=*a;
std::cout << (b->remove(294)) << std::endl;
std::cout << (d->insert(277)) << std::endl;
std::cout << (c->remove(345)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
std::cout << (d->insert(345)) << std::endl;
std::cout << (e->insert(360)) << std::endl;
std::cout << (c->insert(54)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (c->insert(422)) << std::endl;
std::cout << (b->remove(188)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
*c=*d;
std::cout << (c->remove(345)) << std::endl;
*b=*c;
*b=*e;
std::cout << (a->remove(321)) << std::endl;
*e=*d;
std::cout << (d->insert(51)) << std::endl;
*d=*b;
std::cout << (d->insert(422)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
c->printPretty();
std::cout << (b->remove(235)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (a->remove(451)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (c->insert(116)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
std::cout << (a->insert(176)) << std::endl;
std::cout << (c->insert(116)) << std::endl;
b->printPretty();
std::cout << (b->remove(58)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (d->insert(30)) << std::endl;
b->printPretty();
std::cout << (c->remove(361)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
c->printPretty();
std::cout << (d->remove(422)) << std::endl;
*b=*a;
std::cout << (a->insert(459)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
std::cout << (c->remove(218)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
*b=*e;
std::cout << (d->insert(360)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
a->printPretty();
std::cout << (a->remove(459)) << std::endl;
*a=*b;
std::cout << (e->remove(277)) << std::endl;
std::cout << (e->remove(374)) << std::endl;
std::cout << (e->insert(50)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (a->remove(345)) << std::endl;
std::cout << (d->insert(30)) << std::endl;
*d=*d;
*b=*d;
std::cout << (a->remove(277)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(444)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
b->printPretty();
std::cout << (e->insert(50)) << std::endl;
a->printPretty();
std::cout << (d->remove(444)) << std::endl;
std::cout << (c->remove(131)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (d->remove(67)) << std::endl;
std::cout << (b->insert(58)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
std::cout << (e->remove(50)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (a->remove(394)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (c->remove(345)) << std::endl;
std::cout << (d->insert(58)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->remove(360)) << std::endl;
std::cout << (b->remove(30)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
std::cout << (d->insert(478)) << std::endl;
a->printPretty();
std::cout << (d->insert(216)) << std::endl;
std::cout << (e->remove(416)) << std::endl;
*b=*d;
*c=*e;
*b=*e;
*d=*e;
std::cout << (c->remove(113)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->insert(369)) << std::endl;
*a=*a;
std::cout << (d->remove(190)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (c->remove(256)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (e->insert(396)) << std::endl;
*a=*e;
std::cout << (e->remove(396)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->remove(406)) << std::endl;
*e=*d;
std::cout << (e->remove(299)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
*c=*e;
std::cout << (a->remove(396)) << std::endl;
*b=*d;
std::cout << (e->remove(10)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (e->remove(111)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (e->insert(97)) << std::endl;
d->printPretty();
std::cout << (d->remove(2)) << std::endl;
*b=*c;
e->printPretty();
*a=*d;
std::cout << (a->remove(119)) << std::endl;
*d=*c;
std::cout << (c->remove(233)) << std::endl;
std::cout << (d->insert(206)) << std::endl;
c->printPretty();
std::cout << (c->insert(179)) << std::endl;
b->printPretty();
std::cout << (d->insert(428)) << std::endl;
std::cout << (c->insert(46)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
std::cout << (a->remove(364)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
*e=*b;
std::cout << (e->insert(381)) << std::endl;
d->printPretty();
std::cout << (d->insert(206)) << std::endl;
*e=*b;
std::cout << (d->insert(428)) << std::endl;
b->printPretty();
std::cout << (a->remove(66)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (c->insert(171)) << std::endl;
std::cout << (b->insert(297)) << std::endl;
std::cout << (b->remove(297)) << std::endl;
e->printPretty();
std::cout << (c->insert(172)) << std::endl;
std::cout << (c->remove(171)) << std::endl;
std::cout << (a->remove(46)) << std::endl;
std::cout << (a->remove(145)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
std::cout << (d->insert(59)) << std::endl;
*c=*a;
*e=*b;
std::cout << (a->insert(436)) << std::endl;
std::cout << (d->insert(206)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
c->printPretty();
std::cout << (d->insert(219)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (c->remove(481)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (d->insert(370)) << std::endl;
std::cout << (c->remove(200)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->insert(179)) << std::endl;
std::cout << (a->remove(200)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
d->printPretty();
std::cout << (e->remove(497)) << std::endl;
d->printPretty();
std::cout << (c->remove(24)) << std::endl;
*c=*e;
*a=*d;
std::cout << (c->insert(14)) << std::endl;
std::cout << (d->insert(370)) << std::endl;
b->printPretty();
std::cout << (c->remove(14)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(488)) << std::endl;
std::cout << (e->remove(89)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
*e=*a;
std::cout << (d->insert(216)) << std::endl;
std::cout << (c->insert(67)) << std::endl;
e->printPretty();
std::cout << (e->remove(219)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (c->remove(136)) << std::endl;
std::cout << (c->remove(67)) << std::endl;
std::cout << (e->insert(402)) << std::endl;
std::cout << (e->remove(428)) << std::endl;
*e=*d;
std::cout << (e->remove(370)) << std::endl;
e->printPretty();
std::cout << (e->remove(256)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
b->printPretty();
*e=*d;
d->printPretty();
*d=*a;
std::cout << (a->insert(447)) << std::endl;
a->printPretty();
std::cout << (c->remove(142)) << std::endl;
b->printPretty();
std::cout << (c->insert(329)) << std::endl;
std::cout << (b->remove(311)) << std::endl;
*a=*e;
std::cout << (c->remove(329)) << std::endl;
std::cout << (e->insert(122)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
d->printPretty();
*e=*d;
d->printPretty();
std::cout << (a->insert(100)) << std::endl;
*a=*c;
*a=*a;
std::cout << (a->insert(445)) << std::endl;
std::cout << (e->insert(266)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (c->insert(445)) << std::endl;
std::cout << (d->insert(418)) << std::endl;
b->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(445)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->remove(445)) << std::endl;
b->printPretty();
std::cout << (b->remove(119)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (b->insert(330)) << std::endl;
c->printPretty();
std::cout << (d->remove(280)) << std::endl;
*a=*e;
*c=*e;
*d=*a;
std::cout << (a->remove(185)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
std::cout << (e->remove(445)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (b->remove(353)) << std::endl;
d->printPretty();
std::cout << (e->remove(499)) << std::endl;
std::cout << (e->remove(160)) << std::endl;
return 0;
}
