#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(74)) << std::endl;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (d->insert(79)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
*e=*c;
*d=*d;
d->printPretty();
*e=*e;
*e=*c;
*d=*b;
*a=*d;
*a=*d;
b->printPretty();
d->printPretty();
e->printPretty();
*d=*c;
std::cout << (d->insert(180)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
std::cout << (a->insert(474)) << std::endl;
std::cout << (d->remove(180)) << std::endl;
a->printPretty();
std::cout << (b->remove(224)) << std::endl;
std::cout << (e->remove(412)) << std::endl;
b->printPretty();
c->printPretty();
*d=*b;
std::cout << (c->insert(245)) << std::endl;
std::cout << (c->insert(375)) << std::endl;
std::cout << (a->remove(474)) << std::endl;
*d=*c;
a->printPretty();
std::cout << (e->remove(310)) << std::endl;
*a=*d;
std::cout << (c->remove(245)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
*b=*a;
std::cout << (a->remove(375)) << std::endl;
std::cout << (c->insert(375)) << std::endl;
std::cout << (c->remove(385)) << std::endl;
a->printPretty();
std::cout << (c->insert(481)) << std::endl;
c->printPretty();
*c=*c;
d->printPretty();
b->printPretty();
std::cout << (d->remove(193)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (c->remove(479)) << std::endl;
std::cout << (b->remove(245)) << std::endl;
a->printPretty();
*e=*b;
c->printPretty();
std::cout << (d->insert(375)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
std::cout << (d->insert(375)) << std::endl;
std::cout << (c->insert(18)) << std::endl;
std::cout << (a->remove(311)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
d->printPretty();
std::cout << (c->remove(338)) << std::endl;
std::cout << (d->insert(245)) << std::endl;
std::cout << (b->remove(2)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (b->insert(296)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
a->printPretty();
*a=*a;
std::cout << (a->remove(262)) << std::endl;
std::cout << (d->insert(327)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->insert(324)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
*d=*b;
std::cout << (e->remove(41)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (e->remove(408)) << std::endl;
*c=*b;
std::cout << (e->remove(375)) << std::endl;
*c=*e;
std::cout << (d->insert(324)) << std::endl;
a->printPretty();
std::cout << (b->insert(231)) << std::endl;
std::cout << (b->remove(305)) << std::endl;
*e=*d;
c->printPretty();
b->printPretty();
std::cout << (e->remove(324)) << std::endl;
c->printPretty();
*b=*d;
std::cout << (c->remove(499)) << std::endl;
std::cout << (c->remove(108)) << std::endl;
*c=*b;
std::cout << (b->remove(463)) << std::endl;
*a=*d;
std::cout << (d->insert(324)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
*e=*a;
*d=*c;
std::cout << (d->insert(98)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
d->printPretty();
std::cout << (b->remove(324)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
*e=*a;
std::cout << (e->remove(48)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->insert(409)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
e->printPretty();
std::cout << (d->remove(409)) << std::endl;
a->printPretty();
std::cout << (a->insert(431)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
b->printPretty();
std::cout << (b->insert(108)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (e->insert(413)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
a->printPretty();
std::cout << (e->insert(413)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
std::cout << (c->remove(409)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
e->printPretty();
c->printPretty();
*a=*c;
*e=*b;
*c=*a;
std::cout << (a->remove(491)) << std::endl;
std::cout << (b->remove(108)) << std::endl;
a->printPretty();
std::cout << (a->insert(376)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (e->remove(208)) << std::endl;
std::cout << (d->insert(98)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
a->printPretty();
std::cout << (e->remove(108)) << std::endl;
c->printPretty();
std::cout << (c->insert(253)) << std::endl;
*a=*e;
std::cout << (b->remove(231)) << std::endl;
*c=*e;
std::cout << (b->insert(470)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
std::cout << (b->insert(242)) << std::endl;
*b=*b;
*b=*a;
*e=*c;
*a=*b;
std::cout << (c->remove(101)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (a->remove(37)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
std::cout << (d->remove(98)) << std::endl;
*a=*d;
std::cout << (d->remove(192)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
std::cout << (c->insert(206)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
a->printPretty();
std::cout << (b->insert(177)) << std::endl;
*d=*e;
std::cout << (b->remove(177)) << std::endl;
std::cout << (d->insert(18)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
b->printPretty();
std::cout << (b->remove(470)) << std::endl;
std::cout << (e->insert(76)) << std::endl;
std::cout << (e->remove(76)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
std::cout << (d->remove(18)) << std::endl;
*b=*a;
std::cout << (a->remove(108)) << std::endl;
c->printPretty();
*a=*a;
a->printPretty();
std::cout << (d->insert(410)) << std::endl;
std::cout << (c->insert(80)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
a->printPretty();
std::cout << (e->insert(248)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
*a=*c;
*a=*a;
std::cout << (b->insert(236)) << std::endl;
std::cout << (b->insert(324)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (b->remove(236)) << std::endl;
*e=*e;
std::cout << (b->insert(18)) << std::endl;
d->printPretty();
std::cout << (b->remove(167)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
std::cout << (e->insert(248)) << std::endl;
std::cout << (e->remove(201)) << std::endl;
std::cout << (e->insert(248)) << std::endl;
c->printPretty();
std::cout << (c->insert(220)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
*a=*d;
std::cout << (b->insert(286)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
a->printPretty();
e->printPretty();
d->printPretty();
std::cout << (a->remove(185)) << std::endl;
a->printPretty();
std::cout << (a->insert(423)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (a->insert(339)) << std::endl;
a->printPretty();
std::cout << (a->insert(339)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
std::cout << (d->remove(91)) << std::endl;
*a=*a;
*d=*c;
std::cout << (d->insert(220)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
*d=*a;
std::cout << (e->remove(421)) << std::endl;
c->printPretty();
*a=*c;
c->printPretty();
std::cout << (d->remove(143)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
*e=*d;
std::cout << (a->remove(405)) << std::endl;
std::cout << (c->insert(220)) << std::endl;
std::cout << (c->insert(220)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
b->printPretty();
std::cout << (e->insert(423)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (c->insert(220)) << std::endl;
std::cout << (c->remove(220)) << std::endl;
*b=*e;
std::cout << (a->remove(448)) << std::endl;
std::cout << (e->insert(272)) << std::endl;
std::cout << (c->remove(66)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
*c=*b;
std::cout << (b->insert(339)) << std::endl;
c->printPretty();
std::cout << (d->remove(339)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
std::cout << (b->insert(423)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
c->printPretty();
std::cout << (d->insert(232)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (c->remove(89)) << std::endl;
*a=*d;
*a=*b;
std::cout << (c->remove(180)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
std::cout << (d->insert(117)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (c->remove(204)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (e->insert(242)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
std::cout << (c->insert(333)) << std::endl;
*a=*a;
std::cout << (a->insert(272)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
e->printPretty();
std::cout << (c->insert(445)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
std::cout << (d->insert(296)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(240)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (b->remove(382)) << std::endl;
e->printPretty();
std::cout << (a->remove(112)) << std::endl;
*a=*d;
std::cout << (b->insert(235)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
std::cout << (d->remove(296)) << std::endl;
std::cout << (e->insert(272)) << std::endl;
*d=*e;
std::cout << (d->insert(32)) << std::endl;
std::cout << (e->remove(269)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (b->remove(353)) << std::endl;
std::cout << (e->remove(272)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (a->insert(87)) << std::endl;
e->printPretty();
*b=*a;
*c=*b;
c->printPretty();
a->printPretty();
std::cout << (a->insert(296)) << std::endl;
*e=*a;
*c=*c;
std::cout << (a->insert(413)) << std::endl;
std::cout << (a->insert(87)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
b->printPretty();
std::cout << (c->insert(117)) << std::endl;
std::cout << (b->insert(296)) << std::endl;
*e=*e;
std::cout << (d->insert(195)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
*b=*d;
std::cout << (e->remove(53)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
std::cout << (a->remove(49)) << std::endl;
std::cout << (a->insert(457)) << std::endl;
std::cout << (d->insert(423)) << std::endl;
std::cout << (d->remove(272)) << std::endl;
e->printPretty();
std::cout << (a->insert(325)) << std::endl;
std::cout << (a->insert(457)) << std::endl;
std::cout << (a->insert(355)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (e->remove(300)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
*a=*d;
std::cout << (c->insert(100)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
std::cout << (d->insert(65)) << std::endl;
c->printPretty();
std::cout << (d->remove(401)) << std::endl;
*d=*b;
std::cout << (b->insert(423)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
std::cout << (e->insert(393)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
*d=*b;
a->printPretty();
*c=*a;
e->printPretty();
std::cout << (d->remove(481)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
d->printPretty();
d->printPretty();
*e=*d;
c->printPretty();
c->printPretty();
std::cout << (a->remove(143)) << std::endl;
*b=*e;
d->printPretty();
*e=*d;
*b=*d;
*d=*b;
std::cout << (c->remove(32)) << std::endl;
std::cout << (b->remove(214)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
*d=*c;
*e=*b;
b->printPretty();
std::cout << (b->insert(423)) << std::endl;
*c=*e;
a->printPretty();
std::cout << (d->remove(423)) << std::endl;
std::cout << (c->remove(171)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
std::cout << (c->remove(360)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->insert(399)) << std::endl;
std::cout << (c->insert(107)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
e->printPretty();
std::cout << (a->remove(339)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
std::cout << (e->remove(356)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
*c=*c;
std::cout << (b->insert(272)) << std::endl;
std::cout << (a->insert(366)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (e->insert(272)) << std::endl;
std::cout << (c->remove(71)) << std::endl;
d->printPretty();
std::cout << (c->insert(423)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (b->remove(138)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
*a=*e;
std::cout << (b->remove(431)) << std::endl;
std::cout << (b->remove(71)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
std::cout << (b->remove(272)) << std::endl;
b->printPretty();
*b=*b;
std::cout << (c->insert(32)) << std::endl;
std::cout << (a->insert(96)) << std::endl;
std::cout << (e->remove(341)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (c->remove(423)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
std::cout << (c->remove(123)) << std::endl;
std::cout << (a->insert(96)) << std::endl;
std::cout << (c->remove(258)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (e->insert(339)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->remove(431)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
std::cout << (d->remove(242)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
std::cout << (e->remove(310)) << std::endl;
std::cout << (b->insert(32)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
b->printPretty();
b->printPretty();
*c=*b;
c->printPretty();
std::cout << (e->insert(455)) << std::endl;
d->printPretty();
std::cout << (b->insert(32)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (c->remove(24)) << std::endl;
std::cout << (e->remove(442)) << std::endl;
*c=*d;
*e=*a;
a->printPretty();
std::cout << (a->remove(425)) << std::endl;
e->printPretty();
std::cout << (a->insert(195)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (c->insert(431)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
e->printPretty();
std::cout << (c->insert(203)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
d->printPretty();
*c=*c;
d->printPretty();
std::cout << (d->insert(431)) << std::endl;
std::cout << (c->insert(195)) << std::endl;
a->printPretty();
c->printPretty();
b->printPretty();
std::cout << (e->insert(195)) << std::endl;
std::cout << (b->remove(144)) << std::endl;
std::cout << (e->remove(195)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
*c=*e;
*b=*c;
std::cout << (c->remove(96)) << std::endl;
std::cout << (b->insert(423)) << std::endl;
e->printPretty();
std::cout << (d->insert(339)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
std::cout << (d->insert(423)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
*c=*c;
std::cout << (d->remove(431)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
*a=*b;
*c=*d;
std::cout << (c->remove(195)) << std::endl;
std::cout << (d->insert(146)) << std::endl;
std::cout << (d->remove(272)) << std::endl;
std::cout << (c->remove(164)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
*c=*e;
*b=*a;
std::cout << (b->insert(431)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
*b=*d;
std::cout << (a->insert(431)) << std::endl;
std::cout << (d->insert(65)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (c->remove(423)) << std::endl;
*d=*a;
std::cout << (d->remove(313)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
std::cout << (b->insert(180)) << std::endl;
std::cout << (a->remove(132)) << std::endl;
std::cout << (c->insert(64)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
*b=*c;
std::cout << (d->remove(96)) << std::endl;
std::cout << (e->remove(272)) << std::endl;
std::cout << (e->insert(456)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
*b=*e;
std::cout << (d->remove(230)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (d->remove(431)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
*c=*a;
*b=*c;
std::cout << (d->insert(355)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (a->remove(225)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
e->printPretty();
std::cout << (e->insert(423)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
std::cout << (b->insert(200)) << std::endl;
*a=*b;
std::cout << (b->insert(96)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (b->remove(431)) << std::endl;
std::cout << (a->remove(311)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
*c=*c;
std::cout << (e->insert(202)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
std::cout << (c->remove(271)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (a->insert(105)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
std::cout << (b->remove(316)) << std::endl;
*d=*d;
std::cout << (a->remove(431)) << std::endl;
std::cout << (c->insert(32)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
std::cout << (c->insert(482)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
std::cout << (a->remove(105)) << std::endl;
std::cout << (e->insert(242)) << std::endl;
*b=*d;
std::cout << (e->insert(456)) << std::endl;
std::cout << (d->remove(400)) << std::endl;
std::cout << (b->remove(353)) << std::endl;
c->printPretty();
a->printPretty();
*e=*d;
std::cout << (a->remove(453)) << std::endl;
std::cout << (c->insert(32)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
std::cout << (c->remove(406)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
*b=*a;
*b=*a;
*e=*b;
std::cout << (b->remove(484)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (c->insert(383)) << std::endl;
std::cout << (a->insert(120)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (c->insert(383)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (c->remove(383)) << std::endl;
std::cout << (e->remove(59)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
*e=*a;
std::cout << (e->remove(96)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (e->remove(21)) << std::endl;
std::cout << (b->remove(454)) << std::endl;
std::cout << (a->remove(227)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (b->insert(200)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
*c=*c;
std::cout << (c->remove(96)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
*b=*b;
std::cout << (c->remove(200)) << std::endl;
d->printPretty();
std::cout << (a->remove(200)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (e->remove(200)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (b->insert(466)) << std::endl;
std::cout << (d->remove(74)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (d->remove(95)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
*b=*e;
std::cout << (b->insert(453)) << std::endl;
*e=*c;
std::cout << (e->remove(99)) << std::endl;
*b=*a;
*a=*a;
std::cout << (a->remove(326)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
std::cout << (a->insert(123)) << std::endl;
*e=*b;
d->printPretty();
*c=*e;
b->printPretty();
*d=*c;
*c=*c;
*a=*d;
std::cout << (e->insert(397)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
a->printPretty();
std::cout << (a->remove(244)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
std::cout << (a->insert(342)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
a->printPretty();
std::cout << (e->insert(366)) << std::endl;
*b=*c;
std::cout << (c->remove(266)) << std::endl;
*d=*a;
std::cout << (d->remove(120)) << std::endl;
*d=*b;
std::cout << (d->insert(211)) << std::endl;
a->printPretty();
*a=*b;
*e=*a;
d->printPretty();
std::cout << (a->insert(120)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
return 0;
}
