#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(111)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
std::cout << (a->insert(111)) << std::endl;
*b=*a;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (b->insert(111)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->remove(257)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (d->insert(327)) << std::endl;
*b=*b;
*c=*c;
a->printPretty();
*b=*c;
e->printPretty();
std::cout << (e->remove(143)) << std::endl;
c->printPretty();
std::cout << (a->insert(458)) << std::endl;
e->printPretty();
std::cout << (a->remove(447)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
std::cout << (d->remove(406)) << std::endl;
*b=*a;
std::cout << (d->remove(327)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (b->remove(201)) << std::endl;
std::cout << (d->insert(269)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (e->insert(314)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
a->printPretty();
a->printPretty();
*d=*c;
std::cout << (b->insert(178)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
c->printPretty();
*e=*d;
*b=*a;
std::cout << (b->remove(113)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
*c=*b;
std::cout << (c->remove(6)) << std::endl;
*a=*a;
*d=*d;
*b=*c;
std::cout << (a->remove(91)) << std::endl;
std::cout << (c->remove(85)) << std::endl;
*b=*a;
std::cout << (d->remove(332)) << std::endl;
d->printPretty();
*e=*a;
std::cout << (a->insert(6)) << std::endl;
a->printPretty();
std::cout << (d->remove(44)) << std::endl;
*e=*e;
std::cout << (d->insert(31)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
e->printPretty();
e->printPretty();
b->printPretty();
std::cout << (e->insert(6)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
*c=*d;
*d=*b;
std::cout << (b->insert(295)) << std::endl;
d->printPretty();
std::cout << (d->insert(420)) << std::endl;
*e=*c;
std::cout << (c->remove(296)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
std::cout << (b->remove(68)) << std::endl;
std::cout << (b->remove(20)) << std::endl;
*e=*b;
std::cout << (c->insert(31)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
std::cout << (b->remove(420)) << std::endl;
std::cout << (e->remove(6)) << std::endl;
std::cout << (c->insert(46)) << std::endl;
a->printPretty();
c->printPretty();
*e=*e;
*c=*d;
*d=*c;
std::cout << (c->insert(6)) << std::endl;
*b=*e;
std::cout << (e->remove(357)) << std::endl;
*d=*a;
std::cout << (e->remove(420)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (a->insert(269)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (a->remove(269)) << std::endl;
std::cout << (b->remove(420)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
*e=*b;
std::cout << (b->remove(181)) << std::endl;
std::cout << (a->insert(169)) << std::endl;
std::cout << (e->remove(295)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
std::cout << (c->insert(420)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
b->printPretty();
std::cout << (a->insert(182)) << std::endl;
e->printPretty();
std::cout << (a->insert(217)) << std::endl;
d->printPretty();
std::cout << (b->insert(295)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
std::cout << (a->insert(217)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
*c=*d;
std::cout << (e->remove(265)) << std::endl;
std::cout << (a->insert(169)) << std::endl;
*b=*c;
std::cout << (e->insert(242)) << std::endl;
*d=*d;
std::cout << (e->remove(242)) << std::endl;
std::cout << (a->remove(335)) << std::endl;
std::cout << (c->insert(6)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
*a=*c;
std::cout << (a->insert(6)) << std::endl;
*d=*c;
std::cout << (a->insert(412)) << std::endl;
std::cout << (c->insert(232)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
a->printPretty();
std::cout << (a->remove(126)) << std::endl;
*a=*c;
std::cout << (c->insert(201)) << std::endl;
std::cout << (a->remove(121)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
*e=*e;
*c=*e;
std::cout << (d->remove(26)) << std::endl;
*e=*a;
std::cout << (e->insert(437)) << std::endl;
std::cout << (b->insert(496)) << std::endl;
c->printPretty();
*e=*b;
c->printPretty();
*d=*a;
*e=*e;
*a=*e;
*e=*b;
*e=*d;
e->printPretty();
std::cout << (d->remove(6)) << std::endl;
b->printPretty();
*a=*a;
*a=*c;
*e=*b;
*b=*c;
std::cout << (e->remove(496)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (e->insert(242)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
std::cout << (d->insert(443)) << std::endl;
*c=*d;
std::cout << (d->insert(443)) << std::endl;
*e=*e;
std::cout << (b->remove(251)) << std::endl;
*e=*a;
*d=*e;
b->printPretty();
*c=*d;
std::cout << (a->remove(15)) << std::endl;
a->printPretty();
std::cout << (a->insert(104)) << std::endl;
std::cout << (d->remove(64)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (d->remove(284)) << std::endl;
b->printPretty();
std::cout << (c->insert(244)) << std::endl;
c->printPretty();
std::cout << (b->insert(77)) << std::endl;
*d=*e;
std::cout << (b->insert(274)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
*a=*e;
std::cout << (c->remove(244)) << std::endl;
b->printPretty();
std::cout << (b->insert(202)) << std::endl;
*b=*e;
d->printPretty();
c->printPretty();
std::cout << (c->insert(219)) << std::endl;
*a=*e;
*b=*b;
std::cout << (e->insert(439)) << std::endl;
a->printPretty();
std::cout << (d->insert(232)) << std::endl;
*a=*c;
std::cout << (d->remove(232)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->insert(439)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (d->remove(218)) << std::endl;
std::cout << (a->insert(219)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (e->insert(123)) << std::endl;
std::cout << (a->insert(219)) << std::endl;
std::cout << (d->insert(441)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
*a=*c;
std::cout << (c->insert(219)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
b->printPretty();
std::cout << (b->insert(69)) << std::endl;
std::cout << (e->remove(288)) << std::endl;
std::cout << (e->remove(288)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
*a=*d;
*d=*c;
e->printPretty();
c->printPretty();
std::cout << (b->remove(223)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
e->printPretty();
*e=*b;
b->printPretty();
std::cout << (c->insert(219)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
std::cout << (c->remove(414)) << std::endl;
std::cout << (a->remove(338)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (a->remove(270)) << std::endl;
c->printPretty();
std::cout << (d->insert(365)) << std::endl;
std::cout << (c->insert(219)) << std::endl;
*d=*d;
std::cout << (c->remove(219)) << std::endl;
std::cout << (c->remove(262)) << std::endl;
std::cout << (e->insert(139)) << std::endl;
std::cout << (b->insert(46)) << std::endl;
c->printPretty();
std::cout << (c->insert(276)) << std::endl;
std::cout << (c->remove(319)) << std::endl;
*e=*d;
std::cout << (d->insert(63)) << std::endl;
std::cout << (d->remove(262)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (b->remove(321)) << std::endl;
std::cout << (d->remove(365)) << std::endl;
e->printPretty();
std::cout << (c->insert(276)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (c->insert(47)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (c->insert(50)) << std::endl;
std::cout << (c->remove(50)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
std::cout << (e->insert(421)) << std::endl;
std::cout << (e->remove(421)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
e->printPretty();
a->printPretty();
d->printPretty();
d->printPretty();
std::cout << (b->insert(405)) << std::endl;
e->printPretty();
std::cout << (b->insert(305)) << std::endl;
b->printPretty();
*e=*e;
std::cout << (c->insert(48)) << std::endl;
c->printPretty();
std::cout << (d->insert(63)) << std::endl;
a->printPretty();
std::cout << (c->insert(48)) << std::endl;
std::cout << (b->remove(256)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
std::cout << (c->remove(276)) << std::endl;
std::cout << (e->insert(323)) << std::endl;
std::cout << (d->remove(63)) << std::endl;
d->printPretty();
std::cout << (c->insert(308)) << std::endl;
*c=*d;
*d=*b;
std::cout << (e->remove(81)) << std::endl;
*a=*b;
std::cout << (d->remove(405)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
*e=*a;
std::cout << (b->remove(405)) << std::endl;
b->printPretty();
std::cout << (d->insert(235)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
std::cout << (d->remove(493)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
std::cout << (e->remove(313)) << std::endl;
std::cout << (c->remove(7)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
std::cout << (e->insert(405)) << std::endl;
c->printPretty();
std::cout << (a->remove(455)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
d->printPretty();
std::cout << (a->insert(452)) << std::endl;
*c=*a;
c->printPretty();
std::cout << (d->remove(453)) << std::endl;
d->printPretty();
std::cout << (c->remove(452)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
std::cout << (b->remove(137)) << std::endl;
d->printPretty();
std::cout << (e->insert(337)) << std::endl;
std::cout << (d->remove(46)) << std::endl;
*c=*b;
std::cout << (c->remove(381)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
*b=*d;
std::cout << (b->insert(414)) << std::endl;
e->printPretty();
*b=*b;
c->printPretty();
std::cout << (e->remove(46)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (a->remove(46)) << std::endl;
e->printPretty();
std::cout << (d->insert(273)) << std::endl;
std::cout << (a->insert(25)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (d->remove(235)) << std::endl;
std::cout << (d->insert(175)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
e->printPretty();
std::cout << (e->insert(199)) << std::endl;
std::cout << (e->remove(270)) << std::endl;
e->printPretty();
std::cout << (b->insert(30)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
*a=*b;
std::cout << (b->remove(305)) << std::endl;
a->printPretty();
std::cout << (e->remove(405)) << std::endl;
*e=*a;
std::cout << (a->insert(73)) << std::endl;
*d=*c;
std::cout << (c->insert(167)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
std::cout << (e->remove(267)) << std::endl;
b->printPretty();
std::cout << (c->remove(167)) << std::endl;
*e=*a;
*e=*a;
*d=*d;
std::cout << (b->insert(149)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
*a=*a;
b->printPretty();
*b=*e;
std::cout << (d->remove(375)) << std::endl;
std::cout << (b->insert(30)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
*a=*c;
std::cout << (d->remove(371)) << std::endl;
std::cout << (b->remove(190)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
d->printPretty();
std::cout << (d->insert(305)) << std::endl;
std::cout << (a->insert(361)) << std::endl;
*b=*c;
b->printPretty();
std::cout << (a->insert(305)) << std::endl;
e->printPretty();
std::cout << (b->remove(198)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
a->printPretty();
std::cout << (b->insert(414)) << std::endl;
std::cout << (b->remove(414)) << std::endl;
c->printPretty();
std::cout << (c->insert(186)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
c->printPretty();
std::cout << (b->insert(212)) << std::endl;
std::cout << (e->remove(30)) << std::endl;
std::cout << (a->insert(424)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
*d=*c;
c->printPretty();
*d=*c;
std::cout << (b->remove(112)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
*d=*b;
std::cout << (d->remove(305)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
*a=*c;
std::cout << (b->insert(212)) << std::endl;
b->printPretty();
std::cout << (b->insert(55)) << std::endl;
*c=*a;
std::cout << (e->remove(73)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (c->insert(305)) << std::endl;
*d=*e;
std::cout << (d->remove(305)) << std::endl;
std::cout << (c->remove(391)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
*a=*e;
*b=*e;
b->printPretty();
a->printPretty();
std::cout << (b->insert(43)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
d->printPretty();
std::cout << (b->insert(35)) << std::endl;
std::cout << (e->insert(393)) << std::endl;
*d=*d;
*c=*b;
*e=*e;
std::cout << (c->remove(212)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (a->remove(67)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
*e=*b;
*b=*c;
*a=*c;
*b=*d;
std::cout << (d->insert(399)) << std::endl;
std::cout << (b->remove(43)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
std::cout << (a->insert(43)) << std::endl;
std::cout << (a->remove(110)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
std::cout << (d->insert(292)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
std::cout << (a->insert(254)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (d->insert(389)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
c->printPretty();
*a=*c;
std::cout << (d->remove(13)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (c->remove(414)) << std::endl;
std::cout << (c->insert(305)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
e->printPretty();
std::cout << (c->insert(305)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
e->printPretty();
std::cout << (c->insert(374)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->remove(431)) << std::endl;
d->printPretty();
std::cout << (a->remove(237)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
c->printPretty();
std::cout << (a->remove(3)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
*b=*b;
std::cout << (c->insert(399)) << std::endl;
*e=*a;
std::cout << (b->insert(457)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (d->remove(292)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
c->printPretty();
std::cout << (b->remove(294)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (c->remove(190)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (c->remove(82)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
*c=*a;
std::cout << (c->insert(414)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (e->remove(414)) << std::endl;
std::cout << (d->insert(389)) << std::endl;
std::cout << (d->insert(389)) << std::endl;
std::cout << (b->remove(414)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
std::cout << (d->remove(43)) << std::endl;
*a=*c;
d->printPretty();
a->printPretty();
d->printPretty();
std::cout << (b->remove(167)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
std::cout << (d->remove(120)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
std::cout << (c->remove(115)) << std::endl;
*a=*c;
std::cout << (a->insert(165)) << std::endl;
a->printPretty();
std::cout << (e->insert(401)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
e->printPretty();
std::cout << (c->remove(414)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->insert(85)) << std::endl;
d->printPretty();
std::cout << (c->remove(87)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
std::cout << (e->remove(401)) << std::endl;
*b=*a;
std::cout << (e->insert(366)) << std::endl;
std::cout << (b->remove(165)) << std::endl;
c->printPretty();
e->printPretty();
b->printPretty();
std::cout << (e->remove(493)) << std::endl;
*e=*d;
std::cout << (d->insert(390)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
std::cout << (a->insert(291)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
*e=*a;
std::cout << (b->remove(331)) << std::endl;
*b=*c;
*a=*b;
std::cout << (b->insert(491)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
*c=*e;
*a=*a;
d->printPretty();
std::cout << (c->insert(291)) << std::endl;
*e=*d;
std::cout << (d->remove(389)) << std::endl;
std::cout << (c->remove(289)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
*b=*a;
std::cout << (d->remove(182)) << std::endl;
c->printPretty();
d->printPretty();
b->printPretty();
std::cout << (b->remove(300)) << std::endl;
std::cout << (d->remove(21)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
b->printPretty();
*e=*e;
*e=*a;
std::cout << (a->remove(300)) << std::endl;
std::cout << (c->remove(71)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
*a=*b;
std::cout << (d->remove(414)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
*c=*c;
std::cout << (e->insert(300)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
*a=*d;
std::cout << (d->remove(10)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
b->printPretty();
std::cout << (d->remove(223)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
b->printPretty();
d->printPretty();
e->printPretty();
std::cout << (b->remove(406)) << std::endl;
std::cout << (d->insert(465)) << std::endl;
*b=*c;
std::cout << (a->insert(193)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (c->remove(165)) << std::endl;
std::cout << (e->remove(122)) << std::endl;
c->printPretty();
std::cout << (b->insert(102)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
a->printPretty();
std::cout << (d->insert(16)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (b->remove(165)) << std::endl;
*b=*c;
*d=*c;
std::cout << (b->remove(291)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
std::cout << (e->remove(301)) << std::endl;
std::cout << (d->insert(291)) << std::endl;
*b=*d;
std::cout << (b->insert(275)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
*c=*b;
std::cout << (b->insert(71)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
a->printPretty();
std::cout << (b->remove(291)) << std::endl;
*d=*c;
std::cout << (b->remove(321)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
d->printPretty();
std::cout << (c->remove(91)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (a->remove(151)) << std::endl;
std::cout << (b->remove(71)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
*b=*c;
*b=*d;
std::cout << (c->insert(12)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (b->insert(291)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (e->insert(300)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
std::cout << (a->insert(291)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
std::cout << (c->remove(275)) << std::endl;
*d=*a;
std::cout << (b->remove(95)) << std::endl;
std::cout << (a->remove(12)) << std::endl;
*d=*b;
std::cout << (a->insert(122)) << std::endl;
std::cout << (d->insert(275)) << std::endl;
std::cout << (b->insert(98)) << std::endl;
std::cout << (d->insert(275)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
std::cout << (d->remove(275)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
std::cout << (e->remove(383)) << std::endl;
*a=*c;
std::cout << (e->insert(289)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
return 0;
}
