#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->insert(368)) << std::endl;
std::cout << (b->insert(428)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
e->printPretty();
*a=*c;
d->printPretty();
e->printPretty();
std::cout << (b->insert(428)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (e->insert(149)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
std::cout << (b->remove(428)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
std::cout << (d->remove(349)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->insert(483)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
*a=*a;
std::cout << (c->insert(287)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (e->remove(187)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
e->printPretty();
std::cout << (c->insert(155)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
b->printPretty();
c->printPretty();
*c=*e;
std::cout << (b->insert(464)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
std::cout << (b->insert(398)) << std::endl;
*b=*e;
*e=*b;
std::cout << (e->insert(326)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
d->printPretty();
std::cout << (a->remove(441)) << std::endl;
*e=*a;
std::cout << (d->insert(269)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
std::cout << (d->remove(483)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
std::cout << (d->remove(388)) << std::endl;
std::cout << (a->remove(51)) << std::endl;
*e=*a;
d->printPretty();
c->printPretty();
*d=*a;
std::cout << (d->remove(327)) << std::endl;
b->printPretty();
std::cout << (e->remove(303)) << std::endl;
e->printPretty();
*b=*d;
b->printPretty();
std::cout << (b->insert(146)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
a->printPretty();
std::cout << (d->insert(24)) << std::endl;
*e=*c;
std::cout << (b->remove(7)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
d->printPretty();
std::cout << (a->insert(146)) << std::endl;
*b=*c;
std::cout << (b->insert(237)) << std::endl;
std::cout << (e->remove(186)) << std::endl;
*a=*a;
std::cout << (d->remove(44)) << std::endl;
*d=*b;
std::cout << (a->insert(146)) << std::endl;
e->printPretty();
std::cout << (e->remove(212)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
e->printPretty();
std::cout << (b->insert(237)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
std::cout << (b->insert(474)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (c->remove(223)) << std::endl;
std::cout << (e->remove(73)) << std::endl;
std::cout << (a->insert(141)) << std::endl;
std::cout << (d->remove(237)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (c->remove(339)) << std::endl;
*b=*b;
std::cout << (d->insert(458)) << std::endl;
std::cout << (a->remove(327)) << std::endl;
std::cout << (c->insert(50)) << std::endl;
std::cout << (b->insert(453)) << std::endl;
*b=*d;
*d=*c;
std::cout << (d->insert(452)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
*c=*e;
std::cout << (e->insert(420)) << std::endl;
std::cout << (b->insert(55)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
*e=*a;
std::cout << (e->remove(146)) << std::endl;
e->printPretty();
std::cout << (b->insert(300)) << std::endl;
std::cout << (c->insert(282)) << std::endl;
d->printPretty();
std::cout << (d->insert(452)) << std::endl;
std::cout << (b->insert(458)) << std::endl;
*a=*a;
*c=*d;
d->printPretty();
std::cout << (d->remove(298)) << std::endl;
*e=*b;
std::cout << (b->insert(55)) << std::endl;
b->printPretty();
std::cout << (d->remove(50)) << std::endl;
std::cout << (d->insert(305)) << std::endl;
std::cout << (b->insert(55)) << std::endl;
std::cout << (d->insert(305)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
*c=*e;
std::cout << (c->insert(55)) << std::endl;
a->printPretty();
std::cout << (b->remove(55)) << std::endl;
c->printPretty();
std::cout << (a->insert(141)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
*e=*d;
std::cout << (a->remove(146)) << std::endl;
*e=*b;
std::cout << (d->insert(452)) << std::endl;
c->printPretty();
std::cout << (e->insert(300)) << std::endl;
c->printPretty();
std::cout << (e->remove(300)) << std::endl;
std::cout << (e->insert(458)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (d->remove(305)) << std::endl;
*e=*a;
std::cout << (d->remove(169)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
a->printPretty();
*c=*a;
std::cout << (d->insert(9)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (c->insert(183)) << std::endl;
std::cout << (d->remove(9)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
*d=*b;
*e=*d;
a->printPretty();
*c=*e;
b->printPretty();
std::cout << (c->remove(458)) << std::endl;
d->printPretty();
std::cout << (d->remove(95)) << std::endl;
std::cout << (e->insert(120)) << std::endl;
std::cout << (d->remove(61)) << std::endl;
std::cout << (d->insert(458)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (b->remove(458)) << std::endl;
*e=*a;
std::cout << (a->insert(141)) << std::endl;
std::cout << (a->insert(141)) << std::endl;
a->printPretty();
std::cout << (d->insert(300)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
std::cout << (a->insert(210)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
b->printPretty();
b->printPretty();
e->printPretty();
std::cout << (c->insert(124)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
std::cout << (a->remove(452)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
std::cout << (e->remove(118)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
std::cout << (b->remove(338)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
std::cout << (c->remove(198)) << std::endl;
*b=*e;
d->printPretty();
*c=*c;
*d=*e;
std::cout << (b->remove(4)) << std::endl;
std::cout << (c->remove(124)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
a->printPretty();
std::cout << (a->remove(330)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
b->printPretty();
*e=*a;
*a=*e;
std::cout << (c->insert(344)) << std::endl;
std::cout << (a->remove(353)) << std::endl;
*a=*c;
std::cout << (b->insert(235)) << std::endl;
a->printPretty();
*d=*c;
*b=*c;
std::cout << (a->remove(344)) << std::endl;
std::cout << (d->remove(343)) << std::endl;
*e=*d;
std::cout << (d->insert(377)) << std::endl;
*b=*c;
std::cout << (a->insert(431)) << std::endl;
d->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(29)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
a->printPretty();
std::cout << (d->remove(360)) << std::endl;
std::cout << (a->insert(192)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (d->insert(377)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
d->printPretty();
std::cout << (a->insert(322)) << std::endl;
std::cout << (b->remove(344)) << std::endl;
c->printPretty();
std::cout << (a->insert(450)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
*d=*a;
std::cout << (d->insert(450)) << std::endl;
*e=*a;
std::cout << (a->insert(244)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
*d=*c;
std::cout << (b->insert(276)) << std::endl;
c->printPretty();
std::cout << (e->insert(192)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
c->printPretty();
*e=*d;
*c=*c;
std::cout << (c->insert(243)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
*d=*a;
*a=*d;
std::cout << (a->remove(319)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
b->printPretty();
std::cout << (a->insert(322)) << std::endl;
d->printPretty();
std::cout << (d->insert(431)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (d->insert(450)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
a->printPretty();
std::cout << (b->insert(482)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
b->printPretty();
std::cout << (b->remove(488)) << std::endl;
std::cout << (d->remove(431)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->insert(442)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
*e=*a;
std::cout << (b->insert(151)) << std::endl;
std::cout << (a->remove(490)) << std::endl;
*d=*d;
std::cout << (b->remove(299)) << std::endl;
*c=*c;
std::cout << (b->remove(238)) << std::endl;
*a=*b;
std::cout << (a->remove(372)) << std::endl;
a->printPretty();
*b=*d;
std::cout << (c->insert(53)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
*d=*d;
e->printPretty();
*e=*e;
*b=*b;
std::cout << (b->insert(154)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
std::cout << (b->remove(388)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
std::cout << (d->remove(279)) << std::endl;
b->printPretty();
*d=*c;
c->printPretty();
std::cout << (d->remove(442)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
*a=*c;
std::cout << (d->remove(480)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (a->insert(29)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
*b=*c;
std::cout << (a->remove(339)) << std::endl;
c->printPretty();
std::cout << (d->insert(378)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (c->remove(64)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
std::cout << (a->insert(75)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
e->printPretty();
std::cout << (d->insert(243)) << std::endl;
d->printPretty();
std::cout << (b->remove(243)) << std::endl;
e->printPretty();
std::cout << (b->insert(362)) << std::endl;
std::cout << (b->remove(362)) << std::endl;
std::cout << (e->insert(183)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
*a=*d;
std::cout << (a->remove(243)) << std::endl;
std::cout << (a->remove(194)) << std::endl;
std::cout << (c->remove(344)) << std::endl;
d->printPretty();
a->printPretty();
*d=*b;
*e=*b;
std::cout << (e->insert(442)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (b->remove(344)) << std::endl;
*d=*d;
std::cout << (d->insert(349)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
*d=*a;
std::cout << (b->insert(347)) << std::endl;
*b=*b;
std::cout << (c->remove(243)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (c->insert(10)) << std::endl;
std::cout << (b->remove(276)) << std::endl;
std::cout << (a->remove(479)) << std::endl;
*d=*d;
*b=*b;
std::cout << (e->remove(433)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
e->printPretty();
std::cout << (c->remove(314)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
b->printPretty();
b->printPretty();
*d=*b;
*c=*d;
std::cout << (c->insert(442)) << std::endl;
std::cout << (b->remove(197)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (a->remove(189)) << std::endl;
d->printPretty();
std::cout << (a->remove(296)) << std::endl;
e->printPretty();
*e=*b;
b->printPretty();
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (e->insert(361)) << std::endl;
std::cout << (d->remove(29)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
*c=*e;
std::cout << (d->remove(403)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (c->insert(465)) << std::endl;
a->printPretty();
std::cout << (a->remove(274)) << std::endl;
std::cout << (d->remove(442)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
*d=*e;
std::cout << (b->remove(29)) << std::endl;
std::cout << (b->remove(347)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (d->insert(227)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
std::cout << (b->remove(165)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
b->printPretty();
std::cout << (b->remove(442)) << std::endl;
b->printPretty();
std::cout << (a->insert(348)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(378)) << std::endl;
std::cout << (d->remove(347)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
*b=*b;
std::cout << (d->insert(361)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
std::cout << (d->remove(95)) << std::endl;
a->printPretty();
*b=*d;
b->printPretty();
std::cout << (d->remove(165)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
a->printPretty();
std::cout << (b->remove(165)) << std::endl;
std::cout << (d->remove(442)) << std::endl;
std::cout << (b->insert(119)) << std::endl;
*a=*a;
std::cout << (c->insert(72)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
c->printPretty();
std::cout << (a->remove(53)) << std::endl;
std::cout << (e->insert(227)) << std::endl;
*a=*e;
b->printPretty();
d->printPretty();
std::cout << (a->remove(81)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
*e=*b;
std::cout << (a->remove(28)) << std::endl;
std::cout << (c->remove(188)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (b->insert(361)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
*d=*d;
*c=*e;
std::cout << (a->insert(158)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (c->insert(361)) << std::endl;
std::cout << (b->insert(442)) << std::endl;
c->printPretty();
std::cout << (c->remove(345)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (a->remove(50)) << std::endl;
std::cout << (e->remove(248)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (a->remove(174)) << std::endl;
*c=*b;
*e=*c;
std::cout << (b->remove(29)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
std::cout << (e->insert(342)) << std::endl;
*b=*b;
std::cout << (d->remove(53)) << std::endl;
*d=*b;
std::cout << (b->remove(188)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
std::cout << (b->insert(96)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (d->insert(153)) << std::endl;
e->printPretty();
*d=*e;
*a=*a;
*a=*b;
std::cout << (c->remove(245)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (c->remove(205)) << std::endl;
*b=*a;
std::cout << (d->remove(342)) << std::endl;
std::cout << (a->remove(299)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
*b=*e;
*a=*a;
std::cout << (c->remove(53)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (a->remove(156)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
std::cout << (b->remove(304)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (a->remove(37)) << std::endl;
std::cout << (a->insert(413)) << std::endl;
std::cout << (e->insert(252)) << std::endl;
d->printPretty();
std::cout << (e->remove(67)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (c->insert(29)) << std::endl;
std::cout << (a->remove(483)) << std::endl;
d->printPretty();
std::cout << (d->insert(432)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
*c=*e;
*a=*a;
*e=*a;
*e=*e;
std::cout << (c->remove(104)) << std::endl;
c->printPretty();
std::cout << (e->insert(361)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
*c=*c;
std::cout << (a->remove(413)) << std::endl;
e->printPretty();
std::cout << (e->insert(253)) << std::endl;
*b=*e;
*d=*c;
std::cout << (e->insert(413)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->insert(302)) << std::endl;
a->printPretty();
std::cout << (b->remove(361)) << std::endl;
std::cout << (c->remove(337)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (c->remove(253)) << std::endl;
std::cout << (a->insert(160)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
*e=*c;
std::cout << (e->remove(413)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
std::cout << (a->insert(63)) << std::endl;
std::cout << (b->remove(24)) << std::endl;
a->printPretty();
std::cout << (c->insert(88)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(91)) << std::endl;
*b=*c;
std::cout << (e->remove(305)) << std::endl;
std::cout << (c->remove(88)) << std::endl;
std::cout << (c->remove(119)) << std::endl;
std::cout << (b->insert(82)) << std::endl;
d->printPretty();
std::cout << (c->remove(452)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
std::cout << (b->remove(88)) << std::endl;
std::cout << (a->remove(160)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
*e=*c;
std::cout << (c->remove(147)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
std::cout << (d->remove(252)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
std::cout << (e->insert(413)) << std::endl;
a->printPretty();
std::cout << (a->remove(63)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->remove(363)) << std::endl;
std::cout << (b->insert(82)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (a->remove(318)) << std::endl;
std::cout << (e->remove(66)) << std::endl;
*a=*d;
std::cout << (a->remove(266)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (c->insert(413)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (b->insert(66)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (c->insert(413)) << std::endl;
std::cout << (b->remove(428)) << std::endl;
std::cout << (b->remove(189)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (b->insert(488)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
*b=*d;
*c=*a;
std::cout << (c->insert(212)) << std::endl;
e->printPretty();
std::cout << (e->insert(450)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (b->insert(2)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->remove(79)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->remove(10)) << std::endl;
*e=*c;
std::cout << (d->insert(46)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
std::cout << (e->remove(453)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
std::cout << (b->remove(294)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
std::cout << (d->insert(361)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
*b=*d;
std::cout << (d->remove(422)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (e->insert(212)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (c->remove(341)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (d->remove(277)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (d->remove(449)) << std::endl;
e->printPretty();
std::cout << (e->insert(351)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (d->remove(361)) << std::endl;
*a=*d;
a->printPretty();
std::cout << (d->remove(313)) << std::endl;
*a=*b;
a->printPretty();
e->printPretty();
*c=*d;
std::cout << (e->insert(351)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
std::cout << (b->insert(162)) << std::endl;
std::cout << (b->insert(217)) << std::endl;
*a=*e;
*e=*b;
std::cout << (d->insert(91)) << std::endl;
b->printPretty();
std::cout << (d->remove(59)) << std::endl;
std::cout << (a->insert(412)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
*d=*b;
std::cout << (b->remove(467)) << std::endl;
std::cout << (e->insert(361)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (e->insert(29)) << std::endl;
b->printPretty();
a->printPretty();
c->printPretty();
std::cout << (d->remove(53)) << std::endl;
a->printPretty();
std::cout << (b->insert(46)) << std::endl;
std::cout << (c->insert(91)) << std::endl;
*e=*d;
*b=*a;
b->printPretty();
std::cout << (e->remove(46)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
d->printPretty();
std::cout << (d->insert(361)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (b->remove(361)) << std::endl;
std::cout << (c->remove(212)) << std::endl;
std::cout << (d->insert(212)) << std::endl;
std::cout << (d->remove(212)) << std::endl;
std::cout << (d->remove(225)) << std::endl;
*c=*b;
std::cout << (c->remove(53)) << std::endl;
std::cout << (d->remove(91)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
c->printPretty();
a->printPretty();
*c=*a;
*d=*e;
std::cout << (b->insert(342)) << std::endl;
std::cout << (d->remove(277)) << std::endl;
return 0;
}
