#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
b->printPretty();
std::cout << (a->remove(84)) << std::endl;
std::cout << (a->insert(50)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (c->remove(183)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
*b=*c;
*b=*c;
std::cout << (a->insert(25)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
e->printPretty();
*e=*c;
std::cout << (a->remove(50)) << std::endl;
d->printPretty();
std::cout << (e->remove(215)) << std::endl;
d->printPretty();
*a=*d;
d->printPretty();
b->printPretty();
std::cout << (c->remove(222)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
*c=*d;
std::cout << (b->insert(338)) << std::endl;
*a=*a;
std::cout << (b->insert(155)) << std::endl;
std::cout << (c->insert(398)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->insert(228)) << std::endl;
a->printPretty();
std::cout << (b->insert(155)) << std::endl;
*c=*e;
std::cout << (c->remove(374)) << std::endl;
std::cout << (e->remove(94)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
std::cout << (c->remove(71)) << std::endl;
std::cout << (b->remove(209)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
d->printPretty();
std::cout << (e->insert(88)) << std::endl;
d->printPretty();
std::cout << (e->insert(23)) << std::endl;
c->printPretty();
std::cout << (e->remove(23)) << std::endl;
std::cout << (e->remove(96)) << std::endl;
b->printPretty();
std::cout << (d->insert(158)) << std::endl;
std::cout << (e->remove(41)) << std::endl;
*c=*c;
std::cout << (d->insert(158)) << std::endl;
std::cout << (b->remove(420)) << std::endl;
b->printPretty();
a->printPretty();
e->printPretty();
std::cout << (e->insert(88)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
*e=*e;
std::cout << (a->insert(388)) << std::endl;
*d=*d;
*b=*a;
std::cout << (c->insert(342)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (e->insert(12)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (d->remove(252)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (b->insert(388)) << std::endl;
std::cout << (d->insert(75)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->insert(299)) << std::endl;
std::cout << (b->remove(388)) << std::endl;
std::cout << (d->insert(335)) << std::endl;
e->printPretty();
std::cout << (e->remove(88)) << std::endl;
std::cout << (a->remove(132)) << std::endl;
b->printPretty();
std::cout << (d->remove(388)) << std::endl;
*a=*d;
std::cout << (d->remove(129)) << std::endl;
*e=*b;
std::cout << (b->insert(206)) << std::endl;
e->printPretty();
std::cout << (e->insert(344)) << std::endl;
*b=*b;
std::cout << (c->insert(496)) << std::endl;
std::cout << (a->remove(127)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
std::cout << (a->remove(75)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
std::cout << (c->remove(496)) << std::endl;
e->printPretty();
*b=*b;
d->printPretty();
c->printPretty();
std::cout << (d->insert(22)) << std::endl;
std::cout << (d->insert(127)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
*c=*a;
std::cout << (a->insert(366)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
d->printPretty();
std::cout << (b->remove(439)) << std::endl;
std::cout << (b->remove(206)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (b->insert(262)) << std::endl;
b->printPretty();
std::cout << (e->insert(257)) << std::endl;
std::cout << (b->remove(262)) << std::endl;
*d=*d;
std::cout << (c->insert(290)) << std::endl;
std::cout << (b->remove(394)) << std::endl;
*b=*c;
std::cout << (a->remove(203)) << std::endl;
e->printPretty();
std::cout << (b->remove(290)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
std::cout << (a->remove(366)) << std::endl;
*e=*d;
*d=*d;
std::cout << (c->insert(401)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->remove(335)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
e->printPretty();
std::cout << (e->remove(314)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
*a=*a;
std::cout << (b->insert(140)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
*c=*c;
std::cout << (b->insert(67)) << std::endl;
*a=*d;
std::cout << (c->insert(401)) << std::endl;
d->printPretty();
std::cout << (c->insert(401)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (d->remove(361)) << std::endl;
d->printPretty();
std::cout << (b->insert(275)) << std::endl;
b->printPretty();
e->printPretty();
d->printPretty();
std::cout << (b->insert(500)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
*d=*e;
std::cout << (c->remove(381)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
c->printPretty();
*e=*b;
*d=*b;
std::cout << (d->remove(326)) << std::endl;
std::cout << (b->insert(67)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (a->remove(375)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (b->remove(67)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
std::cout << (a->insert(91)) << std::endl;
a->printPretty();
b->printPretty();
d->printPretty();
std::cout << (d->insert(275)) << std::endl;
std::cout << (a->remove(430)) << std::endl;
std::cout << (a->remove(429)) << std::endl;
e->printPretty();
*d=*b;
d->printPretty();
*d=*b;
e->printPretty();
std::cout << (d->insert(140)) << std::endl;
d->printPretty();
std::cout << (e->insert(233)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
std::cout << (b->insert(275)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (b->insert(140)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (a->insert(68)) << std::endl;
*b=*d;
*b=*d;
std::cout << (e->remove(394)) << std::endl;
std::cout << (d->insert(478)) << std::endl;
*e=*b;
std::cout << (d->insert(168)) << std::endl;
*b=*a;
std::cout << (e->remove(13)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
d->printPretty();
std::cout << (c->remove(119)) << std::endl;
std::cout << (a->insert(14)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
b->printPretty();
std::cout << (d->insert(375)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
std::cout << (e->remove(275)) << std::endl;
b->printPretty();
std::cout << (e->remove(10)) << std::endl;
std::cout << (b->remove(354)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (d->insert(500)) << std::endl;
*c=*d;
*b=*d;
std::cout << (d->insert(168)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
*e=*a;
std::cout << (a->remove(196)) << std::endl;
std::cout << (c->remove(360)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
*c=*b;
std::cout << (a->remove(180)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (b->remove(403)) << std::endl;
*c=*b;
std::cout << (c->remove(414)) << std::endl;
std::cout << (a->remove(68)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
std::cout << (b->remove(168)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (b->remove(275)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (e->remove(326)) << std::endl;
std::cout << (a->insert(494)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->insert(232)) << std::endl;
*d=*e;
std::cout << (b->insert(475)) << std::endl;
b->printPretty();
std::cout << (c->insert(182)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
d->printPretty();
std::cout << (e->insert(354)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (e->remove(68)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (a->remove(446)) << std::endl;
std::cout << (e->insert(180)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (d->remove(354)) << std::endl;
std::cout << (b->insert(475)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
std::cout << (d->insert(94)) << std::endl;
a->printPretty();
std::cout << (a->insert(500)) << std::endl;
std::cout << (d->remove(94)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (b->insert(26)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
e->printPretty();
std::cout << (e->insert(111)) << std::endl;
std::cout << (c->remove(417)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
c->printPretty();
std::cout << (b->remove(478)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
c->printPretty();
std::cout << (a->remove(134)) << std::endl;
*c=*b;
*e=*a;
std::cout << (a->insert(196)) << std::endl;
std::cout << (c->insert(26)) << std::endl;
a->printPretty();
std::cout << (d->insert(69)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
c->printPretty();
std::cout << (c->insert(475)) << std::endl;
std::cout << (a->insert(323)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
*d=*b;
*a=*a;
std::cout << (d->remove(500)) << std::endl;
std::cout << (a->insert(182)) << std::endl;
std::cout << (a->insert(202)) << std::endl;
std::cout << (e->remove(161)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
std::cout << (d->insert(26)) << std::endl;
d->printPretty();
std::cout << (a->insert(275)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
a->printPretty();
std::cout << (c->remove(295)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
c->printPretty();
std::cout << (c->insert(331)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
a->printPretty();
std::cout << (b->remove(26)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (d->remove(489)) << std::endl;
*e=*d;
d->printPretty();
*e=*a;
a->printPretty();
std::cout << (b->insert(409)) << std::endl;
a->printPretty();
std::cout << (d->remove(191)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
std::cout << (e->insert(108)) << std::endl;
*a=*e;
std::cout << (d->insert(45)) << std::endl;
*b=*c;
*c=*e;
std::cout << (c->remove(196)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
std::cout << (e->remove(275)) << std::endl;
d->printPretty();
e->printPretty();
b->printPretty();
std::cout << (e->remove(478)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
d->printPretty();
std::cout << (d->remove(34)) << std::endl;
std::cout << (c->insert(54)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
*b=*b;
std::cout << (b->remove(375)) << std::endl;
std::cout << (b->insert(475)) << std::endl;
c->printPretty();
std::cout << (c->insert(33)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (c->remove(139)) << std::endl;
*c=*a;
std::cout << (b->insert(26)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
*e=*c;
d->printPretty();
d->printPretty();
std::cout << (e->remove(379)) << std::endl;
*e=*b;
std::cout << (b->insert(500)) << std::endl;
*c=*d;
a->printPretty();
*a=*a;
std::cout << (e->remove(47)) << std::endl;
std::cout << (a->insert(396)) << std::endl;
std::cout << (c->remove(45)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
b->printPretty();
std::cout << (e->insert(331)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
c->printPretty();
std::cout << (a->remove(108)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->remove(112)) << std::endl;
std::cout << (d->insert(45)) << std::endl;
e->printPretty();
std::cout << (d->insert(45)) << std::endl;
std::cout << (d->insert(286)) << std::endl;
*c=*b;
std::cout << (c->remove(124)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
*d=*b;
std::cout << (e->insert(26)) << std::endl;
std::cout << (c->insert(49)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->insert(49)) << std::endl;
std::cout << (d->remove(461)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
c->printPretty();
std::cout << (e->insert(26)) << std::endl;
b->printPretty();
std::cout << (e->insert(216)) << std::endl;
c->printPretty();
e->printPretty();
*a=*c;
*b=*e;
std::cout << (d->remove(42)) << std::endl;
*c=*a;
std::cout << (a->remove(288)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
a->printPretty();
std::cout << (a->insert(26)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
std::cout << (e->remove(132)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->remove(500)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
*a=*d;
std::cout << (e->remove(60)) << std::endl;
d->printPretty();
std::cout << (e->remove(26)) << std::endl;
*b=*d;
std::cout << (a->remove(57)) << std::endl;
std::cout << (d->remove(385)) << std::endl;
*e=*b;
std::cout << (d->insert(112)) << std::endl;
std::cout << (e->insert(182)) << std::endl;
a->printPretty();
*a=*d;
*d=*a;
std::cout << (a->insert(473)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
d->printPretty();
std::cout << (c->insert(44)) << std::endl;
*b=*c;
c->printPretty();
*e=*b;
std::cout << (a->remove(432)) << std::endl;
d->printPretty();
std::cout << (c->insert(331)) << std::endl;
std::cout << (d->remove(51)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (c->remove(77)) << std::endl;
*e=*a;
std::cout << (d->insert(475)) << std::endl;
a->printPretty();
std::cout << (e->insert(352)) << std::endl;
*d=*c;
std::cout << (b->insert(104)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
*a=*a;
std::cout << (d->insert(283)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (b->remove(237)) << std::endl;
std::cout << (b->insert(475)) << std::endl;
std::cout << (e->remove(435)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (b->insert(37)) << std::endl;
*c=*e;
std::cout << (d->insert(300)) << std::endl;
std::cout << (b->remove(192)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
*d=*c;
std::cout << (e->remove(352)) << std::endl;
a->printPretty();
std::cout << (e->remove(331)) << std::endl;
c->printPretty();
std::cout << (a->remove(113)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
*b=*d;
d->printPretty();
*d=*d;
std::cout << (a->remove(479)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
c->printPretty();
std::cout << (c->remove(74)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (c->insert(91)) << std::endl;
std::cout << (c->insert(26)) << std::endl;
e->printPretty();
std::cout << (b->insert(473)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (c->remove(327)) << std::endl;
*b=*d;
std::cout << (c->insert(352)) << std::endl;
std::cout << (c->remove(8)) << std::endl;
b->printPretty();
std::cout << (a->remove(112)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->insert(370)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
a->printPretty();
std::cout << (d->remove(1)) << std::endl;
b->printPretty();
e->printPretty();
*c=*d;
std::cout << (c->remove(477)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
std::cout << (a->remove(331)) << std::endl;
std::cout << (a->remove(451)) << std::endl;
*b=*e;
e->printPretty();
std::cout << (c->insert(352)) << std::endl;
std::cout << (e->remove(431)) << std::endl;
*a=*d;
std::cout << (b->insert(82)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(500)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
b->printPretty();
std::cout << (e->remove(71)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(82)) << std::endl;
std::cout << (d->insert(52)) << std::endl;
std::cout << (b->remove(288)) << std::endl;
std::cout << (e->remove(26)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
*a=*e;
std::cout << (c->remove(352)) << std::endl;
std::cout << (a->insert(473)) << std::endl;
std::cout << (e->insert(475)) << std::endl;
std::cout << (a->remove(500)) << std::endl;
e->printPretty();
std::cout << (a->insert(188)) << std::endl;
std::cout << (d->insert(212)) << std::endl;
*e=*e;
e->printPretty();
std::cout << (d->insert(138)) << std::endl;
*c=*c;
b->printPretty();
a->printPretty();
std::cout << (c->remove(171)) << std::endl;
c->printPretty();
std::cout << (d->insert(181)) << std::endl;
a->printPretty();
std::cout << (d->insert(146)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
*d=*d;
std::cout << (c->insert(475)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
std::cout << (d->remove(146)) << std::endl;
std::cout << (e->insert(31)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
*d=*c;
std::cout << (b->insert(11)) << std::endl;
e->printPretty();
std::cout << (c->remove(402)) << std::endl;
*e=*b;
std::cout << (b->remove(473)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
*b=*e;
a->printPretty();
b->printPretty();
std::cout << (a->insert(112)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
a->printPretty();
std::cout << (d->insert(112)) << std::endl;
a->printPretty();
std::cout << (e->insert(195)) << std::endl;
*c=*c;
d->printPretty();
*d=*e;
std::cout << (e->insert(473)) << std::endl;
d->printPretty();
std::cout << (c->remove(239)) << std::endl;
a->printPretty();
std::cout << (c->insert(112)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
c->printPretty();
std::cout << (b->insert(82)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (e->insert(296)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
e->printPretty();
std::cout << (e->remove(195)) << std::endl;
*d=*d;
c->printPretty();
e->printPretty();
d->printPretty();
std::cout << (d->remove(112)) << std::endl;
a->printPretty();
std::cout << (e->insert(296)) << std::endl;
*c=*a;
std::cout << (a->insert(112)) << std::endl;
d->printPretty();
std::cout << (c->remove(112)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (e->insert(493)) << std::endl;
*c=*a;
b->printPretty();
c->printPretty();
std::cout << (d->remove(26)) << std::endl;
d->printPretty();
std::cout << (e->insert(356)) << std::endl;
b->printPretty();
*a=*c;
*b=*e;
std::cout << (c->remove(108)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (e->remove(38)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
std::cout << (e->remove(493)) << std::endl;
std::cout << (d->insert(11)) << std::endl;
e->printPretty();
std::cout << (e->remove(105)) << std::endl;
e->printPretty();
std::cout << (c->insert(184)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
*c=*d;
std::cout << (e->remove(82)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (b->remove(82)) << std::endl;
std::cout << (b->remove(55)) << std::endl;
*c=*c;
*b=*d;
*b=*d;
std::cout << (b->remove(195)) << std::endl;
a->printPretty();
d->printPretty();
d->printPretty();
*a=*a;
d->printPretty();
std::cout << (e->insert(11)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
*d=*d;
std::cout << (c->insert(11)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (e->remove(51)) << std::endl;
std::cout << (e->insert(120)) << std::endl;
b->printPretty();
std::cout << (c->insert(76)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
std::cout << (c->remove(195)) << std::endl;
b->printPretty();
c->printPretty();
*c=*d;
std::cout << (d->insert(387)) << std::endl;
std::cout << (e->insert(120)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (c->remove(247)) << std::endl;
std::cout << (a->remove(108)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (b->remove(111)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
std::cout << (a->insert(337)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(473)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
*d=*c;
return 0;
}
