#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (b->remove(303)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (b->insert(331)) << std::endl;
std::cout << (c->insert(398)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
std::cout << (a->insert(109)) << std::endl;
*d=*e;
*d=*d;
std::cout << (c->remove(398)) << std::endl;
*a=*e;
*e=*a;
c->printPretty();
*a=*d;
*b=*b;
std::cout << (e->insert(130)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
std::cout << (b->insert(387)) << std::endl;
std::cout << (e->remove(130)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->remove(30)) << std::endl;
std::cout << (e->insert(126)) << std::endl;
std::cout << (a->remove(270)) << std::endl;
*a=*e;
std::cout << (c->remove(70)) << std::endl;
*d=*a;
d->printPretty();
b->printPretty();
*a=*a;
b->printPretty();
std::cout << (b->insert(387)) << std::endl;
std::cout << (c->insert(73)) << std::endl;
d->printPretty();
std::cout << (d->insert(126)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
c->printPretty();
std::cout << (c->remove(73)) << std::endl;
d->printPretty();
std::cout << (d->insert(57)) << std::endl;
std::cout << (e->insert(282)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
*b=*e;
std::cout << (c->insert(32)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
std::cout << (b->insert(282)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
a->printPretty();
c->printPretty();
c->printPretty();
std::cout << (b->remove(203)) << std::endl;
*c=*d;
std::cout << (a->insert(152)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
std::cout << (e->insert(126)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
e->printPretty();
std::cout << (a->remove(312)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
std::cout << (e->insert(126)) << std::endl;
std::cout << (e->insert(126)) << std::endl;
*c=*d;
e->printPretty();
c->printPretty();
std::cout << (b->insert(282)) << std::endl;
d->printPretty();
std::cout << (d->remove(239)) << std::endl;
std::cout << (e->remove(121)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
*d=*e;
std::cout << (d->remove(362)) << std::endl;
e->printPretty();
*b=*e;
e->printPretty();
std::cout << (c->remove(101)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
std::cout << (d->insert(22)) << std::endl;
e->printPretty();
std::cout << (e->insert(182)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
*d=*d;
std::cout << (d->insert(160)) << std::endl;
b->printPretty();
std::cout << (b->remove(70)) << std::endl;
std::cout << (b->insert(66)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
c->printPretty();
std::cout << (a->insert(152)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
*a=*b;
std::cout << (d->insert(126)) << std::endl;
std::cout << (e->remove(126)) << std::endl;
*c=*e;
c->printPretty();
std::cout << (a->insert(126)) << std::endl;
b->printPretty();
c->printPretty();
e->printPretty();
std::cout << (e->remove(265)) << std::endl;
std::cout << (d->remove(452)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
*a=*d;
std::cout << (b->insert(126)) << std::endl;
std::cout << (e->insert(182)) << std::endl;
std::cout << (d->insert(177)) << std::endl;
*b=*e;
e->printPretty();
*a=*a;
std::cout << (a->insert(179)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (b->insert(182)) << std::endl;
b->printPretty();
std::cout << (d->insert(1)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (c->insert(313)) << std::endl;
a->printPretty();
std::cout << (b->insert(248)) << std::endl;
a->printPretty();
std::cout << (e->insert(155)) << std::endl;
c->printPretty();
std::cout << (b->insert(248)) << std::endl;
std::cout << (b->remove(337)) << std::endl;
std::cout << (d->insert(89)) << std::endl;
std::cout << (e->insert(497)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (a->insert(432)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
std::cout << (e->insert(497)) << std::endl;
d->printPretty();
std::cout << (b->remove(377)) << std::endl;
d->printPretty();
std::cout << (e->insert(310)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (a->insert(46)) << std::endl;
*c=*c;
std::cout << (a->insert(105)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (b->remove(177)) << std::endl;
*c=*a;
std::cout << (d->remove(435)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
e->printPretty();
std::cout << (e->remove(86)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (b->remove(160)) << std::endl;
*d=*a;
std::cout << (b->insert(391)) << std::endl;
std::cout << (b->insert(147)) << std::endl;
std::cout << (e->insert(313)) << std::endl;
std::cout << (e->insert(47)) << std::endl;
std::cout << (e->remove(313)) << std::endl;
*e=*e;
std::cout << (c->remove(234)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
std::cout << (d->remove(170)) << std::endl;
d->printPretty();
*e=*b;
std::cout << (d->remove(160)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
b->printPretty();
std::cout << (a->insert(126)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
e->printPretty();
std::cout << (b->remove(414)) << std::endl;
std::cout << (a->insert(160)) << std::endl;
std::cout << (b->remove(425)) << std::endl;
std::cout << (b->insert(145)) << std::endl;
std::cout << (b->remove(285)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
std::cout << (e->remove(73)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
std::cout << (b->insert(230)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (c->remove(91)) << std::endl;
std::cout << (e->insert(22)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
std::cout << (d->remove(429)) << std::endl;
std::cout << (a->remove(160)) << std::endl;
e->printPretty();
d->printPretty();
*d=*b;
std::cout << (a->remove(228)) << std::endl;
*e=*b;
std::cout << (e->remove(46)) << std::endl;
std::cout << (d->remove(21)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (e->insert(493)) << std::endl;
std::cout << (d->insert(105)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->insert(375)) << std::endl;
std::cout << (b->insert(126)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
*d=*e;
std::cout << (a->remove(89)) << std::endl;
std::cout << (d->remove(436)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (b->remove(89)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (e->insert(373)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
std::cout << (c->insert(432)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
d->printPretty();
std::cout << (a->remove(105)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
c->printPretty();
std::cout << (a->insert(9)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
std::cout << (e->insert(89)) << std::endl;
e->printPretty();
std::cout << (b->remove(147)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (b->insert(144)) << std::endl;
std::cout << (a->insert(9)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (d->insert(432)) << std::endl;
*d=*c;
d->printPretty();
e->printPretty();
*a=*b;
std::cout << (a->insert(426)) << std::endl;
std::cout << (d->insert(89)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (c->insert(347)) << std::endl;
std::cout << (e->insert(420)) << std::endl;
*d=*c;
*c=*d;
std::cout << (a->insert(353)) << std::endl;
std::cout << (d->remove(352)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (b->remove(123)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (e->remove(89)) << std::endl;
std::cout << (e->remove(392)) << std::endl;
std::cout << (e->insert(238)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
std::cout << (e->insert(78)) << std::endl;
c->printPretty();
std::cout << (b->insert(119)) << std::endl;
c->printPretty();
*d=*c;
std::cout << (e->remove(148)) << std::endl;
d->printPretty();
std::cout << (c->insert(432)) << std::endl;
c->printPretty();
std::cout << (d->remove(113)) << std::endl;
*a=*a;
std::cout << (c->remove(269)) << std::endl;
*b=*e;
std::cout << (b->remove(243)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
*e=*c;
c->printPretty();
*d=*b;
std::cout << (e->insert(105)) << std::endl;
std::cout << (d->remove(132)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->remove(389)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (c->insert(22)) << std::endl;
std::cout << (a->remove(18)) << std::endl;
*b=*b;
std::cout << (a->insert(194)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
std::cout << (a->remove(230)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
*d=*b;
std::cout << (a->insert(224)) << std::endl;
*e=*c;
c->printPretty();
std::cout << (e->insert(300)) << std::endl;
*b=*a;
std::cout << (b->insert(245)) << std::endl;
*b=*a;
std::cout << (e->remove(22)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
std::cout << (c->remove(182)) << std::endl;
c->printPretty();
std::cout << (d->remove(436)) << std::endl;
std::cout << (a->insert(198)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
*c=*b;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
*b=*b;
*b=*b;
std::cout << (c->insert(126)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
std::cout << (b->remove(362)) << std::endl;
std::cout << (b->remove(75)) << std::endl;
*d=*e;
std::cout << (b->remove(63)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->remove(426)) << std::endl;
std::cout << (a->remove(194)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
std::cout << (c->insert(296)) << std::endl;
b->printPretty();
*d=*b;
a->printPretty();
c->printPretty();
std::cout << (a->remove(382)) << std::endl;
e->printPretty();
std::cout << (c->insert(53)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->insert(499)) << std::endl;
std::cout << (d->insert(416)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
d->printPretty();
std::cout << (c->insert(296)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
*a=*c;
*a=*b;
std::cout << (a->insert(211)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->insert(230)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
*c=*e;
std::cout << (a->insert(391)) << std::endl;
d->printPretty();
*a=*a;
*b=*c;
std::cout << (d->insert(201)) << std::endl;
std::cout << (d->remove(109)) << std::endl;
std::cout << (c->remove(220)) << std::endl;
std::cout << (b->remove(89)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
std::cout << (b->insert(132)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
a->printPretty();
std::cout << (c->remove(9)) << std::endl;
std::cout << (b->remove(316)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
std::cout << (b->remove(132)) << std::endl;
std::cout << (d->insert(109)) << std::endl;
std::cout << (d->remove(214)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
std::cout << (b->remove(230)) << std::endl;
std::cout << (e->insert(147)) << std::endl;
std::cout << (e->remove(112)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (b->remove(66)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
std::cout << (a->remove(105)) << std::endl;
d->printPretty();
std::cout << (a->remove(22)) << std::endl;
e->printPretty();
*d=*a;
*d=*e;
std::cout << (d->remove(270)) << std::endl;
b->printPretty();
std::cout << (c->insert(459)) << std::endl;
std::cout << (d->remove(147)) << std::endl;
std::cout << (a->insert(63)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
*a=*d;
std::cout << (a->insert(66)) << std::endl;
a->printPretty();
std::cout << (d->insert(343)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
std::cout << (c->remove(381)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
c->printPretty();
std::cout << (d->remove(1)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
std::cout << (a->remove(350)) << std::endl;
std::cout << (a->remove(429)) << std::endl;
*b=*e;
std::cout << (e->remove(247)) << std::endl;
std::cout << (c->remove(147)) << std::endl;
c->printPretty();
std::cout << (a->remove(395)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
*e=*d;
a->printPretty();
*b=*c;
*c=*c;
std::cout << (a->remove(347)) << std::endl;
std::cout << (b->insert(49)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
*e=*e;
std::cout << (d->insert(207)) << std::endl;
*a=*a;
a->printPretty();
std::cout << (a->insert(230)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (e->remove(414)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
*d=*b;
std::cout << (b->remove(142)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
*e=*a;
std::cout << (e->remove(1)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
a->printPretty();
*a=*c;
d->printPretty();
*b=*a;
std::cout << (d->insert(67)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
*d=*c;
a->printPretty();
b->printPretty();
e->printPretty();
a->printPretty();
std::cout << (e->insert(123)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
*b=*a;
std::cout << (b->remove(351)) << std::endl;
*d=*e;
std::cout << (a->remove(29)) << std::endl;
*b=*a;
std::cout << (c->remove(413)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
*c=*d;
std::cout << (e->insert(31)) << std::endl;
d->printPretty();
c->printPretty();
d->printPretty();
c->printPretty();
*c=*a;
std::cout << (d->remove(446)) << std::endl;
*d=*b;
std::cout << (e->remove(391)) << std::endl;
std::cout << (e->remove(367)) << std::endl;
*a=*c;
std::cout << (b->insert(93)) << std::endl;
std::cout << (c->remove(105)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
std::cout << (e->insert(248)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (c->insert(427)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
std::cout << (c->insert(375)) << std::endl;
std::cout << (e->remove(446)) << std::endl;
*c=*b;
std::cout << (c->remove(196)) << std::endl;
std::cout << (a->insert(214)) << std::endl;
std::cout << (b->remove(66)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
d->printPretty();
std::cout << (d->insert(444)) << std::endl;
e->printPretty();
std::cout << (e->insert(123)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (b->remove(24)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (c->remove(89)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->insert(149)) << std::endl;
*b=*c;
std::cout << (d->remove(230)) << std::endl;
std::cout << (d->insert(458)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(313)) << std::endl;
std::cout << (e->remove(145)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (b->remove(285)) << std::endl;
std::cout << (b->remove(243)) << std::endl;
std::cout << (b->remove(142)) << std::endl;
*c=*c;
std::cout << (e->insert(308)) << std::endl;
std::cout << (d->remove(223)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
*e=*c;
std::cout << (a->remove(352)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
e->printPretty();
std::cout << (e->remove(181)) << std::endl;
c->printPretty();
std::cout << (b->insert(105)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (b->insert(1)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
*e=*e;
std::cout << (e->insert(375)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (b->insert(93)) << std::endl;
std::cout << (b->insert(145)) << std::endl;
*c=*c;
std::cout << (c->insert(144)) << std::endl;
*e=*d;
std::cout << (e->insert(450)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
d->printPretty();
std::cout << (a->insert(66)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (a->insert(77)) << std::endl;
*c=*a;
a->printPretty();
e->printPretty();
std::cout << (e->remove(414)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (d->insert(179)) << std::endl;
std::cout << (b->insert(400)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
*a=*e;
std::cout << (b->remove(444)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
*a=*e;
*b=*d;
*a=*c;
c->printPretty();
*d=*b;
a->printPretty();
std::cout << (a->insert(449)) << std::endl;
std::cout << (d->insert(429)) << std::endl;
*e=*a;
std::cout << (d->insert(142)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
*c=*c;
std::cout << (e->remove(215)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (d->remove(207)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (b->remove(89)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
std::cout << (c->insert(77)) << std::endl;
*b=*b;
std::cout << (c->insert(126)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
*d=*a;
std::cout << (b->insert(347)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (e->remove(444)) << std::endl;
b->printPretty();
std::cout << (e->insert(395)) << std::endl;
std::cout << (c->remove(55)) << std::endl;
a->printPretty();
std::cout << (c->insert(459)) << std::endl;
std::cout << (c->insert(38)) << std::endl;
*d=*d;
std::cout << (a->insert(230)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->remove(195)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
*a=*e;
std::cout << (c->insert(391)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
std::cout << (c->insert(151)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (d->insert(395)) << std::endl;
std::cout << (e->insert(403)) << std::endl;
std::cout << (c->remove(409)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (b->insert(126)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
*b=*a;
std::cout << (c->insert(167)) << std::endl;
std::cout << (a->remove(105)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
std::cout << (b->insert(230)) << std::endl;
std::cout << (a->remove(11)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
std::cout << (d->remove(214)) << std::endl;
std::cout << (b->insert(179)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->remove(357)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
b->printPretty();
std::cout << (c->insert(104)) << std::endl;
c->printPretty();
*d=*d;
c->printPretty();
*a=*e;
std::cout << (b->insert(490)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (d->insert(466)) << std::endl;
*b=*e;
std::cout << (b->insert(297)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
*d=*c;
*b=*c;
std::cout << (d->remove(32)) << std::endl;
e->printPretty();
std::cout << (d->remove(324)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
std::cout << (e->remove(66)) << std::endl;
std::cout << (d->remove(167)) << std::endl;
std::cout << (d->insert(373)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
std::cout << (a->remove(279)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
e->printPretty();
std::cout << (d->insert(300)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
std::cout << (e->insert(405)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
*a=*c;
std::cout << (a->remove(167)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
a->printPretty();
std::cout << (d->insert(375)) << std::endl;
*c=*d;
*d=*e;
std::cout << (e->insert(391)) << std::endl;
std::cout << (a->remove(46)) << std::endl;
std::cout << (a->remove(230)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (e->insert(403)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(151)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
*c=*e;
std::cout << (c->insert(5)) << std::endl;
a->printPretty();
std::cout << (a->remove(300)) << std::endl;
b->printPretty();
std::cout << (a->remove(459)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (e->remove(230)) << std::endl;
std::cout << (c->insert(105)) << std::endl;
*b=*e;
std::cout << (a->insert(72)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
std::cout << (b->remove(2)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
*e=*e;
std::cout << (d->insert(145)) << std::endl;
c->printPretty();
std::cout << (b->remove(32)) << std::endl;
std::cout << (c->remove(449)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (b->remove(105)) << std::endl;
d->printPretty();
e->printPretty();
*e=*c;
*d=*e;
b->printPretty();
return 0;
}
