#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
std::cout << (a->remove(388)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
*b=*b;
std::cout << (b->remove(492)) << std::endl;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->remove(213)) << std::endl;
std::cout << (c->insert(45)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
a->printPretty();
a->printPretty();
*a=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (d->insert(25)) << std::endl;
std::cout << (d->remove(398)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
*b=*a;
std::cout << (c->insert(2)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (c->remove(45)) << std::endl;
*b=*b;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (c->remove(56)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (a->remove(351)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (a->insert(45)) << std::endl;
d->printPretty();
std::cout << (a->remove(453)) << std::endl;
c->printPretty();
d->printPretty();
*b=*c;
std::cout << (b->remove(427)) << std::endl;
a->printPretty();
*c=*e;
*a=*e;
std::cout << (c->remove(2)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
d->printPretty();
std::cout << (b->insert(2)) << std::endl;
c->printPretty();
std::cout << (e->insert(2)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (a->insert(2)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (e->insert(2)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
e->printPretty();
std::cout << (d->insert(260)) << std::endl;
std::cout << (c->insert(203)) << std::endl;
*b=*d;
std::cout << (a->remove(2)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
std::cout << (b->insert(126)) << std::endl;
std::cout << (b->remove(260)) << std::endl;
e->printPretty();
std::cout << (d->insert(442)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
*c=*a;
a->printPretty();
*e=*d;
std::cout << (b->remove(384)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (d->remove(134)) << std::endl;
*c=*e;
*a=*a;
std::cout << (c->insert(442)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
std::cout << (d->remove(25)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (e->remove(243)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
std::cout << (e->insert(25)) << std::endl;
std::cout << (d->remove(260)) << std::endl;
c->printPretty();
std::cout << (d->remove(442)) << std::endl;
std::cout << (a->remove(75)) << std::endl;
*d=*c;
*c=*c;
d->printPretty();
a->printPretty();
std::cout << (e->insert(474)) << std::endl;
std::cout << (c->insert(269)) << std::endl;
std::cout << (b->remove(338)) << std::endl;
*e=*b;
std::cout << (c->insert(25)) << std::endl;
*b=*a;
std::cout << (d->remove(442)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
*a=*c;
std::cout << (c->insert(291)) << std::endl;
*c=*d;
std::cout << (e->remove(25)) << std::endl;
std::cout << (a->remove(188)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
std::cout << (e->insert(90)) << std::endl;
std::cout << (b->insert(333)) << std::endl;
*c=*c;
std::cout << (b->insert(79)) << std::endl;
d->printPretty();
std::cout << (b->remove(262)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
d->printPretty();
std::cout << (a->insert(260)) << std::endl;
std::cout << (b->remove(333)) << std::endl;
std::cout << (b->insert(212)) << std::endl;
std::cout << (b->insert(430)) << std::endl;
std::cout << (e->remove(276)) << std::endl;
std::cout << (a->remove(338)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (c->insert(499)) << std::endl;
std::cout << (b->insert(212)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
*d=*c;
std::cout << (d->remove(90)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
a->printPretty();
std::cout << (a->remove(390)) << std::endl;
a->printPretty();
std::cout << (b->insert(212)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
std::cout << (c->remove(123)) << std::endl;
e->printPretty();
std::cout << (c->insert(317)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
*d=*a;
a->printPretty();
*d=*d;
std::cout << (c->remove(473)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (a->remove(442)) << std::endl;
std::cout << (a->insert(25)) << std::endl;
std::cout << (d->insert(24)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
*b=*b;
*c=*e;
b->printPretty();
std::cout << (d->remove(169)) << std::endl;
c->printPretty();
std::cout << (a->remove(269)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (a->remove(20)) << std::endl;
e->printPretty();
std::cout << (c->remove(428)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
std::cout << (d->remove(269)) << std::endl;
b->printPretty();
*a=*a;
a->printPretty();
*e=*a;
std::cout << (e->remove(25)) << std::endl;
std::cout << (e->insert(260)) << std::endl;
a->printPretty();
std::cout << (c->remove(97)) << std::endl;
*c=*a;
std::cout << (a->remove(240)) << std::endl;
std::cout << (e->insert(260)) << std::endl;
std::cout << (e->remove(329)) << std::endl;
std::cout << (e->insert(260)) << std::endl;
std::cout << (c->remove(49)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
std::cout << (d->insert(380)) << std::endl;
b->printPretty();
std::cout << (a->insert(381)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
*b=*c;
std::cout << (a->remove(381)) << std::endl;
*e=*e;
std::cout << (c->remove(260)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
*b=*d;
std::cout << (a->insert(46)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
std::cout << (c->remove(25)) << std::endl;
*d=*e;
std::cout << (b->remove(387)) << std::endl;
std::cout << (e->insert(478)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
*b=*d;
std::cout << (c->remove(284)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (c->remove(275)) << std::endl;
*e=*b;
std::cout << (a->insert(69)) << std::endl;
std::cout << (e->insert(281)) << std::endl;
std::cout << (e->remove(178)) << std::endl;
std::cout << (b->insert(13)) << std::endl;
c->printPretty();
std::cout << (b->remove(307)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
*a=*d;
*d=*c;
std::cout << (e->remove(364)) << std::endl;
std::cout << (b->insert(147)) << std::endl;
std::cout << (e->remove(281)) << std::endl;
std::cout << (c->insert(318)) << std::endl;
a->printPretty();
std::cout << (c->remove(318)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (e->insert(148)) << std::endl;
std::cout << (d->insert(343)) << std::endl;
std::cout << (c->remove(192)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (d->remove(181)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
std::cout << (d->remove(8)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (d->insert(343)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
*e=*c;
std::cout << (b->insert(73)) << std::endl;
*c=*a;
*d=*b;
std::cout << (d->insert(363)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
*d=*a;
std::cout << (c->insert(150)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
*b=*d;
std::cout << (d->remove(102)) << std::endl;
*d=*a;
std::cout << (b->insert(102)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (d->insert(65)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
std::cout << (c->remove(236)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
*a=*b;
*e=*a;
std::cout << (e->remove(74)) << std::endl;
d->printPretty();
std::cout << (d->remove(65)) << std::endl;
c->printPretty();
*e=*e;
*a=*a;
std::cout << (e->remove(102)) << std::endl;
e->printPretty();
std::cout << (b->remove(102)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
std::cout << (c->insert(440)) << std::endl;
*d=*c;
std::cout << (e->insert(495)) << std::endl;
c->printPretty();
std::cout << (d->remove(440)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
e->printPretty();
std::cout << (d->insert(138)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
c->printPretty();
std::cout << (c->insert(312)) << std::endl;
e->printPretty();
std::cout << (e->insert(292)) << std::endl;
std::cout << (e->remove(339)) << std::endl;
std::cout << (b->insert(173)) << std::endl;
*c=*e;
*a=*c;
std::cout << (b->insert(461)) << std::endl;
*c=*b;
std::cout << (c->insert(190)) << std::endl;
std::cout << (d->insert(150)) << std::endl;
std::cout << (e->remove(495)) << std::endl;
*e=*b;
std::cout << (b->insert(190)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
std::cout << (a->insert(167)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
*b=*b;
std::cout << (a->remove(292)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
e->printPretty();
std::cout << (e->insert(461)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (b->insert(190)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (d->insert(138)) << std::endl;
std::cout << (d->remove(150)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
c->printPretty();
std::cout << (d->insert(138)) << std::endl;
std::cout << (a->insert(167)) << std::endl;
*b=*c;
std::cout << (c->insert(306)) << std::endl;
*a=*c;
std::cout << (b->remove(173)) << std::endl;
*d=*a;
*e=*b;
*d=*b;
std::cout << (e->insert(190)) << std::endl;
std::cout << (e->insert(224)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
std::cout << (e->remove(306)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
std::cout << (c->insert(33)) << std::endl;
b->printPretty();
std::cout << (b->remove(306)) << std::endl;
*e=*d;
std::cout << (a->insert(173)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
b->printPretty();
std::cout << (d->remove(190)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (c->remove(173)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (e->insert(461)) << std::endl;
std::cout << (a->insert(45)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
std::cout << (d->insert(306)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (c->remove(58)) << std::endl;
std::cout << (e->remove(82)) << std::endl;
*d=*e;
std::cout << (b->remove(257)) << std::endl;
std::cout << (e->remove(474)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (c->remove(461)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (e->remove(306)) << std::endl;
b->printPretty();
std::cout << (e->insert(190)) << std::endl;
*e=*a;
*e=*b;
a->printPretty();
std::cout << (c->insert(463)) << std::endl;
*a=*e;
*b=*a;
std::cout << (a->remove(463)) << std::endl;
*e=*b;
d->printPretty();
*c=*d;
std::cout << (c->insert(177)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
c->printPretty();
std::cout << (c->insert(308)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
e->printPretty();
std::cout << (c->insert(177)) << std::endl;
std::cout << (b->remove(88)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
std::cout << (a->insert(361)) << std::endl;
std::cout << (b->remove(190)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (a->insert(190)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
*a=*b;
std::cout << (e->remove(35)) << std::endl;
d->printPretty();
std::cout << (e->insert(361)) << std::endl;
std::cout << (e->remove(190)) << std::endl;
std::cout << (a->insert(346)) << std::endl;
b->printPretty();
*b=*b;
std::cout << (d->remove(461)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
*e=*b;
std::cout << (c->insert(483)) << std::endl;
*b=*a;
std::cout << (a->insert(390)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (d->remove(18)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (d->insert(288)) << std::endl;
std::cout << (d->remove(288)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
*d=*d;
*b=*d;
std::cout << (c->insert(296)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
*c=*a;
std::cout << (a->insert(390)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
*a=*e;
std::cout << (d->remove(177)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
std::cout << (a->remove(117)) << std::endl;
*e=*a;
std::cout << (a->remove(103)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
*b=*a;
std::cout << (c->remove(390)) << std::endl;
std::cout << (b->insert(449)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (d->remove(435)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
std::cout << (d->insert(483)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->remove(483)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (b->insert(449)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
c->printPretty();
std::cout << (a->insert(449)) << std::endl;
b->printPretty();
std::cout << (d->insert(344)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
std::cout << (a->remove(353)) << std::endl;
*a=*b;
*c=*a;
std::cout << (b->remove(61)) << std::endl;
*c=*e;
std::cout << (e->insert(329)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (d->remove(461)) << std::endl;
std::cout << (e->insert(461)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (a->insert(317)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
std::cout << (c->remove(295)) << std::endl;
std::cout << (b->insert(377)) << std::endl;
*c=*e;
std::cout << (e->insert(164)) << std::endl;
*b=*e;
std::cout << (c->remove(73)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
std::cout << (d->insert(344)) << std::endl;
std::cout << (c->remove(166)) << std::endl;
std::cout << (b->insert(329)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
std::cout << (a->insert(122)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
*e=*c;
*c=*c;
std::cout << (c->insert(164)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
*b=*c;
std::cout << (a->remove(293)) << std::endl;
e->printPretty();
std::cout << (e->remove(126)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->remove(336)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
d->printPretty();
std::cout << (c->remove(5)) << std::endl;
std::cout << (c->remove(364)) << std::endl;
*d=*d;
std::cout << (d->remove(306)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (c->remove(308)) << std::endl;
std::cout << (e->insert(210)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
d->printPretty();
*a=*e;
std::cout << (d->insert(344)) << std::endl;
*b=*e;
std::cout << (a->remove(329)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
*e=*d;
std::cout << (b->insert(164)) << std::endl;
*d=*e;
std::cout << (e->remove(447)) << std::endl;
a->printPretty();
std::cout << (e->insert(483)) << std::endl;
std::cout << (d->insert(483)) << std::endl;
std::cout << (b->insert(210)) << std::endl;
std::cout << (e->insert(13)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
a->printPretty();
std::cout << (b->remove(283)) << std::endl;
std::cout << (c->remove(70)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (e->insert(382)) << std::endl;
*b=*a;
*d=*d;
*c=*c;
*c=*e;
std::cout << (a->insert(87)) << std::endl;
b->printPretty();
std::cout << (c->insert(166)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (b->insert(158)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
std::cout << (e->insert(382)) << std::endl;
*d=*b;
*e=*a;
std::cout << (a->remove(198)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
std::cout << (c->insert(355)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
*b=*e;
c->printPretty();
std::cout << (a->insert(293)) << std::endl;
std::cout << (c->insert(465)) << std::endl;
*e=*a;
std::cout << (c->insert(94)) << std::endl;
std::cout << (b->insert(86)) << std::endl;
d->printPretty();
std::cout << (e->remove(87)) << std::endl;
*c=*a;
c->printPretty();
*b=*e;
*e=*c;
*a=*d;
std::cout << (d->remove(341)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->remove(344)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
std::cout << (a->remove(341)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (b->remove(293)) << std::endl;
c->printPretty();
c->printPretty();
d->printPretty();
std::cout << (c->remove(87)) << std::endl;
std::cout << (e->remove(87)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (e->insert(483)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (e->remove(483)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (c->remove(324)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
std::cout << (d->remove(483)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
d->printPretty();
std::cout << (c->insert(174)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->remove(344)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (d->insert(313)) << std::endl;
std::cout << (e->remove(318)) << std::endl;
std::cout << (d->insert(313)) << std::endl;
*d=*b;
std::cout << (e->insert(153)) << std::endl;
std::cout << (d->insert(388)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (d->remove(327)) << std::endl;
*a=*a;
std::cout << (a->insert(158)) << std::endl;
*b=*e;
std::cout << (c->insert(229)) << std::endl;
b->printPretty();
std::cout << (a->insert(483)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
std::cout << (b->insert(293)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(483)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (e->remove(288)) << std::endl;
c->printPretty();
std::cout << (d->insert(153)) << std::endl;
std::cout << (d->remove(153)) << std::endl;
std::cout << (a->insert(158)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
*d=*a;
e->printPretty();
*d=*d;
d->printPretty();
std::cout << (d->insert(235)) << std::endl;
b->printPretty();
std::cout << (b->insert(34)) << std::endl;
std::cout << (b->remove(314)) << std::endl;
std::cout << (e->insert(293)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
std::cout << (d->remove(392)) << std::endl;
std::cout << (c->remove(361)) << std::endl;
std::cout << (b->remove(153)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
c->printPretty();
std::cout << (b->remove(34)) << std::endl;
d->printPretty();
std::cout << (b->remove(108)) << std::endl;
c->printPretty();
std::cout << (c->insert(483)) << std::endl;
*d=*b;
std::cout << (b->remove(304)) << std::endl;
std::cout << (e->insert(293)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->insert(109)) << std::endl;
d->printPretty();
std::cout << (c->remove(153)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
std::cout << (c->remove(88)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (d->remove(468)) << std::endl;
std::cout << (c->insert(8)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
c->printPretty();
std::cout << (d->remove(293)) << std::endl;
*b=*e;
*d=*a;
std::cout << (b->insert(400)) << std::endl;
*b=*c;
std::cout << (a->insert(158)) << std::endl;
std::cout << (a->remove(158)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->remove(418)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
std::cout << (e->insert(165)) << std::endl;
std::cout << (c->insert(174)) << std::endl;
*a=*d;
*b=*a;
c->printPretty();
*d=*d;
std::cout << (c->insert(174)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (d->insert(43)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (a->remove(439)) << std::endl;
*b=*e;
*c=*e;
std::cout << (d->remove(435)) << std::endl;
*a=*b;
std::cout << (d->insert(43)) << std::endl;
c->printPretty();
std::cout << (e->insert(50)) << std::endl;
std::cout << (a->insert(445)) << std::endl;
std::cout << (a->remove(293)) << std::endl;
d->printPretty();
std::cout << (c->remove(453)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
c->printPretty();
std::cout << (e->insert(50)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
*a=*b;
std::cout << (e->insert(50)) << std::endl;
*c=*b;
std::cout << (e->insert(50)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
std::cout << (e->insert(50)) << std::endl;
a->printPretty();
std::cout << (b->remove(262)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (e->remove(1)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
*e=*e;
*b=*b;
std::cout << (d->remove(192)) << std::endl;
*b=*e;
a->printPretty();
b->printPretty();
std::cout << (e->insert(50)) << std::endl;
*b=*d;
std::cout << (e->insert(62)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
c->printPretty();
*c=*a;
b->printPretty();
return 0;
}
