#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
std::cout << (a->remove(233)) << std::endl;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*b=*a;
std::cout << (a->remove(2)) << std::endl;
std::cout << (b->insert(213)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (b->remove(150)) << std::endl;
a->printPretty();
*a=*a;
*e=*a;
std::cout << (b->remove(213)) << std::endl;
*b=*a;
*e=*b;
std::cout << (c->remove(122)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (d->insert(395)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
b->printPretty();
std::cout << (c->remove(158)) << std::endl;
d->printPretty();
std::cout << (b->remove(109)) << std::endl;
*a=*d;
*a=*d;
std::cout << (b->insert(56)) << std::endl;
std::cout << (e->insert(432)) << std::endl;
d->printPretty();
*c=*b;
d->printPretty();
std::cout << (b->remove(56)) << std::endl;
std::cout << (e->remove(432)) << std::endl;
d->printPretty();
std::cout << (b->remove(329)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (c->remove(56)) << std::endl;
a->printPretty();
std::cout << (a->insert(380)) << std::endl;
a->printPretty();
*e=*e;
d->printPretty();
std::cout << (d->remove(330)) << std::endl;
std::cout << (e->insert(411)) << std::endl;
*c=*b;
std::cout << (e->insert(411)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
std::cout << (a->insert(284)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (a->remove(220)) << std::endl;
std::cout << (b->remove(275)) << std::endl;
std::cout << (a->remove(146)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->insert(488)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
std::cout << (c->remove(301)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
d->printPretty();
std::cout << (a->remove(219)) << std::endl;
*d=*c;
b->printPretty();
*b=*d;
a->printPretty();
std::cout << (b->insert(402)) << std::endl;
std::cout << (b->remove(173)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
e->printPretty();
std::cout << (a->remove(103)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (e->insert(411)) << std::endl;
std::cout << (e->insert(361)) << std::endl;
std::cout << (b->remove(341)) << std::endl;
*e=*b;
std::cout << (c->insert(435)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (b->remove(77)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
a->printPretty();
std::cout << (d->remove(484)) << std::endl;
std::cout << (b->insert(134)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
b->printPretty();
std::cout << (b->remove(7)) << std::endl;
std::cout << (a->remove(336)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (e->insert(402)) << std::endl;
std::cout << (b->remove(264)) << std::endl;
*b=*d;
*a=*c;
std::cout << (b->remove(273)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
std::cout << (e->remove(402)) << std::endl;
std::cout << (d->insert(45)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
d->printPretty();
std::cout << (d->remove(45)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
*e=*c;
c->printPretty();
std::cout << (a->insert(435)) << std::endl;
std::cout << (a->remove(435)) << std::endl;
*c=*c;
std::cout << (e->remove(469)) << std::endl;
b->printPretty();
c->printPretty();
b->printPretty();
std::cout << (d->insert(370)) << std::endl;
*a=*e;
std::cout << (d->remove(69)) << std::endl;
std::cout << (a->insert(435)) << std::endl;
c->printPretty();
std::cout << (d->insert(370)) << std::endl;
std::cout << (d->remove(370)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
c->printPretty();
std::cout << (d->remove(273)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (e->insert(398)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
c->printPretty();
std::cout << (c->insert(11)) << std::endl;
e->printPretty();
std::cout << (d->insert(330)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (d->insert(342)) << std::endl;
std::cout << (d->remove(411)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
b->printPretty();
std::cout << (a->insert(432)) << std::endl;
c->printPretty();
std::cout << (b->remove(235)) << std::endl;
std::cout << (c->insert(235)) << std::endl;
a->printPretty();
std::cout << (c->remove(122)) << std::endl;
std::cout << (e->insert(398)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (c->insert(235)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (c->insert(11)) << std::endl;
std::cout << (c->remove(205)) << std::endl;
*c=*d;
std::cout << (d->insert(330)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
a->printPretty();
std::cout << (d->insert(86)) << std::endl;
std::cout << (e->insert(45)) << std::endl;
std::cout << (d->remove(86)) << std::endl;
c->printPretty();
std::cout << (c->insert(330)) << std::endl;
std::cout << (e->remove(463)) << std::endl;
std::cout << (c->remove(330)) << std::endl;
*b=*b;
std::cout << (a->remove(485)) << std::endl;
*a=*e;
*d=*c;
std::cout << (e->insert(291)) << std::endl;
d->printPretty();
std::cout << (a->insert(45)) << std::endl;
*c=*c;
std::cout << (b->insert(239)) << std::endl;
std::cout << (a->remove(309)) << std::endl;
d->printPretty();
std::cout << (e->remove(339)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (b->insert(175)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
std::cout << (e->insert(330)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
*d=*a;
*e=*e;
*d=*d;
*a=*d;
std::cout << (a->insert(325)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (a->remove(45)) << std::endl;
std::cout << (c->insert(150)) << std::endl;
std::cout << (e->insert(330)) << std::endl;
std::cout << (c->insert(150)) << std::endl;
a->printPretty();
std::cout << (c->remove(81)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (a->remove(465)) << std::endl;
std::cout << (b->insert(427)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->insert(330)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
c->printPretty();
std::cout << (b->remove(427)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
*b=*e;
std::cout << (e->remove(291)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
d->printPretty();
c->printPretty();
d->printPretty();
std::cout << (e->remove(45)) << std::endl;
*d=*c;
std::cout << (d->insert(400)) << std::endl;
*e=*e;
std::cout << (c->insert(306)) << std::endl;
*b=*a;
std::cout << (d->remove(390)) << std::endl;
std::cout << (e->insert(26)) << std::endl;
std::cout << (c->remove(330)) << std::endl;
std::cout << (e->insert(26)) << std::endl;
e->printPretty();
std::cout << (c->remove(314)) << std::endl;
a->printPretty();
std::cout << (e->remove(26)) << std::endl;
std::cout << (c->insert(14)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
d->printPretty();
std::cout << (c->insert(325)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
a->printPretty();
b->printPretty();
e->printPretty();
*a=*d;
*d=*e;
std::cout << (b->remove(465)) << std::endl;
*a=*a;
std::cout << (e->insert(25)) << std::endl;
*b=*d;
*d=*d;
std::cout << (e->remove(309)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
*c=*c;
std::cout << (b->remove(362)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (c->remove(19)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (d->remove(457)) << std::endl;
std::cout << (a->remove(400)) << std::endl;
std::cout << (c->remove(427)) << std::endl;
c->printPretty();
std::cout << (a->remove(342)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
d->printPretty();
std::cout << (d->insert(123)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
*a=*e;
b->printPretty();
std::cout << (a->insert(367)) << std::endl;
std::cout << (d->insert(123)) << std::endl;
std::cout << (d->insert(123)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (c->insert(86)) << std::endl;
*a=*e;
e->printPretty();
b->printPretty();
c->printPretty();
std::cout << (d->remove(473)) << std::endl;
*c=*d;
std::cout << (d->insert(123)) << std::endl;
std::cout << (d->insert(156)) << std::endl;
std::cout << (d->remove(123)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->insert(229)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
*c=*b;
std::cout << (b->remove(244)) << std::endl;
std::cout << (e->insert(316)) << std::endl;
std::cout << (b->remove(420)) << std::endl;
std::cout << (a->remove(472)) << std::endl;
*c=*b;
std::cout << (a->remove(167)) << std::endl;
std::cout << (a->insert(424)) << std::endl;
d->printPretty();
std::cout << (c->remove(342)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
*b=*e;
std::cout << (d->remove(156)) << std::endl;
std::cout << (e->insert(316)) << std::endl;
std::cout << (e->remove(389)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (e->remove(76)) << std::endl;
std::cout << (e->remove(316)) << std::endl;
e->printPretty();
*c=*c;
std::cout << (a->remove(424)) << std::endl;
std::cout << (c->insert(415)) << std::endl;
std::cout << (c->remove(415)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
b->printPretty();
std::cout << (a->remove(484)) << std::endl;
std::cout << (b->remove(316)) << std::endl;
std::cout << (c->insert(313)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (d->remove(81)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (c->insert(32)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (d->insert(478)) << std::endl;
std::cout << (d->remove(148)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (a->insert(107)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
b->printPretty();
std::cout << (c->insert(217)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->remove(32)) << std::endl;
std::cout << (d->insert(478)) << std::endl;
c->printPretty();
std::cout << (a->insert(444)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
*b=*c;
*d=*a;
std::cout << (c->remove(340)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
*e=*a;
std::cout << (e->insert(33)) << std::endl;
std::cout << (d->remove(5)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
a->printPretty();
std::cout << (d->insert(287)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(94)) << std::endl;
std::cout << (b->insert(303)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (d->insert(405)) << std::endl;
*e=*d;
std::cout << (d->insert(361)) << std::endl;
std::cout << (a->insert(350)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
std::cout << (e->insert(430)) << std::endl;
std::cout << (e->remove(287)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
std::cout << (b->remove(378)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
*b=*d;
std::cout << (e->insert(244)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
a->printPretty();
std::cout << (b->remove(405)) << std::endl;
std::cout << (e->insert(430)) << std::endl;
std::cout << (b->insert(144)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
*d=*e;
*a=*e;
std::cout << (a->remove(67)) << std::endl;
*a=*e;
*a=*e;
std::cout << (e->insert(107)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (a->insert(338)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
a->printPretty();
e->printPretty();
*d=*a;
std::cout << (a->remove(405)) << std::endl;
b->printPretty();
std::cout << (a->remove(338)) << std::endl;
d->printPretty();
std::cout << (c->remove(269)) << std::endl;
*d=*e;
std::cout << (d->remove(479)) << std::endl;
std::cout << (c->remove(287)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (d->insert(361)) << std::endl;
std::cout << (b->remove(287)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (c->remove(107)) << std::endl;
*a=*b;
*e=*a;
b->printPretty();
std::cout << (b->insert(188)) << std::endl;
*c=*c;
std::cout << (b->insert(188)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
d->printPretty();
std::cout << (e->insert(397)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
*b=*c;
*e=*c;
std::cout << (e->insert(295)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
d->printPretty();
std::cout << (d->insert(361)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (b->insert(195)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
std::cout << (d->insert(334)) << std::endl;
std::cout << (d->insert(303)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (b->remove(444)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
*c=*c;
*a=*c;
std::cout << (a->insert(401)) << std::endl;
std::cout << (e->remove(303)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->insert(195)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (c->insert(411)) << std::endl;
b->printPretty();
std::cout << (e->remove(287)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (b->insert(75)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
*d=*b;
std::cout << (c->insert(342)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->insert(482)) << std::endl;
std::cout << (c->insert(411)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(480)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (a->remove(20)) << std::endl;
*d=*a;
*c=*b;
e->printPretty();
std::cout << (b->insert(75)) << std::endl;
c->printPretty();
std::cout << (a->remove(482)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
*e=*e;
std::cout << (c->insert(262)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
a->printPretty();
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
std::cout << (b->remove(409)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (b->remove(21)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
std::cout << (b->insert(75)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
std::cout << (a->remove(439)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (e->insert(461)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(444)) << std::endl;
*d=*a;
std::cout << (b->remove(75)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
std::cout << (c->remove(409)) << std::endl;
std::cout << (c->insert(416)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
std::cout << (e->insert(40)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
std::cout << (a->remove(260)) << std::endl;
d->printPretty();
std::cout << (c->remove(75)) << std::endl;
b->printPretty();
*b=*c;
*e=*a;
std::cout << (a->remove(395)) << std::endl;
*c=*a;
*d=*d;
b->printPretty();
*c=*b;
*a=*d;
std::cout << (c->remove(196)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
*b=*c;
a->printPretty();
std::cout << (d->insert(250)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (b->remove(82)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (a->remove(89)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
c->printPretty();
std::cout << (d->insert(30)) << std::endl;
std::cout << (e->insert(87)) << std::endl;
std::cout << (d->insert(418)) << std::endl;
std::cout << (a->insert(15)) << std::endl;
std::cout << (e->remove(87)) << std::endl;
std::cout << (b->insert(71)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
*e=*e;
std::cout << (a->insert(131)) << std::endl;
*d=*c;
std::cout << (b->remove(94)) << std::endl;
std::cout << (a->remove(210)) << std::endl;
std::cout << (c->insert(195)) << std::endl;
*d=*c;
a->printPretty();
std::cout << (b->remove(262)) << std::endl;
d->printPretty();
std::cout << (a->remove(146)) << std::endl;
*c=*b;
std::cout << (a->insert(181)) << std::endl;
d->printPretty();
std::cout << (a->insert(15)) << std::endl;
std::cout << (c->insert(416)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (e->remove(71)) << std::endl;
std::cout << (b->insert(63)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (e->remove(11)) << std::endl;
std::cout << (a->remove(256)) << std::endl;
std::cout << (a->insert(15)) << std::endl;
b->printPretty();
std::cout << (c->insert(416)) << std::endl;
std::cout << (b->insert(63)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
*c=*a;
std::cout << (d->remove(251)) << std::endl;
std::cout << (d->insert(163)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
*a=*e;
std::cout << (c->insert(131)) << std::endl;
std::cout << (c->insert(285)) << std::endl;
std::cout << (b->remove(177)) << std::endl;
*b=*e;
std::cout << (e->insert(456)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
std::cout << (c->remove(181)) << std::endl;
a->printPretty();
std::cout << (b->insert(119)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
std::cout << (e->insert(456)) << std::endl;
*c=*b;
std::cout << (b->insert(38)) << std::endl;
c->printPretty();
std::cout << (e->remove(326)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
a->printPretty();
*b=*d;
b->printPretty();
e->printPretty();
std::cout << (a->insert(17)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
*b=*e;
d->printPretty();
std::cout << (b->remove(234)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (d->insert(436)) << std::endl;
std::cout << (c->remove(119)) << std::endl;
std::cout << (d->remove(201)) << std::endl;
std::cout << (b->insert(456)) << std::endl;
std::cout << (a->remove(496)) << std::endl;
std::cout << (b->insert(456)) << std::endl;
std::cout << (c->remove(141)) << std::endl;
std::cout << (e->insert(456)) << std::endl;
*e=*d;
std::cout << (e->remove(436)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
b->printPretty();
std::cout << (e->remove(283)) << std::endl;
std::cout << (d->remove(173)) << std::endl;
*d=*a;
std::cout << (d->insert(17)) << std::endl;
std::cout << (b->insert(176)) << std::endl;
std::cout << (d->remove(64)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
d->printPretty();
*d=*a;
c->printPretty();
b->printPretty();
a->printPretty();
std::cout << (e->insert(404)) << std::endl;
std::cout << (d->remove(17)) << std::endl;
std::cout << (e->remove(189)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (b->insert(71)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
std::cout << (b->remove(156)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
*a=*e;
std::cout << (d->remove(339)) << std::endl;
e->printPretty();
std::cout << (b->insert(309)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
c->printPretty();
std::cout << (a->insert(404)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
a->printPretty();
e->printPretty();
c->printPretty();
std::cout << (c->insert(155)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
d->printPretty();
std::cout << (e->remove(171)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (b->insert(138)) << std::endl;
c->printPretty();
return 0;
}
