#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
b->printPretty();
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
*e=*c;
std::cout << (c->remove(76)) << std::endl;
d->printPretty();
b->printPretty();
*a=*c;
*d=*c;
b->printPretty();
std::cout << (d->insert(40)) << std::endl;
*b=*c;
std::cout << (e->insert(73)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (e->remove(73)) << std::endl;
*d=*a;
std::cout << (a->remove(251)) << std::endl;
*b=*c;
*b=*a;
std::cout << (b->remove(276)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
*b=*a;
std::cout << (d->insert(409)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
c->printPretty();
std::cout << (b->insert(430)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (d->insert(397)) << std::endl;
c->printPretty();
std::cout << (a->insert(98)) << std::endl;
a->printPretty();
std::cout << (b->insert(257)) << std::endl;
std::cout << (b->insert(430)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
std::cout << (d->remove(95)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (a->insert(257)) << std::endl;
std::cout << (a->insert(283)) << std::endl;
*b=*b;
*c=*b;
std::cout << (c->remove(1)) << std::endl;
std::cout << (b->remove(430)) << std::endl;
std::cout << (b->remove(419)) << std::endl;
*c=*d;
std::cout << (c->remove(397)) << std::endl;
*b=*c;
std::cout << (e->insert(20)) << std::endl;
std::cout << (c->remove(3)) << std::endl;
*e=*c;
c->printPretty();
*b=*c;
*d=*b;
std::cout << (a->remove(100)) << std::endl;
*a=*c;
*b=*b;
std::cout << (a->remove(409)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (e->remove(409)) << std::endl;
std::cout << (b->insert(362)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
*d=*a;
std::cout << (e->remove(91)) << std::endl;
std::cout << (e->remove(424)) << std::endl;
std::cout << (c->remove(380)) << std::endl;
std::cout << (e->insert(321)) << std::endl;
std::cout << (b->remove(362)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
std::cout << (e->insert(321)) << std::endl;
e->printPretty();
*e=*b;
e->printPretty();
*e=*d;
std::cout << (c->remove(409)) << std::endl;
e->printPretty();
*c=*c;
std::cout << (d->insert(78)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
std::cout << (d->remove(138)) << std::endl;
c->printPretty();
c->printPretty();
e->printPretty();
a->printPretty();
std::cout << (d->insert(360)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (c->remove(386)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
*d=*d;
*b=*b;
std::cout << (e->remove(297)) << std::endl;
c->printPretty();
std::cout << (b->insert(28)) << std::endl;
std::cout << (d->remove(51)) << std::endl;
std::cout << (c->remove(360)) << std::endl;
std::cout << (b->remove(28)) << std::endl;
std::cout << (e->remove(436)) << std::endl;
c->printPretty();
std::cout << (a->remove(453)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
std::cout << (b->remove(409)) << std::endl;
*a=*d;
std::cout << (e->insert(360)) << std::endl;
*e=*b;
std::cout << (c->insert(276)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
std::cout << (c->remove(276)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
*b=*b;
std::cout << (e->insert(111)) << std::endl;
*e=*d;
std::cout << (a->remove(78)) << std::endl;
*a=*a;
std::cout << (a->remove(493)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
*e=*a;
std::cout << (e->insert(134)) << std::endl;
std::cout << (b->insert(324)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (e->insert(327)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
a->printPretty();
std::cout << (c->insert(461)) << std::endl;
std::cout << (d->remove(139)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (b->remove(461)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->insert(397)) << std::endl;
*d=*c;
*d=*c;
a->printPretty();
std::cout << (e->insert(390)) << std::endl;
*e=*e;
*b=*c;
std::cout << (e->insert(236)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
c->printPretty();
*d=*e;
std::cout << (d->insert(236)) << std::endl;
std::cout << (e->remove(236)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
c->printPretty();
std::cout << (a->insert(75)) << std::endl;
std::cout << (c->remove(461)) << std::endl;
std::cout << (d->remove(134)) << std::endl;
std::cout << (d->remove(144)) << std::endl;
c->printPretty();
b->printPretty();
*b=*c;
std::cout << (d->remove(201)) << std::endl;
std::cout << (d->remove(327)) << std::endl;
*d=*d;
d->printPretty();
c->printPretty();
std::cout << (d->remove(200)) << std::endl;
d->printPretty();
std::cout << (b->insert(167)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(53)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (a->remove(53)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (b->remove(219)) << std::endl;
std::cout << (e->insert(29)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
e->printPretty();
std::cout << (a->insert(51)) << std::endl;
std::cout << (b->remove(167)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
std::cout << (d->insert(412)) << std::endl;
std::cout << (e->remove(134)) << std::endl;
*a=*c;
std::cout << (b->insert(6)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (d->insert(74)) << std::endl;
std::cout << (c->remove(363)) << std::endl;
b->printPretty();
std::cout << (d->insert(421)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
*b=*e;
std::cout << (e->insert(327)) << std::endl;
d->printPretty();
std::cout << (d->insert(74)) << std::endl;
std::cout << (e->remove(327)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
*c=*c;
std::cout << (d->insert(201)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
std::cout << (d->remove(74)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (b->insert(446)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
*d=*c;
std::cout << (b->insert(396)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
*b=*b;
std::cout << (d->insert(491)) << std::endl;
std::cout << (b->remove(396)) << std::endl;
*c=*a;
std::cout << (e->remove(431)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
*d=*b;
*e=*c;
std::cout << (b->remove(327)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (b->remove(446)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (c->remove(499)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
d->printPretty();
std::cout << (d->insert(29)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (b->remove(160)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
c->printPretty();
std::cout << (d->remove(224)) << std::endl;
*b=*e;
std::cout << (e->insert(499)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
std::cout << (e->insert(412)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (d->remove(29)) << std::endl;
std::cout << (e->remove(199)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
std::cout << (c->remove(3)) << std::endl;
std::cout << (b->remove(178)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
std::cout << (e->insert(355)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
c->printPretty();
d->printPretty();
*c=*a;
b->printPretty();
std::cout << (b->insert(452)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
std::cout << (a->insert(426)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
*b=*d;
std::cout << (b->insert(461)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
std::cout << (b->remove(408)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
std::cout << (e->remove(27)) << std::endl;
c->printPretty();
std::cout << (e->insert(321)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
c->printPretty();
std::cout << (d->insert(52)) << std::endl;
std::cout << (e->remove(175)) << std::endl;
*a=*a;
std::cout << (b->insert(78)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (e->remove(333)) << std::endl;
std::cout << (b->remove(338)) << std::endl;
std::cout << (e->insert(215)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
*a=*c;
e->printPretty();
*c=*c;
std::cout << (d->insert(11)) << std::endl;
*a=*d;
std::cout << (c->remove(317)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
std::cout << (e->insert(178)) << std::endl;
d->printPretty();
std::cout << (b->insert(327)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
*c=*b;
b->printPretty();
*a=*d;
std::cout << (d->remove(189)) << std::endl;
std::cout << (c->remove(327)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (b->insert(244)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
*d=*a;
std::cout << (e->insert(363)) << std::endl;
d->printPretty();
c->printPretty();
b->printPretty();
std::cout << (e->insert(178)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->insert(52)) << std::endl;
e->printPretty();
std::cout << (b->remove(205)) << std::endl;
b->printPretty();
std::cout << (c->insert(100)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
*c=*b;
std::cout << (b->insert(412)) << std::endl;
*d=*e;
c->printPretty();
*b=*a;
std::cout << (e->remove(412)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
*c=*e;
std::cout << (a->remove(195)) << std::endl;
std::cout << (a->insert(345)) << std::endl;
std::cout << (a->insert(11)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
*e=*b;
*c=*c;
*d=*e;
std::cout << (d->insert(288)) << std::endl;
std::cout << (e->insert(246)) << std::endl;
std::cout << (a->insert(327)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
*b=*c;
*d=*b;
std::cout << (b->remove(83)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
std::cout << (c->remove(321)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->insert(461)) << std::endl;
*b=*e;
std::cout << (c->insert(245)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
std::cout << (e->remove(74)) << std::endl;
*a=*b;
std::cout << (a->insert(287)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
*e=*e;
std::cout << (c->remove(140)) << std::endl;
e->printPretty();
std::cout << (c->remove(363)) << std::endl;
c->printPretty();
std::cout << (a->remove(310)) << std::endl;
std::cout << (c->remove(215)) << std::endl;
c->printPretty();
std::cout << (d->remove(178)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
*c=*d;
std::cout << (c->remove(128)) << std::endl;
*b=*e;
std::cout << (d->remove(138)) << std::endl;
c->printPretty();
*b=*d;
std::cout << (c->remove(66)) << std::endl;
d->printPretty();
std::cout << (d->remove(225)) << std::endl;
a->printPretty();
std::cout << (e->insert(211)) << std::endl;
std::cout << (e->remove(154)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->remove(11)) << std::endl;
std::cout << (b->remove(471)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
a->printPretty();
std::cout << (b->remove(215)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
c->printPretty();
std::cout << (c->remove(215)) << std::endl;
*c=*c;
std::cout << (b->insert(321)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (c->insert(62)) << std::endl;
std::cout << (c->insert(170)) << std::endl;
b->printPretty();
std::cout << (e->remove(242)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
*a=*d;
std::cout << (b->remove(60)) << std::endl;
std::cout << (b->remove(416)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (d->insert(255)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
std::cout << (b->remove(394)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
std::cout << (e->insert(461)) << std::endl;
std::cout << (d->remove(356)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
std::cout << (d->insert(245)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
*a=*a;
std::cout << (b->insert(402)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
std::cout << (d->remove(55)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
e->printPretty();
std::cout << (a->insert(245)) << std::endl;
*d=*d;
std::cout << (c->remove(466)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
a->printPretty();
std::cout << (b->insert(127)) << std::endl;
*c=*e;
std::cout << (a->insert(178)) << std::endl;
b->printPretty();
std::cout << (d->insert(363)) << std::endl;
a->printPretty();
*d=*e;
std::cout << (e->remove(211)) << std::endl;
std::cout << (d->insert(299)) << std::endl;
c->printPretty();
std::cout << (c->remove(466)) << std::endl;
std::cout << (c->insert(11)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
std::cout << (a->remove(438)) << std::endl;
a->printPretty();
std::cout << (a->remove(364)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
*a=*b;
std::cout << (d->remove(327)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->insert(402)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
b->printPretty();
std::cout << (c->remove(327)) << std::endl;
*c=*b;
std::cout << (d->insert(299)) << std::endl;
*d=*a;
std::cout << (d->insert(226)) << std::endl;
*c=*b;
*d=*b;
a->printPretty();
std::cout << (a->remove(179)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
*a=*b;
*e=*a;
*c=*a;
std::cout << (a->remove(363)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
a->printPretty();
std::cout << (d->remove(128)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (d->insert(66)) << std::endl;
*c=*b;
*b=*e;
*b=*d;
std::cout << (d->remove(317)) << std::endl;
e->printPretty();
std::cout << (b->remove(66)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
c->printPretty();
std::cout << (d->remove(374)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
std::cout << (a->insert(203)) << std::endl;
a->printPretty();
std::cout << (a->remove(86)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
c->printPretty();
std::cout << (d->remove(66)) << std::endl;
*c=*b;
std::cout << (a->insert(410)) << std::endl;
d->printPretty();
std::cout << (e->insert(78)) << std::endl;
*c=*d;
d->printPretty();
std::cout << (c->insert(363)) << std::endl;
*b=*b;
std::cout << (a->insert(203)) << std::endl;
std::cout << (e->remove(78)) << std::endl;
std::cout << (c->insert(410)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (e->remove(371)) << std::endl;
std::cout << (e->insert(363)) << std::endl;
std::cout << (b->insert(402)) << std::endl;
std::cout << (e->remove(20)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
std::cout << (c->remove(127)) << std::endl;
std::cout << (c->remove(38)) << std::endl;
std::cout << (c->insert(125)) << std::endl;
std::cout << (a->remove(402)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (b->remove(193)) << std::endl;
std::cout << (b->insert(72)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (c->insert(14)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
*e=*c;
std::cout << (c->insert(363)) << std::endl;
*e=*b;
e->printPretty();
std::cout << (b->remove(410)) << std::endl;
a->printPretty();
std::cout << (a->remove(48)) << std::endl;
*a=*b;
std::cout << (b->insert(363)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
std::cout << (a->remove(402)) << std::endl;
d->printPretty();
*e=*a;
a->printPretty();
std::cout << (e->insert(48)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->remove(48)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
*d=*e;
std::cout << (b->remove(298)) << std::endl;
d->printPretty();
std::cout << (e->remove(197)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (a->insert(392)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
*c=*d;
std::cout << (e->insert(7)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (c->insert(378)) << std::endl;
*d=*e;
std::cout << (b->remove(402)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
*e=*e;
std::cout << (d->remove(363)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
std::cout << (d->insert(356)) << std::endl;
e->printPretty();
std::cout << (c->remove(469)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
std::cout << (b->remove(276)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (e->insert(1)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
std::cout << (d->insert(127)) << std::endl;
c->printPretty();
*e=*b;
a->printPretty();
std::cout << (e->insert(245)) << std::endl;
*b=*b;
*e=*c;
std::cout << (c->remove(245)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (d->remove(321)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (d->remove(480)) << std::endl;
std::cout << (d->remove(296)) << std::endl;
*b=*b;
b->printPretty();
*e=*b;
std::cout << (e->remove(48)) << std::endl;
std::cout << (a->remove(474)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
std::cout << (b->remove(197)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
*a=*c;
std::cout << (c->remove(260)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->insert(338)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
std::cout << (b->remove(293)) << std::endl;
std::cout << (e->insert(341)) << std::endl;
std::cout << (c->insert(275)) << std::endl;
*e=*e;
std::cout << (e->insert(279)) << std::endl;
std::cout << (e->insert(156)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->remove(78)) << std::endl;
*c=*d;
std::cout << (a->remove(127)) << std::endl;
std::cout << (e->insert(341)) << std::endl;
std::cout << (b->remove(127)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
*a=*a;
std::cout << (d->remove(406)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (c->remove(257)) << std::endl;
std::cout << (d->insert(7)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
std::cout << (c->remove(127)) << std::endl;
std::cout << (b->insert(363)) << std::endl;
std::cout << (d->remove(48)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
*b=*d;
std::cout << (d->remove(127)) << std::endl;
*a=*c;
std::cout << (d->remove(489)) << std::endl;
std::cout << (c->remove(7)) << std::endl;
*e=*d;
std::cout << (b->remove(203)) << std::endl;
c->printPretty();
std::cout << (c->remove(356)) << std::endl;
std::cout << (a->insert(48)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
e->printPretty();
std::cout << (d->insert(245)) << std::endl;
e->printPretty();
a->printPretty();
*a=*a;
b->printPretty();
std::cout << (a->remove(7)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
a->printPretty();
std::cout << (d->remove(364)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (d->remove(257)) << std::endl;
std::cout << (d->insert(388)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
std::cout << (e->remove(317)) << std::endl;
std::cout << (e->insert(356)) << std::endl;
std::cout << (d->remove(388)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->remove(245)) << std::endl;
*c=*e;
a->printPretty();
std::cout << (b->remove(356)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
std::cout << (d->insert(275)) << std::endl;
*a=*d;
*e=*d;
*d=*c;
std::cout << (c->remove(245)) << std::endl;
std::cout << (a->remove(275)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
std::cout << (c->remove(7)) << std::endl;
return 0;
}
