#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(358)) << std::endl;
std::cout << (a->remove(200)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
*b=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
a->printPretty();
b->printPretty();
a->printPretty();
std::cout << (b->insert(358)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*d=*c;
std::cout << (b->remove(358)) << std::endl;
*d=*a;
*e=*a;
std::cout << (c->remove(11)) << std::endl;
*a=*a;
std::cout << (c->remove(220)) << std::endl;
*e=*d;
std::cout << (c->insert(315)) << std::endl;
std::cout << (a->remove(356)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (d->remove(415)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
std::cout << (c->insert(315)) << std::endl;
std::cout << (a->remove(71)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (b->remove(406)) << std::endl;
std::cout << (e->insert(140)) << std::endl;
std::cout << (c->remove(261)) << std::endl;
*a=*c;
b->printPretty();
e->printPretty();
std::cout << (c->remove(397)) << std::endl;
std::cout << (d->remove(358)) << std::endl;
std::cout << (a->remove(315)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
*c=*d;
*b=*b;
std::cout << (e->insert(358)) << std::endl;
*b=*d;
std::cout << (d->remove(294)) << std::endl;
std::cout << (d->remove(367)) << std::endl;
*d=*c;
d->printPretty();
d->printPretty();
std::cout << (e->insert(372)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (e->remove(276)) << std::endl;
std::cout << (b->remove(409)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(291)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (e->remove(277)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (b->remove(20)) << std::endl;
b->printPretty();
std::cout << (d->insert(44)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
std::cout << (a->remove(384)) << std::endl;
std::cout << (c->insert(353)) << std::endl;
*e=*c;
*e=*c;
std::cout << (c->remove(184)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->remove(260)) << std::endl;
*d=*a;
std::cout << (b->remove(327)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (e->insert(490)) << std::endl;
std::cout << (b->remove(221)) << std::endl;
d->printPretty();
std::cout << (b->insert(76)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
std::cout << (a->insert(180)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
std::cout << (a->insert(180)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
*d=*c;
std::cout << (c->remove(353)) << std::endl;
std::cout << (a->remove(180)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (d->remove(428)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
*c=*d;
std::cout << (a->remove(447)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
*d=*e;
std::cout << (b->insert(218)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (c->remove(35)) << std::endl;
*a=*a;
*c=*b;
std::cout << (a->insert(428)) << std::endl;
*e=*c;
*c=*e;
std::cout << (c->insert(349)) << std::endl;
c->printPretty();
std::cout << (a->remove(303)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
std::cout << (d->remove(284)) << std::endl;
*c=*e;
std::cout << (d->remove(214)) << std::endl;
c->printPretty();
std::cout << (e->remove(311)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
d->printPretty();
std::cout << (b->remove(328)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
d->printPretty();
*a=*e;
d->printPretty();
*e=*c;
std::cout << (d->remove(353)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
std::cout << (c->remove(284)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
std::cout << (d->insert(10)) << std::endl;
std::cout << (a->insert(398)) << std::endl;
d->printPretty();
std::cout << (a->insert(184)) << std::endl;
*e=*d;
std::cout << (a->insert(484)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
*b=*e;
std::cout << (b->insert(111)) << std::endl;
std::cout << (b->remove(255)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
std::cout << (b->remove(437)) << std::endl;
*c=*a;
std::cout << (e->remove(315)) << std::endl;
std::cout << (d->remove(481)) << std::endl;
std::cout << (d->remove(111)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
std::cout << (d->insert(10)) << std::endl;
std::cout << (a->remove(406)) << std::endl;
e->printPretty();
std::cout << (d->insert(78)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (b->insert(282)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
*a=*c;
std::cout << (e->insert(486)) << std::endl;
e->printPretty();
std::cout << (d->insert(78)) << std::endl;
*c=*a;
std::cout << (b->remove(490)) << std::endl;
*e=*c;
*c=*c;
std::cout << (c->insert(161)) << std::endl;
*a=*a;
std::cout << (e->insert(179)) << std::endl;
std::cout << (a->insert(53)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
*e=*b;
e->printPretty();
std::cout << (a->remove(169)) << std::endl;
std::cout << (d->remove(38)) << std::endl;
*d=*c;
std::cout << (e->insert(10)) << std::endl;
std::cout << (d->remove(484)) << std::endl;
std::cout << (c->insert(398)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
*c=*b;
std::cout << (a->remove(43)) << std::endl;
*c=*c;
std::cout << (a->insert(398)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
*c=*d;
std::cout << (c->remove(19)) << std::endl;
*b=*a;
std::cout << (d->insert(306)) << std::endl;
*c=*a;
std::cout << (e->insert(167)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
e->printPretty();
std::cout << (e->insert(10)) << std::endl;
std::cout << (b->insert(87)) << std::endl;
std::cout << (e->insert(34)) << std::endl;
std::cout << (b->remove(484)) << std::endl;
std::cout << (e->insert(367)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
std::cout << (e->remove(367)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (b->remove(372)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
std::cout << (d->remove(212)) << std::endl;
std::cout << (d->insert(18)) << std::endl;
e->printPretty();
std::cout << (b->remove(398)) << std::endl;
std::cout << (e->remove(34)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (c->insert(484)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (a->remove(118)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
std::cout << (c->remove(50)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
std::cout << (a->remove(19)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (b->insert(87)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
e->printPretty();
std::cout << (e->remove(398)) << std::endl;
*d=*e;
std::cout << (b->remove(48)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (e->insert(19)) << std::endl;
*d=*b;
std::cout << (d->insert(196)) << std::endl;
std::cout << (c->remove(19)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
*e=*b;
std::cout << (b->remove(277)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
std::cout << (e->remove(277)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
*e=*e;
std::cout << (e->insert(143)) << std::endl;
c->printPretty();
*a=*b;
*d=*d;
std::cout << (c->insert(398)) << std::endl;
std::cout << (e->insert(143)) << std::endl;
*d=*c;
*d=*a;
std::cout << (e->remove(87)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
std::cout << (c->remove(484)) << std::endl;
d->printPretty();
std::cout << (c->insert(277)) << std::endl;
b->printPretty();
std::cout << (b->remove(192)) << std::endl;
std::cout << (b->insert(391)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
std::cout << (b->remove(108)) << std::endl;
std::cout << (e->remove(247)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
b->printPretty();
*e=*d;
std::cout << (a->insert(19)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (c->insert(327)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (d->insert(408)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->insert(87)) << std::endl;
d->printPretty();
std::cout << (d->insert(162)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
std::cout << (e->remove(87)) << std::endl;
std::cout << (d->insert(474)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->insert(408)) << std::endl;
std::cout << (d->insert(207)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
std::cout << (a->remove(212)) << std::endl;
*d=*a;
std::cout << (e->insert(41)) << std::endl;
a->printPretty();
std::cout << (e->insert(437)) << std::endl;
*c=*e;
std::cout << (d->remove(442)) << std::endl;
d->printPretty();
*b=*a;
*d=*b;
e->printPretty();
b->printPretty();
a->printPretty();
std::cout << (b->insert(235)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (a->insert(48)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
d->printPretty();
std::cout << (b->remove(105)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
d->printPretty();
std::cout << (c->remove(220)) << std::endl;
*a=*b;
std::cout << (e->insert(95)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
a->printPretty();
std::cout << (b->insert(472)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
*a=*c;
std::cout << (b->insert(134)) << std::endl;
*a=*a;
*b=*b;
std::cout << (e->remove(408)) << std::endl;
e->printPretty();
std::cout << (b->remove(408)) << std::endl;
b->printPretty();
std::cout << (b->remove(235)) << std::endl;
*e=*c;
std::cout << (d->remove(165)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (d->insert(182)) << std::endl;
d->printPretty();
std::cout << (d->remove(333)) << std::endl;
std::cout << (e->insert(88)) << std::endl;
std::cout << (b->remove(41)) << std::endl;
std::cout << (a->remove(19)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
c->printPretty();
std::cout << (c->remove(408)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (c->remove(437)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
d->printPretty();
std::cout << (a->remove(53)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (b->insert(446)) << std::endl;
d->printPretty();
std::cout << (b->insert(490)) << std::endl;
std::cout << (d->insert(333)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (d->remove(19)) << std::endl;
*a=*d;
std::cout << (e->remove(41)) << std::endl;
std::cout << (b->insert(332)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
*d=*a;
*e=*e;
b->printPretty();
std::cout << (a->insert(22)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (d->insert(420)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
std::cout << (d->remove(414)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (a->insert(9)) << std::endl;
c->printPretty();
std::cout << (a->remove(9)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
*c=*c;
*b=*d;
std::cout << (b->insert(19)) << std::endl;
std::cout << (e->insert(437)) << std::endl;
*b=*d;
std::cout << (c->insert(19)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->remove(105)) << std::endl;
std::cout << (e->remove(348)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
*a=*c;
std::cout << (c->remove(191)) << std::endl;
e->printPretty();
std::cout << (d->insert(19)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (a->insert(19)) << std::endl;
std::cout << (a->remove(311)) << std::endl;
*e=*d;
*c=*c;
std::cout << (b->insert(19)) << std::endl;
b->printPretty();
std::cout << (d->insert(393)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
*d=*e;
std::cout << (e->insert(140)) << std::endl;
a->printPretty();
std::cout << (b->insert(120)) << std::endl;
d->printPretty();
std::cout << (e->remove(19)) << std::endl;
*b=*c;
std::cout << (d->remove(149)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->insert(19)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
*b=*c;
std::cout << (a->remove(102)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
*a=*c;
std::cout << (d->remove(79)) << std::endl;
b->printPretty();
std::cout << (d->remove(42)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
*e=*c;
std::cout << (a->remove(160)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (c->remove(19)) << std::endl;
std::cout << (b->insert(99)) << std::endl;
b->printPretty();
std::cout << (d->remove(412)) << std::endl;
std::cout << (e->remove(175)) << std::endl;
std::cout << (d->insert(4)) << std::endl;
e->printPretty();
std::cout << (e->insert(19)) << std::endl;
std::cout << (b->remove(99)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
b->printPretty();
*e=*c;
*e=*e;
std::cout << (c->insert(243)) << std::endl;
a->printPretty();
std::cout << (c->insert(243)) << std::endl;
*b=*a;
std::cout << (a->remove(19)) << std::endl;
std::cout << (d->insert(4)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
std::cout << (a->remove(274)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->remove(349)) << std::endl;
*a=*c;
std::cout << (e->remove(322)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
c->printPretty();
std::cout << (c->remove(243)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
a->printPretty();
std::cout << (d->insert(491)) << std::endl;
a->printPretty();
std::cout << (e->remove(245)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (c->remove(77)) << std::endl;
std::cout << (c->insert(67)) << std::endl;
*b=*b;
std::cout << (c->remove(67)) << std::endl;
a->printPretty();
std::cout << (d->remove(491)) << std::endl;
a->printPretty();
std::cout << (a->remove(243)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->remove(26)) << std::endl;
std::cout << (b->insert(266)) << std::endl;
*a=*e;
e->printPretty();
e->printPretty();
std::cout << (b->insert(19)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
*d=*b;
std::cout << (d->insert(493)) << std::endl;
*d=*b;
*c=*a;
std::cout << (e->remove(183)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (b->insert(393)) << std::endl;
std::cout << (d->remove(487)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (b->insert(66)) << std::endl;
std::cout << (a->remove(31)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (b->remove(66)) << std::endl;
std::cout << (b->remove(435)) << std::endl;
d->printPretty();
std::cout << (b->insert(388)) << std::endl;
d->printPretty();
std::cout << (b->insert(393)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
c->printPretty();
std::cout << (a->insert(363)) << std::endl;
std::cout << (b->insert(309)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
b->printPretty();
std::cout << (a->insert(54)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
*a=*a;
a->printPretty();
std::cout << (d->insert(44)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
c->printPretty();
std::cout << (b->insert(18)) << std::endl;
std::cout << (b->remove(393)) << std::endl;
e->printPretty();
*c=*b;
*e=*e;
std::cout << (c->remove(369)) << std::endl;
*e=*c;
std::cout << (c->remove(388)) << std::endl;
*c=*b;
std::cout << (b->insert(388)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
std::cout << (b->remove(348)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
a->printPretty();
std::cout << (e->remove(309)) << std::endl;
*e=*a;
std::cout << (d->insert(82)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
*b=*e;
std::cout << (a->remove(118)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
*b=*c;
d->printPretty();
*a=*a;
std::cout << (d->remove(82)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
std::cout << (e->insert(54)) << std::endl;
*c=*e;
c->printPretty();
a->printPretty();
*d=*d;
*c=*b;
c->printPretty();
*e=*c;
std::cout << (c->remove(439)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
c->printPretty();
std::cout << (b->insert(309)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (b->insert(250)) << std::endl;
std::cout << (c->insert(195)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (c->insert(19)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
std::cout << (e->insert(19)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (e->remove(134)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
*b=*a;
std::cout << (a->insert(352)) << std::endl;
*c=*c;
std::cout << (c->remove(195)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (e->remove(388)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
a->printPretty();
std::cout << (c->remove(87)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
*b=*d;
std::cout << (b->remove(35)) << std::endl;
b->printPretty();
std::cout << (c->remove(309)) << std::endl;
*a=*e;
*d=*a;
std::cout << (d->remove(384)) << std::endl;
*c=*c;
std::cout << (a->remove(121)) << std::endl;
std::cout << (d->remove(360)) << std::endl;
std::cout << (d->insert(121)) << std::endl;
std::cout << (d->remove(18)) << std::endl;
std::cout << (c->insert(469)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
*b=*d;
std::cout << (d->remove(362)) << std::endl;
a->printPretty();
std::cout << (c->remove(20)) << std::endl;
e->printPretty();
*a=*c;
c->printPretty();
c->printPretty();
std::cout << (b->remove(121)) << std::endl;
c->printPretty();
std::cout << (e->insert(121)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
*a=*b;
std::cout << (d->insert(121)) << std::endl;
*c=*a;
*d=*b;
std::cout << (c->remove(323)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (c->insert(18)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
a->printPretty();
std::cout << (d->remove(172)) << std::endl;
b->printPretty();
a->printPretty();
*c=*c;
std::cout << (b->insert(485)) << std::endl;
std::cout << (b->remove(144)) << std::endl;
c->printPretty();
std::cout << (c->remove(479)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
*b=*d;
e->printPretty();
*c=*e;
std::cout << (d->remove(445)) << std::endl;
std::cout << (c->insert(18)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (c->remove(18)) << std::endl;
std::cout << (b->remove(497)) << std::endl;
*c=*d;
std::cout << (b->remove(94)) << std::endl;
std::cout << (a->remove(70)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
*e=*a;
std::cout << (e->insert(285)) << std::endl;
*a=*c;
std::cout << (d->remove(267)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
std::cout << (c->insert(363)) << std::endl;
*b=*c;
std::cout << (d->remove(466)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
std::cout << (e->remove(129)) << std::endl;
std::cout << (b->remove(363)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
std::cout << (d->remove(290)) << std::endl;
*a=*c;
*a=*b;
std::cout << (d->insert(193)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->insert(363)) << std::endl;
*c=*c;
std::cout << (e->insert(55)) << std::endl;
*a=*e;
std::cout << (c->insert(169)) << std::endl;
std::cout << (b->remove(286)) << std::endl;
std::cout << (e->insert(55)) << std::endl;
*a=*c;
a->printPretty();
e->printPretty();
return 0;
}
