#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(96)) << std::endl;
a->printPretty();
std::cout << (a->insert(96)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (d->remove(374)) << std::endl;
a->printPretty();
*b=*a;
*d=*b;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (c->remove(389)) << std::endl;
std::cout << (a->remove(376)) << std::endl;
std::cout << (a->remove(191)) << std::endl;
*a=*e;
b->printPretty();
std::cout << (a->remove(370)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
c->printPretty();
std::cout << (d->remove(110)) << std::endl;
*e=*e;
*d=*e;
*d=*d;
std::cout << (c->remove(493)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (b->remove(494)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
*e=*e;
std::cout << (c->remove(275)) << std::endl;
d->printPretty();
std::cout << (c->insert(12)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
*a=*e;
std::cout << (a->remove(454)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (a->remove(278)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
std::cout << (e->remove(381)) << std::endl;
std::cout << (b->remove(209)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
*e=*e;
std::cout << (e->insert(240)) << std::endl;
std::cout << (b->insert(104)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
b->printPretty();
std::cout << (e->insert(240)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
std::cout << (b->remove(92)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
std::cout << (e->insert(11)) << std::endl;
d->printPretty();
std::cout << (b->insert(5)) << std::endl;
std::cout << (b->insert(5)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (e->remove(240)) << std::endl;
std::cout << (c->remove(166)) << std::endl;
*e=*e;
std::cout << (a->remove(270)) << std::endl;
b->printPretty();
std::cout << (d->remove(104)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (d->remove(5)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->insert(117)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
e->printPretty();
std::cout << (b->insert(195)) << std::endl;
c->printPretty();
std::cout << (b->insert(3)) << std::endl;
e->printPretty();
std::cout << (a->remove(117)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (b->insert(119)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
b->printPretty();
b->printPretty();
*b=*e;
std::cout << (e->insert(14)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
e->printPretty();
std::cout << (a->remove(327)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
*d=*b;
std::cout << (d->remove(237)) << std::endl;
*b=*c;
*a=*d;
std::cout << (b->remove(113)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
*d=*d;
std::cout << (a->insert(6)) << std::endl;
std::cout << (b->insert(152)) << std::endl;
b->printPretty();
std::cout << (c->remove(497)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (e->remove(133)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (e->insert(102)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
c->printPretty();
d->printPretty();
*e=*d;
*d=*a;
std::cout << (c->insert(452)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (a->remove(151)) << std::endl;
*e=*a;
std::cout << (c->insert(113)) << std::endl;
d->printPretty();
a->printPretty();
d->printPretty();
std::cout << (c->insert(452)) << std::endl;
d->printPretty();
*c=*c;
*b=*c;
std::cout << (b->remove(36)) << std::endl;
std::cout << (b->insert(113)) << std::endl;
std::cout << (e->insert(373)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (e->insert(373)) << std::endl;
std::cout << (d->insert(490)) << std::endl;
std::cout << (a->insert(70)) << std::endl;
std::cout << (b->remove(452)) << std::endl;
b->printPretty();
std::cout << (c->insert(400)) << std::endl;
std::cout << (b->insert(113)) << std::endl;
std::cout << (b->insert(243)) << std::endl;
std::cout << (c->remove(296)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
std::cout << (d->remove(59)) << std::endl;
*d=*b;
std::cout << (d->insert(401)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
std::cout << (a->remove(70)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (b->insert(243)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
*b=*b;
*c=*b;
a->printPretty();
c->printPretty();
*a=*d;
std::cout << (e->remove(363)) << std::endl;
std::cout << (a->remove(243)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
d->printPretty();
std::cout << (a->insert(439)) << std::endl;
std::cout << (b->insert(243)) << std::endl;
e->printPretty();
std::cout << (b->insert(389)) << std::endl;
*b=*e;
std::cout << (a->remove(171)) << std::endl;
*d=*b;
*a=*a;
b->printPretty();
std::cout << (e->remove(153)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->insert(204)) << std::endl;
std::cout << (c->remove(113)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (b->remove(103)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
std::cout << (b->remove(204)) << std::endl;
*d=*e;
std::cout << (c->remove(243)) << std::endl;
std::cout << (d->remove(179)) << std::endl;
*a=*a;
*b=*d;
std::cout << (e->remove(497)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
std::cout << (b->remove(311)) << std::endl;
a->printPretty();
std::cout << (a->insert(424)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (e->insert(142)) << std::endl;
std::cout << (a->insert(251)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (a->insert(251)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
c->printPretty();
std::cout << (d->remove(133)) << std::endl;
std::cout << (a->insert(251)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (c->insert(337)) << std::endl;
*a=*c;
std::cout << (e->remove(251)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
e->printPretty();
std::cout << (e->remove(424)) << std::endl;
std::cout << (c->insert(62)) << std::endl;
std::cout << (a->insert(337)) << std::endl;
std::cout << (b->remove(401)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
b->printPretty();
c->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(450)) << std::endl;
d->printPretty();
std::cout << (a->remove(1)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
*e=*c;
a->printPretty();
d->printPretty();
e->printPretty();
b->printPretty();
*b=*d;
std::cout << (d->insert(102)) << std::endl;
std::cout << (a->remove(337)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
*c=*c;
std::cout << (b->insert(102)) << std::endl;
c->printPretty();
std::cout << (d->insert(5)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
std::cout << (a->insert(441)) << std::endl;
std::cout << (d->remove(5)) << std::endl;
std::cout << (c->remove(375)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (b->remove(52)) << std::endl;
std::cout << (a->remove(203)) << std::endl;
*d=*a;
std::cout << (e->insert(144)) << std::endl;
std::cout << (c->remove(337)) << std::endl;
a->printPretty();
std::cout << (d->remove(194)) << std::endl;
c->printPretty();
std::cout << (e->remove(450)) << std::endl;
e->printPretty();
std::cout << (b->remove(299)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->remove(441)) << std::endl;
std::cout << (d->remove(456)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->remove(144)) << std::endl;
c->printPretty();
std::cout << (c->insert(257)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (c->remove(302)) << std::endl;
*d=*b;
std::cout << (b->insert(7)) << std::endl;
std::cout << (e->remove(132)) << std::endl;
std::cout << (d->remove(102)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
*e=*b;
*d=*b;
*b=*a;
e->printPretty();
std::cout << (c->insert(350)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
*b=*e;
std::cout << (b->insert(102)) << std::endl;
std::cout << (a->insert(332)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
std::cout << (e->insert(340)) << std::endl;
std::cout << (d->insert(175)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (e->insert(210)) << std::endl;
*d=*d;
*a=*a;
*c=*d;
std::cout << (c->insert(102)) << std::endl;
std::cout << (d->remove(175)) << std::endl;
std::cout << (c->remove(175)) << std::endl;
std::cout << (a->remove(204)) << std::endl;
std::cout << (d->remove(340)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
*b=*b;
std::cout << (b->remove(258)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
std::cout << (c->remove(340)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
*b=*a;
*c=*d;
std::cout << (d->remove(469)) << std::endl;
*e=*b;
std::cout << (d->insert(102)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(307)) << std::endl;
std::cout << (b->remove(307)) << std::endl;
e->printPretty();
*a=*e;
std::cout << (d->insert(312)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
*d=*d;
std::cout << (c->remove(7)) << std::endl;
std::cout << (d->insert(400)) << std::endl;
std::cout << (e->remove(126)) << std::endl;
e->printPretty();
std::cout << (e->remove(198)) << std::endl;
std::cout << (d->remove(429)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
e->printPretty();
std::cout << (d->insert(102)) << std::endl;
b->printPretty();
std::cout << (d->insert(312)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
std::cout << (c->remove(102)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (a->remove(202)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (b->remove(400)) << std::endl;
a->printPretty();
std::cout << (d->remove(438)) << std::endl;
*d=*d;
*a=*b;
std::cout << (a->insert(65)) << std::endl;
std::cout << (d->insert(400)) << std::endl;
*b=*b;
*d=*c;
std::cout << (a->remove(65)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
b->printPretty();
std::cout << (d->remove(217)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
c->printPretty();
std::cout << (e->insert(251)) << std::endl;
std::cout << (b->remove(199)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
*e=*c;
std::cout << (d->remove(285)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->insert(395)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
*c=*c;
*c=*e;
a->printPretty();
std::cout << (a->remove(7)) << std::endl;
a->printPretty();
std::cout << (e->insert(395)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
*e=*e;
std::cout << (e->remove(395)) << std::endl;
*d=*c;
e->printPretty();
b->printPretty();
std::cout << (a->remove(197)) << std::endl;
std::cout << (a->remove(424)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->insert(395)) << std::endl;
std::cout << (a->remove(328)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
b->printPretty();
*a=*a;
e->printPretty();
std::cout << (a->remove(146)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
e->printPretty();
b->printPretty();
*e=*a;
std::cout << (e->insert(69)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
std::cout << (c->insert(434)) << std::endl;
a->printPretty();
std::cout << (a->insert(310)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->insert(468)) << std::endl;
*b=*d;
*c=*d;
std::cout << (c->remove(84)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
*b=*b;
std::cout << (d->insert(317)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
std::cout << (d->insert(317)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
*b=*e;
std::cout << (d->insert(317)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (b->insert(114)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
std::cout << (b->remove(489)) << std::endl;
std::cout << (d->remove(134)) << std::endl;
a->printPretty();
std::cout << (c->remove(260)) << std::endl;
std::cout << (d->insert(378)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
*a=*e;
std::cout << (b->remove(216)) << std::endl;
std::cout << (a->remove(468)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (e->insert(401)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (e->insert(406)) << std::endl;
std::cout << (e->remove(334)) << std::endl;
std::cout << (b->insert(269)) << std::endl;
std::cout << (c->remove(47)) << std::endl;
*e=*a;
std::cout << (e->insert(66)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->insert(461)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
a->printPretty();
std::cout << (b->insert(407)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->insert(179)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (a->insert(298)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
e->printPretty();
std::cout << (d->remove(314)) << std::endl;
e->printPretty();
std::cout << (b->insert(52)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->insert(475)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->insert(471)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (a->remove(263)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (e->insert(66)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
std::cout << (b->insert(269)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
a->printPretty();
std::cout << (d->insert(379)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
std::cout << (e->remove(17)) << std::endl;
a->printPretty();
*b=*a;
std::cout << (d->insert(379)) << std::endl;
*c=*b;
std::cout << (a->insert(262)) << std::endl;
std::cout << (c->insert(63)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (d->remove(69)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
*d=*b;
std::cout << (b->remove(262)) << std::endl;
std::cout << (c->insert(361)) << std::endl;
e->printPretty();
d->printPretty();
a->printPretty();
std::cout << (e->remove(312)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
*d=*d;
std::cout << (a->insert(222)) << std::endl;
std::cout << (e->remove(433)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
b->printPretty();
std::cout << (b->insert(81)) << std::endl;
std::cout << (a->insert(26)) << std::endl;
*c=*b;
std::cout << (a->insert(155)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (b->insert(312)) << std::endl;
*d=*e;
std::cout << (d->remove(158)) << std::endl;
std::cout << (a->insert(379)) << std::endl;
std::cout << (c->remove(393)) << std::endl;
std::cout << (c->insert(64)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (c->insert(63)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
std::cout << (b->remove(239)) << std::endl;
*e=*d;
*e=*d;
std::cout << (a->remove(325)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
c->printPretty();
std::cout << (b->remove(63)) << std::endl;
std::cout << (b->insert(298)) << std::endl;
std::cout << (b->insert(264)) << std::endl;
std::cout << (c->insert(63)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (a->remove(379)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
b->printPretty();
std::cout << (a->remove(103)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
*b=*d;
b->printPretty();
c->printPretty();
std::cout << (b->insert(359)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
*a=*b;
std::cout << (c->insert(138)) << std::endl;
*e=*c;
std::cout << (d->insert(379)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (a->remove(60)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
a->printPretty();
c->printPretty();
d->printPretty();
b->printPretty();
std::cout << (e->insert(255)) << std::endl;
*e=*d;
std::cout << (d->insert(386)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (c->remove(81)) << std::endl;
a->printPretty();
std::cout << (d->insert(106)) << std::endl;
b->printPretty();
*c=*a;
std::cout << (b->insert(76)) << std::endl;
std::cout << (d->insert(227)) << std::endl;
std::cout << (b->remove(425)) << std::endl;
*e=*c;
std::cout << (c->insert(330)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
std::cout << (e->remove(471)) << std::endl;
e->printPretty();
std::cout << (c->remove(106)) << std::endl;
std::cout << (a->insert(168)) << std::endl;
e->printPretty();
std::cout << (d->insert(325)) << std::endl;
d->printPretty();
e->printPretty();
*e=*d;
std::cout << (c->insert(492)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
d->printPretty();
std::cout << (c->remove(359)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
std::cout << (d->remove(121)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (c->insert(325)) << std::endl;
*d=*d;
std::cout << (e->insert(69)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
*e=*d;
c->printPretty();
*a=*c;
std::cout << (e->insert(60)) << std::endl;
std::cout << (a->remove(406)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
*e=*c;
std::cout << (c->remove(245)) << std::endl;
std::cout << (e->insert(356)) << std::endl;
std::cout << (b->insert(315)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (e->insert(66)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
std::cout << (a->insert(160)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (d->remove(252)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
a->printPretty();
c->printPretty();
e->printPretty();
std::cout << (c->remove(356)) << std::endl;
std::cout << (c->insert(76)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
c->printPretty();
std::cout << (e->insert(60)) << std::endl;
b->printPretty();
std::cout << (a->insert(386)) << std::endl;
std::cout << (a->insert(379)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
std::cout << (e->insert(76)) << std::endl;
std::cout << (a->insert(48)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
*e=*b;
std::cout << (d->remove(379)) << std::endl;
a->printPretty();
std::cout << (d->insert(80)) << std::endl;
c->printPretty();
b->printPretty();
*a=*d;
d->printPretty();
*b=*d;
a->printPretty();
std::cout << (d->remove(69)) << std::endl;
d->printPretty();
std::cout << (e->remove(216)) << std::endl;
std::cout << (c->remove(187)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
*a=*d;
*e=*d;
std::cout << (a->insert(309)) << std::endl;
std::cout << (c->insert(90)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (b->remove(307)) << std::endl;
std::cout << (e->remove(132)) << std::endl;
std::cout << (a->remove(370)) << std::endl;
std::cout << (b->remove(51)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->insert(325)) << std::endl;
d->printPretty();
std::cout << (d->remove(64)) << std::endl;
std::cout << (e->remove(34)) << std::endl;
*d=*a;
std::cout << (e->remove(325)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (a->insert(392)) << std::endl;
e->printPretty();
*d=*e;
std::cout << (d->remove(386)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (d->remove(66)) << std::endl;
*d=*e;
*b=*d;
a->printPretty();
std::cout << (d->remove(106)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
*d=*c;
std::cout << (a->remove(328)) << std::endl;
*d=*b;
std::cout << (c->remove(227)) << std::endl;
c->printPretty();
*c=*b;
*e=*c;
std::cout << (b->insert(325)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
std::cout << (c->remove(392)) << std::endl;
std::cout << (b->remove(60)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
*c=*a;
std::cout << (c->remove(80)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
std::cout << (c->insert(309)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
return 0;
}
