#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
std::cout << (a->remove(226)) << std::endl;
std::cout << (b->insert(100)) << std::endl;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->insert(100)) << std::endl;
*b=*b;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
*b=*c;
*c=*c;
*b=*e;
std::cout << (d->insert(458)) << std::endl;
std::cout << (d->remove(441)) << std::endl;
std::cout << (a->insert(100)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
std::cout << (d->remove(175)) << std::endl;
std::cout << (a->insert(100)) << std::endl;
*a=*e;
std::cout << (e->insert(80)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
std::cout << (e->insert(360)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
*a=*d;
std::cout << (d->remove(458)) << std::endl;
*a=*b;
std::cout << (e->remove(342)) << std::endl;
std::cout << (d->insert(442)) << std::endl;
std::cout << (c->insert(100)) << std::endl;
e->printPretty();
std::cout << (c->remove(260)) << std::endl;
e->printPretty();
*d=*d;
std::cout << (e->insert(344)) << std::endl;
*d=*a;
std::cout << (a->insert(403)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
b->printPretty();
std::cout << (e->remove(497)) << std::endl;
*b=*c;
std::cout << (d->insert(154)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
b->printPretty();
std::cout << (d->insert(154)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (a->insert(463)) << std::endl;
std::cout << (c->remove(100)) << std::endl;
std::cout << (b->remove(453)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
d->printPretty();
std::cout << (a->insert(470)) << std::endl;
std::cout << (b->insert(416)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
*e=*a;
std::cout << (c->insert(38)) << std::endl;
std::cout << (b->insert(100)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
std::cout << (b->remove(100)) << std::endl;
std::cout << (b->remove(208)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
*e=*b;
std::cout << (b->insert(392)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (e->insert(435)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
*a=*d;
std::cout << (c->insert(26)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (e->insert(34)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
d->printPretty();
std::cout << (b->insert(206)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (b->insert(447)) << std::endl;
std::cout << (e->insert(435)) << std::endl;
*b=*e;
std::cout << (b->remove(38)) << std::endl;
*e=*e;
std::cout << (d->remove(234)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (e->remove(34)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (c->remove(26)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
std::cout << (c->insert(340)) << std::endl;
*b=*b;
d->printPretty();
std::cout << (a->insert(495)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
e->printPretty();
std::cout << (d->remove(231)) << std::endl;
*c=*b;
*c=*e;
std::cout << (b->insert(499)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->insert(491)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (d->remove(440)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
std::cout << (e->remove(435)) << std::endl;
*d=*d;
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->insert(90)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
std::cout << (c->remove(38)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
*b=*e;
*c=*e;
c->printPretty();
std::cout << (c->remove(257)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (c->remove(38)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
std::cout << (c->remove(394)) << std::endl;
e->printPretty();
std::cout << (b->insert(38)) << std::endl;
std::cout << (e->insert(65)) << std::endl;
*c=*d;
std::cout << (a->remove(495)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (e->remove(413)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
*d=*c;
std::cout << (c->remove(284)) << std::endl;
std::cout << (a->insert(445)) << std::endl;
*c=*d;
std::cout << (c->remove(342)) << std::endl;
*c=*a;
std::cout << (d->insert(278)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (d->remove(144)) << std::endl;
std::cout << (a->remove(90)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
*d=*a;
std::cout << (c->remove(445)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
*d=*e;
std::cout << (e->insert(65)) << std::endl;
*c=*e;
*b=*d;
std::cout << (b->insert(65)) << std::endl;
c->printPretty();
std::cout << (c->remove(3)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
*a=*b;
std::cout << (d->insert(65)) << std::endl;
*c=*b;
std::cout << (c->insert(6)) << std::endl;
*d=*b;
*c=*b;
a->printPretty();
std::cout << (e->remove(97)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
std::cout << (c->remove(268)) << std::endl;
std::cout << (c->remove(365)) << std::endl;
e->printPretty();
std::cout << (a->insert(22)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
e->printPretty();
std::cout << (a->insert(137)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
c->printPretty();
a->printPretty();
*e=*c;
*c=*a;
*a=*d;
std::cout << (e->remove(259)) << std::endl;
*c=*b;
std::cout << (c->remove(163)) << std::endl;
a->printPretty();
*e=*a;
c->printPretty();
d->printPretty();
*e=*a;
std::cout << (d->insert(301)) << std::endl;
d->printPretty();
std::cout << (e->remove(133)) << std::endl;
std::cout << (b->insert(412)) << std::endl;
*e=*d;
std::cout << (c->remove(137)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
std::cout << (e->insert(301)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
std::cout << (d->remove(475)) << std::endl;
std::cout << (e->remove(301)) << std::endl;
std::cout << (a->insert(436)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (d->remove(301)) << std::endl;
*b=*d;
std::cout << (a->insert(329)) << std::endl;
*a=*c;
std::cout << (d->remove(291)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (b->insert(115)) << std::endl;
*a=*e;
*b=*b;
std::cout << (b->remove(332)) << std::endl;
std::cout << (d->remove(298)) << std::endl;
std::cout << (c->remove(263)) << std::endl;
b->printPretty();
d->printPretty();
e->printPretty();
*c=*e;
d->printPretty();
b->printPretty();
std::cout << (a->insert(118)) << std::endl;
std::cout << (a->remove(341)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
*b=*a;
std::cout << (d->insert(324)) << std::endl;
*c=*b;
std::cout << (b->insert(481)) << std::endl;
*b=*b;
*b=*d;
std::cout << (e->remove(271)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
*c=*e;
std::cout << (a->insert(410)) << std::endl;
*d=*c;
std::cout << (b->remove(194)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
std::cout << (e->remove(205)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
*c=*b;
std::cout << (e->remove(490)) << std::endl;
*a=*b;
a->printPretty();
d->printPretty();
*e=*a;
std::cout << (a->insert(324)) << std::endl;
std::cout << (b->insert(324)) << std::endl;
std::cout << (e->remove(324)) << std::endl;
std::cout << (c->remove(207)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
c->printPretty();
std::cout << (d->insert(135)) << std::endl;
std::cout << (a->insert(324)) << std::endl;
*a=*c;
std::cout << (b->insert(324)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
std::cout << (d->insert(420)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
*c=*a;
std::cout << (c->insert(293)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
std::cout << (b->insert(426)) << std::endl;
std::cout << (c->insert(324)) << std::endl;
std::cout << (d->insert(420)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (a->insert(324)) << std::endl;
std::cout << (c->insert(324)) << std::endl;
*d=*a;
std::cout << (e->remove(100)) << std::endl;
d->printPretty();
std::cout << (b->insert(426)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
*e=*d;
std::cout << (b->insert(117)) << std::endl;
std::cout << (d->remove(34)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (b->remove(324)) << std::endl;
std::cout << (a->insert(324)) << std::endl;
*c=*d;
std::cout << (a->remove(334)) << std::endl;
*d=*d;
std::cout << (c->insert(444)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
c->printPretty();
std::cout << (d->insert(324)) << std::endl;
std::cout << (b->remove(99)) << std::endl;
b->printPretty();
d->printPretty();
c->printPretty();
*d=*b;
std::cout << (c->remove(324)) << std::endl;
std::cout << (e->insert(474)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (a->insert(324)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
e->printPretty();
std::cout << (b->remove(171)) << std::endl;
c->printPretty();
std::cout << (e->remove(463)) << std::endl;
*e=*e;
std::cout << (c->insert(332)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
std::cout << (d->remove(117)) << std::endl;
c->printPretty();
std::cout << (d->remove(369)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
std::cout << (b->remove(124)) << std::endl;
std::cout << (b->insert(117)) << std::endl;
std::cout << (b->remove(354)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
d->printPretty();
*b=*e;
std::cout << (a->insert(285)) << std::endl;
a->printPretty();
*c=*c;
*d=*d;
c->printPretty();
std::cout << (d->remove(165)) << std::endl;
std::cout << (a->remove(285)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (e->insert(474)) << std::endl;
c->printPretty();
std::cout << (e->remove(474)) << std::endl;
b->printPretty();
std::cout << (c->remove(461)) << std::endl;
b->printPretty();
std::cout << (c->remove(154)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (e->insert(295)) << std::endl;
std::cout << (e->remove(324)) << std::endl;
*b=*b;
std::cout << (b->remove(268)) << std::endl;
c->printPretty();
std::cout << (e->remove(110)) << std::endl;
*b=*e;
std::cout << (c->remove(128)) << std::endl;
std::cout << (c->insert(80)) << std::endl;
b->printPretty();
std::cout << (e->insert(268)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
*e=*e;
*a=*b;
c->printPretty();
*e=*c;
std::cout << (a->insert(199)) << std::endl;
b->printPretty();
std::cout << (b->insert(268)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
c->printPretty();
std::cout << (a->remove(268)) << std::endl;
std::cout << (e->remove(57)) << std::endl;
std::cout << (c->remove(346)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
*b=*d;
std::cout << (d->insert(16)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (e->remove(378)) << std::endl;
std::cout << (e->insert(385)) << std::endl;
*e=*b;
std::cout << (a->insert(449)) << std::endl;
std::cout << (c->insert(151)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
b->printPretty();
std::cout << (b->insert(16)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (c->remove(151)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (e->remove(48)) << std::endl;
std::cout << (b->remove(16)) << std::endl;
std::cout << (e->insert(271)) << std::endl;
a->printPretty();
std::cout << (a->remove(449)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
c->printPretty();
std::cout << (b->insert(269)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
d->printPretty();
std::cout << (a->remove(442)) << std::endl;
d->printPretty();
std::cout << (c->remove(406)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
*d=*a;
std::cout << (b->remove(269)) << std::endl;
*d=*e;
*c=*c;
std::cout << (a->insert(146)) << std::endl;
std::cout << (e->insert(16)) << std::endl;
std::cout << (e->remove(449)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (d->insert(16)) << std::endl;
std::cout << (e->remove(113)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
std::cout << (d->remove(34)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
*c=*c;
b->printPretty();
*c=*c;
*a=*a;
a->printPretty();
std::cout << (a->insert(127)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (a->insert(19)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (c->insert(310)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
a->printPretty();
std::cout << (c->insert(75)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
*a=*c;
std::cout << (c->remove(475)) << std::endl;
*e=*b;
std::cout << (a->insert(426)) << std::endl;
std::cout << (a->remove(402)) << std::endl;
std::cout << (e->insert(170)) << std::endl;
e->printPretty();
std::cout << (b->remove(16)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (a->insert(378)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
*e=*b;
std::cout << (a->insert(426)) << std::endl;
a->printPretty();
std::cout << (c->insert(271)) << std::endl;
e->printPretty();
std::cout << (e->remove(418)) << std::endl;
*d=*e;
*b=*e;
std::cout << (c->insert(198)) << std::endl;
std::cout << (b->remove(257)) << std::endl;
c->printPretty();
std::cout << (c->insert(398)) << std::endl;
std::cout << (e->remove(416)) << std::endl;
std::cout << (e->remove(328)) << std::endl;
std::cout << (b->insert(56)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (b->remove(56)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
*e=*d;
std::cout << (b->insert(462)) << std::endl;
std::cout << (a->remove(382)) << std::endl;
a->printPretty();
std::cout << (e->remove(218)) << std::endl;
c->printPretty();
std::cout << (d->remove(56)) << std::endl;
std::cout << (d->remove(458)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (b->insert(94)) << std::endl;
std::cout << (c->remove(198)) << std::endl;
c->printPretty();
std::cout << (b->remove(94)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
*c=*e;
std::cout << (d->insert(327)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
std::cout << (e->remove(462)) << std::endl;
*e=*d;
std::cout << (e->remove(327)) << std::endl;
std::cout << (b->remove(115)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
*c=*b;
std::cout << (d->insert(243)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (d->insert(243)) << std::endl;
*a=*a;
std::cout << (c->remove(462)) << std::endl;
std::cout << (d->remove(327)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
c->printPretty();
std::cout << (c->insert(257)) << std::endl;
b->printPretty();
*c=*d;
*d=*d;
std::cout << (a->insert(128)) << std::endl;
*e=*a;
std::cout << (c->insert(237)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
*b=*b;
*a=*d;
*a=*a;
std::cout << (e->remove(7)) << std::endl;
std::cout << (d->remove(243)) << std::endl;
*a=*d;
*c=*e;
std::cout << (a->insert(130)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (a->remove(174)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
std::cout << (a->remove(121)) << std::endl;
*c=*d;
std::cout << (b->insert(462)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (c->insert(403)) << std::endl;
std::cout << (b->remove(342)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (c->remove(403)) << std::endl;
b->printPretty();
e->printPretty();
*c=*b;
std::cout << (d->insert(223)) << std::endl;
*c=*e;
std::cout << (d->remove(223)) << std::endl;
e->printPretty();
std::cout << (d->remove(195)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (a->remove(474)) << std::endl;
std::cout << (a->insert(28)) << std::endl;
c->printPretty();
std::cout << (c->remove(418)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
d->printPretty();
std::cout << (c->insert(224)) << std::endl;
std::cout << (b->insert(306)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
a->printPretty();
std::cout << (c->insert(8)) << std::endl;
c->printPretty();
std::cout << (c->remove(372)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
c->printPretty();
std::cout << (a->insert(28)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (a->remove(201)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (b->insert(292)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
*d=*d;
std::cout << (c->remove(426)) << std::endl;
std::cout << (c->remove(378)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
std::cout << (c->remove(437)) << std::endl;
std::cout << (b->insert(140)) << std::endl;
c->printPretty();
std::cout << (c->insert(80)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
b->printPretty();
std::cout << (a->insert(442)) << std::endl;
std::cout << (a->insert(48)) << std::endl;
std::cout << (a->insert(48)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
a->printPretty();
*d=*d;
std::cout << (c->remove(258)) << std::endl;
e->printPretty();
std::cout << (c->insert(310)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
b->printPretty();
std::cout << (b->insert(407)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (b->insert(144)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (c->remove(361)) << std::endl;
std::cout << (e->remove(456)) << std::endl;
*a=*e;
std::cout << (e->insert(426)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
*b=*e;
std::cout << (e->remove(310)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
c->printPretty();
std::cout << (c->insert(80)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(422)) << std::endl;
std::cout << (d->remove(372)) << std::endl;
b->printPretty();
std::cout << (b->remove(422)) << std::endl;
*e=*e;
*a=*a;
std::cout << (a->remove(378)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (d->insert(229)) << std::endl;
std::cout << (c->remove(84)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
d->printPretty();
std::cout << (e->insert(131)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
std::cout << (a->insert(455)) << std::endl;
*b=*e;
*a=*d;
a->printPretty();
*b=*c;
c->printPretty();
std::cout << (d->remove(114)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (a->remove(289)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
std::cout << (c->remove(353)) << std::endl;
e->printPretty();
std::cout << (c->insert(128)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (c->remove(383)) << std::endl;
*d=*b;
std::cout << (b->insert(75)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
c->printPretty();
std::cout << (d->remove(304)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (e->insert(131)) << std::endl;
*d=*e;
std::cout << (d->insert(260)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (a->remove(494)) << std::endl;
*c=*b;
*b=*d;
std::cout << (b->insert(131)) << std::endl;
*e=*a;
std::cout << (b->remove(82)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
e->printPretty();
return 0;
}
