#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
a->printPretty();
std::cout << (a->remove(31)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (a->remove(388)) << std::endl;
a->printPretty();
std::cout << (b->remove(374)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->remove(495)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
d->printPretty();
b->printPretty();
e->printPretty();
*d=*e;
std::cout << (d->insert(225)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (d->insert(225)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
*c=*c;
*e=*b;
std::cout << (d->remove(234)) << std::endl;
*b=*d;
std::cout << (e->remove(433)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (c->remove(213)) << std::endl;
*e=*b;
std::cout << (a->insert(180)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (b->insert(225)) << std::endl;
std::cout << (a->remove(92)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
c->printPretty();
b->printPretty();
e->printPretty();
std::cout << (d->insert(225)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
std::cout << (e->insert(225)) << std::endl;
*e=*c;
a->printPretty();
std::cout << (d->insert(225)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
e->printPretty();
std::cout << (b->insert(340)) << std::endl;
std::cout << (c->insert(103)) << std::endl;
c->printPretty();
std::cout << (c->remove(247)) << std::endl;
std::cout << (e->insert(454)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
std::cout << (a->remove(180)) << std::endl;
a->printPretty();
std::cout << (d->insert(332)) << std::endl;
std::cout << (d->remove(484)) << std::endl;
std::cout << (c->remove(103)) << std::endl;
std::cout << (e->insert(29)) << std::endl;
std::cout << (d->insert(205)) << std::endl;
c->printPretty();
std::cout << (b->insert(352)) << std::endl;
*b=*c;
*a=*e;
std::cout << (e->remove(454)) << std::endl;
d->printPretty();
std::cout << (e->remove(354)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(159)) << std::endl;
*e=*d;
b->printPretty();
*b=*b;
*e=*c;
std::cout << (d->insert(225)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
*b=*d;
*e=*e;
*d=*e;
e->printPretty();
e->printPretty();
b->printPretty();
d->printPretty();
*c=*e;
*d=*c;
std::cout << (c->insert(115)) << std::endl;
*b=*d;
std::cout << (c->remove(115)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (a->insert(180)) << std::endl;
std::cout << (a->insert(28)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (c->insert(190)) << std::endl;
*d=*a;
std::cout << (a->remove(290)) << std::endl;
*e=*b;
*d=*e;
d->printPretty();
d->printPretty();
d->printPretty();
std::cout << (a->remove(156)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
*d=*d;
*d=*c;
std::cout << (d->remove(190)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (b->insert(295)) << std::endl;
*e=*b;
std::cout << (a->remove(73)) << std::endl;
*c=*c;
*a=*c;
*c=*c;
std::cout << (b->insert(154)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
std::cout << (b->insert(118)) << std::endl;
*a=*c;
std::cout << (a->remove(126)) << std::endl;
*d=*b;
std::cout << (e->remove(337)) << std::endl;
std::cout << (d->remove(118)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->insert(295)) << std::endl;
std::cout << (c->remove(192)) << std::endl;
a->printPretty();
std::cout << (a->insert(435)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
std::cout << (a->remove(46)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (e->remove(401)) << std::endl;
*e=*b;
std::cout << (e->insert(484)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
std::cout << (a->insert(190)) << std::endl;
*a=*c;
std::cout << (e->insert(13)) << std::endl;
std::cout << (e->insert(13)) << std::endl;
std::cout << (d->remove(202)) << std::endl;
std::cout << (b->insert(295)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (e->remove(50)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
e->printPretty();
std::cout << (b->remove(307)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
std::cout << (d->remove(408)) << std::endl;
*c=*b;
std::cout << (d->insert(190)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->insert(352)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
*a=*e;
std::cout << (c->remove(17)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
std::cout << (c->insert(457)) << std::endl;
std::cout << (b->remove(4)) << std::endl;
std::cout << (e->remove(13)) << std::endl;
a->printPretty();
d->printPretty();
*d=*e;
std::cout << (e->remove(62)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
c->printPretty();
std::cout << (b->remove(52)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
b->printPretty();
std::cout << (a->remove(28)) << std::endl;
*c=*a;
std::cout << (b->remove(433)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
b->printPretty();
std::cout << (b->insert(295)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (a->remove(23)) << std::endl;
std::cout << (b->insert(295)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (c->remove(52)) << std::endl;
*c=*d;
std::cout << (a->insert(161)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
c->printPretty();
std::cout << (c->remove(394)) << std::endl;
std::cout << (c->insert(223)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
std::cout << (c->insert(144)) << std::endl;
*d=*d;
std::cout << (e->remove(295)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
*d=*d;
std::cout << (e->remove(458)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (e->insert(485)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (d->remove(48)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
std::cout << (a->insert(439)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (a->remove(389)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
c->printPretty();
std::cout << (b->insert(222)) << std::endl;
*b=*d;
std::cout << (a->insert(13)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
std::cout << (a->remove(360)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
b->printPretty();
std::cout << (c->insert(154)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
std::cout << (b->remove(49)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
e->printPretty();
std::cout << (a->insert(137)) << std::endl;
std::cout << (e->insert(242)) << std::endl;
std::cout << (a->insert(345)) << std::endl;
std::cout << (c->remove(22)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
*b=*c;
std::cout << (a->insert(232)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->insert(262)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
std::cout << (d->insert(118)) << std::endl;
b->printPretty();
std::cout << (d->remove(33)) << std::endl;
c->printPretty();
std::cout << (d->remove(177)) << std::endl;
e->printPretty();
std::cout << (a->remove(271)) << std::endl;
std::cout << (e->insert(45)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (e->insert(203)) << std::endl;
b->printPretty();
std::cout << (b->remove(262)) << std::endl;
c->printPretty();
std::cout << (c->insert(281)) << std::endl;
std::cout << (c->remove(117)) << std::endl;
*e=*d;
std::cout << (d->insert(262)) << std::endl;
*d=*d;
d->printPretty();
*b=*e;
std::cout << (a->remove(484)) << std::endl;
std::cout << (e->remove(110)) << std::endl;
std::cout << (e->insert(262)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
*b=*d;
e->printPretty();
std::cout << (d->insert(211)) << std::endl;
std::cout << (e->insert(163)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
d->printPretty();
std::cout << (c->remove(281)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
d->printPretty();
std::cout << (b->insert(262)) << std::endl;
a->printPretty();
*e=*a;
*d=*c;
*e=*a;
e->printPretty();
d->printPretty();
std::cout << (d->insert(480)) << std::endl;
e->printPretty();
std::cout << (b->remove(262)) << std::endl;
*c=*c;
std::cout << (c->insert(480)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
*d=*a;
*a=*a;
*b=*c;
*b=*d;
d->printPretty();
std::cout << (d->insert(162)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (e->insert(469)) << std::endl;
*a=*c;
std::cout << (d->insert(33)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (e->remove(161)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
c->printPretty();
std::cout << (d->remove(452)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (b->remove(390)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
*c=*b;
*e=*a;
std::cout << (c->insert(378)) << std::endl;
std::cout << (b->insert(286)) << std::endl;
d->printPretty();
*b=*d;
*d=*a;
*e=*d;
std::cout << (c->remove(189)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (a->insert(147)) << std::endl;
b->printPretty();
c->printPretty();
*e=*d;
std::cout << (b->insert(196)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (b->insert(118)) << std::endl;
std::cout << (c->insert(118)) << std::endl;
std::cout << (b->insert(118)) << std::endl;
std::cout << (c->remove(483)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
d->printPretty();
std::cout << (d->insert(491)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (c->insert(491)) << std::endl;
*e=*d;
std::cout << (d->remove(452)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
*c=*e;
*a=*c;
std::cout << (e->remove(103)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (e->remove(362)) << std::endl;
std::cout << (e->insert(452)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
*c=*b;
std::cout << (d->remove(137)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
a->printPretty();
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(346)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
d->printPretty();
std::cout << (d->insert(13)) << std::endl;
d->printPretty();
std::cout << (a->remove(491)) << std::endl;
e->printPretty();
std::cout << (e->remove(13)) << std::endl;
std::cout << (a->insert(466)) << std::endl;
b->printPretty();
e->printPretty();
*a=*e;
c->printPretty();
std::cout << (c->remove(348)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
a->printPretty();
std::cout << (a->insert(118)) << std::endl;
std::cout << (c->remove(160)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(452)) << std::endl;
std::cout << (c->remove(420)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (c->insert(118)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (a->insert(200)) << std::endl;
std::cout << (a->remove(336)) << std::endl;
std::cout << (a->remove(228)) << std::endl;
e->printPretty();
c->printPretty();
*d=*d;
std::cout << (d->insert(118)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (c->remove(359)) << std::endl;
*e=*e;
std::cout << (a->remove(184)) << std::endl;
std::cout << (a->remove(58)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
a->printPretty();
std::cout << (c->remove(279)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
std::cout << (d->remove(469)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
c->printPretty();
std::cout << (b->insert(273)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
std::cout << (e->insert(266)) << std::endl;
std::cout << (e->insert(272)) << std::endl;
*d=*d;
std::cout << (d->remove(136)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (b->insert(24)) << std::endl;
std::cout << (a->insert(362)) << std::endl;
std::cout << (e->insert(4)) << std::endl;
*e=*a;
std::cout << (e->insert(26)) << std::endl;
std::cout << (d->remove(39)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
std::cout << (c->remove(378)) << std::endl;
std::cout << (b->remove(165)) << std::endl;
d->printPretty();
std::cout << (b->remove(255)) << std::endl;
a->printPretty();
std::cout << (c->insert(491)) << std::endl;
std::cout << (b->remove(178)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (e->remove(222)) << std::endl;
b->printPretty();
std::cout << (d->insert(446)) << std::endl;
std::cout << (b->insert(13)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
std::cout << (e->insert(211)) << std::endl;
*c=*d;
std::cout << (c->remove(123)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (c->remove(139)) << std::endl;
std::cout << (b->remove(67)) << std::endl;
std::cout << (d->remove(151)) << std::endl;
*d=*a;
std::cout << (e->insert(211)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
std::cout << (a->remove(130)) << std::endl;
*b=*a;
std::cout << (c->insert(481)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
std::cout << (d->remove(20)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
std::cout << (e->insert(378)) << std::endl;
*a=*c;
*d=*b;
std::cout << (c->insert(13)) << std::endl;
std::cout << (d->insert(123)) << std::endl;
std::cout << (d->remove(370)) << std::endl;
*c=*c;
*c=*a;
c->printPretty();
b->printPretty();
std::cout << (c->remove(352)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->insert(200)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (c->insert(381)) << std::endl;
std::cout << (d->insert(378)) << std::endl;
std::cout << (e->remove(26)) << std::endl;
std::cout << (e->insert(491)) << std::endl;
std::cout << (e->remove(222)) << std::endl;
std::cout << (c->remove(324)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
e->printPretty();
std::cout << (c->remove(373)) << std::endl;
std::cout << (c->insert(381)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (d->insert(291)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
*b=*d;
std::cout << (d->insert(475)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
*e=*b;
std::cout << (a->remove(103)) << std::endl;
a->printPretty();
e->printPretty();
d->printPretty();
std::cout << (e->remove(123)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
std::cout << (b->insert(24)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
std::cout << (a->remove(45)) << std::endl;
*a=*e;
a->printPretty();
e->printPretty();
std::cout << (e->insert(291)) << std::endl;
std::cout << (d->insert(89)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
e->printPretty();
std::cout << (c->remove(66)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
*d=*a;
*c=*c;
std::cout << (e->insert(104)) << std::endl;
std::cout << (a->remove(345)) << std::endl;
*e=*c;
std::cout << (a->insert(96)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(354)) << std::endl;
*a=*e;
std::cout << (d->remove(207)) << std::endl;
d->printPretty();
std::cout << (a->insert(322)) << std::endl;
std::cout << (e->remove(155)) << std::endl;
std::cout << (b->insert(452)) << std::endl;
a->printPretty();
*b=*a;
*c=*e;
std::cout << (c->remove(26)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
std::cout << (d->remove(125)) << std::endl;
std::cout << (b->insert(472)) << std::endl;
d->printPretty();
std::cout << (d->remove(200)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
*d=*c;
std::cout << (a->insert(118)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (d->remove(378)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
std::cout << (d->insert(253)) << std::endl;
a->printPretty();
std::cout << (c->remove(232)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
a->printPretty();
std::cout << (a->insert(184)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
std::cout << (e->remove(104)) << std::endl;
*c=*c;
std::cout << (e->insert(260)) << std::endl;
std::cout << (e->remove(334)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
b->printPretty();
std::cout << (e->remove(378)) << std::endl;
d->printPretty();
a->printPretty();
b->printPretty();
std::cout << (b->remove(277)) << std::endl;
std::cout << (c->insert(388)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
std::cout << (c->insert(388)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
std::cout << (c->remove(103)) << std::endl;
std::cout << (b->remove(323)) << std::endl;
*e=*b;
std::cout << (d->insert(381)) << std::endl;
std::cout << (e->insert(253)) << std::endl;
std::cout << (a->insert(350)) << std::endl;
std::cout << (c->insert(381)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (a->remove(60)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
std::cout << (c->insert(253)) << std::endl;
std::cout << (d->remove(427)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
*a=*c;
std::cout << (b->insert(80)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (c->remove(309)) << std::endl;
*b=*c;
std::cout << (d->remove(406)) << std::endl;
std::cout << (d->insert(103)) << std::endl;
b->printPretty();
std::cout << (d->insert(481)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
std::cout << (c->insert(381)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
std::cout << (e->remove(446)) << std::endl;
*c=*d;
std::cout << (e->insert(36)) << std::endl;
*e=*b;
e->printPretty();
std::cout << (e->remove(446)) << std::endl;
*e=*d;
std::cout << (c->remove(253)) << std::endl;
std::cout << (c->insert(381)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (a->insert(13)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->insert(452)) << std::endl;
std::cout << (b->remove(353)) << std::endl;
b->printPretty();
a->printPretty();
*d=*e;
c->printPretty();
std::cout << (d->insert(14)) << std::endl;
*d=*b;
std::cout << (a->insert(397)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
b->printPretty();
std::cout << (c->insert(381)) << std::endl;
std::cout << (c->insert(381)) << std::endl;
e->printPretty();
std::cout << (e->insert(446)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (b->insert(446)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
std::cout << (a->insert(358)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
e->printPretty();
std::cout << (e->remove(118)) << std::endl;
std::cout << (a->remove(301)) << std::endl;
std::cout << (a->remove(90)) << std::endl;
c->printPretty();
std::cout << (d->remove(118)) << std::endl;
std::cout << (e->remove(253)) << std::endl;
std::cout << (d->insert(13)) << std::endl;
d->printPretty();
*d=*d;
*b=*e;
std::cout << (c->insert(366)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
*b=*a;
std::cout << (b->insert(358)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (c->insert(185)) << std::endl;
std::cout << (c->remove(185)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (c->remove(358)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (c->remove(360)) << std::endl;
std::cout << (b->insert(446)) << std::endl;
std::cout << (a->remove(388)) << std::endl;
std::cout << (c->remove(212)) << std::endl;
std::cout << (b->insert(397)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (a->insert(359)) << std::endl;
c->printPretty();
std::cout << (e->remove(358)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
std::cout << (c->insert(38)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
d->printPretty();
std::cout << (e->remove(382)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
e->printPretty();
*e=*c;
std::cout << (e->insert(446)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
d->printPretty();
std::cout << (e->remove(446)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (d->insert(431)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
*e=*a;
*a=*a;
std::cout << (b->remove(296)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
d->printPretty();
std::cout << (e->insert(322)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (b->remove(70)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
*b=*b;
std::cout << (c->remove(246)) << std::endl;
d->printPretty();
std::cout << (a->remove(397)) << std::endl;
std::cout << (e->insert(378)) << std::endl;
e->printPretty();
a->printPretty();
*e=*e;
std::cout << (c->insert(184)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
return 0;
}
