#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*b=*a;
std::cout << (b->remove(81)) << std::endl;
std::cout << (b->remove(378)) << std::endl;
a->printPretty();
std::cout << (c->insert(344)) << std::endl;
std::cout << (c->remove(344)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (c->insert(423)) << std::endl;
std::cout << (a->remove(123)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (e->remove(443)) << std::endl;
std::cout << (b->insert(500)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
d->printPretty();
std::cout << (c->insert(423)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
d->printPretty();
std::cout << (b->insert(413)) << std::endl;
std::cout << (c->remove(415)) << std::endl;
*b=*b;
std::cout << (c->remove(369)) << std::endl;
*b=*b;
c->printPretty();
e->printPretty();
std::cout << (a->remove(343)) << std::endl;
std::cout << (c->insert(423)) << std::endl;
std::cout << (e->remove(267)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(465)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
a->printPretty();
std::cout << (e->remove(409)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (d->remove(465)) << std::endl;
std::cout << (c->remove(423)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
std::cout << (b->insert(336)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (b->remove(378)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->remove(304)) << std::endl;
*a=*c;
*c=*a;
std::cout << (b->remove(29)) << std::endl;
std::cout << (e->insert(225)) << std::endl;
d->printPretty();
std::cout << (a->insert(432)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (e->remove(380)) << std::endl;
*a=*b;
std::cout << (b->insert(223)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
std::cout << (e->remove(225)) << std::endl;
std::cout << (a->remove(223)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (a->insert(411)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (c->remove(414)) << std::endl;
std::cout << (a->insert(196)) << std::endl;
*a=*b;
std::cout << (c->remove(470)) << std::endl;
e->printPretty();
std::cout << (e->insert(223)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
std::cout << (a->insert(47)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (a->remove(440)) << std::endl;
std::cout << (c->remove(121)) << std::endl;
e->printPretty();
std::cout << (a->remove(47)) << std::endl;
b->printPretty();
*e=*a;
*e=*a;
std::cout << (e->remove(35)) << std::endl;
std::cout << (c->remove(35)) << std::endl;
std::cout << (d->insert(150)) << std::endl;
std::cout << (d->insert(361)) << std::endl;
std::cout << (a->remove(35)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (d->remove(242)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (b->insert(470)) << std::endl;
*a=*d;
std::cout << (c->insert(236)) << std::endl;
*a=*b;
std::cout << (e->remove(328)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
*b=*b;
*c=*b;
c->printPretty();
std::cout << (a->insert(470)) << std::endl;
std::cout << (c->remove(251)) << std::endl;
d->printPretty();
c->printPretty();
b->printPretty();
std::cout << (a->remove(372)) << std::endl;
*c=*c;
*c=*c;
std::cout << (d->insert(328)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (a->remove(51)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (b->insert(412)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
a->printPretty();
d->printPretty();
*a=*a;
std::cout << (d->remove(88)) << std::endl;
std::cout << (c->insert(49)) << std::endl;
std::cout << (c->insert(49)) << std::endl;
*d=*a;
std::cout << (e->remove(467)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (b->remove(3)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
e->printPretty();
std::cout << (b->remove(113)) << std::endl;
std::cout << (c->remove(49)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
std::cout << (c->remove(336)) << std::endl;
e->printPretty();
std::cout << (c->insert(377)) << std::endl;
d->printPretty();
std::cout << (d->insert(193)) << std::endl;
*c=*b;
a->printPretty();
*c=*e;
std::cout << (c->insert(268)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
*c=*d;
std::cout << (c->insert(63)) << std::endl;
*b=*d;
std::cout << (a->insert(464)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
std::cout << (d->insert(151)) << std::endl;
std::cout << (a->remove(64)) << std::endl;
*e=*d;
*b=*a;
*d=*a;
std::cout << (b->remove(464)) << std::endl;
std::cout << (b->insert(193)) << std::endl;
std::cout << (e->remove(263)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (e->insert(410)) << std::endl;
std::cout << (c->remove(63)) << std::endl;
*b=*c;
*e=*d;
*c=*a;
std::cout << (d->remove(2)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
*a=*d;
std::cout << (a->insert(440)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
d->printPretty();
std::cout << (c->insert(464)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
*e=*a;
std::cout << (b->insert(193)) << std::endl;
std::cout << (b->insert(193)) << std::endl;
std::cout << (a->remove(464)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
*e=*a;
std::cout << (a->insert(361)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
std::cout << (d->remove(193)) << std::endl;
std::cout << (d->remove(467)) << std::endl;
d->printPretty();
std::cout << (c->insert(464)) << std::endl;
e->printPretty();
std::cout << (d->insert(282)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
*c=*b;
b->printPretty();
b->printPretty();
std::cout << (e->insert(183)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
b->printPretty();
b->printPretty();
c->printPretty();
std::cout << (d->insert(282)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
std::cout << (d->remove(464)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
std::cout << (d->remove(282)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
*d=*e;
std::cout << (e->insert(57)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
std::cout << (b->remove(193)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (e->insert(57)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
*b=*c;
std::cout << (d->insert(193)) << std::endl;
*d=*e;
std::cout << (b->remove(209)) << std::endl;
*a=*d;
std::cout << (b->remove(430)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
std::cout << (e->insert(183)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (a->remove(183)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
*c=*c;
std::cout << (a->remove(193)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
*b=*e;
std::cout << (a->insert(481)) << std::endl;
*d=*a;
*c=*b;
*b=*e;
std::cout << (b->remove(183)) << std::endl;
e->printPretty();
std::cout << (b->remove(57)) << std::endl;
std::cout << (a->insert(67)) << std::endl;
std::cout << (a->remove(57)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
std::cout << (d->insert(57)) << std::endl;
e->printPretty();
std::cout << (a->remove(431)) << std::endl;
std::cout << (a->remove(71)) << std::endl;
*b=*b;
std::cout << (d->insert(57)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
*a=*d;
std::cout << (e->remove(439)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
std::cout << (a->insert(10)) << std::endl;
std::cout << (d->remove(481)) << std::endl;
std::cout << (b->remove(193)) << std::endl;
std::cout << (a->remove(324)) << std::endl;
*e=*d;
std::cout << (d->insert(204)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
std::cout << (d->insert(204)) << std::endl;
*d=*a;
std::cout << (c->remove(193)) << std::endl;
*c=*a;
std::cout << (e->remove(277)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
*b=*a;
*c=*c;
std::cout << (d->insert(314)) << std::endl;
*a=*e;
std::cout << (d->insert(146)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (a->insert(103)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
b->printPretty();
std::cout << (a->insert(57)) << std::endl;
std::cout << (e->remove(57)) << std::endl;
c->printPretty();
std::cout << (a->insert(386)) << std::endl;
e->printPretty();
std::cout << (b->insert(331)) << std::endl;
b->printPretty();
std::cout << (b->remove(40)) << std::endl;
d->printPretty();
*e=*b;
std::cout << (e->insert(251)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
std::cout << (e->remove(333)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
*d=*c;
std::cout << (b->insert(57)) << std::endl;
std::cout << (c->remove(491)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (d->remove(85)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
std::cout << (c->insert(64)) << std::endl;
*c=*a;
std::cout << (c->insert(57)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
std::cout << (d->remove(57)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (a->insert(386)) << std::endl;
*d=*e;
std::cout << (d->insert(251)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (a->remove(10)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (b->insert(481)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
*c=*c;
*e=*b;
*a=*e;
*a=*c;
std::cout << (e->remove(10)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
std::cout << (c->remove(386)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
*e=*a;
*b=*c;
d->printPretty();
std::cout << (b->remove(332)) << std::endl;
std::cout << (b->insert(354)) << std::endl;
c->printPretty();
std::cout << (a->insert(103)) << std::endl;
std::cout << (e->remove(317)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (d->insert(1)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (e->insert(57)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
c->printPretty();
std::cout << (c->insert(481)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
e->printPretty();
c->printPretty();
b->printPretty();
b->printPretty();
std::cout << (c->remove(110)) << std::endl;
std::cout << (e->remove(57)) << std::endl;
*e=*c;
*c=*a;
std::cout << (c->remove(377)) << std::endl;
*b=*d;
std::cout << (b->remove(57)) << std::endl;
std::cout << (b->insert(37)) << std::endl;
std::cout << (c->insert(289)) << std::endl;
*a=*a;
std::cout << (b->remove(374)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (d->insert(481)) << std::endl;
std::cout << (e->insert(177)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
*c=*b;
d->printPretty();
b->printPretty();
*d=*d;
std::cout << (a->remove(10)) << std::endl;
d->printPretty();
std::cout << (b->remove(37)) << std::endl;
std::cout << (d->insert(57)) << std::endl;
*b=*d;
*e=*a;
a->printPretty();
std::cout << (c->insert(37)) << std::endl;
*b=*d;
std::cout << (e->insert(103)) << std::endl;
c->printPretty();
std::cout << (e->insert(322)) << std::endl;
std::cout << (e->insert(483)) << std::endl;
*c=*e;
*c=*b;
d->printPretty();
c->printPretty();
std::cout << (e->insert(254)) << std::endl;
b->printPretty();
std::cout << (b->remove(481)) << std::endl;
std::cout << (e->insert(231)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
std::cout << (d->insert(57)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
std::cout << (a->insert(78)) << std::endl;
std::cout << (e->remove(161)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
*d=*b;
std::cout << (e->remove(241)) << std::endl;
std::cout << (b->remove(244)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
*b=*a;
*c=*c;
std::cout << (d->insert(341)) << std::endl;
d->printPretty();
*c=*e;
b->printPretty();
std::cout << (d->remove(55)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (d->insert(400)) << std::endl;
std::cout << (c->insert(237)) << std::endl;
*b=*c;
std::cout << (d->remove(57)) << std::endl;
*b=*c;
*e=*a;
std::cout << (a->insert(306)) << std::endl;
std::cout << (e->insert(481)) << std::endl;
e->printPretty();
std::cout << (d->remove(400)) << std::endl;
c->printPretty();
std::cout << (a->insert(57)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
std::cout << (c->insert(44)) << std::endl;
*a=*e;
std::cout << (c->insert(140)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (e->insert(358)) << std::endl;
std::cout << (b->insert(309)) << std::endl;
std::cout << (e->insert(241)) << std::endl;
std::cout << (a->remove(57)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
b->printPretty();
std::cout << (b->remove(314)) << std::endl;
c->printPretty();
std::cout << (c->insert(341)) << std::endl;
*b=*a;
std::cout << (d->insert(341)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
*e=*c;
std::cout << (e->remove(342)) << std::endl;
*e=*a;
std::cout << (d->insert(17)) << std::endl;
*a=*c;
*e=*b;
*d=*e;
d->printPretty();
b->printPretty();
std::cout << (d->insert(481)) << std::endl;
a->printPretty();
std::cout << (d->insert(33)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
std::cout << (c->remove(201)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
b->printPretty();
std::cout << (e->remove(286)) << std::endl;
*a=*b;
std::cout << (d->remove(241)) << std::endl;
c->printPretty();
std::cout << (b->insert(304)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
*b=*b;
std::cout << (c->insert(236)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
*d=*b;
std::cout << (e->insert(103)) << std::endl;
b->printPretty();
b->printPretty();
*e=*b;
e->printPretty();
std::cout << (c->remove(379)) << std::endl;
std::cout << (b->remove(304)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
d->printPretty();
std::cout << (e->remove(464)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
std::cout << (c->insert(467)) << std::endl;
std::cout << (b->remove(241)) << std::endl;
std::cout << (c->remove(467)) << std::endl;
*d=*d;
*c=*a;
b->printPretty();
std::cout << (a->insert(103)) << std::endl;
*d=*b;
std::cout << (a->insert(78)) << std::endl;
a->printPretty();
*c=*e;
b->printPretty();
std::cout << (d->insert(289)) << std::endl;
*b=*b;
std::cout << (e->insert(481)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (e->remove(481)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (b->insert(279)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (d->remove(289)) << std::endl;
*b=*e;
a->printPretty();
*b=*c;
b->printPretty();
std::cout << (b->insert(186)) << std::endl;
std::cout << (d->insert(481)) << std::endl;
*d=*b;
std::cout << (b->insert(78)) << std::endl;
std::cout << (d->insert(241)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
*b=*a;
std::cout << (a->insert(481)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
d->printPretty();
std::cout << (c->remove(304)) << std::endl;
*d=*b;
b->printPretty();
std::cout << (a->remove(497)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
std::cout << (a->insert(403)) << std::endl;
std::cout << (c->insert(147)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->remove(241)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
*d=*a;
*c=*b;
std::cout << (c->remove(171)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
std::cout << (d->insert(387)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
e->printPretty();
std::cout << (b->insert(78)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (b->insert(103)) << std::endl;
*e=*a;
std::cout << (d->insert(403)) << std::endl;
e->printPretty();
std::cout << (c->remove(415)) << std::endl;
*b=*e;
std::cout << (c->remove(6)) << std::endl;
std::cout << (a->insert(476)) << std::endl;
d->printPretty();
std::cout << (d->insert(189)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
std::cout << (e->insert(241)) << std::endl;
c->printPretty();
std::cout << (c->remove(489)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
b->printPretty();
std::cout << (a->insert(241)) << std::endl;
d->printPretty();
std::cout << (e->insert(6)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->remove(103)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
std::cout << (b->remove(103)) << std::endl;
std::cout << (e->remove(156)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (d->remove(32)) << std::endl;
b->printPretty();
std::cout << (c->remove(495)) << std::endl;
*e=*d;
std::cout << (c->insert(481)) << std::endl;
std::cout << (a->insert(78)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (a->insert(185)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
d->printPretty();
c->printPretty();
d->printPretty();
*d=*b;
std::cout << (a->insert(481)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->insert(78)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
a->printPretty();
std::cout << (d->remove(241)) << std::endl;
*a=*c;
std::cout << (d->insert(481)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (b->insert(239)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
std::cout << (a->insert(78)) << std::endl;
std::cout << (b->insert(78)) << std::endl;
std::cout << (d->remove(481)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
*e=*b;
e->printPretty();
std::cout << (b->insert(492)) << std::endl;
*a=*b;
*a=*c;
std::cout << (d->insert(218)) << std::endl;
std::cout << (e->insert(355)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (b->remove(239)) << std::endl;
*d=*a;
std::cout << (e->remove(495)) << std::endl;
b->printPretty();
std::cout << (e->remove(225)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
a->printPretty();
*e=*c;
*e=*a;
std::cout << (b->insert(492)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
*b=*d;
std::cout << (d->insert(43)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
std::cout << (e->remove(403)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (b->remove(248)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (d->insert(43)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (e->insert(248)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
std::cout << (a->insert(403)) << std::endl;
*b=*c;
c->printPretty();
*a=*b;
a->printPretty();
*d=*d;
a->printPretty();
std::cout << (c->insert(248)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
c->printPretty();
std::cout << (d->insert(333)) << std::endl;
a->printPretty();
std::cout << (b->remove(248)) << std::endl;
std::cout << (c->insert(113)) << std::endl;
std::cout << (d->remove(333)) << std::endl;
std::cout << (e->insert(241)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
std::cout << (c->insert(81)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->remove(367)) << std::endl;
std::cout << (e->remove(248)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
e->printPretty();
std::cout << (a->remove(176)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
std::cout << (a->remove(279)) << std::endl;
std::cout << (d->remove(29)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
std::cout << (c->insert(309)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
e->printPretty();
std::cout << (b->remove(61)) << std::endl;
*e=*c;
std::cout << (d->insert(495)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
c->printPretty();
std::cout << (c->insert(495)) << std::endl;
c->printPretty();
std::cout << (a->remove(78)) << std::endl;
*c=*d;
return 0;
}
