#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(69)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (a->remove(99)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (a->insert(292)) << std::endl;
*a=*b;
std::cout << (b->insert(36)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
*a=*a;
std::cout << (b->insert(36)) << std::endl;
b->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (b->insert(36)) << std::endl;
*d=*d;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*c=*e;
*e=*b;
std::cout << (b->remove(318)) << std::endl;
a->printPretty();
std::cout << (e->insert(36)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (e->insert(36)) << std::endl;
b->printPretty();
std::cout << (b->remove(180)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (e->insert(211)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
a->printPretty();
std::cout << (c->insert(369)) << std::endl;
*d=*e;
std::cout << (b->insert(65)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
*a=*e;
std::cout << (a->remove(36)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (e->insert(211)) << std::endl;
std::cout << (e->insert(211)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
std::cout << (c->insert(124)) << std::endl;
std::cout << (c->remove(324)) << std::endl;
std::cout << (b->remove(369)) << std::endl;
a->printPretty();
std::cout << (c->remove(369)) << std::endl;
c->printPretty();
std::cout << (e->remove(451)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
*a=*b;
std::cout << (a->remove(86)) << std::endl;
std::cout << (e->insert(127)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
b->printPretty();
*b=*c;
c->printPretty();
std::cout << (e->insert(36)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
std::cout << (c->remove(216)) << std::endl;
d->printPretty();
std::cout << (b->remove(307)) << std::endl;
std::cout << (e->insert(127)) << std::endl;
*d=*c;
std::cout << (c->insert(73)) << std::endl;
std::cout << (d->remove(58)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (c->remove(153)) << std::endl;
*a=*e;
std::cout << (a->insert(315)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
b->printPretty();
*b=*a;
std::cout << (a->remove(315)) << std::endl;
*e=*c;
e->printPretty();
*d=*e;
std::cout << (c->remove(265)) << std::endl;
*a=*a;
*d=*a;
std::cout << (a->insert(289)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (c->remove(105)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
c->printPretty();
std::cout << (e->remove(124)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (d->remove(211)) << std::endl;
std::cout << (c->insert(124)) << std::endl;
*c=*a;
e->printPretty();
b->printPretty();
e->printPretty();
std::cout << (b->remove(375)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (a->insert(463)) << std::endl;
std::cout << (e->remove(415)) << std::endl;
*e=*e;
std::cout << (d->insert(136)) << std::endl;
std::cout << (d->remove(200)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (d->remove(387)) << std::endl;
std::cout << (e->remove(124)) << std::endl;
*a=*b;
std::cout << (c->insert(463)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (b->remove(127)) << std::endl;
*e=*d;
std::cout << (d->insert(257)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (b->remove(315)) << std::endl;
c->printPretty();
std::cout << (e->insert(397)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
e->printPretty();
std::cout << (a->remove(211)) << std::endl;
std::cout << (a->insert(181)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (b->remove(33)) << std::endl;
*a=*a;
std::cout << (d->insert(257)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
*b=*b;
std::cout << (e->remove(365)) << std::endl;
*c=*e;
std::cout << (a->remove(315)) << std::endl;
*b=*b;
std::cout << (e->insert(59)) << std::endl;
std::cout << (c->insert(127)) << std::endl;
*d=*a;
std::cout << (b->insert(397)) << std::endl;
e->printPretty();
a->printPretty();
a->printPretty();
std::cout << (d->remove(127)) << std::endl;
*c=*e;
std::cout << (e->remove(257)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
*b=*a;
std::cout << (d->insert(280)) << std::endl;
std::cout << (e->remove(28)) << std::endl;
a->printPretty();
std::cout << (e->insert(397)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
*c=*d;
std::cout << (e->insert(326)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
*e=*c;
std::cout << (e->insert(486)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
std::cout << (c->remove(236)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
std::cout << (b->remove(127)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (c->remove(280)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
*a=*c;
std::cout << (c->insert(122)) << std::endl;
std::cout << (d->remove(160)) << std::endl;
std::cout << (c->insert(69)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
std::cout << (e->remove(84)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
e->printPretty();
c->printPretty();
d->printPretty();
d->printPretty();
std::cout << (d->remove(93)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (d->remove(274)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
*d=*e;
std::cout << (e->insert(486)) << std::endl;
std::cout << (b->remove(61)) << std::endl;
d->printPretty();
std::cout << (a->insert(426)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
*b=*b;
*c=*e;
std::cout << (b->remove(299)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (a->insert(105)) << std::endl;
*a=*d;
*d=*a;
std::cout << (c->insert(486)) << std::endl;
std::cout << (a->remove(438)) << std::endl;
*c=*e;
*d=*a;
*e=*a;
std::cout << (c->insert(236)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (b->insert(280)) << std::endl;
e->printPretty();
*c=*d;
b->printPretty();
*e=*c;
*e=*b;
*d=*c;
e->printPretty();
*a=*d;
std::cout << (a->remove(292)) << std::endl;
*d=*b;
std::cout << (d->remove(166)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
std::cout << (d->remove(139)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (b->remove(280)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (a->remove(316)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
*a=*b;
std::cout << (c->insert(39)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (a->insert(262)) << std::endl;
std::cout << (c->remove(280)) << std::endl;
e->printPretty();
std::cout << (a->insert(211)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->remove(486)) << std::endl;
c->printPretty();
*d=*e;
e->printPretty();
e->printPretty();
*c=*a;
std::cout << (a->remove(211)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
*e=*c;
std::cout << (a->insert(58)) << std::endl;
std::cout << (d->insert(92)) << std::endl;
std::cout << (d->insert(150)) << std::endl;
c->printPretty();
*d=*b;
*b=*e;
std::cout << (b->remove(388)) << std::endl;
std::cout << (b->remove(362)) << std::endl;
*a=*d;
std::cout << (c->insert(287)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->insert(150)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
d->printPretty();
std::cout << (c->remove(262)) << std::endl;
std::cout << (d->remove(224)) << std::endl;
*d=*b;
std::cout << (a->remove(224)) << std::endl;
std::cout << (c->remove(280)) << std::endl;
*d=*a;
std::cout << (d->remove(211)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
std::cout << (a->insert(136)) << std::endl;
std::cout << (b->insert(486)) << std::endl;
*d=*a;
std::cout << (b->remove(486)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (a->insert(227)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
*a=*b;
std::cout << (b->remove(422)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
*d=*d;
*a=*a;
std::cout << (d->remove(249)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
b->printPretty();
std::cout << (b->remove(150)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
d->printPretty();
a->printPretty();
b->printPretty();
std::cout << (d->remove(425)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
*d=*b;
std::cout << (d->insert(262)) << std::endl;
std::cout << (b->insert(262)) << std::endl;
std::cout << (e->insert(421)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
*a=*b;
*c=*b;
std::cout << (e->insert(280)) << std::endl;
std::cout << (a->remove(446)) << std::endl;
c->printPretty();
std::cout << (d->insert(262)) << std::endl;
std::cout << (d->remove(262)) << std::endl;
e->printPretty();
std::cout << (b->remove(163)) << std::endl;
std::cout << (a->remove(296)) << std::endl;
std::cout << (d->remove(198)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
*b=*e;
std::cout << (d->remove(316)) << std::endl;
e->printPretty();
*a=*a;
std::cout << (d->insert(26)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
*e=*d;
std::cout << (d->insert(351)) << std::endl;
std::cout << (c->insert(35)) << std::endl;
d->printPretty();
std::cout << (c->insert(262)) << std::endl;
std::cout << (e->insert(262)) << std::endl;
std::cout << (e->remove(262)) << std::endl;
std::cout << (a->insert(32)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
*a=*b;
std::cout << (c->remove(335)) << std::endl;
e->printPretty();
std::cout << (b->insert(254)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
std::cout << (a->remove(50)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
b->printPretty();
std::cout << (b->insert(432)) << std::endl;
*e=*d;
std::cout << (e->remove(10)) << std::endl;
b->printPretty();
std::cout << (e->remove(444)) << std::endl;
std::cout << (e->insert(262)) << std::endl;
e->printPretty();
std::cout << (d->remove(60)) << std::endl;
std::cout << (d->insert(499)) << std::endl;
std::cout << (b->insert(288)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (d->remove(23)) << std::endl;
a->printPretty();
*d=*d;
*b=*c;
a->printPretty();
std::cout << (d->remove(16)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
d->printPretty();
*a=*c;
std::cout << (d->insert(438)) << std::endl;
*a=*d;
*d=*d;
std::cout << (b->insert(444)) << std::endl;
e->printPretty();
std::cout << (a->insert(426)) << std::endl;
*d=*a;
e->printPretty();
*d=*e;
std::cout << (e->insert(17)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (b->insert(262)) << std::endl;
std::cout << (a->insert(214)) << std::endl;
std::cout << (d->remove(221)) << std::endl;
*d=*d;
std::cout << (c->insert(229)) << std::endl;
std::cout << (d->remove(10)) << std::endl;
*d=*e;
std::cout << (e->remove(352)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
*a=*b;
d->printPretty();
*a=*d;
c->printPretty();
std::cout << (b->insert(280)) << std::endl;
std::cout << (a->insert(25)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
*e=*a;
std::cout << (d->remove(426)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (d->insert(2)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
std::cout << (a->insert(351)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (d->insert(83)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
std::cout << (a->insert(244)) << std::endl;
a->printPretty();
std::cout << (b->remove(200)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (e->remove(421)) << std::endl;
*b=*d;
std::cout << (c->remove(150)) << std::endl;
b->printPretty();
std::cout << (b->insert(25)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
std::cout << (c->remove(421)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (c->remove(262)) << std::endl;
std::cout << (a->remove(236)) << std::endl;
*a=*b;
std::cout << (a->insert(49)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
e->printPretty();
std::cout << (a->insert(499)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (a->insert(20)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
e->printPretty();
std::cout << (e->insert(122)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
*a=*d;
std::cout << (a->insert(192)) << std::endl;
*b=*a;
std::cout << (a->remove(225)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
std::cout << (d->insert(400)) << std::endl;
b->printPretty();
std::cout << (a->remove(192)) << std::endl;
*d=*b;
std::cout << (e->insert(179)) << std::endl;
std::cout << (a->insert(351)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
std::cout << (b->remove(262)) << std::endl;
*a=*e;
std::cout << (e->insert(329)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (a->remove(49)) << std::endl;
a->printPretty();
std::cout << (c->remove(323)) << std::endl;
std::cout << (c->remove(459)) << std::endl;
a->printPretty();
std::cout << (e->insert(362)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
c->printPretty();
std::cout << (a->remove(111)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (d->remove(25)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (a->insert(34)) << std::endl;
std::cout << (e->remove(428)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
*d=*b;
a->printPretty();
*d=*a;
std::cout << (c->insert(280)) << std::endl;
e->printPretty();
std::cout << (a->insert(362)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (a->remove(138)) << std::endl;
std::cout << (b->insert(346)) << std::endl;
std::cout << (a->insert(122)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
a->printPretty();
std::cout << (c->remove(84)) << std::endl;
std::cout << (a->insert(34)) << std::endl;
std::cout << (b->insert(25)) << std::endl;
b->printPretty();
std::cout << (e->remove(305)) << std::endl;
std::cout << (a->remove(330)) << std::endl;
*a=*c;
std::cout << (d->remove(377)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (e->insert(348)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (a->remove(309)) << std::endl;
std::cout << (a->insert(156)) << std::endl;
std::cout << (b->insert(192)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
a->printPretty();
std::cout << (a->insert(152)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (d->insert(486)) << std::endl;
*d=*a;
*a=*a;
std::cout << (e->insert(144)) << std::endl;
std::cout << (d->insert(70)) << std::endl;
std::cout << (e->remove(495)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
*e=*d;
std::cout << (a->insert(410)) << std::endl;
std::cout << (b->insert(192)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (a->remove(362)) << std::endl;
b->printPretty();
std::cout << (e->insert(73)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
a->printPretty();
std::cout << (e->remove(371)) << std::endl;
std::cout << (b->remove(430)) << std::endl;
d->printPretty();
std::cout << (d->remove(410)) << std::endl;
std::cout << (c->remove(94)) << std::endl;
c->printPretty();
e->printPretty();
c->printPretty();
b->printPretty();
std::cout << (d->insert(152)) << std::endl;
b->printPretty();
*a=*b;
std::cout << (b->remove(278)) << std::endl;
std::cout << (d->remove(380)) << std::endl;
*c=*a;
std::cout << (e->insert(156)) << std::endl;
std::cout << (a->remove(225)) << std::endl;
std::cout << (e->insert(124)) << std::endl;
std::cout << (b->remove(346)) << std::endl;
std::cout << (a->insert(301)) << std::endl;
std::cout << (b->insert(157)) << std::endl;
a->printPretty();
std::cout << (a->insert(301)) << std::endl;
std::cout << (e->insert(156)) << std::endl;
std::cout << (c->remove(201)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
std::cout << (d->remove(499)) << std::endl;
*c=*d;
std::cout << (a->remove(301)) << std::endl;
std::cout << (b->insert(125)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
std::cout << (e->insert(14)) << std::endl;
*b=*a;
std::cout << (c->remove(296)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
std::cout << (b->remove(244)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
b->printPretty();
std::cout << (e->insert(124)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
std::cout << (c->insert(147)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
std::cout << (d->remove(362)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
d->printPretty();
std::cout << (d->insert(239)) << std::endl;
std::cout << (e->remove(410)) << std::endl;
a->printPretty();
std::cout << (e->remove(124)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (e->insert(362)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
std::cout << (e->remove(113)) << std::endl;
std::cout << (d->insert(486)) << std::endl;
std::cout << (a->insert(289)) << std::endl;
std::cout << (b->insert(20)) << std::endl;
std::cout << (b->insert(289)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
std::cout << (e->insert(40)) << std::endl;
std::cout << (a->insert(40)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
b->printPretty();
std::cout << (c->insert(458)) << std::endl;
a->printPretty();
std::cout << (c->insert(462)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
std::cout << (d->remove(280)) << std::endl;
std::cout << (a->insert(40)) << std::endl;
*c=*e;
*a=*a;
std::cout << (d->remove(428)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
c->printPretty();
std::cout << (c->insert(322)) << std::endl;
std::cout << (c->insert(362)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (c->remove(391)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->remove(468)) << std::endl;
d->printPretty();
std::cout << (c->remove(355)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
std::cout << (b->remove(289)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
std::cout << (e->remove(448)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (c->insert(109)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
*b=*a;
b->printPretty();
c->printPretty();
std::cout << (a->remove(192)) << std::endl;
a->printPretty();
std::cout << (e->insert(359)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
e->printPretty();
std::cout << (e->remove(14)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
*c=*b;
std::cout << (b->remove(338)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
e->printPretty();
std::cout << (a->remove(343)) << std::endl;
*c=*a;
std::cout << (e->remove(353)) << std::endl;
std::cout << (a->remove(314)) << std::endl;
a->printPretty();
std::cout << (d->insert(486)) << std::endl;
a->printPretty();
std::cout << (c->insert(115)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
e->printPretty();
std::cout << (b->insert(244)) << std::endl;
std::cout << (b->insert(261)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (e->insert(360)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
*a=*b;
*d=*c;
std::cout << (b->remove(236)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (e->insert(240)) << std::endl;
d->printPretty();
std::cout << (c->remove(289)) << std::endl;
*c=*e;
std::cout << (e->insert(23)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
std::cout << (e->insert(100)) << std::endl;
std::cout << (d->insert(267)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (e->insert(74)) << std::endl;
*c=*a;
*d=*d;
std::cout << (a->remove(244)) << std::endl;
std::cout << (b->insert(75)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
std::cout << (c->remove(40)) << std::endl;
*e=*a;
*c=*e;
std::cout << (a->remove(40)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (b->insert(383)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
std::cout << (c->insert(80)) << std::endl;
std::cout << (a->insert(80)) << std::endl;
*c=*e;
std::cout << (b->insert(68)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
std::cout << (b->insert(68)) << std::endl;
std::cout << (b->remove(210)) << std::endl;
*d=*b;
std::cout << (d->remove(278)) << std::endl;
std::cout << (e->remove(80)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
std::cout << (b->remove(278)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
e->printPretty();
std::cout << (a->insert(278)) << std::endl;
std::cout << (b->insert(289)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (e->insert(16)) << std::endl;
std::cout << (d->insert(40)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (e->remove(84)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
e->printPretty();
return 0;
}
