#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(67)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
b->printPretty();
*a=*b;
*b=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (b->remove(255)) << std::endl;
b->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (d->insert(23)) << std::endl;
std::cout << (e->insert(206)) << std::endl;
*e=*e;
std::cout << (d->remove(143)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (a->remove(244)) << std::endl;
a->printPretty();
std::cout << (a->insert(165)) << std::endl;
std::cout << (a->insert(165)) << std::endl;
*d=*d;
std::cout << (e->remove(435)) << std::endl;
std::cout << (d->remove(132)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
*e=*a;
std::cout << (b->remove(285)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
std::cout << (a->insert(426)) << std::endl;
a->printPretty();
std::cout << (e->insert(128)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->insert(165)) << std::endl;
e->printPretty();
std::cout << (d->insert(319)) << std::endl;
*a=*a;
std::cout << (a->insert(410)) << std::endl;
*b=*a;
std::cout << (d->remove(268)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
e->printPretty();
std::cout << (d->insert(319)) << std::endl;
std::cout << (e->insert(211)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (e->insert(165)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
b->printPretty();
std::cout << (c->remove(165)) << std::endl;
c->printPretty();
std::cout << (c->remove(250)) << std::endl;
std::cout << (c->insert(394)) << std::endl;
b->printPretty();
std::cout << (b->remove(91)) << std::endl;
c->printPretty();
std::cout << (b->insert(69)) << std::endl;
std::cout << (b->remove(363)) << std::endl;
std::cout << (c->remove(40)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (b->remove(429)) << std::endl;
std::cout << (c->insert(394)) << std::endl;
*d=*c;
std::cout << (a->remove(130)) << std::endl;
std::cout << (c->insert(394)) << std::endl;
*e=*d;
std::cout << (c->insert(394)) << std::endl;
std::cout << (c->insert(394)) << std::endl;
*b=*b;
std::cout << (d->remove(362)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (a->remove(70)) << std::endl;
*d=*a;
d->printPretty();
*b=*c;
std::cout << (e->remove(234)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
*b=*b;
e->printPretty();
b->printPretty();
std::cout << (d->remove(410)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
std::cout << (b->remove(394)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
*b=*c;
std::cout << (d->insert(224)) << std::endl;
*e=*d;
*d=*c;
*d=*c;
*d=*e;
std::cout << (c->remove(404)) << std::endl;
std::cout << (e->insert(182)) << std::endl;
*a=*c;
std::cout << (b->insert(404)) << std::endl;
std::cout << (e->remove(224)) << std::endl;
std::cout << (c->remove(15)) << std::endl;
std::cout << (a->remove(415)) << std::endl;
d->printPretty();
std::cout << (d->insert(165)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
std::cout << (e->insert(426)) << std::endl;
std::cout << (e->remove(388)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
*c=*c;
*e=*e;
*a=*d;
std::cout << (b->remove(294)) << std::endl;
std::cout << (d->insert(262)) << std::endl;
std::cout << (e->insert(422)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
e->printPretty();
std::cout << (b->remove(394)) << std::endl;
std::cout << (a->insert(67)) << std::endl;
std::cout << (e->insert(182)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (e->insert(271)) << std::endl;
*a=*c;
std::cout << (a->insert(394)) << std::endl;
*b=*b;
std::cout << (d->remove(458)) << std::endl;
*e=*b;
*a=*c;
*b=*a;
std::cout << (e->insert(485)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
b->printPretty();
std::cout << (b->remove(352)) << std::endl;
std::cout << (c->remove(142)) << std::endl;
std::cout << (c->remove(415)) << std::endl;
*c=*b;
std::cout << (b->remove(394)) << std::endl;
*c=*b;
std::cout << (b->remove(120)) << std::endl;
a->printPretty();
std::cout << (d->insert(192)) << std::endl;
std::cout << (b->remove(400)) << std::endl;
a->printPretty();
a->printPretty();
*d=*b;
std::cout << (c->insert(427)) << std::endl;
a->printPretty();
std::cout << (b->insert(395)) << std::endl;
c->printPretty();
std::cout << (c->insert(288)) << std::endl;
std::cout << (c->insert(427)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
std::cout << (c->remove(142)) << std::endl;
*a=*b;
std::cout << (b->insert(395)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (c->remove(427)) << std::endl;
*d=*a;
std::cout << (b->insert(452)) << std::endl;
std::cout << (c->remove(439)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
*c=*d;
std::cout << (a->insert(395)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (a->insert(395)) << std::endl;
e->printPretty();
std::cout << (c->insert(427)) << std::endl;
c->printPretty();
*a=*c;
*c=*b;
std::cout << (a->insert(230)) << std::endl;
*c=*c;
std::cout << (e->insert(485)) << std::endl;
std::cout << (e->remove(381)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
d->printPretty();
std::cout << (e->insert(485)) << std::endl;
c->printPretty();
std::cout << (c->remove(452)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
std::cout << (b->insert(452)) << std::endl;
*a=*c;
*d=*c;
std::cout << (c->insert(395)) << std::endl;
*e=*e;
std::cout << (d->insert(395)) << std::endl;
std::cout << (c->insert(163)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (b->remove(395)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (d->insert(139)) << std::endl;
std::cout << (d->remove(139)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->remove(353)) << std::endl;
*d=*c;
std::cout << (b->remove(452)) << std::endl;
a->printPretty();
std::cout << (b->insert(106)) << std::endl;
std::cout << (a->insert(295)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(401)) << std::endl;
std::cout << (c->insert(163)) << std::endl;
*b=*d;
std::cout << (c->insert(395)) << std::endl;
*b=*c;
std::cout << (d->remove(278)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (c->insert(45)) << std::endl;
std::cout << (c->remove(361)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
*b=*e;
std::cout << (e->remove(397)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
*d=*d;
std::cout << (b->remove(318)) << std::endl;
a->printPretty();
std::cout << (e->remove(387)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
std::cout << (d->insert(95)) << std::endl;
std::cout << (b->insert(40)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
std::cout << (e->remove(466)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
d->printPretty();
std::cout << (d->remove(163)) << std::endl;
std::cout << (c->insert(45)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (d->insert(95)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (a->remove(398)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
c->printPretty();
std::cout << (c->insert(395)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
std::cout << (c->remove(45)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
b->printPretty();
a->printPretty();
*d=*e;
std::cout << (c->remove(395)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (b->insert(163)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
std::cout << (b->insert(282)) << std::endl;
*c=*d;
*a=*b;
std::cout << (c->remove(187)) << std::endl;
std::cout << (d->remove(27)) << std::endl;
std::cout << (e->insert(385)) << std::endl;
std::cout << (c->remove(338)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
std::cout << (d->remove(240)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (e->insert(385)) << std::endl;
std::cout << (d->insert(330)) << std::endl;
*e=*b;
std::cout << (d->remove(122)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (a->insert(56)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
std::cout << (d->insert(51)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
*d=*c;
std::cout << (d->insert(7)) << std::endl;
std::cout << (b->remove(376)) << std::endl;
*a=*e;
std::cout << (b->insert(208)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
e->printPretty();
std::cout << (d->remove(7)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
*a=*b;
std::cout << (e->insert(40)) << std::endl;
std::cout << (a->remove(275)) << std::endl;
std::cout << (a->insert(40)) << std::endl;
std::cout << (c->insert(415)) << std::endl;
e->printPretty();
std::cout << (d->insert(498)) << std::endl;
*d=*d;
std::cout << (d->remove(28)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (b->insert(398)) << std::endl;
std::cout << (b->remove(337)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
std::cout << (c->remove(415)) << std::endl;
c->printPretty();
std::cout << (e->remove(443)) << std::endl;
*c=*c;
std::cout << (b->remove(208)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
*a=*c;
std::cout << (b->insert(40)) << std::endl;
std::cout << (e->remove(389)) << std::endl;
*b=*e;
std::cout << (e->remove(163)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
b->printPretty();
std::cout << (e->remove(282)) << std::endl;
b->printPretty();
std::cout << (e->insert(395)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
std::cout << (e->remove(40)) << std::endl;
*c=*b;
std::cout << (d->insert(327)) << std::endl;
std::cout << (d->remove(327)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
*d=*a;
std::cout << (c->remove(154)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
*a=*e;
c->printPretty();
std::cout << (b->remove(416)) << std::endl;
a->printPretty();
std::cout << (b->insert(395)) << std::endl;
*e=*e;
std::cout << (a->remove(395)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (b->insert(71)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
std::cout << (b->insert(163)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
c->printPretty();
std::cout << (c->remove(164)) << std::endl;
std::cout << (a->remove(376)) << std::endl;
*b=*c;
std::cout << (b->insert(271)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
c->printPretty();
std::cout << (b->remove(171)) << std::endl;
std::cout << (c->remove(301)) << std::endl;
e->printPretty();
std::cout << (a->remove(409)) << std::endl;
*d=*e;
std::cout << (b->remove(271)) << std::endl;
std::cout << (b->remove(40)) << std::endl;
std::cout << (a->insert(301)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
a->printPretty();
std::cout << (c->remove(70)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (c->remove(376)) << std::endl;
std::cout << (c->insert(40)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (a->remove(439)) << std::endl;
std::cout << (c->remove(40)) << std::endl;
std::cout << (c->remove(168)) << std::endl;
std::cout << (d->remove(481)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
c->printPretty();
std::cout << (d->remove(195)) << std::endl;
*a=*d;
std::cout << (b->insert(373)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
*a=*b;
*c=*d;
std::cout << (a->remove(59)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->remove(139)) << std::endl;
b->printPretty();
std::cout << (e->insert(331)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->insert(376)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
d->printPretty();
std::cout << (a->remove(282)) << std::endl;
std::cout << (b->remove(441)) << std::endl;
e->printPretty();
std::cout << (c->insert(141)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
std::cout << (e->insert(70)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
std::cout << (c->remove(415)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
a->printPretty();
std::cout << (d->remove(416)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
c->printPretty();
b->printPretty();
d->printPretty();
*e=*b;
e->printPretty();
std::cout << (e->insert(70)) << std::endl;
std::cout << (b->remove(373)) << std::endl;
std::cout << (e->insert(282)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (a->insert(107)) << std::endl;
std::cout << (b->remove(459)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
std::cout << (b->insert(217)) << std::endl;
d->printPretty();
std::cout << (e->remove(376)) << std::endl;
b->printPretty();
std::cout << (c->insert(36)) << std::endl;
*a=*e;
std::cout << (c->remove(464)) << std::endl;
std::cout << (c->remove(36)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
*a=*a;
b->printPretty();
b->printPretty();
*b=*a;
*b=*c;
std::cout << (b->remove(465)) << std::endl;
std::cout << (d->insert(51)) << std::endl;
b->printPretty();
std::cout << (d->remove(445)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
*b=*d;
std::cout << (a->insert(459)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->insert(51)) << std::endl;
std::cout << (a->insert(70)) << std::endl;
std::cout << (e->remove(406)) << std::endl;
d->printPretty();
std::cout << (c->insert(179)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
*a=*b;
*b=*c;
std::cout << (a->remove(124)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (a->insert(51)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
std::cout << (a->remove(378)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
std::cout << (b->insert(149)) << std::endl;
std::cout << (d->insert(51)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
*b=*e;
std::cout << (b->insert(230)) << std::endl;
d->printPretty();
std::cout << (e->insert(481)) << std::endl;
std::cout << (b->insert(230)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
*a=*a;
*d=*e;
std::cout << (e->remove(70)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
d->printPretty();
*c=*e;
std::cout << (c->insert(147)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
std::cout << (d->insert(308)) << std::endl;
std::cout << (b->insert(350)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
*e=*b;
std::cout << (c->remove(320)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
b->printPretty();
std::cout << (d->insert(414)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
*e=*c;
std::cout << (b->remove(414)) << std::endl;
std::cout << (d->insert(51)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (e->remove(414)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
std::cout << (c->insert(147)) << std::endl;
std::cout << (a->remove(42)) << std::endl;
std::cout << (e->remove(63)) << std::endl;
std::cout << (d->remove(51)) << std::endl;
*e=*d;
*c=*e;
std::cout << (d->remove(308)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
std::cout << (d->insert(301)) << std::endl;
a->printPretty();
std::cout << (d->remove(354)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (a->insert(426)) << std::endl;
std::cout << (a->insert(426)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
c->printPretty();
d->printPretty();
*a=*c;
std::cout << (d->remove(481)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
*d=*e;
std::cout << (d->insert(414)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
*e=*d;
std::cout << (d->insert(360)) << std::endl;
c->printPretty();
std::cout << (b->insert(325)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (d->insert(227)) << std::endl;
std::cout << (c->remove(70)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
b->printPretty();
std::cout << (b->insert(17)) << std::endl;
a->printPretty();
std::cout << (e->remove(386)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
std::cout << (c->remove(443)) << std::endl;
std::cout << (b->insert(28)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
*e=*c;
*b=*c;
std::cout << (e->insert(16)) << std::endl;
std::cout << (b->insert(50)) << std::endl;
*d=*d;
std::cout << (a->remove(70)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
*a=*b;
*e=*e;
std::cout << (b->remove(50)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
std::cout << (b->insert(481)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
c->printPretty();
std::cout << (d->remove(360)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
*e=*a;
std::cout << (b->remove(294)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
std::cout << (e->insert(50)) << std::endl;
std::cout << (e->insert(385)) << std::endl;
std::cout << (a->remove(68)) << std::endl;
std::cout << (e->remove(486)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
b->printPretty();
*b=*c;
*d=*c;
std::cout << (e->insert(50)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
std::cout << (a->insert(370)) << std::endl;
std::cout << (a->insert(50)) << std::endl;
e->printPretty();
std::cout << (c->remove(308)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->remove(261)) << std::endl;
*e=*d;
std::cout << (b->remove(16)) << std::endl;
std::cout << (b->insert(121)) << std::endl;
e->printPretty();
d->printPretty();
*e=*b;
*a=*e;
*e=*c;
c->printPretty();
std::cout << (d->remove(414)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (e->insert(93)) << std::endl;
c->printPretty();
std::cout << (e->remove(162)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->insert(462)) << std::endl;
std::cout << (a->remove(300)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (a->insert(367)) << std::endl;
c->printPretty();
std::cout << (b->remove(345)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
c->printPretty();
std::cout << (a->insert(68)) << std::endl;
e->printPretty();
*c=*c;
b->printPretty();
std::cout << (a->insert(379)) << std::endl;
e->printPretty();
std::cout << (b->insert(308)) << std::endl;
std::cout << (b->insert(49)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (b->remove(390)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
c->printPretty();
std::cout << (b->insert(327)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
*c=*c;
*e=*e;
std::cout << (a->insert(303)) << std::endl;
*b=*b;
std::cout << (d->insert(481)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
b->printPretty();
std::cout << (d->insert(411)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
d->printPretty();
*a=*e;
std::cout << (c->insert(212)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
std::cout << (e->remove(201)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (a->insert(93)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
d->printPretty();
std::cout << (b->insert(308)) << std::endl;
a->printPretty();
std::cout << (d->insert(441)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
std::cout << (a->insert(167)) << std::endl;
std::cout << (c->remove(456)) << std::endl;
b->printPretty();
std::cout << (d->remove(281)) << std::endl;
std::cout << (b->remove(294)) << std::endl;
c->printPretty();
*a=*b;
*c=*e;
e->printPretty();
std::cout << (a->insert(308)) << std::endl;
*b=*d;
std::cout << (c->remove(481)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
a->printPretty();
std::cout << (e->insert(90)) << std::endl;
std::cout << (e->remove(300)) << std::endl;
b->printPretty();
a->printPretty();
*a=*d;
*e=*a;
std::cout << (a->insert(164)) << std::endl;
std::cout << (d->insert(389)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
std::cout << (b->remove(190)) << std::endl;
std::cout << (a->remove(180)) << std::endl;
*c=*d;
*d=*a;
c->printPretty();
d->printPretty();
std::cout << (d->insert(164)) << std::endl;
a->printPretty();
std::cout << (e->insert(183)) << std::endl;
return 0;
}
