#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (c->remove(397)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (e->insert(65)) << std::endl;
b->printPretty();
std::cout << (a->remove(222)) << std::endl;
*c=*a;
std::cout << (b->remove(453)) << std::endl;
*e=*b;
*e=*d;
std::cout << (a->insert(117)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
std::cout << (a->remove(117)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (e->insert(300)) << std::endl;
d->printPretty();
std::cout << (b->insert(253)) << std::endl;
std::cout << (b->insert(214)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
std::cout << (c->insert(157)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
std::cout << (a->remove(467)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
std::cout << (e->remove(424)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
d->printPretty();
std::cout << (b->remove(214)) << std::endl;
*d=*a;
std::cout << (d->insert(194)) << std::endl;
*e=*a;
std::cout << (c->remove(157)) << std::endl;
*c=*a;
std::cout << (a->insert(226)) << std::endl;
e->printPretty();
e->printPretty();
a->printPretty();
std::cout << (d->remove(452)) << std::endl;
std::cout << (b->remove(454)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
b->printPretty();
std::cout << (a->remove(292)) << std::endl;
*c=*e;
std::cout << (b->remove(253)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (c->insert(298)) << std::endl;
*d=*a;
*b=*d;
std::cout << (b->remove(480)) << std::endl;
std::cout << (a->insert(169)) << std::endl;
c->printPretty();
std::cout << (d->insert(365)) << std::endl;
*a=*c;
std::cout << (e->remove(237)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
b->printPretty();
std::cout << (e->insert(330)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->remove(391)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
c->printPretty();
std::cout << (d->remove(298)) << std::endl;
*a=*a;
c->printPretty();
*e=*c;
std::cout << (c->remove(298)) << std::endl;
c->printPretty();
std::cout << (e->remove(298)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (e->remove(312)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (e->remove(84)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
*b=*e;
std::cout << (a->insert(194)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (d->insert(194)) << std::endl;
std::cout << (d->remove(298)) << std::endl;
*b=*b;
std::cout << (b->remove(318)) << std::endl;
*e=*b;
std::cout << (d->insert(154)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (c->remove(328)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (b->insert(168)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->insert(262)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
*d=*c;
b->printPretty();
*b=*c;
std::cout << (c->remove(131)) << std::endl;
*c=*d;
std::cout << (c->remove(95)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (d->insert(500)) << std::endl;
a->printPretty();
std::cout << (d->insert(500)) << std::endl;
std::cout << (b->insert(479)) << std::endl;
std::cout << (a->insert(439)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
d->printPretty();
std::cout << (b->remove(479)) << std::endl;
std::cout << (a->remove(227)) << std::endl;
std::cout << (e->remove(41)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
*a=*d;
std::cout << (b->remove(372)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
c->printPretty();
std::cout << (b->insert(265)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
*a=*e;
std::cout << (d->remove(376)) << std::endl;
e->printPretty();
*a=*a;
std::cout << (d->insert(497)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
std::cout << (d->remove(115)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
b->printPretty();
std::cout << (c->remove(155)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
b->printPretty();
e->printPretty();
c->printPretty();
std::cout << (b->insert(395)) << std::endl;
c->printPretty();
std::cout << (d->insert(416)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (c->remove(487)) << std::endl;
std::cout << (d->remove(17)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
a->printPretty();
std::cout << (a->insert(8)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
c->printPretty();
d->printPretty();
*d=*d;
std::cout << (e->remove(2)) << std::endl;
std::cout << (a->remove(5)) << std::endl;
std::cout << (b->insert(50)) << std::endl;
std::cout << (a->insert(117)) << std::endl;
std::cout << (b->insert(217)) << std::endl;
std::cout << (a->remove(117)) << std::endl;
c->printPretty();
std::cout << (c->remove(395)) << std::endl;
std::cout << (a->insert(334)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
std::cout << (d->insert(146)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->remove(76)) << std::endl;
d->printPretty();
std::cout << (a->insert(176)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
*a=*d;
std::cout << (c->remove(435)) << std::endl;
*b=*b;
std::cout << (b->remove(51)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
std::cout << (e->remove(120)) << std::endl;
b->printPretty();
*b=*a;
c->printPretty();
std::cout << (d->insert(172)) << std::endl;
c->printPretty();
std::cout << (e->insert(155)) << std::endl;
d->printPretty();
std::cout << (c->insert(457)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
*b=*c;
std::cout << (a->remove(431)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
*e=*b;
std::cout << (d->remove(172)) << std::endl;
std::cout << (d->remove(146)) << std::endl;
b->printPretty();
std::cout << (b->remove(220)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
*b=*a;
std::cout << (d->remove(301)) << std::endl;
*b=*e;
std::cout << (a->insert(350)) << std::endl;
c->printPretty();
std::cout << (d->insert(278)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
e->printPretty();
std::cout << (a->insert(341)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (a->insert(292)) << std::endl;
std::cout << (a->insert(204)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->insert(218)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
*d=*e;
*a=*d;
std::cout << (e->insert(384)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
std::cout << (d->insert(92)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
*c=*d;
std::cout << (c->insert(294)) << std::endl;
std::cout << (b->remove(428)) << std::endl;
std::cout << (d->remove(250)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
std::cout << (a->remove(144)) << std::endl;
std::cout << (e->insert(384)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
*a=*e;
*e=*a;
b->printPretty();
*e=*a;
std::cout << (c->insert(86)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (e->remove(293)) << std::endl;
b->printPretty();
std::cout << (c->insert(457)) << std::endl;
std::cout << (d->remove(92)) << std::endl;
*b=*a;
std::cout << (d->insert(457)) << std::endl;
std::cout << (b->remove(18)) << std::endl;
*d=*c;
std::cout << (c->insert(115)) << std::endl;
b->printPretty();
std::cout << (a->remove(384)) << std::endl;
*a=*d;
*a=*d;
std::cout << (b->remove(290)) << std::endl;
d->printPretty();
std::cout << (d->insert(87)) << std::endl;
std::cout << (b->insert(384)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
*c=*d;
std::cout << (a->remove(213)) << std::endl;
std::cout << (d->insert(140)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
*e=*a;
d->printPretty();
std::cout << (d->remove(417)) << std::endl;
std::cout << (a->remove(475)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (e->insert(294)) << std::endl;
b->printPretty();
std::cout << (b->insert(50)) << std::endl;
std::cout << (b->insert(384)) << std::endl;
std::cout << (e->remove(3)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
std::cout << (b->insert(384)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
*d=*e;
*d=*a;
*a=*c;
*b=*d;
std::cout << (d->remove(67)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
b->printPretty();
std::cout << (a->remove(86)) << std::endl;
a->printPretty();
*e=*b;
std::cout << (b->insert(206)) << std::endl;
d->printPretty();
b->printPretty();
d->printPretty();
b->printPretty();
std::cout << (a->remove(65)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
std::cout << (e->insert(86)) << std::endl;
*e=*d;
std::cout << (b->insert(181)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (c->remove(352)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (e->remove(376)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
*e=*a;
std::cout << (d->insert(294)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
std::cout << (c->insert(20)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (e->remove(189)) << std::endl;
std::cout << (e->remove(199)) << std::endl;
*c=*b;
std::cout << (e->remove(133)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (d->remove(457)) << std::endl;
std::cout << (c->remove(280)) << std::endl;
std::cout << (c->remove(86)) << std::endl;
b->printPretty();
std::cout << (b->insert(280)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
std::cout << (d->insert(55)) << std::endl;
e->printPretty();
std::cout << (c->insert(207)) << std::endl;
e->printPretty();
std::cout << (e->remove(383)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
e->printPretty();
std::cout << (a->insert(470)) << std::endl;
*b=*c;
*d=*e;
*a=*c;
std::cout << (d->insert(87)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
e->printPretty();
c->printPretty();
*c=*b;
*e=*b;
std::cout << (d->insert(457)) << std::endl;
std::cout << (b->remove(294)) << std::endl;
a->printPretty();
std::cout << (e->remove(157)) << std::endl;
std::cout << (d->remove(457)) << std::endl;
e->printPretty();
std::cout << (d->insert(304)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (b->insert(324)) << std::endl;
std::cout << (a->insert(250)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->remove(206)) << std::endl;
std::cout << (a->insert(442)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
std::cout << (d->remove(207)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (a->insert(92)) << std::endl;
*d=*e;
std::cout << (a->insert(267)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
d->printPretty();
std::cout << (b->insert(324)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
c->printPretty();
std::cout << (a->insert(92)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
std::cout << (d->insert(62)) << std::endl;
std::cout << (e->insert(206)) << std::endl;
b->printPretty();
std::cout << (e->remove(141)) << std::endl;
*d=*a;
std::cout << (b->insert(50)) << std::endl;
std::cout << (d->insert(380)) << std::endl;
std::cout << (b->remove(207)) << std::endl;
std::cout << (c->remove(250)) << std::endl;
std::cout << (c->remove(385)) << std::endl;
std::cout << (a->insert(271)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
std::cout << (d->remove(442)) << std::endl;
d->printPretty();
*c=*e;
std::cout << (a->remove(271)) << std::endl;
*d=*c;
std::cout << (b->insert(250)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (c->insert(314)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
std::cout << (e->remove(67)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (c->remove(207)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
b->printPretty();
d->printPretty();
c->printPretty();
std::cout << (e->insert(402)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
*b=*c;
*b=*d;
b->printPretty();
std::cout << (b->remove(314)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
c->printPretty();
e->printPretty();
c->printPretty();
std::cout << (c->insert(407)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (c->insert(312)) << std::endl;
*b=*d;
std::cout << (a->remove(267)) << std::endl;
std::cout << (e->remove(124)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (d->remove(294)) << std::endl;
a->printPretty();
std::cout << (d->remove(49)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
std::cout << (c->remove(198)) << std::endl;
*a=*a;
std::cout << (d->remove(407)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
*b=*d;
std::cout << (e->insert(195)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
std::cout << (b->remove(314)) << std::endl;
*a=*a;
std::cout << (b->insert(181)) << std::endl;
a->printPretty();
std::cout << (a->remove(126)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
*a=*b;
*b=*a;
*c=*c;
std::cout << (c->remove(311)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
std::cout << (d->insert(250)) << std::endl;
e->printPretty();
std::cout << (b->remove(206)) << std::endl;
*c=*c;
std::cout << (e->remove(402)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (a->insert(63)) << std::endl;
std::cout << (a->remove(222)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (e->insert(65)) << std::endl;
std::cout << (e->remove(206)) << std::endl;
*c=*d;
std::cout << (e->insert(92)) << std::endl;
std::cout << (b->insert(181)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
std::cout << (c->insert(248)) << std::endl;
*c=*e;
std::cout << (a->remove(387)) << std::endl;
*c=*b;
b->printPretty();
std::cout << (d->insert(206)) << std::endl;
e->printPretty();
std::cout << (a->remove(290)) << std::endl;
*e=*c;
*c=*a;
*b=*b;
std::cout << (e->insert(276)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (e->remove(4)) << std::endl;
d->printPretty();
std::cout << (b->insert(355)) << std::endl;
std::cout << (b->remove(181)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
*e=*b;
std::cout << (c->insert(36)) << std::endl;
c->printPretty();
std::cout << (e->insert(355)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (b->remove(154)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
a->printPretty();
std::cout << (a->remove(260)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (e->insert(296)) << std::endl;
std::cout << (d->remove(143)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
e->printPretty();
std::cout << (e->insert(338)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (e->insert(180)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(116)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (a->remove(181)) << std::endl;
*d=*b;
std::cout << (a->remove(63)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
std::cout << (e->remove(73)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
std::cout << (c->remove(181)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (c->insert(206)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(180)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (b->remove(313)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (d->insert(264)) << std::endl;
*d=*b;
std::cout << (c->insert(206)) << std::endl;
*b=*a;
*c=*b;
*c=*a;
std::cout << (d->remove(370)) << std::endl;
*d=*c;
std::cout << (d->remove(410)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
d->printPretty();
std::cout << (e->insert(180)) << std::endl;
std::cout << (a->insert(165)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
std::cout << (e->remove(20)) << std::endl;
*c=*d;
*e=*c;
std::cout << (a->remove(165)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
*c=*e;
d->printPretty();
*b=*c;
std::cout << (c->remove(99)) << std::endl;
b->printPretty();
std::cout << (c->insert(380)) << std::endl;
*b=*d;
std::cout << (e->insert(264)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (d->insert(421)) << std::endl;
e->printPretty();
std::cout << (c->remove(380)) << std::endl;
*b=*a;
*b=*c;
a->printPretty();
*c=*b;
std::cout << (e->insert(99)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
*a=*d;
c->printPretty();
b->printPretty();
std::cout << (d->insert(99)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
std::cout << (d->insert(129)) << std::endl;
std::cout << (d->insert(129)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
*d=*c;
b->printPretty();
*a=*c;
*e=*c;
a->printPretty();
std::cout << (a->insert(104)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
*a=*a;
std::cout << (c->insert(234)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (d->remove(41)) << std::endl;
std::cout << (d->insert(2)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (d->insert(2)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
d->printPretty();
std::cout << (c->remove(234)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (e->remove(64)) << std::endl;
*c=*c;
std::cout << (b->insert(6)) << std::endl;
std::cout << (b->remove(398)) << std::endl;
*a=*c;
std::cout << (a->insert(239)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (d->remove(285)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (e->remove(326)) << std::endl;
*c=*b;
std::cout << (c->insert(6)) << std::endl;
*c=*c;
std::cout << (a->remove(360)) << std::endl;
*a=*d;
std::cout << (c->insert(6)) << std::endl;
*e=*b;
std::cout << (a->insert(2)) << std::endl;
std::cout << (e->remove(98)) << std::endl;
std::cout << (c->remove(6)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
std::cout << (a->insert(2)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
*a=*e;
std::cout << (a->insert(330)) << std::endl;
b->printPretty();
std::cout << (d->insert(2)) << std::endl;
std::cout << (b->insert(6)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
e->printPretty();
std::cout << (e->insert(6)) << std::endl;
*e=*b;
std::cout << (e->remove(33)) << std::endl;
std::cout << (e->remove(6)) << std::endl;
*c=*e;
std::cout << (d->remove(2)) << std::endl;
std::cout << (d->insert(176)) << std::endl;
std::cout << (b->remove(110)) << std::endl;
d->printPretty();
std::cout << (d->insert(176)) << std::endl;
std::cout << (d->remove(176)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->insert(43)) << std::endl;
*d=*d;
std::cout << (c->remove(43)) << std::endl;
std::cout << (c->remove(174)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
std::cout << (a->insert(97)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (d->insert(416)) << std::endl;
std::cout << (a->remove(330)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
*a=*d;
std::cout << (d->remove(416)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
std::cout << (b->insert(58)) << std::endl;
c->printPretty();
std::cout << (d->remove(369)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (b->remove(33)) << std::endl;
e->printPretty();
std::cout << (d->insert(438)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
d->printPretty();
std::cout << (d->remove(131)) << std::endl;
*b=*e;
d->printPretty();
std::cout << (a->insert(66)) << std::endl;
std::cout << (a->remove(351)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
*d=*a;
std::cout << (e->insert(316)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (d->remove(218)) << std::endl;
c->printPretty();
std::cout << (b->insert(227)) << std::endl;
return 0;
}
