#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(373)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (b->remove(368)) << std::endl;
*e=*b;
std::cout << (d->insert(206)) << std::endl;
b->printPretty();
std::cout << (c->remove(202)) << std::endl;
std::cout << (a->remove(308)) << std::endl;
std::cout << (d->insert(206)) << std::endl;
*b=*a;
d->printPretty();
c->printPretty();
std::cout << (a->remove(373)) << std::endl;
c->printPretty();
std::cout << (a->remove(253)) << std::endl;
std::cout << (b->insert(373)) << std::endl;
e->printPretty();
a->printPretty();
*e=*b;
b->printPretty();
b->printPretty();
std::cout << (d->remove(185)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (d->remove(206)) << std::endl;
b->printPretty();
*c=*c;
*d=*a;
std::cout << (c->insert(373)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->insert(288)) << std::endl;
a->printPretty();
std::cout << (c->remove(288)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (d->remove(43)) << std::endl;
*d=*b;
std::cout << (a->remove(339)) << std::endl;
std::cout << (a->remove(475)) << std::endl;
std::cout << (a->insert(412)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
e->printPretty();
std::cout << (e->remove(373)) << std::endl;
*d=*d;
std::cout << (a->remove(302)) << std::endl;
std::cout << (a->remove(22)) << std::endl;
e->printPretty();
std::cout << (a->remove(412)) << std::endl;
std::cout << (d->remove(374)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
std::cout << (b->remove(373)) << std::endl;
*d=*a;
std::cout << (b->remove(313)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
c->printPretty();
*e=*e;
*d=*c;
std::cout << (a->remove(443)) << std::endl;
std::cout << (c->insert(361)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
std::cout << (d->remove(343)) << std::endl;
std::cout << (e->insert(480)) << std::endl;
std::cout << (e->remove(480)) << std::endl;
std::cout << (b->insert(436)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
b->printPretty();
std::cout << (a->insert(450)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (d->insert(221)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (a->insert(273)) << std::endl;
*c=*b;
std::cout << (a->insert(273)) << std::endl;
d->printPretty();
*e=*b;
*d=*a;
*a=*d;
*c=*c;
std::cout << (b->insert(265)) << std::endl;
*b=*d;
std::cout << (b->insert(273)) << std::endl;
*a=*d;
std::cout << (a->remove(450)) << std::endl;
*a=*e;
std::cout << (e->remove(115)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
c->printPretty();
std::cout << (a->remove(265)) << std::endl;
std::cout << (a->insert(43)) << std::endl;
std::cout << (a->remove(169)) << std::endl;
*c=*d;
std::cout << (c->remove(217)) << std::endl;
*c=*a;
std::cout << (e->insert(464)) << std::endl;
std::cout << (a->insert(155)) << std::endl;
std::cout << (e->remove(113)) << std::endl;
a->printPretty();
std::cout << (d->insert(365)) << std::endl;
b->printPretty();
*e=*e;
std::cout << (d->insert(152)) << std::endl;
std::cout << (c->remove(43)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
*d=*d;
std::cout << (b->insert(436)) << std::endl;
*e=*c;
*c=*a;
*e=*b;
std::cout << (a->insert(43)) << std::endl;
std::cout << (c->remove(43)) << std::endl;
b->printPretty();
std::cout << (e->remove(450)) << std::endl;
e->printPretty();
std::cout << (d->remove(80)) << std::endl;
d->printPretty();
std::cout << (c->remove(155)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
std::cout << (a->remove(43)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
*e=*c;
b->printPretty();
std::cout << (c->remove(174)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
std::cout << (a->insert(477)) << std::endl;
e->printPretty();
std::cout << (a->remove(174)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->remove(273)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->insert(310)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
b->printPretty();
std::cout << (d->remove(466)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
e->printPretty();
std::cout << (e->insert(82)) << std::endl;
std::cout << (c->insert(310)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (b->insert(76)) << std::endl;
std::cout << (a->remove(253)) << std::endl;
*e=*d;
std::cout << (b->insert(218)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
*b=*c;
std::cout << (c->insert(310)) << std::endl;
std::cout << (e->insert(50)) << std::endl;
std::cout << (d->remove(464)) << std::endl;
a->printPretty();
std::cout << (b->insert(391)) << std::endl;
std::cout << (b->remove(71)) << std::endl;
std::cout << (e->insert(365)) << std::endl;
*b=*c;
std::cout << (e->insert(322)) << std::endl;
*d=*d;
std::cout << (c->insert(33)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (c->remove(261)) << std::endl;
std::cout << (a->insert(48)) << std::endl;
std::cout << (a->remove(48)) << std::endl;
*d=*e;
std::cout << (a->insert(251)) << std::endl;
a->printPretty();
std::cout << (b->remove(486)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
*e=*d;
std::cout << (a->remove(251)) << std::endl;
std::cout << (b->remove(133)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
*b=*a;
std::cout << (c->remove(262)) << std::endl;
*e=*e;
std::cout << (d->insert(189)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->remove(486)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (d->remove(365)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
*e=*b;
std::cout << (c->insert(259)) << std::endl;
a->printPretty();
*e=*c;
*a=*c;
std::cout << (d->insert(158)) << std::endl;
d->printPretty();
std::cout << (d->insert(86)) << std::endl;
std::cout << (a->remove(259)) << std::endl;
d->printPretty();
std::cout << (c->insert(1)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
std::cout << (a->insert(310)) << std::endl;
std::cout << (e->remove(215)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
b->printPretty();
std::cout << (b->remove(269)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (e->insert(259)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (b->remove(389)) << std::endl;
std::cout << (c->remove(424)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
d->printPretty();
std::cout << (d->remove(86)) << std::endl;
e->printPretty();
std::cout << (b->remove(336)) << std::endl;
std::cout << (b->remove(95)) << std::endl;
std::cout << (e->remove(50)) << std::endl;
*d=*b;
*c=*e;
*c=*a;
std::cout << (e->insert(86)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
std::cout << (d->insert(32)) << std::endl;
*a=*d;
std::cout << (a->insert(32)) << std::endl;
std::cout << (a->remove(32)) << std::endl;
std::cout << (b->remove(354)) << std::endl;
std::cout << (c->insert(274)) << std::endl;
std::cout << (a->insert(341)) << std::endl;
std::cout << (c->insert(274)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
c->printPretty();
*d=*d;
*b=*e;
std::cout << (c->insert(236)) << std::endl;
*d=*b;
std::cout << (c->insert(236)) << std::endl;
std::cout << (b->insert(161)) << std::endl;
*e=*c;
e->printPretty();
std::cout << (a->insert(244)) << std::endl;
std::cout << (c->insert(310)) << std::endl;
*a=*b;
std::cout << (a->insert(189)) << std::endl;
*e=*c;
std::cout << (c->insert(251)) << std::endl;
std::cout << (c->insert(236)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->remove(356)) << std::endl;
std::cout << (a->remove(86)) << std::endl;
*c=*d;
*d=*a;
std::cout << (e->insert(310)) << std::endl;
std::cout << (a->remove(158)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (e->remove(318)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (c->remove(482)) << std::endl;
std::cout << (c->insert(146)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (c->remove(110)) << std::endl;
std::cout << (c->remove(152)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->insert(146)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (a->insert(108)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (c->remove(175)) << std::endl;
std::cout << (d->remove(405)) << std::endl;
*c=*e;
std::cout << (b->remove(110)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
a->printPretty();
std::cout << (b->insert(86)) << std::endl;
*b=*a;
std::cout << (e->remove(251)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
c->printPretty();
std::cout << (b->remove(42)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (c->insert(236)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (c->remove(251)) << std::endl;
*b=*c;
std::cout << (c->insert(116)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
std::cout << (d->insert(443)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->insert(399)) << std::endl;
*a=*a;
std::cout << (a->remove(108)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
std::cout << (c->remove(101)) << std::endl;
*c=*e;
std::cout << (b->insert(101)) << std::endl;
std::cout << (d->insert(27)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
*b=*a;
std::cout << (e->remove(236)) << std::endl;
*c=*d;
*b=*d;
e->printPretty();
std::cout << (d->remove(370)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
d->printPretty();
std::cout << (b->remove(474)) << std::endl;
*b=*e;
std::cout << (d->remove(399)) << std::endl;
c->printPretty();
std::cout << (c->insert(161)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
std::cout << (c->remove(158)) << std::endl;
*a=*a;
std::cout << (e->remove(310)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (c->insert(27)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
b->printPretty();
std::cout << (c->insert(443)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
e->printPretty();
*e=*b;
*a=*c;
b->printPretty();
d->printPretty();
std::cout << (b->remove(481)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
std::cout << (c->remove(462)) << std::endl;
*e=*e;
std::cout << (d->remove(124)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
*e=*e;
std::cout << (c->remove(168)) << std::endl;
*e=*e;
std::cout << (a->insert(189)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
a->printPretty();
std::cout << (e->insert(233)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
std::cout << (c->insert(105)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
e->printPretty();
e->printPretty();
a->printPretty();
std::cout << (d->remove(33)) << std::endl;
std::cout << (e->remove(480)) << std::endl;
std::cout << (e->remove(64)) << std::endl;
a->printPretty();
std::cout << (c->remove(235)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
*e=*e;
std::cout << (a->insert(443)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
*e=*a;
std::cout << (c->remove(110)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
std::cout << (e->insert(247)) << std::endl;
std::cout << (b->remove(304)) << std::endl;
e->printPretty();
std::cout << (a->insert(454)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
*b=*e;
std::cout << (d->insert(44)) << std::endl;
*b=*a;
std::cout << (a->remove(281)) << std::endl;
*d=*c;
std::cout << (b->insert(357)) << std::endl;
a->printPretty();
std::cout << (b->insert(140)) << std::endl;
b->printPretty();
b->printPretty();
c->printPretty();
*e=*c;
std::cout << (d->remove(238)) << std::endl;
*d=*e;
std::cout << (d->insert(105)) << std::endl;
*d=*e;
*a=*a;
std::cout << (d->remove(189)) << std::endl;
std::cout << (e->insert(381)) << std::endl;
std::cout << (a->remove(340)) << std::endl;
std::cout << (b->remove(288)) << std::endl;
std::cout << (d->remove(27)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
*b=*d;
std::cout << (e->remove(152)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
*c=*c;
std::cout << (e->remove(280)) << std::endl;
*d=*e;
std::cout << (e->remove(390)) << std::endl;
d->printPretty();
std::cout << (e->insert(189)) << std::endl;
d->printPretty();
*e=*a;
*c=*e;
std::cout << (e->insert(249)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (e->remove(161)) << std::endl;
std::cout << (a->remove(152)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (c->insert(454)) << std::endl;
*e=*d;
std::cout << (c->insert(234)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->insert(454)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
std::cout << (d->remove(454)) << std::endl;
*c=*b;
std::cout << (c->remove(341)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
std::cout << (b->insert(399)) << std::endl;
*a=*a;
std::cout << (c->remove(399)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*b=*a;
std::cout << (c->insert(163)) << std::endl;
std::cout << (b->insert(345)) << std::endl;
c->printPretty();
std::cout << (c->insert(112)) << std::endl;
std::cout << (a->insert(424)) << std::endl;
std::cout << (c->remove(183)) << std::endl;
d->printPretty();
std::cout << (c->remove(69)) << std::endl;
std::cout << (c->remove(166)) << std::endl;
std::cout << (d->remove(353)) << std::endl;
std::cout << (c->insert(189)) << std::endl;
a->printPretty();
std::cout << (a->remove(369)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (b->remove(161)) << std::endl;
e->printPretty();
std::cout << (c->insert(37)) << std::endl;
b->printPretty();
std::cout << (a->remove(82)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
b->printPretty();
*d=*e;
std::cout << (b->remove(178)) << std::endl;
std::cout << (e->insert(123)) << std::endl;
std::cout << (b->remove(459)) << std::endl;
c->printPretty();
std::cout << (d->remove(419)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
std::cout << (e->insert(348)) << std::endl;
c->printPretty();
std::cout << (c->remove(37)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (a->insert(402)) << std::endl;
std::cout << (a->insert(323)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (b->insert(189)) << std::endl;
c->printPretty();
a->printPretty();
e->printPretty();
*d=*e;
std::cout << (b->insert(419)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (d->remove(216)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
std::cout << (c->insert(323)) << std::endl;
c->printPretty();
std::cout << (a->remove(262)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
std::cout << (e->remove(483)) << std::endl;
std::cout << (d->insert(66)) << std::endl;
*b=*b;
*b=*b;
std::cout << (d->remove(80)) << std::endl;
std::cout << (a->remove(189)) << std::endl;
std::cout << (b->remove(399)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
e->printPretty();
std::cout << (e->remove(493)) << std::endl;
a->printPretty();
std::cout << (e->insert(195)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
std::cout << (e->remove(230)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (c->remove(270)) << std::endl;
std::cout << (c->insert(195)) << std::endl;
a->printPretty();
std::cout << (b->remove(112)) << std::endl;
*a=*e;
std::cout << (a->insert(419)) << std::endl;
std::cout << (a->insert(424)) << std::endl;
c->printPretty();
std::cout << (b->remove(33)) << std::endl;
*a=*e;
std::cout << (d->insert(454)) << std::endl;
std::cout << (c->insert(432)) << std::endl;
e->printPretty();
std::cout << (a->insert(90)) << std::endl;
std::cout << (e->insert(161)) << std::endl;
std::cout << (c->remove(370)) << std::endl;
std::cout << (c->remove(485)) << std::endl;
d->printPretty();
std::cout << (c->remove(300)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (a->remove(189)) << std::endl;
*d=*e;
std::cout << (d->remove(397)) << std::endl;
std::cout << (e->remove(189)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
std::cout << (e->insert(287)) << std::endl;
std::cout << (c->insert(419)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
std::cout << (b->remove(454)) << std::endl;
std::cout << (a->remove(162)) << std::endl;
std::cout << (a->insert(237)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
std::cout << (c->insert(91)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
*d=*a;
*e=*d;
std::cout << (d->remove(161)) << std::endl;
std::cout << (b->remove(388)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
*d=*d;
std::cout << (e->remove(419)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
std::cout << (b->insert(208)) << std::endl;
std::cout << (e->insert(8)) << std::endl;
std::cout << (d->insert(465)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (b->insert(247)) << std::endl;
std::cout << (c->insert(432)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
*c=*b;
std::cout << (e->remove(8)) << std::endl;
std::cout << (e->remove(195)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
*b=*b;
d->printPretty();
std::cout << (c->insert(189)) << std::endl;
d->printPretty();
e->printPretty();
c->printPretty();
std::cout << (a->insert(85)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (c->insert(201)) << std::endl;
c->printPretty();
std::cout << (d->insert(189)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (e->remove(414)) << std::endl;
std::cout << (e->remove(163)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (b->insert(404)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
d->printPretty();
std::cout << (d->insert(247)) << std::endl;
b->printPretty();
std::cout << (a->insert(216)) << std::endl;
std::cout << (d->insert(348)) << std::endl;
*b=*c;
std::cout << (d->remove(348)) << std::endl;
std::cout << (e->remove(11)) << std::endl;
std::cout << (d->remove(163)) << std::endl;
e->printPretty();
std::cout << (b->remove(110)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
std::cout << (a->remove(419)) << std::endl;
*a=*d;
std::cout << (e->remove(76)) << std::endl;
std::cout << (b->remove(132)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
c->printPretty();
*b=*d;
std::cout << (a->insert(420)) << std::endl;
std::cout << (a->remove(415)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
std::cout << (c->remove(439)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
std::cout << (d->remove(422)) << std::endl;
std::cout << (a->remove(82)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
*a=*a;
std::cout << (b->remove(39)) << std::endl;
std::cout << (e->insert(454)) << std::endl;
std::cout << (b->remove(110)) << std::endl;
std::cout << (c->insert(88)) << std::endl;
e->printPretty();
std::cout << (d->insert(429)) << std::endl;
std::cout << (b->insert(21)) << std::endl;
std::cout << (b->remove(321)) << std::endl;
*b=*a;
std::cout << (b->insert(419)) << std::endl;
c->printPretty();
std::cout << (b->remove(201)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (e->insert(459)) << std::endl;
std::cout << (c->insert(310)) << std::endl;
std::cout << (c->insert(451)) << std::endl;
*b=*c;
std::cout << (a->insert(189)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
*a=*d;
*e=*a;
std::cout << (a->insert(110)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
std::cout << (d->remove(216)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
*b=*c;
std::cout << (a->remove(158)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
std::cout << (c->insert(216)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (b->remove(279)) << std::endl;
*d=*a;
std::cout << (c->insert(451)) << std::endl;
std::cout << (e->insert(189)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
std::cout << (e->insert(216)) << std::endl;
c->printPretty();
std::cout << (e->insert(194)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
*c=*a;
*d=*b;
d->printPretty();
std::cout << (e->remove(201)) << std::endl;
a->printPretty();
std::cout << (c->remove(419)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
*e=*d;
std::cout << (b->insert(215)) << std::endl;
return 0;
}
