#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(169)) << std::endl;
std::cout << (a->insert(496)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(496)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->remove(318)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
c->printPretty();
*d=*b;
std::cout << (b->insert(223)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
c->printPretty();
std::cout << (c->remove(412)) << std::endl;
*a=*a;
std::cout << (d->remove(120)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (b->remove(155)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
std::cout << (c->insert(282)) << std::endl;
e->printPretty();
*e=*b;
*a=*c;
std::cout << (e->remove(235)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
e->printPretty();
std::cout << (a->insert(366)) << std::endl;
b->printPretty();
std::cout << (a->remove(251)) << std::endl;
a->printPretty();
std::cout << (b->insert(267)) << std::endl;
*a=*b;
std::cout << (c->insert(320)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
*a=*c;
std::cout << (c->remove(320)) << std::endl;
std::cout << (b->remove(267)) << std::endl;
std::cout << (a->insert(320)) << std::endl;
std::cout << (c->insert(361)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
std::cout << (a->remove(320)) << std::endl;
std::cout << (d->remove(268)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (e->remove(317)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
e->printPretty();
std::cout << (e->remove(223)) << std::endl;
a->printPretty();
*c=*e;
d->printPretty();
std::cout << (c->insert(249)) << std::endl;
c->printPretty();
std::cout << (d->remove(371)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
c->printPretty();
std::cout << (c->insert(83)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
b->printPretty();
std::cout << (d->remove(70)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (a->remove(73)) << std::endl;
c->printPretty();
*c=*e;
c->printPretty();
std::cout << (e->remove(71)) << std::endl;
*d=*e;
std::cout << (b->remove(103)) << std::endl;
*c=*c;
std::cout << (d->remove(469)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (c->remove(20)) << std::endl;
*a=*a;
std::cout << (e->insert(203)) << std::endl;
std::cout << (c->insert(32)) << std::endl;
std::cout << (e->remove(203)) << std::endl;
*b=*e;
std::cout << (c->insert(106)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
std::cout << (c->remove(159)) << std::endl;
std::cout << (c->remove(32)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
*b=*b;
std::cout << (e->remove(469)) << std::endl;
b->printPretty();
std::cout << (a->insert(293)) << std::endl;
*b=*d;
*a=*d;
std::cout << (d->insert(364)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
*d=*b;
std::cout << (d->remove(427)) << std::endl;
e->printPretty();
std::cout << (d->remove(137)) << std::endl;
std::cout << (c->insert(469)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (e->insert(343)) << std::endl;
std::cout << (c->remove(358)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
*e=*a;
*e=*d;
std::cout << (d->remove(74)) << std::endl;
c->printPretty();
std::cout << (b->remove(99)) << std::endl;
e->printPretty();
std::cout << (d->remove(213)) << std::endl;
b->printPretty();
d->printPretty();
*d=*e;
b->printPretty();
std::cout << (e->remove(243)) << std::endl;
c->printPretty();
a->printPretty();
*a=*d;
std::cout << (c->remove(113)) << std::endl;
std::cout << (c->insert(380)) << std::endl;
std::cout << (e->insert(110)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
*c=*a;
std::cout << (c->insert(277)) << std::endl;
*b=*a;
*c=*d;
std::cout << (e->insert(110)) << std::endl;
std::cout << (b->remove(344)) << std::endl;
std::cout << (e->insert(21)) << std::endl;
*a=*e;
std::cout << (a->insert(110)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->insert(142)) << std::endl;
*a=*c;
*b=*a;
*b=*c;
*c=*d;
std::cout << (a->remove(45)) << std::endl;
c->printPretty();
std::cout << (a->insert(149)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
c->printPretty();
a->printPretty();
*b=*c;
std::cout << (e->remove(110)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
*c=*e;
std::cout << (c->remove(21)) << std::endl;
b->printPretty();
*c=*b;
std::cout << (e->remove(21)) << std::endl;
std::cout << (a->insert(111)) << std::endl;
std::cout << (c->remove(157)) << std::endl;
d->printPretty();
std::cout << (e->insert(458)) << std::endl;
std::cout << (d->remove(200)) << std::endl;
*e=*c;
std::cout << (a->remove(243)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
*d=*b;
std::cout << (c->remove(94)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
d->printPretty();
std::cout << (c->remove(352)) << std::endl;
std::cout << (a->insert(10)) << std::endl;
d->printPretty();
std::cout << (e->remove(234)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->insert(355)) << std::endl;
std::cout << (e->insert(44)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(325)) << std::endl;
std::cout << (d->remove(18)) << std::endl;
std::cout << (a->remove(274)) << std::endl;
e->printPretty();
std::cout << (b->remove(188)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (c->remove(276)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (a->remove(6)) << std::endl;
std::cout << (a->insert(111)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->remove(128)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
std::cout << (a->remove(259)) << std::endl;
*c=*a;
std::cout << (a->remove(111)) << std::endl;
*b=*d;
std::cout << (e->insert(236)) << std::endl;
*a=*c;
std::cout << (d->remove(474)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (a->insert(10)) << std::endl;
b->printPretty();
*d=*b;
*c=*e;
std::cout << (d->insert(138)) << std::endl;
std::cout << (e->remove(236)) << std::endl;
std::cout << (a->remove(311)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
std::cout << (b->insert(460)) << std::endl;
std::cout << (e->remove(215)) << std::endl;
std::cout << (b->insert(460)) << std::endl;
std::cout << (d->remove(138)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (b->insert(271)) << std::endl;
d->printPretty();
std::cout << (b->remove(147)) << std::endl;
std::cout << (b->remove(271)) << std::endl;
e->printPretty();
std::cout << (c->insert(236)) << std::endl;
std::cout << (d->insert(464)) << std::endl;
std::cout << (a->insert(10)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (e->insert(102)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
*c=*a;
a->printPretty();
std::cout << (d->remove(464)) << std::endl;
std::cout << (e->insert(464)) << std::endl;
c->printPretty();
std::cout << (c->remove(187)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
*a=*e;
std::cout << (b->remove(415)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (c->insert(400)) << std::endl;
*c=*c;
std::cout << (a->insert(445)) << std::endl;
std::cout << (c->insert(401)) << std::endl;
std::cout << (e->insert(102)) << std::endl;
a->printPretty();
std::cout << (b->remove(40)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
*d=*b;
std::cout << (c->remove(322)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (a->remove(464)) << std::endl;
b->printPretty();
std::cout << (e->remove(464)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
std::cout << (e->insert(420)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
*c=*d;
std::cout << (e->insert(102)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (d->insert(165)) << std::endl;
std::cout << (e->insert(58)) << std::endl;
b->printPretty();
std::cout << (d->insert(165)) << std::endl;
*b=*b;
std::cout << (a->insert(93)) << std::endl;
e->printPretty();
std::cout << (a->insert(26)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->insert(165)) << std::endl;
std::cout << (e->remove(58)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
std::cout << (c->insert(165)) << std::endl;
std::cout << (b->remove(141)) << std::endl;
std::cout << (a->insert(445)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (a->insert(233)) << std::endl;
*e=*c;
std::cout << (a->remove(497)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (e->insert(481)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
*e=*e;
std::cout << (c->remove(459)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (e->remove(165)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
*c=*a;
std::cout << (c->remove(390)) << std::endl;
d->printPretty();
*a=*d;
d->printPretty();
std::cout << (a->insert(250)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (e->insert(378)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
a->printPretty();
std::cout << (e->remove(497)) << std::endl;
std::cout << (e->remove(440)) << std::endl;
d->printPretty();
std::cout << (c->insert(128)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
*d=*a;
*e=*a;
*d=*d;
*d=*d;
std::cout << (e->remove(250)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
*a=*c;
std::cout << (e->remove(463)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (e->remove(23)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (c->remove(118)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (e->remove(479)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (e->insert(165)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
std::cout << (a->remove(88)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
std::cout << (e->remove(497)) << std::endl;
*a=*e;
std::cout << (a->remove(423)) << std::endl;
std::cout << (e->insert(205)) << std::endl;
std::cout << (e->remove(227)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
std::cout << (e->remove(205)) << std::endl;
std::cout << (e->insert(156)) << std::endl;
a->printPretty();
std::cout << (d->insert(497)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (a->remove(500)) << std::endl;
std::cout << (e->insert(156)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
a->printPretty();
std::cout << (d->remove(354)) << std::endl;
std::cout << (e->remove(156)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
c->printPretty();
std::cout << (d->remove(497)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
*a=*d;
std::cout << (e->remove(111)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (b->insert(433)) << std::endl;
std::cout << (c->remove(165)) << std::endl;
c->printPretty();
std::cout << (c->remove(360)) << std::endl;
std::cout << (a->remove(145)) << std::endl;
std::cout << (b->remove(337)) << std::endl;
a->printPretty();
std::cout << (a->insert(425)) << std::endl;
std::cout << (a->insert(165)) << std::endl;
b->printPretty();
std::cout << (b->insert(433)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
std::cout << (d->remove(367)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
std::cout << (c->insert(96)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
std::cout << (b->remove(433)) << std::endl;
std::cout << (a->insert(165)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
std::cout << (b->insert(353)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
d->printPretty();
std::cout << (a->insert(327)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (a->remove(250)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (c->remove(400)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
a->printPretty();
std::cout << (e->insert(51)) << std::endl;
*d=*a;
*d=*e;
std::cout << (a->remove(367)) << std::endl;
std::cout << (b->remove(18)) << std::endl;
*b=*a;
std::cout << (a->insert(251)) << std::endl;
std::cout << (c->insert(250)) << std::endl;
b->printPretty();
std::cout << (c->remove(100)) << std::endl;
std::cout << (e->insert(214)) << std::endl;
std::cout << (a->remove(456)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
*e=*e;
std::cout << (e->insert(372)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
std::cout << (d->remove(51)) << std::endl;
*a=*b;
std::cout << (a->insert(327)) << std::endl;
std::cout << (a->insert(327)) << std::endl;
*d=*d;
std::cout << (b->insert(327)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
std::cout << (a->insert(327)) << std::endl;
std::cout << (a->remove(327)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
*c=*b;
std::cout << (a->insert(205)) << std::endl;
d->printPretty();
std::cout << (a->insert(205)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (b->remove(478)) << std::endl;
std::cout << (c->remove(327)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
*c=*a;
a->printPretty();
*d=*e;
std::cout << (b->remove(207)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
*e=*e;
*e=*c;
d->printPretty();
std::cout << (c->insert(423)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->remove(205)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
b->printPretty();
std::cout << (d->insert(372)) << std::endl;
*a=*a;
std::cout << (d->insert(372)) << std::endl;
std::cout << (e->insert(57)) << std::endl;
d->printPretty();
*e=*c;
e->printPretty();
c->printPretty();
std::cout << (d->insert(214)) << std::endl;
*d=*d;
std::cout << (a->insert(31)) << std::endl;
e->printPretty();
std::cout << (d->insert(208)) << std::endl;
std::cout << (c->insert(423)) << std::endl;
std::cout << (c->insert(317)) << std::endl;
std::cout << (b->insert(374)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (d->insert(214)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
*c=*d;
std::cout << (e->remove(205)) << std::endl;
e->printPretty();
std::cout << (b->insert(374)) << std::endl;
e->printPretty();
d->printPretty();
b->printPretty();
std::cout << (d->insert(51)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
e->printPretty();
std::cout << (e->remove(423)) << std::endl;
std::cout << (b->remove(374)) << std::endl;
e->printPretty();
std::cout << (d->remove(372)) << std::endl;
std::cout << (a->remove(75)) << std::endl;
*d=*d;
std::cout << (b->insert(27)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
b->printPretty();
std::cout << (e->remove(265)) << std::endl;
std::cout << (b->remove(142)) << std::endl;
std::cout << (c->insert(282)) << std::endl;
b->printPretty();
e->printPretty();
*d=*e;
std::cout << (a->insert(279)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
std::cout << (a->remove(382)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
std::cout << (d->remove(274)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
*e=*b;
*c=*b;
c->printPretty();
a->printPretty();
std::cout << (c->remove(407)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
std::cout << (a->remove(31)) << std::endl;
std::cout << (d->insert(107)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
std::cout << (d->remove(474)) << std::endl;
a->printPretty();
d->printPretty();
a->printPretty();
std::cout << (d->insert(107)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
*c=*b;
e->printPretty();
b->printPretty();
*c=*d;
std::cout << (a->remove(7)) << std::endl;
d->printPretty();
b->printPretty();
e->printPretty();
std::cout << (a->insert(279)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
*c=*b;
std::cout << (e->insert(273)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
std::cout << (d->remove(106)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
*c=*a;
*a=*b;
std::cout << (a->insert(119)) << std::endl;
std::cout << (e->insert(490)) << std::endl;
std::cout << (a->insert(459)) << std::endl;
std::cout << (e->insert(273)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
*b=*b;
std::cout << (c->insert(279)) << std::endl;
std::cout << (e->remove(490)) << std::endl;
*c=*a;
std::cout << (e->remove(214)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
std::cout << (a->insert(11)) << std::endl;
b->printPretty();
std::cout << (d->insert(486)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
e->printPretty();
*a=*d;
*c=*b;
c->printPretty();
std::cout << (e->remove(249)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (d->remove(195)) << std::endl;
std::cout << (b->insert(55)) << std::endl;
std::cout << (b->insert(55)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (b->insert(55)) << std::endl;
*e=*d;
std::cout << (c->insert(450)) << std::endl;
std::cout << (e->remove(486)) << std::endl;
e->printPretty();
std::cout << (c->remove(486)) << std::endl;
e->printPretty();
std::cout << (a->insert(486)) << std::endl;
*c=*a;
std::cout << (d->remove(330)) << std::endl;
*c=*c;
b->printPretty();
*b=*c;
std::cout << (c->insert(486)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
std::cout << (b->insert(486)) << std::endl;
std::cout << (b->insert(121)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (b->remove(320)) << std::endl;
b->printPretty();
std::cout << (d->remove(486)) << std::endl;
std::cout << (d->insert(46)) << std::endl;
std::cout << (d->insert(46)) << std::endl;
c->printPretty();
std::cout << (a->remove(457)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
*c=*d;
std::cout << (a->remove(200)) << std::endl;
std::cout << (d->insert(46)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
*c=*e;
std::cout << (b->remove(467)) << std::endl;
std::cout << (b->remove(447)) << std::endl;
std::cout << (d->remove(77)) << std::endl;
c->printPretty();
std::cout << (b->remove(486)) << std::endl;
e->printPretty();
*b=*d;
std::cout << (d->insert(46)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (a->remove(340)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (a->remove(486)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
*d=*c;
std::cout << (e->remove(122)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
e->printPretty();
*c=*e;
*b=*d;
d->printPretty();
d->printPretty();
std::cout << (a->remove(6)) << std::endl;
std::cout << (b->insert(101)) << std::endl;
std::cout << (e->insert(104)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->insert(362)) << std::endl;
a->printPretty();
std::cout << (d->remove(101)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
std::cout << (b->insert(101)) << std::endl;
*a=*a;
*b=*e;
c->printPretty();
*e=*d;
b->printPretty();
*b=*b;
*a=*a;
*d=*b;
std::cout << (d->remove(399)) << std::endl;
c->printPretty();
std::cout << (a->insert(359)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
*b=*c;
a->printPretty();
std::cout << (e->remove(81)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
c->printPretty();
std::cout << (e->insert(92)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
std::cout << (c->insert(101)) << std::endl;
std::cout << (a->remove(65)) << std::endl;
std::cout << (d->remove(146)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
b->printPretty();
*b=*a;
std::cout << (a->remove(359)) << std::endl;
d->printPretty();
std::cout << (b->remove(359)) << std::endl;
a->printPretty();
std::cout << (b->insert(436)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (d->remove(127)) << std::endl;
std::cout << (b->insert(263)) << std::endl;
c->printPretty();
return 0;
}
