#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (b->insert(418)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (b->insert(198)) << std::endl;
std::cout << (c->insert(193)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (c->insert(193)) << std::endl;
std::cout << (b->remove(418)) << std::endl;
c->printPretty();
std::cout << (e->insert(122)) << std::endl;
std::cout << (e->insert(122)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
std::cout << (d->insert(498)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (d->remove(19)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (d->insert(475)) << std::endl;
std::cout << (b->insert(309)) << std::endl;
b->printPretty();
std::cout << (a->remove(325)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
e->printPretty();
std::cout << (b->insert(198)) << std::endl;
c->printPretty();
std::cout << (d->remove(338)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (b->insert(198)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
std::cout << (c->remove(49)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
*a=*a;
std::cout << (b->insert(309)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
std::cout << (b->insert(309)) << std::endl;
c->printPretty();
std::cout << (b->remove(244)) << std::endl;
std::cout << (c->insert(316)) << std::endl;
std::cout << (a->insert(433)) << std::endl;
std::cout << (d->insert(498)) << std::endl;
std::cout << (a->remove(433)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (b->insert(475)) << std::endl;
std::cout << (d->remove(61)) << std::endl;
e->printPretty();
std::cout << (b->remove(297)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
std::cout << (e->remove(389)) << std::endl;
*c=*c;
*b=*e;
std::cout << (b->remove(473)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->remove(370)) << std::endl;
std::cout << (c->remove(316)) << std::endl;
*a=*e;
std::cout << (c->remove(111)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
a->printPretty();
std::cout << (c->remove(442)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
*b=*d;
c->printPretty();
std::cout << (e->insert(164)) << std::endl;
*c=*a;
*d=*d;
std::cout << (a->remove(491)) << std::endl;
std::cout << (d->remove(3)) << std::endl;
b->printPretty();
std::cout << (e->insert(102)) << std::endl;
std::cout << (b->remove(413)) << std::endl;
std::cout << (b->remove(417)) << std::endl;
d->printPretty();
std::cout << (d->insert(175)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (a->remove(266)) << std::endl;
std::cout << (e->insert(65)) << std::endl;
*a=*c;
std::cout << (c->insert(264)) << std::endl;
std::cout << (c->insert(365)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
e->printPretty();
std::cout << (a->insert(287)) << std::endl;
d->printPretty();
std::cout << (d->remove(77)) << std::endl;
std::cout << (e->insert(164)) << std::endl;
std::cout << (a->remove(170)) << std::endl;
*e=*b;
*e=*c;
std::cout << (d->remove(124)) << std::endl;
a->printPretty();
std::cout << (d->remove(498)) << std::endl;
*b=*d;
std::cout << (c->insert(491)) << std::endl;
std::cout << (b->insert(427)) << std::endl;
*c=*a;
std::cout << (d->remove(340)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (d->remove(475)) << std::endl;
*a=*a;
b->printPretty();
*d=*d;
std::cout << (c->insert(66)) << std::endl;
std::cout << (c->remove(121)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (d->remove(287)) << std::endl;
*a=*d;
std::cout << (b->insert(484)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (b->remove(484)) << std::endl;
std::cout << (b->remove(427)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
*e=*d;
std::cout << (a->remove(123)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
std::cout << (b->remove(8)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
std::cout << (c->insert(287)) << std::endl;
std::cout << (e->remove(176)) << std::endl;
std::cout << (b->insert(475)) << std::endl;
*b=*e;
b->printPretty();
c->printPretty();
std::cout << (c->remove(132)) << std::endl;
e->printPretty();
std::cout << (b->insert(392)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
std::cout << (d->insert(300)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
e->printPretty();
std::cout << (d->insert(282)) << std::endl;
*b=*a;
*d=*c;
*b=*a;
std::cout << (e->insert(62)) << std::endl;
c->printPretty();
*d=*a;
*d=*b;
std::cout << (d->insert(345)) << std::endl;
std::cout << (c->remove(66)) << std::endl;
std::cout << (d->insert(491)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
a->printPretty();
std::cout << (a->remove(128)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
std::cout << (b->insert(491)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
*d=*c;
std::cout << (b->remove(491)) << std::endl;
*a=*c;
std::cout << (a->insert(107)) << std::endl;
*e=*e;
std::cout << (c->remove(122)) << std::endl;
*e=*e;
std::cout << (e->insert(62)) << std::endl;
std::cout << (d->insert(491)) << std::endl;
std::cout << (c->insert(491)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
std::cout << (c->insert(455)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
std::cout << (c->insert(455)) << std::endl;
d->printPretty();
b->printPretty();
*a=*e;
std::cout << (a->remove(62)) << std::endl;
a->printPretty();
std::cout << (c->remove(491)) << std::endl;
std::cout << (d->remove(287)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
std::cout << (e->insert(62)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->remove(390)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
std::cout << (b->insert(38)) << std::endl;
*d=*a;
std::cout << (d->remove(321)) << std::endl;
*a=*d;
d->printPretty();
*a=*d;
*d=*d;
std::cout << (a->insert(426)) << std::endl;
b->printPretty();
std::cout << (c->insert(163)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
d->printPretty();
*a=*b;
*a=*e;
std::cout << (e->insert(102)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
c->printPretty();
std::cout << (c->insert(163)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
c->printPretty();
std::cout << (d->remove(135)) << std::endl;
std::cout << (c->remove(419)) << std::endl;
std::cout << (e->remove(304)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (e->remove(102)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
c->printPretty();
std::cout << (a->insert(279)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
std::cout << (a->remove(287)) << std::endl;
d->printPretty();
*a=*e;
*b=*d;
a->printPretty();
std::cout << (c->insert(455)) << std::endl;
*e=*d;
std::cout << (e->remove(474)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (c->remove(228)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (b->insert(447)) << std::endl;
std::cout << (a->insert(413)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (b->insert(447)) << std::endl;
b->printPretty();
std::cout << (e->insert(39)) << std::endl;
std::cout << (a->insert(472)) << std::endl;
b->printPretty();
std::cout << (b->remove(447)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
std::cout << (b->insert(212)) << std::endl;
b->printPretty();
std::cout << (b->remove(212)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
std::cout << (d->insert(412)) << std::endl;
std::cout << (e->insert(21)) << std::endl;
std::cout << (d->remove(412)) << std::endl;
std::cout << (e->insert(204)) << std::endl;
d->printPretty();
*a=*e;
*a=*d;
std::cout << (e->remove(78)) << std::endl;
std::cout << (a->insert(24)) << std::endl;
std::cout << (a->insert(24)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (e->remove(78)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
std::cout << (e->remove(21)) << std::endl;
std::cout << (e->remove(259)) << std::endl;
b->printPretty();
d->printPretty();
c->printPretty();
c->printPretty();
*d=*e;
std::cout << (a->remove(24)) << std::endl;
std::cout << (e->insert(39)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
*b=*c;
d->printPretty();
e->printPretty();
std::cout << (c->remove(449)) << std::endl;
std::cout << (e->remove(46)) << std::endl;
*a=*b;
std::cout << (b->remove(447)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->insert(128)) << std::endl;
*e=*e;
*b=*d;
std::cout << (e->remove(368)) << std::endl;
a->printPretty();
std::cout << (d->remove(342)) << std::endl;
b->printPretty();
std::cout << (d->remove(186)) << std::endl;
std::cout << (e->insert(204)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (c->remove(350)) << std::endl;
std::cout << (d->insert(308)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (d->insert(39)) << std::endl;
std::cout << (e->insert(420)) << std::endl;
std::cout << (e->insert(39)) << std::endl;
std::cout << (e->remove(39)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (d->remove(39)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
std::cout << (e->insert(420)) << std::endl;
*e=*a;
*b=*e;
std::cout << (d->remove(204)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
d->printPretty();
std::cout << (d->remove(186)) << std::endl;
std::cout << (e->insert(382)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (c->insert(189)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (c->remove(189)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
std::cout << (b->remove(437)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
std::cout << (b->remove(495)) << std::endl;
std::cout << (c->remove(214)) << std::endl;
std::cout << (e->remove(382)) << std::endl;
d->printPretty();
std::cout << (c->insert(243)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
std::cout << (e->remove(126)) << std::endl;
a->printPretty();
std::cout << (a->insert(316)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->remove(316)) << std::endl;
*c=*d;
std::cout << (b->remove(48)) << std::endl;
std::cout << (c->remove(383)) << std::endl;
std::cout << (c->insert(88)) << std::endl;
std::cout << (b->insert(19)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
e->printPretty();
std::cout << (c->insert(88)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
e->printPretty();
std::cout << (a->remove(473)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
std::cout << (b->remove(285)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (e->remove(486)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
std::cout << (c->remove(301)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
c->printPretty();
std::cout << (a->remove(243)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
a->printPretty();
std::cout << (e->insert(5)) << std::endl;
a->printPretty();
std::cout << (b->insert(143)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
b->printPretty();
std::cout << (a->insert(186)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
*c=*e;
*c=*a;
std::cout << (b->insert(143)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
*d=*c;
std::cout << (b->insert(95)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (c->remove(186)) << std::endl;
*b=*c;
std::cout << (e->remove(5)) << std::endl;
a->printPretty();
std::cout << (a->insert(324)) << std::endl;
e->printPretty();
std::cout << (c->remove(117)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
*b=*b;
b->printPretty();
*e=*a;
*a=*c;
std::cout << (e->insert(324)) << std::endl;
*e=*d;
std::cout << (e->remove(82)) << std::endl;
std::cout << (d->remove(362)) << std::endl;
std::cout << (e->remove(186)) << std::endl;
std::cout << (d->remove(186)) << std::endl;
std::cout << (c->insert(382)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
c->printPretty();
a->printPretty();
*d=*e;
std::cout << (e->insert(224)) << std::endl;
a->printPretty();
std::cout << (c->insert(306)) << std::endl;
std::cout << (c->remove(306)) << std::endl;
d->printPretty();
*d=*e;
c->printPretty();
std::cout << (b->insert(328)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (d->insert(224)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
c->printPretty();
c->printPretty();
a->printPretty();
std::cout << (e->insert(140)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
*a=*e;
std::cout << (b->insert(500)) << std::endl;
*b=*e;
std::cout << (a->insert(224)) << std::endl;
std::cout << (b->remove(71)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
std::cout << (e->remove(224)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
std::cout << (a->insert(224)) << std::endl;
std::cout << (b->remove(224)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->remove(248)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (d->insert(224)) << std::endl;
*e=*a;
*b=*e;
d->printPretty();
std::cout << (e->insert(126)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
*b=*e;
c->printPretty();
std::cout << (e->remove(224)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
std::cout << (e->insert(174)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
std::cout << (d->insert(488)) << std::endl;
std::cout << (b->insert(126)) << std::endl;
std::cout << (b->remove(224)) << std::endl;
std::cout << (e->remove(212)) << std::endl;
*b=*e;
std::cout << (b->remove(343)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
*b=*e;
std::cout << (a->insert(296)) << std::endl;
e->printPretty();
*e=*c;
std::cout << (d->remove(224)) << std::endl;
*a=*b;
std::cout << (d->insert(299)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (c->insert(292)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
*d=*a;
std::cout << (b->remove(126)) << std::endl;
*e=*e;
std::cout << (a->remove(140)) << std::endl;
std::cout << (c->remove(102)) << std::endl;
std::cout << (b->insert(140)) << std::endl;
a->printPretty();
std::cout << (a->insert(209)) << std::endl;
std::cout << (c->insert(292)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
*a=*a;
*e=*a;
*d=*c;
*c=*c;
e->printPretty();
std::cout << (e->remove(257)) << std::endl;
a->printPretty();
std::cout << (a->insert(395)) << std::endl;
e->printPretty();
std::cout << (e->insert(125)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (e->remove(209)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
e->printPretty();
std::cout << (b->remove(209)) << std::endl;
c->printPretty();
*e=*c;
*b=*d;
std::cout << (b->remove(449)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
*e=*a;
std::cout << (d->insert(14)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
std::cout << (e->remove(263)) << std::endl;
b->printPretty();
std::cout << (b->insert(423)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
d->printPretty();
std::cout << (c->remove(65)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (e->remove(231)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
*e=*a;
*e=*a;
std::cout << (e->remove(57)) << std::endl;
std::cout << (e->insert(142)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
std::cout << (b->insert(423)) << std::endl;
std::cout << (b->remove(441)) << std::endl;
a->printPretty();
std::cout << (b->remove(423)) << std::endl;
std::cout << (e->insert(415)) << std::endl;
*b=*a;
std::cout << (e->remove(142)) << std::endl;
*d=*e;
std::cout << (d->insert(395)) << std::endl;
*b=*b;
std::cout << (a->insert(345)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
*d=*d;
std::cout << (a->remove(498)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
*e=*d;
std::cout << (b->remove(289)) << std::endl;
*b=*d;
std::cout << (d->insert(395)) << std::endl;
*e=*c;
std::cout << (a->insert(345)) << std::endl;
std::cout << (d->remove(204)) << std::endl;
*e=*e;
*b=*e;
std::cout << (c->insert(70)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
*c=*c;
*e=*a;
std::cout << (b->remove(70)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
std::cout << (d->insert(209)) << std::endl;
std::cout << (a->remove(345)) << std::endl;
*a=*a;
std::cout << (c->insert(16)) << std::endl;
std::cout << (d->insert(415)) << std::endl;
b->printPretty();
d->printPretty();
*c=*c;
std::cout << (e->insert(453)) << std::endl;
std::cout << (a->insert(306)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(25)) << std::endl;
*a=*d;
std::cout << (c->remove(245)) << std::endl;
e->printPretty();
std::cout << (b->remove(241)) << std::endl;
*c=*c;
std::cout << (c->insert(138)) << std::endl;
std::cout << (d->remove(12)) << std::endl;
*d=*a;
std::cout << (c->remove(328)) << std::endl;
std::cout << (d->insert(334)) << std::endl;
a->printPretty();
std::cout << (e->remove(166)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
std::cout << (e->insert(453)) << std::endl;
std::cout << (e->remove(453)) << std::endl;
*d=*b;
std::cout << (a->insert(415)) << std::endl;
std::cout << (c->remove(70)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (c->remove(395)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
*e=*b;
std::cout << (b->insert(135)) << std::endl;
*c=*e;
*d=*a;
*a=*d;
std::cout << (b->remove(38)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
std::cout << (a->insert(209)) << std::endl;
std::cout << (b->remove(135)) << std::endl;
*e=*e;
e->printPretty();
*c=*c;
d->printPretty();
std::cout << (d->insert(63)) << std::endl;
*d=*e;
std::cout << (d->insert(161)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (e->remove(66)) << std::endl;
std::cout << (c->remove(145)) << std::endl;
std::cout << (c->remove(282)) << std::endl;
c->printPretty();
*a=*b;
e->printPretty();
a->printPretty();
std::cout << (c->remove(434)) << std::endl;
*d=*e;
std::cout << (d->insert(151)) << std::endl;
e->printPretty();
std::cout << (a->insert(173)) << std::endl;
std::cout << (a->insert(173)) << std::endl;
std::cout << (d->insert(151)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (a->remove(151)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (d->insert(479)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (e->insert(338)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
std::cout << (e->insert(81)) << std::endl;
std::cout << (a->insert(366)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
std::cout << (c->insert(173)) << std::endl;
std::cout << (c->remove(173)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
a->printPretty();
*d=*a;
*a=*c;
std::cout << (d->insert(433)) << std::endl;
*e=*b;
std::cout << (c->insert(60)) << std::endl;
a->printPretty();
std::cout << (d->insert(433)) << std::endl;
b->printPretty();
std::cout << (e->remove(177)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (e->insert(303)) << std::endl;
std::cout << (c->remove(60)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(406)) << std::endl;
std::cout << (b->remove(34)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
std::cout << (d->insert(366)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (e->remove(123)) << std::endl;
*e=*c;
return 0;
}
