#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
*a=*a;
b->printPretty();
*b=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->insert(361)) << std::endl;
b->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (b->remove(265)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (e->remove(489)) << std::endl;
std::cout << (e->insert(35)) << std::endl;
b->printPretty();
std::cout << (d->insert(462)) << std::endl;
std::cout << (e->insert(35)) << std::endl;
d->printPretty();
b->printPretty();
e->printPretty();
std::cout << (e->insert(35)) << std::endl;
std::cout << (a->insert(296)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (d->remove(462)) << std::endl;
d->printPretty();
*e=*a;
*d=*d;
std::cout << (e->insert(472)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (e->remove(472)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
std::cout << (c->remove(386)) << std::endl;
std::cout << (e->insert(187)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->insert(254)) << std::endl;
std::cout << (a->remove(296)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(133)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
b->printPretty();
a->printPretty();
b->printPretty();
e->printPretty();
std::cout << (e->insert(354)) << std::endl;
d->printPretty();
std::cout << (e->remove(410)) << std::endl;
std::cout << (e->insert(144)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
b->printPretty();
*d=*a;
a->printPretty();
std::cout << (c->insert(463)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
std::cout << (a->insert(187)) << std::endl;
std::cout << (c->remove(185)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (e->remove(14)) << std::endl;
*d=*a;
std::cout << (b->remove(440)) << std::endl;
*e=*a;
std::cout << (e->remove(165)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
*c=*d;
std::cout << (d->remove(187)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
*c=*c;
std::cout << (d->insert(354)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
std::cout << (a->remove(396)) << std::endl;
c->printPretty();
std::cout << (e->remove(134)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
a->printPretty();
*e=*a;
c->printPretty();
std::cout << (d->insert(354)) << std::endl;
std::cout << (a->remove(370)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
*c=*b;
std::cout << (d->insert(294)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
*d=*c;
*b=*b;
std::cout << (e->remove(187)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
std::cout << (d->remove(143)) << std::endl;
std::cout << (b->insert(473)) << std::endl;
std::cout << (c->insert(340)) << std::endl;
std::cout << (d->remove(405)) << std::endl;
*d=*a;
std::cout << (c->remove(340)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
*e=*d;
std::cout << (e->insert(338)) << std::endl;
*e=*d;
std::cout << (b->insert(70)) << std::endl;
std::cout << (d->remove(354)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
c->printPretty();
std::cout << (b->insert(109)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
std::cout << (e->remove(480)) << std::endl;
d->printPretty();
std::cout << (c->remove(173)) << std::endl;
b->printPretty();
std::cout << (e->insert(354)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
b->printPretty();
c->printPretty();
a->printPretty();
std::cout << (b->remove(143)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
*e=*b;
std::cout << (c->insert(342)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
*d=*b;
std::cout << (d->remove(109)) << std::endl;
std::cout << (b->remove(454)) << std::endl;
e->printPretty();
c->printPretty();
e->printPretty();
std::cout << (b->remove(472)) << std::endl;
std::cout << (b->insert(473)) << std::endl;
d->printPretty();
std::cout << (e->insert(492)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
std::cout << (d->insert(403)) << std::endl;
*e=*e;
std::cout << (a->insert(354)) << std::endl;
a->printPretty();
std::cout << (d->insert(473)) << std::endl;
std::cout << (d->insert(70)) << std::endl;
std::cout << (b->remove(385)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
e->printPretty();
std::cout << (e->remove(398)) << std::endl;
std::cout << (c->insert(460)) << std::endl;
*a=*a;
std::cout << (b->remove(125)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (d->remove(473)) << std::endl;
*a=*a;
std::cout << (a->remove(215)) << std::endl;
*b=*e;
c->printPretty();
a->printPretty();
std::cout << (e->insert(271)) << std::endl;
*d=*c;
std::cout << (d->remove(143)) << std::endl;
*a=*e;
std::cout << (a->remove(473)) << std::endl;
*a=*a;
c->printPretty();
c->printPretty();
std::cout << (c->insert(342)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
std::cout << (d->insert(84)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (a->insert(271)) << std::endl;
std::cout << (e->remove(402)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
*a=*d;
std::cout << (d->remove(84)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (b->insert(342)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (b->insert(143)) << std::endl;
std::cout << (e->insert(216)) << std::endl;
std::cout << (d->remove(278)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(473)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
std::cout << (e->insert(271)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
a->printPretty();
std::cout << (c->remove(295)) << std::endl;
std::cout << (c->remove(71)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
std::cout << (e->insert(362)) << std::endl;
*a=*e;
std::cout << (b->insert(342)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (c->remove(131)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (a->insert(473)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
a->printPretty();
std::cout << (b->insert(428)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (e->insert(460)) << std::endl;
*b=*a;
std::cout << (d->remove(301)) << std::endl;
std::cout << (b->remove(468)) << std::endl;
std::cout << (e->remove(300)) << std::endl;
std::cout << (e->insert(460)) << std::endl;
std::cout << (e->insert(491)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
b->printPretty();
std::cout << (a->insert(294)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->remove(306)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
std::cout << (a->remove(271)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
*b=*d;
std::cout << (d->remove(485)) << std::endl;
*e=*a;
std::cout << (e->remove(20)) << std::endl;
*e=*a;
a->printPretty();
*d=*d;
std::cout << (b->insert(460)) << std::endl;
c->printPretty();
std::cout << (c->remove(201)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
std::cout << (c->insert(237)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
*d=*a;
std::cout << (a->remove(473)) << std::endl;
*e=*c;
std::cout << (b->remove(283)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (b->insert(75)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
std::cout << (d->insert(492)) << std::endl;
c->printPretty();
std::cout << (a->insert(417)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
std::cout << (a->insert(24)) << std::endl;
std::cout << (d->insert(109)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
*a=*d;
*e=*d;
std::cout << (b->insert(34)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
*e=*d;
std::cout << (d->insert(216)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
c->printPretty();
std::cout << (e->remove(324)) << std::endl;
*b=*a;
std::cout << (c->remove(25)) << std::endl;
std::cout << (a->insert(417)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (c->insert(260)) << std::endl;
*c=*b;
*d=*b;
std::cout << (e->insert(417)) << std::endl;
*b=*a;
*a=*b;
std::cout << (c->insert(417)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->insert(294)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
e->printPretty();
std::cout << (c->remove(216)) << std::endl;
std::cout << (a->remove(130)) << std::endl;
a->printPretty();
std::cout << (b->remove(312)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (e->remove(216)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
b->printPretty();
std::cout << (e->insert(176)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
*e=*e;
*c=*e;
std::cout << (b->remove(263)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (d->remove(73)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
*e=*b;
std::cout << (e->remove(101)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (c->remove(176)) << std::endl;
*b=*c;
std::cout << (d->insert(15)) << std::endl;
std::cout << (b->insert(469)) << std::endl;
std::cout << (d->insert(277)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (a->remove(109)) << std::endl;
std::cout << (b->insert(334)) << std::endl;
std::cout << (e->insert(417)) << std::endl;
std::cout << (c->insert(417)) << std::endl;
*a=*b;
std::cout << (c->remove(199)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->remove(417)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (a->remove(469)) << std::endl;
*b=*c;
std::cout << (c->remove(417)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (d->remove(19)) << std::endl;
std::cout << (a->insert(477)) << std::endl;
std::cout << (b->insert(109)) << std::endl;
std::cout << (a->remove(270)) << std::endl;
std::cout << (a->insert(181)) << std::endl;
std::cout << (b->insert(363)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
*e=*d;
std::cout << (d->insert(322)) << std::endl;
std::cout << (e->remove(102)) << std::endl;
std::cout << (c->remove(147)) << std::endl;
std::cout << (e->insert(401)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
b->printPretty();
std::cout << (c->insert(109)) << std::endl;
*a=*a;
b->printPretty();
d->printPretty();
*e=*c;
std::cout << (e->remove(418)) << std::endl;
*d=*c;
std::cout << (e->remove(109)) << std::endl;
*e=*a;
std::cout << (c->insert(297)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
*d=*c;
std::cout << (d->insert(492)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
*b=*c;
std::cout << (d->remove(297)) << std::endl;
e->printPretty();
std::cout << (d->insert(38)) << std::endl;
*d=*e;
d->printPretty();
*b=*e;
std::cout << (a->remove(266)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (b->remove(281)) << std::endl;
a->printPretty();
std::cout << (b->insert(492)) << std::endl;
std::cout << (a->insert(456)) << std::endl;
std::cout << (d->insert(271)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
std::cout << (a->remove(428)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (b->remove(181)) << std::endl;
*a=*e;
std::cout << (c->insert(458)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (c->remove(63)) << std::endl;
*e=*d;
c->printPretty();
std::cout << (e->remove(153)) << std::endl;
b->printPretty();
d->printPretty();
b->printPretty();
b->printPretty();
std::cout << (e->remove(436)) << std::endl;
std::cout << (b->insert(426)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
*e=*b;
std::cout << (d->remove(271)) << std::endl;
c->printPretty();
std::cout << (c->remove(346)) << std::endl;
*e=*a;
std::cout << (e->remove(181)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->insert(477)) << std::endl;
c->printPretty();
std::cout << (b->insert(338)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(362)) << std::endl;
std::cout << (e->remove(405)) << std::endl;
std::cout << (b->remove(338)) << std::endl;
std::cout << (c->insert(70)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
*d=*b;
std::cout << (e->insert(492)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
*d=*b;
std::cout << (a->insert(304)) << std::endl;
std::cout << (c->insert(109)) << std::endl;
std::cout << (c->remove(70)) << std::endl;
std::cout << (d->insert(408)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
*d=*b;
c->printPretty();
d->printPretty();
std::cout << (b->remove(143)) << std::endl;
std::cout << (e->insert(477)) << std::endl;
e->printPretty();
std::cout << (d->insert(426)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (a->insert(484)) << std::endl;
c->printPretty();
std::cout << (d->remove(169)) << std::endl;
*e=*b;
std::cout << (b->remove(426)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
std::cout << (b->insert(112)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
a->printPretty();
std::cout << (e->remove(151)) << std::endl;
*d=*b;
c->printPretty();
d->printPretty();
*b=*e;
std::cout << (c->insert(316)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
std::cout << (a->remove(304)) << std::endl;
std::cout << (d->insert(334)) << std::endl;
*d=*a;
std::cout << (e->remove(348)) << std::endl;
std::cout << (a->remove(301)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
b->printPretty();
std::cout << (c->insert(316)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (d->insert(184)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (a->remove(334)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (d->remove(62)) << std::endl;
std::cout << (d->remove(181)) << std::endl;
std::cout << (e->remove(483)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
std::cout << (b->remove(83)) << std::endl;
std::cout << (a->remove(181)) << std::endl;
std::cout << (e->remove(477)) << std::endl;
std::cout << (c->insert(316)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->insert(492)) << std::endl;
a->printPretty();
*b=*e;
a->printPretty();
std::cout << (d->remove(334)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
b->printPretty();
*e=*d;
std::cout << (e->insert(496)) << std::endl;
e->printPretty();
std::cout << (d->remove(184)) << std::endl;
std::cout << (b->remove(334)) << std::endl;
c->printPretty();
std::cout << (d->remove(201)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
a->printPretty();
std::cout << (b->remove(492)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (c->remove(411)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
std::cout << (b->remove(426)) << std::endl;
std::cout << (c->insert(474)) << std::endl;
std::cout << (e->insert(192)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (b->remove(445)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
a->printPretty();
std::cout << (a->insert(197)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (d->remove(179)) << std::endl;
*e=*c;
*b=*b;
std::cout << (a->insert(440)) << std::endl;
std::cout << (c->remove(159)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (d->remove(484)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
*d=*e;
*c=*a;
std::cout << (b->insert(387)) << std::endl;
std::cout << (b->insert(387)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (d->remove(218)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
std::cout << (c->insert(440)) << std::endl;
std::cout << (c->insert(154)) << std::endl;
*a=*e;
std::cout << (a->remove(20)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
*c=*c;
std::cout << (d->remove(484)) << std::endl;
std::cout << (c->insert(440)) << std::endl;
*a=*b;
std::cout << (b->remove(33)) << std::endl;
*b=*b;
std::cout << (c->insert(131)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
*d=*c;
c->printPretty();
*a=*d;
std::cout << (b->insert(109)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
std::cout << (d->remove(131)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
*d=*d;
*a=*c;
std::cout << (e->remove(155)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
std::cout << (d->remove(440)) << std::endl;
*d=*e;
std::cout << (a->insert(245)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
std::cout << (a->insert(490)) << std::endl;
std::cout << (b->remove(464)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
a->printPretty();
std::cout << (a->insert(490)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
*a=*b;
std::cout << (e->remove(25)) << std::endl;
std::cout << (a->remove(375)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (c->insert(440)) << std::endl;
*a=*c;
std::cout << (b->insert(375)) << std::endl;
a->printPretty();
*a=*d;
std::cout << (e->remove(474)) << std::endl;
std::cout << (b->remove(62)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
b->printPretty();
std::cout << (d->remove(130)) << std::endl;
*e=*c;
std::cout << (a->insert(474)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (a->insert(360)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
std::cout << (d->remove(46)) << std::endl;
*e=*b;
std::cout << (b->remove(30)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (c->remove(272)) << std::endl;
std::cout << (e->remove(366)) << std::endl;
std::cout << (a->remove(360)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
c->printPretty();
std::cout << (a->remove(484)) << std::endl;
b->printPretty();
d->printPretty();
*c=*e;
std::cout << (b->remove(375)) << std::endl;
std::cout << (e->insert(295)) << std::endl;
*e=*e;
std::cout << (a->remove(83)) << std::endl;
*b=*d;
std::cout << (d->remove(340)) << std::endl;
a->printPretty();
std::cout << (d->remove(401)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
c->printPretty();
std::cout << (d->insert(330)) << std::endl;
*a=*d;
std::cout << (c->remove(277)) << std::endl;
std::cout << (e->remove(295)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
b->printPretty();
std::cout << (b->remove(484)) << std::endl;
a->printPretty();
*c=*a;
e->printPretty();
e->printPretty();
std::cout << (e->insert(375)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
*d=*e;
std::cout << (d->insert(392)) << std::endl;
*a=*c;
std::cout << (a->insert(114)) << std::endl;
std::cout << (c->insert(474)) << std::endl;
std::cout << (d->insert(344)) << std::endl;
*a=*c;
e->printPretty();
e->printPretty();
*d=*c;
std::cout << (c->remove(474)) << std::endl;
std::cout << (a->insert(474)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
std::cout << (d->remove(274)) << std::endl;
std::cout << (b->insert(435)) << std::endl;
std::cout << (c->remove(138)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
*d=*e;
std::cout << (b->insert(440)) << std::endl;
std::cout << (d->remove(176)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
std::cout << (e->remove(51)) << std::endl;
*b=*c;
std::cout << (c->remove(250)) << std::endl;
*c=*a;
*d=*c;
a->printPretty();
std::cout << (e->remove(480)) << std::endl;
std::cout << (a->remove(474)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
*e=*a;
std::cout << (a->insert(126)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
a->printPretty();
std::cout << (c->insert(440)) << std::endl;
return 0;
}
