#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(427)) << std::endl;
a->printPretty();
a->printPretty();
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
c->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>;
d->printPretty();
std::cout << (c->remove(361)) << std::endl;
a->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (d->remove(81)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (b->remove(438)) << std::endl;
std::cout << (a->insert(285)) << std::endl;
a->printPretty();
std::cout << (a->remove(285)) << std::endl;
*b=*e;
std::cout << (a->insert(427)) << std::endl;
e->printPretty();
std::cout << (a->remove(227)) << std::endl;
std::cout << (b->insert(474)) << std::endl;
a->printPretty();
std::cout << (e->insert(219)) << std::endl;
std::cout << (b->insert(430)) << std::endl;
std::cout << (e->remove(21)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->remove(430)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
*d=*e;
std::cout << (b->remove(474)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (c->remove(406)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
*d=*c;
std::cout << (a->insert(427)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
*c=*c;
*c=*c;
std::cout << (c->insert(219)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (b->insert(406)) << std::endl;
std::cout << (b->insert(481)) << std::endl;
e->printPretty();
std::cout << (c->remove(383)) << std::endl;
std::cout << (a->remove(20)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
std::cout << (a->remove(427)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
*b=*a;
std::cout << (b->insert(230)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
std::cout << (d->insert(164)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
a->printPretty();
std::cout << (e->remove(128)) << std::endl;
std::cout << (b->insert(293)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (b->remove(87)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
*b=*a;
*e=*b;
a->printPretty();
std::cout << (d->remove(368)) << std::endl;
*a=*c;
std::cout << (a->remove(219)) << std::endl;
std::cout << (c->insert(296)) << std::endl;
c->printPretty();
std::cout << (d->insert(337)) << std::endl;
std::cout << (d->remove(337)) << std::endl;
std::cout << (c->insert(443)) << std::endl;
std::cout << (a->insert(15)) << std::endl;
a->printPretty();
*e=*d;
std::cout << (c->remove(219)) << std::endl;
*e=*c;
std::cout << (e->insert(83)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
*a=*e;
std::cout << (b->remove(493)) << std::endl;
*d=*e;
std::cout << (d->insert(296)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (d->insert(443)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (c->insert(443)) << std::endl;
d->printPretty();
std::cout << (d->remove(400)) << std::endl;
a->printPretty();
std::cout << (d->insert(296)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
*c=*e;
*c=*d;
std::cout << (d->insert(178)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (d->insert(384)) << std::endl;
*e=*a;
std::cout << (e->remove(361)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (e->remove(390)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
*e=*b;
std::cout << (a->remove(367)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
std::cout << (c->remove(171)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
*c=*c;
std::cout << (e->remove(373)) << std::endl;
std::cout << (a->remove(259)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
a->printPretty();
std::cout << (e->remove(405)) << std::endl;
b->printPretty();
std::cout << (c->insert(29)) << std::endl;
d->printPretty();
std::cout << (a->insert(477)) << std::endl;
*a=*a;
std::cout << (b->remove(465)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
e->printPretty();
std::cout << (d->insert(230)) << std::endl;
std::cout << (d->remove(298)) << std::endl;
std::cout << (a->insert(477)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (c->insert(340)) << std::endl;
std::cout << (a->insert(349)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (c->remove(22)) << std::endl;
*c=*e;
std::cout << (a->remove(349)) << std::endl;
d->printPretty();
std::cout << (e->insert(181)) << std::endl;
std::cout << (a->insert(466)) << std::endl;
std::cout << (c->insert(335)) << std::endl;
c->printPretty();
a->printPretty();
d->printPretty();
std::cout << (c->insert(335)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
std::cout << (e->remove(269)) << std::endl;
b->printPretty();
*d=*e;
*a=*d;
std::cout << (a->insert(50)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (d->remove(335)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
std::cout << (d->remove(9)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
*d=*b;
std::cout << (d->insert(85)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (e->insert(335)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (d->remove(49)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
std::cout << (c->remove(10)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
std::cout << (c->insert(265)) << std::endl;
std::cout << (a->insert(349)) << std::endl;
*c=*d;
std::cout << (a->insert(413)) << std::endl;
*a=*b;
std::cout << (c->insert(411)) << std::endl;
std::cout << (a->insert(334)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
*e=*d;
std::cout << (e->insert(310)) << std::endl;
d->printPretty();
*d=*e;
e->printPretty();
std::cout << (b->remove(16)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
*e=*b;
std::cout << (e->insert(239)) << std::endl;
std::cout << (e->remove(417)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
d->printPretty();
std::cout << (b->remove(85)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
*d=*b;
std::cout << (c->remove(85)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
std::cout << (a->insert(217)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (c->remove(310)) << std::endl;
std::cout << (b->insert(272)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->insert(110)) << std::endl;
std::cout << (b->remove(272)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
b->printPretty();
a->printPretty();
*d=*b;
std::cout << (b->remove(310)) << std::endl;
*d=*e;
std::cout << (e->remove(217)) << std::endl;
a->printPretty();
std::cout << (e->insert(449)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (e->insert(304)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (e->remove(218)) << std::endl;
std::cout << (c->remove(462)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
std::cout << (c->remove(3)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
std::cout << (c->remove(110)) << std::endl;
b->printPretty();
std::cout << (d->insert(411)) << std::endl;
std::cout << (b->remove(136)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
std::cout << (a->insert(334)) << std::endl;
*a=*a;
*e=*b;
std::cout << (c->remove(285)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (a->remove(262)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
*c=*d;
std::cout << (a->insert(215)) << std::endl;
*c=*e;
std::cout << (b->remove(80)) << std::endl;
std::cout << (d->remove(38)) << std::endl;
e->printPretty();
std::cout << (e->insert(100)) << std::endl;
a->printPretty();
std::cout << (a->insert(422)) << std::endl;
std::cout << (c->insert(32)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
*c=*d;
std::cout << (b->remove(358)) << std::endl;
d->printPretty();
*c=*e;
*b=*d;
*e=*d;
std::cout << (a->insert(105)) << std::endl;
e->printPretty();
std::cout << (d->insert(217)) << std::endl;
std::cout << (d->remove(217)) << std::endl;
*e=*c;
std::cout << (b->insert(389)) << std::endl;
d->printPretty();
std::cout << (e->insert(95)) << std::endl;
c->printPretty();
std::cout << (a->insert(203)) << std::endl;
c->printPretty();
*a=*c;
*c=*d;
std::cout << (b->remove(334)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->remove(100)) << std::endl;
e->printPretty();
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
*d=*b;
std::cout << (e->insert(106)) << std::endl;
std::cout << (a->remove(100)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
std::cout << (b->insert(217)) << std::endl;
std::cout << (c->insert(334)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
std::cout << (b->remove(217)) << std::endl;
b->printPretty();
std::cout << (e->remove(106)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
std::cout << (b->remove(34)) << std::endl;
std::cout << (b->insert(310)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (c->remove(310)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->remove(478)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (e->remove(67)) << std::endl;
*e=*c;
std::cout << (e->remove(219)) << std::endl;
*b=*a;
std::cout << (a->remove(95)) << std::endl;
*e=*c;
std::cout << (a->insert(453)) << std::endl;
*e=*b;
std::cout << (c->insert(280)) << std::endl;
*e=*e;
std::cout << (e->insert(95)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
std::cout << (b->remove(95)) << std::endl;
*c=*e;
*d=*b;
std::cout << (b->insert(199)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (a->remove(95)) << std::endl;
std::cout << (c->insert(442)) << std::endl;
std::cout << (c->insert(442)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
b->printPretty();
a->printPretty();
d->printPretty();
std::cout << (a->remove(249)) << std::endl;
*e=*d;
std::cout << (d->remove(471)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (c->remove(199)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (e->insert(246)) << std::endl;
*b=*c;
std::cout << (a->remove(447)) << std::endl;
b->printPretty();
*b=*d;
e->printPretty();
*a=*e;
std::cout << (e->insert(54)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
std::cout << (a->remove(142)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
std::cout << (e->insert(266)) << std::endl;
*b=*b;
d->printPretty();
*c=*e;
d->printPretty();
std::cout << (e->remove(54)) << std::endl;
*d=*b;
a->printPretty();
*d=*d;
std::cout << (d->insert(142)) << std::endl;
std::cout << (a->remove(36)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
*d=*c;
std::cout << (c->remove(246)) << std::endl;
*c=*a;
std::cout << (e->insert(266)) << std::endl;
std::cout << (c->remove(275)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
std::cout << (e->insert(11)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->remove(266)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
c->printPretty();
std::cout << (d->remove(54)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
b->printPretty();
std::cout << (d->insert(497)) << std::endl;
*c=*c;
std::cout << (c->insert(393)) << std::endl;
a->printPretty();
std::cout << (e->remove(11)) << std::endl;
std::cout << (a->insert(442)) << std::endl;
*c=*e;
std::cout << (e->insert(246)) << std::endl;
*b=*e;
std::cout << (b->insert(246)) << std::endl;
std::cout << (e->insert(356)) << std::endl;
std::cout << (e->insert(246)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
std::cout << (d->remove(246)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (a->insert(442)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
*e=*b;
std::cout << (a->insert(372)) << std::endl;
e->printPretty();
std::cout << (c->insert(109)) << std::endl;
b->printPretty();
std::cout << (d->remove(142)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(399)) << std::endl;
std::cout << (e->insert(169)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
std::cout << (d->insert(129)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
d->printPretty();
std::cout << (d->remove(450)) << std::endl;
a->printPretty();
std::cout << (b->insert(246)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (e->insert(446)) << std::endl;
std::cout << (a->remove(485)) << std::endl;
*c=*a;
std::cout << (d->insert(246)) << std::endl;
c->printPretty();
*e=*d;
b->printPretty();
std::cout << (a->insert(149)) << std::endl;
std::cout << (d->insert(290)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
*c=*a;
*c=*a;
a->printPretty();
std::cout << (c->insert(106)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
d->printPretty();
std::cout << (d->insert(246)) << std::endl;
std::cout << (e->remove(290)) << std::endl;
std::cout << (e->insert(246)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
*e=*a;
std::cout << (a->remove(149)) << std::endl;
b->printPretty();
std::cout << (a->insert(151)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
std::cout << (e->remove(312)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (d->insert(246)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
e->printPretty();
std::cout << (d->remove(195)) << std::endl;
std::cout << (e->insert(442)) << std::endl;
d->printPretty();
std::cout << (c->insert(413)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
std::cout << (d->remove(246)) << std::endl;
*e=*b;
std::cout << (a->insert(442)) << std::endl;
std::cout << (c->insert(298)) << std::endl;
*d=*c;
std::cout << (b->insert(362)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
std::cout << (b->insert(362)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (d->remove(45)) << std::endl;
std::cout << (d->insert(122)) << std::endl;
e->printPretty();
std::cout << (a->insert(106)) << std::endl;
a->printPretty();
std::cout << (e->remove(262)) << std::endl;
c->printPretty();
std::cout << (d->remove(395)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
*e=*c;
std::cout << (c->insert(61)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
*b=*c;
*c=*a;
std::cout << (e->remove(372)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (a->insert(442)) << std::endl;
std::cout << (b->remove(298)) << std::endl;
std::cout << (a->remove(82)) << std::endl;
std::cout << (d->remove(100)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (b->remove(442)) << std::endl;
std::cout << (d->remove(106)) << std::endl;
std::cout << (a->insert(149)) << std::endl;
std::cout << (d->remove(151)) << std::endl;
std::cout << (b->remove(256)) << std::endl;
std::cout << (e->insert(433)) << std::endl;
*e=*e;
d->printPretty();
*a=*b;
std::cout << (e->insert(433)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
e->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(151)) << std::endl;
std::cout << (c->remove(275)) << std::endl;
*a=*b;
std::cout << (d->insert(442)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
*a=*a;
*d=*e;
std::cout << (e->remove(442)) << std::endl;
std::cout << (c->insert(106)) << std::endl;
std::cout << (b->insert(200)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (e->remove(433)) << std::endl;
a->printPretty();
std::cout << (e->remove(223)) << std::endl;
a->printPretty();
d->printPretty();
*c=*b;
std::cout << (c->insert(307)) << std::endl;
d->printPretty();
*e=*a;
std::cout << (c->insert(149)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
std::cout << (b->remove(106)) << std::endl;
d->printPretty();
std::cout << (a->remove(151)) << std::endl;
b->printPretty();
std::cout << (a->insert(149)) << std::endl;
std::cout << (d->remove(298)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (b->insert(366)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->remove(200)) << std::endl;
std::cout << (c->insert(455)) << std::endl;
std::cout << (d->remove(106)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
c->printPretty();
std::cout << (c->insert(255)) << std::endl;
a->printPretty();
d->printPretty();
c->printPretty();
b->printPretty();
*a=*a;
e->printPretty();
d->printPretty();
c->printPretty();
e->printPretty();
d->printPretty();
std::cout << (a->insert(96)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->insert(12)) << std::endl;
std::cout << (a->insert(12)) << std::endl;
std::cout << (e->insert(413)) << std::endl;
*e=*c;
std::cout << (e->remove(255)) << std::endl;
*b=*c;
std::cout << (b->remove(146)) << std::endl;
d->printPretty();
std::cout << (a->insert(413)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (d->insert(151)) << std::endl;
std::cout << (b->remove(149)) << std::endl;
*b=*c;
std::cout << (c->insert(317)) << std::endl;
*d=*c;
std::cout << (a->insert(61)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
*e=*c;
*e=*d;
e->printPretty();
std::cout << (d->remove(213)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
e->printPretty();
std::cout << (b->insert(151)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
c->printPretty();
*d=*d;
std::cout << (d->insert(307)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
*e=*d;
std::cout << (e->insert(307)) << std::endl;
std::cout << (d->insert(233)) << std::endl;
std::cout << (b->remove(147)) << std::endl;
std::cout << (e->insert(380)) << std::endl;
c->printPretty();
std::cout << (c->insert(372)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
b->printPretty();
std::cout << (b->remove(151)) << std::endl;
std::cout << (c->remove(386)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (a->remove(310)) << std::endl;
*d=*c;
std::cout << (e->remove(120)) << std::endl;
std::cout << (d->remove(149)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
std::cout << (d->remove(106)) << std::endl;
*a=*b;
std::cout << (e->remove(200)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
std::cout << (c->remove(425)) << std::endl;
std::cout << (d->insert(55)) << std::endl;
e->printPretty();
std::cout << (d->remove(379)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
a->printPretty();
std::cout << (b->insert(200)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
*d=*d;
std::cout << (a->insert(106)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->insert(200)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
std::cout << (c->remove(151)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
std::cout << (e->remove(400)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
c->printPretty();
std::cout << (d->remove(381)) << std::endl;
std::cout << (e->insert(344)) << std::endl;
*b=*c;
*d=*c;
*a=*c;
std::cout << (e->insert(480)) << std::endl;
*b=*a;
std::cout << (e->insert(438)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
std::cout << (d->remove(455)) << std::endl;
std::cout << (a->remove(307)) << std::endl;
std::cout << (b->remove(372)) << std::endl;
std::cout << (a->insert(413)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(413)) << std::endl;
*d=*b;
std::cout << (a->remove(156)) << std::endl;
c->printPretty();
*e=*c;
*e=*e;
std::cout << (a->insert(249)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
std::cout << (a->remove(374)) << std::endl;
std::cout << (a->insert(455)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
*b=*c;
std::cout << (d->insert(342)) << std::endl;
*d=*d;
std::cout << (c->insert(200)) << std::endl;
std::cout << (b->remove(422)) << std::endl;
std::cout << (a->remove(408)) << std::endl;
std::cout << (e->remove(413)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (e->insert(173)) << std::endl;
std::cout << (c->remove(272)) << std::endl;
c->printPretty();
std::cout << (e->insert(99)) << std::endl;
*b=*c;
std::cout << (c->insert(13)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
c->printPretty();
std::cout << (a->remove(379)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
std::cout << (a->remove(426)) << std::endl;
d->printPretty();
std::cout << (d->remove(379)) << std::endl;
b->printPretty();
*d=*a;
*e=*b;
e->printPretty();
std::cout << (c->insert(379)) << std::endl;
return 0;
}
