#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
c->printPretty();
std::cout << (b->insert(399)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
std::cout << (a->remove(169)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->remove(491)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
std::cout << (a->insert(132)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
b->printPretty();
std::cout << (c->insert(246)) << std::endl;
*c=*c;
std::cout << (c->remove(246)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->insert(8)) << std::endl;
a->printPretty();
d->printPretty();
*c=*e;
std::cout << (e->remove(111)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
std::cout << (e->insert(373)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
*b=*b;
std::cout << (d->remove(309)) << std::endl;
*e=*c;
*b=*e;
*d=*c;
std::cout << (a->remove(132)) << std::endl;
*c=*c;
std::cout << (c->remove(94)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
a->printPretty();
*b=*d;
e->printPretty();
e->printPretty();
std::cout << (c->insert(481)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
std::cout << (a->remove(8)) << std::endl;
std::cout << (d->insert(316)) << std::endl;
d->printPretty();
std::cout << (e->insert(473)) << std::endl;
c->printPretty();
std::cout << (a->remove(94)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(473)) << std::endl;
std::cout << (d->insert(94)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->remove(352)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (e->insert(493)) << std::endl;
e->printPretty();
std::cout << (d->remove(283)) << std::endl;
std::cout << (e->remove(166)) << std::endl;
*a=*a;
*e=*b;
std::cout << (e->insert(156)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
std::cout << (a->insert(95)) << std::endl;
std::cout << (a->insert(95)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
std::cout << (d->remove(316)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
e->printPretty();
std::cout << (d->remove(94)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
std::cout << (c->insert(481)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
std::cout << (b->remove(108)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
*a=*b;
*b=*e;
std::cout << (e->remove(91)) << std::endl;
std::cout << (b->remove(187)) << std::endl;
*e=*b;
b->printPretty();
a->printPretty();
std::cout << (e->remove(17)) << std::endl;
a->printPretty();
std::cout << (e->insert(110)) << std::endl;
e->printPretty();
*c=*e;
std::cout << (c->remove(94)) << std::endl;
a->printPretty();
b->printPretty();
*c=*c;
d->printPretty();
std::cout << (b->remove(252)) << std::endl;
std::cout << (a->insert(254)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (e->remove(94)) << std::endl;
*e=*a;
std::cout << (a->insert(254)) << std::endl;
*b=*b;
*d=*b;
std::cout << (d->remove(156)) << std::endl;
std::cout << (a->remove(254)) << std::endl;
*a=*c;
std::cout << (a->insert(133)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
std::cout << (e->insert(254)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
std::cout << (c->insert(110)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (a->insert(240)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->insert(156)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
std::cout << (e->insert(349)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
e->printPretty();
std::cout << (c->remove(166)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
*e=*e;
c->printPretty();
std::cout << (c->remove(111)) << std::endl;
*b=*b;
std::cout << (b->remove(352)) << std::endl;
std::cout << (c->remove(478)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (a->insert(7)) << std::endl;
*a=*d;
std::cout << (d->insert(493)) << std::endl;
std::cout << (e->insert(381)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
*b=*d;
std::cout << (e->remove(381)) << std::endl;
*a=*d;
std::cout << (d->insert(279)) << std::endl;
std::cout << (c->remove(340)) << std::endl;
std::cout << (a->insert(491)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
std::cout << (c->remove(156)) << std::endl;
b->printPretty();
std::cout << (a->insert(491)) << std::endl;
*d=*e;
*b=*a;
d->printPretty();
a->printPretty();
*c=*a;
std::cout << (b->insert(491)) << std::endl;
b->printPretty();
std::cout << (d->remove(296)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
std::cout << (e->insert(200)) << std::endl;
*a=*b;
std::cout << (d->remove(349)) << std::endl;
std::cout << (c->insert(114)) << std::endl;
std::cout << (c->remove(464)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
std::cout << (c->remove(436)) << std::endl;
*b=*d;
std::cout << (b->insert(254)) << std::endl;
std::cout << (c->remove(138)) << std::endl;
std::cout << (e->insert(254)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
*a=*d;
std::cout << (c->remove(67)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
*b=*b;
std::cout << (a->insert(487)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
std::cout << (c->remove(491)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
*e=*c;
std::cout << (e->insert(182)) << std::endl;
e->printPretty();
*c=*b;
*a=*c;
std::cout << (d->remove(304)) << std::endl;
a->printPretty();
std::cout << (d->insert(60)) << std::endl;
*b=*d;
std::cout << (c->remove(417)) << std::endl;
std::cout << (c->insert(124)) << std::endl;
std::cout << (d->insert(60)) << std::endl;
c->printPretty();
std::cout << (b->insert(60)) << std::endl;
std::cout << (d->remove(60)) << std::endl;
std::cout << (b->remove(60)) << std::endl;
std::cout << (e->insert(41)) << std::endl;
std::cout << (e->insert(321)) << std::endl;
std::cout << (b->remove(134)) << std::endl;
*a=*e;
std::cout << (c->remove(222)) << std::endl;
std::cout << (e->remove(41)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->insert(286)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
std::cout << (c->remove(198)) << std::endl;
std::cout << (c->remove(124)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (e->insert(455)) << std::endl;
std::cout << (a->insert(306)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
e->printPretty();
std::cout << (b->remove(423)) << std::endl;
*c=*c;
std::cout << (b->remove(387)) << std::endl;
std::cout << (e->insert(321)) << std::endl;
d->printPretty();
std::cout << (d->insert(390)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
std::cout << (a->remove(171)) << std::endl;
std::cout << (b->remove(80)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
*e=*d;
std::cout << (e->insert(414)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
std::cout << (c->remove(236)) << std::endl;
*a=*a;
*e=*c;
*b=*d;
*e=*d;
std::cout << (d->insert(3)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (a->remove(41)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
std::cout << (a->remove(217)) << std::endl;
b->printPretty();
*a=*e;
*d=*c;
*b=*d;
a->printPretty();
std::cout << (d->remove(341)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
a->printPretty();
std::cout << (c->insert(412)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (b->insert(43)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
c->printPretty();
std::cout << (e->remove(414)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
*b=*c;
std::cout << (d->insert(452)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
*d=*a;
std::cout << (c->remove(294)) << std::endl;
*c=*c;
std::cout << (d->remove(154)) << std::endl;
*c=*d;
*c=*b;
*e=*e;
std::cout << (e->remove(3)) << std::endl;
e->printPretty();
std::cout << (e->insert(179)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (b->insert(100)) << std::endl;
*d=*d;
std::cout << (c->remove(412)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
std::cout << (c->insert(347)) << std::endl;
std::cout << (d->insert(387)) << std::endl;
std::cout << (d->insert(159)) << std::endl;
std::cout << (c->insert(347)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
std::cout << (e->remove(312)) << std::endl;
std::cout << (c->insert(432)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
std::cout << (a->remove(51)) << std::endl;
c->printPretty();
std::cout << (e->remove(371)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
std::cout << (d->remove(159)) << std::endl;
std::cout << (d->insert(387)) << std::endl;
std::cout << (b->insert(255)) << std::endl;
c->printPretty();
std::cout << (d->insert(210)) << std::endl;
*b=*e;
*c=*b;
std::cout << (a->remove(112)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (a->insert(3)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
a->printPretty();
std::cout << (d->insert(175)) << std::endl;
std::cout << (d->insert(478)) << std::endl;
*e=*c;
std::cout << (b->remove(427)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
b->printPretty();
std::cout << (a->insert(444)) << std::endl;
b->printPretty();
*d=*b;
d->printPretty();
*b=*d;
d->printPretty();
std::cout << (c->remove(210)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
*b=*b;
std::cout << (b->insert(105)) << std::endl;
*c=*a;
*e=*d;
std::cout << (c->insert(265)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
d->printPretty();
*d=*a;
d->printPretty();
std::cout << (d->insert(444)) << std::endl;
*a=*c;
std::cout << (b->remove(120)) << std::endl;
*d=*d;
std::cout << (d->insert(444)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
*d=*e;
std::cout << (d->remove(339)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
e->printPretty();
std::cout << (c->insert(265)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (b->remove(105)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (e->remove(427)) << std::endl;
std::cout << (b->insert(476)) << std::endl;
*b=*d;
a->printPretty();
*d=*c;
std::cout << (c->insert(444)) << std::endl;
a->printPretty();
std::cout << (d->remove(411)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (e->remove(47)) << std::endl;
std::cout << (b->insert(325)) << std::endl;
*b=*b;
std::cout << (b->insert(229)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
*b=*d;
std::cout << (b->insert(461)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
*d=*c;
std::cout << (c->insert(265)) << std::endl;
*a=*c;
std::cout << (d->insert(310)) << std::endl;
c->printPretty();
std::cout << (b->remove(461)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
*b=*c;
std::cout << (d->insert(253)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (c->remove(178)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
*a=*a;
std::cout << (b->remove(53)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(130)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->remove(291)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
*d=*e;
std::cout << (c->remove(213)) << std::endl;
b->printPretty();
*a=*d;
c->printPretty();
*c=*d;
std::cout << (a->insert(354)) << std::endl;
std::cout << (c->insert(361)) << std::endl;
a->printPretty();
std::cout << (a->insert(247)) << std::endl;
e->printPretty();
*c=*d;
*e=*b;
std::cout << (b->insert(55)) << std::endl;
std::cout << (c->insert(214)) << std::endl;
*d=*d;
*c=*b;
std::cout << (c->remove(340)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (a->remove(284)) << std::endl;
std::cout << (a->remove(247)) << std::endl;
std::cout << (c->remove(55)) << std::endl;
std::cout << (a->insert(221)) << std::endl;
std::cout << (d->insert(196)) << std::endl;
*d=*e;
*e=*e;
c->printPretty();
std::cout << (c->remove(108)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
*e=*d;
std::cout << (b->insert(55)) << std::endl;
std::cout << (d->remove(423)) << std::endl;
std::cout << (a->insert(221)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
std::cout << (b->remove(55)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (a->insert(444)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (d->remove(134)) << std::endl;
std::cout << (d->remove(272)) << std::endl;
e->printPretty();
a->printPretty();
e->printPretty();
a->printPretty();
a->printPretty();
*b=*e;
std::cout << (b->insert(273)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
d->printPretty();
std::cout << (c->insert(267)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (d->insert(343)) << std::endl;
d->printPretty();
*e=*a;
std::cout << (e->remove(332)) << std::endl;
a->printPretty();
std::cout << (a->insert(50)) << std::endl;
e->printPretty();
std::cout << (e->remove(180)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
std::cout << (c->remove(117)) << std::endl;
e->printPretty();
*b=*d;
std::cout << (d->insert(343)) << std::endl;
std::cout << (d->remove(343)) << std::endl;
*d=*d;
std::cout << (c->insert(168)) << std::endl;
std::cout << (c->insert(168)) << std::endl;
std::cout << (d->insert(344)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->remove(168)) << std::endl;
a->printPretty();
std::cout << (e->remove(444)) << std::endl;
std::cout << (b->remove(117)) << std::endl;
*a=*e;
*c=*e;
e->printPretty();
std::cout << (c->remove(354)) << std::endl;
std::cout << (b->insert(343)) << std::endl;
std::cout << (c->remove(221)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
*a=*d;
std::cout << (b->insert(343)) << std::endl;
std::cout << (b->insert(343)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
std::cout << (a->insert(89)) << std::endl;
std::cout << (e->insert(354)) << std::endl;
std::cout << (b->remove(75)) << std::endl;
b->printPretty();
std::cout << (e->insert(361)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
a->printPretty();
std::cout << (a->remove(89)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
b->printPretty();
std::cout << (c->insert(447)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
*b=*b;
std::cout << (e->remove(405)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
std::cout << (c->insert(219)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
std::cout << (e->insert(361)) << std::endl;
std::cout << (d->remove(186)) << std::endl;
e->printPretty();
std::cout << (c->insert(219)) << std::endl;
std::cout << (c->insert(185)) << std::endl;
std::cout << (b->insert(343)) << std::endl;
*a=*a;
std::cout << (e->insert(460)) << std::endl;
std::cout << (a->insert(159)) << std::endl;
std::cout << (e->remove(442)) << std::endl;
a->printPretty();
*a=*c;
c->printPretty();
b->printPretty();
std::cout << (a->remove(322)) << std::endl;
*d=*c;
std::cout << (a->insert(219)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
*d=*e;
std::cout << (d->remove(221)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
std::cout << (a->remove(59)) << std::endl;
std::cout << (b->remove(51)) << std::endl;
std::cout << (c->remove(424)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (c->insert(146)) << std::endl;
std::cout << (d->insert(392)) << std::endl;
*d=*e;
c->printPretty();
b->printPretty();
std::cout << (e->remove(269)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (c->insert(447)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (a->remove(219)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (c->insert(447)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
*a=*d;
std::cout << (e->insert(135)) << std::endl;
*e=*c;
std::cout << (a->insert(230)) << std::endl;
std::cout << (b->remove(343)) << std::endl;
e->printPretty();
std::cout << (a->insert(354)) << std::endl;
std::cout << (c->insert(410)) << std::endl;
*a=*b;
*c=*e;
std::cout << (c->remove(411)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (d->insert(185)) << std::endl;
*a=*e;
*d=*b;
std::cout << (d->remove(439)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
d->printPretty();
std::cout << (a->insert(229)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
std::cout << (c->insert(417)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (a->insert(437)) << std::endl;
a->printPretty();
std::cout << (d->insert(266)) << std::endl;
std::cout << (c->insert(185)) << std::endl;
a->printPretty();
std::cout << (b->remove(278)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
std::cout << (e->insert(424)) << std::endl;
std::cout << (d->remove(372)) << std::endl;
std::cout << (c->insert(403)) << std::endl;
std::cout << (b->insert(124)) << std::endl;
b->printPretty();
std::cout << (c->insert(447)) << std::endl;
*a=*a;
std::cout << (c->insert(245)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
std::cout << (c->remove(439)) << std::endl;
*d=*b;
std::cout << (c->remove(146)) << std::endl;
std::cout << (e->insert(424)) << std::endl;
a->printPretty();
std::cout << (e->remove(367)) << std::endl;
std::cout << (d->remove(124)) << std::endl;
e->printPretty();
std::cout << (c->insert(24)) << std::endl;
*d=*d;
d->printPretty();
std::cout << (c->insert(472)) << std::endl;
std::cout << (c->insert(307)) << std::endl;
std::cout << (a->remove(229)) << std::endl;
d->printPretty();
std::cout << (b->remove(124)) << std::endl;
d->printPretty();
std::cout << (d->insert(90)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
*a=*d;
std::cout << (b->remove(149)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
*b=*e;
std::cout << (b->remove(219)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
std::cout << (c->insert(219)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (d->remove(90)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
std::cout << (a->insert(500)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
std::cout << (b->insert(38)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
std::cout << (b->insert(457)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
std::cout << (a->insert(198)) << std::endl;
std::cout << (b->remove(328)) << std::endl;
c->printPretty();
std::cout << (b->remove(146)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
*b=*e;
std::cout << (c->insert(403)) << std::endl;
*e=*a;
std::cout << (a->remove(386)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (d->remove(165)) << std::endl;
std::cout << (e->insert(231)) << std::endl;
b->printPretty();
std::cout << (d->insert(139)) << std::endl;
d->printPretty();
*d=*b;
c->printPretty();
std::cout << (e->insert(182)) << std::endl;
c->printPretty();
std::cout << (e->insert(198)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
std::cout << (b->remove(185)) << std::endl;
e->printPretty();
std::cout << (c->remove(140)) << std::endl;
std::cout << (a->remove(185)) << std::endl;
d->printPretty();
std::cout << (d->remove(296)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
std::cout << (e->insert(185)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
a->printPretty();
*e=*d;
c->printPretty();
std::cout << (a->remove(167)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
e->printPretty();
std::cout << (c->insert(356)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
std::cout << (a->remove(308)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
*c=*e;
std::cout << (b->remove(152)) << std::endl;
std::cout << (e->remove(494)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
*c=*e;
std::cout << (a->insert(313)) << std::endl;
std::cout << (c->remove(146)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (e->insert(424)) << std::endl;
std::cout << (d->remove(481)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (a->insert(424)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
*d=*b;
std::cout << (a->insert(146)) << std::endl;
*a=*e;
c->printPretty();
std::cout << (e->insert(3)) << std::endl;
std::cout << (e->insert(460)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
a->printPretty();
std::cout << (b->remove(49)) << std::endl;
std::cout << (a->insert(313)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
std::cout << (d->insert(94)) << std::endl;
std::cout << (c->insert(38)) << std::endl;
std::cout << (b->remove(214)) << std::endl;
b->printPretty();
std::cout << (e->insert(100)) << std::endl;
std::cout << (a->insert(109)) << std::endl;
std::cout << (c->insert(20)) << std::endl;
*c=*e;
std::cout << (a->insert(109)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (c->remove(146)) << std::endl;
return 0;
}
