#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(2)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
b->printPretty();
*b=*b;
*b=*b;
std::cout << (a->insert(44)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
std::cout << (a->remove(468)) << std::endl;
b->printPretty();
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (c->insert(275)) << std::endl;
std::cout << (b->insert(398)) << std::endl;
std::cout << (c->insert(269)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*b=*d;
*c=*c;
std::cout << (d->insert(207)) << std::endl;
std::cout << (c->remove(8)) << std::endl;
std::cout << (c->insert(62)) << std::endl;
std::cout << (e->insert(489)) << std::endl;
std::cout << (c->insert(62)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
c->printPretty();
std::cout << (b->remove(5)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (e->insert(38)) << std::endl;
e->printPretty();
std::cout << (d->insert(207)) << std::endl;
std::cout << (d->insert(336)) << std::endl;
*c=*d;
std::cout << (a->remove(419)) << std::endl;
b->printPretty();
*d=*e;
c->printPretty();
a->printPretty();
*d=*e;
std::cout << (e->insert(228)) << std::endl;
b->printPretty();
std::cout << (c->remove(207)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
e->printPretty();
std::cout << (b->remove(485)) << std::endl;
std::cout << (c->insert(336)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (a->insert(44)) << std::endl;
*b=*e;
std::cout << (e->remove(38)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (d->insert(462)) << std::endl;
std::cout << (c->remove(336)) << std::endl;
*b=*a;
a->printPretty();
*a=*a;
c->printPretty();
std::cout << (b->remove(47)) << std::endl;
std::cout << (e->remove(228)) << std::endl;
std::cout << (e->insert(489)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
c->printPretty();
std::cout << (d->insert(233)) << std::endl;
std::cout << (d->remove(182)) << std::endl;
std::cout << (a->remove(409)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
*d=*c;
*e=*b;
std::cout << (e->remove(36)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
e->printPretty();
std::cout << (c->remove(234)) << std::endl;
c->printPretty();
a->printPretty();
*d=*e;
std::cout << (e->insert(44)) << std::endl;
*b=*b;
*a=*e;
std::cout << (a->remove(44)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
std::cout << (e->insert(393)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (a->insert(393)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (c->insert(81)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
*e=*a;
std::cout << (c->insert(81)) << std::endl;
std::cout << (e->insert(328)) << std::endl;
*d=*d;
*c=*e;
std::cout << (c->insert(139)) << std::endl;
std::cout << (e->remove(328)) << std::endl;
std::cout << (e->insert(388)) << std::endl;
*c=*e;
std::cout << (c->insert(108)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(44)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (c->remove(306)) << std::endl;
std::cout << (e->insert(363)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
*c=*a;
std::cout << (d->insert(76)) << std::endl;
*b=*e;
std::cout << (c->remove(58)) << std::endl;
e->printPretty();
std::cout << (b->insert(92)) << std::endl;
a->printPretty();
std::cout << (d->insert(404)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
e->printPretty();
std::cout << (c->insert(169)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
*a=*c;
*a=*c;
std::cout << (a->insert(493)) << std::endl;
e->printPretty();
std::cout << (d->insert(69)) << std::endl;
*c=*c;
std::cout << (e->remove(69)) << std::endl;
std::cout << (c->insert(452)) << std::endl;
b->printPretty();
std::cout << (c->remove(452)) << std::endl;
d->printPretty();
std::cout << (b->remove(170)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
std::cout << (a->insert(46)) << std::endl;
d->printPretty();
std::cout << (a->remove(237)) << std::endl;
std::cout << (e->insert(247)) << std::endl;
*d=*c;
std::cout << (b->remove(92)) << std::endl;
c->printPretty();
std::cout << (a->insert(388)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
*e=*e;
std::cout << (a->insert(46)) << std::endl;
d->printPretty();
std::cout << (e->insert(363)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
std::cout << (a->remove(388)) << std::endl;
b->printPretty();
std::cout << (b->remove(388)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (a->remove(169)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
b->printPretty();
std::cout << (b->remove(69)) << std::endl;
c->printPretty();
std::cout << (c->remove(207)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
std::cout << (b->insert(423)) << std::endl;
b->printPretty();
*b=*e;
std::cout << (a->remove(406)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (e->insert(247)) << std::endl;
d->printPretty();
std::cout << (c->remove(236)) << std::endl;
std::cout << (a->remove(38)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
c->printPretty();
std::cout << (e->insert(169)) << std::endl;
std::cout << (d->insert(87)) << std::endl;
a->printPretty();
std::cout << (a->remove(46)) << std::endl;
*b=*b;
std::cout << (e->insert(351)) << std::endl;
std::cout << (c->remove(253)) << std::endl;
*b=*a;
std::cout << (e->remove(351)) << std::endl;
std::cout << (b->remove(28)) << std::endl;
std::cout << (d->remove(87)) << std::endl;
std::cout << (d->insert(161)) << std::endl;
std::cout << (e->insert(347)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
c->printPretty();
b->printPretty();
*b=*a;
std::cout << (c->remove(262)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (a->insert(493)) << std::endl;
*e=*e;
std::cout << (a->remove(19)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
std::cout << (d->remove(427)) << std::endl;
std::cout << (e->remove(388)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
std::cout << (a->remove(50)) << std::endl;
std::cout << (e->remove(347)) << std::endl;
std::cout << (e->remove(491)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
c->printPretty();
std::cout << (c->insert(92)) << std::endl;
*c=*e;
*b=*e;
std::cout << (a->insert(112)) << std::endl;
std::cout << (c->remove(268)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
b->printPretty();
std::cout << (b->insert(243)) << std::endl;
std::cout << (c->insert(71)) << std::endl;
a->printPretty();
std::cout << (c->insert(198)) << std::endl;
*c=*d;
std::cout << (e->insert(169)) << std::endl;
std::cout << (e->remove(27)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
std::cout << (b->insert(169)) << std::endl;
*c=*b;
*c=*c;
*e=*c;
std::cout << (d->remove(286)) << std::endl;
a->printPretty();
std::cout << (d->remove(464)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (a->remove(112)) << std::endl;
*b=*d;
*b=*e;
std::cout << (a->insert(493)) << std::endl;
std::cout << (c->insert(169)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
*c=*b;
std::cout << (a->remove(79)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
std::cout << (c->insert(60)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
c->printPretty();
std::cout << (e->remove(187)) << std::endl;
b->printPretty();
b->printPretty();
*a=*c;
std::cout << (e->insert(247)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (d->insert(390)) << std::endl;
std::cout << (e->remove(199)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
*a=*d;
b->printPretty();
std::cout << (c->insert(243)) << std::endl;
c->printPretty();
std::cout << (b->insert(414)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
a->printPretty();
std::cout << (e->insert(247)) << std::endl;
std::cout << (a->remove(390)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
std::cout << (e->insert(235)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (e->remove(434)) << std::endl;
*d=*d;
std::cout << (d->insert(390)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (c->remove(238)) << std::endl;
std::cout << (b->insert(353)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (e->remove(247)) << std::endl;
std::cout << (c->insert(383)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
*c=*d;
*b=*c;
std::cout << (c->remove(37)) << std::endl;
std::cout << (c->remove(238)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
*a=*d;
std::cout << (a->insert(390)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
std::cout << (e->insert(385)) << std::endl;
*d=*e;
std::cout << (b->insert(390)) << std::endl;
std::cout << (b->insert(451)) << std::endl;
e->printPretty();
std::cout << (e->remove(385)) << std::endl;
*d=*c;
c->printPretty();
*a=*b;
e->printPretty();
b->printPretty();
std::cout << (d->insert(317)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
std::cout << (a->remove(257)) << std::endl;
std::cout << (d->insert(418)) << std::endl;
d->printPretty();
std::cout << (e->insert(339)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
*d=*d;
std::cout << (a->insert(390)) << std::endl;
*d=*e;
std::cout << (e->insert(130)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->remove(284)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
b->printPretty();
std::cout << (d->remove(174)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (d->remove(204)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
c->printPretty();
d->printPretty();
*b=*e;
std::cout << (b->remove(332)) << std::endl;
*d=*a;
*d=*e;
std::cout << (b->insert(353)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (c->remove(390)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
*e=*e;
*b=*c;
std::cout << (b->insert(184)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
*e=*a;
std::cout << (b->remove(445)) << std::endl;
std::cout << (b->remove(257)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
std::cout << (a->remove(8)) << std::endl;
std::cout << (a->remove(419)) << std::endl;
std::cout << (c->insert(125)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
std::cout << (a->insert(483)) << std::endl;
std::cout << (d->insert(346)) << std::endl;
std::cout << (a->remove(19)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
*b=*b;
std::cout << (e->insert(390)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(500)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
*b=*d;
std::cout << (e->remove(295)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (e->insert(402)) << std::endl;
std::cout << (b->remove(346)) << std::endl;
*e=*e;
std::cout << (e->remove(470)) << std::endl;
std::cout << (d->insert(156)) << std::endl;
std::cout << (b->insert(246)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
c->printPretty();
std::cout << (a->insert(451)) << std::endl;
std::cout << (a->insert(262)) << std::endl;
std::cout << (d->remove(314)) << std::endl;
c->printPretty();
b->printPretty();
*d=*c;
*e=*c;
*a=*b;
std::cout << (e->remove(206)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
*e=*c;
a->printPretty();
std::cout << (d->remove(402)) << std::endl;
std::cout << (e->insert(424)) << std::endl;
std::cout << (d->remove(442)) << std::endl;
e->printPretty();
std::cout << (e->insert(167)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
std::cout << (a->insert(235)) << std::endl;
std::cout << (e->remove(424)) << std::endl;
std::cout << (c->insert(60)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->insert(337)) << std::endl;
*c=*d;
std::cout << (e->remove(167)) << std::endl;
*b=*c;
*a=*b;
c->printPretty();
std::cout << (a->remove(81)) << std::endl;
std::cout << (d->remove(84)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
e->printPretty();
std::cout << (d->remove(497)) << std::endl;
*d=*b;
*b=*d;
std::cout << (a->remove(337)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
*c=*e;
std::cout << (b->insert(231)) << std::endl;
std::cout << (b->remove(495)) << std::endl;
*b=*a;
c->printPretty();
*c=*d;
std::cout << (d->insert(337)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
*e=*e;
*e=*a;
*e=*d;
std::cout << (e->remove(197)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
a->printPretty();
std::cout << (b->remove(197)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (b->insert(179)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (d->insert(337)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (a->insert(301)) << std::endl;
c->printPretty();
std::cout << (b->insert(314)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (e->remove(263)) << std::endl;
std::cout << (d->insert(197)) << std::endl;
*e=*d;
std::cout << (c->remove(36)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(337)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (e->insert(483)) << std::endl;
std::cout << (d->remove(263)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (a->remove(197)) << std::endl;
std::cout << (a->remove(301)) << std::endl;
std::cout << (a->remove(160)) << std::endl;
std::cout << (e->insert(496)) << std::endl;
std::cout << (d->insert(459)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
std::cout << (e->insert(263)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (a->remove(115)) << std::endl;
*e=*a;
std::cout << (b->insert(314)) << std::endl;
std::cout << (d->insert(459)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
std::cout << (a->remove(118)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
b->printPretty();
std::cout << (a->insert(243)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (b->insert(498)) << std::endl;
*b=*b;
std::cout << (c->remove(498)) << std::endl;
std::cout << (e->remove(314)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
std::cout << (b->remove(301)) << std::endl;
b->printPretty();
std::cout << (e->insert(321)) << std::endl;
*c=*c;
d->printPretty();
e->printPretty();
std::cout << (a->insert(177)) << std::endl;
std::cout << (c->insert(60)) << std::endl;
std::cout << (d->insert(459)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
std::cout << (d->remove(197)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
std::cout << (b->remove(133)) << std::endl;
std::cout << (c->remove(60)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (a->insert(177)) << std::endl;
std::cout << (b->remove(162)) << std::endl;
std::cout << (e->remove(491)) << std::endl;
*c=*e;
std::cout << (b->insert(214)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
a->printPretty();
std::cout << (b->remove(314)) << std::endl;
e->printPretty();
std::cout << (c->remove(194)) << std::endl;
*b=*d;
*c=*a;
std::cout << (b->remove(265)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (b->insert(459)) << std::endl;
*b=*c;
std::cout << (a->insert(116)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (e->remove(445)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
std::cout << (a->remove(37)) << std::endl;
a->printPretty();
std::cout << (d->insert(92)) << std::endl;
std::cout << (b->insert(311)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(345)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
*b=*c;
std::cout << (d->insert(393)) << std::endl;
std::cout << (c->insert(292)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
d->printPretty();
std::cout << (b->remove(434)) << std::endl;
std::cout << (e->remove(345)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
d->printPretty();
std::cout << (b->remove(318)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
b->printPretty();
std::cout << (b->insert(177)) << std::endl;
b->printPretty();
std::cout << (c->insert(177)) << std::endl;
std::cout << (b->insert(133)) << std::endl;
std::cout << (a->remove(88)) << std::endl;
std::cout << (a->remove(84)) << std::endl;
std::cout << (e->remove(1)) << std::endl;
*d=*e;
*c=*a;
std::cout << (c->remove(116)) << std::endl;
c->printPretty();
std::cout << (e->insert(414)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
std::cout << (b->insert(131)) << std::endl;
std::cout << (d->remove(414)) << std::endl;
a->printPretty();
std::cout << (b->insert(165)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (a->insert(365)) << std::endl;
a->printPretty();
std::cout << (d->remove(383)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (b->remove(131)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
d->printPretty();
std::cout << (c->remove(47)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (a->insert(365)) << std::endl;
*a=*b;
std::cout << (e->remove(471)) << std::endl;
std::cout << (d->insert(482)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
std::cout << (e->insert(174)) << std::endl;
*c=*d;
std::cout << (e->insert(414)) << std::endl;
std::cout << (b->remove(133)) << std::endl;
std::cout << (b->insert(86)) << std::endl;
std::cout << (d->remove(4)) << std::endl;
d->printPretty();
std::cout << (e->remove(414)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
*d=*c;
std::cout << (c->insert(290)) << std::endl;
c->printPretty();
std::cout << (d->insert(369)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
c->printPretty();
std::cout << (c->remove(482)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
std::cout << (e->remove(464)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (b->insert(26)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (a->insert(177)) << std::endl;
std::cout << (a->insert(374)) << std::endl;
std::cout << (d->insert(496)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
b->printPretty();
*d=*b;
*d=*d;
std::cout << (d->insert(48)) << std::endl;
*c=*d;
std::cout << (a->insert(165)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
b->printPretty();
c->printPretty();
*c=*e;
a->printPretty();
b->printPretty();
*b=*a;
std::cout << (b->remove(62)) << std::endl;
e->printPretty();
std::cout << (a->remove(8)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (b->insert(422)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
*e=*a;
std::cout << (b->remove(264)) << std::endl;
*e=*d;
*b=*b;
std::cout << (c->insert(72)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
std::cout << (b->remove(422)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (e->insert(329)) << std::endl;
*d=*b;
std::cout << (b->insert(133)) << std::endl;
*e=*b;
std::cout << (a->insert(56)) << std::endl;
std::cout << (e->remove(133)) << std::endl;
std::cout << (b->remove(230)) << std::endl;
std::cout << (e->remove(177)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
d->printPretty();
std::cout << (b->remove(177)) << std::endl;
std::cout << (c->insert(285)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
std::cout << (b->remove(66)) << std::endl;
d->printPretty();
std::cout << (b->insert(299)) << std::endl;
*e=*d;
std::cout << (c->insert(273)) << std::endl;
c->printPretty();
std::cout << (a->insert(488)) << std::endl;
std::cout << (d->remove(165)) << std::endl;
std::cout << (c->insert(285)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
std::cout << (d->remove(429)) << std::endl;
std::cout << (d->insert(492)) << std::endl;
a->printPretty();
std::cout << (c->insert(13)) << std::endl;
std::cout << (c->insert(42)) << std::endl;
*e=*a;
std::cout << (a->insert(296)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
d->printPretty();
std::cout << (e->insert(165)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (b->insert(133)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (a->remove(357)) << std::endl;
*b=*b;
std::cout << (c->insert(6)) << std::endl;
*b=*a;
return 0;
}
