#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(268)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
*a=*a;
std::cout << (a->remove(41)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*a=*a;
std::cout << (b->remove(277)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
b->printPretty();
std::cout << (b->remove(412)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
*a=*b;
a->printPretty();
e->printPretty();
b->printPretty();
*a=*c;
std::cout << (d->insert(373)) << std::endl;
std::cout << (e->remove(97)) << std::endl;
d->printPretty();
d->printPretty();
c->printPretty();
std::cout << (a->remove(261)) << std::endl;
std::cout << (e->remove(334)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
std::cout << (d->insert(195)) << std::endl;
std::cout << (a->insert(139)) << std::endl;
a->printPretty();
std::cout << (c->insert(318)) << std::endl;
*b=*e;
std::cout << (c->remove(318)) << std::endl;
b->printPretty();
*b=*d;
std::cout << (b->insert(373)) << std::endl;
std::cout << (d->insert(373)) << std::endl;
std::cout << (e->insert(240)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
std::cout << (e->remove(240)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
*d=*a;
std::cout << (d->insert(395)) << std::endl;
std::cout << (c->insert(370)) << std::endl;
std::cout << (c->remove(403)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (e->insert(204)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (a->insert(232)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
std::cout << (d->insert(288)) << std::endl;
c->printPretty();
std::cout << (b->insert(373)) << std::endl;
a->printPretty();
std::cout << (d->insert(362)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
std::cout << (b->remove(3)) << std::endl;
*b=*e;
std::cout << (e->insert(109)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
d->printPretty();
std::cout << (e->insert(269)) << std::endl;
std::cout << (e->insert(363)) << std::endl;
d->printPretty();
std::cout << (d->remove(34)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
c->printPretty();
*a=*a;
*c=*d;
std::cout << (e->insert(363)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (a->insert(232)) << std::endl;
*b=*e;
std::cout << (c->insert(251)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (d->remove(370)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
std::cout << (e->insert(125)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (a->remove(105)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (d->insert(158)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
std::cout << (b->remove(222)) << std::endl;
std::cout << (c->insert(361)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (a->insert(435)) << std::endl;
*e=*d;
e->printPretty();
b->printPretty();
std::cout << (d->remove(12)) << std::endl;
*d=*d;
std::cout << (c->insert(197)) << std::endl;
std::cout << (e->remove(81)) << std::endl;
*c=*d;
std::cout << (d->remove(362)) << std::endl;
std::cout << (d->remove(288)) << std::endl;
std::cout << (c->remove(362)) << std::endl;
std::cout << (e->remove(227)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
c->printPretty();
std::cout << (a->remove(435)) << std::endl;
std::cout << (b->remove(288)) << std::endl;
std::cout << (e->remove(389)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
c->printPretty();
std::cout << (c->remove(288)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (b->insert(259)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (a->insert(30)) << std::endl;
*c=*c;
std::cout << (d->insert(307)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (b->remove(143)) << std::endl;
b->printPretty();
std::cout << (a->insert(30)) << std::endl;
std::cout << (a->remove(30)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
*a=*b;
std::cout << (c->remove(128)) << std::endl;
std::cout << (e->remove(315)) << std::endl;
*d=*d;
std::cout << (a->remove(303)) << std::endl;
c->printPretty();
std::cout << (b->remove(376)) << std::endl;
a->printPretty();
std::cout << (e->remove(362)) << std::endl;
std::cout << (d->insert(307)) << std::endl;
std::cout << (e->insert(288)) << std::endl;
std::cout << (e->insert(443)) << std::endl;
std::cout << (e->remove(121)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
*a=*d;
std::cout << (c->remove(143)) << std::endl;
*e=*d;
std::cout << (d->insert(307)) << std::endl;
*a=*a;
std::cout << (b->insert(306)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
std::cout << (e->insert(304)) << std::endl;
*d=*d;
std::cout << (b->remove(206)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
d->printPretty();
std::cout << (a->insert(203)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
std::cout << (a->remove(203)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
std::cout << (e->remove(304)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (b->insert(159)) << std::endl;
std::cout << (d->remove(381)) << std::endl;
std::cout << (e->remove(286)) << std::endl;
e->printPretty();
std::cout << (e->remove(281)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
std::cout << (e->insert(183)) << std::endl;
a->printPretty();
std::cout << (a->remove(307)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (b->insert(462)) << std::endl;
d->printPretty();
c->printPretty();
*b=*d;
std::cout << (a->insert(342)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
e->printPretty();
std::cout << (d->remove(112)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (e->remove(94)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
*a=*d;
*a=*a;
std::cout << (c->insert(281)) << std::endl;
std::cout << (a->insert(463)) << std::endl;
std::cout << (d->remove(374)) << std::endl;
c->printPretty();
std::cout << (c->remove(281)) << std::endl;
*a=*c;
std::cout << (e->insert(210)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
b->printPretty();
std::cout << (c->insert(358)) << std::endl;
std::cout << (e->insert(145)) << std::endl;
std::cout << (e->insert(210)) << std::endl;
b->printPretty();
std::cout << (c->remove(277)) << std::endl;
c->printPretty();
std::cout << (a->insert(244)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
std::cout << (c->insert(358)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
e->printPretty();
*a=*a;
std::cout << (a->insert(368)) << std::endl;
std::cout << (e->insert(212)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
*c=*e;
a->printPretty();
std::cout << (e->remove(210)) << std::endl;
std::cout << (c->remove(350)) << std::endl;
*b=*a;
std::cout << (a->insert(268)) << std::endl;
std::cout << (d->insert(138)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
d->printPretty();
std::cout << (d->remove(138)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
d->printPretty();
std::cout << (e->remove(52)) << std::endl;
std::cout << (c->remove(183)) << std::endl;
*e=*c;
std::cout << (b->insert(44)) << std::endl;
c->printPretty();
std::cout << (b->insert(44)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
std::cout << (c->remove(145)) << std::endl;
*a=*a;
std::cout << (d->remove(438)) << std::endl;
std::cout << (c->insert(210)) << std::endl;
d->printPretty();
std::cout << (e->insert(52)) << std::endl;
std::cout << (c->remove(210)) << std::endl;
std::cout << (a->insert(268)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (e->insert(65)) << std::endl;
std::cout << (c->remove(212)) << std::endl;
a->printPretty();
std::cout << (b->insert(44)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
d->printPretty();
std::cout << (b->remove(89)) << std::endl;
c->printPretty();
std::cout << (e->insert(210)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
*c=*c;
std::cout << (a->insert(445)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (c->insert(125)) << std::endl;
d->printPretty();
e->printPretty();
*c=*a;
*b=*c;
std::cout << (b->remove(481)) << std::endl;
b->printPretty();
std::cout << (e->remove(447)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
std::cout << (e->remove(212)) << std::endl;
c->printPretty();
std::cout << (a->remove(162)) << std::endl;
*d=*e;
std::cout << (c->remove(488)) << std::endl;
*d=*a;
std::cout << (b->insert(268)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
*a=*e;
std::cout << (b->insert(488)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
std::cout << (a->insert(145)) << std::endl;
std::cout << (c->insert(405)) << std::endl;
*e=*e;
std::cout << (a->insert(280)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
e->printPretty();
*d=*a;
d->printPretty();
std::cout << (c->insert(405)) << std::endl;
std::cout << (b->remove(435)) << std::endl;
std::cout << (c->remove(441)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (d->insert(52)) << std::endl;
*c=*a;
std::cout << (b->insert(368)) << std::endl;
std::cout << (d->remove(280)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
*e=*c;
std::cout << (e->insert(251)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
d->printPretty();
std::cout << (c->insert(280)) << std::endl;
std::cout << (a->insert(3)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (e->insert(457)) << std::endl;
*d=*c;
*e=*e;
*d=*c;
std::cout << (e->remove(105)) << std::endl;
std::cout << (a->insert(210)) << std::endl;
*a=*b;
e->printPretty();
b->printPretty();
std::cout << (d->insert(280)) << std::endl;
std::cout << (b->remove(488)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
*b=*c;
std::cout << (e->remove(457)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
std::cout << (a->remove(454)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (b->remove(190)) << std::endl;
*e=*e;
e->printPretty();
std::cout << (b->insert(210)) << std::endl;
b->printPretty();
std::cout << (b->insert(210)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
d->printPretty();
std::cout << (c->insert(59)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (e->remove(22)) << std::endl;
*e=*d;
std::cout << (e->remove(56)) << std::endl;
*e=*c;
std::cout << (e->remove(210)) << std::endl;
std::cout << (b->remove(60)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
*e=*c;
std::cout << (a->remove(445)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (b->remove(210)) << std::endl;
c->printPretty();
std::cout << (e->remove(65)) << std::endl;
*b=*a;
std::cout << (b->insert(146)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
std::cout << (e->insert(134)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
*e=*a;
std::cout << (b->remove(263)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
*b=*c;
std::cout << (e->remove(35)) << std::endl;
std::cout << (c->remove(65)) << std::endl;
*c=*e;
*d=*c;
c->printPretty();
a->printPretty();
std::cout << (c->remove(222)) << std::endl;
std::cout << (d->insert(488)) << std::endl;
e->printPretty();
std::cout << (a->remove(420)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
std::cout << (c->remove(146)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
a->printPretty();
*e=*c;
*e=*b;
std::cout << (c->remove(35)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (b->remove(391)) << std::endl;
std::cout << (e->remove(298)) << std::endl;
a->printPretty();
std::cout << (a->remove(488)) << std::endl;
*e=*b;
std::cout << (c->remove(488)) << std::endl;
c->printPretty();
std::cout << (b->remove(65)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
b->printPretty();
std::cout << (c->remove(23)) << std::endl;
std::cout << (c->remove(302)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (e->insert(400)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
std::cout << (c->insert(368)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
b->printPretty();
std::cout << (e->remove(400)) << std::endl;
std::cout << (e->remove(210)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (d->remove(80)) << std::endl;
std::cout << (d->insert(146)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
*a=*e;
std::cout << (c->insert(453)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (a->remove(412)) << std::endl;
std::cout << (a->remove(44)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
*b=*a;
std::cout << (a->remove(145)) << std::endl;
*a=*b;
std::cout << (a->remove(145)) << std::endl;
*e=*d;
*b=*a;
d->printPretty();
std::cout << (a->remove(59)) << std::endl;
std::cout << (d->insert(488)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
*d=*e;
e->printPretty();
b->printPretty();
std::cout << (d->remove(222)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
std::cout << (a->remove(65)) << std::endl;
*c=*e;
std::cout << (d->insert(368)) << std::endl;
std::cout << (b->remove(59)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
*c=*c;
std::cout << (d->insert(488)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
std::cout << (b->insert(52)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
std::cout << (d->remove(494)) << std::endl;
a->printPretty();
*e=*d;
std::cout << (e->insert(282)) << std::endl;
std::cout << (a->insert(52)) << std::endl;
std::cout << (c->insert(367)) << std::endl;
d->printPretty();
e->printPretty();
*a=*e;
c->printPretty();
e->printPretty();
a->printPretty();
*a=*a;
std::cout << (b->insert(65)) << std::endl;
std::cout << (c->insert(364)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (a->insert(240)) << std::endl;
*c=*e;
std::cout << (e->insert(339)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
std::cout << (b->remove(52)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
*e=*c;
std::cout << (a->insert(240)) << std::endl;
std::cout << (e->remove(128)) << std::endl;
std::cout << (c->remove(282)) << std::endl;
e->printPretty();
std::cout << (e->remove(249)) << std::endl;
*b=*c;
std::cout << (e->insert(146)) << std::endl;
*b=*d;
*c=*b;
std::cout << (b->insert(382)) << std::endl;
a->printPretty();
std::cout << (e->remove(212)) << std::endl;
std::cout << (e->remove(145)) << std::endl;
std::cout << (c->remove(368)) << std::endl;
std::cout << (c->insert(319)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
*e=*e;
std::cout << (b->remove(68)) << std::endl;
e->printPretty();
std::cout << (a->insert(208)) << std::endl;
std::cout << (c->remove(425)) << std::endl;
std::cout << (b->remove(123)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
std::cout << (e->insert(11)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
c->printPretty();
std::cout << (d->remove(496)) << std::endl;
b->printPretty();
std::cout << (a->remove(260)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (e->remove(11)) << std::endl;
*e=*e;
std::cout << (d->insert(93)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
*c=*a;
std::cout << (a->remove(308)) << std::endl;
b->printPretty();
std::cout << (a->remove(319)) << std::endl;
std::cout << (a->insert(240)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
e->printPretty();
std::cout << (d->insert(488)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
std::cout << (d->remove(146)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
std::cout << (e->remove(301)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
*e=*e;
std::cout << (b->insert(488)) << std::endl;
d->printPretty();
std::cout << (a->insert(359)) << std::endl;
*e=*e;
std::cout << (e->insert(185)) << std::endl;
b->printPretty();
*c=*a;
*c=*c;
std::cout << (d->remove(469)) << std::endl;
std::cout << (d->insert(306)) << std::endl;
std::cout << (d->remove(93)) << std::endl;
std::cout << (e->insert(240)) << std::endl;
std::cout << (b->insert(58)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
std::cout << (c->insert(494)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
*c=*b;
std::cout << (c->insert(58)) << std::endl;
std::cout << (b->remove(488)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (c->remove(57)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
std::cout << (e->insert(85)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
c->printPretty();
std::cout << (d->insert(353)) << std::endl;
std::cout << (b->insert(275)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (b->remove(259)) << std::endl;
std::cout << (c->remove(124)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (c->insert(73)) << std::endl;
*b=*d;
std::cout << (d->remove(388)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (a->insert(275)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (c->remove(282)) << std::endl;
a->printPretty();
std::cout << (e->insert(85)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
std::cout << (d->remove(306)) << std::endl;
std::cout << (e->insert(206)) << std::endl;
std::cout << (a->insert(99)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
*e=*c;
std::cout << (c->remove(487)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
std::cout << (b->insert(306)) << std::endl;
std::cout << (b->insert(306)) << std::endl;
std::cout << (d->insert(368)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
*c=*a;
std::cout << (b->remove(136)) << std::endl;
std::cout << (b->remove(488)) << std::endl;
std::cout << (c->remove(336)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
b->printPretty();
c->printPretty();
*a=*d;
std::cout << (e->remove(488)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
*b=*a;
std::cout << (a->remove(353)) << std::endl;
std::cout << (b->remove(156)) << std::endl;
e->printPretty();
std::cout << (a->insert(368)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
b->printPretty();
std::cout << (d->remove(368)) << std::endl;
std::cout << (b->remove(245)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
*b=*e;
*a=*b;
std::cout << (a->insert(359)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
std::cout << (d->remove(353)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
*d=*d;
std::cout << (b->insert(359)) << std::endl;
*c=*b;
std::cout << (a->insert(470)) << std::endl;
*d=*c;
std::cout << (e->remove(389)) << std::endl;
*e=*a;
std::cout << (a->insert(179)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (b->insert(299)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
std::cout << (c->remove(208)) << std::endl;
std::cout << (c->remove(474)) << std::endl;
*e=*c;
*d=*c;
d->printPretty();
e->printPretty();
std::cout << (b->remove(345)) << std::endl;
a->printPretty();
*b=*c;
*e=*c;
std::cout << (b->insert(233)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (d->remove(70)) << std::endl;
std::cout << (d->insert(240)) << std::endl;
std::cout << (b->insert(240)) << std::endl;
*e=*b;
std::cout << (a->remove(466)) << std::endl;
*d=*e;
std::cout << (e->remove(472)) << std::endl;
c->printPretty();
std::cout << (e->remove(359)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (a->insert(470)) << std::endl;
std::cout << (b->insert(49)) << std::endl;
std::cout << (b->remove(49)) << std::endl;
std::cout << (b->insert(240)) << std::endl;
*e=*e;
std::cout << (a->remove(246)) << std::endl;
std::cout << (a->insert(340)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
std::cout << (d->remove(482)) << std::endl;
e->printPretty();
std::cout << (a->insert(431)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (b->remove(118)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (d->remove(371)) << std::endl;
std::cout << (e->insert(233)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->remove(359)) << std::endl;
std::cout << (b->remove(240)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
*b=*e;
std::cout << (a->insert(179)) << std::endl;
e->printPretty();
std::cout << (c->remove(48)) << std::endl;
std::cout << (b->insert(240)) << std::endl;
std::cout << (a->remove(179)) << std::endl;
*d=*c;
std::cout << (e->insert(240)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->remove(260)) << std::endl;
*a=*e;
return 0;
}
