#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
std::cout << (a->insert(11)) << std::endl;
std::cout << (a->remove(478)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(11)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (b->remove(458)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->remove(394)) << std::endl;
*a=*d;
*c=*c;
*d=*b;
a->printPretty();
*c=*a;
*b=*b;
*c=*e;
std::cout << (b->remove(52)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
std::cout << (e->insert(337)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->remove(434)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
a->printPretty();
std::cout << (b->insert(357)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
*c=*e;
std::cout << (c->insert(69)) << std::endl;
b->printPretty();
std::cout << (d->remove(361)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (d->remove(210)) << std::endl;
std::cout << (e->insert(354)) << std::endl;
std::cout << (e->remove(406)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
b->printPretty();
std::cout << (c->insert(379)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
b->printPretty();
std::cout << (b->insert(357)) << std::endl;
std::cout << (d->insert(232)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
d->printPretty();
std::cout << (d->insert(14)) << std::endl;
*b=*c;
std::cout << (e->remove(354)) << std::endl;
*c=*a;
std::cout << (e->remove(258)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
e->printPretty();
std::cout << (e->insert(69)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
std::cout << (d->insert(153)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->remove(69)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
std::cout << (b->insert(337)) << std::endl;
std::cout << (c->insert(304)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
*a=*d;
std::cout << (c->remove(91)) << std::endl;
*d=*d;
*b=*e;
d->printPretty();
std::cout << (c->remove(77)) << std::endl;
*a=*b;
*c=*d;
std::cout << (b->remove(23)) << std::endl;
d->printPretty();
std::cout << (a->insert(432)) << std::endl;
std::cout << (a->remove(247)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (a->remove(23)) << std::endl;
*e=*e;
e->printPretty();
a->printPretty();
std::cout << (a->remove(432)) << std::endl;
*a=*b;
c->printPretty();
a->printPretty();
std::cout << (d->insert(192)) << std::endl;
c->printPretty();
*d=*d;
std::cout << (c->remove(14)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
*b=*a;
std::cout << (e->insert(23)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
b->printPretty();
std::cout << (e->insert(122)) << std::endl;
std::cout << (e->remove(23)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
*d=*b;
*c=*d;
a->printPretty();
e->printPretty();
std::cout << (a->remove(30)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
*e=*a;
std::cout << (d->insert(208)) << std::endl;
std::cout << (e->remove(224)) << std::endl;
*e=*d;
std::cout << (d->remove(461)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
e->printPretty();
std::cout << (d->insert(208)) << std::endl;
*b=*d;
std::cout << (e->remove(199)) << std::endl;
a->printPretty();
*c=*a;
a->printPretty();
std::cout << (b->remove(144)) << std::endl;
std::cout << (e->remove(458)) << std::endl;
e->printPretty();
*c=*e;
e->printPretty();
std::cout << (e->remove(171)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (d->insert(208)) << std::endl;
*b=*b;
std::cout << (e->insert(208)) << std::endl;
std::cout << (c->remove(285)) << std::endl;
d->printPretty();
std::cout << (e->insert(364)) << std::endl;
std::cout << (e->insert(79)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
*e=*b;
std::cout << (d->insert(208)) << std::endl;
*a=*e;
std::cout << (b->remove(208)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
*e=*c;
e->printPretty();
std::cout << (e->insert(201)) << std::endl;
*d=*c;
std::cout << (e->insert(461)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
d->printPretty();
*a=*d;
a->printPretty();
std::cout << (d->remove(351)) << std::endl;
std::cout << (e->remove(208)) << std::endl;
*e=*c;
std::cout << (d->remove(461)) << std::endl;
std::cout << (a->remove(171)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
b->printPretty();
std::cout << (a->remove(454)) << std::endl;
std::cout << (a->insert(367)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (e->remove(17)) << std::endl;
std::cout << (b->insert(7)) << std::endl;
std::cout << (c->remove(171)) << std::endl;
d->printPretty();
std::cout << (a->remove(208)) << std::endl;
std::cout << (a->insert(367)) << std::endl;
std::cout << (e->insert(488)) << std::endl;
std::cout << (a->remove(367)) << std::endl;
std::cout << (e->remove(489)) << std::endl;
std::cout << (b->insert(373)) << std::endl;
*a=*b;
std::cout << (e->insert(350)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (b->insert(7)) << std::endl;
*a=*d;
std::cout << (e->insert(350)) << std::endl;
std::cout << (e->remove(463)) << std::endl;
std::cout << (a->remove(354)) << std::endl;
std::cout << (c->remove(102)) << std::endl;
std::cout << (d->insert(28)) << std::endl;
std::cout << (c->remove(439)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
std::cout << (b->insert(326)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
std::cout << (b->insert(373)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->insert(324)) << std::endl;
std::cout << (d->insert(180)) << std::endl;
std::cout << (e->remove(208)) << std::endl;
std::cout << (c->remove(324)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->remove(208)) << std::endl;
std::cout << (e->remove(118)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
std::cout << (a->insert(461)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
*d=*c;
std::cout << (e->insert(488)) << std::endl;
*b=*e;
std::cout << (b->remove(462)) << std::endl;
*a=*c;
std::cout << (e->remove(465)) << std::endl;
std::cout << (b->insert(350)) << std::endl;
std::cout << (c->remove(478)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (b->insert(81)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
b->printPretty();
*c=*c;
*a=*d;
std::cout << (a->insert(461)) << std::endl;
std::cout << (a->remove(191)) << std::endl;
*e=*b;
e->printPretty();
*c=*e;
std::cout << (e->insert(350)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
std::cout << (a->remove(389)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (b->insert(461)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
*c=*e;
std::cout << (e->insert(350)) << std::endl;
std::cout << (d->insert(461)) << std::endl;
std::cout << (d->insert(388)) << std::endl;
std::cout << (b->remove(350)) << std::endl;
*d=*c;
std::cout << (c->remove(472)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (d->insert(350)) << std::endl;
std::cout << (c->insert(54)) << std::endl;
std::cout << (b->remove(212)) << std::endl;
b->printPretty();
std::cout << (a->insert(132)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
a->printPretty();
std::cout << (a->insert(132)) << std::endl;
d->printPretty();
std::cout << (d->insert(302)) << std::endl;
std::cout << (c->remove(54)) << std::endl;
c->printPretty();
c->printPretty();
*e=*e;
d->printPretty();
e->printPretty();
*a=*d;
*e=*c;
d->printPretty();
std::cout << (a->remove(443)) << std::endl;
std::cout << (c->insert(495)) << std::endl;
std::cout << (a->remove(285)) << std::endl;
*c=*e;
std::cout << (e->remove(469)) << std::endl;
std::cout << (a->insert(268)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
std::cout << (a->insert(366)) << std::endl;
*b=*d;
c->printPretty();
std::cout << (a->remove(81)) << std::endl;
*a=*d;
a->printPretty();
std::cout << (a->insert(257)) << std::endl;
std::cout << (d->insert(416)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
e->printPretty();
*a=*e;
std::cout << (a->insert(488)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (b->remove(461)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
*b=*e;
*e=*c;
std::cout << (a->remove(302)) << std::endl;
*b=*a;
std::cout << (a->remove(303)) << std::endl;
std::cout << (a->remove(469)) << std::endl;
*b=*e;
std::cout << (c->remove(350)) << std::endl;
d->printPretty();
std::cout << (c->insert(469)) << std::endl;
std::cout << (d->remove(469)) << std::endl;
d->printPretty();
std::cout << (a->remove(488)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
std::cout << (d->remove(71)) << std::endl;
std::cout << (b->insert(488)) << std::endl;
std::cout << (b->insert(488)) << std::endl;
std::cout << (b->remove(461)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
b->printPretty();
a->printPretty();
a->printPretty();
std::cout << (a->insert(360)) << std::endl;
c->printPretty();
std::cout << (d->insert(96)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(488)) << std::endl;
std::cout << (e->insert(201)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (a->remove(329)) << std::endl;
std::cout << (c->insert(488)) << std::endl;
*b=*a;
std::cout << (d->insert(461)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
std::cout << (a->remove(472)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
std::cout << (c->remove(461)) << std::endl;
std::cout << (c->insert(292)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
std::cout << (c->remove(24)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (b->insert(472)) << std::endl;
std::cout << (c->remove(288)) << std::endl;
std::cout << (d->remove(487)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (d->insert(155)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
*e=*b;
std::cout << (e->remove(354)) << std::endl;
std::cout << (e->insert(227)) << std::endl;
d->printPretty();
std::cout << (e->insert(227)) << std::endl;
c->printPretty();
std::cout << (d->insert(288)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
std::cout << (a->insert(158)) << std::endl;
*a=*d;
std::cout << (b->remove(240)) << std::endl;
std::cout << (e->remove(58)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
*c=*b;
std::cout << (d->remove(469)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
std::cout << (a->remove(479)) << std::endl;
std::cout << (e->insert(360)) << std::endl;
*a=*c;
std::cout << (e->insert(366)) << std::endl;
std::cout << (e->remove(366)) << std::endl;
std::cout << (c->insert(206)) << std::endl;
std::cout << (d->insert(414)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
std::cout << (b->remove(298)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (c->remove(472)) << std::endl;
e->printPretty();
std::cout << (d->insert(435)) << std::endl;
std::cout << (b->insert(360)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
std::cout << (c->insert(363)) << std::endl;
std::cout << (c->remove(181)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
std::cout << (c->insert(81)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
std::cout << (d->remove(374)) << std::endl;
std::cout << (a->remove(108)) << std::endl;
std::cout << (e->remove(360)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (e->insert(97)) << std::endl;
std::cout << (c->remove(360)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
std::cout << (c->insert(206)) << std::endl;
*c=*b;
*a=*d;
c->printPretty();
d->printPretty();
std::cout << (c->remove(210)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
d->printPretty();
std::cout << (c->insert(335)) << std::endl;
*b=*b;
std::cout << (e->insert(227)) << std::endl;
std::cout << (a->insert(213)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
*a=*b;
std::cout << (e->remove(292)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
*c=*b;
std::cout << (d->insert(360)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
std::cout << (b->remove(486)) << std::endl;
std::cout << (c->insert(295)) << std::endl;
std::cout << (b->remove(19)) << std::endl;
std::cout << (b->remove(209)) << std::endl;
std::cout << (c->remove(27)) << std::endl;
c->printPretty();
std::cout << (b->remove(69)) << std::endl;
*c=*a;
std::cout << (a->insert(431)) << std::endl;
d->printPretty();
std::cout << (d->insert(438)) << std::endl;
*a=*c;
*a=*c;
std::cout << (e->insert(169)) << std::endl;
*b=*c;
std::cout << (d->insert(47)) << std::endl;
std::cout << (a->insert(163)) << std::endl;
*d=*a;
std::cout << (e->remove(97)) << std::endl;
std::cout << (d->insert(331)) << std::endl;
std::cout << (c->remove(431)) << std::endl;
std::cout << (b->remove(415)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->remove(431)) << std::endl;
std::cout << (c->remove(449)) << std::endl;
*c=*b;
std::cout << (d->remove(431)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (e->insert(146)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (e->insert(151)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
*a=*e;
e->printPretty();
e->printPretty();
b->printPretty();
std::cout << (a->remove(146)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (b->insert(247)) << std::endl;
b->printPretty();
e->printPretty();
*a=*d;
std::cout << (a->insert(163)) << std::endl;
std::cout << (e->insert(214)) << std::endl;
std::cout << (d->insert(80)) << std::endl;
std::cout << (c->insert(125)) << std::endl;
std::cout << (d->remove(443)) << std::endl;
c->printPretty();
std::cout << (e->remove(9)) << std::endl;
std::cout << (a->insert(163)) << std::endl;
std::cout << (d->remove(80)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
*a=*d;
std::cout << (c->insert(302)) << std::endl;
std::cout << (c->insert(125)) << std::endl;
std::cout << (d->remove(163)) << std::endl;
std::cout << (b->insert(215)) << std::endl;
std::cout << (d->insert(177)) << std::endl;
std::cout << (c->insert(371)) << std::endl;
std::cout << (e->insert(227)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (b->remove(247)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
a->printPretty();
*b=*e;
*e=*e;
std::cout << (e->remove(151)) << std::endl;
std::cout << (d->remove(280)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
*a=*e;
std::cout << (d->insert(153)) << std::endl;
*d=*a;
std::cout << (c->insert(214)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->insert(81)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
c->printPretty();
b->printPretty();
*e=*a;
a->printPretty();
c->printPretty();
std::cout << (b->insert(227)) << std::endl;
std::cout << (c->remove(371)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
std::cout << (a->remove(237)) << std::endl;
std::cout << (a->insert(328)) << std::endl;
*e=*c;
*c=*a;
std::cout << (c->remove(169)) << std::endl;
std::cout << (e->remove(214)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
a->printPretty();
std::cout << (c->insert(227)) << std::endl;
std::cout << (b->remove(135)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
std::cout << (d->insert(227)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
a->printPretty();
std::cout << (b->remove(18)) << std::endl;
std::cout << (a->remove(160)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (e->remove(125)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
*c=*e;
std::cout << (b->insert(214)) << std::endl;
std::cout << (e->insert(338)) << std::endl;
e->printPretty();
std::cout << (a->insert(169)) << std::endl;
d->printPretty();
std::cout << (b->insert(267)) << std::endl;
std::cout << (e->insert(7)) << std::endl;
*e=*d;
*b=*c;
std::cout << (e->insert(230)) << std::endl;
std::cout << (e->remove(214)) << std::endl;
a->printPretty();
std::cout << (d->remove(447)) << std::endl;
*d=*e;
std::cout << (a->remove(498)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
std::cout << (b->insert(447)) << std::endl;
std::cout << (d->insert(169)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (d->insert(146)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
e->printPretty();
std::cout << (b->insert(153)) << std::endl;
std::cout << (e->remove(305)) << std::endl;
std::cout << (d->insert(485)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
std::cout << (b->insert(421)) << std::endl;
std::cout << (e->insert(328)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (b->remove(153)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (a->remove(227)) << std::endl;
std::cout << (a->remove(169)) << std::endl;
std::cout << (c->insert(237)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
*a=*e;
std::cout << (b->insert(368)) << std::endl;
std::cout << (e->insert(227)) << std::endl;
d->printPretty();
a->printPretty();
*a=*c;
*e=*c;
std::cout << (c->remove(205)) << std::endl;
std::cout << (c->remove(98)) << std::endl;
std::cout << (a->remove(454)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
std::cout << (e->insert(205)) << std::endl;
*e=*c;
std::cout << (e->insert(58)) << std::endl;
std::cout << (e->remove(58)) << std::endl;
*c=*e;
std::cout << (d->remove(34)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
b->printPretty();
std::cout << (d->insert(169)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
std::cout << (d->insert(499)) << std::endl;
std::cout << (b->insert(59)) << std::endl;
std::cout << (a->remove(201)) << std::endl;
std::cout << (d->remove(311)) << std::endl;
*c=*e;
std::cout << (e->insert(443)) << std::endl;
*c=*d;
std::cout << (a->remove(161)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
std::cout << (d->remove(176)) << std::endl;
std::cout << (d->insert(131)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->remove(22)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->remove(472)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
std::cout << (a->remove(391)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
*b=*d;
std::cout << (d->insert(227)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
std::cout << (d->remove(277)) << std::endl;
*e=*a;
*a=*a;
std::cout << (a->insert(302)) << std::endl;
std::cout << (d->remove(31)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
*c=*c;
a->printPretty();
*c=*b;
std::cout << (d->insert(347)) << std::endl;
e->printPretty();
std::cout << (e->insert(33)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
e->printPretty();
std::cout << (b->insert(289)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (e->insert(172)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
e->printPretty();
std::cout << (b->remove(256)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
c->printPretty();
d->printPretty();
*a=*d;
std::cout << (c->remove(128)) << std::endl;
std::cout << (d->remove(193)) << std::endl;
std::cout << (a->insert(328)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (d->insert(131)) << std::endl;
*a=*a;
std::cout << (b->insert(122)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
std::cout << (b->insert(475)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
*d=*c;
std::cout << (e->remove(237)) << std::endl;
d->printPretty();
std::cout << (d->insert(199)) << std::endl;
std::cout << (e->insert(108)) << std::endl;
std::cout << (b->remove(289)) << std::endl;
b->printPretty();
std::cout << (e->remove(205)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (e->remove(230)) << std::endl;
b->printPretty();
*e=*e;
std::cout << (a->insert(489)) << std::endl;
std::cout << (a->insert(292)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
std::cout << (e->remove(436)) << std::endl;
a->printPretty();
*a=*a;
*d=*c;
std::cout << (d->remove(124)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (b->insert(472)) << std::endl;
std::cout << (a->remove(303)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
std::cout << (c->insert(282)) << std::endl;
b->printPretty();
*c=*b;
std::cout << (e->insert(20)) << std::endl;
c->printPretty();
std::cout << (d->remove(33)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
std::cout << (d->insert(237)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
std::cout << (a->remove(350)) << std::endl;
std::cout << (b->insert(230)) << std::endl;
d->printPretty();
e->printPretty();
a->printPretty();
*e=*e;
std::cout << (b->remove(475)) << std::endl;
std::cout << (b->remove(363)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
return 0;
}
