#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(6)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->remove(440)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
*a=*c;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*a=*d;
std::cout << (c->remove(342)) << std::endl;
a->printPretty();
c->printPretty();
b->printPretty();
b->printPretty();
std::cout << (d->remove(6)) << std::endl;
*a=*a;
*d=*e;
std::cout << (c->remove(6)) << std::endl;
*b=*d;
b->printPretty();
std::cout << (b->insert(96)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (a->insert(242)) << std::endl;
c->printPretty();
a->printPretty();
*d=*a;
e->printPretty();
std::cout << (d->remove(242)) << std::endl;
b->printPretty();
std::cout << (a->remove(48)) << std::endl;
*b=*a;
*c=*d;
std::cout << (b->remove(215)) << std::endl;
std::cout << (c->insert(6)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
c->printPretty();
*d=*e;
std::cout << (c->insert(6)) << std::endl;
std::cout << (e->remove(410)) << std::endl;
*d=*b;
std::cout << (c->insert(6)) << std::endl;
a->printPretty();
std::cout << (c->remove(119)) << std::endl;
*c=*a;
*d=*b;
std::cout << (b->remove(376)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
*a=*a;
b->printPretty();
*a=*d;
std::cout << (a->remove(242)) << std::endl;
*a=*c;
std::cout << (a->remove(6)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
*c=*c;
std::cout << (d->remove(455)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
std::cout << (b->remove(6)) << std::endl;
std::cout << (b->remove(213)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (d->insert(328)) << std::endl;
*d=*c;
std::cout << (c->insert(180)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
std::cout << (c->remove(75)) << std::endl;
*e=*b;
std::cout << (e->insert(365)) << std::endl;
*d=*d;
std::cout << (e->insert(314)) << std::endl;
e->printPretty();
std::cout << (c->insert(150)) << std::endl;
*d=*d;
b->printPretty();
b->printPretty();
std::cout << (c->insert(6)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (d->insert(180)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
std::cout << (e->insert(365)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
*b=*a;
std::cout << (a->insert(120)) << std::endl;
std::cout << (e->remove(26)) << std::endl;
std::cout << (e->remove(314)) << std::endl;
d->printPretty();
std::cout << (d->insert(391)) << std::endl;
d->printPretty();
std::cout << (b->remove(313)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (b->insert(473)) << std::endl;
std::cout << (c->insert(73)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (a->remove(42)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
b->printPretty();
*c=*b;
c->printPretty();
std::cout << (c->insert(58)) << std::endl;
std::cout << (b->remove(347)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
*e=*d;
std::cout << (a->insert(193)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
*c=*d;
*d=*c;
std::cout << (b->remove(473)) << std::endl;
std::cout << (e->remove(6)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
*a=*c;
std::cout << (a->remove(284)) << std::endl;
*a=*a;
*c=*c;
std::cout << (e->insert(72)) << std::endl;
*c=*c;
std::cout << (d->insert(391)) << std::endl;
std::cout << (d->remove(180)) << std::endl;
std::cout << (a->remove(391)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (e->remove(391)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (b->remove(31)) << std::endl;
*b=*e;
std::cout << (b->remove(449)) << std::endl;
std::cout << (d->remove(323)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
std::cout << (e->remove(403)) << std::endl;
std::cout << (c->insert(391)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
std::cout << (b->insert(180)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
*a=*b;
std::cout << (c->remove(223)) << std::endl;
*e=*a;
a->printPretty();
d->printPretty();
std::cout << (a->insert(359)) << std::endl;
a->printPretty();
std::cout << (d->insert(291)) << std::endl;
*e=*e;
std::cout << (e->insert(180)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
std::cout << (d->insert(355)) << std::endl;
std::cout << (b->remove(297)) << std::endl;
std::cout << (e->insert(180)) << std::endl;
*a=*e;
*d=*d;
std::cout << (c->remove(73)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (a->insert(274)) << std::endl;
std::cout << (d->insert(74)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
*d=*c;
std::cout << (c->remove(391)) << std::endl;
std::cout << (b->insert(238)) << std::endl;
std::cout << (a->remove(274)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (e->insert(180)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (b->insert(473)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
e->printPretty();
std::cout << (b->remove(278)) << std::endl;
c->printPretty();
std::cout << (e->insert(180)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
c->printPretty();
std::cout << (a->remove(180)) << std::endl;
std::cout << (a->insert(281)) << std::endl;
d->printPretty();
*b=*c;
*a=*e;
std::cout << (e->insert(84)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (e->insert(321)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
c->printPretty();
std::cout << (c->insert(6)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
std::cout << (d->insert(239)) << std::endl;
std::cout << (d->insert(12)) << std::endl;
e->printPretty();
std::cout << (c->remove(321)) << std::endl;
std::cout << (b->remove(321)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
*c=*c;
std::cout << (e->insert(255)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (e->insert(321)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (d->remove(12)) << std::endl;
d->printPretty();
std::cout << (c->remove(6)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (e->remove(219)) << std::endl;
*c=*e;
std::cout << (c->insert(176)) << std::endl;
a->printPretty();
a->printPretty();
*c=*b;
std::cout << (d->insert(6)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
std::cout << (b->insert(224)) << std::endl;
*d=*a;
std::cout << (a->insert(278)) << std::endl;
*b=*d;
std::cout << (d->insert(278)) << std::endl;
d->printPretty();
std::cout << (a->insert(180)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (c->remove(212)) << std::endl;
*b=*b;
std::cout << (c->remove(6)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
std::cout << (e->remove(458)) << std::endl;
*a=*b;
std::cout << (e->remove(391)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->remove(180)) << std::endl;
a->printPretty();
std::cout << (b->remove(11)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (e->insert(380)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
*b=*b;
a->printPretty();
std::cout << (a->remove(482)) << std::endl;
a->printPretty();
std::cout << (b->remove(180)) << std::endl;
std::cout << (e->remove(12)) << std::endl;
std::cout << (a->insert(180)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
std::cout << (a->insert(198)) << std::endl;
*a=*d;
std::cout << (b->insert(84)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (e->remove(380)) << std::endl;
*d=*b;
std::cout << (b->remove(84)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
c->printPretty();
std::cout << (c->insert(485)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
std::cout << (d->insert(67)) << std::endl;
std::cout << (a->remove(112)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
std::cout << (b->remove(372)) << std::endl;
std::cout << (e->insert(6)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
a->printPretty();
std::cout << (d->insert(278)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (b->remove(278)) << std::endl;
*b=*c;
a->printPretty();
std::cout << (b->remove(180)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->insert(7)) << std::endl;
*a=*e;
std::cout << (e->insert(278)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (a->remove(256)) << std::endl;
std::cout << (b->insert(261)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(180)) << std::endl;
std::cout << (d->remove(101)) << std::endl;
*c=*c;
std::cout << (c->insert(278)) << std::endl;
std::cout << (b->remove(278)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (e->insert(239)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
a->printPretty();
std::cout << (b->remove(97)) << std::endl;
std::cout << (e->insert(239)) << std::endl;
e->printPretty();
std::cout << (c->remove(221)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
d->printPretty();
c->printPretty();
c->printPretty();
std::cout << (e->remove(239)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
c->printPretty();
std::cout << (c->insert(308)) << std::endl;
*c=*a;
*e=*c;
std::cout << (a->remove(234)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (d->remove(84)) << std::endl;
std::cout << (e->insert(482)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (d->insert(67)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
*a=*b;
std::cout << (d->insert(67)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
*a=*c;
std::cout << (b->insert(7)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
std::cout << (d->insert(174)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (d->insert(176)) << std::endl;
std::cout << (d->remove(49)) << std::endl;
std::cout << (c->remove(47)) << std::endl;
d->printPretty();
std::cout << (d->insert(278)) << std::endl;
std::cout << (b->remove(420)) << std::endl;
c->printPretty();
std::cout << (d->remove(67)) << std::endl;
std::cout << (d->remove(160)) << std::endl;
b->printPretty();
*c=*b;
*b=*a;
std::cout << (b->remove(213)) << std::endl;
std::cout << (d->remove(174)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
std::cout << (d->remove(176)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (c->remove(357)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
std::cout << (b->insert(133)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (c->remove(485)) << std::endl;
std::cout << (b->remove(196)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
*c=*e;
*c=*a;
std::cout << (b->remove(102)) << std::endl;
e->printPretty();
std::cout << (a->remove(399)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
std::cout << (b->insert(164)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (b->remove(133)) << std::endl;
std::cout << (d->insert(7)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
c->printPretty();
std::cout << (a->insert(205)) << std::endl;
*a=*d;
std::cout << (a->insert(7)) << std::endl;
std::cout << (e->insert(187)) << std::endl;
b->printPretty();
d->printPretty();
*c=*e;
std::cout << (c->remove(264)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
std::cout << (e->remove(412)) << std::endl;
std::cout << (e->insert(456)) << std::endl;
*b=*d;
std::cout << (a->insert(494)) << std::endl;
std::cout << (e->remove(187)) << std::endl;
std::cout << (e->remove(78)) << std::endl;
std::cout << (a->remove(485)) << std::endl;
b->printPretty();
std::cout << (b->remove(485)) << std::endl;
e->printPretty();
std::cout << (d->remove(221)) << std::endl;
d->printPretty();
a->printPretty();
*d=*e;
std::cout << (e->remove(166)) << std::endl;
std::cout << (a->insert(461)) << std::endl;
std::cout << (d->insert(45)) << std::endl;
*e=*b;
std::cout << (e->insert(221)) << std::endl;
std::cout << (a->remove(226)) << std::endl;
*c=*e;
std::cout << (a->insert(197)) << std::endl;
*e=*e;
std::cout << (a->remove(63)) << std::endl;
std::cout << (c->insert(55)) << std::endl;
std::cout << (c->remove(7)) << std::endl;
*b=*c;
std::cout << (c->remove(432)) << std::endl;
std::cout << (c->insert(55)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
std::cout << (c->remove(55)) << std::endl;
std::cout << (b->insert(55)) << std::endl;
std::cout << (b->insert(417)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (d->remove(21)) << std::endl;
*e=*a;
std::cout << (b->insert(350)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
*b=*e;
std::cout << (a->insert(58)) << std::endl;
std::cout << (e->insert(98)) << std::endl;
std::cout << (d->insert(456)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (c->insert(161)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (d->remove(45)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
std::cout << (e->insert(197)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
std::cout << (e->insert(98)) << std::endl;
std::cout << (d->remove(456)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
b->printPretty();
std::cout << (c->remove(161)) << std::endl;
a->printPretty();
std::cout << (c->insert(413)) << std::endl;
std::cout << (e->insert(197)) << std::endl;
*e=*e;
std::cout << (e->insert(494)) << std::endl;
std::cout << (a->remove(221)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
std::cout << (e->insert(87)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (b->remove(297)) << std::endl;
std::cout << (b->remove(363)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
std::cout << (e->remove(494)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
*e=*a;
std::cout << (b->insert(221)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->remove(124)) << std::endl;
e->printPretty();
std::cout << (d->remove(107)) << std::endl;
*e=*d;
std::cout << (b->remove(7)) << std::endl;
*d=*a;
std::cout << (c->remove(413)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->remove(221)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (c->insert(221)) << std::endl;
*e=*d;
d->printPretty();
b->printPretty();
std::cout << (b->insert(197)) << std::endl;
std::cout << (d->insert(500)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (a->insert(419)) << std::endl;
*c=*a;
std::cout << (c->insert(234)) << std::endl;
*b=*a;
std::cout << (a->remove(467)) << std::endl;
std::cout << (a->insert(419)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
std::cout << (b->remove(486)) << std::endl;
*b=*b;
*d=*b;
std::cout << (c->insert(315)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
*d=*a;
std::cout << (d->insert(192)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (c->insert(272)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
std::cout << (b->insert(464)) << std::endl;
c->printPretty();
std::cout << (b->insert(206)) << std::endl;
*d=*a;
std::cout << (a->remove(419)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (d->insert(419)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (c->remove(234)) << std::endl;
*b=*d;
a->printPretty();
*e=*d;
std::cout << (b->insert(96)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (c->remove(486)) << std::endl;
b->printPretty();
std::cout << (b->remove(421)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->insert(234)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
std::cout << (c->insert(419)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (b->remove(486)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
std::cout << (a->insert(340)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
e->printPretty();
*a=*b;
b->printPretty();
std::cout << (c->insert(419)) << std::endl;
a->printPretty();
*b=*a;
std::cout << (d->remove(234)) << std::endl;
std::cout << (b->remove(293)) << std::endl;
std::cout << (a->remove(419)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
std::cout << (c->insert(419)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
*a=*d;
*a=*e;
std::cout << (e->remove(419)) << std::endl;
e->printPretty();
std::cout << (d->remove(378)) << std::endl;
a->printPretty();
*c=*e;
std::cout << (c->insert(274)) << std::endl;
*c=*c;
d->printPretty();
*b=*d;
std::cout << (e->insert(302)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
*b=*c;
std::cout << (a->insert(419)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
*a=*d;
std::cout << (e->remove(41)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (c->remove(4)) << std::endl;
std::cout << (c->remove(234)) << std::endl;
std::cout << (b->insert(486)) << std::endl;
std::cout << (c->remove(274)) << std::endl;
*c=*b;
std::cout << (b->insert(486)) << std::endl;
std::cout << (a->insert(271)) << std::endl;
std::cout << (b->insert(439)) << std::endl;
std::cout << (c->remove(236)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
a->printPretty();
*d=*d;
std::cout << (a->remove(55)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (b->remove(274)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (d->remove(165)) << std::endl;
std::cout << (a->remove(232)) << std::endl;
std::cout << (b->insert(175)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
std::cout << (d->remove(222)) << std::endl;
std::cout << (b->remove(105)) << std::endl;
std::cout << (b->remove(298)) << std::endl;
std::cout << (a->remove(12)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
std::cout << (b->insert(166)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (e->remove(431)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
b->printPretty();
std::cout << (a->remove(418)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
e->printPretty();
std::cout << (c->insert(486)) << std::endl;
*d=*c;
std::cout << (a->remove(271)) << std::endl;
a->printPretty();
std::cout << (e->insert(486)) << std::endl;
c->printPretty();
std::cout << (a->remove(17)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
c->printPretty();
*b=*b;
a->printPretty();
*b=*a;
c->printPretty();
std::cout << (e->insert(166)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (c->insert(486)) << std::endl;
e->printPretty();
std::cout << (e->insert(486)) << std::endl;
b->printPretty();
std::cout << (e->remove(424)) << std::endl;
*e=*e;
std::cout << (b->insert(341)) << std::endl;
c->printPretty();
std::cout << (d->insert(355)) << std::endl;
a->printPretty();
std::cout << (e->insert(139)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (c->remove(111)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
d->printPretty();
std::cout << (e->insert(255)) << std::endl;
*a=*e;
*d=*d;
std::cout << (c->insert(9)) << std::endl;
*d=*c;
std::cout << (a->insert(255)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
b->printPretty();
std::cout << (b->insert(308)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
std::cout << (b->insert(179)) << std::endl;
std::cout << (d->remove(166)) << std::endl;
b->printPretty();
*c=*d;
d->printPretty();
std::cout << (a->insert(6)) << std::endl;
std::cout << (c->insert(347)) << std::endl;
*d=*b;
a->printPretty();
*a=*d;
c->printPretty();
std::cout << (c->insert(207)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
c->printPretty();
std::cout << (d->insert(424)) << std::endl;
c->printPretty();
std::cout << (a->remove(398)) << std::endl;
std::cout << (e->remove(139)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
c->printPretty();
std::cout << (a->insert(179)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (a->remove(186)) << std::endl;
std::cout << (e->remove(355)) << std::endl;
std::cout << (c->insert(414)) << std::endl;
d->printPretty();
std::cout << (e->remove(166)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
*c=*e;
std::cout << (b->insert(305)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
std::cout << (a->insert(371)) << std::endl;
a->printPretty();
a->printPretty();
*b=*d;
std::cout << (c->remove(234)) << std::endl;
std::cout << (e->remove(486)) << std::endl;
e->printPretty();
std::cout << (e->insert(255)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
return 0;
}
