#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(371)) << std::endl;
std::cout << (a->remove(371)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(494)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (d->insert(199)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (e->remove(132)) << std::endl;
std::cout << (a->remove(110)) << std::endl;
std::cout << (b->remove(203)) << std::endl;
std::cout << (e->insert(376)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
c->printPretty();
std::cout << (d->insert(183)) << std::endl;
*e=*c;
*a=*a;
d->printPretty();
std::cout << (d->insert(183)) << std::endl;
d->printPretty();
std::cout << (a->remove(23)) << std::endl;
*b=*a;
std::cout << (a->remove(31)) << std::endl;
std::cout << (a->remove(190)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
std::cout << (b->insert(494)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (a->remove(494)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
a->printPretty();
std::cout << (d->insert(199)) << std::endl;
std::cout << (b->insert(45)) << std::endl;
a->printPretty();
std::cout << (c->remove(83)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
std::cout << (e->insert(379)) << std::endl;
std::cout << (b->remove(462)) << std::endl;
*e=*e;
std::cout << (b->insert(20)) << std::endl;
c->printPretty();
std::cout << (b->remove(20)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (d->insert(199)) << std::endl;
std::cout << (d->remove(199)) << std::endl;
*c=*b;
*c=*d;
std::cout << (a->insert(99)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
std::cout << (b->insert(181)) << std::endl;
*e=*b;
std::cout << (c->insert(215)) << std::endl;
*e=*c;
std::cout << (a->insert(66)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
std::cout << (a->insert(99)) << std::endl;
*b=*a;
std::cout << (c->remove(370)) << std::endl;
*e=*b;
std::cout << (a->insert(99)) << std::endl;
std::cout << (c->remove(215)) << std::endl;
std::cout << (d->remove(152)) << std::endl;
*d=*d;
std::cout << (d->remove(35)) << std::endl;
std::cout << (b->insert(99)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
std::cout << (b->remove(99)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
std::cout << (a->remove(99)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (d->insert(424)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->remove(219)) << std::endl;
*d=*c;
c->printPretty();
a->printPretty();
a->printPretty();
std::cout << (d->remove(80)) << std::endl;
a->printPretty();
std::cout << (e->remove(320)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
std::cout << (a->remove(251)) << std::endl;
std::cout << (d->insert(321)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
e->printPretty();
std::cout << (a->insert(480)) << std::endl;
a->printPretty();
*c=*a;
*e=*b;
std::cout << (a->remove(464)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
b->printPretty();
std::cout << (e->remove(337)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (a->insert(480)) << std::endl;
b->printPretty();
std::cout << (e->remove(69)) << std::endl;
*a=*c;
std::cout << (c->remove(480)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
std::cout << (a->remove(342)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
std::cout << (a->insert(242)) << std::endl;
*b=*d;
std::cout << (d->insert(315)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (a->remove(242)) << std::endl;
*d=*c;
*c=*a;
*a=*b;
std::cout << (d->insert(420)) << std::endl;
*c=*e;
*c=*d;
std::cout << (c->insert(290)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
std::cout << (b->insert(491)) << std::endl;
e->printPretty();
std::cout << (b->remove(133)) << std::endl;
e->printPretty();
std::cout << (e->remove(67)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (a->insert(253)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
std::cout << (a->remove(257)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
std::cout << (e->remove(127)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (a->remove(268)) << std::endl;
std::cout << (b->insert(389)) << std::endl;
*c=*b;
*e=*e;
std::cout << (a->insert(99)) << std::endl;
std::cout << (a->insert(445)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
*b=*d;
*c=*b;
std::cout << (a->insert(445)) << std::endl;
*b=*e;
*d=*c;
d->printPretty();
*e=*b;
*a=*e;
std::cout << (d->insert(377)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->remove(75)) << std::endl;
std::cout << (d->insert(330)) << std::endl;
e->printPretty();
d->printPretty();
d->printPretty();
std::cout << (a->remove(458)) << std::endl;
std::cout << (b->insert(481)) << std::endl;
std::cout << (d->insert(331)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
*b=*b;
std::cout << (c->remove(107)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
c->printPretty();
std::cout << (d->remove(330)) << std::endl;
*d=*c;
*b=*b;
std::cout << (b->remove(345)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (e->remove(410)) << std::endl;
d->printPretty();
b->printPretty();
*b=*c;
d->printPretty();
std::cout << (a->insert(202)) << std::endl;
std::cout << (a->remove(252)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
*d=*b;
*e=*c;
std::cout << (a->remove(104)) << std::endl;
*d=*c;
std::cout << (a->remove(200)) << std::endl;
e->printPretty();
d->printPretty();
*c=*c;
*d=*e;
e->printPretty();
*d=*b;
std::cout << (b->insert(450)) << std::endl;
std::cout << (c->remove(146)) << std::endl;
*d=*b;
*e=*a;
std::cout << (a->insert(202)) << std::endl;
std::cout << (a->remove(335)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
std::cout << (b->insert(450)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (e->insert(202)) << std::endl;
*a=*b;
*b=*c;
*c=*e;
*a=*a;
std::cout << (c->remove(281)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
std::cout << (d->insert(450)) << std::endl;
*d=*b;
std::cout << (e->insert(202)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (b->insert(352)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
std::cout << (e->insert(202)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
*a=*a;
std::cout << (b->remove(111)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
*e=*d;
std::cout << (a->insert(450)) << std::endl;
std::cout << (b->insert(352)) << std::endl;
*b=*b;
*c=*e;
d->printPretty();
std::cout << (d->remove(376)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
c->printPretty();
std::cout << (a->remove(35)) << std::endl;
*b=*e;
std::cout << (a->insert(54)) << std::endl;
a->printPretty();
std::cout << (a->insert(54)) << std::endl;
std::cout << (c->remove(437)) << std::endl;
*a=*a;
c->printPretty();
std::cout << (a->insert(137)) << std::endl;
*a=*a;
*c=*a;
std::cout << (a->remove(125)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (a->insert(54)) << std::endl;
*c=*b;
*e=*c;
*d=*e;
std::cout << (c->remove(267)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
a->printPretty();
*e=*a;
*e=*d;
std::cout << (a->remove(222)) << std::endl;
*a=*d;
std::cout << (e->remove(256)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
e->printPretty();
std::cout << (e->remove(40)) << std::endl;
std::cout << (e->insert(27)) << std::endl;
std::cout << (e->insert(27)) << std::endl;
*e=*c;
std::cout << (b->remove(299)) << std::endl;
std::cout << (e->remove(424)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
e->printPretty();
*d=*e;
std::cout << (d->insert(332)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
std::cout << (c->remove(133)) << std::endl;
std::cout << (b->remove(492)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
a->printPretty();
std::cout << (c->remove(145)) << std::endl;
std::cout << (e->remove(254)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (e->remove(298)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
b->printPretty();
*a=*a;
std::cout << (a->insert(19)) << std::endl;
std::cout << (d->insert(366)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
std::cout << (a->remove(19)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (e->insert(357)) << std::endl;
std::cout << (e->insert(478)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
a->printPretty();
*c=*b;
std::cout << (c->insert(104)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->remove(478)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
*e=*e;
*a=*d;
*a=*c;
std::cout << (b->remove(405)) << std::endl;
std::cout << (d->remove(366)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (a->insert(104)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
std::cout << (c->insert(366)) << std::endl;
std::cout << (c->insert(406)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
std::cout << (a->insert(94)) << std::endl;
d->printPretty();
b->printPretty();
*b=*a;
c->printPretty();
std::cout << (c->insert(104)) << std::endl;
*e=*d;
*c=*d;
*e=*b;
std::cout << (e->insert(459)) << std::endl;
std::cout << (b->remove(332)) << std::endl;
*a=*a;
std::cout << (a->insert(94)) << std::endl;
std::cout << (b->insert(94)) << std::endl;
std::cout << (d->remove(27)) << std::endl;
*d=*c;
std::cout << (e->remove(481)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (d->insert(310)) << std::endl;
c->printPretty();
std::cout << (a->remove(8)) << std::endl;
d->printPretty();
std::cout << (d->insert(310)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->insert(201)) << std::endl;
*a=*a;
std::cout << (d->remove(310)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (d->remove(463)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
*d=*b;
std::cout << (a->insert(104)) << std::endl;
*e=*c;
std::cout << (e->remove(346)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (e->insert(390)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
std::cout << (c->insert(84)) << std::endl;
d->printPretty();
std::cout << (c->remove(133)) << std::endl;
std::cout << (b->remove(377)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(205)) << std::endl;
d->printPretty();
a->printPretty();
*b=*d;
std::cout << (e->insert(300)) << std::endl;
d->printPretty();
a->printPretty();
b->printPretty();
e->printPretty();
std::cout << (e->insert(22)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
b->printPretty();
std::cout << (b->remove(348)) << std::endl;
std::cout << (c->insert(46)) << std::endl;
std::cout << (b->insert(94)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
c->printPretty();
std::cout << (a->remove(103)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
*d=*d;
std::cout << (b->insert(94)) << std::endl;
std::cout << (b->remove(5)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
std::cout << (c->insert(203)) << std::endl;
std::cout << (c->insert(84)) << std::endl;
d->printPretty();
std::cout << (d->insert(205)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
e->printPretty();
std::cout << (b->remove(98)) << std::endl;
*d=*e;
std::cout << (a->insert(116)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (a->remove(116)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
std::cout << (d->remove(203)) << std::endl;
std::cout << (d->remove(159)) << std::endl;
*c=*e;
d->printPretty();
*b=*b;
std::cout << (a->insert(463)) << std::endl;
std::cout << (e->insert(421)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
std::cout << (d->remove(84)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
*d=*e;
std::cout << (e->remove(320)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
std::cout << (e->remove(300)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
*b=*d;
std::cout << (b->remove(471)) << std::endl;
b->printPretty();
std::cout << (a->insert(403)) << std::endl;
*a=*b;
std::cout << (e->insert(421)) << std::endl;
std::cout << (e->insert(471)) << std::endl;
std::cout << (a->insert(421)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
d->printPretty();
std::cout << (e->insert(223)) << std::endl;
e->printPretty();
std::cout << (a->remove(426)) << std::endl;
std::cout << (e->remove(421)) << std::endl;
std::cout << (c->insert(60)) << std::endl;
std::cout << (a->remove(304)) << std::endl;
c->printPretty();
d->printPretty();
d->printPretty();
b->printPretty();
std::cout << (e->remove(223)) << std::endl;
std::cout << (c->remove(60)) << std::endl;
e->printPretty();
std::cout << (e->remove(33)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
std::cout << (b->remove(376)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
*d=*d;
a->printPretty();
*d=*d;
std::cout << (b->remove(486)) << std::endl;
b->printPretty();
std::cout << (b->remove(320)) << std::endl;
*e=*d;
std::cout << (d->remove(320)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
*e=*a;
std::cout << (e->insert(296)) << std::endl;
*e=*c;
std::cout << (c->remove(379)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (d->insert(130)) << std::endl;
*d=*d;
std::cout << (c->insert(353)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->insert(304)) << std::endl;
std::cout << (c->remove(295)) << std::endl;
d->printPretty();
*b=*e;
std::cout << (a->remove(391)) << std::endl;
std::cout << (b->remove(106)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
*e=*e;
std::cout << (a->remove(52)) << std::endl;
std::cout << (a->remove(320)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
std::cout << (a->insert(421)) << std::endl;
e->printPretty();
std::cout << (e->remove(280)) << std::endl;
e->printPretty();
std::cout << (a->insert(300)) << std::endl;
c->printPretty();
std::cout << (c->remove(353)) << std::endl;
std::cout << (b->insert(187)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (b->insert(161)) << std::endl;
*d=*e;
*b=*c;
std::cout << (b->remove(152)) << std::endl;
*a=*e;
b->printPretty();
std::cout << (b->insert(214)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
d->printPretty();
std::cout << (c->insert(176)) << std::endl;
*e=*d;
std::cout << (c->remove(169)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
*d=*a;
std::cout << (c->remove(454)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (c->insert(176)) << std::endl;
std::cout << (d->remove(64)) << std::endl;
std::cout << (a->remove(343)) << std::endl;
b->printPretty();
std::cout << (a->remove(367)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
std::cout << (b->remove(132)) << std::endl;
std::cout << (b->insert(182)) << std::endl;
e->printPretty();
std::cout << (d->insert(161)) << std::endl;
*e=*d;
*d=*a;
std::cout << (a->insert(173)) << std::endl;
std::cout << (a->remove(173)) << std::endl;
std::cout << (e->insert(161)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
std::cout << (c->insert(348)) << std::endl;
std::cout << (e->remove(364)) << std::endl;
b->printPretty();
std::cout << (e->insert(382)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
b->printPretty();
std::cout << (d->insert(334)) << std::endl;
std::cout << (c->remove(36)) << std::endl;
*d=*a;
std::cout << (e->insert(439)) << std::endl;
std::cout << (b->insert(214)) << std::endl;
*b=*c;
a->printPretty();
d->printPretty();
std::cout << (c->insert(348)) << std::endl;
*c=*a;
std::cout << (b->remove(348)) << std::endl;
*c=*a;
std::cout << (c->insert(456)) << std::endl;
e->printPretty();
std::cout << (c->insert(332)) << std::endl;
std::cout << (c->remove(173)) << std::endl;
b->printPretty();
std::cout << (b->remove(159)) << std::endl;
*b=*d;
std::cout << (c->remove(497)) << std::endl;
std::cout << (a->insert(75)) << std::endl;
std::cout << (e->remove(398)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
*e=*c;
std::cout << (b->insert(177)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
c->printPretty();
*b=*d;
std::cout << (d->insert(137)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (a->remove(56)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
*d=*e;
std::cout << (a->insert(280)) << std::endl;
d->printPretty();
std::cout << (b->insert(340)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (d->insert(456)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
*c=*b;
std::cout << (e->remove(456)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
*d=*a;
*a=*e;
*d=*d;
std::cout << (c->remove(74)) << std::endl;
std::cout << (c->remove(340)) << std::endl;
*c=*b;
std::cout << (c->remove(340)) << std::endl;
std::cout << (b->insert(165)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (a->remove(57)) << std::endl;
*c=*e;
std::cout << (b->remove(110)) << std::endl;
std::cout << (b->insert(287)) << std::endl;
std::cout << (a->insert(417)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
*c=*b;
std::cout << (c->insert(31)) << std::endl;
*a=*b;
*e=*c;
std::cout << (b->remove(306)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
std::cout << (a->remove(366)) << std::endl;
std::cout << (b->remove(349)) << std::endl;
std::cout << (a->remove(165)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (b->insert(340)) << std::endl;
std::cout << (a->remove(340)) << std::endl;
b->printPretty();
*a=*d;
c->printPretty();
std::cout << (e->remove(203)) << std::endl;
*d=*a;
std::cout << (e->remove(7)) << std::endl;
std::cout << (b->remove(165)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
std::cout << (b->remove(287)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
*c=*a;
std::cout << (d->remove(75)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (a->remove(123)) << std::endl;
std::cout << (d->insert(31)) << std::endl;
std::cout << (e->remove(165)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (d->remove(171)) << std::endl;
a->printPretty();
std::cout << (a->insert(1)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
*a=*e;
*d=*b;
std::cout << (d->insert(1)) << std::endl;
b->printPretty();
*d=*d;
std::cout << (c->remove(483)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
*d=*c;
*c=*b;
std::cout << (e->insert(103)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
std::cout << (c->remove(131)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
return 0;
}
