#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(455)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
*a=*a;
std::cout << (a->insert(305)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->insert(376)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->insert(360)) << std::endl;
*d=*d;
*b=*d;
*b=*a;
std::cout << (c->remove(429)) << std::endl;
*b=*a;
std::cout << (b->insert(376)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->remove(50)) << std::endl;
std::cout << (d->insert(151)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->remove(494)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
*a=*d;
std::cout << (c->remove(152)) << std::endl;
std::cout << (d->insert(38)) << std::endl;
std::cout << (a->remove(432)) << std::endl;
std::cout << (d->insert(151)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
*c=*c;
*e=*e;
std::cout << (e->insert(340)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
std::cout << (b->remove(432)) << std::endl;
std::cout << (b->remove(305)) << std::endl;
std::cout << (d->insert(151)) << std::endl;
*d=*c;
*e=*e;
std::cout << (a->insert(382)) << std::endl;
b->printPretty();
std::cout << (a->insert(382)) << std::endl;
std::cout << (d->insert(35)) << std::endl;
*a=*e;
std::cout << (e->insert(250)) << std::endl;
std::cout << (c->remove(126)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
*a=*d;
std::cout << (d->remove(35)) << std::endl;
std::cout << (c->remove(230)) << std::endl;
std::cout << (b->insert(376)) << std::endl;
std::cout << (e->insert(250)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (a->remove(35)) << std::endl;
*e=*d;
std::cout << (b->remove(376)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
a->printPretty();
std::cout << (b->remove(278)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
*b=*d;
std::cout << (b->remove(488)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
std::cout << (c->insert(210)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->insert(249)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
*d=*c;
std::cout << (d->remove(249)) << std::endl;
*c=*e;
*c=*a;
*d=*c;
std::cout << (b->insert(205)) << std::endl;
*d=*a;
std::cout << (c->insert(475)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
std::cout << (e->remove(496)) << std::endl;
std::cout << (c->remove(242)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (e->remove(295)) << std::endl;
*c=*b;
*b=*c;
*b=*b;
std::cout << (a->insert(461)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
*e=*b;
std::cout << (a->remove(461)) << std::endl;
d->printPretty();
std::cout << (b->insert(384)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (d->insert(321)) << std::endl;
std::cout << (c->remove(205)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (a->insert(187)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
b->printPretty();
std::cout << (b->remove(384)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (d->insert(156)) << std::endl;
*b=*c;
*b=*d;
std::cout << (a->insert(187)) << std::endl;
a->printPretty();
std::cout << (d->remove(321)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (b->remove(156)) << std::endl;
std::cout << (e->insert(205)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
*b=*b;
std::cout << (d->remove(281)) << std::endl;
*d=*a;
std::cout << (d->insert(488)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
e->printPretty();
std::cout << (e->remove(205)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (a->remove(292)) << std::endl;
std::cout << (b->remove(478)) << std::endl;
std::cout << (e->remove(446)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->remove(404)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (e->remove(74)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
d->printPretty();
std::cout << (a->remove(76)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
e->printPretty();
std::cout << (c->remove(43)) << std::endl;
*c=*d;
std::cout << (d->remove(19)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
*c=*a;
a->printPretty();
c->printPretty();
std::cout << (a->insert(126)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (d->insert(193)) << std::endl;
*b=*b;
*b=*b;
std::cout << (a->insert(416)) << std::endl;
std::cout << (d->insert(488)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
a->printPretty();
std::cout << (d->remove(120)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
d->printPretty();
std::cout << (b->insert(499)) << std::endl;
std::cout << (d->remove(212)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
std::cout << (c->insert(126)) << std::endl;
std::cout << (c->remove(205)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(126)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (e->remove(74)) << std::endl;
std::cout << (c->insert(177)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
*c=*e;
*a=*c;
std::cout << (c->remove(43)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
std::cout << (a->insert(230)) << std::endl;
d->printPretty();
*a=*a;
*a=*d;
e->printPretty();
*b=*c;
std::cout << (b->remove(394)) << std::endl;
std::cout << (c->insert(2)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (d->remove(242)) << std::endl;
d->printPretty();
std::cout << (c->insert(2)) << std::endl;
*a=*d;
std::cout << (e->insert(226)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
d->printPretty();
std::cout << (b->insert(233)) << std::endl;
a->printPretty();
std::cout << (c->insert(494)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (e->insert(226)) << std::endl;
std::cout << (b->insert(470)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (b->insert(70)) << std::endl;
d->printPretty();
std::cout << (c->insert(470)) << std::endl;
std::cout << (d->remove(226)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->remove(430)) << std::endl;
std::cout << (c->remove(2)) << std::endl;
*b=*b;
std::cout << (c->remove(247)) << std::endl;
std::cout << (a->insert(216)) << std::endl;
std::cout << (a->remove(488)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (a->remove(193)) << std::endl;
std::cout << (d->remove(216)) << std::endl;
std::cout << (e->remove(315)) << std::endl;
std::cout << (c->remove(247)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
*c=*c;
std::cout << (e->remove(470)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (b->insert(494)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
std::cout << (b->remove(470)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (a->insert(129)) << std::endl;
*c=*c;
std::cout << (c->remove(335)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (e->remove(43)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
*e=*d;
std::cout << (e->insert(193)) << std::endl;
b->printPretty();
std::cout << (d->insert(488)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
e->printPretty();
std::cout << (c->remove(476)) << std::endl;
std::cout << (e->insert(10)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->remove(193)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (e->remove(145)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (e->insert(193)) << std::endl;
std::cout << (a->remove(21)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
e->printPretty();
a->printPretty();
b->printPretty();
*d=*e;
std::cout << (d->insert(329)) << std::endl;
std::cout << (e->remove(329)) << std::endl;
*e=*d;
*c=*c;
b->printPretty();
*c=*c;
e->printPretty();
std::cout << (c->insert(486)) << std::endl;
e->printPretty();
std::cout << (c->insert(486)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
*a=*c;
a->printPretty();
*d=*d;
std::cout << (e->remove(329)) << std::endl;
*d=*d;
*a=*e;
std::cout << (a->insert(324)) << std::endl;
*c=*e;
std::cout << (a->remove(179)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
b->printPretty();
std::cout << (a->remove(42)) << std::endl;
std::cout << (e->insert(446)) << std::endl;
std::cout << (b->remove(124)) << std::endl;
std::cout << (c->remove(328)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (a->insert(279)) << std::endl;
std::cout << (b->insert(216)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
std::cout << (c->insert(193)) << std::endl;
c->printPretty();
*c=*e;
a->printPretty();
std::cout << (d->remove(329)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (d->insert(143)) << std::endl;
std::cout << (b->insert(405)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
*b=*a;
std::cout << (e->insert(280)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
*a=*e;
std::cout << (e->remove(446)) << std::endl;
b->printPretty();
*c=*c;
c->printPretty();
std::cout << (b->insert(492)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (e->insert(143)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (c->insert(340)) << std::endl;
*c=*a;
std::cout << (b->insert(15)) << std::endl;
std::cout << (a->remove(191)) << std::endl;
std::cout << (b->remove(133)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
d->printPretty();
d->printPretty();
*b=*e;
std::cout << (b->insert(143)) << std::endl;
a->printPretty();
*c=*a;
std::cout << (d->remove(446)) << std::endl;
std::cout << (b->remove(484)) << std::endl;
a->printPretty();
std::cout << (e->remove(184)) << std::endl;
c->printPretty();
std::cout << (e->insert(257)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
std::cout << (c->insert(10)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
*b=*a;
std::cout << (c->remove(193)) << std::endl;
a->printPretty();
std::cout << (d->remove(161)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (c->remove(345)) << std::endl;
std::cout << (e->remove(143)) << std::endl;
*c=*b;
*b=*b;
b->printPretty();
std::cout << (e->remove(193)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
e->printPretty();
std::cout << (b->remove(446)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
std::cout << (b->remove(144)) << std::endl;
std::cout << (b->remove(280)) << std::endl;
*c=*d;
*c=*e;
std::cout << (d->insert(193)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
*d=*e;
d->printPretty();
b->printPretty();
std::cout << (b->remove(344)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
d->printPretty();
std::cout << (d->remove(337)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (a->remove(406)) << std::endl;
std::cout << (e->remove(149)) << std::endl;
a->printPretty();
std::cout << (d->insert(257)) << std::endl;
a->printPretty();
std::cout << (d->remove(268)) << std::endl;
std::cout << (c->remove(363)) << std::endl;
*d=*d;
*b=*d;
*e=*e;
std::cout << (a->remove(280)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
std::cout << (d->remove(6)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (e->remove(411)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (e->remove(280)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
*a=*e;
std::cout << (c->remove(256)) << std::endl;
std::cout << (d->insert(280)) << std::endl;
*a=*e;
*a=*e;
d->printPretty();
std::cout << (d->remove(187)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
std::cout << (a->remove(304)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
d->printPretty();
*d=*a;
b->printPretty();
std::cout << (a->insert(390)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
*b=*c;
std::cout << (b->insert(280)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
*e=*d;
std::cout << (d->insert(268)) << std::endl;
c->printPretty();
a->printPretty();
*d=*e;
std::cout << (d->remove(37)) << std::endl;
b->printPretty();
std::cout << (d->remove(186)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
*d=*b;
std::cout << (b->remove(268)) << std::endl;
*e=*d;
std::cout << (d->remove(268)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
*c=*b;
std::cout << (d->remove(280)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (d->insert(257)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
*a=*a;
d->printPretty();
e->printPretty();
e->printPretty();
*b=*e;
std::cout << (e->remove(407)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
*c=*e;
std::cout << (a->insert(69)) << std::endl;
*a=*b;
*b=*b;
std::cout << (c->remove(268)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
*a=*e;
std::cout << (a->insert(69)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (e->insert(268)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
c->printPretty();
std::cout << (e->insert(8)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
*c=*d;
std::cout << (a->insert(217)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
d->printPretty();
std::cout << (d->insert(257)) << std::endl;
std::cout << (c->insert(497)) << std::endl;
*a=*d;
std::cout << (d->insert(327)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
*b=*a;
std::cout << (b->remove(257)) << std::endl;
std::cout << (e->insert(354)) << std::endl;
std::cout << (d->remove(48)) << std::endl;
*b=*a;
std::cout << (d->remove(327)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
*c=*c;
e->printPretty();
*a=*d;
std::cout << (a->insert(15)) << std::endl;
std::cout << (c->insert(389)) << std::endl;
*d=*c;
std::cout << (c->insert(69)) << std::endl;
std::cout << (e->insert(158)) << std::endl;
std::cout << (a->insert(440)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
std::cout << (a->insert(440)) << std::endl;
a->printPretty();
std::cout << (a->insert(440)) << std::endl;
std::cout << (d->insert(30)) << std::endl;
std::cout << (b->insert(64)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (a->remove(440)) << std::endl;
std::cout << (c->insert(69)) << std::endl;
*c=*d;
*c=*d;
std::cout << (a->remove(354)) << std::endl;
std::cout << (e->insert(497)) << std::endl;
std::cout << (d->insert(497)) << std::endl;
*e=*b;
std::cout << (c->remove(25)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
*b=*d;
std::cout << (c->insert(30)) << std::endl;
std::cout << (b->remove(389)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
std::cout << (b->insert(30)) << std::endl;
*a=*e;
*b=*d;
std::cout << (c->remove(283)) << std::endl;
std::cout << (d->remove(124)) << std::endl;
*a=*b;
std::cout << (e->insert(257)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
d->printPretty();
std::cout << (b->insert(30)) << std::endl;
std::cout << (d->insert(335)) << std::endl;
std::cout << (a->remove(426)) << std::endl;
a->printPretty();
*d=*b;
*e=*d;
*b=*b;
std::cout << (b->remove(89)) << std::endl;
std::cout << (c->remove(191)) << std::endl;
*d=*e;
std::cout << (e->remove(257)) << std::endl;
std::cout << (a->insert(386)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
*a=*a;
std::cout << (b->remove(30)) << std::endl;
std::cout << (c->insert(30)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (e->insert(386)) << std::endl;
d->printPretty();
std::cout << (e->remove(386)) << std::endl;
*c=*a;
*a=*e;
std::cout << (e->remove(30)) << std::endl;
std::cout << (b->remove(301)) << std::endl;
std::cout << (d->insert(257)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (b->insert(389)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
*b=*a;
std::cout << (b->remove(389)) << std::endl;
*a=*d;
std::cout << (c->insert(166)) << std::endl;
std::cout << (d->insert(157)) << std::endl;
std::cout << (a->remove(257)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
a->printPretty();
std::cout << (a->insert(30)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
std::cout << (a->remove(389)) << std::endl;
std::cout << (d->insert(30)) << std::endl;
a->printPretty();
std::cout << (e->remove(98)) << std::endl;
std::cout << (a->insert(30)) << std::endl;
std::cout << (c->insert(127)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
*a=*d;
*d=*d;
std::cout << (b->remove(8)) << std::endl;
std::cout << (e->remove(480)) << std::endl;
e->printPretty();
std::cout << (b->insert(160)) << std::endl;
std::cout << (b->insert(284)) << std::endl;
c->printPretty();
std::cout << (e->remove(285)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (d->remove(180)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (a->insert(120)) << std::endl;
std::cout << (c->insert(466)) << std::endl;
*a=*b;
*a=*d;
std::cout << (e->insert(420)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
std::cout << (a->insert(272)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
*d=*c;
std::cout << (b->insert(439)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (d->insert(166)) << std::endl;
std::cout << (a->remove(30)) << std::endl;
std::cout << (e->remove(80)) << std::endl;
b->printPretty();
*a=*e;
b->printPretty();
std::cout << (e->insert(113)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
c->printPretty();
std::cout << (e->insert(29)) << std::endl;
*a=*a;
e->printPretty();
d->printPretty();
*c=*a;
*c=*b;
d->printPretty();
*b=*c;
std::cout << (a->insert(272)) << std::endl;
*a=*a;
std::cout << (a->remove(76)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
*e=*e;
std::cout << (c->insert(149)) << std::endl;
*b=*b;
*a=*d;
std::cout << (b->remove(428)) << std::endl;
std::cout << (b->remove(348)) << std::endl;
std::cout << (d->insert(207)) << std::endl;
*e=*b;
std::cout << (d->insert(64)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (c->remove(149)) << std::endl;
b->printPretty();
std::cout << (b->remove(145)) << std::endl;
c->printPretty();
std::cout << (b->remove(108)) << std::endl;
*b=*b;
std::cout << (c->insert(284)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (c->remove(284)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
a->printPretty();
std::cout << (a->insert(484)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (d->remove(366)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
c->printPretty();
std::cout << (c->insert(245)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
std::cout << (c->remove(191)) << std::endl;
d->printPretty();
std::cout << (d->remove(477)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
a->printPretty();
std::cout << (c->insert(257)) << std::endl;
d->printPretty();
std::cout << (e->remove(177)) << std::endl;
std::cout << (b->insert(257)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
*a=*d;
std::cout << (a->remove(389)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (d->insert(244)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
b->printPretty();
std::cout << (c->insert(144)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (d->remove(257)) << std::endl;
std::cout << (e->insert(30)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
std::cout << (e->insert(30)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (d->insert(166)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->remove(412)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (e->insert(462)) << std::endl;
c->printPretty();
std::cout << (b->remove(284)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
c->printPretty();
std::cout << (b->insert(30)) << std::endl;
std::cout << (b->remove(439)) << std::endl;
std::cout << (d->insert(254)) << std::endl;
*e=*d;
std::cout << (b->insert(125)) << std::endl;
std::cout << (d->insert(340)) << std::endl;
std::cout << (a->insert(386)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->insert(253)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (b->remove(79)) << std::endl;
d->printPretty();
std::cout << (b->remove(125)) << std::endl;
e->printPretty();
std::cout << (b->remove(71)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (a->insert(97)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
*a=*b;
std::cout << (a->insert(142)) << std::endl;
e->printPretty();
std::cout << (e->insert(54)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (c->insert(145)) << std::endl;
d->printPretty();
std::cout << (a->insert(160)) << std::endl;
std::cout << (b->insert(5)) << std::endl;
std::cout << (b->insert(5)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (d->insert(417)) << std::endl;
std::cout << (b->remove(30)) << std::endl;
*b=*c;
return 0;
}
