#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
a->printPretty();
std::cout << (a->insert(161)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
std::cout << (b->insert(446)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (a->insert(272)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (b->insert(446)) << std::endl;
*a=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (c->remove(336)) << std::endl;
std::cout << (d->remove(398)) << std::endl;
*a=*c;
std::cout << (b->remove(161)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->remove(433)) << std::endl;
e->printPretty();
std::cout << (b->insert(446)) << std::endl;
e->printPretty();
*a=*a;
*c=*d;
std::cout << (b->remove(241)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
std::cout << (c->insert(48)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (d->insert(93)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
a->printPretty();
std::cout << (e->remove(457)) << std::endl;
std::cout << (d->remove(415)) << std::endl;
std::cout << (b->insert(487)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
a->printPretty();
std::cout << (b->insert(272)) << std::endl;
std::cout << (b->insert(272)) << std::endl;
std::cout << (e->remove(180)) << std::endl;
std::cout << (e->insert(226)) << std::endl;
std::cout << (d->remove(155)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (e->insert(226)) << std::endl;
d->printPretty();
std::cout << (b->insert(370)) << std::endl;
std::cout << (b->insert(487)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
*b=*a;
a->printPretty();
std::cout << (a->insert(383)) << std::endl;
c->printPretty();
c->printPretty();
d->printPretty();
std::cout << (d->remove(117)) << std::endl;
*d=*a;
std::cout << (a->remove(383)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
*e=*d;
c->printPretty();
a->printPretty();
std::cout << (d->remove(95)) << std::endl;
*a=*b;
std::cout << (d->insert(138)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (c->remove(344)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->remove(160)) << std::endl;
std::cout << (c->remove(464)) << std::endl;
d->printPretty();
std::cout << (a->insert(278)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (e->remove(383)) << std::endl;
*e=*b;
std::cout << (a->insert(499)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
b->printPretty();
std::cout << (e->insert(383)) << std::endl;
std::cout << (c->remove(208)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
std::cout << (d->insert(383)) << std::endl;
*b=*d;
std::cout << (b->insert(138)) << std::endl;
std::cout << (c->remove(171)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
*e=*d;
std::cout << (d->remove(102)) << std::endl;
std::cout << (d->remove(404)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
std::cout << (b->insert(383)) << std::endl;
*d=*d;
std::cout << (a->remove(384)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
a->printPretty();
std::cout << (c->remove(168)) << std::endl;
std::cout << (e->remove(97)) << std::endl;
std::cout << (c->remove(425)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (b->remove(388)) << std::endl;
*c=*d;
std::cout << (a->insert(278)) << std::endl;
std::cout << (d->insert(333)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
*c=*e;
c->printPretty();
b->printPretty();
std::cout << (c->insert(255)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
a->printPretty();
std::cout << (b->remove(168)) << std::endl;
std::cout << (d->insert(268)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
std::cout << (a->remove(279)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
*c=*e;
std::cout << (d->remove(112)) << std::endl;
std::cout << (a->remove(465)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
*d=*a;
std::cout << (d->remove(457)) << std::endl;
std::cout << (e->remove(168)) << std::endl;
std::cout << (e->remove(326)) << std::endl;
std::cout << (d->insert(143)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
d->printPretty();
std::cout << (a->insert(452)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (d->insert(470)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (b->insert(138)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (b->insert(419)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
a->printPretty();
std::cout << (b->insert(365)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (b->insert(383)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
std::cout << (b->insert(138)) << std::endl;
std::cout << (d->remove(451)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (a->insert(327)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
std::cout << (c->insert(326)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
std::cout << (d->insert(114)) << std::endl;
std::cout << (b->insert(383)) << std::endl;
std::cout << (e->remove(67)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
c->printPretty();
std::cout << (a->insert(452)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
std::cout << (e->remove(84)) << std::endl;
*a=*b;
std::cout << (a->insert(365)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (a->remove(365)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
*d=*b;
*d=*e;
*a=*c;
std::cout << (b->insert(483)) << std::endl;
std::cout << (b->insert(138)) << std::endl;
*c=*c;
std::cout << (a->insert(45)) << std::endl;
std::cout << (e->remove(383)) << std::endl;
d->printPretty();
std::cout << (e->remove(239)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
std::cout << (a->insert(77)) << std::endl;
b->printPretty();
std::cout << (e->insert(255)) << std::endl;
std::cout << (b->remove(138)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (e->remove(367)) << std::endl;
b->printPretty();
std::cout << (c->insert(216)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
c->printPretty();
std::cout << (d->remove(307)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->remove(365)) << std::endl;
*e=*a;
*b=*c;
e->printPretty();
std::cout << (a->remove(351)) << std::endl;
std::cout << (c->insert(116)) << std::endl;
*c=*e;
std::cout << (e->remove(450)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
*d=*c;
std::cout << (c->insert(450)) << std::endl;
d->printPretty();
std::cout << (b->remove(415)) << std::endl;
std::cout << (c->remove(26)) << std::endl;
b->printPretty();
std::cout << (e->insert(17)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (d->insert(416)) << std::endl;
b->printPretty();
d->printPretty();
d->printPretty();
*d=*a;
std::cout << (b->insert(371)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (d->insert(450)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
c->printPretty();
*e=*b;
e->printPretty();
d->printPretty();
e->printPretty();
*c=*c;
std::cout << (e->remove(157)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (d->remove(77)) << std::endl;
*c=*a;
std::cout << (b->insert(116)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
std::cout << (e->remove(400)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
std::cout << (a->insert(408)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (c->remove(9)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (e->insert(302)) << std::endl;
std::cout << (d->remove(371)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
b->printPretty();
std::cout << (d->remove(51)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (b->insert(51)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
std::cout << (a->remove(193)) << std::endl;
a->printPretty();
a->printPretty();
c->printPretty();
c->printPretty();
a->printPretty();
std::cout << (c->insert(450)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
std::cout << (e->insert(77)) << std::endl;
std::cout << (d->remove(193)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
a->printPretty();
std::cout << (e->insert(77)) << std::endl;
std::cout << (e->remove(318)) << std::endl;
std::cout << (e->remove(371)) << std::endl;
c->printPretty();
std::cout << (d->remove(426)) << std::endl;
*c=*d;
std::cout << (d->insert(450)) << std::endl;
std::cout << (a->remove(110)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (b->insert(326)) << std::endl;
std::cout << (c->remove(416)) << std::endl;
*a=*d;
std::cout << (b->remove(445)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
std::cout << (a->insert(257)) << std::endl;
std::cout << (d->remove(251)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
a->printPretty();
std::cout << (a->remove(450)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
std::cout << (e->insert(51)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (e->insert(45)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
std::cout << (b->remove(11)) << std::endl;
std::cout << (b->insert(259)) << std::endl;
std::cout << (e->remove(78)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (d->remove(17)) << std::endl;
std::cout << (d->remove(268)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (c->remove(448)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
std::cout << (e->remove(206)) << std::endl;
e->printPretty();
std::cout << (e->insert(51)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
a->printPretty();
std::cout << (c->remove(448)) << std::endl;
std::cout << (e->insert(208)) << std::endl;
std::cout << (c->remove(17)) << std::endl;
std::cout << (b->remove(390)) << std::endl;
b->printPretty();
*d=*a;
std::cout << (d->insert(370)) << std::endl;
*d=*b;
std::cout << (e->insert(51)) << std::endl;
b->printPretty();
a->printPretty();
c->printPretty();
std::cout << (e->remove(228)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
a->printPretty();
std::cout << (d->remove(363)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
std::cout << (b->insert(85)) << std::endl;
*e=*b;
std::cout << (a->insert(199)) << std::endl;
*a=*b;
*d=*d;
a->printPretty();
d->printPretty();
b->printPretty();
e->printPretty();
std::cout << (e->insert(51)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
std::cout << (a->insert(366)) << std::endl;
*a=*c;
*c=*a;
*a=*c;
*e=*b;
std::cout << (c->remove(450)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
std::cout << (e->remove(119)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
e->printPretty();
std::cout << (e->remove(311)) << std::endl;
*b=*a;
std::cout << (d->remove(51)) << std::endl;
std::cout << (b->insert(251)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (d->remove(116)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
std::cout << (b->insert(265)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
*b=*e;
std::cout << (c->remove(176)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (e->insert(441)) << std::endl;
*e=*a;
std::cout << (e->remove(244)) << std::endl;
*e=*b;
d->printPretty();
*c=*d;
*e=*e;
e->printPretty();
std::cout << (a->insert(450)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
std::cout << (e->remove(203)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
b->printPretty();
std::cout << (e->remove(15)) << std::endl;
std::cout << (c->remove(281)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (d->insert(371)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
*a=*a;
std::cout << (e->insert(277)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
std::cout << (a->remove(428)) << std::endl;
std::cout << (a->remove(356)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (e->insert(277)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
e->printPretty();
std::cout << (a->insert(461)) << std::endl;
std::cout << (a->insert(461)) << std::endl;
std::cout << (d->insert(382)) << std::endl;
*a=*e;
std::cout << (e->remove(277)) << std::endl;
c->printPretty();
std::cout << (b->insert(380)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
std::cout << (e->insert(414)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->remove(428)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (c->insert(277)) << std::endl;
std::cout << (c->remove(304)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
*a=*d;
std::cout << (a->insert(151)) << std::endl;
std::cout << (b->remove(380)) << std::endl;
d->printPretty();
std::cout << (b->insert(68)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (c->insert(277)) << std::endl;
std::cout << (a->remove(281)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
*a=*e;
*e=*c;
d->printPretty();
*d=*e;
std::cout << (d->insert(181)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
std::cout << (a->insert(219)) << std::endl;
*a=*a;
std::cout << (d->remove(277)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
std::cout << (d->insert(385)) << std::endl;
std::cout << (a->insert(32)) << std::endl;
std::cout << (a->insert(219)) << std::endl;
std::cout << (a->insert(117)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
e->printPretty();
std::cout << (d->insert(257)) << std::endl;
std::cout << (b->remove(68)) << std::endl;
std::cout << (d->insert(181)) << std::endl;
std::cout << (e->remove(57)) << std::endl;
a->printPretty();
std::cout << (c->insert(448)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (b->remove(441)) << std::endl;
std::cout << (e->insert(28)) << std::endl;
std::cout << (e->remove(277)) << std::endl;
*d=*b;
*a=*e;
a->printPretty();
std::cout << (d->remove(70)) << std::endl;
std::cout << (a->remove(28)) << std::endl;
std::cout << (c->remove(497)) << std::endl;
std::cout << (a->remove(54)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
*a=*e;
std::cout << (b->remove(172)) << std::endl;
*b=*b;
*a=*c;
*a=*d;
*e=*c;
std::cout << (a->remove(19)) << std::endl;
c->printPretty();
std::cout << (d->insert(310)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
std::cout << (d->remove(310)) << std::endl;
*c=*a;
std::cout << (e->insert(491)) << std::endl;
std::cout << (e->insert(277)) << std::endl;
std::cout << (e->insert(448)) << std::endl;
a->printPretty();
std::cout << (d->insert(155)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
std::cout << (c->insert(149)) << std::endl;
std::cout << (a->insert(142)) << std::endl;
std::cout << (d->remove(446)) << std::endl;
c->printPretty();
*a=*d;
a->printPretty();
std::cout << (c->remove(149)) << std::endl;
e->printPretty();
c->printPretty();
c->printPretty();
std::cout << (d->remove(63)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
b->printPretty();
std::cout << (b->remove(494)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
*c=*a;
std::cout << (e->insert(133)) << std::endl;
std::cout << (e->remove(277)) << std::endl;
std::cout << (a->remove(229)) << std::endl;
*d=*b;
*e=*e;
std::cout << (e->remove(448)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
*c=*c;
std::cout << (b->remove(307)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
*e=*a;
e->printPretty();
*c=*d;
std::cout << (c->insert(275)) << std::endl;
*d=*a;
std::cout << (e->insert(443)) << std::endl;
*a=*a;
std::cout << (b->insert(95)) << std::endl;
std::cout << (e->remove(53)) << std::endl;
*b=*d;
a->printPretty();
std::cout << (c->remove(275)) << std::endl;
std::cout << (e->insert(28)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (a->insert(294)) << std::endl;
*d=*e;
a->printPretty();
a->printPretty();
*c=*a;
*b=*c;
*c=*a;
std::cout << (e->remove(28)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (b->remove(294)) << std::endl;
c->printPretty();
std::cout << (d->remove(38)) << std::endl;
*b=*b;
d->printPretty();
std::cout << (c->remove(116)) << std::endl;
c->printPretty();
std::cout << (a->remove(77)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
e->printPretty();
std::cout << (d->remove(204)) << std::endl;
std::cout << (e->insert(443)) << std::endl;
std::cout << (c->insert(267)) << std::endl;
b->printPretty();
std::cout << (e->remove(265)) << std::endl;
d->printPretty();
std::cout << (a->insert(209)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (e->insert(269)) << std::endl;
a->printPretty();
std::cout << (e->remove(269)) << std::endl;
*d=*a;
*e=*b;
*d=*d;
std::cout << (a->remove(41)) << std::endl;
std::cout << (d->remove(115)) << std::endl;
*e=*d;
std::cout << (e->remove(14)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (c->insert(139)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
std::cout << (b->insert(77)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
std::cout << (b->insert(401)) << std::endl;
e->printPretty();
std::cout << (c->remove(38)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
*d=*b;
std::cout << (e->remove(68)) << std::endl;
std::cout << (e->insert(151)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
std::cout << (b->insert(401)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (e->remove(128)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
*c=*e;
std::cout << (a->insert(220)) << std::endl;
std::cout << (e->remove(209)) << std::endl;
std::cout << (a->insert(273)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (c->remove(294)) << std::endl;
std::cout << (a->remove(92)) << std::endl;
std::cout << (a->remove(38)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
std::cout << (e->insert(139)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (a->remove(220)) << std::endl;
std::cout << (e->insert(424)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
*e=*a;
std::cout << (a->remove(88)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
*b=*a;
*b=*c;
e->printPretty();
*d=*e;
*b=*b;
std::cout << (b->insert(103)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
std::cout << (d->remove(258)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
std::cout << (d->remove(177)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
std::cout << (c->remove(57)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (c->insert(246)) << std::endl;
std::cout << (e->insert(212)) << std::endl;
std::cout << (a->remove(384)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
e->printPretty();
std::cout << (c->remove(209)) << std::endl;
std::cout << (d->insert(162)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
std::cout << (c->insert(139)) << std::endl;
std::cout << (b->insert(452)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
*d=*b;
e->printPretty();
d->printPretty();
std::cout << (c->remove(155)) << std::endl;
std::cout << (a->insert(373)) << std::endl;
std::cout << (d->remove(139)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
*c=*d;
std::cout << (e->insert(273)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (c->insert(452)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
std::cout << (b->insert(349)) << std::endl;
*a=*e;
std::cout << (a->insert(321)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
*e=*e;
std::cout << (d->remove(112)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
a->printPretty();
std::cout << (d->insert(299)) << std::endl;
std::cout << (b->insert(105)) << std::endl;
*a=*e;
std::cout << (a->remove(348)) << std::endl;
std::cout << (e->insert(366)) << std::endl;
std::cout << (e->remove(421)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
std::cout << (a->insert(446)) << std::endl;
std::cout << (d->insert(24)) << std::endl;
std::cout << (c->insert(60)) << std::endl;
std::cout << (d->remove(144)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
*a=*a;
std::cout << (e->insert(273)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (a->insert(71)) << std::endl;
return 0;
}
