#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
*b=*a;
std::cout << (b->insert(22)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
*b=*c;
a->printPretty();
std::cout << (b->remove(368)) << std::endl;
std::cout << (b->remove(22)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
*a=*a;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (c->insert(393)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
*c=*c;
*d=*d;
a->printPretty();
std::cout << (c->insert(360)) << std::endl;
b->printPretty();
*a=*c;
std::cout << (c->remove(458)) << std::endl;
*a=*b;
std::cout << (a->insert(13)) << std::endl;
std::cout << (a->insert(13)) << std::endl;
*d=*e;
std::cout << (b->remove(443)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
std::cout << (c->remove(360)) << std::endl;
*a=*e;
c->printPretty();
e->printPretty();
std::cout << (e->remove(404)) << std::endl;
*c=*c;
std::cout << (d->insert(238)) << std::endl;
d->printPretty();
*b=*e;
std::cout << (c->insert(297)) << std::endl;
std::cout << (d->insert(238)) << std::endl;
std::cout << (e->remove(441)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
std::cout << (a->insert(341)) << std::endl;
std::cout << (e->insert(70)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
*a=*c;
*a=*c;
std::cout << (d->remove(238)) << std::endl;
*c=*e;
std::cout << (c->insert(416)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
std::cout << (a->remove(393)) << std::endl;
*e=*e;
std::cout << (c->insert(476)) << std::endl;
std::cout << (c->insert(476)) << std::endl;
e->printPretty();
std::cout << (e->insert(70)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (e->insert(70)) << std::endl;
*c=*a;
*d=*a;
std::cout << (d->remove(243)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
*b=*d;
*b=*e;
std::cout << (a->insert(424)) << std::endl;
b->printPretty();
std::cout << (d->remove(179)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (e->insert(236)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
d->printPretty();
std::cout << (b->insert(70)) << std::endl;
std::cout << (a->remove(30)) << std::endl;
std::cout << (d->insert(424)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
std::cout << (c->remove(22)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
*e=*d;
std::cout << (a->remove(22)) << std::endl;
std::cout << (e->insert(22)) << std::endl;
d->printPretty();
std::cout << (a->remove(193)) << std::endl;
c->printPretty();
std::cout << (b->insert(367)) << std::endl;
std::cout << (c->insert(301)) << std::endl;
std::cout << (c->insert(462)) << std::endl;
std::cout << (d->remove(424)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (c->remove(462)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (e->insert(297)) << std::endl;
std::cout << (b->remove(355)) << std::endl;
std::cout << (c->insert(145)) << std::endl;
*c=*a;
std::cout << (d->insert(498)) << std::endl;
b->printPretty();
std::cout << (a->insert(422)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (d->insert(144)) << std::endl;
std::cout << (b->remove(343)) << std::endl;
*c=*b;
std::cout << (b->remove(345)) << std::endl;
std::cout << (a->remove(58)) << std::endl;
std::cout << (e->remove(124)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
*e=*a;
std::cout << (e->insert(352)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
c->printPretty();
std::cout << (a->remove(304)) << std::endl;
std::cout << (d->insert(144)) << std::endl;
*b=*d;
std::cout << (b->remove(297)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
std::cout << (a->remove(313)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
*e=*d;
std::cout << (a->remove(21)) << std::endl;
*d=*c;
std::cout << (c->insert(367)) << std::endl;
std::cout << (d->insert(369)) << std::endl;
*d=*d;
b->printPretty();
d->printPretty();
*e=*a;
std::cout << (a->remove(424)) << std::endl;
*c=*d;
std::cout << (d->remove(390)) << std::endl;
std::cout << (e->insert(129)) << std::endl;
std::cout << (a->remove(388)) << std::endl;
std::cout << (a->remove(297)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
std::cout << (e->remove(240)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(8)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (a->insert(49)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->insert(183)) << std::endl;
std::cout << (c->remove(70)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
std::cout << (c->remove(284)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
a->printPretty();
std::cout << (e->insert(226)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
*e=*a;
std::cout << (d->insert(367)) << std::endl;
*b=*c;
std::cout << (b->remove(341)) << std::endl;
a->printPretty();
std::cout << (d->insert(137)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
std::cout << (d->remove(367)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
std::cout << (d->insert(435)) << std::endl;
std::cout << (e->remove(454)) << std::endl;
e->printPretty();
std::cout << (d->remove(182)) << std::endl;
std::cout << (e->insert(16)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
*e=*c;
std::cout << (d->remove(385)) << std::endl;
std::cout << (a->remove(49)) << std::endl;
b->printPretty();
std::cout << (a->insert(403)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (d->insert(490)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
*e=*a;
std::cout << (d->remove(218)) << std::endl;
*b=*a;
std::cout << (d->remove(231)) << std::endl;
*d=*c;
std::cout << (d->remove(286)) << std::endl;
*d=*c;
std::cout << (e->remove(246)) << std::endl;
std::cout << (e->insert(444)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (e->insert(376)) << std::endl;
std::cout << (c->remove(341)) << std::endl;
std::cout << (e->insert(354)) << std::endl;
*c=*a;
std::cout << (c->insert(403)) << std::endl;
c->printPretty();
std::cout << (b->insert(233)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (c->remove(403)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (d->remove(198)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (e->insert(246)) << std::endl;
std::cout << (b->insert(203)) << std::endl;
b->printPretty();
std::cout << (e->remove(493)) << std::endl;
std::cout << (a->insert(186)) << std::endl;
std::cout << (a->remove(82)) << std::endl;
std::cout << (d->remove(225)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
std::cout << (b->remove(246)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
a->printPretty();
std::cout << (e->remove(246)) << std::endl;
std::cout << (a->insert(186)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
*b=*b;
*d=*d;
std::cout << (a->insert(198)) << std::endl;
*c=*a;
*e=*e;
std::cout << (b->remove(203)) << std::endl;
a->printPretty();
std::cout << (d->remove(364)) << std::endl;
c->printPretty();
b->printPretty();
d->printPretty();
std::cout << (d->remove(120)) << std::endl;
b->printPretty();
std::cout << (c->remove(11)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
std::cout << (e->remove(483)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
*c=*e;
std::cout << (e->insert(255)) << std::endl;
d->printPretty();
std::cout << (e->insert(255)) << std::endl;
std::cout << (c->insert(490)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
std::cout << (c->insert(418)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
std::cout << (e->remove(255)) << std::endl;
c->printPretty();
*c=*a;
b->printPretty();
std::cout << (a->insert(198)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
std::cout << (e->insert(357)) << std::endl;
std::cout << (b->insert(443)) << std::endl;
std::cout << (c->insert(403)) << std::endl;
*e=*b;
std::cout << (e->insert(403)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
std::cout << (c->remove(103)) << std::endl;
*e=*b;
*e=*b;
std::cout << (b->remove(51)) << std::endl;
*c=*a;
std::cout << (c->insert(100)) << std::endl;
std::cout << (e->insert(403)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
*a=*d;
*d=*a;
std::cout << (c->remove(309)) << std::endl;
std::cout << (e->remove(403)) << std::endl;
std::cout << (e->remove(423)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
c->printPretty();
std::cout << (b->insert(443)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (d->remove(75)) << std::endl;
std::cout << (e->remove(225)) << std::endl;
std::cout << (c->remove(126)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
*b=*a;
b->printPretty();
d->printPretty();
std::cout << (e->insert(252)) << std::endl;
std::cout << (e->remove(252)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
std::cout << (d->remove(134)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (b->remove(134)) << std::endl;
d->printPretty();
c->printPretty();
*d=*e;
std::cout << (d->remove(443)) << std::endl;
c->printPretty();
std::cout << (c->insert(152)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
b->printPretty();
std::cout << (a->insert(134)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
e->printPretty();
std::cout << (e->remove(443)) << std::endl;
*b=*c;
std::cout << (b->remove(198)) << std::endl;
*a=*b;
c->printPretty();
*c=*d;
c->printPretty();
*e=*d;
std::cout << (a->insert(47)) << std::endl;
*c=*c;
std::cout << (d->insert(312)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
a->printPretty();
std::cout << (a->insert(403)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (a->remove(351)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
*d=*b;
c->printPretty();
std::cout << (a->insert(100)) << std::endl;
std::cout << (d->insert(424)) << std::endl;
std::cout << (c->remove(412)) << std::endl;
std::cout << (d->remove(424)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
e->printPretty();
std::cout << (c->insert(462)) << std::endl;
std::cout << (b->remove(100)) << std::endl;
d->printPretty();
std::cout << (c->insert(329)) << std::endl;
*e=*c;
std::cout << (e->remove(329)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
c->printPretty();
std::cout << (e->remove(230)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
c->printPretty();
std::cout << (e->insert(462)) << std::endl;
*c=*b;
std::cout << (e->remove(117)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
e->printPretty();
std::cout << (d->remove(317)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (e->remove(433)) << std::endl;
*c=*e;
b->printPretty();
c->printPretty();
std::cout << (a->remove(419)) << std::endl;
*c=*e;
std::cout << (c->remove(371)) << std::endl;
d->printPretty();
std::cout << (b->insert(281)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (c->insert(462)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
std::cout << (c->remove(462)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
b->printPretty();
e->printPretty();
c->printPretty();
std::cout << (b->remove(370)) << std::endl;
std::cout << (a->insert(461)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (b->remove(363)) << std::endl;
std::cout << (a->insert(186)) << std::endl;
std::cout << (c->remove(204)) << std::endl;
std::cout << (b->insert(93)) << std::endl;
std::cout << (a->insert(461)) << std::endl;
std::cout << (a->remove(191)) << std::endl;
std::cout << (b->insert(145)) << std::endl;
std::cout << (d->remove(100)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (e->insert(494)) << std::endl;
*e=*b;
*a=*c;
std::cout << (c->remove(399)) << std::endl;
std::cout << (e->remove(462)) << std::endl;
*c=*d;
std::cout << (d->insert(281)) << std::endl;
b->printPretty();
std::cout << (a->remove(49)) << std::endl;
std::cout << (e->insert(193)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
*e=*a;
*d=*e;
std::cout << (e->remove(42)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
std::cout << (b->remove(153)) << std::endl;
*c=*b;
std::cout << (b->remove(186)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
b->printPretty();
std::cout << (b->insert(17)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (a->insert(32)) << std::endl;
std::cout << (d->insert(186)) << std::endl;
b->printPretty();
std::cout << (d->insert(426)) << std::endl;
std::cout << (c->insert(403)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
*a=*a;
std::cout << (a->remove(32)) << std::endl;
std::cout << (c->remove(219)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (b->remove(93)) << std::endl;
c->printPretty();
std::cout << (c->remove(459)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (b->remove(145)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->insert(145)) << std::endl;
std::cout << (e->insert(16)) << std::endl;
*d=*e;
std::cout << (d->insert(138)) << std::endl;
*c=*e;
a->printPretty();
b->printPretty();
std::cout << (c->insert(16)) << std::endl;
std::cout << (c->remove(247)) << std::endl;
*d=*d;
*b=*b;
d->printPretty();
*d=*e;
std::cout << (b->remove(98)) << std::endl;
std::cout << (c->remove(65)) << std::endl;
std::cout << (d->remove(316)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
std::cout << (b->remove(28)) << std::endl;
c->printPretty();
std::cout << (d->remove(191)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (c->insert(16)) << std::endl;
*b=*d;
*d=*d;
std::cout << (c->insert(16)) << std::endl;
*c=*a;
*a=*c;
std::cout << (d->insert(16)) << std::endl;
c->printPretty();
std::cout << (c->remove(483)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
*c=*c;
std::cout << (d->remove(67)) << std::endl;
std::cout << (b->remove(88)) << std::endl;
std::cout << (b->insert(242)) << std::endl;
b->printPretty();
b->printPretty();
*b=*a;
std::cout << (e->remove(16)) << std::endl;
d->printPretty();
std::cout << (b->insert(202)) << std::endl;
std::cout << (a->insert(181)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
*b=*c;
*b=*b;
std::cout << (d->remove(16)) << std::endl;
*d=*b;
std::cout << (a->remove(181)) << std::endl;
std::cout << (a->insert(403)) << std::endl;
std::cout << (a->remove(215)) << std::endl;
std::cout << (a->insert(403)) << std::endl;
std::cout << (d->insert(34)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
std::cout << (d->insert(251)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (a->insert(403)) << std::endl;
std::cout << (c->insert(470)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (c->insert(229)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
*a=*d;
*c=*d;
*a=*d;
std::cout << (b->remove(96)) << std::endl;
std::cout << (a->insert(401)) << std::endl;
*d=*d;
std::cout << (b->insert(408)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (a->insert(401)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
std::cout << (a->remove(287)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (a->remove(183)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (d->remove(251)) << std::endl;
b->printPretty();
*c=*d;
*a=*d;
std::cout << (b->insert(468)) << std::endl;
std::cout << (b->insert(226)) << std::endl;
*e=*e;
std::cout << (a->insert(34)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (e->remove(183)) << std::endl;
a->printPretty();
b->printPretty();
*d=*e;
*c=*b;
std::cout << (a->insert(34)) << std::endl;
a->printPretty();
std::cout << (a->remove(34)) << std::endl;
std::cout << (d->remove(378)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (e->remove(79)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (b->insert(226)) << std::endl;
d->printPretty();
std::cout << (a->remove(430)) << std::endl;
e->printPretty();
std::cout << (a->insert(418)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
d->printPretty();
std::cout << (a->insert(418)) << std::endl;
a->printPretty();
std::cout << (a->insert(418)) << std::endl;
std::cout << (a->insert(418)) << std::endl;
std::cout << (e->remove(215)) << std::endl;
c->printPretty();
*b=*d;
e->printPretty();
*c=*a;
std::cout << (e->insert(353)) << std::endl;
std::cout << (e->insert(207)) << std::endl;
d->printPretty();
std::cout << (d->remove(78)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
std::cout << (c->insert(418)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
*d=*b;
d->printPretty();
std::cout << (c->remove(135)) << std::endl;
e->printPretty();
*c=*b;
b->printPretty();
*a=*e;
std::cout << (c->insert(470)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
b->printPretty();
std::cout << (b->insert(66)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
std::cout << (d->insert(283)) << std::endl;
std::cout << (e->remove(180)) << std::endl;
std::cout << (c->remove(340)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
std::cout << (a->remove(353)) << std::endl;
*b=*b;
std::cout << (c->remove(417)) << std::endl;
*a=*a;
e->printPretty();
a->printPretty();
e->printPretty();
b->printPretty();
d->printPretty();
std::cout << (c->remove(385)) << std::endl;
std::cout << (b->remove(66)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
*c=*a;
std::cout << (e->insert(205)) << std::endl;
std::cout << (c->insert(489)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
a->printPretty();
std::cout << (e->remove(205)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (c->remove(117)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
std::cout << (a->insert(377)) << std::endl;
c->printPretty();
std::cout << (d->remove(176)) << std::endl;
*c=*c;
*e=*c;
*e=*a;
c->printPretty();
*a=*e;
std::cout << (c->insert(183)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
a->printPretty();
*a=*d;
c->printPretty();
*e=*c;
std::cout << (b->remove(237)) << std::endl;
std::cout << (a->insert(426)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (a->insert(295)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
*e=*e;
std::cout << (d->remove(416)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
std::cout << (d->remove(283)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
c->printPretty();
std::cout << (d->remove(484)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
d->printPretty();
std::cout << (a->insert(471)) << std::endl;
std::cout << (e->insert(183)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
d->printPretty();
std::cout << (a->remove(426)) << std::endl;
*b=*d;
*d=*e;
a->printPretty();
std::cout << (e->remove(268)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (b->remove(381)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (d->remove(183)) << std::endl;
std::cout << (a->remove(266)) << std::endl;
*c=*c;
std::cout << (a->insert(306)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (c->remove(409)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (a->insert(237)) << std::endl;
*c=*d;
std::cout << (a->insert(237)) << std::endl;
std::cout << (a->remove(237)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
return 0;
}
