#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(310)) << std::endl;
*b=*a;
std::cout << (b->insert(404)) << std::endl;
*a=*b;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (a->insert(404)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (c->remove(246)) << std::endl;
*c=*a;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*b=*d;
e->printPretty();
std::cout << (c->insert(404)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
*a=*e;
std::cout << (b->insert(404)) << std::endl;
std::cout << (b->insert(96)) << std::endl;
std::cout << (d->remove(371)) << std::endl;
a->printPretty();
std::cout << (b->remove(404)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (d->insert(404)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
std::cout << (d->insert(157)) << std::endl;
a->printPretty();
std::cout << (b->remove(380)) << std::endl;
*d=*c;
d->printPretty();
std::cout << (e->insert(186)) << std::endl;
*e=*c;
std::cout << (a->remove(50)) << std::endl;
c->printPretty();
std::cout << (d->insert(36)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
std::cout << (e->remove(250)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
c->printPretty();
std::cout << (b->insert(291)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
std::cout << (d->insert(343)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(96)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (d->remove(404)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (b->insert(291)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (e->insert(96)) << std::endl;
*e=*b;
*a=*c;
a->printPretty();
std::cout << (a->insert(242)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
b->printPretty();
std::cout << (a->remove(242)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
std::cout << (c->insert(289)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
std::cout << (e->remove(209)) << std::endl;
a->printPretty();
std::cout << (e->remove(270)) << std::endl;
std::cout << (c->remove(289)) << std::endl;
std::cout << (d->remove(343)) << std::endl;
std::cout << (e->remove(487)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
e->printPretty();
b->printPretty();
d->printPretty();
*b=*d;
std::cout << (a->remove(220)) << std::endl;
d->printPretty();
c->printPretty();
e->printPretty();
std::cout << (c->remove(71)) << std::endl;
*b=*c;
std::cout << (e->insert(291)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
*a=*d;
std::cout << (c->remove(158)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
c->printPretty();
std::cout << (c->remove(242)) << std::endl;
*b=*a;
c->printPretty();
*d=*b;
*c=*a;
d->printPretty();
std::cout << (e->remove(127)) << std::endl;
*a=*e;
*d=*e;
std::cout << (e->remove(96)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
std::cout << (c->remove(115)) << std::endl;
*a=*c;
std::cout << (b->insert(375)) << std::endl;
std::cout << (e->remove(318)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
*e=*d;
std::cout << (d->insert(80)) << std::endl;
std::cout << (b->remove(311)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (d->insert(323)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
*b=*d;
std::cout << (d->insert(149)) << std::endl;
std::cout << (d->remove(185)) << std::endl;
std::cout << (d->insert(256)) << std::endl;
*e=*b;
b->printPretty();
e->printPretty();
*a=*b;
std::cout << (d->insert(225)) << std::endl;
std::cout << (d->remove(81)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (d->insert(397)) << std::endl;
std::cout << (d->insert(42)) << std::endl;
d->printPretty();
std::cout << (a->remove(323)) << std::endl;
std::cout << (c->remove(274)) << std::endl;
std::cout << (e->insert(80)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
b->printPretty();
*d=*e;
std::cout << (e->remove(80)) << std::endl;
std::cout << (d->insert(323)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (d->remove(80)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
c->printPretty();
std::cout << (b->remove(323)) << std::endl;
*d=*a;
std::cout << (b->insert(96)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->insert(96)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (d->remove(81)) << std::endl;
std::cout << (d->remove(461)) << std::endl;
std::cout << (c->remove(285)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
e->printPretty();
std::cout << (a->remove(38)) << std::endl;
a->printPretty();
std::cout << (e->remove(131)) << std::endl;
a->printPretty();
std::cout << (d->remove(33)) << std::endl;
a->printPretty();
*b=*d;
std::cout << (b->insert(291)) << std::endl;
std::cout << (b->remove(347)) << std::endl;
c->printPretty();
std::cout << (b->remove(3)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
*c=*a;
*d=*b;
std::cout << (e->remove(368)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (d->insert(191)) << std::endl;
*e=*c;
c->printPretty();
*e=*b;
std::cout << (a->insert(96)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
b->printPretty();
std::cout << (e->remove(80)) << std::endl;
d->printPretty();
std::cout << (c->remove(452)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (b->remove(291)) << std::endl;
std::cout << (b->insert(80)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
*b=*e;
*e=*b;
std::cout << (d->insert(191)) << std::endl;
a->printPretty();
*d=*e;
*e=*a;
b->printPretty();
std::cout << (d->insert(291)) << std::endl;
std::cout << (c->insert(455)) << std::endl;
std::cout << (b->insert(291)) << std::endl;
*e=*a;
std::cout << (c->insert(372)) << std::endl;
std::cout << (b->remove(204)) << std::endl;
std::cout << (e->insert(191)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (c->remove(336)) << std::endl;
*b=*c;
std::cout << (d->insert(28)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
std::cout << (a->insert(462)) << std::endl;
e->printPretty();
std::cout << (c->insert(455)) << std::endl;
*a=*d;
std::cout << (d->remove(91)) << std::endl;
std::cout << (c->insert(96)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
std::cout << (d->remove(281)) << std::endl;
std::cout << (e->remove(191)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (e->remove(290)) << std::endl;
e->printPretty();
std::cout << (a->insert(28)) << std::endl;
*a=*b;
*d=*d;
std::cout << (c->insert(112)) << std::endl;
std::cout << (d->insert(28)) << std::endl;
std::cout << (d->remove(401)) << std::endl;
d->printPretty();
std::cout << (c->remove(80)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
std::cout << (a->insert(96)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (a->insert(96)) << std::endl;
std::cout << (d->insert(291)) << std::endl;
std::cout << (c->insert(291)) << std::endl;
std::cout << (c->insert(81)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (b->insert(149)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
*a=*e;
*e=*e;
e->printPretty();
std::cout << (d->remove(474)) << std::endl;
e->printPretty();
std::cout << (b->insert(149)) << std::endl;
c->printPretty();
c->printPretty();
d->printPretty();
std::cout << (b->insert(291)) << std::endl;
*a=*e;
*e=*d;
std::cout << (e->remove(283)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
std::cout << (a->remove(396)) << std::endl;
*b=*a;
std::cout << (b->insert(291)) << std::endl;
std::cout << (a->remove(394)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
std::cout << (c->remove(369)) << std::endl;
a->printPretty();
std::cout << (d->insert(291)) << std::endl;
std::cout << (b->insert(378)) << std::endl;
d->printPretty();
std::cout << (e->remove(346)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
*d=*e;
std::cout << (a->insert(451)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (b->insert(251)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
e->printPretty();
std::cout << (a->remove(183)) << std::endl;
b->printPretty();
std::cout << (b->remove(291)) << std::endl;
*c=*b;
*d=*b;
d->printPretty();
*e=*d;
std::cout << (c->insert(363)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (c->remove(251)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (c->insert(145)) << std::endl;
*c=*d;
*c=*b;
std::cout << (e->insert(251)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (e->insert(326)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
b->printPretty();
std::cout << (b->remove(96)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (d->remove(29)) << std::endl;
*e=*d;
std::cout << (c->insert(184)) << std::endl;
*d=*a;
std::cout << (b->insert(251)) << std::endl;
std::cout << (c->remove(80)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (e->remove(80)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
*a=*e;
std::cout << (b->insert(342)) << std::endl;
std::cout << (b->remove(342)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
std::cout << (b->remove(34)) << std::endl;
std::cout << (e->insert(378)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
e->printPretty();
std::cout << (c->insert(96)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
*b=*a;
*b=*e;
c->printPretty();
std::cout << (e->insert(422)) << std::endl;
c->printPretty();
std::cout << (a->remove(386)) << std::endl;
std::cout << (d->insert(265)) << std::endl;
e->printPretty();
std::cout << (d->insert(330)) << std::endl;
std::cout << (b->remove(203)) << std::endl;
*d=*b;
*d=*a;
e->printPretty();
std::cout << (a->remove(378)) << std::endl;
a->printPretty();
std::cout << (a->insert(64)) << std::endl;
std::cout << (b->remove(15)) << std::endl;
std::cout << (c->insert(468)) << std::endl;
std::cout << (b->insert(451)) << std::endl;
*d=*e;
d->printPretty();
*b=*b;
std::cout << (b->remove(74)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
c->printPretty();
std::cout << (c->insert(378)) << std::endl;
*c=*d;
std::cout << (a->insert(263)) << std::endl;
std::cout << (a->remove(424)) << std::endl;
std::cout << (a->remove(263)) << std::endl;
*b=*a;
std::cout << (a->insert(251)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
a->printPretty();
*b=*d;
c->printPretty();
std::cout << (b->remove(81)) << std::endl;
std::cout << (a->remove(251)) << std::endl;
std::cout << (d->remove(277)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
std::cout << (d->remove(386)) << std::endl;
std::cout << (a->insert(451)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (b->remove(378)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (b->remove(422)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (a->remove(466)) << std::endl;
*c=*d;
std::cout << (e->insert(96)) << std::endl;
*e=*b;
std::cout << (c->remove(85)) << std::endl;
std::cout << (b->remove(96)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (a->remove(451)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (c->insert(251)) << std::endl;
c->printPretty();
std::cout << (b->remove(117)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
std::cout << (c->remove(433)) << std::endl;
std::cout << (e->insert(207)) << std::endl;
b->printPretty();
std::cout << (d->remove(378)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (d->insert(174)) << std::endl;
d->printPretty();
std::cout << (a->insert(245)) << std::endl;
std::cout << (d->insert(451)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (c->remove(378)) << std::endl;
std::cout << (a->insert(210)) << std::endl;
*a=*a;
std::cout << (c->insert(482)) << std::endl;
std::cout << (d->insert(251)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
*d=*a;
c->printPretty();
*d=*d;
std::cout << (b->insert(447)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (b->insert(447)) << std::endl;
d->printPretty();
std::cout << (d->remove(371)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
*e=*a;
std::cout << (a->remove(435)) << std::endl;
std::cout << (d->insert(210)) << std::endl;
*b=*b;
std::cout << (c->insert(81)) << std::endl;
e->printPretty();
std::cout << (a->insert(245)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
*a=*e;
d->printPretty();
c->printPretty();
std::cout << (a->remove(459)) << std::endl;
std::cout << (a->insert(272)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
*c=*b;
std::cout << (a->remove(480)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
*d=*a;
std::cout << (e->remove(210)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (e->insert(445)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
*e=*c;
std::cout << (c->remove(447)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
std::cout << (a->insert(64)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
*b=*b;
std::cout << (d->remove(251)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
std::cout << (b->insert(251)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
b->printPretty();
std::cout << (a->insert(75)) << std::endl;
std::cout << (c->remove(364)) << std::endl;
b->printPretty();
std::cout << (c->remove(488)) << std::endl;
std::cout << (c->remove(296)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
std::cout << (a->insert(64)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
std::cout << (d->insert(315)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
std::cout << (d->remove(426)) << std::endl;
std::cout << (a->remove(64)) << std::endl;
std::cout << (e->remove(251)) << std::endl;
*e=*c;
std::cout << (a->remove(208)) << std::endl;
std::cout << (d->remove(315)) << std::endl;
std::cout << (b->remove(251)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
c->printPretty();
std::cout << (e->insert(203)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
std::cout << (b->insert(451)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
std::cout << (b->remove(334)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
a->printPretty();
std::cout << (e->remove(444)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
e->printPretty();
*c=*d;
std::cout << (e->insert(205)) << std::endl;
std::cout << (b->remove(451)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
*b=*b;
*a=*a;
std::cout << (e->insert(203)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (e->insert(251)) << std::endl;
std::cout << (d->remove(258)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
*b=*a;
std::cout << (e->remove(205)) << std::endl;
std::cout << (b->insert(250)) << std::endl;
*c=*e;
std::cout << (d->remove(245)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
c->printPretty();
std::cout << (d->insert(400)) << std::endl;
*c=*a;
std::cout << (e->insert(344)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
c->printPretty();
std::cout << (c->remove(168)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (b->insert(433)) << std::endl;
std::cout << (b->insert(433)) << std::endl;
std::cout << (b->remove(453)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (e->remove(451)) << std::endl;
e->printPretty();
std::cout << (b->insert(484)) << std::endl;
a->printPretty();
std::cout << (a->insert(267)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (b->insert(44)) << std::endl;
std::cout << (e->insert(12)) << std::endl;
std::cout << (a->remove(267)) << std::endl;
std::cout << (e->insert(203)) << std::endl;
std::cout << (a->insert(90)) << std::endl;
*b=*d;
std::cout << (b->insert(191)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
std::cout << (a->remove(118)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
std::cout << (a->remove(90)) << std::endl;
std::cout << (c->remove(244)) << std::endl;
std::cout << (e->remove(251)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
d->printPretty();
std::cout << (b->insert(316)) << std::endl;
*c=*c;
std::cout << (b->remove(454)) << std::endl;
std::cout << (b->remove(180)) << std::endl;
*e=*e;
std::cout << (a->remove(161)) << std::endl;
*b=*e;
std::cout << (d->remove(173)) << std::endl;
a->printPretty();
std::cout << (e->insert(12)) << std::endl;
*c=*a;
*d=*c;
std::cout << (a->remove(229)) << std::endl;
std::cout << (e->insert(203)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
std::cout << (e->insert(12)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
b->printPretty();
std::cout << (b->remove(12)) << std::endl;
std::cout << (e->remove(12)) << std::endl;
c->printPretty();
std::cout << (b->remove(392)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
e->printPretty();
std::cout << (c->remove(276)) << std::endl;
std::cout << (a->insert(382)) << std::endl;
std::cout << (d->remove(4)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
b->printPretty();
std::cout << (b->insert(191)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (b->remove(267)) << std::endl;
std::cout << (d->insert(245)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
a->printPretty();
std::cout << (d->remove(245)) << std::endl;
*c=*c;
std::cout << (d->insert(465)) << std::endl;
b->printPretty();
std::cout << (a->remove(30)) << std::endl;
*e=*e;
std::cout << (e->insert(468)) << std::endl;
c->printPretty();
std::cout << (d->insert(354)) << std::endl;
std::cout << (c->insert(268)) << std::endl;
std::cout << (b->remove(276)) << std::endl;
std::cout << (e->insert(460)) << std::endl;
std::cout << (c->remove(268)) << std::endl;
a->printPretty();
std::cout << (a->remove(382)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
a->printPretty();
std::cout << (a->remove(443)) << std::endl;
e->printPretty();
std::cout << (b->remove(191)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (e->remove(468)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
std::cout << (d->remove(168)) << std::endl;
std::cout << (c->insert(426)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (d->insert(303)) << std::endl;
std::cout << (e->insert(203)) << std::endl;
e->printPretty();
std::cout << (c->insert(314)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
std::cout << (e->insert(203)) << std::endl;
std::cout << (e->remove(452)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (b->remove(67)) << std::endl;
std::cout << (b->insert(229)) << std::endl;
std::cout << (e->remove(203)) << std::endl;
std::cout << (a->insert(2)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(412)) << std::endl;
std::cout << (b->remove(412)) << std::endl;
d->printPretty();
*c=*e;
a->printPretty();
std::cout << (e->insert(229)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
std::cout << (c->remove(166)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
c->printPretty();
std::cout << (a->remove(356)) << std::endl;
c->printPretty();
std::cout << (d->remove(135)) << std::endl;
e->printPretty();
d->printPretty();
d->printPretty();
a->printPretty();
std::cout << (c->insert(229)) << std::endl;
c->printPretty();
std::cout << (c->insert(229)) << std::endl;
std::cout << (d->insert(49)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
*a=*c;
std::cout << (d->insert(309)) << std::endl;
std::cout << (d->insert(227)) << std::endl;
std::cout << (e->insert(15)) << std::endl;
std::cout << (c->insert(229)) << std::endl;
std::cout << (a->insert(229)) << std::endl;
std::cout << (c->remove(97)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
std::cout << (a->insert(475)) << std::endl;
b->printPretty();
std::cout << (e->insert(15)) << std::endl;
*e=*d;
std::cout << (e->insert(405)) << std::endl;
*c=*c;
std::cout << (c->remove(168)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
*c=*c;
*d=*c;
std::cout << (b->insert(298)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (b->insert(203)) << std::endl;
std::cout << (d->remove(229)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (b->insert(282)) << std::endl;
std::cout << (d->insert(384)) << std::endl;
a->printPretty();
std::cout << (e->remove(49)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
*a=*c;
std::cout << (c->insert(229)) << std::endl;
std::cout << (c->remove(229)) << std::endl;
*c=*d;
*c=*d;
e->printPretty();
*d=*d;
std::cout << (b->insert(128)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
std::cout << (c->insert(179)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
b->printPretty();
std::cout << (a->remove(229)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
*c=*a;
std::cout << (e->insert(354)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
b->printPretty();
*e=*b;
c->printPretty();
std::cout << (b->remove(362)) << std::endl;
return 0;
}
