#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (b->remove(488)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
*b=*b;
std::cout << (b->insert(486)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*c=*a;
*c=*c;
std::cout << (b->remove(112)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (b->remove(83)) << std::endl;
std::cout << (a->remove(273)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
*a=*c;
std::cout << (d->remove(267)) << std::endl;
c->printPretty();
std::cout << (b->insert(175)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (c->insert(287)) << std::endl;
d->printPretty();
std::cout << (e->insert(266)) << std::endl;
d->printPretty();
a->printPretty();
*e=*e;
std::cout << (c->remove(287)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
std::cout << (e->insert(266)) << std::endl;
std::cout << (c->insert(449)) << std::endl;
std::cout << (e->remove(266)) << std::endl;
c->printPretty();
std::cout << (e->insert(214)) << std::endl;
std::cout << (b->insert(486)) << std::endl;
std::cout << (c->remove(256)) << std::endl;
e->printPretty();
*a=*d;
std::cout << (c->remove(44)) << std::endl;
*d=*e;
std::cout << (d->insert(214)) << std::endl;
std::cout << (c->remove(449)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (b->remove(486)) << std::endl;
std::cout << (d->insert(377)) << std::endl;
std::cout << (e->remove(54)) << std::endl;
*d=*e;
std::cout << (c->remove(137)) << std::endl;
c->printPretty();
std::cout << (b->insert(223)) << std::endl;
*d=*d;
std::cout << (e->remove(184)) << std::endl;
b->printPretty();
*b=*b;
std::cout << (e->remove(486)) << std::endl;
c->printPretty();
*b=*c;
*c=*d;
std::cout << (e->remove(214)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
*d=*e;
std::cout << (e->remove(173)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
*c=*b;
std::cout << (d->remove(406)) << std::endl;
a->printPretty();
std::cout << (a->remove(91)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
a->printPretty();
std::cout << (d->remove(285)) << std::endl;
a->printPretty();
std::cout << (e->remove(174)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
a->printPretty();
std::cout << (b->insert(465)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
*e=*d;
std::cout << (e->remove(275)) << std::endl;
*a=*b;
std::cout << (b->remove(491)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (e->remove(82)) << std::endl;
*b=*c;
d->printPretty();
*a=*e;
std::cout << (d->remove(420)) << std::endl;
*a=*d;
*d=*e;
std::cout << (c->remove(384)) << std::endl;
*e=*b;
a->printPretty();
*d=*a;
std::cout << (b->remove(327)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (c->remove(175)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
b->printPretty();
std::cout << (d->insert(347)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
*d=*d;
std::cout << (c->remove(105)) << std::endl;
std::cout << (d->insert(347)) << std::endl;
std::cout << (b->insert(454)) << std::endl;
*d=*a;
std::cout << (e->insert(110)) << std::endl;
std::cout << (e->remove(464)) << std::endl;
std::cout << (e->remove(183)) << std::endl;
std::cout << (e->remove(435)) << std::endl;
*b=*e;
*a=*b;
*b=*e;
std::cout << (e->remove(31)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->remove(386)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
*a=*c;
std::cout << (c->remove(198)) << std::endl;
std::cout << (b->remove(258)) << std::endl;
*e=*e;
std::cout << (b->insert(110)) << std::endl;
std::cout << (c->remove(175)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
std::cout << (e->remove(110)) << std::endl;
std::cout << (b->remove(110)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
a->printPretty();
*c=*c;
std::cout << (e->insert(225)) << std::endl;
std::cout << (e->insert(225)) << std::endl;
std::cout << (c->insert(351)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (c->remove(218)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->remove(175)) << std::endl;
std::cout << (b->insert(243)) << std::endl;
*a=*a;
std::cout << (e->remove(147)) << std::endl;
std::cout << (b->remove(58)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
d->printPretty();
std::cout << (b->insert(243)) << std::endl;
std::cout << (c->remove(150)) << std::endl;
std::cout << (b->remove(243)) << std::endl;
std::cout << (b->insert(78)) << std::endl;
std::cout << (a->insert(49)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
*a=*d;
*d=*c;
*e=*b;
std::cout << (d->remove(319)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
*e=*b;
a->printPretty();
e->printPretty();
std::cout << (b->insert(227)) << std::endl;
std::cout << (c->insert(319)) << std::endl;
std::cout << (c->insert(393)) << std::endl;
*e=*a;
*c=*b;
*e=*c;
*d=*c;
std::cout << (c->insert(227)) << std::endl;
std::cout << (a->remove(465)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (d->insert(227)) << std::endl;
*c=*d;
std::cout << (a->insert(227)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
std::cout << (e->remove(10)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (c->insert(409)) << std::endl;
*a=*e;
std::cout << (c->insert(409)) << std::endl;
a->printPretty();
std::cout << (b->remove(263)) << std::endl;
c->printPretty();
std::cout << (d->remove(251)) << std::endl;
*b=*e;
std::cout << (e->remove(57)) << std::endl;
*e=*d;
*e=*b;
std::cout << (d->remove(227)) << std::endl;
std::cout << (b->insert(221)) << std::endl;
std::cout << (b->remove(221)) << std::endl;
std::cout << (e->remove(227)) << std::endl;
c->printPretty();
std::cout << (e->insert(95)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
c->printPretty();
std::cout << (e->insert(95)) << std::endl;
std::cout << (c->remove(227)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
std::cout << (a->insert(227)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
b->printPretty();
std::cout << (a->insert(183)) << std::endl;
std::cout << (a->remove(183)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (e->insert(95)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
std::cout << (a->remove(72)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (d->remove(216)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
d->printPretty();
std::cout << (a->insert(282)) << std::endl;
*d=*a;
std::cout << (a->insert(12)) << std::endl;
b->printPretty();
std::cout << (a->remove(82)) << std::endl;
std::cout << (d->insert(10)) << std::endl;
std::cout << (d->remove(38)) << std::endl;
std::cout << (d->insert(31)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
std::cout << (a->insert(12)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (e->insert(95)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
*e=*c;
std::cout << (a->insert(462)) << std::endl;
*a=*e;
std::cout << (c->insert(228)) << std::endl;
a->printPretty();
std::cout << (c->remove(330)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
std::cout << (d->insert(10)) << std::endl;
std::cout << (e->insert(37)) << std::endl;
*d=*d;
std::cout << (c->insert(260)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (e->remove(200)) << std::endl;
*a=*a;
std::cout << (a->remove(397)) << std::endl;
std::cout << (b->insert(380)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
*d=*c;
std::cout << (e->insert(409)) << std::endl;
*b=*c;
*e=*d;
std::cout << (b->insert(409)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
*b=*b;
c->printPretty();
c->printPretty();
a->printPretty();
std::cout << (c->remove(155)) << std::endl;
std::cout << (d->insert(409)) << std::endl;
d->printPretty();
std::cout << (c->insert(401)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (c->remove(190)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (c->insert(228)) << std::endl;
b->printPretty();
std::cout << (c->insert(246)) << std::endl;
e->printPretty();
std::cout << (d->remove(384)) << std::endl;
e->printPretty();
d->printPretty();
*b=*b;
std::cout << (a->remove(409)) << std::endl;
*d=*d;
std::cout << (c->insert(183)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (c->remove(466)) << std::endl;
b->printPretty();
*a=*d;
*d=*e;
std::cout << (d->remove(212)) << std::endl;
b->printPretty();
std::cout << (e->insert(162)) << std::endl;
std::cout << (c->remove(228)) << std::endl;
std::cout << (a->insert(40)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (d->remove(409)) << std::endl;
std::cout << (c->insert(309)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
std::cout << (d->remove(228)) << std::endl;
*c=*e;
std::cout << (e->remove(24)) << std::endl;
std::cout << (c->insert(409)) << std::endl;
std::cout << (d->insert(188)) << std::endl;
*a=*b;
*d=*d;
std::cout << (b->insert(20)) << std::endl;
*c=*b;
std::cout << (e->insert(111)) << std::endl;
std::cout << (b->remove(228)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
*b=*a;
std::cout << (b->remove(440)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
std::cout << (c->insert(20)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (c->remove(20)) << std::endl;
d->printPretty();
std::cout << (c->insert(228)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
b->printPretty();
std::cout << (b->remove(184)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
std::cout << (e->insert(46)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
std::cout << (c->insert(490)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
std::cout << (b->remove(316)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
*a=*b;
d->printPretty();
std::cout << (a->insert(228)) << std::endl;
*c=*d;
std::cout << (c->insert(402)) << std::endl;
std::cout << (e->insert(162)) << std::endl;
*a=*c;
std::cout << (a->insert(228)) << std::endl;
e->printPretty();
std::cout << (e->insert(46)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
std::cout << (d->insert(272)) << std::endl;
std::cout << (c->remove(27)) << std::endl;
std::cout << (c->insert(188)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (e->remove(162)) << std::endl;
std::cout << (d->remove(260)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (c->insert(182)) << std::endl;
std::cout << (c->insert(40)) << std::endl;
std::cout << (b->remove(260)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (e->remove(46)) << std::endl;
std::cout << (e->remove(31)) << std::endl;
std::cout << (c->insert(182)) << std::endl;
d->printPretty();
std::cout << (d->remove(390)) << std::endl;
std::cout << (a->insert(402)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
a->printPretty();
*d=*a;
*b=*d;
std::cout << (d->remove(182)) << std::endl;
std::cout << (e->remove(130)) << std::endl;
std::cout << (d->remove(311)) << std::endl;
*e=*b;
std::cout << (a->insert(169)) << std::endl;
std::cout << (e->remove(228)) << std::endl;
b->printPretty();
std::cout << (a->remove(77)) << std::endl;
std::cout << (a->insert(402)) << std::endl;
std::cout << (d->remove(188)) << std::endl;
*c=*c;
std::cout << (a->insert(260)) << std::endl;
*e=*b;
std::cout << (d->insert(228)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
std::cout << (d->remove(3)) << std::endl;
std::cout << (e->insert(188)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
a->printPretty();
*d=*e;
b->printPretty();
std::cout << (e->insert(205)) << std::endl;
std::cout << (d->remove(383)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
std::cout << (a->remove(225)) << std::endl;
std::cout << (b->remove(188)) << std::endl;
*d=*d;
*c=*d;
std::cout << (e->insert(448)) << std::endl;
*b=*a;
*e=*d;
std::cout << (c->insert(188)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
std::cout << (d->insert(402)) << std::endl;
b->printPretty();
d->printPretty();
*d=*a;
std::cout << (c->remove(182)) << std::endl;
*c=*c;
std::cout << (e->insert(110)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
std::cout << (c->remove(228)) << std::endl;
b->printPretty();
std::cout << (d->insert(182)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
std::cout << (c->remove(137)) << std::endl;
std::cout << (a->insert(343)) << std::endl;
std::cout << (b->insert(366)) << std::endl;
*e=*e;
std::cout << (b->remove(255)) << std::endl;
std::cout << (d->remove(188)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (c->remove(260)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
std::cout << (c->insert(374)) << std::endl;
*b=*e;
*c=*e;
std::cout << (e->insert(260)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
*c=*d;
std::cout << (e->remove(127)) << std::endl;
std::cout << (d->insert(412)) << std::endl;
*e=*b;
b->printPretty();
std::cout << (c->insert(228)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
std::cout << (b->remove(437)) << std::endl;
std::cout << (d->insert(402)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
*d=*c;
c->printPretty();
a->printPretty();
std::cout << (c->remove(182)) << std::endl;
*b=*e;
std::cout << (a->remove(188)) << std::endl;
d->printPretty();
std::cout << (a->remove(270)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (a->remove(246)) << std::endl;
std::cout << (e->remove(448)) << std::endl;
std::cout << (c->insert(85)) << std::endl;
std::cout << (e->remove(188)) << std::endl;
std::cout << (e->remove(351)) << std::endl;
*b=*b;
std::cout << (a->remove(182)) << std::endl;
std::cout << (e->remove(475)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (e->remove(214)) << std::endl;
*a=*e;
*e=*a;
b->printPretty();
*b=*a;
std::cout << (a->insert(255)) << std::endl;
std::cout << (c->insert(340)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (a->insert(374)) << std::endl;
*a=*d;
std::cout << (e->remove(260)) << std::endl;
std::cout << (b->insert(377)) << std::endl;
*c=*c;
std::cout << (b->remove(260)) << std::endl;
std::cout << (a->insert(402)) << std::endl;
std::cout << (a->remove(169)) << std::endl;
std::cout << (a->insert(260)) << std::endl;
std::cout << (d->insert(228)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
*c=*e;
a->printPretty();
*a=*a;
*b=*b;
*d=*d;
std::cout << (d->remove(228)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
d->printPretty();
std::cout << (b->insert(164)) << std::endl;
d->printPretty();
std::cout << (a->remove(280)) << std::endl;
std::cout << (e->insert(494)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(325)) << std::endl;
std::cout << (e->remove(442)) << std::endl;
std::cout << (a->remove(50)) << std::endl;
*a=*e;
std::cout << (b->insert(377)) << std::endl;
*e=*a;
std::cout << (c->insert(300)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
*e=*c;
std::cout << (d->remove(182)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(28)) << std::endl;
b->printPretty();
std::cout << (e->insert(300)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (d->remove(423)) << std::endl;
*a=*c;
std::cout << (e->insert(123)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (c->remove(398)) << std::endl;
*a=*a;
d->printPretty();
std::cout << (a->insert(415)) << std::endl;
std::cout << (a->insert(453)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (b->insert(377)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
std::cout << (e->insert(325)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
std::cout << (e->remove(123)) << std::endl;
b->printPretty();
std::cout << (e->remove(300)) << std::endl;
std::cout << (d->insert(260)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (c->remove(48)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
*d=*d;
std::cout << (a->insert(453)) << std::endl;
std::cout << (c->remove(325)) << std::endl;
std::cout << (d->remove(185)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
c->printPretty();
std::cout << (d->remove(246)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (a->insert(230)) << std::endl;
std::cout << (d->insert(325)) << std::endl;
*d=*d;
std::cout << (d->remove(29)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
std::cout << (b->insert(377)) << std::endl;
d->printPretty();
std::cout << (a->remove(235)) << std::endl;
*b=*a;
std::cout << (b->insert(453)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
*b=*c;
std::cout << (e->remove(394)) << std::endl;
*a=*c;
std::cout << (b->remove(89)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (b->remove(276)) << std::endl;
std::cout << (b->insert(400)) << std::endl;
*d=*b;
std::cout << (c->remove(300)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
std::cout << (d->remove(57)) << std::endl;
std::cout << (c->insert(74)) << std::endl;
std::cout << (c->remove(252)) << std::endl;
std::cout << (b->insert(400)) << std::endl;
std::cout << (b->remove(400)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
*d=*c;
std::cout << (e->remove(232)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
std::cout << (c->remove(402)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
std::cout << (c->remove(179)) << std::endl;
*a=*b;
std::cout << (a->insert(218)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
c->printPretty();
std::cout << (a->insert(218)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (a->insert(211)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
std::cout << (c->remove(74)) << std::endl;
std::cout << (b->remove(435)) << std::endl;
*c=*e;
*a=*c;
e->printPretty();
*d=*d;
*d=*e;
std::cout << (b->insert(344)) << std::endl;
std::cout << (b->remove(90)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (e->remove(18)) << std::endl;
*a=*a;
d->printPretty();
a->printPretty();
a->printPretty();
std::cout << (c->remove(56)) << std::endl;
b->printPretty();
std::cout << (c->remove(466)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
*d=*d;
std::cout << (e->insert(56)) << std::endl;
std::cout << (b->insert(380)) << std::endl;
d->printPretty();
std::cout << (c->remove(481)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
*c=*a;
std::cout << (b->remove(81)) << std::endl;
std::cout << (a->insert(2)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (d->remove(133)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
e->printPretty();
std::cout << (a->remove(370)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
*e=*d;
std::cout << (c->remove(18)) << std::endl;
*a=*b;
std::cout << (b->insert(380)) << std::endl;
std::cout << (c->remove(56)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
*c=*e;
*d=*a;
std::cout << (c->remove(56)) << std::endl;
b->printPretty();
std::cout << (e->insert(347)) << std::endl;
std::cout << (a->remove(49)) << std::endl;
e->printPretty();
std::cout << (b->remove(429)) << std::endl;
std::cout << (d->insert(344)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
e->printPretty();
std::cout << (a->insert(395)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
std::cout << (d->insert(380)) << std::endl;
std::cout << (d->remove(8)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (b->remove(380)) << std::endl;
std::cout << (a->insert(403)) << std::endl;
std::cout << (d->remove(72)) << std::endl;
b->printPretty();
e->printPretty();
*e=*b;
std::cout << (e->remove(344)) << std::endl;
std::cout << (e->insert(482)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
std::cout << (e->remove(482)) << std::endl;
*d=*a;
std::cout << (d->insert(344)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (b->insert(344)) << std::endl;
*c=*d;
*e=*c;
e->printPretty();
std::cout << (c->insert(344)) << std::endl;
*a=*d;
std::cout << (b->remove(276)) << std::endl;
a->printPretty();
std::cout << (c->insert(344)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
*e=*e;
*a=*e;
std::cout << (e->insert(468)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
*c=*e;
*b=*b;
*a=*d;
std::cout << (c->remove(125)) << std::endl;
std::cout << (e->insert(177)) << std::endl;
std::cout << (b->insert(264)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
std::cout << (b->remove(490)) << std::endl;
d->printPretty();
std::cout << (e->remove(403)) << std::endl;
std::cout << (b->remove(495)) << std::endl;
return 0;
}
