#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*a;
std::cout << (b->insert(150)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
c->printPretty();
std::cout << (b->insert(150)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*c=*d;
*a=*b;
std::cout << (b->remove(169)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (a->insert(150)) << std::endl;
*b=*e;
std::cout << (a->remove(150)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
*b=*b;
*a=*c;
std::cout << (d->remove(500)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
std::cout << (a->remove(316)) << std::endl;
std::cout << (c->remove(413)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
*e=*d;
std::cout << (b->insert(437)) << std::endl;
e->printPretty();
*b=*a;
std::cout << (b->remove(308)) << std::endl;
std::cout << (e->remove(348)) << std::endl;
std::cout << (a->insert(327)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
std::cout << (d->insert(23)) << std::endl;
*e=*b;
*d=*a;
*a=*c;
std::cout << (e->remove(315)) << std::endl;
std::cout << (d->remove(121)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (a->remove(117)) << std::endl;
*a=*d;
std::cout << (d->remove(327)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
*a=*e;
std::cout << (b->remove(488)) << std::endl;
*c=*b;
std::cout << (c->insert(225)) << std::endl;
std::cout << (b->remove(370)) << std::endl;
*c=*e;
std::cout << (d->remove(465)) << std::endl;
*c=*e;
std::cout << (d->remove(349)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->insert(481)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (e->remove(412)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (a->insert(481)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (c->insert(115)) << std::endl;
d->printPretty();
*b=*c;
std::cout << (d->insert(180)) << std::endl;
std::cout << (b->insert(481)) << std::endl;
std::cout << (c->remove(395)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
*a=*e;
std::cout << (d->insert(180)) << std::endl;
a->printPretty();
b->printPretty();
d->printPretty();
std::cout << (c->remove(481)) << std::endl;
a->printPretty();
a->printPretty();
*c=*a;
std::cout << (a->insert(124)) << std::endl;
std::cout << (d->insert(180)) << std::endl;
*c=*b;
std::cout << (b->insert(26)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (a->insert(112)) << std::endl;
std::cout << (d->insert(180)) << std::endl;
a->printPretty();
std::cout << (b->insert(115)) << std::endl;
*a=*b;
*e=*b;
std::cout << (c->remove(115)) << std::endl;
*b=*a;
std::cout << (d->insert(180)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
std::cout << (e->insert(144)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
std::cout << (a->insert(192)) << std::endl;
std::cout << (d->remove(180)) << std::endl;
e->printPretty();
std::cout << (a->insert(284)) << std::endl;
e->printPretty();
std::cout << (b->remove(447)) << std::endl;
b->printPretty();
std::cout << (a->insert(192)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
d->printPretty();
*b=*c;
std::cout << (a->remove(463)) << std::endl;
a->printPretty();
*e=*d;
*c=*b;
*d=*c;
c->printPretty();
b->printPretty();
e->printPretty();
std::cout << (a->insert(72)) << std::endl;
std::cout << (a->remove(266)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (c->insert(87)) << std::endl;
*e=*a;
*b=*c;
d->printPretty();
std::cout << (d->remove(238)) << std::endl;
b->printPretty();
std::cout << (c->remove(465)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
*b=*e;
std::cout << (e->insert(465)) << std::endl;
*e=*d;
std::cout << (d->insert(394)) << std::endl;
std::cout << (c->remove(81)) << std::endl;
*d=*a;
std::cout << (c->insert(87)) << std::endl;
d->printPretty();
std::cout << (b->remove(269)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
std::cout << (c->insert(87)) << std::endl;
*b=*b;
*e=*c;
std::cout << (e->remove(87)) << std::endl;
std::cout << (d->insert(371)) << std::endl;
std::cout << (a->insert(312)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
std::cout << (e->remove(196)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (d->remove(371)) << std::endl;
std::cout << (e->insert(156)) << std::endl;
std::cout << (a->remove(312)) << std::endl;
*b=*e;
std::cout << (b->insert(156)) << std::endl;
std::cout << (b->remove(67)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
std::cout << (d->remove(257)) << std::endl;
c->printPretty();
std::cout << (e->insert(156)) << std::endl;
c->printPretty();
std::cout << (b->remove(156)) << std::endl;
std::cout << (a->insert(335)) << std::endl;
std::cout << (a->insert(342)) << std::endl;
c->printPretty();
std::cout << (a->remove(342)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (e->remove(112)) << std::endl;
c->printPretty();
std::cout << (d->insert(472)) << std::endl;
std::cout << (d->insert(85)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
d->printPretty();
std::cout << (c->insert(284)) << std::endl;
std::cout << (d->remove(138)) << std::endl;
std::cout << (a->remove(139)) << std::endl;
std::cout << (a->insert(236)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
std::cout << (e->insert(198)) << std::endl;
d->printPretty();
std::cout << (e->insert(116)) << std::endl;
std::cout << (a->insert(392)) << std::endl;
std::cout << (c->remove(284)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
e->printPretty();
std::cout << (a->insert(392)) << std::endl;
std::cout << (b->insert(422)) << std::endl;
b->printPretty();
d->printPretty();
*c=*c;
*d=*d;
std::cout << (a->insert(392)) << std::endl;
std::cout << (b->insert(422)) << std::endl;
std::cout << (b->insert(422)) << std::endl;
d->printPretty();
std::cout << (a->insert(162)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
*b=*a;
std::cout << (a->insert(314)) << std::endl;
e->printPretty();
std::cout << (d->insert(472)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
*b=*b;
std::cout << (d->remove(85)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
std::cout << (d->remove(160)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
std::cout << (e->remove(495)) << std::endl;
std::cout << (b->insert(236)) << std::endl;
std::cout << (a->remove(314)) << std::endl;
*c=*b;
std::cout << (a->remove(392)) << std::endl;
*a=*a;
std::cout << (b->remove(162)) << std::endl;
std::cout << (b->remove(367)) << std::endl;
std::cout << (c->remove(67)) << std::endl;
std::cout << (e->remove(134)) << std::endl;
std::cout << (b->remove(353)) << std::endl;
a->printPretty();
std::cout << (b->insert(305)) << std::endl;
b->printPretty();
*c=*d;
*c=*d;
std::cout << (b->remove(377)) << std::endl;
a->printPretty();
std::cout << (b->remove(236)) << std::endl;
std::cout << (e->insert(116)) << std::endl;
e->printPretty();
e->printPretty();
*c=*c;
std::cout << (e->remove(116)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
a->printPretty();
std::cout << (a->insert(407)) << std::endl;
*b=*e;
a->printPretty();
b->printPretty();
std::cout << (d->insert(434)) << std::endl;
std::cout << (d->insert(434)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
a->printPretty();
std::cout << (d->remove(434)) << std::endl;
std::cout << (c->remove(143)) << std::endl;
std::cout << (d->insert(105)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
a->printPretty();
std::cout << (a->insert(236)) << std::endl;
*b=*d;
std::cout << (b->remove(105)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (e->insert(354)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
*c=*a;
std::cout << (c->insert(236)) << std::endl;
d->printPretty();
c->printPretty();
e->printPretty();
std::cout << (a->insert(236)) << std::endl;
std::cout << (d->insert(308)) << std::endl;
d->printPretty();
*e=*c;
a->printPretty();
a->printPretty();
std::cout << (d->remove(105)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(279)) << std::endl;
e->printPretty();
std::cout << (b->insert(279)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (c->insert(115)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (e->insert(370)) << std::endl;
std::cout << (d->insert(73)) << std::endl;
*b=*c;
std::cout << (d->insert(407)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
std::cout << (c->insert(279)) << std::endl;
std::cout << (a->insert(119)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
*e=*a;
std::cout << (e->remove(162)) << std::endl;
std::cout << (d->insert(349)) << std::endl;
b->printPretty();
std::cout << (c->insert(279)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
b->printPretty();
std::cout << (a->insert(495)) << std::endl;
std::cout << (d->insert(349)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (e->remove(115)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (e->insert(407)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
*b=*b;
std::cout << (b->insert(485)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
d->printPretty();
std::cout << (b->remove(485)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
d->printPretty();
std::cout << (d->insert(163)) << std::endl;
std::cout << (a->insert(122)) << std::endl;
*d=*a;
c->printPretty();
std::cout << (c->insert(279)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
std::cout << (b->remove(426)) << std::endl;
c->printPretty();
std::cout << (a->remove(162)) << std::endl;
*b=*c;
std::cout << (a->remove(122)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
std::cout << (d->insert(495)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (e->insert(219)) << std::endl;
b->printPretty();
std::cout << (d->insert(295)) << std::endl;
*c=*b;
std::cout << (c->remove(33)) << std::endl;
std::cout << (a->insert(207)) << std::endl;
std::cout << (a->remove(142)) << std::endl;
std::cout << (d->remove(122)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
*a=*a;
std::cout << (e->insert(236)) << std::endl;
std::cout << (a->remove(495)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
std::cout << (d->insert(270)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
std::cout << (c->remove(316)) << std::endl;
d->printPretty();
std::cout << (a->insert(300)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (a->insert(119)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
e->printPretty();
std::cout << (d->insert(342)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
std::cout << (b->insert(316)) << std::endl;
e->printPretty();
std::cout << (d->remove(270)) << std::endl;
std::cout << (b->remove(173)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
std::cout << (e->insert(433)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
std::cout << (e->insert(160)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
std::cout << (b->insert(159)) << std::endl;
std::cout << (a->insert(300)) << std::endl;
*b=*c;
*b=*b;
e->printPretty();
std::cout << (a->insert(209)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (b->insert(450)) << std::endl;
std::cout << (e->remove(12)) << std::endl;
*e=*b;
std::cout << (b->remove(370)) << std::endl;
b->printPretty();
std::cout << (d->insert(24)) << std::endl;
*d=*c;
std::cout << (c->insert(369)) << std::endl;
*d=*b;
std::cout << (b->remove(450)) << std::endl;
c->printPretty();
*b=*c;
*a=*b;
*a=*a;
std::cout << (a->remove(23)) << std::endl;
std::cout << (d->remove(23)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (e->remove(23)) << std::endl;
std::cout << (e->insert(500)) << std::endl;
a->printPretty();
std::cout << (e->remove(454)) << std::endl;
std::cout << (c->remove(471)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
std::cout << (a->remove(369)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
std::cout << (c->insert(369)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->remove(450)) << std::endl;
std::cout << (a->insert(32)) << std::endl;
*d=*e;
*d=*b;
std::cout << (c->remove(369)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->remove(32)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
std::cout << (c->remove(456)) << std::endl;
c->printPretty();
*a=*a;
std::cout << (c->remove(23)) << std::endl;
std::cout << (c->insert(349)) << std::endl;
e->printPretty();
std::cout << (b->insert(332)) << std::endl;
std::cout << (c->remove(27)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
c->printPretty();
std::cout << (c->remove(349)) << std::endl;
*b=*d;
std::cout << (c->insert(167)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
std::cout << (e->insert(490)) << std::endl;
*e=*e;
std::cout << (b->remove(361)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
*e=*d;
std::cout << (d->insert(330)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
std::cout << (d->insert(409)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
std::cout << (e->remove(382)) << std::endl;
std::cout << (d->insert(364)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
*d=*c;
std::cout << (e->insert(259)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
std::cout << (e->insert(23)) << std::endl;
*b=*d;
*c=*a;
*a=*a;
std::cout << (c->insert(256)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
*e=*a;
std::cout << (a->remove(448)) << std::endl;
*e=*e;
*d=*a;
std::cout << (e->remove(437)) << std::endl;
std::cout << (e->remove(270)) << std::endl;
std::cout << (d->insert(256)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
*b=*d;
*b=*a;
std::cout << (a->insert(381)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (c->insert(472)) << std::endl;
std::cout << (d->remove(276)) << std::endl;
*e=*e;
std::cout << (d->insert(256)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
std::cout << (c->insert(256)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
std::cout << (b->remove(256)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
c->printPretty();
std::cout << (c->insert(256)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
d->printPretty();
std::cout << (b->insert(127)) << std::endl;
*d=*a;
c->printPretty();
std::cout << (b->insert(127)) << std::endl;
std::cout << (b->remove(474)) << std::endl;
std::cout << (d->remove(256)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (e->remove(381)) << std::endl;
std::cout << (d->remove(381)) << std::endl;
a->printPretty();
*d=*d;
std::cout << (a->remove(381)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
std::cout << (d->remove(361)) << std::endl;
std::cout << (c->insert(57)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
d->printPretty();
*c=*a;
*d=*d;
std::cout << (c->remove(122)) << std::endl;
std::cout << (a->remove(382)) << std::endl;
std::cout << (a->insert(256)) << std::endl;
e->printPretty();
std::cout << (b->insert(127)) << std::endl;
std::cout << (b->remove(127)) << std::endl;
std::cout << (a->insert(347)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
e->printPretty();
*c=*e;
*a=*a;
*a=*d;
*a=*e;
std::cout << (b->insert(342)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (c->insert(7)) << std::endl;
std::cout << (e->insert(49)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
c->printPretty();
std::cout << (e->insert(49)) << std::endl;
std::cout << (c->insert(7)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(7)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
d->printPretty();
*a=*d;
d->printPretty();
std::cout << (c->insert(62)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->remove(258)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
*b=*a;
e->printPretty();
*d=*e;
std::cout << (b->remove(478)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
std::cout << (d->remove(49)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (b->insert(92)) << std::endl;
std::cout << (d->insert(367)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
a->printPretty();
*a=*d;
e->printPretty();
std::cout << (a->remove(141)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
*a=*b;
std::cout << (b->remove(182)) << std::endl;
c->printPretty();
std::cout << (b->insert(264)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (d->insert(90)) << std::endl;
e->printPretty();
std::cout << (d->insert(166)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (e->insert(182)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
c->printPretty();
std::cout << (d->insert(115)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
c->printPretty();
std::cout << (e->insert(152)) << std::endl;
d->printPretty();
std::cout << (d->insert(367)) << std::endl;
std::cout << (d->insert(281)) << std::endl;
std::cout << (a->remove(382)) << std::endl;
std::cout << (e->insert(195)) << std::endl;
std::cout << (d->insert(115)) << std::endl;
std::cout << (a->remove(92)) << std::endl;
std::cout << (c->insert(175)) << std::endl;
*e=*b;
std::cout << (c->insert(61)) << std::endl;
std::cout << (d->remove(42)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
*a=*a;
*d=*a;
std::cout << (a->remove(100)) << std::endl;
std::cout << (e->remove(140)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (c->insert(175)) << std::endl;
std::cout << (b->insert(83)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
b->printPretty();
*b=*a;
std::cout << (c->remove(320)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(92)) << std::endl;
std::cout << (e->insert(431)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
std::cout << (a->remove(365)) << std::endl;
std::cout << (a->insert(203)) << std::endl;
*c=*d;
std::cout << (e->remove(431)) << std::endl;
*d=*d;
*a=*d;
std::cout << (c->remove(223)) << std::endl;
std::cout << (e->remove(269)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (d->remove(453)) << std::endl;
a->printPretty();
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->insert(270)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (e->remove(234)) << std::endl;
std::cout << (d->remove(309)) << std::endl;
b->printPretty();
std::cout << (e->insert(257)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
std::cout << (b->remove(40)) << std::endl;
std::cout << (d->remove(101)) << std::endl;
std::cout << (a->insert(407)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (d->insert(251)) << std::endl;
std::cout << (b->remove(392)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->remove(251)) << std::endl;
*d=*d;
*c=*a;
std::cout << (d->insert(138)) << std::endl;
std::cout << (c->insert(407)) << std::endl;
std::cout << (d->insert(138)) << std::endl;
std::cout << (d->remove(138)) << std::endl;
a->printPretty();
*c=*b;
std::cout << (d->insert(370)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (b->insert(330)) << std::endl;
std::cout << (b->remove(330)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(332)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
*b=*b;
std::cout << (a->insert(489)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
c->printPretty();
std::cout << (e->remove(415)) << std::endl;
std::cout << (b->insert(301)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (a->remove(407)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
std::cout << (e->insert(128)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (e->remove(128)) << std::endl;
e->printPretty();
std::cout << (b->insert(77)) << std::endl;
return 0;
}
