#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(108)) << std::endl;
a->printPretty();
std::cout << (a->remove(108)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
std::cout << (b->remove(264)) << std::endl;
std::cout << (c->insert(132)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (c->remove(345)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
c->printPretty();
std::cout << (b->insert(144)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
*c=*b;
std::cout << (b->remove(144)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
e->printPretty();
*d=*e;
b->printPretty();
*c=*a;
*c=*a;
*c=*b;
std::cout << (b->insert(146)) << std::endl;
std::cout << (c->remove(465)) << std::endl;
std::cout << (a->insert(202)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->insert(202)) << std::endl;
std::cout << (b->insert(146)) << std::endl;
std::cout << (b->remove(195)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->insert(11)) << std::endl;
d->printPretty();
*c=*a;
*b=*b;
std::cout << (b->insert(146)) << std::endl;
std::cout << (a->insert(202)) << std::endl;
b->printPretty();
std::cout << (d->remove(448)) << std::endl;
*d=*d;
*b=*e;
e->printPretty();
std::cout << (b->remove(314)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
b->printPretty();
std::cout << (d->insert(263)) << std::endl;
e->printPretty();
b->printPretty();
d->printPretty();
std::cout << (a->insert(270)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
std::cout << (c->insert(136)) << std::endl;
*a=*c;
std::cout << (d->insert(318)) << std::endl;
std::cout << (c->insert(270)) << std::endl;
std::cout << (d->remove(27)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
c->printPretty();
std::cout << (b->remove(467)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
*b=*e;
*d=*a;
std::cout << (a->insert(136)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
*a=*d;
std::cout << (a->remove(136)) << std::endl;
std::cout << (a->remove(217)) << std::endl;
d->printPretty();
std::cout << (b->insert(9)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (b->remove(9)) << std::endl;
std::cout << (e->remove(136)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
b->printPretty();
std::cout << (a->insert(184)) << std::endl;
c->printPretty();
std::cout << (c->insert(479)) << std::endl;
*c=*c;
d->printPretty();
std::cout << (e->insert(479)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
*b=*e;
*d=*e;
std::cout << (c->remove(288)) << std::endl;
c->printPretty();
e->printPretty();
*a=*d;
std::cout << (e->remove(479)) << std::endl;
c->printPretty();
std::cout << (d->remove(270)) << std::endl;
d->printPretty();
std::cout << (e->remove(202)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
std::cout << (c->remove(132)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
std::cout << (d->remove(174)) << std::endl;
*a=*b;
std::cout << (d->insert(4)) << std::endl;
*d=*e;
*c=*a;
std::cout << (d->remove(50)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
*d=*c;
std::cout << (a->insert(202)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
*e=*c;
std::cout << (a->remove(202)) << std::endl;
std::cout << (a->insert(369)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
*c=*b;
e->printPretty();
*a=*c;
std::cout << (b->insert(267)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
*a=*a;
std::cout << (c->insert(239)) << std::endl;
std::cout << (d->insert(202)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
std::cout << (e->remove(237)) << std::endl;
std::cout << (e->remove(426)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
*c=*e;
std::cout << (b->insert(479)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
d->printPretty();
std::cout << (c->remove(270)) << std::endl;
std::cout << (c->remove(375)) << std::endl;
std::cout << (a->insert(239)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
b->printPretty();
std::cout << (a->remove(202)) << std::endl;
a->printPretty();
std::cout << (a->remove(479)) << std::endl;
d->printPretty();
*c=*e;
std::cout << (c->insert(270)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
std::cout << (a->remove(270)) << std::endl;
std::cout << (e->remove(334)) << std::endl;
std::cout << (d->insert(238)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->remove(239)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
std::cout << (e->remove(202)) << std::endl;
std::cout << (a->insert(239)) << std::endl;
*c=*d;
std::cout << (d->insert(238)) << std::endl;
std::cout << (b->remove(267)) << std::endl;
std::cout << (e->insert(131)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
*b=*a;
std::cout << (d->insert(479)) << std::endl;
std::cout << (d->remove(20)) << std::endl;
d->printPretty();
std::cout << (d->insert(247)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
std::cout << (c->remove(175)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
std::cout << (d->remove(462)) << std::endl;
e->printPretty();
std::cout << (b->remove(68)) << std::endl;
c->printPretty();
d->printPretty();
a->printPretty();
std::cout << (d->insert(239)) << std::endl;
std::cout << (d->remove(41)) << std::endl;
a->printPretty();
*d=*e;
std::cout << (e->remove(109)) << std::endl;
std::cout << (c->insert(270)) << std::endl;
std::cout << (e->insert(270)) << std::endl;
std::cout << (b->insert(233)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (e->remove(239)) << std::endl;
*d=*a;
a->printPretty();
d->printPretty();
std::cout << (b->remove(233)) << std::endl;
*c=*a;
*d=*e;
*c=*c;
std::cout << (d->insert(33)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (c->insert(352)) << std::endl;
c->printPretty();
std::cout << (c->insert(300)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
a->printPretty();
d->printPretty();
d->printPretty();
std::cout << (a->insert(179)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
std::cout << (d->insert(231)) << std::endl;
std::cout << (d->remove(285)) << std::endl;
std::cout << (c->remove(350)) << std::endl;
std::cout << (d->remove(33)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
d->printPretty();
std::cout << (b->insert(251)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
*b=*a;
std::cout << (d->remove(131)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (b->insert(179)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (a->remove(179)) << std::endl;
std::cout << (c->insert(66)) << std::endl;
*d=*d;
std::cout << (d->remove(231)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
std::cout << (e->remove(193)) << std::endl;
*d=*c;
std::cout << (b->insert(417)) << std::endl;
*d=*a;
std::cout << (a->insert(135)) << std::endl;
e->printPretty();
std::cout << (b->remove(417)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
*c=*d;
std::cout << (e->insert(231)) << std::endl;
std::cout << (c->remove(397)) << std::endl;
std::cout << (c->remove(301)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
std::cout << (a->insert(176)) << std::endl;
std::cout << (d->remove(397)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
*b=*e;
c->printPretty();
std::cout << (c->remove(78)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
std::cout << (e->insert(351)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (a->remove(457)) << std::endl;
std::cout << (a->remove(345)) << std::endl;
*a=*b;
*e=*b;
*e=*a;
std::cout << (d->remove(78)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (d->remove(367)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
*e=*e;
std::cout << (b->remove(483)) << std::endl;
std::cout << (c->insert(270)) << std::endl;
c->printPretty();
std::cout << (e->remove(270)) << std::endl;
std::cout << (b->insert(166)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
*c=*a;
std::cout << (b->insert(231)) << std::endl;
c->printPretty();
std::cout << (c->insert(479)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
*e=*e;
std::cout << (c->insert(198)) << std::endl;
std::cout << (b->remove(166)) << std::endl;
std::cout << (b->insert(223)) << std::endl;
*d=*c;
std::cout << (e->insert(311)) << std::endl;
std::cout << (a->insert(379)) << std::endl;
std::cout << (e->remove(231)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (a->remove(490)) << std::endl;
*d=*d;
std::cout << (d->insert(264)) << std::endl;
*a=*d;
std::cout << (c->remove(479)) << std::endl;
std::cout << (c->insert(429)) << std::endl;
std::cout << (b->insert(465)) << std::endl;
*c=*d;
std::cout << (e->insert(225)) << std::endl;
b->printPretty();
std::cout << (c->insert(191)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (e->insert(281)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
*a=*e;
std::cout << (d->remove(479)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
*a=*c;
std::cout << (c->remove(191)) << std::endl;
d->printPretty();
std::cout << (b->insert(223)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (e->remove(359)) << std::endl;
*d=*c;
std::cout << (e->remove(475)) << std::endl;
*b=*a;
std::cout << (a->remove(167)) << std::endl;
a->printPretty();
std::cout << (a->remove(270)) << std::endl;
*c=*e;
std::cout << (e->insert(223)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (b->insert(430)) << std::endl;
d->printPretty();
std::cout << (b->remove(479)) << std::endl;
std::cout << (c->remove(128)) << std::endl;
a->printPretty();
std::cout << (c->insert(479)) << std::endl;
e->printPretty();
*a=*c;
b->printPretty();
d->printPretty();
std::cout << (c->insert(7)) << std::endl;
std::cout << (e->remove(270)) << std::endl;
std::cout << (d->insert(353)) << std::endl;
std::cout << (d->remove(124)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
c->printPretty();
*c=*b;
std::cout << (e->remove(291)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(231)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (c->insert(430)) << std::endl;
std::cout << (c->remove(430)) << std::endl;
*b=*a;
std::cout << (c->remove(223)) << std::endl;
std::cout << (c->insert(35)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
b->printPretty();
*e=*b;
*b=*c;
std::cout << (c->remove(478)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
*c=*c;
d->printPretty();
*d=*b;
std::cout << (b->remove(35)) << std::endl;
std::cout << (a->remove(479)) << std::endl;
std::cout << (a->remove(327)) << std::endl;
a->printPretty();
c->printPretty();
*c=*b;
std::cout << (e->remove(231)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
std::cout << (b->remove(193)) << std::endl;
std::cout << (c->insert(219)) << std::endl;
*a=*c;
std::cout << (d->remove(323)) << std::endl;
*b=*e;
std::cout << (c->remove(431)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (e->remove(55)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
std::cout << (e->remove(223)) << std::endl;
std::cout << (a->insert(233)) << std::endl;
b->printPretty();
*d=*b;
b->printPretty();
std::cout << (b->remove(60)) << std::endl;
*b=*d;
*b=*d;
a->printPretty();
std::cout << (e->insert(479)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (a->insert(330)) << std::endl;
*a=*d;
*a=*e;
std::cout << (d->insert(479)) << std::endl;
*a=*b;
std::cout << (b->insert(426)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
a->printPretty();
std::cout << (d->remove(479)) << std::endl;
std::cout << (a->remove(198)) << std::endl;
std::cout << (d->insert(278)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
a->printPretty();
std::cout << (d->insert(27)) << std::endl;
c->printPretty();
std::cout << (c->insert(451)) << std::endl;
*b=*d;
std::cout << (b->insert(137)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
*c=*d;
std::cout << (d->remove(12)) << std::endl;
std::cout << (a->remove(35)) << std::endl;
std::cout << (b->remove(278)) << std::endl;
b->printPretty();
std::cout << (e->remove(119)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
c->printPretty();
*a=*e;
std::cout << (e->insert(479)) << std::endl;
e->printPretty();
*d=*a;
std::cout << (a->insert(270)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
b->printPretty();
*a=*b;
std::cout << (a->insert(27)) << std::endl;
std::cout << (a->remove(137)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
std::cout << (e->remove(479)) << std::endl;
c->printPretty();
std::cout << (e->remove(471)) << std::endl;
std::cout << (d->insert(441)) << std::endl;
*d=*c;
std::cout << (b->insert(226)) << std::endl;
std::cout << (a->insert(27)) << std::endl;
a->printPretty();
std::cout << (b->insert(201)) << std::endl;
std::cout << (e->insert(113)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
std::cout << (e->remove(371)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(201)) << std::endl;
*e=*e;
std::cout << (c->insert(27)) << std::endl;
std::cout << (b->remove(447)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (d->remove(27)) << std::endl;
*a=*c;
std::cout << (a->remove(27)) << std::endl;
b->printPretty();
std::cout << (b->insert(226)) << std::endl;
*d=*d;
std::cout << (e->insert(180)) << std::endl;
*e=*b;
*b=*c;
std::cout << (c->insert(27)) << std::endl;
*e=*e;
std::cout << (b->insert(60)) << std::endl;
e->printPretty();
std::cout << (b->remove(332)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
*a=*a;
std::cout << (a->insert(379)) << std::endl;
c->printPretty();
std::cout << (c->insert(474)) << std::endl;
std::cout << (b->insert(27)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
std::cout << (c->remove(474)) << std::endl;
std::cout << (b->remove(55)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
std::cout << (c->insert(35)) << std::endl;
std::cout << (b->remove(60)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (a->remove(316)) << std::endl;
a->printPretty();
std::cout << (a->remove(379)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
std::cout << (d->remove(59)) << std::endl;
std::cout << (a->remove(201)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
*b=*b;
std::cout << (c->remove(35)) << std::endl;
*b=*e;
std::cout << (c->insert(27)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->insert(140)) << std::endl;
b->printPretty();
std::cout << (b->insert(140)) << std::endl;
std::cout << (c->insert(236)) << std::endl;
std::cout << (c->insert(297)) << std::endl;
std::cout << (e->remove(403)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
std::cout << (e->remove(261)) << std::endl;
b->printPretty();
e->printPretty();
e->printPretty();
std::cout << (c->remove(27)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
e->printPretty();
std::cout << (d->insert(97)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (a->insert(410)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
c->printPretty();
std::cout << (d->insert(67)) << std::endl;
*e=*e;
std::cout << (a->insert(289)) << std::endl;
std::cout << (a->insert(450)) << std::endl;
*d=*d;
b->printPretty();
std::cout << (c->insert(324)) << std::endl;
d->printPretty();
std::cout << (a->remove(289)) << std::endl;
std::cout << (d->remove(67)) << std::endl;
std::cout << (b->remove(261)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
*b=*a;
*a=*b;
std::cout << (c->insert(201)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(137)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
std::cout << (b->insert(388)) << std::endl;
*a=*b;
*b=*c;
std::cout << (b->insert(342)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
d->printPretty();
std::cout << (d->remove(132)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->remove(324)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
*b=*b;
std::cout << (a->insert(55)) << std::endl;
*e=*c;
std::cout << (c->insert(137)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
std::cout << (e->insert(131)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (a->insert(44)) << std::endl;
std::cout << (e->insert(42)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
std::cout << (a->remove(410)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
std::cout << (e->remove(137)) << std::endl;
std::cout << (e->insert(346)) << std::endl;
*e=*e;
std::cout << (d->remove(401)) << std::endl;
std::cout << (b->remove(28)) << std::endl;
std::cout << (a->insert(178)) << std::endl;
std::cout << (a->remove(55)) << std::endl;
*e=*a;
std::cout << (d->insert(350)) << std::endl;
std::cout << (b->insert(398)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
std::cout << (b->insert(324)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
std::cout << (c->remove(137)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
std::cout << (c->insert(28)) << std::endl;
std::cout << (b->remove(201)) << std::endl;
e->printPretty();
std::cout << (c->remove(104)) << std::endl;
*e=*d;
std::cout << (e->insert(350)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
*b=*e;
std::cout << (a->remove(178)) << std::endl;
*e=*a;
std::cout << (c->remove(201)) << std::endl;
std::cout << (d->insert(271)) << std::endl;
std::cout << (d->remove(195)) << std::endl;
std::cout << (b->insert(132)) << std::endl;
c->printPretty();
std::cout << (d->remove(297)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
std::cout << (c->insert(71)) << std::endl;
std::cout << (b->insert(350)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (d->remove(271)) << std::endl;
std::cout << (b->remove(186)) << std::endl;
std::cout << (e->remove(44)) << std::endl;
*e=*c;
*c=*a;
std::cout << (e->remove(33)) << std::endl;
*b=*a;
std::cout << (b->insert(456)) << std::endl;
*b=*a;
std::cout << (c->remove(213)) << std::endl;
*b=*e;
e->printPretty();
std::cout << (c->insert(482)) << std::endl;
std::cout << (b->insert(70)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (a->remove(415)) << std::endl;
d->printPretty();
std::cout << (a->insert(408)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->insert(34)) << std::endl;
*a=*c;
std::cout << (d->insert(350)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
std::cout << (b->insert(450)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
std::cout << (a->insert(464)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (b->insert(79)) << std::endl;
std::cout << (d->remove(364)) << std::endl;
*c=*a;
*c=*b;
std::cout << (e->insert(414)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
*e=*b;
std::cout << (b->remove(79)) << std::endl;
*a=*c;
std::cout << (a->insert(130)) << std::endl;
d->printPretty();
std::cout << (e->insert(79)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (a->remove(450)) << std::endl;
*e=*b;
std::cout << (b->remove(270)) << std::endl;
e->printPretty();
std::cout << (b->insert(183)) << std::endl;
*b=*d;
b->printPretty();
*c=*b;
std::cout << (a->remove(70)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
std::cout << (b->remove(350)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (b->remove(398)) << std::endl;
std::cout << (e->insert(262)) << std::endl;
*d=*e;
std::cout << (d->remove(155)) << std::endl;
*e=*e;
std::cout << (e->remove(143)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
std::cout << (e->insert(205)) << std::endl;
a->printPretty();
std::cout << (a->insert(401)) << std::endl;
std::cout << (e->remove(187)) << std::endl;
e->printPretty();
std::cout << (d->remove(466)) << std::endl;
std::cout << (d->remove(262)) << std::endl;
std::cout << (d->remove(6)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
d->printPretty();
std::cout << (a->insert(314)) << std::endl;
std::cout << (b->insert(377)) << std::endl;
std::cout << (a->insert(388)) << std::endl;
*e=*a;
*d=*a;
std::cout << (c->insert(187)) << std::endl;
e->printPretty();
std::cout << (b->insert(157)) << std::endl;
std::cout << (a->remove(388)) << std::endl;
std::cout << (a->insert(314)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
*c=*d;
return 0;
}
