#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->insert(6)) << std::endl;
*b=*a;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->remove(365)) << std::endl;
std::cout << (c->remove(151)) << std::endl;
*b=*b;
std::cout << (a->remove(456)) << std::endl;
*a=*a;
*b=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (d->remove(148)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
d->printPretty();
std::cout << (c->insert(490)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
std::cout << (b->remove(471)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
*c=*a;
std::cout << (a->insert(275)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
*e=*e;
*a=*d;
std::cout << (e->insert(467)) << std::endl;
std::cout << (a->remove(415)) << std::endl;
std::cout << (e->remove(20)) << std::endl;
*d=*d;
std::cout << (c->remove(414)) << std::endl;
b->printPretty();
std::cout << (e->insert(467)) << std::endl;
std::cout << (b->insert(362)) << std::endl;
*c=*b;
std::cout << (b->remove(362)) << std::endl;
std::cout << (b->remove(70)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
d->printPretty();
std::cout << (a->insert(77)) << std::endl;
std::cout << (d->remove(349)) << std::endl;
std::cout << (c->insert(186)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
d->printPretty();
std::cout << (c->remove(187)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
std::cout << (c->remove(362)) << std::endl;
std::cout << (d->remove(474)) << std::endl;
std::cout << (b->remove(294)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
std::cout << (b->remove(414)) << std::endl;
*d=*a;
std::cout << (a->remove(351)) << std::endl;
std::cout << (c->insert(270)) << std::endl;
*c=*d;
std::cout << (c->remove(329)) << std::endl;
c->printPretty();
std::cout << (d->remove(255)) << std::endl;
*c=*c;
*a=*c;
*e=*b;
b->printPretty();
e->printPretty();
c->printPretty();
*d=*a;
std::cout << (d->insert(164)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
*c=*b;
std::cout << (e->remove(84)) << std::endl;
*d=*b;
*c=*d;
std::cout << (b->insert(295)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
b->printPretty();
std::cout << (e->remove(496)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
*e=*c;
std::cout << (a->insert(268)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (b->remove(102)) << std::endl;
*d=*e;
std::cout << (a->insert(268)) << std::endl;
c->printPretty();
std::cout << (a->insert(282)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
std::cout << (b->remove(295)) << std::endl;
*e=*c;
std::cout << (a->remove(85)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
std::cout << (c->remove(244)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
std::cout << (e->remove(197)) << std::endl;
std::cout << (a->remove(19)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->insert(283)) << std::endl;
c->printPretty();
std::cout << (c->remove(331)) << std::endl;
std::cout << (a->remove(11)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
std::cout << (b->insert(368)) << std::endl;
c->printPretty();
std::cout << (b->insert(368)) << std::endl;
d->printPretty();
*c=*b;
b->printPretty();
std::cout << (a->insert(228)) << std::endl;
std::cout << (b->insert(214)) << std::endl;
std::cout << (b->remove(368)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
std::cout << (d->insert(132)) << std::endl;
std::cout << (e->insert(455)) << std::endl;
std::cout << (c->insert(368)) << std::endl;
*c=*c;
std::cout << (e->insert(455)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
*b=*c;
std::cout << (e->insert(455)) << std::endl;
a->printPretty();
*a=*a;
std::cout << (e->remove(23)) << std::endl;
std::cout << (d->insert(10)) << std::endl;
std::cout << (d->remove(88)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
c->printPretty();
std::cout << (a->remove(268)) << std::endl;
std::cout << (d->remove(132)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
*b=*a;
std::cout << (c->remove(253)) << std::endl;
std::cout << (a->insert(148)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
std::cout << (b->remove(27)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
std::cout << (c->remove(10)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
d->printPretty();
std::cout << (d->remove(325)) << std::endl;
std::cout << (a->remove(121)) << std::endl;
*b=*d;
*c=*a;
std::cout << (a->remove(148)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->remove(340)) << std::endl;
*d=*c;
c->printPretty();
std::cout << (c->insert(148)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (a->insert(263)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (e->insert(372)) << std::endl;
std::cout << (c->remove(156)) << std::endl;
std::cout << (d->remove(228)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
d->printPretty();
std::cout << (a->insert(156)) << std::endl;
std::cout << (e->insert(285)) << std::endl;
std::cout << (e->remove(372)) << std::endl;
std::cout << (a->remove(156)) << std::endl;
std::cout << (a->remove(263)) << std::endl;
std::cout << (b->insert(10)) << std::endl;
*b=*e;
*e=*c;
*a=*e;
std::cout << (e->remove(148)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
*e=*d;
std::cout << (b->remove(285)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
std::cout << (a->remove(419)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
std::cout << (d->insert(277)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
std::cout << (c->insert(189)) << std::endl;
std::cout << (c->remove(476)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
*c=*a;
b->printPretty();
std::cout << (a->insert(148)) << std::endl;
*b=*c;
*a=*e;
d->printPretty();
std::cout << (a->remove(148)) << std::endl;
c->printPretty();
std::cout << (b->remove(228)) << std::endl;
std::cout << (e->insert(391)) << std::endl;
std::cout << (d->insert(7)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
*c=*b;
std::cout << (d->remove(413)) << std::endl;
*c=*c;
std::cout << (e->remove(154)) << std::endl;
std::cout << (c->remove(145)) << std::endl;
*d=*a;
std::cout << (c->insert(316)) << std::endl;
*c=*a;
std::cout << (e->insert(280)) << std::endl;
std::cout << (e->insert(83)) << std::endl;
*d=*b;
std::cout << (a->remove(351)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
e->printPretty();
std::cout << (e->remove(391)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (a->remove(322)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
*e=*e;
std::cout << (d->insert(452)) << std::endl;
std::cout << (b->insert(364)) << std::endl;
std::cout << (d->insert(93)) << std::endl;
e->printPretty();
*e=*c;
*b=*c;
std::cout << (d->insert(452)) << std::endl;
a->printPretty();
std::cout << (a->insert(93)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
std::cout << (d->insert(402)) << std::endl;
*d=*e;
std::cout << (e->insert(322)) << std::endl;
d->printPretty();
std::cout << (d->remove(12)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (a->insert(93)) << std::endl;
e->printPretty();
std::cout << (a->insert(224)) << std::endl;
std::cout << (c->remove(344)) << std::endl;
d->printPretty();
e->printPretty();
*e=*c;
*a=*d;
*a=*b;
b->printPretty();
std::cout << (e->remove(173)) << std::endl;
std::cout << (b->remove(273)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->remove(322)) << std::endl;
std::cout << (a->remove(392)) << std::endl;
std::cout << (e->remove(303)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (e->insert(459)) << std::endl;
std::cout << (d->insert(187)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (e->remove(65)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
d->printPretty();
std::cout << (b->remove(265)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (a->insert(471)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
d->printPretty();
std::cout << (d->insert(379)) << std::endl;
std::cout << (a->remove(322)) << std::endl;
*c=*e;
std::cout << (a->remove(471)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
*e=*d;
std::cout << (d->insert(112)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
*c=*c;
*e=*b;
std::cout << (d->remove(215)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (e->insert(460)) << std::endl;
std::cout << (b->insert(119)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
std::cout << (a->insert(280)) << std::endl;
std::cout << (c->insert(287)) << std::endl;
std::cout << (b->remove(325)) << std::endl;
c->printPretty();
std::cout << (b->insert(119)) << std::endl;
*e=*d;
*a=*d;
*a=*e;
a->printPretty();
std::cout << (a->insert(386)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
std::cout << (c->insert(252)) << std::endl;
*d=*a;
*b=*d;
std::cout << (e->insert(72)) << std::endl;
*b=*b;
b->printPretty();
d->printPretty();
std::cout << (d->remove(189)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
*a=*c;
std::cout << (c->remove(94)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
std::cout << (d->insert(104)) << std::endl;
std::cout << (c->remove(252)) << std::endl;
std::cout << (c->remove(385)) << std::endl;
d->printPretty();
std::cout << (a->insert(171)) << std::endl;
std::cout << (d->insert(379)) << std::endl;
std::cout << (b->insert(294)) << std::endl;
*b=*e;
c->printPretty();
std::cout << (d->remove(292)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
std::cout << (c->remove(287)) << std::endl;
std::cout << (a->remove(151)) << std::endl;
*b=*b;
std::cout << (b->remove(72)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (d->insert(444)) << std::endl;
*c=*a;
std::cout << (d->insert(104)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (b->remove(294)) << std::endl;
std::cout << (e->remove(147)) << std::endl;
std::cout << (c->remove(154)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (b->remove(112)) << std::endl;
a->printPretty();
std::cout << (e->insert(112)) << std::endl;
*d=*c;
*a=*e;
d->printPretty();
std::cout << (d->remove(491)) << std::endl;
*a=*c;
std::cout << (a->insert(287)) << std::endl;
a->printPretty();
std::cout << (c->remove(87)) << std::endl;
a->printPretty();
std::cout << (a->remove(499)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (a->remove(252)) << std::endl;
std::cout << (c->insert(99)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
a->printPretty();
std::cout << (d->remove(474)) << std::endl;
c->printPretty();
std::cout << (c->insert(171)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
d->printPretty();
std::cout << (b->insert(159)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (a->insert(161)) << std::endl;
b->printPretty();
std::cout << (a->remove(171)) << std::endl;
*b=*d;
*a=*d;
a->printPretty();
b->printPretty();
e->printPretty();
std::cout << (b->insert(407)) << std::endl;
std::cout << (c->remove(303)) << std::endl;
std::cout << (b->remove(99)) << std::endl;
std::cout << (c->insert(252)) << std::endl;
std::cout << (d->insert(286)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
*a=*e;
std::cout << (a->remove(72)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (c->remove(154)) << std::endl;
b->printPretty();
std::cout << (e->remove(72)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
std::cout << (a->insert(194)) << std::endl;
*d=*c;
std::cout << (c->remove(171)) << std::endl;
std::cout << (d->insert(406)) << std::endl;
std::cout << (d->remove(252)) << std::endl;
std::cout << (d->insert(94)) << std::endl;
std::cout << (d->remove(406)) << std::endl;
a->printPretty();
*b=*e;
std::cout << (c->insert(311)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
a->printPretty();
std::cout << (a->insert(194)) << std::endl;
*e=*e;
c->printPretty();
std::cout << (c->insert(190)) << std::endl;
std::cout << (e->insert(470)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
std::cout << (b->remove(244)) << std::endl;
*d=*c;
std::cout << (d->remove(59)) << std::endl;
std::cout << (b->insert(112)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
*b=*e;
std::cout << (e->remove(447)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
std::cout << (e->insert(213)) << std::endl;
e->printPretty();
std::cout << (c->remove(287)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
*b=*a;
std::cout << (e->insert(470)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (e->insert(212)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (e->insert(204)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (b->insert(112)) << std::endl;
*d=*b;
std::cout << (a->insert(173)) << std::endl;
a->printPretty();
b->printPretty();
*d=*e;
std::cout << (b->insert(194)) << std::endl;
*c=*d;
std::cout << (e->remove(204)) << std::endl;
std::cout << (b->insert(59)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
std::cout << (e->insert(212)) << std::endl;
e->printPretty();
std::cout << (b->remove(299)) << std::endl;
std::cout << (e->remove(212)) << std::endl;
std::cout << (b->remove(59)) << std::endl;
a->printPretty();
std::cout << (d->insert(112)) << std::endl;
std::cout << (c->insert(204)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
std::cout << (e->insert(322)) << std::endl;
*e=*c;
*a=*a;
std::cout << (e->insert(477)) << std::endl;
std::cout << (d->insert(470)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (c->insert(213)) << std::endl;
a->printPretty();
d->printPretty();
*d=*d;
b->printPretty();
std::cout << (a->insert(4)) << std::endl;
e->printPretty();
std::cout << (b->insert(86)) << std::endl;
c->printPretty();
std::cout << (d->remove(190)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (e->insert(173)) << std::endl;
*e=*c;
d->printPretty();
std::cout << (c->remove(334)) << std::endl;
*a=*d;
std::cout << (c->remove(322)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
std::cout << (a->remove(112)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (b->remove(86)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
c->printPretty();
std::cout << (a->remove(49)) << std::endl;
c->printPretty();
std::cout << (a->insert(220)) << std::endl;
b->printPretty();
std::cout << (a->remove(276)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
std::cout << (e->insert(331)) << std::endl;
b->printPretty();
std::cout << (b->insert(194)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (e->insert(112)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
*e=*e;
std::cout << (e->insert(152)) << std::endl;
d->printPretty();
std::cout << (e->insert(19)) << std::endl;
e->printPretty();
std::cout << (b->remove(441)) << std::endl;
std::cout << (b->remove(483)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (d->insert(149)) << std::endl;
std::cout << (d->remove(298)) << std::endl;
*e=*a;
*c=*a;
std::cout << (e->insert(98)) << std::endl;
std::cout << (a->remove(204)) << std::endl;
std::cout << (a->remove(213)) << std::endl;
std::cout << (b->remove(139)) << std::endl;
std::cout << (d->remove(336)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (c->insert(257)) << std::endl;
std::cout << (b->insert(374)) << std::endl;
std::cout << (e->insert(204)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (e->insert(439)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
a->printPretty();
std::cout << (a->insert(266)) << std::endl;
*c=*a;
e->printPretty();
std::cout << (d->remove(210)) << std::endl;
std::cout << (b->remove(112)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
*c=*b;
std::cout << (b->remove(374)) << std::endl;
std::cout << (b->insert(122)) << std::endl;
a->printPretty();
std::cout << (d->remove(448)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
d->printPretty();
std::cout << (b->insert(322)) << std::endl;
std::cout << (a->insert(445)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
a->printPretty();
*d=*b;
b->printPretty();
std::cout << (e->remove(169)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
std::cout << (d->insert(97)) << std::endl;
std::cout << (b->remove(441)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (c->insert(370)) << std::endl;
*c=*c;
std::cout << (b->remove(16)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
b->printPretty();
std::cout << (a->remove(466)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
*d=*c;
std::cout << (b->remove(297)) << std::endl;
std::cout << (d->insert(370)) << std::endl;
*d=*a;
std::cout << (e->remove(426)) << std::endl;
std::cout << (d->insert(99)) << std::endl;
std::cout << (a->insert(212)) << std::endl;
*c=*a;
std::cout << (b->insert(395)) << std::endl;
std::cout << (b->insert(236)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
e->printPretty();
std::cout << (d->insert(198)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
c->printPretty();
std::cout << (b->insert(122)) << std::endl;
std::cout << (e->insert(439)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
std::cout << (e->remove(204)) << std::endl;
std::cout << (a->insert(364)) << std::endl;
*a=*d;
std::cout << (a->insert(203)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
std::cout << (b->insert(487)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
std::cout << (e->insert(286)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
std::cout << (b->remove(371)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
*e=*e;
std::cout << (b->remove(67)) << std::endl;
std::cout << (b->remove(236)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (d->insert(212)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (e->insert(439)) << std::endl;
std::cout << (c->remove(50)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
*d=*d;
std::cout << (c->insert(59)) << std::endl;
std::cout << (e->remove(98)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
b->printPretty();
std::cout << (a->insert(198)) << std::endl;
std::cout << (b->insert(487)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
std::cout << (c->remove(59)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
std::cout << (e->remove(412)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (b->remove(417)) << std::endl;
std::cout << (e->insert(313)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (c->insert(67)) << std::endl;
e->printPretty();
std::cout << (e->insert(286)) << std::endl;
std::cout << (b->insert(276)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
std::cout << (a->insert(35)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
*d=*e;
std::cout << (a->remove(99)) << std::endl;
*e=*a;
*c=*b;
std::cout << (b->remove(97)) << std::endl;
*e=*b;
std::cout << (b->remove(487)) << std::endl;
std::cout << (a->remove(228)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (e->insert(240)) << std::endl;
std::cout << (c->insert(247)) << std::endl;
b->printPretty();
std::cout << (a->remove(298)) << std::endl;
std::cout << (e->insert(487)) << std::endl;
*d=*a;
std::cout << (c->remove(394)) << std::endl;
std::cout << (e->remove(240)) << std::endl;
*b=*d;
std::cout << (b->remove(470)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
*a=*b;
std::cout << (a->remove(362)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
std::cout << (b->insert(61)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
std::cout << (e->remove(78)) << std::endl;
std::cout << (a->remove(2)) << std::endl;
std::cout << (d->remove(198)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (e->insert(487)) << std::endl;
e->printPretty();
std::cout << (c->remove(203)) << std::endl;
b->printPretty();
*d=*d;
*a=*e;
a->printPretty();
std::cout << (a->remove(223)) << std::endl;
*b=*a;
a->printPretty();
e->printPretty();
std::cout << (e->insert(95)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (e->insert(188)) << std::endl;
e->printPretty();
std::cout << (a->insert(394)) << std::endl;
std::cout << (b->remove(487)) << std::endl;
e->printPretty();
std::cout << (c->remove(106)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
std::cout << (b->insert(60)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
b->printPretty();
std::cout << (d->remove(106)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
std::cout << (b->insert(60)) << std::endl;
b->printPretty();
std::cout << (e->insert(103)) << std::endl;
b->printPretty();
*a=*d;
std::cout << (b->remove(397)) << std::endl;
std::cout << (e->remove(487)) << std::endl;
b->printPretty();
std::cout << (a->insert(315)) << std::endl;
*b=*b;
std::cout << (b->insert(106)) << std::endl;
std::cout << (c->insert(220)) << std::endl;
std::cout << (c->insert(262)) << std::endl;
*a=*c;
std::cout << (c->insert(84)) << std::endl;
std::cout << (b->insert(242)) << std::endl;
std::cout << (c->remove(212)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
*d=*a;
std::cout << (c->insert(183)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
d->printPretty();
std::cout << (c->insert(84)) << std::endl;
std::cout << (d->insert(84)) << std::endl;
*c=*a;
std::cout << (a->remove(213)) << std::endl;
std::cout << (e->remove(487)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
return 0;
}
