#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(385)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (b->insert(201)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (e->remove(175)) << std::endl;
std::cout << (a->insert(457)) << std::endl;
a->printPretty();
std::cout << (b->remove(201)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
*b=*e;
std::cout << (d->remove(385)) << std::endl;
std::cout << (b->insert(432)) << std::endl;
*c=*a;
std::cout << (a->insert(227)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
d->printPretty();
std::cout << (e->insert(385)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
std::cout << (a->remove(227)) << std::endl;
*e=*c;
std::cout << (a->insert(457)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (e->insert(385)) << std::endl;
std::cout << (c->insert(385)) << std::endl;
std::cout << (b->remove(432)) << std::endl;
*d=*e;
std::cout << (d->insert(441)) << std::endl;
std::cout << (d->insert(441)) << std::endl;
*d=*a;
std::cout << (c->insert(407)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
d->printPretty();
std::cout << (d->insert(6)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
b->printPretty();
*e=*c;
std::cout << (c->remove(457)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->remove(399)) << std::endl;
std::cout << (d->insert(21)) << std::endl;
std::cout << (c->remove(239)) << std::endl;
a->printPretty();
std::cout << (b->remove(467)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (b->remove(3)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->remove(385)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
d->printPretty();
*e=*c;
*a=*c;
std::cout << (a->remove(42)) << std::endl;
std::cout << (c->insert(407)) << std::endl;
*b=*a;
std::cout << (e->insert(408)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(407)) << std::endl;
a->printPretty();
std::cout << (d->insert(351)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
*a=*c;
std::cout << (c->remove(76)) << std::endl;
*a=*b;
std::cout << (a->insert(407)) << std::endl;
*e=*a;
std::cout << (b->remove(14)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
*b=*a;
std::cout << (e->remove(142)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (e->insert(407)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
std::cout << (d->remove(28)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
d->printPretty();
std::cout << (a->insert(366)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
a->printPretty();
std::cout << (c->remove(165)) << std::endl;
std::cout << (b->insert(142)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (d->remove(457)) << std::endl;
*a=*b;
std::cout << (a->insert(407)) << std::endl;
*c=*a;
e->printPretty();
*e=*c;
d->printPretty();
*d=*c;
std::cout << (e->insert(142)) << std::endl;
std::cout << (d->remove(164)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (c->insert(380)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
std::cout << (d->remove(368)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (d->remove(142)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
std::cout << (e->remove(278)) << std::endl;
std::cout << (d->remove(320)) << std::endl;
std::cout << (e->insert(101)) << std::endl;
std::cout << (c->insert(142)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
std::cout << (a->remove(142)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
*d=*b;
std::cout << (e->insert(96)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
std::cout << (d->remove(143)) << std::endl;
b->printPretty();
std::cout << (a->remove(320)) << std::endl;
c->printPretty();
b->printPretty();
*c=*a;
d->printPretty();
std::cout << (e->insert(96)) << std::endl;
*c=*e;
std::cout << (b->remove(61)) << std::endl;
e->printPretty();
std::cout << (a->insert(66)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
c->printPretty();
std::cout << (e->remove(384)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (c->insert(223)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
std::cout << (d->insert(261)) << std::endl;
*c=*e;
std::cout << (d->insert(255)) << std::endl;
a->printPretty();
std::cout << (b->remove(238)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
std::cout << (c->insert(407)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
*b=*b;
std::cout << (e->remove(478)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (e->remove(101)) << std::endl;
std::cout << (c->remove(142)) << std::endl;
std::cout << (b->remove(142)) << std::endl;
std::cout << (c->insert(77)) << std::endl;
*a=*c;
b->printPretty();
*a=*c;
std::cout << (d->insert(142)) << std::endl;
std::cout << (d->insert(255)) << std::endl;
*c=*e;
std::cout << (e->insert(320)) << std::endl;
b->printPretty();
std::cout << (a->insert(279)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (e->insert(320)) << std::endl;
*a=*e;
std::cout << (a->remove(320)) << std::endl;
std::cout << (d->remove(142)) << std::endl;
std::cout << (d->insert(255)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
*b=*d;
*d=*a;
e->printPretty();
*e=*d;
std::cout << (b->insert(56)) << std::endl;
*c=*e;
*b=*e;
std::cout << (e->insert(266)) << std::endl;
*c=*e;
*d=*b;
c->printPretty();
*d=*a;
std::cout << (e->remove(266)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
b->printPretty();
std::cout << (d->remove(114)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (b->insert(309)) << std::endl;
*e=*a;
std::cout << (b->insert(309)) << std::endl;
std::cout << (b->insert(472)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
*a=*c;
*d=*d;
d->printPretty();
b->printPretty();
std::cout << (a->remove(266)) << std::endl;
d->printPretty();
std::cout << (c->insert(277)) << std::endl;
*e=*b;
std::cout << (c->remove(150)) << std::endl;
std::cout << (c->insert(266)) << std::endl;
*b=*d;
std::cout << (e->remove(270)) << std::endl;
std::cout << (b->remove(156)) << std::endl;
std::cout << (a->insert(168)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
*b=*e;
std::cout << (a->remove(266)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (a->remove(168)) << std::endl;
std::cout << (c->insert(277)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
std::cout << (a->remove(120)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
std::cout << (e->insert(2)) << std::endl;
std::cout << (b->insert(355)) << std::endl;
std::cout << (d->insert(419)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
*e=*e;
std::cout << (e->remove(26)) << std::endl;
std::cout << (b->remove(230)) << std::endl;
*b=*a;
c->printPretty();
e->printPretty();
c->printPretty();
std::cout << (b->insert(29)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (e->remove(286)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (b->insert(4)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
*e=*d;
*a=*b;
std::cout << (a->remove(197)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
c->printPretty();
std::cout << (d->insert(129)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
*a=*b;
std::cout << (e->insert(419)) << std::endl;
std::cout << (a->remove(65)) << std::endl;
std::cout << (c->remove(277)) << std::endl;
d->printPretty();
std::cout << (d->remove(324)) << std::endl;
*b=*b;
a->printPretty();
*d=*e;
e->printPretty();
std::cout << (b->remove(417)) << std::endl;
std::cout << (e->remove(333)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
*b=*d;
*e=*d;
std::cout << (c->insert(170)) << std::endl;
*e=*a;
std::cout << (a->insert(29)) << std::endl;
*c=*b;
*e=*a;
std::cout << (b->remove(309)) << std::endl;
std::cout << (d->remove(320)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
*e=*e;
std::cout << (e->insert(4)) << std::endl;
e->printPretty();
std::cout << (a->insert(99)) << std::endl;
*c=*b;
std::cout << (e->remove(272)) << std::endl;
c->printPretty();
std::cout << (c->insert(135)) << std::endl;
*c=*a;
*a=*b;
*a=*e;
std::cout << (b->remove(419)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (a->remove(472)) << std::endl;
*b=*b;
std::cout << (c->insert(373)) << std::endl;
std::cout << (e->insert(430)) << std::endl;
e->printPretty();
std::cout << (c->insert(75)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (c->insert(248)) << std::endl;
std::cout << (e->insert(430)) << std::endl;
std::cout << (c->insert(244)) << std::endl;
std::cout << (c->insert(435)) << std::endl;
std::cout << (b->remove(99)) << std::endl;
std::cout << (c->insert(316)) << std::endl;
b->printPretty();
*a=*c;
b->printPretty();
std::cout << (e->insert(404)) << std::endl;
d->printPretty();
std::cout << (b->remove(320)) << std::endl;
a->printPretty();
std::cout << (e->insert(4)) << std::endl;
b->printPretty();
std::cout << (c->insert(380)) << std::endl;
e->printPretty();
std::cout << (a->remove(336)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
*a=*e;
std::cout << (e->insert(404)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (c->remove(454)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
*e=*c;
b->printPretty();
e->printPretty();
a->printPretty();
std::cout << (b->insert(450)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (c->insert(460)) << std::endl;
std::cout << (d->insert(309)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
*d=*d;
std::cout << (e->insert(407)) << std::endl;
std::cout << (a->insert(4)) << std::endl;
std::cout << (a->remove(4)) << std::endl;
*e=*a;
std::cout << (e->remove(38)) << std::endl;
std::cout << (a->insert(404)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
std::cout << (e->insert(430)) << std::endl;
*b=*a;
*e=*c;
std::cout << (b->remove(430)) << std::endl;
std::cout << (e->insert(397)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
std::cout << (e->remove(440)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
*a=*e;
d->printPretty();
*a=*a;
d->printPretty();
std::cout << (d->insert(394)) << std::endl;
std::cout << (d->insert(238)) << std::endl;
d->printPretty();
std::cout << (e->insert(460)) << std::endl;
std::cout << (d->remove(309)) << std::endl;
std::cout << (c->insert(30)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (c->insert(232)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
*b=*d;
std::cout << (e->remove(408)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
*a=*e;
*b=*e;
std::cout << (a->remove(202)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
*b=*d;
*d=*c;
std::cout << (e->insert(107)) << std::endl;
*b=*d;
std::cout << (e->remove(289)) << std::endl;
*a=*d;
std::cout << (d->remove(232)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
c->printPretty();
*d=*a;
*b=*c;
std::cout << (b->remove(232)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
std::cout << (c->remove(69)) << std::endl;
d->printPretty();
std::cout << (e->remove(107)) << std::endl;
std::cout << (e->insert(309)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (b->insert(489)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
std::cout << (c->remove(232)) << std::endl;
*c=*d;
std::cout << (b->insert(152)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (c->remove(392)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (e->insert(269)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->insert(489)) << std::endl;
*c=*d;
std::cout << (e->remove(309)) << std::endl;
*a=*c;
*e=*b;
std::cout << (e->insert(278)) << std::endl;
*e=*b;
std::cout << (b->remove(372)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
a->printPretty();
std::cout << (e->insert(460)) << std::endl;
b->printPretty();
std::cout << (c->insert(423)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
std::cout << (c->remove(423)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (c->insert(204)) << std::endl;
std::cout << (b->remove(169)) << std::endl;
std::cout << (c->remove(204)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(152)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
*c=*b;
std::cout << (d->insert(116)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
d->printPretty();
std::cout << (e->remove(405)) << std::endl;
*c=*d;
std::cout << (a->insert(163)) << std::endl;
*c=*a;
std::cout << (b->remove(26)) << std::endl;
std::cout << (c->insert(163)) << std::endl;
std::cout << (b->remove(20)) << std::endl;
*d=*c;
std::cout << (b->remove(46)) << std::endl;
a->printPretty();
std::cout << (a->remove(163)) << std::endl;
d->printPretty();
std::cout << (b->remove(453)) << std::endl;
std::cout << (c->insert(81)) << std::endl;
std::cout << (e->remove(217)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (a->remove(81)) << std::endl;
std::cout << (c->insert(163)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
std::cout << (d->remove(163)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (d->insert(81)) << std::endl;
std::cout << (d->remove(368)) << std::endl;
std::cout << (b->insert(163)) << std::endl;
a->printPretty();
std::cout << (a->remove(290)) << std::endl;
*a=*a;
std::cout << (b->insert(131)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
*d=*a;
*a=*e;
std::cout << (a->remove(69)) << std::endl;
std::cout << (e->remove(235)) << std::endl;
e->printPretty();
std::cout << (a->insert(389)) << std::endl;
std::cout << (e->insert(460)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (e->remove(489)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
*c=*e;
std::cout << (e->insert(14)) << std::endl;
*e=*e;
*d=*b;
std::cout << (b->insert(131)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
*e=*e;
std::cout << (e->remove(78)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (e->remove(14)) << std::endl;
b->printPretty();
std::cout << (c->insert(69)) << std::endl;
c->printPretty();
std::cout << (e->insert(118)) << std::endl;
*a=*c;
std::cout << (d->remove(163)) << std::endl;
std::cout << (b->remove(131)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (d->remove(363)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(120)) << std::endl;
std::cout << (a->insert(477)) << std::endl;
c->printPretty();
std::cout << (d->insert(335)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
std::cout << (a->remove(279)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
std::cout << (e->insert(480)) << std::endl;
*d=*a;
*c=*c;
*c=*d;
std::cout << (c->remove(477)) << std::endl;
std::cout << (e->insert(452)) << std::endl;
e->printPretty();
*c=*d;
*d=*a;
std::cout << (d->insert(69)) << std::endl;
std::cout << (c->insert(173)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->remove(388)) << std::endl;
std::cout << (b->remove(473)) << std::endl;
*d=*c;
std::cout << (c->remove(173)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
*d=*b;
*d=*a;
std::cout << (a->remove(407)) << std::endl;
std::cout << (a->insert(477)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (e->remove(288)) << std::endl;
std::cout << (e->remove(160)) << std::endl;
*c=*a;
*d=*a;
std::cout << (c->remove(259)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
*a=*c;
std::cout << (e->remove(449)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (e->insert(452)) << std::endl;
*c=*d;
std::cout << (d->remove(69)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (a->insert(69)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
b->printPretty();
c->printPretty();
d->printPretty();
*c=*a;
a->printPretty();
std::cout << (e->remove(452)) << std::endl;
std::cout << (a->remove(69)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
std::cout << (b->remove(474)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
a->printPretty();
std::cout << (c->remove(319)) << std::endl;
a->printPretty();
std::cout << (e->insert(480)) << std::endl;
std::cout << (d->insert(363)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
*b=*e;
*c=*d;
std::cout << (a->remove(164)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
std::cout << (d->remove(66)) << std::endl;
*a=*c;
std::cout << (a->remove(182)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
std::cout << (a->remove(90)) << std::endl;
std::cout << (b->insert(323)) << std::endl;
std::cout << (b->insert(127)) << std::endl;
*c=*b;
std::cout << (e->remove(480)) << std::endl;
*a=*c;
std::cout << (a->remove(393)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
*d=*a;
std::cout << (c->remove(118)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
std::cout << (a->remove(323)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
e->printPretty();
*d=*a;
e->printPretty();
std::cout << (d->insert(480)) << std::endl;
*b=*d;
std::cout << (d->insert(127)) << std::endl;
e->printPretty();
std::cout << (b->remove(85)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (c->remove(140)) << std::endl;
a->printPretty();
*a=*c;
std::cout << (e->remove(118)) << std::endl;
*a=*b;
std::cout << (e->remove(69)) << std::endl;
std::cout << (b->remove(450)) << std::endl;
std::cout << (d->insert(118)) << std::endl;
d->printPretty();
std::cout << (b->insert(127)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
std::cout << (c->remove(201)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
std::cout << (b->remove(127)) << std::endl;
std::cout << (b->remove(480)) << std::endl;
std::cout << (d->insert(450)) << std::endl;
*b=*b;
std::cout << (c->insert(225)) << std::endl;
std::cout << (d->insert(192)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->insert(450)) << std::endl;
std::cout << (b->insert(438)) << std::endl;
std::cout << (c->insert(371)) << std::endl;
std::cout << (c->insert(190)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->insert(265)) << std::endl;
c->printPretty();
std::cout << (e->insert(76)) << std::endl;
std::cout << (d->remove(450)) << std::endl;
d->printPretty();
std::cout << (d->remove(192)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (c->insert(55)) << std::endl;
std::cout << (b->insert(438)) << std::endl;
std::cout << (b->insert(438)) << std::endl;
std::cout << (d->insert(68)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (c->insert(225)) << std::endl;
std::cout << (e->insert(368)) << std::endl;
std::cout << (e->remove(368)) << std::endl;
e->printPretty();
d->printPretty();
e->printPretty();
c->printPretty();
e->printPretty();
std::cout << (e->insert(76)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
std::cout << (e->remove(76)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
std::cout << (d->insert(14)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (e->insert(141)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (c->remove(183)) << std::endl;
a->printPretty();
std::cout << (b->insert(438)) << std::endl;
b->printPretty();
*c=*b;
std::cout << (b->remove(438)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (d->insert(476)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
e->printPretty();
std::cout << (d->insert(14)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (c->remove(127)) << std::endl;
std::cout << (a->remove(118)) << std::endl;
*e=*a;
d->printPretty();
*d=*d;
e->printPretty();
std::cout << (c->remove(381)) << std::endl;
std::cout << (b->remove(18)) << std::endl;
e->printPretty();
std::cout << (e->insert(450)) << std::endl;
*c=*e;
c->printPretty();
*e=*d;
std::cout << (c->remove(25)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
std::cout << (a->remove(450)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
std::cout << (c->insert(281)) << std::endl;
e->printPretty();
std::cout << (e->insert(35)) << std::endl;
std::cout << (d->remove(68)) << std::endl;
*c=*e;
std::cout << (d->remove(365)) << std::endl;
std::cout << (d->remove(476)) << std::endl;
std::cout << (a->remove(480)) << std::endl;
std::cout << (b->remove(241)) << std::endl;
std::cout << (b->remove(2)) << std::endl;
std::cout << (c->insert(35)) << std::endl;
std::cout << (a->insert(127)) << std::endl;
std::cout << (a->remove(127)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
std::cout << (c->insert(36)) << std::endl;
*b=*a;
d->printPretty();
return 0;
}
