#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(466)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->remove(323)) << std::endl;
std::cout << (a->insert(466)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->insert(148)) << std::endl;
std::cout << (a->insert(251)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
*b=*b;
a->printPretty();
std::cout << (c->remove(259)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->insert(251)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (c->insert(152)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (d->remove(382)) << std::endl;
std::cout << (b->insert(328)) << std::endl;
std::cout << (b->insert(233)) << std::endl;
c->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->remove(188)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
*a=*b;
std::cout << (b->insert(328)) << std::endl;
std::cout << (a->remove(328)) << std::endl;
d->printPretty();
std::cout << (e->remove(56)) << std::endl;
std::cout << (b->insert(233)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (c->remove(214)) << std::endl;
*b=*e;
std::cout << (e->insert(425)) << std::endl;
*b=*a;
std::cout << (e->insert(135)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
std::cout << (c->insert(471)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
d->printPretty();
std::cout << (a->remove(233)) << std::endl;
std::cout << (c->insert(65)) << std::endl;
std::cout << (b->remove(326)) << std::endl;
std::cout << (a->remove(456)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (b->remove(73)) << std::endl;
std::cout << (e->remove(24)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
*d=*b;
std::cout << (e->insert(33)) << std::endl;
std::cout << (e->remove(306)) << std::endl;
std::cout << (e->insert(202)) << std::endl;
*c=*c;
std::cout << (e->remove(202)) << std::endl;
d->printPretty();
std::cout << (d->remove(471)) << std::endl;
std::cout << (d->insert(233)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->remove(349)) << std::endl;
*a=*b;
std::cout << (b->insert(238)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
e->printPretty();
std::cout << (c->insert(200)) << std::endl;
std::cout << (c->insert(318)) << std::endl;
a->printPretty();
std::cout << (c->insert(267)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
std::cout << (b->insert(238)) << std::endl;
std::cout << (a->remove(233)) << std::endl;
e->printPretty();
std::cout << (c->insert(152)) << std::endl;
e->printPretty();
std::cout << (a->remove(382)) << std::endl;
std::cout << (a->remove(422)) << std::endl;
*a=*c;
std::cout << (e->insert(310)) << std::endl;
c->printPretty();
c->printPretty();
*c=*b;
a->printPretty();
std::cout << (b->insert(233)) << std::endl;
std::cout << (e->insert(287)) << std::endl;
std::cout << (e->insert(146)) << std::endl;
c->printPretty();
e->printPretty();
*c=*d;
*d=*d;
std::cout << (e->remove(40)) << std::endl;
*c=*a;
std::cout << (e->insert(287)) << std::endl;
std::cout << (b->insert(233)) << std::endl;
std::cout << (c->insert(29)) << std::endl;
*c=*a;
std::cout << (d->insert(233)) << std::endl;
std::cout << (b->remove(471)) << std::endl;
c->printPretty();
std::cout << (a->insert(241)) << std::endl;
std::cout << (a->insert(340)) << std::endl;
*a=*c;
*e=*c;
std::cout << (c->insert(408)) << std::endl;
std::cout << (a->insert(309)) << std::endl;
std::cout << (c->remove(281)) << std::endl;
std::cout << (c->insert(148)) << std::endl;
c->printPretty();
std::cout << (c->insert(471)) << std::endl;
e->printPretty();
std::cout << (a->insert(182)) << std::endl;
std::cout << (c->remove(138)) << std::endl;
a->printPretty();
std::cout << (e->remove(70)) << std::endl;
std::cout << (a->insert(418)) << std::endl;
*d=*d;
e->printPretty();
std::cout << (e->remove(251)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
*c=*b;
*e=*b;
std::cout << (b->remove(458)) << std::endl;
a->printPretty();
std::cout << (c->remove(480)) << std::endl;
std::cout << (e->insert(238)) << std::endl;
std::cout << (c->remove(373)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (d->insert(120)) << std::endl;
std::cout << (a->remove(418)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
b->printPretty();
*e=*d;
std::cout << (a->remove(251)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
*d=*d;
c->printPretty();
c->printPretty();
e->printPretty();
*a=*a;
std::cout << (a->insert(152)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(218)) << std::endl;
std::cout << (b->insert(147)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
std::cout << (e->remove(42)) << std::endl;
std::cout << (b->insert(233)) << std::endl;
std::cout << (e->insert(312)) << std::endl;
std::cout << (e->insert(2)) << std::endl;
std::cout << (a->remove(182)) << std::endl;
e->printPretty();
std::cout << (d->remove(424)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
std::cout << (a->remove(65)) << std::endl;
*a=*e;
std::cout << (a->insert(113)) << std::endl;
*a=*a;
*e=*c;
std::cout << (d->remove(120)) << std::endl;
*e=*e;
*d=*e;
e->printPretty();
std::cout << (b->insert(360)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (e->remove(233)) << std::endl;
std::cout << (a->remove(273)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
*b=*b;
std::cout << (e->insert(114)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (a->insert(120)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
*c=*b;
std::cout << (b->remove(22)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
*a=*b;
std::cout << (c->remove(256)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
std::cout << (a->remove(233)) << std::endl;
std::cout << (c->remove(400)) << std::endl;
std::cout << (a->insert(147)) << std::endl;
std::cout << (c->insert(233)) << std::endl;
*d=*e;
std::cout << (e->insert(330)) << std::endl;
std::cout << (c->remove(160)) << std::endl;
std::cout << (e->remove(330)) << std::endl;
std::cout << (d->insert(238)) << std::endl;
std::cout << (a->remove(360)) << std::endl;
std::cout << (d->insert(238)) << std::endl;
std::cout << (b->insert(238)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
*e=*d;
std::cout << (b->remove(238)) << std::endl;
std::cout << (a->insert(201)) << std::endl;
std::cout << (e->remove(99)) << std::endl;
a->printPretty();
std::cout << (b->insert(233)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
std::cout << (e->remove(114)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (b->insert(399)) << std::endl;
std::cout << (d->remove(238)) << std::endl;
std::cout << (a->remove(238)) << std::endl;
b->printPretty();
std::cout << (d->remove(99)) << std::endl;
std::cout << (b->insert(50)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (c->remove(147)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
std::cout << (d->insert(445)) << std::endl;
d->printPretty();
std::cout << (c->remove(238)) << std::endl;
c->printPretty();
std::cout << (a->insert(319)) << std::endl;
std::cout << (a->remove(328)) << std::endl;
*b=*c;
*d=*e;
std::cout << (b->insert(390)) << std::endl;
std::cout << (e->insert(238)) << std::endl;
std::cout << (d->insert(238)) << std::endl;
std::cout << (e->insert(238)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(233)) << std::endl;
std::cout << (a->remove(223)) << std::endl;
*b=*b;
std::cout << (c->remove(360)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
std::cout << (c->remove(90)) << std::endl;
std::cout << (a->insert(201)) << std::endl;
*e=*a;
std::cout << (a->remove(253)) << std::endl;
std::cout << (e->insert(147)) << std::endl;
std::cout << (a->insert(149)) << std::endl;
e->printPretty();
std::cout << (e->remove(226)) << std::endl;
b->printPretty();
*b=*e;
*e=*b;
std::cout << (d->remove(492)) << std::endl;
std::cout << (e->insert(112)) << std::endl;
d->printPretty();
std::cout << (a->insert(285)) << std::endl;
std::cout << (d->remove(265)) << std::endl;
*a=*c;
std::cout << (b->remove(201)) << std::endl;
e->printPretty();
std::cout << (b->remove(448)) << std::endl;
*e=*c;
std::cout << (e->remove(415)) << std::endl;
std::cout << (a->remove(429)) << std::endl;
std::cout << (d->remove(238)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (a->remove(432)) << std::endl;
std::cout << (c->remove(333)) << std::endl;
std::cout << (b->insert(60)) << std::endl;
c->printPretty();
std::cout << (d->remove(332)) << std::endl;
std::cout << (d->insert(126)) << std::endl;
std::cout << (d->remove(445)) << std::endl;
d->printPretty();
std::cout << (d->remove(213)) << std::endl;
std::cout << (d->insert(381)) << std::endl;
std::cout << (e->insert(308)) << std::endl;
std::cout << (e->insert(29)) << std::endl;
c->printPretty();
d->printPretty();
*c=*d;
std::cout << (e->remove(478)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
*b=*b;
std::cout << (d->remove(126)) << std::endl;
std::cout << (c->remove(169)) << std::endl;
std::cout << (b->remove(130)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
*e=*e;
std::cout << (e->remove(260)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(234)) << std::endl;
std::cout << (d->remove(381)) << std::endl;
*a=*e;
std::cout << (b->remove(216)) << std::endl;
b->printPretty();
e->printPretty();
*b=*d;
*b=*b;
*a=*c;
c->printPretty();
e->printPretty();
std::cout << (c->remove(126)) << std::endl;
std::cout << (b->insert(424)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
*b=*e;
std::cout << (a->insert(126)) << std::endl;
std::cout << (b->remove(7)) << std::endl;
std::cout << (b->remove(130)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
std::cout << (a->remove(246)) << std::endl;
*c=*c;
std::cout << (c->remove(381)) << std::endl;
std::cout << (c->insert(360)) << std::endl;
*c=*e;
std::cout << (e->insert(308)) << std::endl;
b->printPretty();
*a=*e;
*d=*c;
std::cout << (a->insert(189)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
d->printPretty();
std::cout << (c->insert(215)) << std::endl;
std::cout << (b->remove(485)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
std::cout << (b->remove(174)) << std::endl;
std::cout << (d->insert(302)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
*b=*a;
*a=*b;
std::cout << (a->insert(274)) << std::endl;
std::cout << (a->insert(308)) << std::endl;
*d=*e;
a->printPretty();
e->printPretty();
std::cout << (d->remove(308)) << std::endl;
*d=*e;
c->printPretty();
std::cout << (e->remove(388)) << std::endl;
e->printPretty();
std::cout << (e->insert(308)) << std::endl;
*e=*b;
*b=*a;
std::cout << (b->remove(481)) << std::endl;
std::cout << (e->insert(481)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
*a=*e;
b->printPretty();
*a=*c;
d->printPretty();
std::cout << (e->insert(139)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
d->printPretty();
std::cout << (e->remove(481)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
b->printPretty();
std::cout << (c->remove(308)) << std::endl;
*e=*d;
std::cout << (a->insert(142)) << std::endl;
std::cout << (d->insert(254)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
std::cout << (d->remove(255)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (c->remove(457)) << std::endl;
std::cout << (b->remove(382)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (d->insert(254)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
std::cout << (d->remove(394)) << std::endl;
std::cout << (c->remove(478)) << std::endl;
b->printPretty();
std::cout << (e->remove(146)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->insert(23)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->insert(489)) << std::endl;
std::cout << (c->insert(23)) << std::endl;
d->printPretty();
std::cout << (a->remove(29)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (c->insert(256)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
std::cout << (a->remove(461)) << std::endl;
c->printPretty();
std::cout << (c->remove(30)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
c->printPretty();
std::cout << (b->remove(274)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
std::cout << (e->remove(497)) << std::endl;
std::cout << (a->remove(215)) << std::endl;
std::cout << (b->insert(189)) << std::endl;
std::cout << (d->insert(254)) << std::endl;
*c=*b;
*c=*d;
std::cout << (d->insert(489)) << std::endl;
std::cout << (e->remove(289)) << std::endl;
std::cout << (a->insert(255)) << std::endl;
std::cout << (c->remove(309)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
b->printPretty();
std::cout << (a->insert(255)) << std::endl;
std::cout << (a->insert(222)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
std::cout << (c->remove(458)) << std::endl;
d->printPretty();
*a=*e;
a->printPretty();
std::cout << (c->insert(191)) << std::endl;
e->printPretty();
std::cout << (c->insert(489)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
std::cout << (a->remove(141)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (a->remove(338)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
*b=*e;
b->printPretty();
std::cout << (c->remove(364)) << std::endl;
std::cout << (b->remove(68)) << std::endl;
*a=*c;
std::cout << (d->insert(83)) << std::endl;
*b=*a;
std::cout << (e->insert(395)) << std::endl;
e->printPretty();
b->printPretty();
b->printPretty();
std::cout << (a->remove(138)) << std::endl;
*d=*c;
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
std::cout << (e->insert(200)) << std::endl;
std::cout << (d->remove(287)) << std::endl;
d->printPretty();
std::cout << (d->insert(420)) << std::endl;
std::cout << (a->insert(66)) << std::endl;
std::cout << (a->insert(191)) << std::endl;
std::cout << (c->insert(282)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
std::cout << (c->remove(255)) << std::endl;
std::cout << (a->insert(278)) << std::endl;
std::cout << (c->remove(254)) << std::endl;
std::cout << (d->remove(26)) << std::endl;
*a=*e;
std::cout << (e->remove(133)) << std::endl;
std::cout << (b->remove(489)) << std::endl;
b->printPretty();
std::cout << (b->insert(362)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
std::cout << (d->insert(488)) << std::endl;
e->printPretty();
*b=*b;
*d=*b;
std::cout << (e->remove(200)) << std::endl;
std::cout << (d->remove(254)) << std::endl;
*d=*e;
*e=*a;
std::cout << (d->insert(395)) << std::endl;
std::cout << (b->insert(362)) << std::endl;
*d=*a;
std::cout << (e->remove(55)) << std::endl;
std::cout << (c->insert(384)) << std::endl;
*d=*b;
*d=*c;
*b=*e;
*b=*b;
std::cout << (d->insert(422)) << std::endl;
d->printPretty();
std::cout << (a->insert(294)) << std::endl;
std::cout << (c->remove(282)) << std::endl;
std::cout << (e->remove(402)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (a->remove(200)) << std::endl;
std::cout << (a->insert(395)) << std::endl;
*a=*a;
std::cout << (a->remove(395)) << std::endl;
*c=*e;
std::cout << (e->insert(294)) << std::endl;
std::cout << (d->remove(191)) << std::endl;
*c=*a;
std::cout << (a->insert(281)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
std::cout << (b->insert(281)) << std::endl;
std::cout << (d->remove(461)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
a->printPretty();
std::cout << (b->insert(407)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->insert(235)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
std::cout << (b->insert(318)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
std::cout << (e->remove(443)) << std::endl;
std::cout << (b->remove(75)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
d->printPretty();
std::cout << (c->remove(68)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
*e=*c;
std::cout << (c->remove(294)) << std::endl;
d->printPretty();
*e=*e;
*c=*e;
std::cout << (a->remove(387)) << std::endl;
std::cout << (d->insert(189)) << std::endl;
b->printPretty();
std::cout << (d->remove(444)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (a->remove(281)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
*c=*a;
std::cout << (b->remove(294)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
std::cout << (a->insert(113)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
std::cout << (b->insert(131)) << std::endl;
std::cout << (a->remove(113)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
*e=*b;
std::cout << (d->insert(282)) << std::endl;
e->printPretty();
std::cout << (c->insert(120)) << std::endl;
std::cout << (e->remove(318)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (c->remove(120)) << std::endl;
std::cout << (e->insert(131)) << std::endl;
std::cout << (d->insert(472)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
e->printPretty();
std::cout << (d->insert(422)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
std::cout << (b->remove(426)) << std::endl;
*d=*c;
a->printPretty();
b->printPretty();
a->printPretty();
std::cout << (d->remove(167)) << std::endl;
std::cout << (b->remove(281)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
c->printPretty();
*d=*b;
a->printPretty();
std::cout << (a->insert(397)) << std::endl;
std::cout << (d->remove(500)) << std::endl;
std::cout << (e->remove(16)) << std::endl;
d->printPretty();
a->printPretty();
*c=*d;
std::cout << (b->remove(276)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
d->printPretty();
std::cout << (d->remove(200)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
std::cout << (c->remove(332)) << std::endl;
std::cout << (b->insert(129)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
*d=*d;
d->printPretty();
std::cout << (d->remove(205)) << std::endl;
*e=*e;
std::cout << (c->insert(171)) << std::endl;
*d=*d;
std::cout << (c->remove(499)) << std::endl;
std::cout << (a->remove(414)) << std::endl;
std::cout << (a->remove(397)) << std::endl;
*b=*b;
std::cout << (a->insert(250)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
std::cout << (c->insert(407)) << std::endl;
std::cout << (a->insert(144)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
*e=*d;
*e=*a;
*c=*d;
std::cout << (a->remove(250)) << std::endl;
std::cout << (c->remove(74)) << std::endl;
std::cout << (b->insert(200)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (e->insert(144)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
std::cout << (d->remove(495)) << std::endl;
std::cout << (e->remove(185)) << std::endl;
std::cout << (e->remove(34)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->insert(144)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
std::cout << (a->remove(144)) << std::endl;
*c=*d;
d->printPretty();
std::cout << (b->insert(395)) << std::endl;
std::cout << (d->remove(425)) << std::endl;
*d=*c;
std::cout << (d->insert(2)) << std::endl;
*c=*b;
a->printPretty();
*e=*a;
std::cout << (c->insert(26)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
a->printPretty();
std::cout << (b->insert(334)) << std::endl;
*b=*c;
std::cout << (a->remove(493)) << std::endl;
d->printPretty();
std::cout << (d->remove(294)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
d->printPretty();
std::cout << (b->insert(200)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
*c=*d;
std::cout << (b->insert(326)) << std::endl;
a->printPretty();
c->printPretty();
e->printPretty();
std::cout << (d->remove(59)) << std::endl;
std::cout << (e->insert(280)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (a->remove(467)) << std::endl;
std::cout << (b->insert(458)) << std::endl;
*e=*c;
std::cout << (e->remove(287)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (e->insert(104)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
*e=*c;
std::cout << (b->insert(326)) << std::endl;
e->printPretty();
std::cout << (c->insert(287)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
c->printPretty();
b->printPretty();
*c=*c;
std::cout << (c->remove(110)) << std::endl;
c->printPretty();
std::cout << (d->remove(287)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
c->printPretty();
std::cout << (e->remove(12)) << std::endl;
*b=*e;
std::cout << (e->remove(480)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
*c=*e;
std::cout << (b->remove(325)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (a->insert(414)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
*b=*c;
std::cout << (c->insert(287)) << std::endl;
*e=*b;
std::cout << (a->remove(10)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
c->printPretty();
std::cout << (a->insert(414)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
std::cout << (d->insert(144)) << std::endl;
std::cout << (e->insert(287)) << std::endl;
std::cout << (b->insert(287)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
*d=*c;
*a=*d;
d->printPretty();
c->printPretty();
b->printPretty();
std::cout << (d->insert(301)) << std::endl;
*a=*e;
*a=*a;
*c=*c;
c->printPretty();
std::cout << (b->insert(110)) << std::endl;
std::cout << (b->insert(144)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
*e=*c;
std::cout << (d->insert(255)) << std::endl;
c->printPretty();
std::cout << (c->remove(262)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
*e=*e;
std::cout << (b->remove(2)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
a->printPretty();
std::cout << (d->remove(497)) << std::endl;
std::cout << (d->remove(323)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(110)) << std::endl;
std::cout << (b->remove(356)) << std::endl;
*d=*d;
std::cout << (e->insert(2)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
return 0;
}
