#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
c->printPretty();
*b=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
*a=*c;
c->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*a=*e;
std::cout << (e->remove(368)) << std::endl;
std::cout << (d->insert(401)) << std::endl;
*c=*b;
std::cout << (d->insert(15)) << std::endl;
b->printPretty();
std::cout << (d->insert(112)) << std::endl;
std::cout << (d->insert(74)) << std::endl;
std::cout << (a->remove(144)) << std::endl;
*d=*e;
std::cout << (e->remove(305)) << std::endl;
std::cout << (e->insert(194)) << std::endl;
*c=*a;
d->printPretty();
std::cout << (c->remove(305)) << std::endl;
a->printPretty();
std::cout << (b->insert(21)) << std::endl;
std::cout << (a->insert(301)) << std::endl;
e->printPretty();
b->printPretty();
*a=*d;
std::cout << (d->remove(261)) << std::endl;
*e=*d;
std::cout << (c->insert(201)) << std::endl;
c->printPretty();
std::cout << (c->remove(5)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (b->remove(21)) << std::endl;
std::cout << (d->remove(398)) << std::endl;
*e=*e;
std::cout << (a->remove(499)) << std::endl;
std::cout << (d->insert(290)) << std::endl;
std::cout << (c->remove(8)) << std::endl;
e->printPretty();
std::cout << (c->remove(163)) << std::endl;
std::cout << (c->remove(201)) << std::endl;
*d=*e;
std::cout << (a->insert(489)) << std::endl;
std::cout << (b->insert(108)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
std::cout << (d->insert(220)) << std::endl;
std::cout << (c->remove(166)) << std::endl;
std::cout << (b->insert(180)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (a->remove(44)) << std::endl;
std::cout << (d->remove(104)) << std::endl;
std::cout << (c->remove(228)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
*d=*d;
std::cout << (e->insert(220)) << std::endl;
d->printPretty();
std::cout << (e->insert(220)) << std::endl;
std::cout << (a->remove(489)) << std::endl;
d->printPretty();
std::cout << (b->insert(180)) << std::endl;
std::cout << (c->insert(145)) << std::endl;
*e=*d;
std::cout << (e->insert(220)) << std::endl;
std::cout << (d->remove(452)) << std::endl;
*d=*a;
std::cout << (c->remove(147)) << std::endl;
std::cout << (b->remove(108)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
std::cout << (e->remove(220)) << std::endl;
e->printPretty();
std::cout << (c->remove(145)) << std::endl;
*d=*d;
*c=*b;
std::cout << (e->remove(186)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
b->printPretty();
std::cout << (b->remove(149)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
*d=*a;
std::cout << (b->insert(117)) << std::endl;
std::cout << (c->remove(180)) << std::endl;
c->printPretty();
std::cout << (b->insert(34)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
c->printPretty();
std::cout << (c->remove(118)) << std::endl;
std::cout << (b->insert(180)) << std::endl;
std::cout << (e->insert(198)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
std::cout << (b->remove(117)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
c->printPretty();
std::cout << (a->remove(466)) << std::endl;
*a=*e;
*e=*e;
std::cout << (c->remove(84)) << std::endl;
c->printPretty();
b->printPretty();
*e=*a;
b->printPretty();
b->printPretty();
std::cout << (b->insert(312)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
std::cout << (a->insert(391)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
std::cout << (b->insert(312)) << std::endl;
a->printPretty();
std::cout << (d->remove(339)) << std::endl;
std::cout << (a->insert(321)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (a->remove(321)) << std::endl;
a->printPretty();
std::cout << (c->insert(37)) << std::endl;
std::cout << (a->remove(71)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
std::cout << (c->remove(478)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (b->insert(180)) << std::endl;
a->printPretty();
std::cout << (a->remove(391)) << std::endl;
*b=*d;
std::cout << (b->insert(154)) << std::endl;
std::cout << (b->insert(154)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
*d=*e;
std::cout << (b->remove(419)) << std::endl;
std::cout << (e->remove(51)) << std::endl;
*a=*c;
e->printPretty();
*c=*b;
std::cout << (b->insert(154)) << std::endl;
*e=*e;
std::cout << (b->remove(94)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
std::cout << (e->insert(472)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (a->insert(37)) << std::endl;
*e=*c;
e->printPretty();
*c=*b;
std::cout << (a->insert(37)) << std::endl;
*d=*e;
*e=*a;
std::cout << (e->insert(37)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (c->remove(154)) << std::endl;
d->printPretty();
std::cout << (b->remove(92)) << std::endl;
d->printPretty();
std::cout << (c->remove(258)) << std::endl;
std::cout << (b->remove(302)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
c->printPretty();
std::cout << (a->remove(37)) << std::endl;
a->printPretty();
*b=*d;
*a=*e;
a->printPretty();
*b=*c;
std::cout << (e->remove(37)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
*a=*d;
std::cout << (a->insert(154)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
std::cout << (e->remove(340)) << std::endl;
std::cout << (a->remove(191)) << std::endl;
std::cout << (e->remove(452)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
e->printPretty();
std::cout << (d->insert(258)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
std::cout << (c->insert(240)) << std::endl;
*d=*a;
std::cout << (b->remove(495)) << std::endl;
std::cout << (d->remove(400)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (d->insert(258)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (a->insert(154)) << std::endl;
std::cout << (d->remove(447)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (d->insert(326)) << std::endl;
b->printPretty();
std::cout << (e->remove(305)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (a->remove(160)) << std::endl;
std::cout << (a->remove(148)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (c->insert(404)) << std::endl;
std::cout << (e->insert(16)) << std::endl;
c->printPretty();
*e=*a;
a->printPretty();
std::cout << (e->remove(320)) << std::endl;
std::cout << (c->remove(34)) << std::endl;
std::cout << (e->remove(154)) << std::endl;
std::cout << (c->remove(174)) << std::endl;
b->printPretty();
std::cout << (e->insert(299)) << std::endl;
std::cout << (c->remove(404)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (e->remove(248)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
std::cout << (e->insert(299)) << std::endl;
std::cout << (b->insert(132)) << std::endl;
std::cout << (d->insert(154)) << std::endl;
*a=*e;
std::cout << (d->insert(154)) << std::endl;
*a=*e;
*e=*c;
std::cout << (c->insert(366)) << std::endl;
*c=*e;
std::cout << (a->insert(295)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
std::cout << (d->remove(36)) << std::endl;
b->printPretty();
std::cout << (d->remove(223)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->insert(199)) << std::endl;
*c=*b;
std::cout << (c->insert(154)) << std::endl;
std::cout << (a->insert(299)) << std::endl;
e->printPretty();
std::cout << (b->remove(132)) << std::endl;
std::cout << (b->insert(458)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
*c=*a;
std::cout << (c->remove(99)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
*a=*a;
std::cout << (e->insert(68)) << std::endl;
c->printPretty();
std::cout << (b->remove(206)) << std::endl;
a->printPretty();
std::cout << (e->remove(464)) << std::endl;
std::cout << (b->remove(458)) << std::endl;
e->printPretty();
c->printPretty();
*b=*a;
std::cout << (e->remove(68)) << std::endl;
*e=*e;
std::cout << (a->insert(295)) << std::endl;
*a=*d;
*e=*b;
std::cout << (b->remove(299)) << std::endl;
std::cout << (b->insert(295)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
*b=*a;
std::cout << (e->remove(87)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->remove(432)) << std::endl;
*c=*b;
std::cout << (d->remove(87)) << std::endl;
std::cout << (e->insert(299)) << std::endl;
std::cout << (e->insert(295)) << std::endl;
std::cout << (e->remove(295)) << std::endl;
b->printPretty();
std::cout << (a->insert(222)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
b->printPretty();
std::cout << (a->remove(222)) << std::endl;
*e=*a;
*e=*c;
std::cout << (c->insert(429)) << std::endl;
std::cout << (d->remove(190)) << std::endl;
std::cout << (d->remove(249)) << std::endl;
*b=*c;
std::cout << (c->insert(429)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (b->insert(297)) << std::endl;
std::cout << (d->remove(394)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (d->insert(345)) << std::endl;
d->printPretty();
e->printPretty();
e->printPretty();
*c=*a;
std::cout << (d->insert(345)) << std::endl;
*c=*a;
*e=*a;
b->printPretty();
std::cout << (b->remove(152)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (b->remove(118)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (c->insert(423)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (b->insert(194)) << std::endl;
std::cout << (b->remove(194)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (e->remove(123)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
*a=*e;
*a=*d;
*c=*c;
b->printPretty();
std::cout << (a->remove(345)) << std::endl;
std::cout << (a->remove(319)) << std::endl;
*e=*a;
e->printPretty();
std::cout << (a->remove(377)) << std::endl;
std::cout << (c->remove(423)) << std::endl;
std::cout << (d->remove(345)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
a->printPretty();
e->printPretty();
*a=*b;
e->printPretty();
std::cout << (c->insert(110)) << std::endl;
*e=*b;
std::cout << (a->remove(158)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
*b=*b;
b->printPretty();
std::cout << (d->remove(319)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (e->insert(439)) << std::endl;
std::cout << (a->insert(217)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
*b=*a;
*b=*c;
std::cout << (a->insert(178)) << std::endl;
std::cout << (c->insert(110)) << std::endl;
std::cout << (b->remove(110)) << std::endl;
*b=*c;
std::cout << (c->insert(110)) << std::endl;
*a=*c;
std::cout << (d->remove(221)) << std::endl;
*b=*a;
*c=*b;
std::cout << (b->insert(110)) << std::endl;
c->printPretty();
std::cout << (c->remove(110)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
d->printPretty();
std::cout << (a->remove(110)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
*d=*b;
std::cout << (e->insert(469)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
std::cout << (b->remove(110)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
c->printPretty();
std::cout << (c->remove(21)) << std::endl;
std::cout << (e->remove(108)) << std::endl;
*b=*e;
*b=*d;
std::cout << (b->remove(110)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
*a=*a;
*c=*e;
*b=*e;
std::cout << (b->remove(469)) << std::endl;
std::cout << (a->insert(381)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (b->insert(222)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
std::cout << (e->insert(222)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (a->remove(252)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
std::cout << (c->insert(469)) << std::endl;
e->printPretty();
std::cout << (b->insert(222)) << std::endl;
a->printPretty();
std::cout << (c->remove(158)) << std::endl;
e->printPretty();
std::cout << (a->remove(381)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
*e=*d;
std::cout << (e->remove(341)) << std::endl;
*c=*e;
*c=*d;
std::cout << (d->remove(51)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (b->remove(50)) << std::endl;
a->printPretty();
std::cout << (b->insert(222)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
std::cout << (c->insert(251)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (e->remove(302)) << std::endl;
std::cout << (a->remove(23)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
std::cout << (d->insert(128)) << std::endl;
std::cout << (b->insert(222)) << std::endl;
*d=*d;
std::cout << (a->remove(1)) << std::endl;
std::cout << (b->insert(54)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
std::cout << (b->remove(222)) << std::endl;
std::cout << (c->remove(114)) << std::endl;
std::cout << (b->remove(263)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->insert(128)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
std::cout << (d->insert(313)) << std::endl;
std::cout << (e->insert(261)) << std::endl;
b->printPretty();
std::cout << (b->remove(54)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
std::cout << (e->remove(261)) << std::endl;
std::cout << (a->remove(265)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
std::cout << (d->insert(332)) << std::endl;
std::cout << (c->insert(122)) << std::endl;
std::cout << (c->insert(140)) << std::endl;
std::cout << (a->remove(493)) << std::endl;
std::cout << (c->remove(122)) << std::endl;
std::cout << (c->insert(58)) << std::endl;
d->printPretty();
d->printPretty();
a->printPretty();
e->printPretty();
*e=*d;
std::cout << (e->remove(332)) << std::endl;
std::cout << (d->insert(360)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (c->insert(497)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (e->remove(445)) << std::endl;
std::cout << (c->insert(105)) << std::endl;
std::cout << (c->remove(236)) << std::endl;
*e=*a;
std::cout << (d->insert(335)) << std::endl;
std::cout << (b->remove(172)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
std::cout << (b->remove(497)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
std::cout << (a->remove(100)) << std::endl;
std::cout << (a->remove(363)) << std::endl;
c->printPretty();
std::cout << (d->insert(335)) << std::endl;
*c=*c;
std::cout << (e->remove(139)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
std::cout << (d->insert(335)) << std::endl;
std::cout << (c->remove(448)) << std::endl;
b->printPretty();
std::cout << (c->remove(362)) << std::endl;
std::cout << (b->remove(346)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
*b=*a;
std::cout << (b->remove(444)) << std::endl;
*c=*b;
std::cout << (b->insert(100)) << std::endl;
std::cout << (e->remove(198)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
*a=*e;
*a=*b;
std::cout << (c->insert(36)) << std::endl;
std::cout << (d->remove(46)) << std::endl;
*a=*d;
c->printPretty();
*b=*e;
c->printPretty();
std::cout << (a->remove(496)) << std::endl;
*d=*a;
c->printPretty();
std::cout << (c->remove(144)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
*d=*c;
std::cout << (d->insert(416)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
std::cout << (b->insert(30)) << std::endl;
std::cout << (a->remove(219)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
a->printPretty();
std::cout << (a->remove(55)) << std::endl;
c->printPretty();
std::cout << (d->remove(405)) << std::endl;
std::cout << (e->remove(131)) << std::endl;
std::cout << (d->insert(211)) << std::endl;
std::cout << (d->remove(228)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
*b=*c;
d->printPretty();
std::cout << (a->insert(360)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
*d=*c;
std::cout << (c->remove(36)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
std::cout << (c->remove(462)) << std::endl;
std::cout << (b->remove(164)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
d->printPretty();
b->printPretty();
a->printPretty();
std::cout << (e->remove(150)) << std::endl;
*e=*c;
std::cout << (d->insert(102)) << std::endl;
*d=*d;
d->printPretty();
std::cout << (a->remove(360)) << std::endl;
std::cout << (b->remove(36)) << std::endl;
std::cout << (d->remove(288)) << std::endl;
std::cout << (a->insert(313)) << std::endl;
std::cout << (d->remove(421)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
std::cout << (b->remove(148)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (e->remove(116)) << std::endl;
b->printPretty();
*d=*e;
*d=*b;
std::cout << (d->insert(477)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
std::cout << (e->remove(360)) << std::endl;
*a=*e;
std::cout << (d->insert(305)) << std::endl;
*c=*b;
std::cout << (c->remove(67)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
std::cout << (a->remove(459)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (d->insert(264)) << std::endl;
std::cout << (b->remove(477)) << std::endl;
std::cout << (e->insert(462)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
std::cout << (d->insert(440)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
*a=*b;
std::cout << (d->insert(440)) << std::endl;
b->printPretty();
std::cout << (d->remove(25)) << std::endl;
std::cout << (b->insert(262)) << std::endl;
*a=*d;
std::cout << (e->insert(462)) << std::endl;
std::cout << (b->insert(458)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
std::cout << (e->remove(462)) << std::endl;
std::cout << (a->remove(248)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
std::cout << (b->insert(443)) << std::endl;
*d=*a;
e->printPretty();
std::cout << (d->remove(229)) << std::endl;
std::cout << (a->remove(102)) << std::endl;
std::cout << (e->remove(495)) << std::endl;
std::cout << (b->remove(391)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (e->remove(420)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
std::cout << (d->remove(367)) << std::endl;
std::cout << (b->remove(167)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
a->printPretty();
std::cout << (a->insert(440)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
*b=*c;
std::cout << (a->remove(305)) << std::endl;
std::cout << (e->insert(310)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (a->remove(232)) << std::endl;
std::cout << (b->insert(298)) << std::endl;
c->printPretty();
a->printPretty();
*b=*e;
std::cout << (b->remove(37)) << std::endl;
*a=*e;
*d=*c;
b->printPretty();
std::cout << (c->insert(299)) << std::endl;
std::cout << (a->insert(310)) << std::endl;
std::cout << (b->remove(310)) << std::endl;
*b=*c;
*d=*e;
std::cout << (d->insert(310)) << std::endl;
std::cout << (c->insert(146)) << std::endl;
std::cout << (b->insert(299)) << std::endl;
c->printPretty();
std::cout << (e->insert(448)) << std::endl;
*d=*e;
std::cout << (a->insert(310)) << std::endl;
*b=*c;
std::cout << (b->remove(431)) << std::endl;
std::cout << (e->remove(323)) << std::endl;
b->printPretty();
e->printPretty();
e->printPretty();
std::cout << (c->insert(46)) << std::endl;
std::cout << (d->insert(448)) << std::endl;
c->printPretty();
std::cout << (c->remove(483)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
std::cout << (e->remove(421)) << std::endl;
c->printPretty();
e->printPretty();
a->printPretty();
std::cout << (b->remove(243)) << std::endl;
return 0;
}
