#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (a->insert(31)) << std::endl;
a->printPretty();
*a=*b;
std::cout << (a->remove(31)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (c->remove(464)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (a->insert(253)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
d->printPretty();
*b=*c;
*c=*a;
a->printPretty();
c->printPretty();
d->printPretty();
c->printPretty();
*e=*d;
*a=*b;
*c=*b;
std::cout << (b->insert(98)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
d->printPretty();
std::cout << (b->remove(98)) << std::endl;
std::cout << (e->insert(214)) << std::endl;
d->printPretty();
std::cout << (c->remove(435)) << std::endl;
d->printPretty();
std::cout << (e->insert(214)) << std::endl;
std::cout << (c->insert(389)) << std::endl;
*a=*a;
std::cout << (c->remove(203)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
std::cout << (b->insert(72)) << std::endl;
*c=*a;
c->printPretty();
b->printPretty();
std::cout << (c->remove(392)) << std::endl;
b->printPretty();
*c=*b;
*d=*d;
e->printPretty();
e->printPretty();
b->printPretty();
std::cout << (a->insert(66)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
std::cout << (a->remove(174)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
std::cout << (e->remove(214)) << std::endl;
d->printPretty();
std::cout << (b->insert(337)) << std::endl;
b->printPretty();
std::cout << (b->insert(337)) << std::endl;
std::cout << (d->remove(292)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
*c=*b;
std::cout << (d->insert(383)) << std::endl;
std::cout << (a->remove(66)) << std::endl;
std::cout << (e->insert(348)) << std::endl;
std::cout << (b->insert(337)) << std::endl;
c->printPretty();
std::cout << (d->remove(383)) << std::endl;
a->printPretty();
std::cout << (b->insert(274)) << std::endl;
std::cout << (e->insert(49)) << std::endl;
std::cout << (d->insert(457)) << std::endl;
std::cout << (d->insert(457)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
std::cout << (d->remove(6)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
*a=*e;
std::cout << (b->insert(337)) << std::endl;
std::cout << (e->remove(49)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
std::cout << (d->insert(103)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
*a=*d;
std::cout << (c->insert(337)) << std::endl;
*e=*c;
std::cout << (c->remove(449)) << std::endl;
std::cout << (a->remove(457)) << std::endl;
*d=*e;
std::cout << (d->remove(353)) << std::endl;
d->printPretty();
std::cout << (d->insert(337)) << std::endl;
std::cout << (e->insert(337)) << std::endl;
std::cout << (c->remove(282)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
*e=*a;
std::cout << (b->remove(172)) << std::endl;
std::cout << (a->insert(162)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
std::cout << (c->insert(134)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
b->printPretty();
std::cout << (d->remove(356)) << std::endl;
a->printPretty();
std::cout << (e->insert(453)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
*e=*b;
std::cout << (d->insert(337)) << std::endl;
std::cout << (b->insert(337)) << std::endl;
*a=*a;
std::cout << (b->insert(337)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
e->printPretty();
std::cout << (e->remove(274)) << std::endl;
std::cout << (b->insert(382)) << std::endl;
*e=*a;
std::cout << (a->insert(409)) << std::endl;
std::cout << (e->remove(162)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
std::cout << (d->insert(306)) << std::endl;
*b=*b;
a->printPretty();
std::cout << (a->insert(409)) << std::endl;
e->printPretty();
std::cout << (b->insert(463)) << std::endl;
std::cout << (a->insert(409)) << std::endl;
std::cout << (b->insert(274)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (c->remove(213)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
*d=*a;
std::cout << (c->remove(134)) << std::endl;
std::cout << (b->insert(15)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (d->remove(443)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
std::cout << (e->insert(337)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->remove(337)) << std::endl;
*a=*d;
std::cout << (b->insert(382)) << std::endl;
std::cout << (b->insert(48)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(337)) << std::endl;
*b=*c;
std::cout << (d->insert(110)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (a->remove(162)) << std::endl;
std::cout << (b->remove(232)) << std::endl;
std::cout << (d->insert(175)) << std::endl;
*a=*b;
std::cout << (c->insert(409)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
*d=*e;
std::cout << (a->insert(126)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (a->insert(288)) << std::endl;
std::cout << (c->remove(409)) << std::endl;
*a=*d;
*a=*d;
std::cout << (c->insert(494)) << std::endl;
std::cout << (d->insert(72)) << std::endl;
std::cout << (a->insert(463)) << std::endl;
a->printPretty();
std::cout << (a->remove(382)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (c->insert(76)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
d->printPretty();
std::cout << (d->insert(463)) << std::endl;
d->printPretty();
std::cout << (b->insert(153)) << std::endl;
*b=*e;
std::cout << (a->insert(274)) << std::endl;
std::cout << (c->insert(469)) << std::endl;
*a=*a;
std::cout << (c->insert(469)) << std::endl;
std::cout << (a->insert(465)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
std::cout << (b->remove(77)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
*a=*a;
std::cout << (a->insert(465)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
std::cout << (e->insert(489)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
c->printPretty();
*d=*c;
std::cout << (b->insert(99)) << std::endl;
*a=*b;
std::cout << (c->remove(494)) << std::endl;
*d=*e;
*d=*c;
std::cout << (a->remove(263)) << std::endl;
std::cout << (c->remove(105)) << std::endl;
*a=*c;
a->printPretty();
std::cout << (b->insert(357)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
*e=*e;
*c=*c;
d->printPretty();
std::cout << (e->remove(274)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
std::cout << (a->insert(469)) << std::endl;
a->printPretty();
std::cout << (a->remove(199)) << std::endl;
*b=*e;
std::cout << (e->insert(107)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
*e=*b;
std::cout << (b->remove(382)) << std::endl;
std::cout << (b->remove(107)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
std::cout << (a->remove(469)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
*c=*e;
*e=*b;
b->printPretty();
std::cout << (b->insert(78)) << std::endl;
std::cout << (e->insert(228)) << std::endl;
std::cout << (d->remove(469)) << std::endl;
std::cout << (d->insert(131)) << std::endl;
*e=*c;
b->printPretty();
a->printPretty();
std::cout << (e->remove(28)) << std::endl;
std::cout << (c->remove(31)) << std::endl;
std::cout << (c->remove(489)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->remove(301)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
c->printPretty();
std::cout << (b->remove(350)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
std::cout << (c->remove(463)) << std::endl;
*d=*e;
d->printPretty();
*e=*a;
std::cout << (c->insert(350)) << std::endl;
std::cout << (d->insert(423)) << std::endl;
a->printPretty();
std::cout << (d->remove(463)) << std::endl;
d->printPretty();
*d=*b;
std::cout << (d->remove(463)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
*b=*d;
std::cout << (a->insert(231)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (a->insert(411)) << std::endl;
std::cout << (c->insert(107)) << std::endl;
*e=*a;
std::cout << (d->insert(289)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
std::cout << (c->insert(107)) << std::endl;
c->printPretty();
std::cout << (b->insert(198)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (c->remove(107)) << std::endl;
std::cout << (b->insert(15)) << std::endl;
*b=*a;
std::cout << (d->insert(289)) << std::endl;
*e=*c;
std::cout << (c->insert(137)) << std::endl;
std::cout << (e->remove(22)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
b->printPretty();
std::cout << (a->insert(466)) << std::endl;
std::cout << (a->insert(231)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
std::cout << (c->remove(342)) << std::endl;
b->printPretty();
std::cout << (e->remove(350)) << std::endl;
std::cout << (e->insert(342)) << std::endl;
*d=*e;
*b=*a;
e->printPretty();
std::cout << (d->remove(116)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
std::cout << (a->insert(20)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
std::cout << (a->remove(51)) << std::endl;
std::cout << (a->remove(474)) << std::endl;
c->printPretty();
std::cout << (d->insert(342)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (b->insert(76)) << std::endl;
std::cout << (e->insert(376)) << std::endl;
std::cout << (e->remove(342)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
std::cout << (c->insert(13)) << std::endl;
b->printPretty();
std::cout << (e->remove(475)) << std::endl;
std::cout << (d->insert(395)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
std::cout << (e->remove(19)) << std::endl;
std::cout << (a->insert(467)) << std::endl;
*b=*e;
c->printPretty();
std::cout << (a->insert(414)) << std::endl;
*d=*e;
*a=*e;
std::cout << (b->remove(376)) << std::endl;
std::cout << (d->remove(459)) << std::endl;
std::cout << (b->insert(35)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
a->printPretty();
std::cout << (b->insert(451)) << std::endl;
b->printPretty();
std::cout << (a->remove(376)) << std::endl;
*d=*c;
*a=*a;
std::cout << (e->insert(436)) << std::endl;
c->printPretty();
std::cout << (b->insert(451)) << std::endl;
std::cout << (d->remove(97)) << std::endl;
*b=*e;
d->printPretty();
*c=*a;
std::cout << (b->insert(436)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
*a=*d;
std::cout << (c->insert(460)) << std::endl;
e->printPretty();
std::cout << (c->remove(259)) << std::endl;
e->printPretty();
std::cout << (a->remove(122)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
std::cout << (e->remove(276)) << std::endl;
std::cout << (c->insert(460)) << std::endl;
std::cout << (a->insert(179)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (a->insert(153)) << std::endl;
*e=*e;
std::cout << (b->insert(460)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
std::cout << (d->insert(65)) << std::endl;
std::cout << (c->remove(287)) << std::endl;
a->printPretty();
std::cout << (e->insert(436)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(259)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
a->printPretty();
std::cout << (e->remove(341)) << std::endl;
std::cout << (c->insert(212)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
*b=*a;
*a=*e;
std::cout << (a->insert(436)) << std::endl;
b->printPretty();
*a=*d;
e->printPretty();
std::cout << (d->insert(350)) << std::endl;
*c=*d;
*b=*e;
std::cout << (c->insert(293)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (e->insert(339)) << std::endl;
*e=*e;
std::cout << (e->remove(65)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
*a=*a;
std::cout << (d->remove(2)) << std::endl;
*a=*d;
std::cout << (b->remove(80)) << std::endl;
c->printPretty();
*a=*d;
std::cout << (a->remove(53)) << std::endl;
std::cout << (d->insert(137)) << std::endl;
std::cout << (d->insert(15)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (c->insert(202)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
e->printPretty();
std::cout << (d->insert(13)) << std::endl;
*a=*e;
std::cout << (a->remove(137)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
c->printPretty();
std::cout << (a->insert(339)) << std::endl;
std::cout << (d->insert(119)) << std::endl;
std::cout << (d->insert(65)) << std::endl;
std::cout << (e->insert(13)) << std::endl;
*b=*e;
std::cout << (c->insert(281)) << std::endl;
std::cout << (c->insert(189)) << std::endl;
e->printPretty();
std::cout << (e->insert(28)) << std::endl;
std::cout << (a->remove(445)) << std::endl;
d->printPretty();
std::cout << (a->insert(339)) << std::endl;
*e=*b;
std::cout << (b->remove(13)) << std::endl;
std::cout << (d->remove(65)) << std::endl;
std::cout << (c->remove(324)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (d->insert(64)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
d->printPretty();
std::cout << (c->remove(350)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (d->remove(64)) << std::endl;
*a=*e;
std::cout << (b->remove(58)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (b->insert(448)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->insert(343)) << std::endl;
c->printPretty();
std::cout << (e->remove(339)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
std::cout << (b->remove(448)) << std::endl;
*d=*e;
std::cout << (e->remove(13)) << std::endl;
*e=*a;
*d=*c;
std::cout << (b->insert(89)) << std::endl;
e->printPretty();
std::cout << (b->remove(148)) << std::endl;
std::cout << (b->remove(137)) << std::endl;
d->printPretty();
std::cout << (a->insert(158)) << std::endl;
*a=*a;
std::cout << (a->remove(322)) << std::endl;
std::cout << (c->insert(329)) << std::endl;
std::cout << (d->insert(109)) << std::endl;
b->printPretty();
std::cout << (d->insert(23)) << std::endl;
std::cout << (c->insert(382)) << std::endl;
std::cout << (e->insert(137)) << std::endl;
c->printPretty();
std::cout << (d->remove(109)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
std::cout << (c->remove(336)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
*b=*d;
std::cout << (a->insert(460)) << std::endl;
d->printPretty();
std::cout << (e->remove(339)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
c->printPretty();
std::cout << (c->remove(382)) << std::endl;
a->printPretty();
std::cout << (c->insert(329)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
c->printPretty();
*e=*e;
std::cout << (d->insert(422)) << std::endl;
a->printPretty();
std::cout << (c->remove(339)) << std::endl;
*d=*c;
std::cout << (d->insert(332)) << std::endl;
std::cout << (a->remove(262)) << std::endl;
c->printPretty();
std::cout << (a->insert(339)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (a->remove(293)) << std::endl;
*e=*a;
std::cout << (b->insert(253)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
std::cout << (d->insert(37)) << std::endl;
std::cout << (e->insert(89)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (e->remove(370)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
std::cout << (d->insert(72)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
a->printPretty();
std::cout << (e->remove(158)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
std::cout << (d->remove(72)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (e->remove(349)) << std::endl;
std::cout << (a->insert(137)) << std::endl;
std::cout << (c->remove(329)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
*a=*b;
std::cout << (a->insert(23)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
std::cout << (a->remove(78)) << std::endl;
*b=*b;
std::cout << (e->remove(107)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (b->insert(23)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(175)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
d->printPretty();
std::cout << (e->remove(137)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (a->insert(488)) << std::endl;
std::cout << (a->remove(18)) << std::endl;
b->printPretty();
*c=*c;
d->printPretty();
std::cout << (d->insert(350)) << std::endl;
std::cout << (d->insert(350)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
std::cout << (b->insert(57)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
d->printPretty();
*a=*d;
b->printPretty();
std::cout << (e->insert(339)) << std::endl;
e->printPretty();
a->printPretty();
e->printPretty();
a->printPretty();
std::cout << (a->remove(67)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
std::cout << (b->insert(180)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (a->remove(200)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
*b=*b;
std::cout << (a->insert(350)) << std::endl;
*d=*e;
std::cout << (c->remove(491)) << std::endl;
b->printPretty();
std::cout << (c->insert(124)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (d->remove(286)) << std::endl;
std::cout << (e->remove(13)) << std::endl;
*d=*e;
std::cout << (c->insert(94)) << std::endl;
a->printPretty();
std::cout << (c->remove(350)) << std::endl;
e->printPretty();
std::cout << (a->insert(24)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
c->printPretty();
*b=*e;
std::cout << (b->remove(493)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
std::cout << (a->remove(223)) << std::endl;
std::cout << (c->insert(94)) << std::endl;
b->printPretty();
std::cout << (b->remove(89)) << std::endl;
*d=*e;
std::cout << (a->remove(289)) << std::endl;
*e=*d;
std::cout << (e->insert(69)) << std::endl;
*d=*a;
std::cout << (c->insert(94)) << std::endl;
std::cout << (e->remove(427)) << std::endl;
*b=*b;
std::cout << (e->insert(89)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (b->insert(339)) << std::endl;
std::cout << (b->insert(385)) << std::endl;
std::cout << (b->insert(267)) << std::endl;
a->printPretty();
std::cout << (a->remove(91)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (b->remove(329)) << std::endl;
std::cout << (a->insert(350)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (c->insert(408)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
std::cout << (a->insert(350)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
std::cout << (c->insert(217)) << std::endl;
a->printPretty();
std::cout << (e->remove(19)) << std::endl;
std::cout << (d->remove(350)) << std::endl;
e->printPretty();
std::cout << (b->insert(79)) << std::endl;
std::cout << (a->insert(350)) << std::endl;
std::cout << (b->remove(381)) << std::endl;
std::cout << (b->insert(79)) << std::endl;
std::cout << (b->remove(385)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
std::cout << (d->insert(43)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
std::cout << (c->insert(280)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
*e=*e;
std::cout << (d->remove(43)) << std::endl;
a->printPretty();
*e=*e;
a->printPretty();
std::cout << (d->insert(260)) << std::endl;
std::cout << (c->insert(328)) << std::endl;
b->printPretty();
std::cout << (e->insert(102)) << std::endl;
std::cout << (d->insert(143)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
*d=*d;
std::cout << (b->insert(339)) << std::endl;
std::cout << (d->remove(347)) << std::endl;
std::cout << (e->remove(287)) << std::endl;
std::cout << (e->insert(229)) << std::endl;
std::cout << (e->remove(89)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
std::cout << (b->remove(339)) << std::endl;
std::cout << (c->remove(217)) << std::endl;
*b=*d;
std::cout << (e->insert(229)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (c->remove(408)) << std::endl;
std::cout << (c->insert(207)) << std::endl;
d->printPretty();
std::cout << (e->remove(394)) << std::endl;
*e=*d;
std::cout << (d->insert(261)) << std::endl;
std::cout << (e->remove(239)) << std::endl;
std::cout << (c->insert(99)) << std::endl;
std::cout << (c->insert(305)) << std::endl;
c->printPretty();
std::cout << (c->remove(124)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (e->insert(143)) << std::endl;
std::cout << (e->remove(299)) << std::endl;
std::cout << (e->remove(143)) << std::endl;
a->printPretty();
std::cout << (a->remove(304)) << std::endl;
std::cout << (c->remove(270)) << std::endl;
std::cout << (e->insert(150)) << std::endl;
*a=*b;
std::cout << (e->remove(459)) << std::endl;
b->printPretty();
std::cout << (b->insert(143)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
std::cout << (b->insert(2)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
e->printPretty();
std::cout << (a->remove(260)) << std::endl;
*d=*d;
std::cout << (c->insert(478)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
*c=*b;
*d=*a;
std::cout << (c->insert(143)) << std::endl;
b->printPretty();
*c=*a;
std::cout << (b->insert(260)) << std::endl;
std::cout << (c->remove(387)) << std::endl;
c->printPretty();
e->printPretty();
b->printPretty();
std::cout << (b->remove(57)) << std::endl;
c->printPretty();
std::cout << (b->insert(449)) << std::endl;
d->printPretty();
std::cout << (b->remove(2)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
std::cout << (a->remove(487)) << std::endl;
*a=*d;
*b=*b;
*e=*b;
*e=*a;
d->printPretty();
a->printPretty();
std::cout << (c->remove(135)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->insert(391)) << std::endl;
*d=*a;
std::cout << (c->remove(270)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (c->insert(155)) << std::endl;
a->printPretty();
std::cout << (b->remove(50)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
*d=*a;
*a=*a;
e->printPretty();
b->printPretty();
return 0;
}
