#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(220)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
a->printPretty();
std::cout << (a->insert(135)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
std::cout << (a->insert(497)) << std::endl;
std::cout << (b->insert(497)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (b->remove(203)) << std::endl;
*b=*a;
b->printPretty();
a->printPretty();
std::cout << (a->remove(443)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (b->remove(459)) << std::endl;
a->printPretty();
*b=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (b->remove(423)) << std::endl;
std::cout << (d->remove(42)) << std::endl;
std::cout << (b->remove(42)) << std::endl;
std::cout << (c->remove(323)) << std::endl;
c->printPretty();
std::cout << (e->remove(42)) << std::endl;
c->printPretty();
std::cout << (b->remove(102)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
std::cout << (a->remove(42)) << std::endl;
b->printPretty();
std::cout << (c->remove(364)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
*c=*d;
std::cout << (c->insert(453)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
std::cout << (c->remove(201)) << std::endl;
std::cout << (b->remove(42)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
std::cout << (a->remove(159)) << std::endl;
*d=*e;
std::cout << (d->insert(56)) << std::endl;
std::cout << (e->insert(56)) << std::endl;
*e=*a;
std::cout << (d->remove(119)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
c->printPretty();
std::cout << (c->remove(41)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
std::cout << (a->insert(17)) << std::endl;
d->printPretty();
std::cout << (e->remove(210)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
std::cout << (e->insert(140)) << std::endl;
*d=*a;
d->printPretty();
c->printPretty();
*a=*e;
b->printPretty();
std::cout << (d->remove(193)) << std::endl;
std::cout << (c->insert(453)) << std::endl;
c->printPretty();
*b=*e;
*d=*c;
std::cout << (c->insert(453)) << std::endl;
std::cout << (d->remove(420)) << std::endl;
std::cout << (d->insert(453)) << std::endl;
std::cout << (e->remove(469)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
std::cout << (d->remove(453)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (c->remove(453)) << std::endl;
std::cout << (d->remove(136)) << std::endl;
std::cout << (b->remove(463)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (a->remove(322)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (d->remove(140)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
std::cout << (e->remove(259)) << std::endl;
std::cout << (a->insert(140)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (a->remove(140)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (d->remove(149)) << std::endl;
*a=*d;
*e=*c;
*d=*d;
b->printPretty();
std::cout << (b->remove(231)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
*e=*b;
std::cout << (d->insert(82)) << std::endl;
e->printPretty();
*a=*e;
*b=*a;
b->printPretty();
std::cout << (b->insert(140)) << std::endl;
std::cout << (e->remove(50)) << std::endl;
*e=*d;
a->printPretty();
std::cout << (c->remove(155)) << std::endl;
d->printPretty();
std::cout << (a->insert(143)) << std::endl;
std::cout << (e->insert(82)) << std::endl;
e->printPretty();
std::cout << (c->remove(66)) << std::endl;
*a=*d;
std::cout << (c->remove(490)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
c->printPretty();
std::cout << (b->remove(140)) << std::endl;
a->printPretty();
std::cout << (a->remove(61)) << std::endl;
*e=*e;
std::cout << (a->insert(347)) << std::endl;
d->printPretty();
std::cout << (c->remove(288)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (a->remove(82)) << std::endl;
*c=*b;
*a=*a;
*e=*c;
std::cout << (e->remove(423)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (c->remove(143)) << std::endl;
*e=*b;
*d=*c;
std::cout << (e->insert(498)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
d->printPretty();
std::cout << (e->remove(498)) << std::endl;
std::cout << (b->insert(279)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
*b=*b;
std::cout << (e->remove(400)) << std::endl;
b->printPretty();
std::cout << (e->remove(143)) << std::endl;
*e=*a;
std::cout << (b->insert(165)) << std::endl;
*c=*b;
std::cout << (c->remove(13)) << std::endl;
*b=*a;
std::cout << (a->remove(210)) << std::endl;
a->printPretty();
std::cout << (c->remove(320)) << std::endl;
std::cout << (c->insert(498)) << std::endl;
e->printPretty();
std::cout << (e->remove(105)) << std::endl;
*c=*a;
std::cout << (b->insert(265)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
e->printPretty();
std::cout << (d->insert(304)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (a->remove(287)) << std::endl;
std::cout << (b->remove(313)) << std::endl;
std::cout << (b->remove(315)) << std::endl;
d->printPretty();
std::cout << (a->remove(70)) << std::endl;
std::cout << (e->insert(457)) << std::endl;
std::cout << (b->insert(488)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
*d=*e;
std::cout << (d->insert(270)) << std::endl;
e->printPretty();
std::cout << (d->remove(270)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (b->remove(436)) << std::endl;
std::cout << (a->insert(119)) << std::endl;
std::cout << (a->remove(260)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
std::cout << (b->remove(488)) << std::endl;
*a=*b;
*c=*c;
*d=*a;
*e=*c;
std::cout << (b->insert(34)) << std::endl;
std::cout << (a->remove(287)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
e->printPretty();
std::cout << (a->remove(319)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(94)) << std::endl;
*c=*e;
std::cout << (a->insert(478)) << std::endl;
std::cout << (c->insert(331)) << std::endl;
std::cout << (a->remove(56)) << std::endl;
*d=*d;
std::cout << (c->insert(181)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
std::cout << (d->insert(249)) << std::endl;
*a=*b;
std::cout << (c->insert(331)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (c->insert(181)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
std::cout << (b->insert(34)) << std::endl;
*a=*d;
*c=*d;
std::cout << (b->insert(500)) << std::endl;
std::cout << (a->insert(294)) << std::endl;
std::cout << (d->insert(294)) << std::endl;
std::cout << (c->remove(168)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
b->printPretty();
std::cout << (d->remove(416)) << std::endl;
a->printPretty();
std::cout << (d->remove(249)) << std::endl;
*a=*d;
std::cout << (d->remove(70)) << std::endl;
a->printPretty();
std::cout << (a->insert(114)) << std::endl;
d->printPretty();
d->printPretty();
*a=*e;
e->printPretty();
*e=*b;
std::cout << (d->remove(211)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
std::cout << (e->remove(268)) << std::endl;
a->printPretty();
d->printPretty();
*e=*c;
d->printPretty();
std::cout << (e->insert(294)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
*b=*c;
b->printPretty();
std::cout << (e->insert(249)) << std::endl;
b->printPretty();
std::cout << (b->remove(294)) << std::endl;
e->printPretty();
std::cout << (e->insert(294)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
d->printPretty();
std::cout << (a->remove(399)) << std::endl;
std::cout << (c->remove(294)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
e->printPretty();
std::cout << (c->insert(468)) << std::endl;
*e=*d;
std::cout << (c->insert(111)) << std::endl;
std::cout << (e->remove(59)) << std::endl;
*b=*c;
std::cout << (b->remove(407)) << std::endl;
*d=*b;
std::cout << (a->insert(486)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
std::cout << (b->remove(468)) << std::endl;
std::cout << (d->insert(249)) << std::endl;
std::cout << (e->remove(100)) << std::endl;
*a=*d;
std::cout << (a->insert(208)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
*a=*c;
std::cout << (b->insert(249)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (c->remove(176)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
std::cout << (d->remove(468)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (c->remove(257)) << std::endl;
std::cout << (b->insert(241)) << std::endl;
*d=*a;
std::cout << (b->remove(449)) << std::endl;
std::cout << (b->remove(241)) << std::endl;
e->printPretty();
std::cout << (b->remove(473)) << std::endl;
*d=*e;
a->printPretty();
*e=*a;
std::cout << (b->insert(249)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
std::cout << (d->insert(264)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
*c=*d;
std::cout << (d->remove(264)) << std::endl;
*d=*b;
std::cout << (b->remove(474)) << std::endl;
std::cout << (e->insert(460)) << std::endl;
b->printPretty();
e->printPretty();
b->printPretty();
std::cout << (c->remove(327)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
std::cout << (a->insert(487)) << std::endl;
std::cout << (d->insert(77)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
std::cout << (d->insert(50)) << std::endl;
std::cout << (e->insert(346)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
d->printPretty();
std::cout << (b->insert(63)) << std::endl;
std::cout << (b->remove(102)) << std::endl;
std::cout << (b->insert(197)) << std::endl;
c->printPretty();
b->printPretty();
*d=*d;
*e=*c;
std::cout << (d->insert(50)) << std::endl;
b->printPretty();
std::cout << (c->remove(84)) << std::endl;
d->printPretty();
std::cout << (e->remove(84)) << std::endl;
*a=*d;
a->printPretty();
std::cout << (d->remove(32)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
std::cout << (a->remove(77)) << std::endl;
std::cout << (c->remove(261)) << std::endl;
std::cout << (e->remove(318)) << std::endl;
std::cout << (a->insert(334)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
d->printPretty();
std::cout << (b->insert(265)) << std::endl;
d->printPretty();
std::cout << (c->remove(77)) << std::endl;
std::cout << (d->insert(255)) << std::endl;
std::cout << (e->remove(264)) << std::endl;
std::cout << (c->remove(285)) << std::endl;
std::cout << (a->insert(334)) << std::endl;
*d=*b;
e->printPretty();
std::cout << (d->remove(349)) << std::endl;
std::cout << (a->insert(249)) << std::endl;
std::cout << (e->remove(147)) << std::endl;
d->printPretty();
std::cout << (d->remove(145)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
c->printPretty();
std::cout << (b->remove(197)) << std::endl;
std::cout << (e->remove(111)) << std::endl;
std::cout << (d->remove(289)) << std::endl;
std::cout << (c->insert(373)) << std::endl;
std::cout << (c->insert(64)) << std::endl;
std::cout << (a->remove(291)) << std::endl;
std::cout << (e->insert(241)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
d->printPretty();
std::cout << (c->insert(64)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (a->remove(9)) << std::endl;
std::cout << (d->insert(249)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->insert(166)) << std::endl;
std::cout << (b->insert(111)) << std::endl;
*a=*d;
*d=*a;
std::cout << (c->remove(264)) << std::endl;
*a=*a;
std::cout << (b->insert(249)) << std::endl;
std::cout << (d->remove(206)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
std::cout << (b->remove(249)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
*e=*c;
c->printPretty();
d->printPretty();
*c=*d;
*d=*b;
*b=*e;
std::cout << (e->remove(315)) << std::endl;
*c=*a;
std::cout << (d->insert(334)) << std::endl;
std::cout << (c->remove(197)) << std::endl;
a->printPretty();
std::cout << (b->insert(388)) << std::endl;
*c=*e;
std::cout << (b->remove(5)) << std::endl;
std::cout << (e->remove(373)) << std::endl;
*d=*e;
std::cout << (d->remove(166)) << std::endl;
*c=*a;
std::cout << (b->remove(388)) << std::endl;
a->printPretty();
std::cout << (b->insert(373)) << std::endl;
*c=*b;
std::cout << (a->remove(197)) << std::endl;
std::cout << (b->remove(226)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
a->printPretty();
std::cout << (d->insert(64)) << std::endl;
*b=*c;
std::cout << (e->insert(166)) << std::endl;
*e=*c;
std::cout << (a->remove(418)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(216)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
std::cout << (b->remove(64)) << std::endl;
std::cout << (d->remove(400)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
std::cout << (c->insert(74)) << std::endl;
*e=*b;
std::cout << (e->remove(272)) << std::endl;
std::cout << (c->insert(166)) << std::endl;
std::cout << (c->insert(213)) << std::endl;
std::cout << (e->remove(164)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
std::cout << (a->remove(265)) << std::endl;
*e=*d;
*d=*e;
*e=*b;
std::cout << (a->insert(58)) << std::endl;
std::cout << (c->remove(11)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (b->insert(373)) << std::endl;
*d=*a;
std::cout << (a->remove(87)) << std::endl;
std::cout << (e->remove(388)) << std::endl;
*e=*c;
std::cout << (c->remove(338)) << std::endl;
std::cout << (e->remove(124)) << std::endl;
*d=*a;
std::cout << (e->remove(484)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
std::cout << (e->remove(64)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
std::cout << (a->insert(58)) << std::endl;
std::cout << (c->remove(383)) << std::endl;
*b=*b;
e->printPretty();
std::cout << (a->insert(399)) << std::endl;
std::cout << (b->insert(305)) << std::endl;
*a=*c;
*e=*a;
a->printPretty();
e->printPretty();
e->printPretty();
*e=*b;
std::cout << (c->insert(140)) << std::endl;
std::cout << (d->remove(393)) << std::endl;
std::cout << (c->insert(140)) << std::endl;
std::cout << (d->insert(111)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (c->insert(178)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
d->printPretty();
std::cout << (c->remove(440)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
std::cout << (d->insert(494)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (e->remove(308)) << std::endl;
d->printPretty();
std::cout << (b->remove(74)) << std::endl;
std::cout << (d->insert(427)) << std::endl;
std::cout << (e->insert(74)) << std::endl;
c->printPretty();
std::cout << (b->remove(166)) << std::endl;
*d=*b;
*d=*c;
std::cout << (c->remove(342)) << std::endl;
a->printPretty();
std::cout << (c->remove(373)) << std::endl;
std::cout << (d->remove(34)) << std::endl;
std::cout << (e->insert(74)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
a->printPretty();
std::cout << (b->insert(457)) << std::endl;
std::cout << (a->remove(213)) << std::endl;
std::cout << (c->insert(74)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
std::cout << (b->insert(373)) << std::endl;
std::cout << (a->remove(166)) << std::endl;
d->printPretty();
std::cout << (b->remove(446)) << std::endl;
*d=*a;
std::cout << (c->insert(242)) << std::endl;
*d=*d;
*d=*a;
std::cout << (e->remove(166)) << std::endl;
std::cout << (c->insert(201)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
a->printPretty();
std::cout << (a->remove(123)) << std::endl;
c->printPretty();
c->printPretty();
*a=*b;
std::cout << (c->remove(213)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
std::cout << (c->insert(39)) << std::endl;
std::cout << (b->insert(213)) << std::endl;
std::cout << (c->remove(203)) << std::endl;
std::cout << (b->remove(373)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
c->printPretty();
std::cout << (b->insert(213)) << std::endl;
std::cout << (d->remove(309)) << std::endl;
std::cout << (a->remove(389)) << std::endl;
a->printPretty();
*e=*c;
std::cout << (e->insert(220)) << std::endl;
std::cout << (c->insert(267)) << std::endl;
d->printPretty();
std::cout << (c->remove(476)) << std::endl;
std::cout << (d->remove(373)) << std::endl;
*a=*d;
std::cout << (e->insert(166)) << std::endl;
*d=*d;
std::cout << (c->remove(166)) << std::endl;
b->printPretty();
std::cout << (b->remove(396)) << std::endl;
*d=*a;
e->printPretty();
a->printPretty();
std::cout << (d->remove(279)) << std::endl;
*b=*b;
std::cout << (b->remove(457)) << std::endl;
*c=*d;
d->printPretty();
*e=*c;
c->printPretty();
std::cout << (d->insert(467)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
std::cout << (a->remove(32)) << std::endl;
std::cout << (a->remove(87)) << std::endl;
*a=*c;
c->printPretty();
std::cout << (c->remove(85)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
*e=*d;
b->printPretty();
c->printPretty();
std::cout << (d->insert(467)) << std::endl;
std::cout << (b->insert(213)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
std::cout << (c->remove(64)) << std::endl;
std::cout << (b->insert(213)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
*d=*d;
std::cout << (e->remove(467)) << std::endl;
*e=*c;
std::cout << (c->insert(112)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (b->insert(420)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
std::cout << (b->insert(173)) << std::endl;
*e=*b;
std::cout << (b->remove(198)) << std::endl;
a->printPretty();
std::cout << (c->remove(112)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
std::cout << (e->remove(91)) << std::endl;
std::cout << (a->remove(217)) << std::endl;
std::cout << (c->insert(244)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
std::cout << (b->insert(213)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->remove(111)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (b->remove(144)) << std::endl;
std::cout << (d->remove(467)) << std::endl;
*b=*b;
std::cout << (d->insert(45)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
*d=*b;
std::cout << (e->insert(420)) << std::endl;
*e=*c;
*d=*e;
std::cout << (a->insert(124)) << std::endl;
std::cout << (d->remove(202)) << std::endl;
std::cout << (b->remove(213)) << std::endl;
std::cout << (c->remove(225)) << std::endl;
*a=*c;
std::cout << (a->insert(244)) << std::endl;
d->printPretty();
std::cout << (e->insert(244)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (a->remove(376)) << std::endl;
d->printPretty();
std::cout << (d->remove(261)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->remove(244)) << std::endl;
std::cout << (c->remove(155)) << std::endl;
e->printPretty();
std::cout << (d->insert(383)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
*a=*c;
std::cout << (e->insert(103)) << std::endl;
std::cout << (b->remove(377)) << std::endl;
*c=*c;
*a=*e;
*c=*d;
std::cout << (d->remove(383)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (b->remove(326)) << std::endl;
std::cout << (a->remove(164)) << std::endl;
e->printPretty();
*e=*a;
*a=*e;
*c=*c;
b->printPretty();
std::cout << (c->remove(383)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
std::cout << (a->remove(195)) << std::endl;
*e=*a;
*c=*d;
std::cout << (d->remove(384)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
b->printPretty();
std::cout << (e->insert(353)) << std::endl;
std::cout << (c->remove(62)) << std::endl;
b->printPretty();
std::cout << (c->remove(323)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
std::cout << (a->remove(240)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
a->printPretty();
std::cout << (c->remove(428)) << std::endl;
*d=*d;
a->printPretty();
std::cout << (b->insert(356)) << std::endl;
*c=*b;
std::cout << (c->insert(356)) << std::endl;
std::cout << (b->remove(173)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
std::cout << (a->insert(103)) << std::endl;
d->printPretty();
std::cout << (b->remove(318)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
std::cout << (a->remove(103)) << std::endl;
std::cout << (e->remove(362)) << std::endl;
std::cout << (a->remove(11)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
*d=*e;
std::cout << (b->insert(420)) << std::endl;
e->printPretty();
std::cout << (c->insert(420)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
*e=*d;
std::cout << (d->remove(20)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
*a=*b;
std::cout << (b->remove(356)) << std::endl;
std::cout << (c->insert(356)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
std::cout << (d->remove(154)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(244)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
std::cout << (b->insert(420)) << std::endl;
std::cout << (c->remove(173)) << std::endl;
std::cout << (c->remove(491)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (d->remove(103)) << std::endl;
a->printPretty();
std::cout << (a->insert(365)) << std::endl;
std::cout << (e->insert(103)) << std::endl;
*c=*d;
*d=*d;
std::cout << (e->remove(244)) << std::endl;
std::cout << (c->remove(384)) << std::endl;
std::cout << (d->insert(20)) << std::endl;
std::cout << (a->insert(100)) << std::endl;
std::cout << (a->insert(442)) << std::endl;
std::cout << (a->insert(333)) << std::endl;
std::cout << (c->remove(19)) << std::endl;
std::cout << (a->remove(368)) << std::endl;
return 0;
}
