#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(27)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->remove(174)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (b->remove(125)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (d->insert(234)) << std::endl;
*c=*c;
std::cout << (a->insert(289)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (a->remove(204)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (d->remove(234)) << std::endl;
c->printPretty();
*e=*b;
*e=*b;
*d=*a;
std::cout << (c->remove(276)) << std::endl;
*e=*a;
std::cout << (c->remove(134)) << std::endl;
b->printPretty();
std::cout << (a->remove(289)) << std::endl;
d->printPretty();
std::cout << (c->insert(302)) << std::endl;
std::cout << (e->insert(289)) << std::endl;
std::cout << (a->insert(494)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (c->insert(96)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (b->insert(88)) << std::endl;
std::cout << (d->remove(119)) << std::endl;
std::cout << (b->insert(47)) << std::endl;
std::cout << (d->insert(289)) << std::endl;
std::cout << (d->remove(344)) << std::endl;
*c=*e;
a->printPretty();
std::cout << (d->insert(434)) << std::endl;
d->printPretty();
std::cout << (d->insert(341)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (c->insert(289)) << std::endl;
std::cout << (a->insert(373)) << std::endl;
*c=*a;
std::cout << (d->remove(289)) << std::endl;
b->printPretty();
*e=*b;
*c=*e;
std::cout << (a->insert(494)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
std::cout << (e->remove(15)) << std::endl;
*b=*c;
std::cout << (b->insert(88)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
std::cout << (e->remove(47)) << std::endl;
std::cout << (a->remove(276)) << std::endl;
b->printPretty();
std::cout << (d->insert(61)) << std::endl;
std::cout << (c->remove(88)) << std::endl;
std::cout << (b->insert(365)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
std::cout << (c->remove(47)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
std::cout << (b->insert(365)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
e->printPretty();
std::cout << (d->remove(321)) << std::endl;
std::cout << (e->insert(298)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
e->printPretty();
std::cout << (d->remove(465)) << std::endl;
*c=*c;
*e=*b;
std::cout << (d->remove(402)) << std::endl;
d->printPretty();
std::cout << (b->insert(191)) << std::endl;
d->printPretty();
std::cout << (d->insert(465)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
std::cout << (e->remove(182)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
*c=*d;
std::cout << (a->remove(373)) << std::endl;
std::cout << (a->remove(411)) << std::endl;
std::cout << (a->remove(494)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (e->remove(47)) << std::endl;
std::cout << (e->remove(88)) << std::endl;
std::cout << (c->insert(465)) << std::endl;
std::cout << (b->remove(191)) << std::endl;
std::cout << (d->insert(465)) << std::endl;
*c=*b;
d->printPretty();
c->printPretty();
a->printPretty();
*e=*b;
std::cout << (b->insert(465)) << std::endl;
d->printPretty();
std::cout << (a->remove(475)) << std::endl;
c->printPretty();
std::cout << (d->remove(229)) << std::endl;
*a=*d;
std::cout << (a->remove(465)) << std::endl;
e->printPretty();
std::cout << (e->remove(47)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (c->insert(299)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
b->printPretty();
std::cout << (d->insert(59)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
*c=*b;
std::cout << (c->remove(80)) << std::endl;
std::cout << (c->remove(74)) << std::endl;
std::cout << (b->remove(365)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (c->insert(88)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (d->remove(180)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
e->printPretty();
std::cout << (b->insert(487)) << std::endl;
std::cout << (d->remove(59)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
b->printPretty();
std::cout << (a->remove(402)) << std::endl;
std::cout << (a->remove(293)) << std::endl;
std::cout << (d->remove(77)) << std::endl;
*e=*e;
std::cout << (d->insert(292)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (b->remove(238)) << std::endl;
std::cout << (e->insert(445)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
*e=*d;
a->printPretty();
*b=*d;
b->printPretty();
std::cout << (b->remove(292)) << std::endl;
c->printPretty();
std::cout << (e->insert(365)) << std::endl;
std::cout << (b->insert(348)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (e->insert(486)) << std::endl;
std::cout << (b->remove(365)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
*b=*d;
std::cout << (d->remove(365)) << std::endl;
e->printPretty();
std::cout << (a->insert(353)) << std::endl;
std::cout << (a->insert(477)) << std::endl;
std::cout << (a->insert(353)) << std::endl;
std::cout << (b->remove(88)) << std::endl;
c->printPretty();
std::cout << (a->insert(431)) << std::endl;
*b=*a;
std::cout << (b->remove(61)) << std::endl;
std::cout << (a->insert(431)) << std::endl;
std::cout << (b->insert(218)) << std::endl;
c->printPretty();
std::cout << (c->insert(428)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
std::cout << (a->insert(152)) << std::endl;
std::cout << (d->remove(156)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
*c=*e;
std::cout << (b->insert(477)) << std::endl;
e->printPretty();
std::cout << (d->remove(54)) << std::endl;
*d=*c;
std::cout << (d->remove(375)) << std::endl;
std::cout << (b->remove(299)) << std::endl;
a->printPretty();
std::cout << (b->remove(391)) << std::endl;
d->printPretty();
std::cout << (a->remove(152)) << std::endl;
std::cout << (e->insert(88)) << std::endl;
*b=*b;
std::cout << (c->insert(486)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (e->remove(292)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (b->remove(353)) << std::endl;
std::cout << (b->remove(372)) << std::endl;
*a=*e;
std::cout << (e->insert(97)) << std::endl;
*c=*d;
c->printPretty();
std::cout << (d->remove(365)) << std::endl;
std::cout << (b->remove(431)) << std::endl;
std::cout << (b->insert(268)) << std::endl;
std::cout << (a->insert(340)) << std::endl;
std::cout << (c->remove(54)) << std::endl;
std::cout << (c->remove(443)) << std::endl;
std::cout << (a->remove(160)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (c->insert(288)) << std::endl;
std::cout << (d->insert(486)) << std::endl;
std::cout << (a->remove(486)) << std::endl;
*e=*c;
std::cout << (a->remove(478)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
std::cout << (b->insert(164)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
c->printPretty();
std::cout << (b->remove(268)) << std::endl;
std::cout << (e->insert(38)) << std::endl;
*a=*a;
std::cout << (c->remove(288)) << std::endl;
*a=*e;
std::cout << (a->insert(415)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
std::cout << (a->remove(292)) << std::endl;
std::cout << (a->remove(62)) << std::endl;
*e=*d;
std::cout << (b->remove(29)) << std::endl;
std::cout << (c->remove(7)) << std::endl;
*e=*b;
std::cout << (c->insert(231)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (b->insert(477)) << std::endl;
std::cout << (a->insert(486)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
a->printPretty();
*b=*a;
*e=*c;
std::cout << (b->insert(88)) << std::endl;
std::cout << (b->insert(38)) << std::endl;
std::cout << (b->remove(415)) << std::endl;
c->printPretty();
std::cout << (a->remove(208)) << std::endl;
std::cout << (e->remove(20)) << std::endl;
*b=*d;
*a=*e;
a->printPretty();
*b=*a;
std::cout << (d->remove(156)) << std::endl;
e->printPretty();
std::cout << (e->remove(88)) << std::endl;
std::cout << (e->remove(442)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (b->insert(160)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (d->remove(486)) << std::endl;
std::cout << (c->insert(356)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (e->insert(135)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
std::cout << (a->remove(365)) << std::endl;
*d=*e;
std::cout << (e->remove(242)) << std::endl;
std::cout << (d->remove(365)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
e->printPretty();
std::cout << (b->insert(399)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
*e=*e;
std::cout << (a->insert(327)) << std::endl;
std::cout << (a->insert(480)) << std::endl;
std::cout << (c->remove(365)) << std::endl;
std::cout << (b->insert(88)) << std::endl;
b->printPretty();
*d=*c;
std::cout << (c->insert(478)) << std::endl;
std::cout << (a->insert(88)) << std::endl;
*a=*a;
a->printPretty();
std::cout << (b->remove(399)) << std::endl;
e->printPretty();
std::cout << (d->insert(478)) << std::endl;
std::cout << (e->remove(415)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
b->printPretty();
a->printPretty();
a->printPretty();
*b=*d;
std::cout << (d->insert(478)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
*c=*d;
std::cout << (d->insert(478)) << std::endl;
std::cout << (a->remove(327)) << std::endl;
std::cout << (c->insert(159)) << std::endl;
*a=*d;
d->printPretty();
std::cout << (d->insert(88)) << std::endl;
b->printPretty();
std::cout << (e->insert(365)) << std::endl;
std::cout << (b->remove(406)) << std::endl;
d->printPretty();
*b=*e;
a->printPretty();
std::cout << (c->insert(478)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
*b=*c;
*b=*c;
std::cout << (b->remove(284)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
*c=*b;
std::cout << (c->remove(187)) << std::endl;
d->printPretty();
std::cout << (c->insert(88)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (a->insert(88)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
d->printPretty();
std::cout << (e->remove(399)) << std::endl;
*a=*c;
std::cout << (c->remove(478)) << std::endl;
*b=*b;
std::cout << (a->insert(88)) << std::endl;
std::cout << (c->remove(159)) << std::endl;
std::cout << (b->remove(159)) << std::endl;
*b=*c;
std::cout << (b->remove(88)) << std::endl;
std::cout << (b->insert(399)) << std::endl;
std::cout << (b->insert(259)) << std::endl;
std::cout << (e->remove(275)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (b->remove(259)) << std::endl;
a->printPretty();
a->printPretty();
b->printPretty();
std::cout << (c->remove(357)) << std::endl;
std::cout << (e->insert(365)) << std::endl;
*e=*b;
std::cout << (b->remove(240)) << std::endl;
std::cout << (c->insert(88)) << std::endl;
b->printPretty();
std::cout << (a->remove(478)) << std::endl;
std::cout << (e->insert(494)) << std::endl;
std::cout << (b->insert(399)) << std::endl;
d->printPretty();
std::cout << (b->remove(339)) << std::endl;
*a=*d;
std::cout << (c->remove(220)) << std::endl;
*c=*e;
std::cout << (c->insert(96)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
std::cout << (a->insert(233)) << std::endl;
std::cout << (d->remove(478)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->remove(399)) << std::endl;
*a=*b;
std::cout << (c->remove(494)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
e->printPretty();
c->printPretty();
*d=*a;
std::cout << (d->remove(469)) << std::endl;
std::cout << (a->insert(306)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
std::cout << (e->remove(390)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
*e=*b;
std::cout << (a->insert(306)) << std::endl;
std::cout << (c->insert(135)) << std::endl;
*b=*c;
std::cout << (a->insert(146)) << std::endl;
std::cout << (b->insert(135)) << std::endl;
a->printPretty();
*c=*b;
*d=*a;
c->printPretty();
std::cout << (c->insert(135)) << std::endl;
std::cout << (e->insert(399)) << std::endl;
std::cout << (e->remove(434)) << std::endl;
c->printPretty();
std::cout << (c->insert(394)) << std::endl;
std::cout << (d->insert(146)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
d->printPretty();
std::cout << (a->remove(200)) << std::endl;
std::cout << (c->insert(135)) << std::endl;
e->printPretty();
std::cout << (b->insert(135)) << std::endl;
*c=*d;
std::cout << (d->remove(146)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
*b=*a;
std::cout << (b->insert(291)) << std::endl;
std::cout << (c->remove(306)) << std::endl;
std::cout << (d->insert(306)) << std::endl;
std::cout << (c->remove(285)) << std::endl;
*e=*a;
std::cout << (a->insert(146)) << std::endl;
std::cout << (e->remove(180)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
std::cout << (d->remove(318)) << std::endl;
std::cout << (d->insert(399)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
e->printPretty();
std::cout << (c->insert(399)) << std::endl;
*c=*b;
std::cout << (e->insert(202)) << std::endl;
std::cout << (c->insert(146)) << std::endl;
d->printPretty();
std::cout << (b->remove(499)) << std::endl;
e->printPretty();
std::cout << (e->remove(399)) << std::endl;
*a=*c;
*d=*d;
std::cout << (c->remove(259)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (a->insert(399)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
std::cout << (a->insert(126)) << std::endl;
std::cout << (a->remove(442)) << std::endl;
c->printPretty();
std::cout << (e->insert(202)) << std::endl;
std::cout << (e->remove(384)) << std::endl;
std::cout << (e->insert(306)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
std::cout << (d->remove(153)) << std::endl;
std::cout << (d->insert(454)) << std::endl;
*d=*b;
std::cout << (e->insert(395)) << std::endl;
*e=*e;
std::cout << (c->remove(399)) << std::endl;
e->printPretty();
std::cout << (e->insert(352)) << std::endl;
e->printPretty();
*e=*e;
e->printPretty();
std::cout << (a->insert(135)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (c->insert(205)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
c->printPretty();
*c=*b;
*c=*c;
std::cout << (e->remove(220)) << std::endl;
std::cout << (d->remove(448)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
std::cout << (d->remove(434)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (a->remove(231)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
d->printPretty();
std::cout << (d->remove(96)) << std::endl;
*d=*a;
a->printPretty();
std::cout << (a->remove(485)) << std::endl;
std::cout << (c->remove(280)) << std::endl;
std::cout << (d->remove(258)) << std::endl;
a->printPretty();
std::cout << (b->remove(399)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
*c=*c;
std::cout << (b->insert(135)) << std::endl;
*e=*a;
std::cout << (c->insert(179)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
std::cout << (c->insert(207)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
*d=*c;
std::cout << (e->insert(80)) << std::endl;
std::cout << (a->remove(135)) << std::endl;
std::cout << (b->insert(65)) << std::endl;
e->printPretty();
std::cout << (e->remove(399)) << std::endl;
std::cout << (c->insert(179)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
c->printPretty();
*d=*a;
*c=*a;
d->printPretty();
std::cout << (e->insert(431)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
*e=*a;
std::cout << (b->remove(499)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (a->remove(341)) << std::endl;
e->printPretty();
std::cout << (c->remove(126)) << std::endl;
std::cout << (d->remove(284)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
e->printPretty();
std::cout << (b->remove(330)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
d->printPretty();
std::cout << (d->remove(182)) << std::endl;
std::cout << (c->remove(3)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (b->insert(135)) << std::endl;
std::cout << (a->insert(291)) << std::endl;
std::cout << (c->insert(437)) << std::endl;
*b=*a;
*b=*d;
std::cout << (c->remove(359)) << std::endl;
std::cout << (c->remove(193)) << std::endl;
std::cout << (b->insert(399)) << std::endl;
*d=*d;
std::cout << (d->insert(497)) << std::endl;
std::cout << (a->remove(437)) << std::endl;
std::cout << (b->insert(414)) << std::endl;
b->printPretty();
std::cout << (c->insert(254)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
e->printPretty();
std::cout << (d->remove(229)) << std::endl;
std::cout << (b->insert(295)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (d->insert(146)) << std::endl;
std::cout << (d->insert(487)) << std::endl;
d->printPretty();
std::cout << (b->remove(211)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
std::cout << (d->insert(38)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
std::cout << (e->insert(459)) << std::endl;
d->printPretty();
std::cout << (e->insert(263)) << std::endl;
e->printPretty();
std::cout << (b->insert(391)) << std::endl;
std::cout << (d->insert(38)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
a->printPretty();
std::cout << (b->remove(195)) << std::endl;
std::cout << (d->remove(307)) << std::endl;
std::cout << (e->remove(166)) << std::endl;
*e=*e;
std::cout << (a->remove(146)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (a->insert(384)) << std::endl;
std::cout << (d->remove(210)) << std::endl;
d->printPretty();
*b=*a;
*b=*c;
b->printPretty();
*a=*b;
std::cout << (c->remove(296)) << std::endl;
a->printPretty();
std::cout << (a->insert(139)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (e->insert(263)) << std::endl;
std::cout << (c->insert(497)) << std::endl;
std::cout << (c->insert(24)) << std::endl;
std::cout << (c->remove(146)) << std::endl;
std::cout << (c->insert(106)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (c->insert(498)) << std::endl;
*c=*c;
std::cout << (c->insert(473)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
std::cout << (e->insert(126)) << std::endl;
*d=*c;
e->printPretty();
*a=*c;
std::cout << (c->insert(254)) << std::endl;
b->printPretty();
std::cout << (e->insert(415)) << std::endl;
*c=*d;
std::cout << (c->insert(126)) << std::endl;
d->printPretty();
std::cout << (d->remove(493)) << std::endl;
e->printPretty();
std::cout << (a->insert(437)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
std::cout << (c->insert(336)) << std::endl;
std::cout << (e->remove(29)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
d->printPretty();
std::cout << (b->insert(83)) << std::endl;
std::cout << (d->insert(437)) << std::endl;
a->printPretty();
*a=*e;
std::cout << (c->insert(437)) << std::endl;
*e=*c;
std::cout << (c->remove(341)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
std::cout << (a->insert(442)) << std::endl;
std::cout << (c->remove(126)) << std::endl;
std::cout << (a->insert(438)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
std::cout << (a->insert(117)) << std::endl;
std::cout << (a->insert(459)) << std::endl;
std::cout << (e->insert(47)) << std::endl;
*b=*a;
std::cout << (a->remove(442)) << std::endl;
std::cout << (d->insert(345)) << std::endl;
std::cout << (c->insert(408)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
*e=*a;
*a=*d;
*b=*a;
std::cout << (e->remove(93)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (e->insert(415)) << std::endl;
*d=*e;
std::cout << (e->insert(459)) << std::endl;
a->printPretty();
std::cout << (d->insert(498)) << std::endl;
*e=*c;
*d=*e;
std::cout << (b->remove(341)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
std::cout << (b->remove(473)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
std::cout << (e->insert(336)) << std::endl;
std::cout << (e->remove(259)) << std::endl;
std::cout << (e->remove(80)) << std::endl;
std::cout << (e->remove(497)) << std::endl;
std::cout << (a->insert(156)) << std::endl;
*c=*c;
*e=*d;
c->printPretty();
e->printPretty();
std::cout << (a->remove(480)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
*c=*d;
std::cout << (d->insert(137)) << std::endl;
std::cout << (d->remove(41)) << std::endl;
c->printPretty();
*c=*e;
c->printPretty();
*c=*e;
e->printPretty();
*c=*a;
std::cout << (b->remove(24)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
std::cout << (e->insert(254)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
d->printPretty();
*b=*c;
a->printPretty();
e->printPretty();
*b=*d;
b->printPretty();
std::cout << (b->remove(264)) << std::endl;
e->printPretty();
std::cout << (b->insert(291)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
std::cout << (e->remove(457)) << std::endl;
*b=*a;
std::cout << (c->insert(156)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
std::cout << (e->remove(79)) << std::endl;
std::cout << (a->remove(381)) << std::endl;
*e=*b;
std::cout << (b->insert(151)) << std::endl;
std::cout << (e->remove(497)) << std::endl;
std::cout << (b->insert(345)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (b->insert(155)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
a->printPretty();
std::cout << (a->insert(489)) << std::endl;
std::cout << (d->remove(306)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
std::cout << (c->insert(345)) << std::endl;
*d=*a;
std::cout << (d->insert(275)) << std::endl;
std::cout << (a->insert(369)) << std::endl;
std::cout << (d->insert(24)) << std::endl;
std::cout << (d->remove(24)) << std::endl;
std::cout << (e->insert(299)) << std::endl;
std::cout << (a->insert(156)) << std::endl;
std::cout << (d->remove(43)) << std::endl;
std::cout << (a->insert(291)) << std::endl;
std::cout << (b->insert(16)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
std::cout << (e->remove(24)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
std::cout << (d->remove(201)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (a->remove(170)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
std::cout << (c->remove(291)) << std::endl;
*a=*b;
e->printPretty();
b->printPretty();
std::cout << (b->remove(345)) << std::endl;
*e=*e;
d->printPretty();
std::cout << (c->insert(199)) << std::endl;
std::cout << (a->insert(16)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
c->printPretty();
std::cout << (d->remove(251)) << std::endl;
std::cout << (e->insert(99)) << std::endl;
std::cout << (a->remove(306)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
std::cout << (d->remove(341)) << std::endl;
std::cout << (e->insert(473)) << std::endl;
std::cout << (e->remove(130)) << std::endl;
*e=*a;
std::cout << (a->remove(473)) << std::endl;
*a=*b;
*e=*e;
std::cout << (b->remove(451)) << std::endl;
std::cout << (d->remove(306)) << std::endl;
std::cout << (d->insert(342)) << std::endl;
*c=*a;
*d=*d;
std::cout << (e->insert(341)) << std::endl;
return 0;
}
