#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
*b=*b;
*b=*b;
std::cout << (b->remove(309)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
a->printPretty();
std::cout << (b->remove(305)) << std::endl;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
std::cout << (a->remove(269)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*b);
std::cout << (c->insert(163)) << std::endl;
*c=*c;
std::cout << (c->insert(193)) << std::endl;
*d=*e;
*d=*a;
b->printPretty();
std::cout << (b->remove(441)) << std::endl;
*c=*c;
std::cout << (c->insert(255)) << std::endl;
e->printPretty();
std::cout << (b->remove(11)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
*a=*b;
*c=*d;
std::cout << (c->remove(23)) << std::endl;
std::cout << (a->remove(386)) << std::endl;
*c=*e;
std::cout << (e->remove(296)) << std::endl;
b->printPretty();
*d=*d;
c->printPretty();
c->printPretty();
std::cout << (b->remove(318)) << std::endl;
e->printPretty();
std::cout << (b->remove(207)) << std::endl;
*c=*b;
std::cout << (d->remove(111)) << std::endl;
a->printPretty();
std::cout << (d->remove(297)) << std::endl;
*e=*b;
*b=*d;
d->printPretty();
*a=*d;
std::cout << (e->remove(459)) << std::endl;
a->printPretty();
std::cout << (b->insert(129)) << std::endl;
*a=*b;
std::cout << (d->insert(17)) << std::endl;
std::cout << (b->insert(24)) << std::endl;
std::cout << (e->remove(497)) << std::endl;
std::cout << (a->remove(129)) << std::endl;
*b=*a;
*d=*b;
*a=*c;
std::cout << (b->remove(12)) << std::endl;
std::cout << (d->remove(311)) << std::endl;
std::cout << (e->insert(438)) << std::endl;
std::cout << (a->insert(7)) << std::endl;
std::cout << (a->remove(7)) << std::endl;
std::cout << (b->remove(152)) << std::endl;
*c=*c;
*b=*a;
*c=*e;
std::cout << (d->insert(52)) << std::endl;
*d=*c;
std::cout << (b->remove(249)) << std::endl;
e->printPretty();
*d=*d;
std::cout << (b->remove(141)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
std::cout << (c->remove(19)) << std::endl;
*e=*b;
std::cout << (a->insert(114)) << std::endl;
a->printPretty();
a->printPretty();
*b=*d;
std::cout << (a->insert(270)) << std::endl;
std::cout << (d->remove(8)) << std::endl;
std::cout << (e->remove(334)) << std::endl;
std::cout << (b->remove(233)) << std::endl;
std::cout << (c->insert(438)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
c->printPretty();
*e=*b;
std::cout << (d->remove(184)) << std::endl;
std::cout << (c->remove(456)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
*b=*d;
std::cout << (e->remove(8)) << std::endl;
std::cout << (a->insert(270)) << std::endl;
c->printPretty();
std::cout << (e->remove(151)) << std::endl;
*e=*a;
*c=*e;
std::cout << (b->remove(191)) << std::endl;
std::cout << (a->remove(270)) << std::endl;
std::cout << (c->remove(110)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
*c=*d;
std::cout << (a->remove(439)) << std::endl;
std::cout << (c->remove(388)) << std::endl;
*c=*a;
std::cout << (b->insert(176)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
*b=*b;
std::cout << (d->insert(456)) << std::endl;
c->printPretty();
std::cout << (d->insert(456)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
*c=*d;
std::cout << (c->remove(456)) << std::endl;
std::cout << (d->insert(456)) << std::endl;
std::cout << (d->insert(477)) << std::endl;
std::cout << (d->insert(170)) << std::endl;
e->printPretty();
std::cout << (a->remove(298)) << std::endl;
b->printPretty();
std::cout << (a->insert(472)) << std::endl;
std::cout << (d->remove(170)) << std::endl;
std::cout << (d->remove(5)) << std::endl;
*a=*c;
std::cout << (e->remove(419)) << std::endl;
std::cout << (d->insert(390)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (d->remove(456)) << std::endl;
d->printPretty();
*a=*c;
*a=*b;
std::cout << (b->remove(176)) << std::endl;
a->printPretty();
std::cout << (a->insert(385)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
d->printPretty();
std::cout << (a->insert(385)) << std::endl;
std::cout << (d->insert(3)) << std::endl;
b->printPretty();
std::cout << (e->remove(270)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
std::cout << (e->insert(441)) << std::endl;
std::cout << (c->insert(227)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (a->remove(176)) << std::endl;
std::cout << (a->remove(13)) << std::endl;
c->printPretty();
std::cout << (a->remove(277)) << std::endl;
std::cout << (a->remove(426)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
c->printPretty();
std::cout << (a->remove(315)) << std::endl;
std::cout << (e->insert(114)) << std::endl;
std::cout << (e->remove(142)) << std::endl;
*d=*a;
*a=*e;
*c=*c;
std::cout << (d->remove(134)) << std::endl;
e->printPretty();
std::cout << (a->insert(114)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
*d=*e;
std::cout << (b->remove(427)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->insert(58)) << std::endl;
*b=*d;
*c=*a;
*e=*e;
a->printPretty();
*b=*e;
std::cout << (e->insert(133)) << std::endl;
*d=*b;
std::cout << (d->remove(129)) << std::endl;
b->printPretty();
std::cout << (a->remove(67)) << std::endl;
std::cout << (c->remove(301)) << std::endl;
b->printPretty();
std::cout << (c->insert(441)) << std::endl;
std::cout << (e->insert(133)) << std::endl;
c->printPretty();
std::cout << (b->insert(114)) << std::endl;
std::cout << (b->remove(66)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (d->remove(107)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
*d=*e;
std::cout << (b->remove(171)) << std::endl;
std::cout << (d->insert(72)) << std::endl;
std::cout << (d->insert(286)) << std::endl;
*a=*a;
std::cout << (e->insert(114)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (d->remove(114)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
std::cout << (a->insert(291)) << std::endl;
std::cout << (d->insert(5)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (c->remove(321)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
b->printPretty();
std::cout << (c->insert(383)) << std::endl;
b->printPretty();
std::cout << (a->insert(119)) << std::endl;
std::cout << (d->remove(133)) << std::endl;
std::cout << (d->remove(138)) << std::endl;
std::cout << (a->insert(497)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
a->printPretty();
std::cout << (d->remove(306)) << std::endl;
std::cout << (c->insert(58)) << std::endl;
*e=*c;
std::cout << (a->remove(2)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (a->insert(441)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
std::cout << (c->insert(45)) << std::endl;
std::cout << (c->insert(197)) << std::endl;
*a=*c;
b->printPretty();
std::cout << (b->insert(315)) << std::endl;
c->printPretty();
*c=*d;
d->printPretty();
c->printPretty();
*c=*a;
std::cout << (a->insert(45)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (d->insert(47)) << std::endl;
e->printPretty();
e->printPretty();
*d=*e;
std::cout << (d->insert(114)) << std::endl;
e->printPretty();
std::cout << (d->remove(217)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
*a=*c;
std::cout << (b->insert(121)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
c->printPretty();
std::cout << (d->remove(291)) << std::endl;
*e=*a;
*b=*a;
*b=*c;
std::cout << (d->insert(107)) << std::endl;
b->printPretty();
std::cout << (b->remove(92)) << std::endl;
std::cout << (c->insert(58)) << std::endl;
*e=*c;
std::cout << (a->insert(286)) << std::endl;
b->printPretty();
*b=*a;
std::cout << (a->remove(286)) << std::endl;
*b=*a;
a->printPretty();
*b=*b;
std::cout << (c->insert(299)) << std::endl;
std::cout << (e->remove(183)) << std::endl;
std::cout << (c->insert(272)) << std::endl;
std::cout << (c->insert(272)) << std::endl;
*a=*b;
std::cout << (e->remove(441)) << std::endl;
*e=*e;
c->printPretty();
b->printPretty();
std::cout << (d->remove(114)) << std::endl;
e->printPretty();
std::cout << (c->insert(441)) << std::endl;
std::cout << (c->remove(423)) << std::endl;
std::cout << (c->insert(5)) << std::endl;
d->printPretty();
std::cout << (c->remove(234)) << std::endl;
*c=*c;
*b=*a;
std::cout << (b->insert(441)) << std::endl;
std::cout << (b->remove(31)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
*e=*d;
std::cout << (c->remove(150)) << std::endl;
d->printPretty();
std::cout << (c->remove(134)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (c->insert(473)) << std::endl;
*d=*b;
std::cout << (b->insert(72)) << std::endl;
c->printPretty();
std::cout << (e->insert(441)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
b->printPretty();
d->printPretty();
*e=*b;
a->printPretty();
std::cout << (c->insert(404)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
std::cout << (c->insert(305)) << std::endl;
std::cout << (e->insert(5)) << std::endl;
*c=*a;
a->printPretty();
*c=*b;
std::cout << (a->insert(25)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
std::cout << (e->insert(67)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
std::cout << (a->remove(441)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (b->remove(72)) << std::endl;
*b=*d;
std::cout << (b->insert(5)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
*e=*b;
std::cout << (b->insert(238)) << std::endl;
std::cout << (c->remove(441)) << std::endl;
std::cout << (d->remove(260)) << std::endl;
std::cout << (e->remove(453)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
b->printPretty();
std::cout << (d->remove(5)) << std::endl;
*c=*a;
std::cout << (c->insert(407)) << std::endl;
*e=*a;
*b=*d;
std::cout << (a->insert(220)) << std::endl;
std::cout << (e->insert(323)) << std::endl;
std::cout << (b->remove(441)) << std::endl;
std::cout << (b->insert(72)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
*d=*b;
*e=*a;
std::cout << (e->remove(72)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (b->remove(473)) << std::endl;
*d=*a;
std::cout << (a->remove(72)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
std::cout << (a->remove(278)) << std::endl;
std::cout << (a->remove(5)) << std::endl;
std::cout << (d->insert(96)) << std::endl;
std::cout << (c->insert(72)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (b->insert(186)) << std::endl;
d->printPretty();
std::cout << (a->remove(176)) << std::endl;
b->printPretty();
*e=*d;
std::cout << (b->remove(475)) << std::endl;
std::cout << (c->insert(72)) << std::endl;
std::cout << (d->remove(72)) << std::endl;
std::cout << (c->insert(72)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (d->remove(5)) << std::endl;
std::cout << (c->remove(72)) << std::endl;
d->printPretty();
std::cout << (e->insert(96)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
*b=*a;
std::cout << (d->insert(96)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (a->insert(203)) << std::endl;
std::cout << (b->insert(326)) << std::endl;
*a=*a;
std::cout << (c->insert(219)) << std::endl;
*b=*b;
std::cout << (b->remove(326)) << std::endl;
*d=*b;
std::cout << (a->insert(106)) << std::endl;
*a=*e;
d->printPretty();
std::cout << (b->remove(142)) << std::endl;
std::cout << (b->insert(443)) << std::endl;
c->printPretty();
*c=*e;
std::cout << (c->insert(52)) << std::endl;
std::cout << (c->insert(5)) << std::endl;
std::cout << (b->remove(287)) << std::endl;
std::cout << (a->insert(331)) << std::endl;
std::cout << (d->remove(428)) << std::endl;
*a=*d;
std::cout << (e->remove(96)) << std::endl;
*b=*e;
a->printPretty();
std::cout << (c->remove(25)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
std::cout << (b->remove(170)) << std::endl;
std::cout << (c->remove(464)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
std::cout << (a->remove(287)) << std::endl;
*a=*c;
std::cout << (d->insert(287)) << std::endl;
std::cout << (e->remove(72)) << std::endl;
a->printPretty();
std::cout << (d->remove(287)) << std::endl;
std::cout << (b->remove(72)) << std::endl;
std::cout << (e->remove(5)) << std::endl;
*d=*c;
std::cout << (e->remove(139)) << std::endl;
*d=*e;
d->printPretty();
std::cout << (b->remove(5)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (a->remove(52)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (c->remove(5)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (d->insert(25)) << std::endl;
std::cout << (b->insert(39)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
std::cout << (a->remove(109)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->insert(52)) << std::endl;
*e=*d;
std::cout << (d->remove(25)) << std::endl;
std::cout << (c->remove(262)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
std::cout << (e->remove(25)) << std::endl;
std::cout << (a->insert(5)) << std::endl;
std::cout << (b->insert(25)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
c->printPretty();
std::cout << (a->insert(22)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (a->remove(22)) << std::endl;
*e=*c;
std::cout << (b->remove(159)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
d->printPretty();
b->printPretty();
e->printPretty();
std::cout << (b->insert(492)) << std::endl;
std::cout << (c->remove(67)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
e->printPretty();
std::cout << (a->insert(221)) << std::endl;
*c=*c;
*a=*b;
a->printPretty();
std::cout << (a->insert(492)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (a->remove(440)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
*a=*c;
std::cout << (b->remove(442)) << std::endl;
std::cout << (e->remove(52)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (d->remove(423)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
*e=*c;
std::cout << (d->insert(72)) << std::endl;
*a=*e;
std::cout << (d->remove(52)) << std::endl;
*b=*c;
std::cout << (d->insert(400)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (b->remove(231)) << std::endl;
std::cout << (e->insert(370)) << std::endl;
std::cout << (d->remove(477)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
*a=*b;
std::cout << (c->remove(431)) << std::endl;
std::cout << (a->remove(403)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
std::cout << (c->insert(248)) << std::endl;
c->printPretty();
std::cout << (d->insert(72)) << std::endl;
std::cout << (d->remove(72)) << std::endl;
*d=*e;
std::cout << (b->remove(72)) << std::endl;
*a=*c;
std::cout << (b->remove(52)) << std::endl;
std::cout << (e->insert(370)) << std::endl;
*a=*e;
std::cout << (d->remove(475)) << std::endl;
*a=*b;
std::cout << (b->insert(299)) << std::endl;
std::cout << (b->remove(229)) << std::endl;
b->printPretty();
std::cout << (d->insert(370)) << std::endl;
std::cout << (c->remove(426)) << std::endl;
c->printPretty();
a->printPretty();
a->printPretty();
std::cout << (e->insert(72)) << std::endl;
*e=*d;
std::cout << (b->remove(137)) << std::endl;
*b=*b;
std::cout << (a->insert(321)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
*d=*b;
std::cout << (b->insert(426)) << std::endl;
std::cout << (c->insert(353)) << std::endl;
std::cout << (e->remove(370)) << std::endl;
*d=*a;
std::cout << (d->insert(321)) << std::endl;
std::cout << (d->remove(321)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
c->printPretty();
std::cout << (d->remove(431)) << std::endl;
*e=*c;
e->printPretty();
std::cout << (e->remove(346)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->insert(125)) << std::endl;
d->printPretty();
std::cout << (c->insert(72)) << std::endl;
*c=*a;
std::cout << (e->insert(353)) << std::endl;
std::cout << (a->insert(330)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
d->printPretty();
std::cout << (e->insert(99)) << std::endl;
std::cout << (e->insert(108)) << std::endl;
std::cout << (c->insert(431)) << std::endl;
*c=*e;
d->printPretty();
std::cout << (b->insert(476)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (a->insert(63)) << std::endl;
std::cout << (e->insert(423)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
e->printPretty();
std::cout << (b->remove(431)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
std::cout << (e->insert(440)) << std::endl;
c->printPretty();
std::cout << (c->remove(475)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
*b=*c;
std::cout << (c->insert(252)) << std::endl;
std::cout << (a->remove(426)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
a->printPretty();
std::cout << (e->remove(353)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
std::cout << (b->insert(280)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->remove(99)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
a->printPretty();
std::cout << (d->insert(167)) << std::endl;
*b=*a;
d->printPretty();
std::cout << (d->insert(157)) << std::endl;
std::cout << (c->insert(321)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
a->printPretty();
*b=*d;
*c=*c;
std::cout << (d->remove(400)) << std::endl;
std::cout << (d->insert(201)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
std::cout << (a->insert(86)) << std::endl;
e->printPretty();
std::cout << (d->remove(339)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
*e=*d;
std::cout << (d->remove(378)) << std::endl;
std::cout << (d->insert(52)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (d->insert(69)) << std::endl;
a->printPretty();
std::cout << (c->remove(182)) << std::endl;
std::cout << (a->insert(69)) << std::endl;
*c=*c;
*d=*e;
std::cout << (e->remove(256)) << std::endl;
std::cout << (b->remove(17)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
*a=*b;
std::cout << (a->remove(167)) << std::endl;
*c=*c;
std::cout << (c->insert(321)) << std::endl;
std::cout << (a->remove(56)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
*a=*b;
std::cout << (c->remove(436)) << std::endl;
std::cout << (a->insert(218)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
*a=*d;
std::cout << (c->insert(376)) << std::endl;
c->printPretty();
std::cout << (d->insert(201)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
*a=*e;
std::cout << (d->remove(201)) << std::endl;
std::cout << (d->remove(157)) << std::endl;
std::cout << (b->remove(167)) << std::endl;
std::cout << (c->remove(248)) << std::endl;
*a=*c;
*d=*b;
std::cout << (a->insert(252)) << std::endl;
std::cout << (d->remove(141)) << std::endl;
std::cout << (d->remove(401)) << std::endl;
std::cout << (a->insert(32)) << std::endl;
std::cout << (a->insert(12)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
*b=*e;
std::cout << (c->insert(498)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->insert(201)) << std::endl;
std::cout << (e->insert(476)) << std::endl;
std::cout << (e->remove(176)) << std::endl;
std::cout << (e->insert(157)) << std::endl;
std::cout << (c->insert(108)) << std::endl;
b->printPretty();
std::cout << (e->remove(305)) << std::endl;
*d=*c;
std::cout << (c->insert(108)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
std::cout << (a->insert(125)) << std::endl;
std::cout << (b->remove(201)) << std::endl;
std::cout << (a->insert(494)) << std::endl;
std::cout << (e->remove(201)) << std::endl;
*c=*d;
std::cout << (d->remove(465)) << std::endl;
std::cout << (c->insert(436)) << std::endl;
std::cout << (e->insert(35)) << std::endl;
std::cout << (c->insert(125)) << std::endl;
*a=*d;
std::cout << (b->insert(25)) << std::endl;
std::cout << (b->remove(177)) << std::endl;
std::cout << (b->insert(25)) << std::endl;
std::cout << (d->insert(376)) << std::endl;
d->printPretty();
std::cout << (d->remove(498)) << std::endl;
std::cout << (b->remove(2)) << std::endl;
std::cout << (e->remove(35)) << std::endl;
std::cout << (a->remove(108)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
b->printPretty();
std::cout << (a->remove(438)) << std::endl;
std::cout << (b->insert(25)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
b->printPretty();
std::cout << (d->remove(253)) << std::endl;
std::cout << (e->insert(408)) << std::endl;
*e=*c;
std::cout << (c->remove(125)) << std::endl;
std::cout << (c->remove(436)) << std::endl;
*d=*d;
std::cout << (e->remove(436)) << std::endl;
d->printPretty();
std::cout << (d->insert(321)) << std::endl;
c->printPretty();
std::cout << (e->insert(498)) << std::endl;
std::cout << (e->remove(252)) << std::endl;
std::cout << (b->remove(34)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (e->remove(321)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
d->printPretty();
*a=*e;
std::cout << (e->insert(498)) << std::endl;
std::cout << (c->remove(376)) << std::endl;
*c=*d;
c->printPretty();
d->printPretty();
*a=*e;
std::cout << (c->insert(72)) << std::endl;
std::cout << (a->remove(335)) << std::endl;
std::cout << (a->insert(427)) << std::endl;
std::cout << (e->remove(9)) << std::endl;
b->printPretty();
*b=*e;
std::cout << (a->remove(471)) << std::endl;
a->printPretty();
std::cout << (b->remove(376)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
std::cout << (e->insert(353)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (b->remove(108)) << std::endl;
return 0;
}
