#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(200)) << std::endl;
a->printPretty();
std::cout << (a->insert(358)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (a->remove(200)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
std::cout << (a->remove(358)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (c->remove(478)) << std::endl;
std::cout << (e->insert(256)) << std::endl;
*c=*c;
*e=*c;
std::cout << (e->insert(86)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
b->printPretty();
std::cout << (c->remove(86)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (c->insert(237)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (a->remove(337)) << std::endl;
std::cout << (a->remove(112)) << std::endl;
std::cout << (e->remove(86)) << std::endl;
*a=*a;
std::cout << (b->insert(56)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
std::cout << (b->insert(81)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
*e=*e;
b->printPretty();
std::cout << (c->remove(145)) << std::endl;
c->printPretty();
std::cout << (c->insert(237)) << std::endl;
std::cout << (c->insert(68)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
*d=*b;
std::cout << (c->insert(68)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (c->insert(168)) << std::endl;
*e=*d;
std::cout << (b->insert(360)) << std::endl;
b->printPretty();
std::cout << (a->remove(420)) << std::endl;
std::cout << (a->remove(452)) << std::endl;
std::cout << (c->remove(237)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
a->printPretty();
std::cout << (b->remove(45)) << std::endl;
e->printPretty();
std::cout << (a->remove(382)) << std::endl;
std::cout << (b->insert(99)) << std::endl;
std::cout << (a->insert(133)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
std::cout << (a->insert(133)) << std::endl;
std::cout << (d->insert(375)) << std::endl;
std::cout << (e->remove(56)) << std::endl;
std::cout << (e->remove(488)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (a->insert(21)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
std::cout << (e->insert(375)) << std::endl;
std::cout << (c->remove(18)) << std::endl;
std::cout << (c->insert(299)) << std::endl;
std::cout << (c->insert(386)) << std::endl;
std::cout << (e->remove(300)) << std::endl;
std::cout << (a->remove(21)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
*c=*d;
std::cout << (b->insert(360)) << std::endl;
std::cout << (c->insert(56)) << std::endl;
b->printPretty();
std::cout << (d->remove(452)) << std::endl;
*d=*b;
std::cout << (b->remove(375)) << std::endl;
*b=*a;
std::cout << (b->remove(124)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (d->insert(312)) << std::endl;
std::cout << (c->insert(91)) << std::endl;
std::cout << (b->remove(185)) << std::endl;
e->printPretty();
std::cout << (d->remove(1)) << std::endl;
*a=*e;
std::cout << (e->insert(230)) << std::endl;
b->printPretty();
std::cout << (d->remove(200)) << std::endl;
c->printPretty();
std::cout << (b->insert(441)) << std::endl;
std::cout << (a->remove(53)) << std::endl;
std::cout << (d->insert(142)) << std::endl;
std::cout << (b->insert(441)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
std::cout << (c->remove(91)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
*b=*e;
std::cout << (a->insert(61)) << std::endl;
*e=*d;
*e=*b;
std::cout << (e->insert(281)) << std::endl;
std::cout << (c->remove(289)) << std::endl;
std::cout << (a->insert(192)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
std::cout << (d->insert(304)) << std::endl;
d->printPretty();
std::cout << (a->remove(36)) << std::endl;
std::cout << (b->remove(230)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
c->printPretty();
std::cout << (a->insert(383)) << std::endl;
std::cout << (e->insert(2)) << std::endl;
std::cout << (d->insert(436)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
*b=*c;
std::cout << (b->remove(289)) << std::endl;
std::cout << (d->insert(266)) << std::endl;
std::cout << (c->remove(375)) << std::endl;
std::cout << (a->insert(9)) << std::endl;
std::cout << (d->insert(375)) << std::endl;
std::cout << (c->insert(173)) << std::endl;
std::cout << (e->remove(2)) << std::endl;
std::cout << (d->remove(497)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
e->printPretty();
std::cout << (c->insert(173)) << std::endl;
std::cout << (d->insert(190)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (c->remove(173)) << std::endl;
std::cout << (e->remove(281)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
d->printPretty();
std::cout << (d->remove(312)) << std::endl;
std::cout << (c->remove(116)) << std::endl;
*c=*d;
*a=*a;
std::cout << (a->insert(9)) << std::endl;
d->printPretty();
std::cout << (b->insert(143)) << std::endl;
std::cout << (b->remove(56)) << std::endl;
std::cout << (a->insert(383)) << std::endl;
std::cout << (a->insert(496)) << std::endl;
std::cout << (d->remove(142)) << std::endl;
c->printPretty();
std::cout << (b->remove(108)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
c->printPretty();
std::cout << (d->remove(155)) << std::endl;
std::cout << (a->insert(114)) << std::endl;
std::cout << (a->insert(192)) << std::endl;
std::cout << (b->remove(97)) << std::endl;
std::cout << (c->remove(142)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
a->printPretty();
std::cout << (e->insert(279)) << std::endl;
std::cout << (c->insert(266)) << std::endl;
std::cout << (d->remove(99)) << std::endl;
std::cout << (d->remove(208)) << std::endl;
c->printPretty();
std::cout << (d->insert(485)) << std::endl;
std::cout << (a->remove(114)) << std::endl;
std::cout << (c->insert(99)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
*e=*b;
std::cout << (b->insert(116)) << std::endl;
*b=*e;
std::cout << (d->remove(304)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (b->insert(211)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
*a=*b;
std::cout << (d->remove(190)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
std::cout << (e->remove(332)) << std::endl;
a->printPretty();
*b=*d;
a->printPretty();
std::cout << (b->remove(266)) << std::endl;
std::cout << (a->remove(163)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
*d=*a;
std::cout << (d->insert(211)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
std::cout << (a->remove(257)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
*a=*a;
std::cout << (d->remove(235)) << std::endl;
*b=*d;
std::cout << (a->remove(27)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
std::cout << (d->remove(483)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
b->printPretty();
std::cout << (d->insert(162)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
d->printPretty();
std::cout << (a->insert(152)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
std::cout << (b->insert(228)) << std::endl;
std::cout << (b->remove(375)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
std::cout << (d->insert(162)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
std::cout << (d->remove(161)) << std::endl;
std::cout << (c->remove(399)) << std::endl;
std::cout << (a->insert(112)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
std::cout << (a->remove(335)) << std::endl;
std::cout << (a->remove(152)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
*b=*e;
e->printPretty();
std::cout << (d->insert(251)) << std::endl;
std::cout << (c->insert(136)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
*c=*e;
std::cout << (c->remove(146)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(187)) << std::endl;
*e=*d;
b->printPretty();
e->printPretty();
std::cout << (d->remove(251)) << std::endl;
b->printPretty();
std::cout << (d->remove(198)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->remove(105)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
std::cout << (a->remove(330)) << std::endl;
std::cout << (e->insert(251)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
std::cout << (e->remove(251)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (e->insert(198)) << std::endl;
d->printPretty();
std::cout << (c->remove(354)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (c->remove(123)) << std::endl;
std::cout << (d->remove(375)) << std::endl;
std::cout << (c->remove(153)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
std::cout << (d->remove(215)) << std::endl;
std::cout << (b->insert(99)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
*c=*c;
std::cout << (e->insert(198)) << std::endl;
d->printPretty();
std::cout << (c->remove(49)) << std::endl;
*d=*a;
std::cout << (e->remove(476)) << std::endl;
*e=*d;
std::cout << (b->insert(99)) << std::endl;
*b=*a;
std::cout << (d->remove(429)) << std::endl;
*a=*d;
std::cout << (c->insert(318)) << std::endl;
e->printPretty();
std::cout << (e->remove(460)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
*d=*a;
d->printPretty();
std::cout << (e->insert(27)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
*a=*c;
e->printPretty();
std::cout << (a->insert(318)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
std::cout << (d->insert(152)) << std::endl;
*d=*b;
*d=*e;
std::cout << (a->remove(270)) << std::endl;
std::cout << (d->remove(271)) << std::endl;
*d=*c;
std::cout << (d->remove(100)) << std::endl;
d->printPretty();
std::cout << (c->remove(421)) << std::endl;
*d=*e;
std::cout << (c->insert(318)) << std::endl;
*d=*e;
std::cout << (c->insert(318)) << std::endl;
std::cout << (e->insert(467)) << std::endl;
std::cout << (a->insert(2)) << std::endl;
std::cout << (d->remove(27)) << std::endl;
*c=*c;
std::cout << (d->insert(416)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
*e=*c;
*b=*a;
d->printPretty();
a->printPretty();
*e=*a;
b->printPretty();
std::cout << (a->remove(35)) << std::endl;
*d=*e;
e->printPretty();
std::cout << (d->remove(318)) << std::endl;
std::cout << (a->insert(318)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
e->printPretty();
*b=*e;
c->printPretty();
e->printPretty();
d->printPretty();
c->printPretty();
std::cout << (e->remove(318)) << std::endl;
std::cout << (e->remove(394)) << std::endl;
e->printPretty();
std::cout << (d->remove(2)) << std::endl;
std::cout << (d->insert(102)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
std::cout << (a->remove(402)) << std::endl;
*d=*d;
a->printPretty();
*c=*b;
std::cout << (e->insert(2)) << std::endl;
*e=*c;
std::cout << (b->insert(318)) << std::endl;
std::cout << (d->insert(394)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
std::cout << (b->remove(45)) << std::endl;
a->printPretty();
std::cout << (a->insert(394)) << std::endl;
*c=*c;
e->printPretty();
a->printPretty();
std::cout << (b->remove(455)) << std::endl;
*b=*c;
std::cout << (a->insert(2)) << std::endl;
b->printPretty();
std::cout << (a->remove(203)) << std::endl;
std::cout << (b->insert(311)) << std::endl;
e->printPretty();
d->printPretty();
*e=*d;
std::cout << (b->remove(311)) << std::endl;
*b=*a;
std::cout << (a->insert(2)) << std::endl;
*a=*e;
*a=*c;
*e=*c;
std::cout << (a->remove(479)) << std::endl;
c->printPretty();
b->printPretty();
d->printPretty();
*b=*b;
std::cout << (d->insert(394)) << std::endl;
std::cout << (b->remove(394)) << std::endl;
*e=*a;
std::cout << (e->remove(2)) << std::endl;
*a=*c;
e->printPretty();
d->printPretty();
b->printPretty();
std::cout << (e->remove(394)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (a->remove(16)) << std::endl;
std::cout << (b->remove(2)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
std::cout << (d->insert(303)) << std::endl;
std::cout << (d->insert(303)) << std::endl;
std::cout << (d->remove(394)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (d->insert(211)) << std::endl;
*a=*e;
e->printPretty();
std::cout << (e->insert(295)) << std::endl;
*b=*c;
std::cout << (e->remove(295)) << std::endl;
std::cout << (e->insert(297)) << std::endl;
*e=*d;
std::cout << (d->remove(318)) << std::endl;
std::cout << (e->remove(2)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
*b=*b;
*d=*a;
std::cout << (c->remove(2)) << std::endl;
*d=*c;
std::cout << (c->remove(99)) << std::endl;
*d=*b;
std::cout << (b->insert(394)) << std::endl;
*c=*c;
*b=*b;
std::cout << (a->insert(375)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (a->remove(375)) << std::endl;
*e=*c;
std::cout << (c->remove(394)) << std::endl;
*b=*a;
std::cout << (c->insert(173)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
d->printPretty();
std::cout << (a->remove(199)) << std::endl;
d->printPretty();
std::cout << (e->insert(394)) << std::endl;
*c=*d;
b->printPretty();
a->printPretty();
d->printPretty();
std::cout << (e->insert(394)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (d->insert(143)) << std::endl;
std::cout << (c->remove(275)) << std::endl;
*d=*e;
a->printPretty();
a->printPretty();
std::cout << (c->insert(460)) << std::endl;
std::cout << (d->remove(83)) << std::endl;
std::cout << (b->remove(69)) << std::endl;
a->printPretty();
std::cout << (e->insert(248)) << std::endl;
*b=*c;
std::cout << (c->remove(460)) << std::endl;
a->printPretty();
std::cout << (c->insert(394)) << std::endl;
*c=*a;
*d=*e;
std::cout << (d->remove(248)) << std::endl;
std::cout << (e->insert(248)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
*d=*c;
std::cout << (b->remove(2)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->insert(304)) << std::endl;
*e=*a;
*d=*a;
std::cout << (a->insert(373)) << std::endl;
*e=*c;
std::cout << (e->remove(199)) << std::endl;
std::cout << (b->insert(104)) << std::endl;
a->printPretty();
std::cout << (b->remove(460)) << std::endl;
*d=*d;
std::cout << (e->remove(217)) << std::endl;
*d=*c;
std::cout << (e->insert(476)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (d->remove(170)) << std::endl;
d->printPretty();
std::cout << (a->insert(373)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
std::cout << (a->insert(419)) << std::endl;
*e=*e;
e->printPretty();
std::cout << (a->insert(294)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
std::cout << (b->insert(104)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
std::cout << (e->remove(395)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->insert(86)) << std::endl;
std::cout << (a->remove(477)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
*d=*d;
b->printPretty();
b->printPretty();
std::cout << (d->insert(333)) << std::endl;
*e=*d;
std::cout << (a->insert(304)) << std::endl;
std::cout << (d->insert(400)) << std::endl;
std::cout << (e->remove(232)) << std::endl;
std::cout << (a->remove(419)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
c->printPretty();
*d=*a;
*e=*e;
std::cout << (d->insert(304)) << std::endl;
std::cout << (d->remove(304)) << std::endl;
std::cout << (b->insert(4)) << std::endl;
std::cout << (c->remove(107)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
std::cout << (b->insert(489)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
std::cout << (e->insert(476)) << std::endl;
*a=*b;
std::cout << (d->insert(231)) << std::endl;
std::cout << (a->insert(489)) << std::endl;
a->printPretty();
std::cout << (d->insert(231)) << std::endl;
std::cout << (a->remove(349)) << std::endl;
std::cout << (b->insert(394)) << std::endl;
std::cout << (d->remove(21)) << std::endl;
e->printPretty();
std::cout << (e->remove(476)) << std::endl;
*e=*d;
*b=*b;
std::cout << (a->insert(4)) << std::endl;
*b=*c;
std::cout << (d->remove(454)) << std::endl;
std::cout << (e->remove(231)) << std::endl;
std::cout << (e->remove(176)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
std::cout << (c->insert(134)) << std::endl;
*a=*a;
std::cout << (e->insert(218)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (a->remove(394)) << std::endl;
b->printPretty();
std::cout << (e->remove(301)) << std::endl;
c->printPretty();
std::cout << (e->insert(414)) << std::endl;
a->printPretty();
std::cout << (e->insert(66)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->remove(134)) << std::endl;
b->printPretty();
std::cout << (c->insert(172)) << std::endl;
std::cout << (e->insert(320)) << std::endl;
std::cout << (d->remove(231)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
*e=*d;
*b=*b;
std::cout << (d->insert(53)) << std::endl;
*b=*a;
std::cout << (a->insert(489)) << std::endl;
std::cout << (c->insert(172)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
*c=*e;
std::cout << (a->insert(150)) << std::endl;
*c=*e;
std::cout << (b->insert(201)) << std::endl;
std::cout << (a->insert(228)) << std::endl;
c->printPretty();
std::cout << (c->remove(395)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (b->insert(308)) << std::endl;
e->printPretty();
std::cout << (a->remove(220)) << std::endl;
b->printPretty();
std::cout << (a->insert(258)) << std::endl;
std::cout << (e->insert(53)) << std::endl;
std::cout << (b->insert(350)) << std::endl;
std::cout << (b->insert(173)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
e->printPretty();
std::cout << (a->remove(150)) << std::endl;
std::cout << (b->remove(220)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
b->printPretty();
std::cout << (d->insert(53)) << std::endl;
*c=*d;
std::cout << (d->insert(11)) << std::endl;
std::cout << (b->insert(493)) << std::endl;
std::cout << (a->remove(228)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (d->insert(278)) << std::endl;
std::cout << (d->insert(237)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (c->remove(21)) << std::endl;
std::cout << (d->remove(278)) << std::endl;
std::cout << (c->remove(361)) << std::endl;
b->printPretty();
std::cout << (a->remove(258)) << std::endl;
std::cout << (b->remove(281)) << std::endl;
std::cout << (a->insert(459)) << std::endl;
e->printPretty();
std::cout << (e->remove(26)) << std::endl;
std::cout << (b->remove(245)) << std::endl;
std::cout << (c->insert(110)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
*e=*c;
e->printPretty();
std::cout << (d->remove(53)) << std::endl;
std::cout << (d->insert(237)) << std::endl;
std::cout << (e->remove(110)) << std::endl;
*b=*d;
std::cout << (d->remove(237)) << std::endl;
*d=*c;
std::cout << (e->remove(53)) << std::endl;
std::cout << (e->remove(439)) << std::endl;
d->printPretty();
std::cout << (a->remove(228)) << std::endl;
std::cout << (a->remove(49)) << std::endl;
std::cout << (a->insert(394)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (c->insert(110)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
c->printPretty();
std::cout << (b->remove(244)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
std::cout << (c->remove(260)) << std::endl;
*d=*a;
std::cout << (d->insert(394)) << std::endl;
std::cout << (b->insert(237)) << std::endl;
std::cout << (b->remove(237)) << std::endl;
b->printPretty();
std::cout << (d->remove(4)) << std::endl;
c->printPretty();
std::cout << (b->insert(156)) << std::endl;
c->printPretty();
std::cout << (d->insert(90)) << std::endl;
*d=*c;
std::cout << (d->insert(189)) << std::endl;
b->printPretty();
std::cout << (d->insert(16)) << std::endl;
std::cout << (c->remove(110)) << std::endl;
*a=*d;
std::cout << (d->insert(473)) << std::endl;
std::cout << (c->insert(267)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (d->insert(267)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
std::cout << (d->remove(333)) << std::endl;
std::cout << (d->remove(473)) << std::endl;
*a=*d;
std::cout << (c->remove(267)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
a->printPretty();
std::cout << (b->remove(393)) << std::endl;
std::cout << (b->remove(55)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
std::cout << (a->remove(250)) << std::endl;
std::cout << (a->insert(368)) << std::endl;
std::cout << (b->remove(324)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (c->insert(227)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
*c=*b;
std::cout << (d->remove(431)) << std::endl;
*a=*a;
std::cout << (e->remove(291)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (d->remove(441)) << std::endl;
std::cout << (c->remove(253)) << std::endl;
std::cout << (e->remove(274)) << std::endl;
b->printPretty();
std::cout << (e->remove(418)) << std::endl;
c->printPretty();
std::cout << (c->remove(156)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
std::cout << (b->remove(308)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->insert(243)) << std::endl;
*d=*e;
return 0;
}
