#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(484)) << std::endl;
std::cout << (a->insert(30)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
a->printPretty();
std::cout << (a->remove(334)) << std::endl;
std::cout << (e->remove(139)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (c->insert(372)) << std::endl;
std::cout << (a->remove(30)) << std::endl;
std::cout << (b->remove(370)) << std::endl;
*b=*a;
e->printPretty();
e->printPretty();
std::cout << (c->insert(339)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
*e=*b;
std::cout << (c->remove(499)) << std::endl;
*e=*c;
std::cout << (c->insert(393)) << std::endl;
*c=*a;
std::cout << (e->remove(195)) << std::endl;
c->printPretty();
std::cout << (e->insert(279)) << std::endl;
c->printPretty();
*d=*d;
std::cout << (d->remove(166)) << std::endl;
*c=*a;
std::cout << (b->remove(350)) << std::endl;
*b=*c;
*a=*a;
std::cout << (e->remove(339)) << std::endl;
std::cout << (b->insert(9)) << std::endl;
std::cout << (a->insert(243)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
std::cout << (c->insert(98)) << std::endl;
std::cout << (a->insert(265)) << std::endl;
*a=*c;
*c=*a;
*c=*a;
*c=*d;
std::cout << (d->insert(497)) << std::endl;
std::cout << (e->remove(54)) << std::endl;
*e=*e;
d->printPretty();
*c=*e;
std::cout << (a->insert(98)) << std::endl;
std::cout << (c->insert(120)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->remove(279)) << std::endl;
*c=*d;
*e=*c;
*b=*a;
std::cout << (d->remove(497)) << std::endl;
std::cout << (b->insert(98)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
*a=*b;
*c=*a;
*d=*e;
std::cout << (c->insert(98)) << std::endl;
a->printPretty();
*d=*b;
std::cout << (b->remove(98)) << std::endl;
std::cout << (c->insert(379)) << std::endl;
std::cout << (e->remove(478)) << std::endl;
std::cout << (b->insert(219)) << std::endl;
b->printPretty();
std::cout << (e->remove(497)) << std::endl;
*b=*c;
b->printPretty();
*a=*d;
*d=*b;
std::cout << (e->remove(274)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
std::cout << (b->remove(397)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
d->printPretty();
std::cout << (e->insert(386)) << std::endl;
*c=*a;
std::cout << (c->insert(226)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
e->printPretty();
std::cout << (e->remove(386)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
std::cout << (c->insert(226)) << std::endl;
*b=*b;
std::cout << (c->insert(68)) << std::endl;
std::cout << (b->remove(292)) << std::endl;
std::cout << (c->remove(226)) << std::endl;
*b=*c;
c->printPretty();
std::cout << (a->insert(378)) << std::endl;
std::cout << (b->insert(98)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (c->remove(494)) << std::endl;
std::cout << (e->insert(211)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->remove(259)) << std::endl;
*b=*e;
d->printPretty();
std::cout << (b->insert(99)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (a->insert(378)) << std::endl;
std::cout << (b->insert(327)) << std::endl;
std::cout << (b->insert(307)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (d->remove(295)) << std::endl;
c->printPretty();
std::cout << (a->remove(229)) << std::endl;
std::cout << (e->remove(211)) << std::endl;
std::cout << (b->remove(99)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
d->printPretty();
std::cout << (a->remove(378)) << std::endl;
std::cout << (e->remove(247)) << std::endl;
std::cout << (a->remove(451)) << std::endl;
e->printPretty();
std::cout << (d->remove(379)) << std::endl;
std::cout << (b->remove(338)) << std::endl;
std::cout << (d->remove(98)) << std::endl;
std::cout << (a->remove(143)) << std::endl;
std::cout << (e->remove(307)) << std::endl;
b->printPretty();
std::cout << (c->insert(98)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(212)) << std::endl;
*c=*d;
std::cout << (a->insert(98)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
c->printPretty();
std::cout << (b->remove(250)) << std::endl;
std::cout << (a->insert(304)) << std::endl;
std::cout << (a->remove(235)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
d->printPretty();
a->printPretty();
*e=*e;
std::cout << (d->insert(437)) << std::endl;
*d=*e;
std::cout << (e->remove(409)) << std::endl;
std::cout << (d->insert(295)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (c->insert(129)) << std::endl;
b->printPretty();
std::cout << (c->insert(362)) << std::endl;
*e=*e;
std::cout << (c->insert(101)) << std::endl;
a->printPretty();
std::cout << (c->remove(28)) << std::endl;
std::cout << (a->insert(234)) << std::endl;
std::cout << (d->insert(244)) << std::endl;
*e=*c;
*b=*a;
std::cout << (a->remove(77)) << std::endl;
std::cout << (c->insert(129)) << std::endl;
std::cout << (b->remove(236)) << std::endl;
std::cout << (a->remove(20)) << std::endl;
std::cout << (b->insert(365)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
a->printPretty();
std::cout << (d->insert(295)) << std::endl;
std::cout << (a->remove(98)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
*e=*c;
std::cout << (b->remove(98)) << std::endl;
std::cout << (c->remove(362)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
std::cout << (c->remove(458)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
*d=*e;
std::cout << (e->remove(232)) << std::endl;
std::cout << (d->insert(362)) << std::endl;
e->printPretty();
std::cout << (b->insert(304)) << std::endl;
e->printPretty();
std::cout << (e->remove(129)) << std::endl;
std::cout << (a->insert(305)) << std::endl;
std::cout << (b->remove(365)) << std::endl;
std::cout << (b->remove(337)) << std::endl;
std::cout << (e->remove(101)) << std::endl;
std::cout << (d->remove(251)) << std::endl;
*a=*d;
std::cout << (d->insert(460)) << std::endl;
c->printPretty();
*e=*d;
std::cout << (a->remove(101)) << std::endl;
std::cout << (b->remove(234)) << std::endl;
std::cout << (d->remove(129)) << std::endl;
std::cout << (b->insert(295)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
a->printPretty();
std::cout << (c->remove(399)) << std::endl;
c->printPretty();
std::cout << (b->remove(304)) << std::endl;
std::cout << (e->insert(199)) << std::endl;
std::cout << (e->remove(101)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
std::cout << (a->insert(129)) << std::endl;
*b=*d;
*c=*b;
std::cout << (a->insert(129)) << std::endl;
a->printPretty();
*e=*e;
std::cout << (d->insert(101)) << std::endl;
std::cout << (e->insert(95)) << std::endl;
*a=*d;
*d=*d;
std::cout << (d->insert(153)) << std::endl;
std::cout << (d->insert(465)) << std::endl;
std::cout << (c->insert(460)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
*d=*e;
std::cout << (e->remove(2)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
std::cout << (e->remove(135)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->remove(101)) << std::endl;
b->printPretty();
*e=*a;
std::cout << (c->remove(353)) << std::endl;
std::cout << (a->remove(460)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (c->remove(346)) << std::endl;
std::cout << (e->remove(460)) << std::endl;
std::cout << (e->insert(350)) << std::endl;
*c=*e;
std::cout << (e->insert(164)) << std::endl;
std::cout << (c->remove(362)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (a->insert(401)) << std::endl;
std::cout << (b->remove(443)) << std::endl;
std::cout << (b->insert(101)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
*d=*c;
std::cout << (c->insert(59)) << std::endl;
std::cout << (d->insert(151)) << std::endl;
*c=*e;
b->printPretty();
*e=*c;
std::cout << (c->remove(362)) << std::endl;
std::cout << (a->insert(95)) << std::endl;
std::cout << (d->remove(260)) << std::endl;
c->printPretty();
std::cout << (d->remove(350)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
a->printPretty();
a->printPretty();
b->printPretty();
std::cout << (b->insert(101)) << std::endl;
std::cout << (d->remove(153)) << std::endl;
std::cout << (c->insert(350)) << std::endl;
std::cout << (e->insert(454)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (a->remove(429)) << std::endl;
e->printPretty();
std::cout << (c->insert(164)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
*c=*a;
e->printPretty();
*b=*d;
*a=*b;
std::cout << (d->insert(151)) << std::endl;
std::cout << (c->insert(230)) << std::endl;
std::cout << (e->remove(350)) << std::endl;
std::cout << (a->remove(152)) << std::endl;
*e=*e;
std::cout << (d->remove(138)) << std::endl;
std::cout << (a->insert(485)) << std::endl;
e->printPretty();
std::cout << (a->remove(33)) << std::endl;
*e=*a;
std::cout << (e->insert(492)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
std::cout << (b->remove(151)) << std::endl;
std::cout << (c->remove(84)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
std::cout << (c->remove(306)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
*a=*a;
*a=*d;
std::cout << (c->insert(230)) << std::endl;
std::cout << (c->insert(75)) << std::endl;
std::cout << (e->insert(159)) << std::endl;
std::cout << (c->insert(95)) << std::endl;
std::cout << (e->remove(485)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (c->insert(215)) << std::endl;
c->printPretty();
std::cout << (c->insert(145)) << std::endl;
std::cout << (c->remove(230)) << std::endl;
*e=*c;
*d=*c;
c->printPretty();
std::cout << (e->remove(460)) << std::endl;
std::cout << (a->insert(151)) << std::endl;
std::cout << (b->remove(70)) << std::endl;
e->printPretty();
std::cout << (d->remove(129)) << std::endl;
std::cout << (b->remove(351)) << std::endl;
std::cout << (b->remove(331)) << std::endl;
std::cout << (a->remove(328)) << std::endl;
std::cout << (b->insert(479)) << std::endl;
a->printPretty();
std::cout << (e->insert(429)) << std::endl;
std::cout << (b->insert(321)) << std::endl;
std::cout << (d->insert(145)) << std::endl;
std::cout << (e->remove(145)) << std::endl;
*e=*a;
std::cout << (d->remove(198)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
std::cout << (c->insert(145)) << std::endl;
a->printPretty();
d->printPretty();
std::cout << (d->remove(126)) << std::endl;
e->printPretty();
std::cout << (e->insert(419)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
*a=*d;
b->printPretty();
*d=*b;
std::cout << (a->insert(210)) << std::endl;
std::cout << (d->insert(313)) << std::endl;
a->printPretty();
std::cout << (a->insert(215)) << std::endl;
a->printPretty();
std::cout << (c->remove(129)) << std::endl;
std::cout << (b->remove(321)) << std::endl;
std::cout << (b->remove(387)) << std::endl;
a->printPretty();
std::cout << (e->remove(388)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
std::cout << (c->insert(271)) << std::endl;
std::cout << (a->remove(362)) << std::endl;
*b=*b;
std::cout << (d->insert(321)) << std::endl;
std::cout << (a->insert(75)) << std::endl;
std::cout << (e->insert(419)) << std::endl;
b->printPretty();
std::cout << (c->remove(399)) << std::endl;
*b=*b;
std::cout << (e->remove(363)) << std::endl;
std::cout << (e->insert(107)) << std::endl;
b->printPretty();
std::cout << (e->remove(71)) << std::endl;
std::cout << (d->remove(321)) << std::endl;
std::cout << (a->insert(210)) << std::endl;
*a=*c;
std::cout << (d->insert(313)) << std::endl;
std::cout << (c->insert(145)) << std::endl;
std::cout << (b->insert(235)) << std::endl;
b->printPretty();
std::cout << (b->insert(235)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
*b=*d;
std::cout << (a->insert(199)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(313)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
std::cout << (e->remove(419)) << std::endl;
*a=*a;
*e=*e;
b->printPretty();
b->printPretty();
std::cout << (e->remove(109)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (c->remove(415)) << std::endl;
std::cout << (b->remove(198)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->insert(313)) << std::endl;
std::cout << (d->remove(313)) << std::endl;
std::cout << (c->remove(52)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
std::cout << (c->remove(271)) << std::endl;
std::cout << (b->remove(410)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
std::cout << (b->insert(313)) << std::endl;
std::cout << (c->insert(500)) << std::endl;
std::cout << (b->remove(176)) << std::endl;
*a=*e;
*b=*d;
std::cout << (a->insert(110)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->insert(110)) << std::endl;
std::cout << (e->remove(399)) << std::endl;
std::cout << (d->remove(312)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (c->remove(145)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
*d=*a;
std::cout << (c->remove(75)) << std::endl;
b->printPretty();
d->printPretty();
*d=*d;
std::cout << (d->remove(245)) << std::endl;
std::cout << (c->insert(287)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
*d=*a;
*a=*a;
std::cout << (a->insert(110)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
c->printPretty();
std::cout << (b->remove(279)) << std::endl;
*b=*e;
std::cout << (d->remove(419)) << std::endl;
d->printPretty();
std::cout << (c->remove(362)) << std::endl;
std::cout << (d->insert(110)) << std::endl;
std::cout << (d->insert(479)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
std::cout << (e->remove(92)) << std::endl;
*b=*a;
*a=*c;
std::cout << (b->insert(248)) << std::endl;
std::cout << (e->remove(266)) << std::endl;
std::cout << (e->remove(26)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (e->insert(111)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (b->insert(156)) << std::endl;
std::cout << (c->insert(478)) << std::endl;
std::cout << (d->insert(32)) << std::endl;
std::cout << (d->insert(479)) << std::endl;
std::cout << (c->insert(287)) << std::endl;
std::cout << (e->insert(192)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
c->printPretty();
std::cout << (b->remove(261)) << std::endl;
std::cout << (e->insert(12)) << std::endl;
std::cout << (e->insert(267)) << std::endl;
*e=*d;
std::cout << (c->remove(215)) << std::endl;
*a=*c;
d->printPretty();
c->printPretty();
std::cout << (c->remove(135)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
*b=*d;
std::cout << (e->insert(479)) << std::endl;
std::cout << (e->remove(422)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
*e=*d;
std::cout << (b->insert(467)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
*e=*c;
std::cout << (d->insert(245)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (d->insert(479)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (a->remove(95)) << std::endl;
*e=*d;
std::cout << (a->remove(500)) << std::endl;
std::cout << (d->remove(435)) << std::endl;
std::cout << (a->insert(397)) << std::endl;
e->printPretty();
std::cout << (b->insert(226)) << std::endl;
std::cout << (c->insert(146)) << std::endl;
std::cout << (b->remove(12)) << std::endl;
std::cout << (c->remove(82)) << std::endl;
std::cout << (d->insert(213)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
e->printPretty();
std::cout << (d->remove(32)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
a->printPretty();
std::cout << (c->insert(500)) << std::endl;
c->printPretty();
std::cout << (d->remove(435)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (b->remove(32)) << std::endl;
std::cout << (a->insert(227)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
*e=*b;
std::cout << (e->remove(479)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (c->insert(163)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
*b=*a;
std::cout << (b->remove(273)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
std::cout << (a->remove(136)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (a->remove(34)) << std::endl;
*c=*e;
std::cout << (b->insert(478)) << std::endl;
std::cout << (d->remove(419)) << std::endl;
std::cout << (a->remove(397)) << std::endl;
std::cout << (d->insert(374)) << std::endl;
*c=*b;
std::cout << (a->insert(158)) << std::endl;
std::cout << (a->remove(146)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
a->printPretty();
std::cout << (a->insert(468)) << std::endl;
std::cout << (d->remove(374)) << std::endl;
std::cout << (a->insert(478)) << std::endl;
b->printPretty();
*c=*a;
c->printPretty();
std::cout << (a->insert(166)) << std::endl;
std::cout << (c->remove(432)) << std::endl;
*e=*b;
std::cout << (b->remove(199)) << std::endl;
std::cout << (d->insert(53)) << std::endl;
std::cout << (c->insert(138)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
std::cout << (a->remove(197)) << std::endl;
e->printPretty();
std::cout << (a->remove(468)) << std::endl;
std::cout << (a->insert(237)) << std::endl;
b->printPretty();
std::cout << (b->remove(478)) << std::endl;
std::cout << (c->insert(172)) << std::endl;
std::cout << (a->insert(166)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
std::cout << (a->remove(199)) << std::endl;
*e=*b;
*b=*d;
b->printPretty();
std::cout << (c->insert(450)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
*a=*b;
e->printPretty();
std::cout << (c->insert(123)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (d->remove(82)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
*a=*c;
std::cout << (d->remove(237)) << std::endl;
*b=*a;
std::cout << (a->remove(172)) << std::endl;
*a=*e;
std::cout << (c->insert(123)) << std::endl;
std::cout << (a->remove(427)) << std::endl;
std::cout << (e->remove(483)) << std::endl;
a->printPretty();
std::cout << (b->remove(21)) << std::endl;
std::cout << (b->insert(110)) << std::endl;
std::cout << (c->insert(139)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (c->insert(110)) << std::endl;
std::cout << (c->insert(364)) << std::endl;
*e=*a;
*c=*c;
a->printPretty();
std::cout << (c->insert(138)) << std::endl;
b->printPretty();
std::cout << (d->insert(313)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
*b=*e;
std::cout << (d->insert(313)) << std::endl;
std::cout << (d->insert(149)) << std::endl;
std::cout << (c->remove(364)) << std::endl;
std::cout << (c->insert(398)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
a->printPretty();
std::cout << (b->insert(322)) << std::endl;
std::cout << (a->insert(55)) << std::endl;
std::cout << (c->remove(268)) << std::endl;
a->printPretty();
std::cout << (d->insert(484)) << std::endl;
std::cout << (d->remove(149)) << std::endl;
std::cout << (a->remove(211)) << std::endl;
std::cout << (e->remove(397)) << std::endl;
std::cout << (c->remove(434)) << std::endl;
*c=*b;
std::cout << (c->remove(397)) << std::endl;
*e=*e;
std::cout << (d->insert(319)) << std::endl;
std::cout << (d->insert(422)) << std::endl;
b->printPretty();
*b=*b;
*b=*a;
std::cout << (a->remove(26)) << std::endl;
*b=*c;
std::cout << (a->insert(402)) << std::endl;
std::cout << (a->remove(264)) << std::endl;
std::cout << (a->insert(287)) << std::endl;
*b=*e;
std::cout << (c->remove(292)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (b->insert(214)) << std::endl;
*a=*d;
d->printPretty();
d->printPretty();
std::cout << (a->insert(317)) << std::endl;
e->printPretty();
std::cout << (e->remove(227)) << std::endl;
std::cout << (c->remove(163)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
*a=*d;
c->printPretty();
std::cout << (a->remove(484)) << std::endl;
std::cout << (d->insert(11)) << std::endl;
std::cout << (d->remove(11)) << std::endl;
std::cout << (d->insert(18)) << std::endl;
std::cout << (d->insert(216)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
e->printPretty();
b->printPretty();
*e=*c;
std::cout << (e->remove(322)) << std::endl;
std::cout << (d->remove(319)) << std::endl;
*c=*b;
d->printPretty();
std::cout << (e->insert(227)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
*c=*d;
*a=*e;
std::cout << (a->insert(70)) << std::endl;
d->printPretty();
std::cout << (c->insert(204)) << std::endl;
d->printPretty();
e->printPretty();
*d=*e;
std::cout << (c->insert(216)) << std::endl;
std::cout << (b->remove(227)) << std::endl;
*b=*a;
*e=*a;
std::cout << (b->remove(287)) << std::endl;
*a=*b;
std::cout << (e->insert(84)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->remove(228)) << std::endl;
std::cout << (e->remove(227)) << std::endl;
std::cout << (c->remove(140)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (d->remove(298)) << std::endl;
*d=*c;
b->printPretty();
*a=*c;
std::cout << (c->remove(216)) << std::endl;
*a=*b;
*d=*b;
std::cout << (a->insert(389)) << std::endl;
*c=*e;
std::cout << (d->insert(142)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (b->insert(484)) << std::endl;
d->printPretty();
std::cout << (b->remove(313)) << std::endl;
e->printPretty();
std::cout << (b->insert(484)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
std::cout << (b->insert(409)) << std::endl;
c->printPretty();
std::cout << (d->insert(313)) << std::endl;
std::cout << (e->insert(48)) << std::endl;
*c=*a;
*a=*b;
std::cout << (a->insert(244)) << std::endl;
a->printPretty();
std::cout << (c->remove(483)) << std::endl;
std::cout << (e->insert(215)) << std::endl;
c->printPretty();
std::cout << (d->insert(323)) << std::endl;
std::cout << (c->remove(206)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
std::cout << (b->remove(30)) << std::endl;
*d=*c;
c->printPretty();
*a=*e;
*c=*e;
return 0;
}
