#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*a=*b;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (b->insert(39)) << std::endl;
std::cout << (e->remove(474)) << std::endl;
c->printPretty();
std::cout << (d->insert(33)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
b->printPretty();
std::cout << (d->remove(71)) << std::endl;
std::cout << (b->remove(44)) << std::endl;
std::cout << (d->insert(413)) << std::endl;
*c=*e;
*d=*c;
std::cout << (e->remove(294)) << std::endl;
*b=*d;
std::cout << (a->insert(298)) << std::endl;
d->printPretty();
std::cout << (e->insert(309)) << std::endl;
std::cout << (b->insert(254)) << std::endl;
std::cout << (c->remove(83)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
*a=*a;
std::cout << (e->remove(482)) << std::endl;
*e=*c;
std::cout << (e->remove(73)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->insert(274)) << std::endl;
std::cout << (b->remove(104)) << std::endl;
*b=*e;
*b=*b;
std::cout << (e->remove(15)) << std::endl;
d->printPretty();
std::cout << (d->remove(274)) << std::endl;
*a=*e;
a->printPretty();
c->printPretty();
std::cout << (d->insert(473)) << std::endl;
std::cout << (d->insert(365)) << std::endl;
a->printPretty();
std::cout << (e->remove(253)) << std::endl;
std::cout << (e->remove(107)) << std::endl;
std::cout << (a->insert(172)) << std::endl;
std::cout << (c->remove(147)) << std::endl;
std::cout << (d->insert(473)) << std::endl;
*e=*c;
std::cout << (a->insert(172)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
*d=*c;
std::cout << (a->remove(320)) << std::endl;
c->printPretty();
std::cout << (b->remove(120)) << std::endl;
std::cout << (b->insert(398)) << std::endl;
std::cout << (d->remove(267)) << std::endl;
std::cout << (b->insert(253)) << std::endl;
std::cout << (b->remove(253)) << std::endl;
std::cout << (b->insert(398)) << std::endl;
std::cout << (c->insert(309)) << std::endl;
*a=*c;
std::cout << (a->remove(309)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
*c=*d;
std::cout << (c->remove(235)) << std::endl;
std::cout << (b->remove(158)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
c->printPretty();
std::cout << (b->insert(136)) << std::endl;
*b=*e;
std::cout << (c->remove(394)) << std::endl;
std::cout << (b->remove(264)) << std::endl;
*e=*a;
std::cout << (e->insert(353)) << std::endl;
std::cout << (e->insert(353)) << std::endl;
c->printPretty();
std::cout << (e->insert(353)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (e->insert(484)) << std::endl;
*b=*e;
std::cout << (b->insert(457)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
a->printPretty();
d->printPretty();
c->printPretty();
std::cout << (b->insert(457)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (b->insert(84)) << std::endl;
std::cout << (b->remove(148)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (d->insert(164)) << std::endl;
std::cout << (c->insert(243)) << std::endl;
std::cout << (b->remove(171)) << std::endl;
std::cout << (b->remove(84)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->remove(353)) << std::endl;
std::cout << (e->insert(17)) << std::endl;
e->printPretty();
std::cout << (b->insert(484)) << std::endl;
*a=*e;
std::cout << (b->insert(457)) << std::endl;
std::cout << (b->insert(457)) << std::endl;
std::cout << (c->remove(243)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
*a=*b;
std::cout << (e->remove(105)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
*c=*e;
c->printPretty();
std::cout << (b->insert(484)) << std::endl;
std::cout << (e->insert(395)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (c->remove(17)) << std::endl;
c->printPretty();
std::cout << (d->insert(164)) << std::endl;
*c=*a;
std::cout << (a->insert(150)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
d->printPretty();
std::cout << (b->insert(484)) << std::endl;
std::cout << (d->insert(164)) << std::endl;
b->printPretty();
std::cout << (b->insert(262)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
std::cout << (c->remove(101)) << std::endl;
*d=*e;
*c=*c;
d->printPretty();
std::cout << (a->remove(452)) << std::endl;
std::cout << (e->insert(3)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (a->remove(24)) << std::endl;
std::cout << (d->remove(132)) << std::endl;
std::cout << (e->remove(3)) << std::endl;
d->printPretty();
std::cout << (d->insert(17)) << std::endl;
std::cout << (d->remove(395)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (e->remove(395)) << std::endl;
*d=*c;
std::cout << (a->remove(405)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
*a=*b;
std::cout << (b->remove(277)) << std::endl;
*c=*a;
std::cout << (d->insert(480)) << std::endl;
d->printPretty();
std::cout << (c->remove(484)) << std::endl;
*a=*b;
std::cout << (d->remove(480)) << std::endl;
std::cout << (c->insert(483)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
c->printPretty();
std::cout << (a->remove(483)) << std::endl;
std::cout << (a->remove(122)) << std::endl;
std::cout << (a->remove(72)) << std::endl;
std::cout << (d->remove(349)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
c->printPretty();
std::cout << (c->remove(284)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
std::cout << (b->insert(483)) << std::endl;
*c=*c;
d->printPretty();
e->printPretty();
std::cout << (a->remove(262)) << std::endl;
c->printPretty();
std::cout << (c->remove(168)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (c->insert(45)) << std::endl;
b->printPretty();
std::cout << (c->insert(102)) << std::endl;
a->printPretty();
std::cout << (b->insert(411)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
*d=*e;
std::cout << (a->remove(325)) << std::endl;
std::cout << (d->insert(17)) << std::endl;
d->printPretty();
std::cout << (b->remove(14)) << std::endl;
std::cout << (d->remove(17)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
std::cout << (a->insert(481)) << std::endl;
*d=*d;
std::cout << (c->insert(305)) << std::endl;
std::cout << (e->remove(70)) << std::endl;
*e=*e;
c->printPretty();
std::cout << (b->remove(378)) << std::endl;
*e=*e;
b->printPretty();
*c=*a;
std::cout << (c->insert(276)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (b->insert(39)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
std::cout << (c->remove(25)) << std::endl;
a->printPretty();
*d=*a;
std::cout << (d->remove(441)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
std::cout << (b->remove(484)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
*c=*b;
std::cout << (b->insert(411)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
*d=*d;
*c=*d;
std::cout << (e->remove(17)) << std::endl;
std::cout << (b->remove(39)) << std::endl;
*e=*a;
*d=*e;
std::cout << (e->insert(484)) << std::endl;
*e=*b;
a->printPretty();
std::cout << (b->insert(446)) << std::endl;
*e=*b;
std::cout << (b->insert(493)) << std::endl;
e->printPretty();
std::cout << (c->remove(134)) << std::endl;
c->printPretty();
std::cout << (e->remove(299)) << std::endl;
*c=*c;
std::cout << (c->remove(230)) << std::endl;
std::cout << (b->remove(172)) << std::endl;
std::cout << (a->remove(401)) << std::endl;
std::cout << (a->remove(484)) << std::endl;
std::cout << (a->remove(434)) << std::endl;
std::cout << (b->insert(493)) << std::endl;
std::cout << (b->remove(196)) << std::endl;
a->printPretty();
std::cout << (a->insert(184)) << std::endl;
std::cout << (c->remove(276)) << std::endl;
std::cout << (a->insert(276)) << std::endl;
*d=*c;
b->printPretty();
std::cout << (b->remove(243)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (b->insert(493)) << std::endl;
a->printPretty();
*b=*e;
d->printPretty();
std::cout << (d->remove(61)) << std::endl;
std::cout << (e->insert(483)) << std::endl;
*e=*a;
std::cout << (d->insert(481)) << std::endl;
*a=*e;
std::cout << (d->insert(47)) << std::endl;
b->printPretty();
e->printPretty();
std::cout << (b->remove(483)) << std::endl;
*d=*e;
std::cout << (d->insert(336)) << std::endl;
std::cout << (c->insert(424)) << std::endl;
c->printPretty();
std::cout << (a->remove(406)) << std::endl;
std::cout << (c->remove(183)) << std::endl;
c->printPretty();
*e=*c;
*d=*e;
a->printPretty();
a->printPretty();
std::cout << (b->remove(262)) << std::endl;
d->printPretty();
std::cout << (e->insert(427)) << std::endl;
std::cout << (e->insert(484)) << std::endl;
*d=*b;
std::cout << (d->remove(411)) << std::endl;
std::cout << (e->remove(156)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (d->remove(446)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
std::cout << (b->insert(446)) << std::endl;
std::cout << (b->remove(316)) << std::endl;
a->printPretty();
std::cout << (b->remove(88)) << std::endl;
std::cout << (e->remove(134)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (e->insert(276)) << std::endl;
std::cout << (b->remove(446)) << std::endl;
std::cout << (b->insert(411)) << std::endl;
std::cout << (b->remove(411)) << std::endl;
e->printPretty();
std::cout << (b->remove(295)) << std::endl;
c->printPretty();
std::cout << (d->remove(410)) << std::endl;
e->printPretty();
std::cout << (e->insert(276)) << std::endl;
std::cout << (e->remove(276)) << std::endl;
c->printPretty();
std::cout << (d->insert(245)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
c->printPretty();
std::cout << (a->remove(134)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
std::cout << (c->remove(248)) << std::endl;
std::cout << (b->insert(413)) << std::endl;
std::cout << (b->remove(224)) << std::endl;
std::cout << (c->remove(484)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (a->remove(276)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
d->printPretty();
std::cout << (e->remove(161)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
*e=*e;
std::cout << (a->insert(14)) << std::endl;
std::cout << (a->insert(339)) << std::endl;
std::cout << (d->insert(29)) << std::endl;
std::cout << (c->insert(439)) << std::endl;
std::cout << (e->insert(151)) << std::endl;
std::cout << (a->remove(481)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
d->printPretty();
std::cout << (b->insert(413)) << std::endl;
std::cout << (a->insert(171)) << std::endl;
std::cout << (a->insert(385)) << std::endl;
std::cout << (a->remove(170)) << std::endl;
std::cout << (a->insert(171)) << std::endl;
a->printPretty();
std::cout << (d->remove(29)) << std::endl;
e->printPretty();
std::cout << (c->remove(481)) << std::endl;
std::cout << (b->insert(137)) << std::endl;
a->printPretty();
std::cout << (e->remove(158)) << std::endl;
*b=*e;
std::cout << (d->insert(33)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
std::cout << (e->insert(186)) << std::endl;
*c=*a;
std::cout << (a->remove(343)) << std::endl;
*d=*c;
std::cout << (c->insert(370)) << std::endl;
std::cout << (a->remove(14)) << std::endl;
std::cout << (c->remove(101)) << std::endl;
*e=*c;
c->printPretty();
std::cout << (d->remove(314)) << std::endl;
std::cout << (b->remove(415)) << std::endl;
*e=*b;
std::cout << (a->remove(171)) << std::endl;
std::cout << (e->insert(259)) << std::endl;
a->printPretty();
std::cout << (c->remove(171)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
d->printPretty();
std::cout << (a->insert(184)) << std::endl;
std::cout << (c->remove(428)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
*b=*a;
b->printPretty();
std::cout << (b->insert(385)) << std::endl;
std::cout << (d->insert(236)) << std::endl;
std::cout << (e->insert(259)) << std::endl;
*b=*a;
*a=*a;
a->printPretty();
std::cout << (e->remove(259)) << std::endl;
*d=*d;
std::cout << (d->remove(358)) << std::endl;
std::cout << (d->remove(429)) << std::endl;
std::cout << (a->remove(280)) << std::endl;
c->printPretty();
std::cout << (b->insert(337)) << std::endl;
*c=*c;
std::cout << (d->insert(14)) << std::endl;
*d=*e;
std::cout << (b->insert(215)) << std::endl;
b->printPretty();
std::cout << (b->remove(150)) << std::endl;
std::cout << (a->insert(12)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (e->remove(378)) << std::endl;
std::cout << (a->insert(162)) << std::endl;
b->printPretty();
e->printPretty();
b->printPretty();
std::cout << (c->insert(65)) << std::endl;
std::cout << (c->remove(370)) << std::endl;
std::cout << (a->remove(12)) << std::endl;
std::cout << (d->insert(31)) << std::endl;
std::cout << (b->remove(215)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
std::cout << (e->remove(192)) << std::endl;
std::cout << (c->remove(385)) << std::endl;
d->printPretty();
std::cout << (d->insert(31)) << std::endl;
b->printPretty();
*d=*a;
a->printPretty();
std::cout << (e->remove(339)) << std::endl;
std::cout << (a->insert(237)) << std::endl;
std::cout << (a->remove(298)) << std::endl;
d->printPretty();
std::cout << (b->insert(449)) << std::endl;
d->printPretty();
std::cout << (e->remove(373)) << std::endl;
e->printPretty();
std::cout << (a->remove(395)) << std::endl;
*a=*e;
b->printPretty();
std::cout << (b->insert(449)) << std::endl;
std::cout << (e->remove(385)) << std::endl;
std::cout << (c->insert(65)) << std::endl;
std::cout << (b->insert(212)) << std::endl;
*b=*e;
std::cout << (b->remove(72)) << std::endl;
a->printPretty();
std::cout << (b->insert(468)) << std::endl;
e->printPretty();
std::cout << (e->remove(480)) << std::endl;
std::cout << (c->remove(54)) << std::endl;
std::cout << (c->remove(446)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->insert(12)) << std::endl;
std::cout << (c->remove(14)) << std::endl;
std::cout << (b->insert(243)) << std::endl;
*c=*a;
*d=*b;
std::cout << (d->remove(12)) << std::endl;
std::cout << (d->remove(52)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (a->remove(142)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
*e=*c;
std::cout << (b->insert(184)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
a->printPretty();
std::cout << (d->remove(468)) << std::endl;
a->printPretty();
std::cout << (e->remove(184)) << std::endl;
std::cout << (d->remove(325)) << std::endl;
a->printPretty();
std::cout << (c->insert(237)) << std::endl;
*e=*a;
std::cout << (b->insert(249)) << std::endl;
std::cout << (b->remove(121)) << std::endl;
std::cout << (d->remove(184)) << std::endl;
std::cout << (a->remove(158)) << std::endl;
std::cout << (e->remove(228)) << std::endl;
std::cout << (a->insert(184)) << std::endl;
std::cout << (e->insert(184)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (e->insert(187)) << std::endl;
std::cout << (e->remove(360)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
a->printPretty();
std::cout << (b->remove(243)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
*a=*b;
std::cout << (d->insert(243)) << std::endl;
e->printPretty();
std::cout << (c->insert(385)) << std::endl;
std::cout << (c->remove(115)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
std::cout << (e->remove(352)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
d->printPretty();
std::cout << (c->remove(237)) << std::endl;
std::cout << (e->insert(187)) << std::endl;
e->printPretty();
std::cout << (d->insert(44)) << std::endl;
a->printPretty();
std::cout << (a->remove(226)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
std::cout << (b->remove(468)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
std::cout << (c->remove(492)) << std::endl;
*c=*b;
c->printPretty();
std::cout << (e->insert(248)) << std::endl;
std::cout << (c->remove(336)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
*d=*d;
std::cout << (c->remove(184)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
std::cout << (a->remove(359)) << std::endl;
std::cout << (d->insert(44)) << std::endl;
std::cout << (c->insert(249)) << std::endl;
std::cout << (a->remove(159)) << std::endl;
std::cout << (c->insert(483)) << std::endl;
*c=*d;
e->printPretty();
b->printPretty();
std::cout << (e->insert(206)) << std::endl;
*c=*d;
std::cout << (d->insert(344)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (b->remove(24)) << std::endl;
std::cout << (d->insert(134)) << std::endl;
std::cout << (e->insert(385)) << std::endl;
b->printPretty();
std::cout << (e->remove(184)) << std::endl;
std::cout << (c->insert(456)) << std::endl;
e->printPretty();
std::cout << (a->insert(264)) << std::endl;
std::cout << (b->remove(179)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (d->insert(130)) << std::endl;
*c=*e;
*d=*b;
std::cout << (b->insert(258)) << std::endl;
std::cout << (a->insert(88)) << std::endl;
std::cout << (e->remove(206)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (b->insert(184)) << std::endl;
std::cout << (d->remove(410)) << std::endl;
*c=*d;
std::cout << (b->remove(18)) << std::endl;
*e=*b;
std::cout << (c->insert(455)) << std::endl;
std::cout << (b->remove(249)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
std::cout << (c->remove(1)) << std::endl;
std::cout << (e->remove(327)) << std::endl;
*e=*c;
std::cout << (d->remove(331)) << std::endl;
*d=*a;
std::cout << (d->insert(116)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (a->insert(88)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (d->insert(268)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
*b=*c;
std::cout << (e->insert(134)) << std::endl;
c->printPretty();
std::cout << (e->insert(184)) << std::endl;
std::cout << (d->insert(268)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
std::cout << (e->insert(481)) << std::endl;
std::cout << (c->remove(194)) << std::endl;
a->printPretty();
std::cout << (c->remove(402)) << std::endl;
std::cout << (b->insert(102)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (e->remove(438)) << std::endl;
std::cout << (d->insert(13)) << std::endl;
*c=*e;
std::cout << (c->remove(198)) << std::endl;
a->printPretty();
e->printPretty();
*a=*c;
b->printPretty();
std::cout << (a->remove(184)) << std::endl;
c->printPretty();
*d=*d;
std::cout << (d->remove(122)) << std::endl;
a->printPretty();
std::cout << (c->insert(184)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
std::cout << (b->remove(184)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
*a=*c;
std::cout << (a->remove(184)) << std::endl;
std::cout << (d->remove(268)) << std::endl;
std::cout << (c->remove(365)) << std::endl;
std::cout << (e->remove(481)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
*d=*a;
*c=*d;
*c=*e;
std::cout << (d->remove(481)) << std::endl;
a->printPretty();
std::cout << (a->remove(12)) << std::endl;
d->printPretty();
std::cout << (b->remove(102)) << std::endl;
std::cout << (c->insert(207)) << std::endl;
c->printPretty();
*b=*b;
std::cout << (e->remove(133)) << std::endl;
*e=*d;
*e=*d;
*c=*c;
std::cout << (e->insert(249)) << std::endl;
a->printPretty();
*b=*b;
*b=*c;
d->printPretty();
std::cout << (e->remove(455)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (c->remove(184)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
c->printPretty();
std::cout << (b->remove(184)) << std::endl;
std::cout << (a->remove(337)) << std::endl;
std::cout << (a->insert(161)) << std::endl;
std::cout << (a->remove(39)) << std::endl;
std::cout << (a->insert(456)) << std::endl;
std::cout << (e->insert(435)) << std::endl;
std::cout << (e->remove(12)) << std::endl;
std::cout << (d->remove(249)) << std::endl;
*d=*d;
std::cout << (d->insert(40)) << std::endl;
std::cout << (e->remove(249)) << std::endl;
b->printPretty();
std::cout << (b->insert(245)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (b->insert(84)) << std::endl;
c->printPretty();
std::cout << (e->insert(125)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (e->remove(441)) << std::endl;
std::cout << (b->insert(320)) << std::endl;
std::cout << (d->insert(455)) << std::endl;
d->printPretty();
*b=*b;
std::cout << (d->insert(455)) << std::endl;
a->printPretty();
std::cout << (c->remove(12)) << std::endl;
std::cout << (b->insert(136)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
*b=*d;
a->printPretty();
b->printPretty();
std::cout << (d->remove(438)) << std::endl;
std::cout << (d->insert(40)) << std::endl;
std::cout << (a->remove(249)) << std::endl;
std::cout << (d->remove(135)) << std::endl;
std::cout << (a->insert(192)) << std::endl;
*d=*c;
*d=*b;
a->printPretty();
b->printPretty();
std::cout << (c->insert(326)) << std::endl;
std::cout << (c->insert(374)) << std::endl;
std::cout << (c->remove(455)) << std::endl;
b->printPretty();
*c=*b;
std::cout << (a->insert(29)) << std::endl;
std::cout << (d->remove(126)) << std::endl;
std::cout << (c->remove(321)) << std::endl;
c->printPretty();
std::cout << (c->remove(389)) << std::endl;
std::cout << (b->remove(455)) << std::endl;
*e=*b;
return 0;
}
