#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
*a=*b;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
c->printPretty();
a->printPretty();
std::cout << (b->insert(193)) << std::endl;
*b=*b;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
d->printPretty();
std::cout << (d->remove(335)) << std::endl;
std::cout << (b->insert(193)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
*c=*b;
std::cout << (b->remove(193)) << std::endl;
std::cout << (a->insert(8)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
*a=*e;
std::cout << (a->insert(497)) << std::endl;
*a=*d;
std::cout << (c->insert(421)) << std::endl;
std::cout << (d->remove(92)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
*a=*e;
d->printPretty();
d->printPretty();
std::cout << (b->insert(248)) << std::endl;
std::cout << (e->insert(72)) << std::endl;
std::cout << (a->insert(496)) << std::endl;
std::cout << (b->remove(26)) << std::endl;
std::cout << (c->remove(394)) << std::endl;
e->printPretty();
std::cout << (e->remove(383)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
std::cout << (b->remove(248)) << std::endl;
std::cout << (b->remove(38)) << std::endl;
std::cout << (c->insert(395)) << std::endl;
std::cout << (d->remove(209)) << std::endl;
std::cout << (e->insert(420)) << std::endl;
*a=*d;
std::cout << (c->insert(31)) << std::endl;
std::cout << (e->insert(438)) << std::endl;
d->printPretty();
std::cout << (e->remove(52)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
b->printPretty();
*e=*b;
b->printPretty();
*d=*a;
b->printPretty();
std::cout << (c->remove(395)) << std::endl;
d->printPretty();
std::cout << (c->insert(31)) << std::endl;
std::cout << (a->remove(178)) << std::endl;
std::cout << (e->remove(55)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
e->printPretty();
std::cout << (e->remove(249)) << std::endl;
*e=*e;
*a=*d;
std::cout << (d->insert(471)) << std::endl;
*b=*a;
std::cout << (d->remove(356)) << std::endl;
d->printPretty();
a->printPretty();
e->printPretty();
e->printPretty();
a->printPretty();
std::cout << (e->remove(252)) << std::endl;
*b=*a;
a->printPretty();
c->printPretty();
*d=*e;
*e=*a;
d->printPretty();
std::cout << (d->remove(437)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->insert(499)) << std::endl;
std::cout << (e->remove(67)) << std::endl;
a->printPretty();
std::cout << (b->remove(186)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (a->insert(246)) << std::endl;
*c=*b;
std::cout << (e->remove(352)) << std::endl;
c->printPretty();
std::cout << (e->remove(474)) << std::endl;
b->printPretty();
*d=*b;
std::cout << (c->remove(198)) << std::endl;
std::cout << (d->remove(370)) << std::endl;
std::cout << (b->remove(475)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
*e=*c;
*e=*a;
std::cout << (a->remove(172)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (b->insert(371)) << std::endl;
d->printPretty();
std::cout << (a->remove(246)) << std::endl;
std::cout << (e->remove(246)) << std::endl;
b->printPretty();
*a=*a;
d->printPretty();
std::cout << (e->remove(51)) << std::endl;
*e=*d;
b->printPretty();
std::cout << (b->insert(57)) << std::endl;
std::cout << (e->insert(258)) << std::endl;
std::cout << (a->remove(313)) << std::endl;
std::cout << (b->insert(261)) << std::endl;
d->printPretty();
std::cout << (d->insert(434)) << std::endl;
*d=*c;
std::cout << (b->remove(371)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (c->remove(28)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (e->remove(347)) << std::endl;
*b=*c;
e->printPretty();
std::cout << (e->insert(20)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
std::cout << (e->remove(258)) << std::endl;
std::cout << (a->insert(410)) << std::endl;
std::cout << (e->insert(45)) << std::endl;
d->printPretty();
*d=*e;
a->printPretty();
e->printPretty();
c->printPretty();
std::cout << (d->remove(45)) << std::endl;
std::cout << (c->remove(34)) << std::endl;
*e=*b;
e->printPretty();
std::cout << (a->insert(8)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (b->remove(294)) << std::endl;
std::cout << (b->insert(428)) << std::endl;
*e=*c;
std::cout << (a->remove(115)) << std::endl;
std::cout << (b->remove(402)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (c->remove(331)) << std::endl;
a->printPretty();
std::cout << (d->insert(264)) << std::endl;
std::cout << (e->insert(47)) << std::endl;
*e=*e;
std::cout << (a->insert(425)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
std::cout << (b->insert(428)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
std::cout << (b->remove(428)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (a->remove(343)) << std::endl;
std::cout << (a->insert(305)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
std::cout << (d->remove(211)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
c->printPretty();
std::cout << (e->insert(47)) << std::endl;
std::cout << (b->remove(383)) << std::endl;
std::cout << (e->insert(218)) << std::endl;
std::cout << (c->insert(165)) << std::endl;
std::cout << (b->insert(75)) << std::endl;
*e=*a;
std::cout << (c->remove(383)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (a->insert(1)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (b->insert(75)) << std::endl;
a->printPretty();
std::cout << (e->insert(377)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (c->insert(242)) << std::endl;
std::cout << (b->remove(75)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (a->insert(300)) << std::endl;
*b=*e;
std::cout << (d->insert(384)) << std::endl;
c->printPretty();
*e=*e;
c->printPretty();
b->printPretty();
std::cout << (e->remove(214)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
std::cout << (e->remove(67)) << std::endl;
std::cout << (d->insert(433)) << std::endl;
std::cout << (a->insert(305)) << std::endl;
std::cout << (c->insert(180)) << std::endl;
e->printPretty();
*b=*e;
std::cout << (e->insert(48)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
d->printPretty();
std::cout << (c->insert(265)) << std::endl;
*c=*d;
*b=*a;
std::cout << (e->remove(476)) << std::endl;
std::cout << (e->insert(413)) << std::endl;
std::cout << (a->insert(258)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->remove(43)) << std::endl;
std::cout << (a->insert(425)) << std::endl;
std::cout << (a->remove(294)) << std::endl;
std::cout << (e->insert(229)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
std::cout << (e->remove(446)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
a->printPretty();
std::cout << (c->remove(52)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
std::cout << (c->remove(417)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
std::cout << (a->remove(410)) << std::endl;
*b=*a;
std::cout << (a->remove(258)) << std::endl;
std::cout << (a->remove(65)) << std::endl;
*d=*c;
std::cout << (c->insert(433)) << std::endl;
*a=*b;
std::cout << (a->remove(460)) << std::endl;
b->printPretty();
*a=*b;
d->printPretty();
a->printPretty();
a->printPretty();
*e=*a;
std::cout << (c->remove(433)) << std::endl;
std::cout << (b->insert(421)) << std::endl;
e->printPretty();
*b=*b;
std::cout << (c->insert(384)) << std::endl;
std::cout << (e->insert(447)) << std::endl;
std::cout << (e->insert(63)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
*c=*d;
std::cout << (b->insert(421)) << std::endl;
std::cout << (a->remove(447)) << std::endl;
std::cout << (a->insert(217)) << std::endl;
std::cout << (c->remove(433)) << std::endl;
std::cout << (e->remove(410)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (b->remove(378)) << std::endl;
std::cout << (b->insert(260)) << std::endl;
std::cout << (c->remove(384)) << std::endl;
std::cout << (e->remove(261)) << std::endl;
std::cout << (c->insert(20)) << std::endl;
std::cout << (d->remove(384)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (a->remove(366)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (e->remove(294)) << std::endl;
std::cout << (d->remove(425)) << std::endl;
*c=*b;
a->printPretty();
std::cout << (e->remove(468)) << std::endl;
d->printPretty();
std::cout << (b->insert(260)) << std::endl;
*b=*c;
b->printPretty();
std::cout << (e->remove(447)) << std::endl;
std::cout << (e->insert(425)) << std::endl;
b->printPretty();
std::cout << (d->insert(300)) << std::endl;
std::cout << (a->remove(258)) << std::endl;
b->printPretty();
std::cout << (e->remove(127)) << std::endl;
*b=*c;
*b=*d;
std::cout << (a->insert(8)) << std::endl;
std::cout << (d->remove(8)) << std::endl;
std::cout << (c->insert(421)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
std::cout << (d->insert(45)) << std::endl;
std::cout << (c->insert(447)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
a->printPretty();
std::cout << (b->insert(258)) << std::endl;
std::cout << (e->remove(214)) << std::endl;
std::cout << (b->remove(480)) << std::endl;
a->printPretty();
a->printPretty();
*e=*a;
std::cout << (d->remove(5)) << std::endl;
e->printPretty();
std::cout << (d->remove(260)) << std::endl;
std::cout << (d->insert(447)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
d->printPretty();
std::cout << (b->remove(72)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
std::cout << (a->remove(305)) << std::endl;
std::cout << (a->insert(224)) << std::endl;
std::cout << (c->insert(425)) << std::endl;
std::cout << (c->remove(391)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
*a=*b;
std::cout << (b->remove(214)) << std::endl;
*b=*b;
std::cout << (d->remove(17)) << std::endl;
d->printPretty();
std::cout << (a->insert(10)) << std::endl;
std::cout << (a->remove(10)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
std::cout << (e->remove(8)) << std::endl;
*a=*b;
*a=*e;
std::cout << (b->insert(447)) << std::endl;
std::cout << (b->remove(447)) << std::endl;
b->printPretty();
std::cout << (c->insert(470)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
std::cout << (e->remove(305)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
*d=*e;
a->printPretty();
c->printPretty();
std::cout << (a->remove(217)) << std::endl;
std::cout << (e->insert(295)) << std::endl;
std::cout << (b->insert(300)) << std::endl;
a->printPretty();
std::cout << (d->insert(130)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
std::cout << (c->insert(194)) << std::endl;
e->printPretty();
std::cout << (c->remove(193)) << std::endl;
std::cout << (b->remove(260)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (d->insert(58)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (d->remove(300)) << std::endl;
*e=*b;
*a=*a;
std::cout << (c->insert(425)) << std::endl;
*a=*a;
*c=*b;
std::cout << (c->remove(330)) << std::endl;
std::cout << (d->insert(58)) << std::endl;
std::cout << (d->insert(425)) << std::endl;
std::cout << (b->remove(177)) << std::endl;
std::cout << (c->remove(300)) << std::endl;
std::cout << (c->remove(177)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
std::cout << (a->insert(42)) << std::endl;
std::cout << (e->insert(177)) << std::endl;
std::cout << (c->insert(8)) << std::endl;
std::cout << (b->remove(300)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
std::cout << (b->remove(8)) << std::endl;
std::cout << (c->remove(258)) << std::endl;
*c=*e;
*e=*d;
std::cout << (d->insert(329)) << std::endl;
std::cout << (b->insert(258)) << std::endl;
std::cout << (d->insert(391)) << std::endl;
std::cout << (a->insert(29)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
std::cout << (d->remove(305)) << std::endl;
b->printPretty();
std::cout << (d->remove(64)) << std::endl;
std::cout << (b->remove(421)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
std::cout << (d->remove(457)) << std::endl;
std::cout << (b->insert(205)) << std::endl;
*d=*d;
std::cout << (c->remove(266)) << std::endl;
std::cout << (e->remove(45)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (a->remove(29)) << std::endl;
std::cout << (e->remove(425)) << std::endl;
b->printPretty();
std::cout << (b->remove(258)) << std::endl;
d->printPretty();
std::cout << (e->insert(58)) << std::endl;
*c=*a;
std::cout << (b->insert(482)) << std::endl;
std::cout << (e->remove(58)) << std::endl;
c->printPretty();
std::cout << (a->insert(499)) << std::endl;
d->printPretty();
std::cout << (a->remove(305)) << std::endl;
std::cout << (d->remove(158)) << std::endl;
std::cout << (a->remove(234)) << std::endl;
e->printPretty();
std::cout << (b->insert(482)) << std::endl;
std::cout << (a->insert(373)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
std::cout << (e->insert(94)) << std::endl;
b->printPretty();
std::cout << (c->remove(302)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
std::cout << (d->remove(391)) << std::endl;
*a=*b;
std::cout << (c->remove(425)) << std::endl;
std::cout << (c->remove(204)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (b->remove(305)) << std::endl;
std::cout << (e->insert(92)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
d->printPretty();
std::cout << (a->remove(300)) << std::endl;
std::cout << (c->insert(300)) << std::endl;
e->printPretty();
d->printPretty();
*e=*a;
std::cout << (d->remove(329)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
std::cout << (b->remove(205)) << std::endl;
std::cout << (a->remove(305)) << std::endl;
std::cout << (e->insert(120)) << std::endl;
std::cout << (e->insert(100)) << std::endl;
std::cout << (b->remove(482)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
std::cout << (d->insert(234)) << std::endl;
std::cout << (c->remove(224)) << std::endl;
std::cout << (a->remove(383)) << std::endl;
*e=*e;
std::cout << (d->remove(58)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
c->printPretty();
std::cout << (d->remove(425)) << std::endl;
d->printPretty();
std::cout << (d->insert(291)) << std::endl;
*e=*b;
std::cout << (a->insert(277)) << std::endl;
*b=*e;
std::cout << (e->insert(106)) << std::endl;
std::cout << (e->remove(418)) << std::endl;
std::cout << (b->insert(150)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->insert(427)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
e->printPretty();
*c=*d;
c->printPretty();
std::cout << (a->insert(411)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
std::cout << (b->insert(427)) << std::endl;
*a=*e;
a->printPretty();
std::cout << (d->remove(234)) << std::endl;
std::cout << (b->insert(403)) << std::endl;
std::cout << (a->insert(283)) << std::endl;
b->printPretty();
std::cout << (e->remove(151)) << std::endl;
std::cout << (a->remove(44)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
std::cout << (b->remove(254)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (a->remove(148)) << std::endl;
d->printPretty();
std::cout << (d->remove(436)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
*d=*d;
std::cout << (b->insert(148)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
std::cout << (d->remove(148)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
std::cout << (c->insert(156)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (c->insert(234)) << std::endl;
std::cout << (c->insert(15)) << std::endl;
std::cout << (e->insert(106)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
std::cout << (b->insert(418)) << std::endl;
*c=*d;
std::cout << (d->remove(283)) << std::endl;
std::cout << (e->insert(148)) << std::endl;
*a=*c;
d->printPretty();
std::cout << (b->insert(418)) << std::endl;
a->printPretty();
std::cout << (b->insert(8)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
a->printPretty();
a->printPretty();
a->printPretty();
std::cout << (d->insert(106)) << std::endl;
std::cout << (a->remove(283)) << std::endl;
*c=*c;
e->printPretty();
e->printPretty();
std::cout << (c->remove(354)) << std::endl;
*a=*e;
std::cout << (e->remove(106)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
a->printPretty();
std::cout << (c->remove(106)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
b->printPretty();
std::cout << (b->remove(30)) << std::endl;
*e=*a;
std::cout << (a->insert(449)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
*b=*d;
std::cout << (e->remove(430)) << std::endl;
b->printPretty();
std::cout << (e->remove(106)) << std::endl;
e->printPretty();
std::cout << (d->insert(106)) << std::endl;
d->printPretty();
*b=*e;
c->printPretty();
b->printPretty();
std::cout << (a->remove(449)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
a->printPretty();
std::cout << (c->remove(85)) << std::endl;
std::cout << (c->insert(283)) << std::endl;
std::cout << (d->insert(106)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
std::cout << (b->insert(148)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
*c=*c;
std::cout << (b->remove(148)) << std::endl;
d->printPretty();
std::cout << (c->remove(462)) << std::endl;
*e=*b;
std::cout << (d->insert(101)) << std::endl;
*c=*b;
std::cout << (d->insert(378)) << std::endl;
b->printPretty();
*a=*b;
e->printPretty();
std::cout << (c->insert(1)) << std::endl;
std::cout << (b->remove(465)) << std::endl;
std::cout << (a->insert(423)) << std::endl;
std::cout << (a->insert(149)) << std::endl;
std::cout << (c->insert(446)) << std::endl;
std::cout << (b->insert(95)) << std::endl;
std::cout << (d->remove(20)) << std::endl;
*d=*c;
a->printPretty();
std::cout << (d->remove(63)) << std::endl;
*d=*b;
std::cout << (a->insert(149)) << std::endl;
std::cout << (a->insert(286)) << std::endl;
c->printPretty();
std::cout << (b->remove(95)) << std::endl;
std::cout << (a->remove(394)) << std::endl;
std::cout << (d->remove(303)) << std::endl;
*c=*c;
std::cout << (a->remove(29)) << std::endl;
std::cout << (c->remove(323)) << std::endl;
*c=*e;
std::cout << (e->remove(19)) << std::endl;
*b=*b;
std::cout << (d->insert(95)) << std::endl;
std::cout << (e->insert(134)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->insert(452)) << std::endl;
*b=*e;
std::cout << (e->remove(134)) << std::endl;
a->printPretty();
std::cout << (e->remove(405)) << std::endl;
*e=*e;
std::cout << (c->insert(452)) << std::endl;
c->printPretty();
std::cout << (b->insert(134)) << std::endl;
std::cout << (a->remove(423)) << std::endl;
std::cout << (e->insert(136)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
std::cout << (b->insert(337)) << std::endl;
c->printPretty();
std::cout << (e->remove(450)) << std::endl;
std::cout << (c->insert(452)) << std::endl;
e->printPretty();
*c=*a;
*a=*a;
*c=*b;
*e=*b;
std::cout << (e->insert(337)) << std::endl;
std::cout << (c->insert(337)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
std::cout << (a->remove(149)) << std::endl;
std::cout << (c->remove(337)) << std::endl;
b->printPretty();
std::cout << (a->insert(286)) << std::endl;
*b=*a;
std::cout << (c->remove(71)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
std::cout << (b->remove(265)) << std::endl;
b->printPretty();
std::cout << (c->remove(349)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (d->insert(188)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
e->printPretty();
*e=*c;
std::cout << (d->remove(106)) << std::endl;
d->printPretty();
std::cout << (a->insert(154)) << std::endl;
a->printPretty();
std::cout << (d->remove(188)) << std::endl;
std::cout << (a->insert(393)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
std::cout << (b->insert(410)) << std::endl;
*b=*c;
std::cout << (d->remove(270)) << std::endl;
*c=*d;
std::cout << (a->insert(308)) << std::endl;
d->printPretty();
std::cout << (d->insert(339)) << std::endl;
std::cout << (b->remove(218)) << std::endl;
std::cout << (d->remove(76)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
std::cout << (e->insert(237)) << std::endl;
std::cout << (a->remove(458)) << std::endl;
*c=*d;
std::cout << (d->remove(339)) << std::endl;
d->printPretty();
*e=*d;
std::cout << (d->remove(95)) << std::endl;
std::cout << (b->remove(28)) << std::endl;
std::cout << (e->remove(95)) << std::endl;
*a=*c;
std::cout << (a->remove(95)) << std::endl;
std::cout << (c->remove(95)) << std::endl;
a->printPretty();
std::cout << (e->insert(286)) << std::endl;
std::cout << (d->remove(48)) << std::endl;
*c=*c;
*b=*b;
std::cout << (c->remove(286)) << std::endl;
std::cout << (e->remove(335)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
a->printPretty();
std::cout << (a->insert(339)) << std::endl;
std::cout << (c->remove(382)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (c->insert(339)) << std::endl;
std::cout << (d->remove(472)) << std::endl;
std::cout << (e->remove(286)) << std::endl;
std::cout << (c->remove(339)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
*a=*c;
std::cout << (b->insert(362)) << std::endl;
*b=*e;
std::cout << (c->insert(438)) << std::endl;
b->printPretty();
*e=*c;
d->printPretty();
*a=*b;
std::cout << (b->remove(29)) << std::endl;
*b=*a;
std::cout << (b->insert(112)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (c->remove(472)) << std::endl;
std::cout << (e->insert(438)) << std::endl;
d->printPretty();
a->printPretty();
a->printPretty();
b->printPretty();
std::cout << (b->insert(68)) << std::endl;
std::cout << (e->remove(226)) << std::endl;
std::cout << (e->remove(2)) << std::endl;
e->printPretty();
std::cout << (e->insert(198)) << std::endl;
std::cout << (b->insert(248)) << std::endl;
std::cout << (d->insert(40)) << std::endl;
return 0;
}
