#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
a->printPretty();
std::cout << (b->remove(358)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*b=*a;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->remove(443)) << std::endl;
std::cout << (a->remove(177)) << std::endl;
std::cout << (a->insert(316)) << std::endl;
*a=*b;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
b->printPretty();
d->printPretty();
std::cout << (b->remove(205)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
std::cout << (d->insert(160)) << std::endl;
std::cout << (a->insert(197)) << std::endl;
std::cout << (c->insert(464)) << std::endl;
a->printPretty();
std::cout << (d->insert(160)) << std::endl;
*e=*e;
std::cout << (a->remove(197)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
std::cout << (d->remove(160)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
a->printPretty();
*d=*c;
std::cout << (b->insert(433)) << std::endl;
*a=*b;
std::cout << (b->remove(433)) << std::endl;
std::cout << (c->remove(464)) << std::endl;
e->printPretty();
std::cout << (b->insert(222)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
b->printPretty();
std::cout << (d->insert(338)) << std::endl;
e->printPretty();
std::cout << (c->remove(346)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (a->insert(433)) << std::endl;
*a=*a;
d->printPretty();
*b=*e;
std::cout << (b->remove(302)) << std::endl;
std::cout << (b->insert(178)) << std::endl;
std::cout << (d->remove(464)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (a->remove(433)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (a->remove(36)) << std::endl;
*a=*b;
std::cout << (d->remove(338)) << std::endl;
std::cout << (a->remove(305)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
*a=*c;
std::cout << (b->remove(178)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
c->printPretty();
std::cout << (a->remove(330)) << std::endl;
d->printPretty();
*d=*d;
std::cout << (d->insert(496)) << std::endl;
std::cout << (c->insert(330)) << std::endl;
std::cout << (c->remove(330)) << std::endl;
d->printPretty();
d->printPretty();
*c=*e;
b->printPretty();
std::cout << (a->insert(89)) << std::endl;
std::cout << (e->remove(476)) << std::endl;
std::cout << (c->insert(399)) << std::endl;
e->printPretty();
std::cout << (a->insert(202)) << std::endl;
a->printPretty();
std::cout << (b->insert(270)) << std::endl;
e->printPretty();
std::cout << (d->insert(496)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
std::cout << (b->remove(48)) << std::endl;
std::cout << (a->insert(125)) << std::endl;
*b=*c;
std::cout << (b->remove(399)) << std::endl;
*d=*d;
std::cout << (d->remove(120)) << std::endl;
c->printPretty();
std::cout << (c->remove(399)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
std::cout << (a->insert(474)) << std::endl;
*b=*b;
a->printPretty();
c->printPretty();
d->printPretty();
a->printPretty();
*a=*d;
std::cout << (d->remove(496)) << std::endl;
d->printPretty();
std::cout << (a->insert(433)) << std::endl;
*c=*a;
*a=*e;
e->printPretty();
std::cout << (c->remove(496)) << std::endl;
*e=*b;
*e=*d;
std::cout << (d->remove(11)) << std::endl;
*c=*b;
a->printPretty();
a->printPretty();
e->printPretty();
std::cout << (c->insert(357)) << std::endl;
e->printPretty();
*e=*a;
std::cout << (e->remove(140)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->insert(358)) << std::endl;
std::cout << (b->remove(1)) << std::endl;
std::cout << (a->remove(192)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (a->remove(358)) << std::endl;
std::cout << (e->remove(162)) << std::endl;
std::cout << (d->remove(261)) << std::endl;
std::cout << (b->remove(55)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(496)) << std::endl;
c->printPretty();
std::cout << (c->insert(458)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (d->remove(486)) << std::endl;
*a=*d;
e->printPretty();
std::cout << (e->remove(139)) << std::endl;
*b=*b;
b->printPretty();
std::cout << (a->insert(107)) << std::endl;
std::cout << (a->remove(107)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (e->insert(144)) << std::endl;
std::cout << (c->remove(107)) << std::endl;
e->printPretty();
std::cout << (e->remove(144)) << std::endl;
*a=*d;
std::cout << (a->insert(4)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (a->insert(4)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
std::cout << (b->insert(12)) << std::endl;
b->printPretty();
e->printPretty();
d->printPretty();
std::cout << (e->remove(401)) << std::endl;
std::cout << (e->insert(34)) << std::endl;
std::cout << (b->insert(206)) << std::endl;
*d=*a;
std::cout << (b->remove(206)) << std::endl;
std::cout << (c->remove(458)) << std::endl;
std::cout << (e->insert(383)) << std::endl;
*d=*c;
std::cout << (d->insert(93)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->remove(4)) << std::endl;
a->printPretty();
std::cout << (a->insert(416)) << std::endl;
std::cout << (d->remove(487)) << std::endl;
std::cout << (b->insert(114)) << std::endl;
std::cout << (a->insert(416)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
std::cout << (d->remove(357)) << std::endl;
std::cout << (c->remove(326)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (c->remove(487)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->remove(168)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->insert(14)) << std::endl;
std::cout << (b->insert(3)) << std::endl;
*b=*c;
std::cout << (e->insert(14)) << std::endl;
std::cout << (a->remove(416)) << std::endl;
std::cout << (c->remove(214)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (c->insert(376)) << std::endl;
b->printPretty();
std::cout << (c->insert(310)) << std::endl;
*c=*c;
std::cout << (e->insert(51)) << std::endl;
*a=*d;
std::cout << (d->remove(351)) << std::endl;
std::cout << (a->remove(12)) << std::endl;
*e=*e;
std::cout << (e->insert(168)) << std::endl;
d->printPretty();
*c=*d;
d->printPretty();
std::cout << (c->remove(252)) << std::endl;
std::cout << (e->insert(93)) << std::endl;
*e=*a;
std::cout << (d->insert(24)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (d->remove(172)) << std::endl;
std::cout << (c->insert(466)) << std::endl;
std::cout << (c->insert(466)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
*a=*c;
std::cout << (b->remove(51)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
std::cout << (b->insert(415)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
*b=*d;
a->printPretty();
*b=*b;
std::cout << (d->remove(24)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
*e=*e;
*e=*c;
std::cout << (b->insert(444)) << std::endl;
std::cout << (c->remove(313)) << std::endl;
std::cout << (e->insert(355)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
b->printPretty();
std::cout << (c->insert(315)) << std::endl;
*d=*e;
*e=*c;
std::cout << (b->insert(158)) << std::endl;
std::cout << (c->remove(315)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
b->printPretty();
std::cout << (b->insert(131)) << std::endl;
std::cout << (a->remove(8)) << std::endl;
*c=*d;
std::cout << (b->remove(158)) << std::endl;
std::cout << (b->remove(59)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (c->remove(355)) << std::endl;
std::cout << (d->remove(355)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
*e=*e;
d->printPretty();
e->printPretty();
*a=*c;
std::cout << (a->remove(444)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (b->remove(24)) << std::endl;
std::cout << (a->remove(466)) << std::endl;
std::cout << (e->insert(33)) << std::endl;
b->printPretty();
std::cout << (c->remove(283)) << std::endl;
d->printPretty();
std::cout << (b->remove(234)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
std::cout << (c->insert(31)) << std::endl;
std::cout << (b->insert(55)) << std::endl;
*a=*a;
*a=*b;
std::cout << (c->remove(34)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
b->printPretty();
*b=*e;
d->printPretty();
c->printPretty();
a->printPretty();
e->printPretty();
c->printPretty();
e->printPretty();
std::cout << (a->insert(131)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
d->printPretty();
std::cout << (e->insert(158)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (b->insert(466)) << std::endl;
std::cout << (b->insert(444)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
b->printPretty();
*c=*d;
std::cout << (e->remove(33)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(66)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
*e=*c;
std::cout << (d->remove(384)) << std::endl;
std::cout << (a->insert(55)) << std::endl;
std::cout << (e->insert(466)) << std::endl;
std::cout << (e->remove(93)) << std::endl;
d->printPretty();
std::cout << (c->remove(195)) << std::endl;
b->printPretty();
std::cout << (e->insert(444)) << std::endl;
std::cout << (b->remove(379)) << std::endl;
std::cout << (b->insert(466)) << std::endl;
std::cout << (c->insert(430)) << std::endl;
std::cout << (c->insert(151)) << std::endl;
*d=*e;
*d=*c;
std::cout << (b->insert(304)) << std::endl;
std::cout << (b->remove(434)) << std::endl;
std::cout << (a->insert(55)) << std::endl;
*a=*d;
std::cout << (e->remove(444)) << std::endl;
std::cout << (d->insert(444)) << std::endl;
std::cout << (b->remove(466)) << std::endl;
*a=*a;
std::cout << (a->insert(151)) << std::endl;
std::cout << (c->remove(496)) << std::endl;
std::cout << (a->remove(466)) << std::endl;
std::cout << (d->insert(324)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
std::cout << (b->insert(158)) << std::endl;
std::cout << (a->remove(444)) << std::endl;
*c=*a;
std::cout << (d->remove(158)) << std::endl;
*e=*a;
c->printPretty();
std::cout << (a->remove(151)) << std::endl;
std::cout << (e->remove(151)) << std::endl;
std::cout << (c->remove(93)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
e->printPretty();
std::cout << (c->remove(151)) << std::endl;
std::cout << (c->insert(158)) << std::endl;
std::cout << (b->remove(33)) << std::endl;
d->printPretty();
*d=*e;
e->printPretty();
std::cout << (e->remove(128)) << std::endl;
std::cout << (a->insert(430)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (e->remove(325)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
e->printPretty();
std::cout << (c->insert(430)) << std::endl;
std::cout << (b->insert(499)) << std::endl;
*c=*a;
std::cout << (b->insert(234)) << std::endl;
a->printPretty();
std::cout << (e->remove(281)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
std::cout << (e->insert(400)) << std::endl;
std::cout << (d->insert(125)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
*d=*a;
std::cout << (c->insert(17)) << std::endl;
d->printPretty();
std::cout << (b->insert(234)) << std::endl;
c->printPretty();
std::cout << (b->insert(234)) << std::endl;
*e=*c;
std::cout << (a->remove(482)) << std::endl;
std::cout << (a->insert(147)) << std::endl;
std::cout << (d->insert(4)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
std::cout << (d->remove(4)) << std::endl;
std::cout << (b->remove(304)) << std::endl;
std::cout << (d->insert(158)) << std::endl;
std::cout << (d->insert(430)) << std::endl;
std::cout << (d->remove(490)) << std::endl;
std::cout << (a->insert(189)) << std::endl;
std::cout << (c->insert(93)) << std::endl;
std::cout << (b->remove(444)) << std::endl;
a->printPretty();
std::cout << (a->insert(140)) << std::endl;
std::cout << (d->remove(430)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (e->remove(17)) << std::endl;
b->printPretty();
*a=*b;
std::cout << (e->insert(411)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (a->insert(234)) << std::endl;
c->printPretty();
std::cout << (d->remove(158)) << std::endl;
std::cout << (c->insert(318)) << std::endl;
std::cout << (b->remove(315)) << std::endl;
e->printPretty();
std::cout << (c->insert(226)) << std::endl;
*b=*a;
std::cout << (e->insert(411)) << std::endl;
b->printPretty();
std::cout << (a->remove(34)) << std::endl;
*e=*b;
*e=*e;
std::cout << (a->insert(192)) << std::endl;
std::cout << (a->insert(462)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (b->insert(78)) << std::endl;
std::cout << (e->remove(309)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
d->printPretty();
*e=*b;
*e=*a;
std::cout << (a->insert(158)) << std::endl;
std::cout << (d->remove(91)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
*e=*d;
e->printPretty();
std::cout << (a->remove(234)) << std::endl;
*b=*e;
*d=*d;
std::cout << (c->remove(318)) << std::endl;
c->printPretty();
std::cout << (e->remove(418)) << std::endl;
*d=*d;
*c=*c;
std::cout << (e->remove(369)) << std::endl;
*a=*d;
std::cout << (b->insert(371)) << std::endl;
std::cout << (b->remove(433)) << std::endl;
std::cout << (b->insert(371)) << std::endl;
std::cout << (b->insert(371)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
*d=*b;
std::cout << (e->insert(380)) << std::endl;
e->printPretty();
std::cout << (e->remove(219)) << std::endl;
d->printPretty();
std::cout << (b->insert(56)) << std::endl;
*c=*d;
*e=*b;
*d=*d;
std::cout << (e->remove(333)) << std::endl;
*a=*c;
std::cout << (d->remove(371)) << std::endl;
d->printPretty();
std::cout << (e->remove(313)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (b->remove(360)) << std::endl;
e->printPretty();
std::cout << (e->remove(43)) << std::endl;
c->printPretty();
std::cout << (a->insert(293)) << std::endl;
std::cout << (b->remove(250)) << std::endl;
std::cout << (b->insert(371)) << std::endl;
std::cout << (a->remove(50)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (a->remove(161)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
std::cout << (e->insert(371)) << std::endl;
*b=*d;
std::cout << (c->remove(371)) << std::endl;
c->printPretty();
e->printPretty();
*e=*e;
std::cout << (b->remove(467)) << std::endl;
std::cout << (d->remove(198)) << std::endl;
std::cout << (c->remove(317)) << std::endl;
std::cout << (e->insert(199)) << std::endl;
std::cout << (a->remove(371)) << std::endl;
std::cout << (e->remove(199)) << std::endl;
std::cout << (a->remove(448)) << std::endl;
std::cout << (a->remove(293)) << std::endl;
b->printPretty();
std::cout << (c->remove(423)) << std::endl;
c->printPretty();
std::cout << (b->insert(497)) << std::endl;
*d=*c;
std::cout << (d->insert(37)) << std::endl;
std::cout << (b->remove(497)) << std::endl;
*b=*a;
d->printPretty();
*e=*b;
a->printPretty();
c->printPretty();
std::cout << (a->remove(40)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (d->insert(251)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
a->printPretty();
*e=*b;
*d=*a;
*c=*b;
std::cout << (b->remove(23)) << std::endl;
*d=*d;
std::cout << (b->insert(316)) << std::endl;
*c=*d;
std::cout << (d->remove(36)) << std::endl;
e->printPretty();
*e=*d;
std::cout << (b->insert(316)) << std::endl;
d->printPretty();
std::cout << (d->remove(349)) << std::endl;
*b=*e;
std::cout << (b->remove(9)) << std::endl;
std::cout << (b->insert(49)) << std::endl;
*c=*c;
d->printPretty();
b->printPretty();
std::cout << (d->insert(36)) << std::endl;
std::cout << (b->insert(49)) << std::endl;
*b=*a;
std::cout << (d->remove(251)) << std::endl;
*d=*c;
std::cout << (e->insert(9)) << std::endl;
std::cout << (c->insert(485)) << std::endl;
d->printPretty();
*a=*d;
std::cout << (a->remove(294)) << std::endl;
d->printPretty();
std::cout << (b->insert(439)) << std::endl;
std::cout << (e->insert(9)) << std::endl;
std::cout << (b->remove(182)) << std::endl;
*d=*b;
b->printPretty();
b->printPretty();
*b=*a;
std::cout << (b->insert(223)) << std::endl;
std::cout << (c->insert(485)) << std::endl;
*a=*a;
std::cout << (b->remove(223)) << std::endl;
std::cout << (e->insert(9)) << std::endl;
b->printPretty();
std::cout << (d->remove(125)) << std::endl;
std::cout << (c->remove(274)) << std::endl;
std::cout << (d->insert(439)) << std::endl;
std::cout << (b->insert(345)) << std::endl;
*e=*e;
std::cout << (b->remove(294)) << std::endl;
b->printPretty();
*c=*a;
std::cout << (e->remove(422)) << std::endl;
*d=*c;
std::cout << (b->insert(93)) << std::endl;
c->printPretty();
std::cout << (e->insert(247)) << std::endl;
d->printPretty();
a->printPretty();
*e=*c;
std::cout << (b->remove(93)) << std::endl;
std::cout << (d->insert(372)) << std::endl;
*c=*d;
*b=*b;
std::cout << (d->remove(372)) << std::endl;
*a=*d;
std::cout << (b->remove(140)) << std::endl;
std::cout << (b->insert(345)) << std::endl;
std::cout << (b->remove(345)) << std::endl;
*a=*e;
b->printPretty();
d->printPretty();
std::cout << (c->remove(115)) << std::endl;
*d=*e;
std::cout << (b->remove(211)) << std::endl;
c->printPretty();
*e=*b;
*b=*b;
std::cout << (c->remove(55)) << std::endl;
e->printPretty();
std::cout << (d->remove(444)) << std::endl;
std::cout << (b->remove(54)) << std::endl;
std::cout << (d->insert(298)) << std::endl;
std::cout << (d->insert(298)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (c->remove(466)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
a->printPretty();
*a=*c;
b->printPretty();
std::cout << (d->remove(7)) << std::endl;
std::cout << (d->insert(451)) << std::endl;
std::cout << (d->insert(409)) << std::endl;
e->printPretty();
std::cout << (d->remove(298)) << std::endl;
std::cout << (b->remove(135)) << std::endl;
e->printPretty();
std::cout << (c->remove(463)) << std::endl;
std::cout << (c->remove(372)) << std::endl;
std::cout << (d->insert(451)) << std::endl;
*c=*b;
std::cout << (d->remove(451)) << std::endl;
std::cout << (a->insert(372)) << std::endl;
b->printPretty();
std::cout << (a->remove(372)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
std::cout << (a->remove(194)) << std::endl;
*d=*b;
std::cout << (c->remove(166)) << std::endl;
e->printPretty();
std::cout << (d->remove(403)) << std::endl;
std::cout << (d->remove(113)) << std::endl;
std::cout << (d->insert(203)) << std::endl;
std::cout << (d->remove(86)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
std::cout << (e->insert(155)) << std::endl;
std::cout << (d->remove(304)) << std::endl;
e->printPretty();
c->printPretty();
c->printPretty();
*a=*d;
std::cout << (d->remove(203)) << std::endl;
a->printPretty();
std::cout << (e->insert(155)) << std::endl;
std::cout << (a->insert(164)) << std::endl;
*e=*b;
b->printPretty();
c->printPretty();
*c=*c;
c->printPretty();
*c=*e;
std::cout << (e->remove(168)) << std::endl;
*b=*d;
*d=*c;
std::cout << (a->remove(203)) << std::endl;
*a=*c;
std::cout << (d->remove(235)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (d->remove(128)) << std::endl;
std::cout << (b->insert(369)) << std::endl;
std::cout << (b->remove(213)) << std::endl;
std::cout << (d->remove(252)) << std::endl;
*d=*c;
d->printPretty();
*d=*b;
*e=*b;
std::cout << (b->insert(369)) << std::endl;
std::cout << (e->remove(369)) << std::endl;
*d=*d;
c->printPretty();
std::cout << (e->remove(228)) << std::endl;
std::cout << (d->remove(416)) << std::endl;
*a=*a;
std::cout << (c->remove(394)) << std::endl;
*c=*d;
std::cout << (c->insert(437)) << std::endl;
std::cout << (d->insert(28)) << std::endl;
*a=*a;
std::cout << (c->insert(437)) << std::endl;
std::cout << (b->insert(87)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (c->insert(346)) << std::endl;
std::cout << (d->insert(133)) << std::endl;
c->printPretty();
std::cout << (c->insert(176)) << std::endl;
std::cout << (d->insert(369)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (e->insert(209)) << std::endl;
return 0;
}
