#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->insert(207)) << std::endl;
std::cout << (a->remove(229)) << std::endl;
std::cout << (a->remove(175)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
*a=*b;
a->printPretty();
std::cout << (b->remove(160)) << std::endl;
std::cout << (c->remove(303)) << std::endl;
std::cout << (c->remove(235)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*a);
std::cout << (c->insert(481)) << std::endl;
*d=*b;
std::cout << (c->insert(200)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (d->remove(248)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*a);
std::cout << (d->remove(126)) << std::endl;
*b=*a;
*d=*a;
std::cout << (e->insert(241)) << std::endl;
*e=*b;
a->printPretty();
*d=*a;
std::cout << (a->remove(107)) << std::endl;
std::cout << (e->remove(405)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
std::cout << (c->remove(481)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
std::cout << (d->insert(15)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
std::cout << (c->insert(200)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
*a=*e;
std::cout << (d->remove(15)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (b->insert(172)) << std::endl;
std::cout << (c->remove(356)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (a->insert(241)) << std::endl;
*d=*a;
std::cout << (c->insert(221)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
*e=*d;
std::cout << (c->insert(221)) << std::endl;
e->printPretty();
std::cout << (c->insert(353)) << std::endl;
a->printPretty();
std::cout << (d->insert(241)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
a->printPretty();
std::cout << (b->remove(241)) << std::endl;
std::cout << (c->remove(492)) << std::endl;
*a=*b;
*e=*b;
std::cout << (d->remove(120)) << std::endl;
a->printPretty();
std::cout << (c->insert(470)) << std::endl;
std::cout << (e->remove(400)) << std::endl;
*a=*c;
std::cout << (a->remove(353)) << std::endl;
*b=*d;
std::cout << (d->remove(283)) << std::endl;
std::cout << (b->remove(235)) << std::endl;
a->printPretty();
std::cout << (a->remove(107)) << std::endl;
a->printPretty();
std::cout << (e->insert(172)) << std::endl;
b->printPretty();
std::cout << (d->remove(172)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (d->remove(241)) << std::endl;
*d=*c;
std::cout << (e->insert(385)) << std::endl;
*d=*d;
std::cout << (b->insert(372)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
*d=*d;
std::cout << (d->remove(426)) << std::endl;
std::cout << (c->insert(444)) << std::endl;
std::cout << (c->remove(490)) << std::endl;
std::cout << (a->insert(221)) << std::endl;
std::cout << (d->insert(18)) << std::endl;
c->printPretty();
std::cout << (e->remove(385)) << std::endl;
std::cout << (a->insert(246)) << std::endl;
std::cout << (d->insert(18)) << std::endl;
*a=*b;
*d=*e;
*d=*c;
e->printPretty();
std::cout << (d->insert(110)) << std::endl;
*e=*d;
std::cout << (b->insert(241)) << std::endl;
std::cout << (e->insert(290)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
std::cout << (c->remove(444)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (a->insert(282)) << std::endl;
d->printPretty();
std::cout << (d->insert(356)) << std::endl;
*a=*c;
std::cout << (b->insert(76)) << std::endl;
std::cout << (a->remove(241)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (e->insert(290)) << std::endl;
std::cout << (b->remove(46)) << std::endl;
std::cout << (e->insert(221)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
std::cout << (c->remove(187)) << std::endl;
std::cout << (d->insert(465)) << std::endl;
d->printPretty();
std::cout << (a->remove(353)) << std::endl;
a->printPretty();
std::cout << (a->remove(221)) << std::endl;
*e=*e;
*e=*e;
std::cout << (c->remove(203)) << std::endl;
std::cout << (e->insert(110)) << std::endl;
std::cout << (e->remove(159)) << std::endl;
e->printPretty();
std::cout << (a->remove(148)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
std::cout << (c->insert(353)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
e->printPretty();
std::cout << (b->insert(35)) << std::endl;
std::cout << (e->remove(221)) << std::endl;
std::cout << (c->insert(486)) << std::endl;
d->printPretty();
std::cout << (d->remove(241)) << std::endl;
std::cout << (c->insert(313)) << std::endl;
*b=*b;
std::cout << (e->remove(286)) << std::endl;
std::cout << (d->insert(168)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
*d=*a;
*d=*b;
std::cout << (d->insert(92)) << std::endl;
std::cout << (c->remove(470)) << std::endl;
*c=*d;
e->printPretty();
std::cout << (d->insert(76)) << std::endl;
*c=*b;
std::cout << (d->insert(172)) << std::endl;
std::cout << (a->insert(110)) << std::endl;
std::cout << (b->remove(320)) << std::endl;
std::cout << (c->insert(76)) << std::endl;
std::cout << (e->remove(470)) << std::endl;
b->printPretty();
std::cout << (d->remove(35)) << std::endl;
*d=*d;
std::cout << (a->insert(449)) << std::endl;
std::cout << (e->remove(386)) << std::endl;
*c=*b;
b->printPretty();
std::cout << (d->remove(7)) << std::endl;
c->printPretty();
std::cout << (b->insert(172)) << std::endl;
b->printPretty();
std::cout << (d->insert(92)) << std::endl;
std::cout << (e->remove(353)) << std::endl;
*b=*a;
std::cout << (e->remove(418)) << std::endl;
*d=*e;
std::cout << (b->remove(110)) << std::endl;
*d=*d;
*d=*e;
std::cout << (b->remove(321)) << std::endl;
std::cout << (a->remove(110)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
e->printPretty();
std::cout << (a->remove(449)) << std::endl;
std::cout << (c->remove(172)) << std::endl;
*b=*e;
std::cout << (c->insert(448)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
std::cout << (b->insert(290)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
a->printPretty();
std::cout << (b->remove(156)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
a->printPretty();
c->printPretty();
*a=*c;
std::cout << (b->remove(241)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
*b=*d;
a->printPretty();
d->printPretty();
std::cout << (e->remove(240)) << std::endl;
std::cout << (b->insert(358)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (e->remove(290)) << std::endl;
*e=*a;
*b=*e;
std::cout << (d->insert(241)) << std::endl;
std::cout << (d->insert(358)) << std::endl;
a->printPretty();
*b=*b;
std::cout << (c->remove(372)) << std::endl;
std::cout << (b->insert(448)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
std::cout << (c->insert(459)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
std::cout << (a->remove(146)) << std::endl;
std::cout << (c->insert(448)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (d->insert(241)) << std::endl;
c->printPretty();
std::cout << (b->remove(154)) << std::endl;
std::cout << (e->remove(404)) << std::endl;
std::cout << (e->remove(245)) << std::endl;
std::cout << (b->insert(26)) << std::endl;
e->printPretty();
std::cout << (a->remove(448)) << std::endl;
c->printPretty();
std::cout << (c->insert(35)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (e->insert(135)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
e->printPretty();
std::cout << (c->remove(35)) << std::endl;
std::cout << (e->remove(448)) << std::endl;
std::cout << (a->insert(374)) << std::endl;
std::cout << (d->insert(103)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
std::cout << (e->remove(438)) << std::endl;
*b=*b;
std::cout << (e->remove(135)) << std::endl;
std::cout << (e->insert(232)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
std::cout << (c->insert(104)) << std::endl;
std::cout << (d->insert(229)) << std::endl;
*b=*c;
std::cout << (c->insert(104)) << std::endl;
*a=*a;
*e=*a;
std::cout << (a->insert(374)) << std::endl;
std::cout << (d->insert(103)) << std::endl;
std::cout << (d->insert(290)) << std::endl;
e->printPretty();
std::cout << (e->insert(241)) << std::endl;
a->printPretty();
std::cout << (a->remove(322)) << std::endl;
std::cout << (a->remove(374)) << std::endl;
std::cout << (d->insert(398)) << std::endl;
std::cout << (a->insert(35)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
*d=*e;
*c=*b;
*d=*d;
*c=*d;
e->printPretty();
c->printPretty();
std::cout << (e->remove(343)) << std::endl;
*e=*c;
*e=*b;
std::cout << (c->remove(252)) << std::endl;
std::cout << (a->insert(241)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
*a=*a;
std::cout << (a->remove(35)) << std::endl;
std::cout << (a->insert(171)) << std::endl;
std::cout << (d->remove(35)) << std::endl;
c->printPretty();
c->printPretty();
b->printPretty();
d->printPretty();
std::cout << (c->insert(395)) << std::endl;
std::cout << (a->insert(479)) << std::endl;
*c=*a;
std::cout << (a->remove(48)) << std::endl;
*e=*c;
a->printPretty();
*d=*c;
std::cout << (c->remove(479)) << std::endl;
*d=*b;
*d=*a;
e->printPretty();
*c=*e;
std::cout << (a->remove(171)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->insert(449)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (b->remove(18)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
a->printPretty();
std::cout << (e->insert(426)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
*b=*d;
*a=*a;
std::cout << (c->remove(80)) << std::endl;
a->printPretty();
c->printPretty();
d->printPretty();
std::cout << (b->insert(171)) << std::endl;
std::cout << (a->remove(440)) << std::endl;
std::cout << (e->remove(33)) << std::endl;
std::cout << (a->remove(76)) << std::endl;
std::cout << (c->insert(241)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
std::cout << (c->remove(314)) << std::endl;
std::cout << (e->remove(426)) << std::endl;
std::cout << (e->remove(241)) << std::endl;
std::cout << (c->insert(164)) << std::endl;
*c=*e;
std::cout << (c->insert(27)) << std::endl;
std::cout << (d->insert(171)) << std::endl;
std::cout << (e->insert(219)) << std::endl;
std::cout << (d->remove(266)) << std::endl;
std::cout << (d->insert(54)) << std::endl;
std::cout << (a->insert(479)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
std::cout << (e->remove(449)) << std::endl;
*e=*b;
std::cout << (a->remove(241)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
std::cout << (a->remove(339)) << std::endl;
std::cout << (e->insert(466)) << std::endl;
*a=*c;
std::cout << (d->insert(449)) << std::endl;
a->printPretty();
std::cout << (c->remove(374)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (e->insert(76)) << std::endl;
std::cout << (e->insert(241)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (a->insert(449)) << std::endl;
*e=*e;
*a=*a;
b->printPretty();
e->printPretty();
a->printPretty();
c->printPretty();
std::cout << (d->remove(449)) << std::endl;
std::cout << (a->remove(228)) << std::endl;
std::cout << (c->insert(479)) << std::endl;
b->printPretty();
std::cout << (e->insert(241)) << std::endl;
b->printPretty();
std::cout << (a->remove(258)) << std::endl;
std::cout << (c->insert(171)) << std::endl;
*c=*b;
std::cout << (c->insert(241)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (c->remove(241)) << std::endl;
std::cout << (a->insert(76)) << std::endl;
std::cout << (e->insert(146)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
*c=*e;
std::cout << (a->insert(449)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
std::cout << (c->remove(449)) << std::endl;
c->printPretty();
std::cout << (b->remove(241)) << std::endl;
std::cout << (c->remove(367)) << std::endl;
std::cout << (a->remove(27)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (e->remove(76)) << std::endl;
std::cout << (b->insert(171)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (d->remove(328)) << std::endl;
c->printPretty();
std::cout << (e->remove(241)) << std::endl;
std::cout << (c->insert(4)) << std::endl;
std::cout << (d->remove(175)) << std::endl;
std::cout << (e->insert(68)) << std::endl;
std::cout << (c->insert(215)) << std::endl;
std::cout << (d->insert(127)) << std::endl;
std::cout << (b->remove(171)) << std::endl;
e->printPretty();
std::cout << (e->remove(459)) << std::endl;
*c=*e;
std::cout << (d->remove(171)) << std::endl;
*c=*b;
std::cout << (d->insert(133)) << std::endl;
e->printPretty();
*e=*e;
std::cout << (b->insert(251)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (a->remove(216)) << std::endl;
c->printPretty();
std::cout << (d->remove(241)) << std::endl;
std::cout << (d->remove(148)) << std::endl;
c->printPretty();
std::cout << (a->remove(158)) << std::endl;
*d=*e;
std::cout << (d->remove(68)) << std::endl;
std::cout << (c->remove(491)) << std::endl;
c->printPretty();
c->printPretty();
a->printPretty();
std::cout << (a->insert(76)) << std::endl;
std::cout << (d->remove(417)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
std::cout << (b->remove(43)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
*a=*a;
std::cout << (d->insert(57)) << std::endl;
std::cout << (d->remove(57)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
std::cout << (c->insert(452)) << std::endl;
b->printPretty();
std::cout << (a->remove(165)) << std::endl;
d->printPretty();
std::cout << (e->remove(146)) << std::endl;
std::cout << (e->insert(255)) << std::endl;
*a=*d;
std::cout << (a->remove(278)) << std::endl;
std::cout << (c->remove(452)) << std::endl;
std::cout << (e->insert(466)) << std::endl;
*e=*c;
std::cout << (c->insert(447)) << std::endl;
b->printPretty();
*c=*c;
*d=*d;
std::cout << (a->remove(227)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
*a=*a;
std::cout << (b->insert(404)) << std::endl;
*a=*b;
std::cout << (d->insert(171)) << std::endl;
std::cout << (c->remove(174)) << std::endl;
*b=*a;
std::cout << (c->remove(447)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
*e=*b;
std::cout << (b->insert(159)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
*c=*a;
d->printPretty();
*a=*e;
std::cout << (b->insert(251)) << std::endl;
*d=*d;
std::cout << (a->remove(5)) << std::endl;
std::cout << (b->insert(415)) << std::endl;
std::cout << (c->remove(176)) << std::endl;
*a=*e;
a->printPretty();
*e=*c;
std::cout << (b->insert(445)) << std::endl;
std::cout << (c->remove(410)) << std::endl;
std::cout << (e->insert(404)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
b->printPretty();
std::cout << (b->insert(415)) << std::endl;
std::cout << (a->insert(251)) << std::endl;
std::cout << (c->insert(230)) << std::endl;
*d=*c;
std::cout << (e->remove(251)) << std::endl;
std::cout << (b->insert(277)) << std::endl;
std::cout << (a->insert(134)) << std::endl;
std::cout << (b->insert(445)) << std::endl;
*b=*a;
std::cout << (e->insert(404)) << std::endl;
std::cout << (c->remove(251)) << std::endl;
std::cout << (d->remove(225)) << std::endl;
std::cout << (a->insert(77)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (e->remove(463)) << std::endl;
std::cout << (b->insert(404)) << std::endl;
c->printPretty();
std::cout << (e->remove(404)) << std::endl;
*a=*d;
std::cout << (d->insert(404)) << std::endl;
std::cout << (c->remove(12)) << std::endl;
c->printPretty();
std::cout << (d->insert(453)) << std::endl;
std::cout << (a->insert(230)) << std::endl;
std::cout << (c->insert(53)) << std::endl;
std::cout << (b->insert(201)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
*c=*b;
std::cout << (a->insert(251)) << std::endl;
*a=*e;
*d=*c;
std::cout << (b->remove(404)) << std::endl;
std::cout << (d->remove(201)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(346)) << std::endl;
b->printPretty();
std::cout << (c->insert(201)) << std::endl;
a->printPretty();
std::cout << (b->insert(201)) << std::endl;
d->printPretty();
std::cout << (e->remove(45)) << std::endl;
std::cout << (a->insert(162)) << std::endl;
*d=*e;
std::cout << (b->remove(350)) << std::endl;
std::cout << (b->remove(251)) << std::endl;
e->printPretty();
std::cout << (a->insert(162)) << std::endl;
*c=*a;
std::cout << (c->insert(492)) << std::endl;
std::cout << (e->insert(346)) << std::endl;
std::cout << (e->remove(346)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
std::cout << (d->remove(169)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (c->remove(210)) << std::endl;
*c=*a;
std::cout << (e->insert(6)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
*b=*d;
std::cout << (d->insert(19)) << std::endl;
std::cout << (d->insert(375)) << std::endl;
std::cout << (a->remove(420)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (c->remove(125)) << std::endl;
*b=*a;
std::cout << (e->remove(472)) << std::endl;
std::cout << (c->remove(236)) << std::endl;
std::cout << (c->remove(493)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (c->remove(266)) << std::endl;
*b=*d;
d->printPretty();
std::cout << (e->remove(418)) << std::endl;
std::cout << (c->insert(302)) << std::endl;
std::cout << (b->insert(343)) << std::endl;
std::cout << (c->remove(302)) << std::endl;
std::cout << (c->insert(390)) << std::endl;
std::cout << (d->insert(207)) << std::endl;
std::cout << (b->remove(343)) << std::endl;
b->printPretty();
std::cout << (d->remove(287)) << std::endl;
std::cout << (c->insert(388)) << std::endl;
*c=*e;
std::cout << (e->remove(487)) << std::endl;
std::cout << (a->remove(162)) << std::endl;
*d=*c;
std::cout << (c->insert(480)) << std::endl;
std::cout << (c->remove(480)) << std::endl;
*e=*b;
*c=*a;
*b=*e;
std::cout << (d->insert(6)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(247)) << std::endl;
std::cout << (d->insert(32)) << std::endl;
*a=*d;
std::cout << (d->remove(32)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
std::cout << (e->insert(339)) << std::endl;
std::cout << (b->insert(175)) << std::endl;
b->printPretty();
a->printPretty();
*d=*d;
c->printPretty();
std::cout << (c->remove(82)) << std::endl;
e->printPretty();
std::cout << (c->remove(378)) << std::endl;
std::cout << (d->insert(6)) << std::endl;
c->printPretty();
std::cout << (a->remove(32)) << std::endl;
std::cout << (b->insert(145)) << std::endl;
std::cout << (d->remove(6)) << std::endl;
std::cout << (d->insert(331)) << std::endl;
std::cout << (c->insert(359)) << std::endl;
std::cout << (a->remove(247)) << std::endl;
a->printPretty();
std::cout << (e->insert(152)) << std::endl;
c->printPretty();
std::cout << (e->remove(19)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
*a=*b;
std::cout << (c->remove(359)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (c->insert(71)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
e->printPretty();
std::cout << (e->remove(50)) << std::endl;
std::cout << (c->insert(71)) << std::endl;
a->printPretty();
std::cout << (e->remove(375)) << std::endl;
std::cout << (e->insert(447)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (e->remove(339)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
c->printPretty();
std::cout << (c->insert(495)) << std::endl;
std::cout << (b->insert(491)) << std::endl;
std::cout << (b->remove(143)) << std::endl;
std::cout << (c->remove(175)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
std::cout << (b->insert(145)) << std::endl;
c->printPretty();
std::cout << (e->insert(447)) << std::endl;
std::cout << (a->insert(19)) << std::endl;
c->printPretty();
std::cout << (d->remove(287)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
std::cout << (e->remove(377)) << std::endl;
std::cout << (c->insert(252)) << std::endl;
e->printPretty();
std::cout << (c->remove(160)) << std::endl;
std::cout << (c->remove(378)) << std::endl;
b->printPretty();
std::cout << (e->remove(152)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
std::cout << (d->insert(82)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->remove(82)) << std::endl;
std::cout << (b->remove(174)) << std::endl;
std::cout << (a->remove(304)) << std::endl;
std::cout << (c->remove(488)) << std::endl;
std::cout << (b->insert(375)) << std::endl;
*e=*e;
*d=*b;
*a=*d;
std::cout << (a->insert(247)) << std::endl;
*e=*c;
std::cout << (d->remove(242)) << std::endl;
*b=*c;
*c=*b;
std::cout << (b->remove(487)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
*b=*b;
std::cout << (d->remove(145)) << std::endl;
std::cout << (a->insert(390)) << std::endl;
std::cout << (c->insert(450)) << std::endl;
std::cout << (b->insert(239)) << std::endl;
std::cout << (c->remove(252)) << std::endl;
*a=*d;
std::cout << (a->remove(436)) << std::endl;
std::cout << (c->insert(15)) << std::endl;
std::cout << (b->insert(66)) << std::endl;
std::cout << (d->insert(375)) << std::endl;
c->printPretty();
std::cout << (d->insert(19)) << std::endl;
std::cout << (b->remove(364)) << std::endl;
std::cout << (c->insert(487)) << std::endl;
std::cout << (e->remove(487)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (b->insert(252)) << std::endl;
*d=*d;
std::cout << (e->insert(284)) << std::endl;
e->printPretty();
*d=*e;
std::cout << (a->remove(165)) << std::endl;
std::cout << (e->remove(433)) << std::endl;
std::cout << (a->remove(473)) << std::endl;
std::cout << (a->remove(251)) << std::endl;
std::cout << (e->remove(450)) << std::endl;
b->printPretty();
b->printPretty();
a->printPretty();
std::cout << (c->insert(71)) << std::endl;
std::cout << (d->insert(284)) << std::endl;
std::cout << (b->insert(468)) << std::endl;
c->printPretty();
*c=*d;
std::cout << (c->remove(450)) << std::endl;
std::cout << (b->remove(405)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
std::cout << (d->remove(363)) << std::endl;
a->printPretty();
c->printPretty();
a->printPretty();
e->printPretty();
std::cout << (d->insert(284)) << std::endl;
std::cout << (c->remove(252)) << std::endl;
std::cout << (a->insert(130)) << std::endl;
std::cout << (d->insert(252)) << std::endl;
*a=*c;
std::cout << (d->remove(284)) << std::endl;
std::cout << (a->remove(63)) << std::endl;
b->printPretty();
std::cout << (d->insert(236)) << std::endl;
std::cout << (c->insert(136)) << std::endl;
e->printPretty();
*e=*a;
e->printPretty();
std::cout << (c->insert(284)) << std::endl;
std::cout << (d->insert(164)) << std::endl;
*e=*e;
std::cout << (c->insert(495)) << std::endl;
*b=*e;
std::cout << (c->remove(242)) << std::endl;
std::cout << (a->remove(1)) << std::endl;
std::cout << (a->remove(60)) << std::endl;
std::cout << (e->remove(444)) << std::endl;
std::cout << (c->insert(71)) << std::endl;
std::cout << (d->remove(239)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
d->printPretty();
*a=*b;
std::cout << (d->insert(164)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
std::cout << (b->remove(71)) << std::endl;
std::cout << (b->remove(282)) << std::endl;
std::cout << (a->remove(413)) << std::endl;
std::cout << (d->insert(450)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (e->remove(37)) << std::endl;
std::cout << (e->insert(450)) << std::endl;
*b=*e;
std::cout << (c->insert(352)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (c->remove(45)) << std::endl;
*b=*e;
*a=*d;
std::cout << (e->remove(450)) << std::endl;
std::cout << (a->remove(71)) << std::endl;
*c=*a;
std::cout << (d->insert(36)) << std::endl;
std::cout << (e->insert(345)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (a->insert(164)) << std::endl;
std::cout << (b->insert(422)) << std::endl;
return 0;
}
