#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(14)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
b->printPretty();
b->printPretty();
std::cout << (a->remove(242)) << std::endl;
a->printPretty();
std::cout << (b->remove(334)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
std::cout << (b->remove(116)) << std::endl;
*c=*b;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
std::cout << (b->remove(437)) << std::endl;
*c=*b;
*d=*a;
std::cout << (c->insert(339)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>;
*c=*b;
*d=*e;
std::cout << (e->remove(22)) << std::endl;
a->printPretty();
std::cout << (b->insert(395)) << std::endl;
*c=*b;
*c=*e;
*c=*d;
std::cout << (e->remove(82)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (d->remove(301)) << std::endl;
std::cout << (d->remove(469)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
std::cout << (d->remove(491)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
std::cout << (d->insert(56)) << std::endl;
std::cout << (d->remove(137)) << std::endl;
std::cout << (b->insert(395)) << std::endl;
std::cout << (e->remove(152)) << std::endl;
std::cout << (e->insert(343)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
std::cout << (e->insert(48)) << std::endl;
std::cout << (d->remove(56)) << std::endl;
a->printPretty();
std::cout << (b->remove(395)) << std::endl;
*b=*a;
e->printPretty();
e->printPretty();
*d=*c;
std::cout << (c->remove(288)) << std::endl;
d->printPretty();
std::cout << (c->remove(100)) << std::endl;
std::cout << (e->remove(343)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
std::cout << (b->remove(400)) << std::endl;
*a=*c;
std::cout << (e->insert(427)) << std::endl;
c->printPretty();
std::cout << (e->insert(427)) << std::endl;
std::cout << (c->insert(441)) << std::endl;
*c=*c;
e->printPretty();
std::cout << (b->insert(377)) << std::endl;
std::cout << (b->remove(197)) << std::endl;
std::cout << (c->remove(318)) << std::endl;
std::cout << (d->remove(40)) << std::endl;
std::cout << (c->insert(417)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
std::cout << (e->insert(427)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (d->insert(9)) << std::endl;
std::cout << (b->insert(256)) << std::endl;
a->printPretty();
std::cout << (b->remove(256)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
c->printPretty();
std::cout << (d->remove(46)) << std::endl;
std::cout << (c->insert(417)) << std::endl;
std::cout << (e->insert(105)) << std::endl;
c->printPretty();
std::cout << (c->remove(57)) << std::endl;
std::cout << (e->remove(427)) << std::endl;
std::cout << (a->insert(482)) << std::endl;
std::cout << (a->remove(482)) << std::endl;
std::cout << (d->remove(308)) << std::endl;
std::cout << (e->insert(387)) << std::endl;
d->printPretty();
std::cout << (b->remove(377)) << std::endl;
std::cout << (d->insert(349)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
std::cout << (c->insert(342)) << std::endl;
*b=*c;
std::cout << (c->remove(417)) << std::endl;
c->printPretty();
std::cout << (a->remove(233)) << std::endl;
std::cout << (e->insert(497)) << std::endl;
std::cout << (a->remove(348)) << std::endl;
std::cout << (a->insert(469)) << std::endl;
std::cout << (b->insert(93)) << std::endl;
std::cout << (e->remove(105)) << std::endl;
*e=*d;
*b=*e;
std::cout << (e->insert(9)) << std::endl;
std::cout << (b->remove(94)) << std::endl;
std::cout << (d->insert(267)) << std::endl;
*e=*a;
std::cout << (d->remove(9)) << std::endl;
std::cout << (c->remove(33)) << std::endl;
std::cout << (e->remove(229)) << std::endl;
std::cout << (a->insert(469)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
std::cout << (c->insert(480)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
std::cout << (a->remove(91)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
*b=*a;
e->printPretty();
std::cout << (a->remove(461)) << std::endl;
std::cout << (c->insert(312)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (e->remove(171)) << std::endl;
*a=*b;
std::cout << (b->insert(469)) << std::endl;
std::cout << (e->insert(217)) << std::endl;
std::cout << (d->remove(339)) << std::endl;
*d=*b;
*d=*d;
std::cout << (c->insert(342)) << std::endl;
std::cout << (c->remove(207)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (c->remove(312)) << std::endl;
*d=*c;
std::cout << (d->insert(86)) << std::endl;
std::cout << (e->remove(213)) << std::endl;
std::cout << (a->insert(469)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (c->insert(152)) << std::endl;
std::cout << (a->remove(19)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (c->remove(307)) << std::endl;
std::cout << (e->insert(132)) << std::endl;
*a=*c;
*c=*a;
std::cout << (d->remove(342)) << std::endl;
a->printPretty();
b->printPretty();
*c=*c;
std::cout << (b->insert(207)) << std::endl;
*c=*b;
std::cout << (c->insert(360)) << std::endl;
std::cout << (a->remove(86)) << std::endl;
std::cout << (e->remove(132)) << std::endl;
std::cout << (c->remove(377)) << std::endl;
std::cout << (e->insert(52)) << std::endl;
std::cout << (b->remove(65)) << std::endl;
std::cout << (d->remove(393)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
std::cout << (d->remove(441)) << std::endl;
std::cout << (a->insert(118)) << std::endl;
*e=*e;
std::cout << (a->remove(441)) << std::endl;
*c=*d;
d->printPretty();
*a=*e;
std::cout << (c->remove(86)) << std::endl;
e->printPretty();
std::cout << (a->remove(62)) << std::endl;
std::cout << (d->insert(86)) << std::endl;
d->printPretty();
*a=*c;
*d=*d;
std::cout << (a->insert(88)) << std::endl;
e->printPretty();
std::cout << (b->insert(351)) << std::endl;
std::cout << (d->remove(86)) << std::endl;
*e=*d;
std::cout << (a->remove(303)) << std::endl;
*a=*a;
std::cout << (b->remove(479)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(442)) << std::endl;
std::cout << (a->insert(88)) << std::endl;
std::cout << (c->remove(299)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
std::cout << (e->insert(291)) << std::endl;
*d=*b;
std::cout << (e->remove(293)) << std::endl;
std::cout << (e->remove(291)) << std::endl;
*c=*e;
std::cout << (d->remove(351)) << std::endl;
*c=*c;
*b=*b;
std::cout << (b->insert(207)) << std::endl;
std::cout << (b->insert(351)) << std::endl;
d->printPretty();
*c=*e;
a->printPretty();
*c=*e;
std::cout << (d->remove(84)) << std::endl;
std::cout << (a->remove(88)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
std::cout << (d->remove(332)) << std::endl;
*d=*d;
*b=*e;
std::cout << (d->insert(207)) << std::endl;
*e=*e;
std::cout << (d->remove(212)) << std::endl;
std::cout << (d->insert(207)) << std::endl;
std::cout << (e->insert(70)) << std::endl;
a->printPretty();
*a=*c;
*b=*a;
std::cout << (c->insert(475)) << std::endl;
std::cout << (c->insert(475)) << std::endl;
e->printPretty();
std::cout << (a->remove(475)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (c->remove(475)) << std::endl;
*b=*a;
std::cout << (d->remove(207)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (c->insert(52)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (c->remove(488)) << std::endl;
*c=*b;
*c=*d;
std::cout << (a->insert(211)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
*e=*c;
std::cout << (a->insert(211)) << std::endl;
b->printPretty();
*e=*b;
std::cout << (e->remove(280)) << std::endl;
std::cout << (d->insert(351)) << std::endl;
std::cout << (b->remove(175)) << std::endl;
std::cout << (d->remove(425)) << std::endl;
c->printPretty();
std::cout << (a->insert(154)) << std::endl;
std::cout << (a->insert(211)) << std::endl;
std::cout << (d->insert(113)) << std::endl;
a->printPretty();
std::cout << (b->remove(318)) << std::endl;
std::cout << (c->insert(497)) << std::endl;
b->printPretty();
std::cout << (b->insert(57)) << std::endl;
*a=*a;
*d=*a;
std::cout << (a->remove(175)) << std::endl;
std::cout << (b->remove(57)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
c->printPretty();
std::cout << (c->insert(497)) << std::endl;
std::cout << (e->insert(175)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
std::cout << (c->insert(21)) << std::endl;
*c=*e;
std::cout << (c->remove(175)) << std::endl;
e->printPretty();
*e=*e;
b->printPretty();
std::cout << (c->insert(89)) << std::endl;
std::cout << (e->remove(175)) << std::endl;
std::cout << (a->insert(277)) << std::endl;
std::cout << (c->insert(89)) << std::endl;
std::cout << (a->remove(154)) << std::endl;
std::cout << (c->insert(258)) << std::endl;
std::cout << (c->remove(89)) << std::endl;
std::cout << (d->insert(465)) << std::endl;
std::cout << (b->insert(454)) << std::endl;
e->printPretty();
std::cout << (d->insert(154)) << std::endl;
*c=*a;
std::cout << (b->insert(454)) << std::endl;
c->printPretty();
std::cout << (c->remove(438)) << std::endl;
std::cout << (e->remove(108)) << std::endl;
std::cout << (c->insert(211)) << std::endl;
std::cout << (c->remove(68)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
b->printPretty();
std::cout << (d->insert(154)) << std::endl;
std::cout << (a->insert(453)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
e->printPretty();
*a=*b;
std::cout << (c->remove(211)) << std::endl;
std::cout << (e->insert(171)) << std::endl;
std::cout << (d->insert(175)) << std::endl;
std::cout << (c->insert(279)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
b->printPretty();
*b=*c;
std::cout << (b->insert(418)) << std::endl;
std::cout << (b->remove(352)) << std::endl;
*d=*c;
std::cout << (d->remove(277)) << std::endl;
*e=*c;
std::cout << (e->insert(97)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
*c=*b;
c->printPretty();
b->printPretty();
std::cout << (b->insert(21)) << std::endl;
e->printPretty();
e->printPretty();
c->printPretty();
std::cout << (c->insert(77)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
std::cout << (d->remove(138)) << std::endl;
std::cout << (a->remove(289)) << std::endl;
std::cout << (e->remove(393)) << std::endl;
std::cout << (a->remove(311)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
std::cout << (a->insert(378)) << std::endl;
*b=*e;
std::cout << (b->remove(61)) << std::endl;
std::cout << (c->remove(494)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
d->printPretty();
std::cout << (d->insert(279)) << std::endl;
std::cout << (d->remove(96)) << std::endl;
*b=*d;
std::cout << (e->insert(277)) << std::endl;
std::cout << (b->insert(37)) << std::endl;
std::cout << (a->remove(378)) << std::endl;
std::cout << (e->insert(334)) << std::endl;
std::cout << (b->remove(47)) << std::endl;
std::cout << (c->remove(73)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (d->insert(360)) << std::endl;
std::cout << (e->remove(334)) << std::endl;
std::cout << (c->insert(429)) << std::endl;
std::cout << (b->remove(37)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
std::cout << (d->insert(426)) << std::endl;
std::cout << (c->remove(303)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
std::cout << (c->insert(178)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (a->remove(269)) << std::endl;
*e=*d;
std::cout << (c->remove(277)) << std::endl;
std::cout << (b->remove(426)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (d->remove(47)) << std::endl;
std::cout << (e->insert(449)) << std::endl;
std::cout << (b->insert(155)) << std::endl;
std::cout << (c->remove(450)) << std::endl;
std::cout << (e->remove(179)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
*d=*a;
*b=*b;
std::cout << (e->remove(360)) << std::endl;
std::cout << (e->insert(206)) << std::endl;
*d=*b;
std::cout << (e->remove(359)) << std::endl;
*d=*c;
std::cout << (e->remove(430)) << std::endl;
b->printPretty();
std::cout << (b->insert(346)) << std::endl;
std::cout << (b->insert(25)) << std::endl;
std::cout << (d->remove(489)) << std::endl;
std::cout << (d->insert(241)) << std::endl;
std::cout << (e->insert(279)) << std::endl;
std::cout << (b->remove(25)) << std::endl;
std::cout << (e->remove(279)) << std::endl;
std::cout << (a->insert(454)) << std::endl;
b->printPretty();
*d=*b;
a->printPretty();
std::cout << (b->remove(421)) << std::endl;
std::cout << (d->remove(33)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
std::cout << (b->remove(29)) << std::endl;
std::cout << (b->remove(155)) << std::endl;
std::cout << (e->insert(69)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
std::cout << (d->remove(407)) << std::endl;
*e=*b;
std::cout << (c->remove(77)) << std::endl;
std::cout << (c->remove(46)) << std::endl;
*d=*e;
*e=*d;
std::cout << (b->remove(391)) << std::endl;
d->printPretty();
std::cout << (a->remove(454)) << std::endl;
std::cout << (b->insert(141)) << std::endl;
std::cout << (e->insert(285)) << std::endl;
std::cout << (c->remove(429)) << std::endl;
std::cout << (a->remove(385)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (b->remove(469)) << std::endl;
std::cout << (e->remove(346)) << std::endl;
std::cout << (c->insert(51)) << std::endl;
std::cout << (e->remove(2)) << std::endl;
*a=*a;
std::cout << (b->insert(303)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (c->insert(195)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
*d=*c;
*c=*d;
*d=*e;
std::cout << (b->insert(25)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (c->remove(195)) << std::endl;
std::cout << (c->remove(418)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
*e=*c;
std::cout << (b->insert(495)) << std::endl;
b->printPretty();
*b=*b;
std::cout << (c->insert(121)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
std::cout << (d->remove(488)) << std::endl;
*d=*d;
std::cout << (c->insert(455)) << std::endl;
std::cout << (b->insert(8)) << std::endl;
*e=*c;
std::cout << (b->remove(51)) << std::endl;
std::cout << (d->insert(469)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
std::cout << (d->insert(67)) << std::endl;
std::cout << (c->insert(121)) << std::endl;
std::cout << (b->insert(302)) << std::endl;
a->printPretty();
std::cout << (d->insert(81)) << std::endl;
*b=*c;
std::cout << (d->remove(458)) << std::endl;
std::cout << (e->remove(455)) << std::endl;
*c=*b;
std::cout << (b->insert(121)) << std::endl;
std::cout << (b->insert(455)) << std::endl;
std::cout << (e->remove(51)) << std::endl;
std::cout << (b->insert(473)) << std::endl;
std::cout << (c->insert(121)) << std::endl;
std::cout << (a->remove(15)) << std::endl;
std::cout << (e->remove(447)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
std::cout << (a->remove(141)) << std::endl;
std::cout << (c->insert(455)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
std::cout << (a->remove(204)) << std::endl;
a->printPretty();
d->printPretty();
d->printPretty();
std::cout << (c->remove(121)) << std::endl;
std::cout << (a->insert(106)) << std::endl;
e->printPretty();
std::cout << (b->remove(337)) << std::endl;
std::cout << (b->insert(431)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (a->insert(60)) << std::endl;
c->printPretty();
b->printPretty();
std::cout << (d->remove(433)) << std::endl;
*d=*b;
*d=*e;
std::cout << (b->remove(121)) << std::endl;
std::cout << (b->insert(478)) << std::endl;
*d=*e;
b->printPretty();
std::cout << (c->remove(455)) << std::endl;
*b=*a;
std::cout << (a->remove(60)) << std::endl;
std::cout << (a->remove(374)) << std::endl;
b->printPretty();
std::cout << (a->insert(398)) << std::endl;
*d=*c;
std::cout << (b->remove(269)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
e->printPretty();
std::cout << (a->remove(398)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (d->remove(260)) << std::endl;
*c=*c;
c->printPretty();
std::cout << (b->remove(60)) << std::endl;
c->printPretty();
*e=*a;
std::cout << (a->insert(104)) << std::endl;
std::cout << (a->insert(34)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (a->remove(34)) << std::endl;
std::cout << (b->remove(367)) << std::endl;
d->printPretty();
std::cout << (a->remove(221)) << std::endl;
std::cout << (c->remove(457)) << std::endl;
std::cout << (c->insert(208)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
std::cout << (e->insert(84)) << std::endl;
e->printPretty();
a->printPretty();
*b=*d;
std::cout << (b->remove(233)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
std::cout << (d->insert(215)) << std::endl;
std::cout << (d->remove(145)) << std::endl;
*e=*e;
*e=*b;
std::cout << (d->remove(215)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (a->remove(141)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->insert(11)) << std::endl;
b->printPretty();
d->printPretty();
a->printPretty();
std::cout << (b->insert(211)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
b->printPretty();
std::cout << (d->insert(230)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (e->insert(11)) << std::endl;
std::cout << (c->remove(208)) << std::endl;
std::cout << (a->insert(344)) << std::endl;
std::cout << (d->insert(471)) << std::endl;
std::cout << (c->remove(191)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
std::cout << (b->remove(196)) << std::endl;
std::cout << (c->remove(318)) << std::endl;
std::cout << (b->remove(211)) << std::endl;
std::cout << (e->insert(354)) << std::endl;
*b=*a;
std::cout << (e->remove(125)) << std::endl;
std::cout << (d->insert(476)) << std::endl;
d->printPretty();
*a=*a;
b->printPretty();
*c=*a;
std::cout << (b->remove(344)) << std::endl;
std::cout << (d->remove(213)) << std::endl;
std::cout << (c->remove(344)) << std::endl;
std::cout << (d->remove(92)) << std::endl;
*e=*a;
std::cout << (d->remove(23)) << std::endl;
std::cout << (b->remove(421)) << std::endl;
std::cout << (c->insert(286)) << std::endl;
c->printPretty();
std::cout << (a->remove(344)) << std::endl;
std::cout << (c->remove(286)) << std::endl;
std::cout << (e->insert(344)) << std::endl;
std::cout << (d->insert(459)) << std::endl;
c->printPretty();
std::cout << (a->remove(41)) << std::endl;
e->printPretty();
std::cout << (c->remove(262)) << std::endl;
std::cout << (d->insert(438)) << std::endl;
d->printPretty();
std::cout << (e->remove(441)) << std::endl;
std::cout << (a->remove(72)) << std::endl;
std::cout << (c->insert(290)) << std::endl;
std::cout << (c->remove(290)) << std::endl;
std::cout << (c->remove(381)) << std::endl;
c->printPretty();
std::cout << (d->insert(471)) << std::endl;
std::cout << (b->remove(305)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
std::cout << (b->insert(71)) << std::endl;
std::cout << (c->insert(308)) << std::endl;
std::cout << (c->insert(246)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (a->insert(499)) << std::endl;
std::cout << (d->remove(485)) << std::endl;
std::cout << (e->remove(344)) << std::endl;
*e=*d;
b->printPretty();
a->printPretty();
std::cout << (b->remove(71)) << std::endl;
*b=*a;
std::cout << (a->insert(389)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (c->insert(5)) << std::endl;
std::cout << (c->remove(246)) << std::endl;
*d=*c;
a->printPretty();
c->printPretty();
d->printPretty();
std::cout << (c->remove(441)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
*d=*b;
std::cout << (b->insert(95)) << std::endl;
std::cout << (d->insert(428)) << std::endl;
c->printPretty();
std::cout << (e->remove(32)) << std::endl;
c->printPretty();
std::cout << (b->remove(389)) << std::endl;
std::cout << (d->remove(232)) << std::endl;
*a=*d;
std::cout << (b->remove(499)) << std::endl;
*e=*d;
*b=*b;
std::cout << (a->remove(499)) << std::endl;
std::cout << (b->remove(340)) << std::endl;
std::cout << (e->insert(460)) << std::endl;
*b=*a;
std::cout << (c->remove(79)) << std::endl;
std::cout << (e->remove(308)) << std::endl;
std::cout << (a->insert(389)) << std::endl;
std::cout << (c->remove(5)) << std::endl;
*d=*c;
std::cout << (e->remove(463)) << std::endl;
std::cout << (a->insert(336)) << std::endl;
std::cout << (e->insert(499)) << std::endl;
*d=*a;
std::cout << (c->remove(441)) << std::endl;
std::cout << (a->insert(255)) << std::endl;
std::cout << (d->insert(389)) << std::endl;
std::cout << (b->remove(428)) << std::endl;
*c=*a;
a->printPretty();
d->printPretty();
std::cout << (a->remove(474)) << std::endl;
*a=*c;
std::cout << (d->remove(389)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (d->insert(369)) << std::endl;
*c=*b;
std::cout << (a->remove(428)) << std::endl;
std::cout << (a->insert(121)) << std::endl;
std::cout << (c->insert(389)) << std::endl;
std::cout << (b->remove(329)) << std::endl;
std::cout << (c->remove(389)) << std::endl;
std::cout << (d->remove(369)) << std::endl;
*b=*a;
std::cout << (a->remove(82)) << std::endl;
std::cout << (b->remove(336)) << std::endl;
std::cout << (e->remove(389)) << std::endl;
return 0;
}
