#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
std::cout << (a->remove(276)) << std::endl;
a->printPretty();
std::cout << (a->remove(63)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
std::cout << (b->remove(140)) << std::endl;
std::cout << (a->insert(93)) << std::endl;
std::cout << (b->remove(168)) << std::endl;
a->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
a->printPretty();
std::cout << (a->insert(93)) << std::endl;
c->printPretty();
std::cout << (a->insert(492)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
std::cout << (c->insert(461)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*c);
std::cout << (b->remove(235)) << std::endl;
std::cout << (b->insert(492)) << std::endl;
d->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>(*c);
c->printPretty();
std::cout << (a->remove(93)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
b->printPretty();
*b=*a;
std::cout << (b->insert(437)) << std::endl;
*e=*b;
*c=*a;
std::cout << (d->remove(403)) << std::endl;
std::cout << (a->insert(413)) << std::endl;
b->printPretty();
std::cout << (a->remove(413)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (e->remove(437)) << std::endl;
d->printPretty();
std::cout << (c->insert(482)) << std::endl;
std::cout << (d->insert(93)) << std::endl;
std::cout << (c->insert(492)) << std::endl;
std::cout << (d->remove(461)) << std::endl;
*c=*d;
a->printPretty();
c->printPretty();
std::cout << (d->insert(472)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
e->printPretty();
std::cout << (c->insert(109)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
c->printPretty();
*c=*c;
std::cout << (c->insert(314)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
c->printPretty();
std::cout << (d->insert(293)) << std::endl;
std::cout << (c->remove(9)) << std::endl;
std::cout << (b->remove(437)) << std::endl;
*e=*a;
*c=*a;
d->printPretty();
std::cout << (d->remove(293)) << std::endl;
c->printPretty();
std::cout << (c->remove(342)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
std::cout << (d->remove(377)) << std::endl;
c->printPretty();
e->printPretty();
*b=*a;
*b=*d;
*b=*a;
*c=*c;
*d=*e;
*a=*e;
*c=*e;
*b=*c;
std::cout << (a->remove(248)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (b->insert(63)) << std::endl;
std::cout << (d->insert(93)) << std::endl;
d->printPretty();
std::cout << (b->remove(45)) << std::endl;
std::cout << (d->insert(93)) << std::endl;
e->printPretty();
*c=*a;
std::cout << (c->remove(145)) << std::endl;
*d=*e;
*e=*d;
std::cout << (e->remove(36)) << std::endl;
*b=*c;
std::cout << (b->insert(373)) << std::endl;
std::cout << (d->remove(302)) << std::endl;
c->printPretty();
std::cout << (e->insert(369)) << std::endl;
*d=*a;
*d=*d;
b->printPretty();
std::cout << (c->insert(244)) << std::endl;
std::cout << (d->insert(330)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (b->insert(452)) << std::endl;
std::cout << (c->insert(284)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
*a=*d;
std::cout << (b->remove(452)) << std::endl;
*d=*b;
std::cout << (a->remove(411)) << std::endl;
a->printPretty();
*b=*c;
std::cout << (e->remove(369)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->insert(172)) << std::endl;
a->printPretty();
std::cout << (e->insert(306)) << std::endl;
*e=*b;
std::cout << (e->remove(178)) << std::endl;
std::cout << (c->insert(278)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
c->printPretty();
std::cout << (c->insert(284)) << std::endl;
d->printPretty();
std::cout << (e->insert(184)) << std::endl;
std::cout << (d->insert(319)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (c->insert(269)) << std::endl;
std::cout << (d->insert(339)) << std::endl;
std::cout << (b->insert(278)) << std::endl;
std::cout << (b->remove(278)) << std::endl;
*d=*c;
std::cout << (a->insert(92)) << std::endl;
std::cout << (a->remove(92)) << std::endl;
std::cout << (b->remove(284)) << std::endl;
std::cout << (e->insert(284)) << std::endl;
*a=*e;
*a=*b;
std::cout << (b->insert(244)) << std::endl;
e->printPretty();
std::cout << (e->insert(486)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
*e=*c;
std::cout << (d->remove(269)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (e->insert(170)) << std::endl;
std::cout << (c->insert(54)) << std::endl;
std::cout << (a->remove(373)) << std::endl;
*c=*d;
std::cout << (d->remove(244)) << std::endl;
*d=*d;
*e=*d;
std::cout << (d->insert(284)) << std::endl;
std::cout << (b->remove(368)) << std::endl;
std::cout << (a->insert(367)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
a->printPretty();
std::cout << (e->insert(278)) << std::endl;
*a=*b;
std::cout << (a->insert(235)) << std::endl;
*a=*c;
std::cout << (e->insert(74)) << std::endl;
std::cout << (e->remove(284)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (b->insert(244)) << std::endl;
std::cout << (a->insert(196)) << std::endl;
*c=*c;
*c=*d;
std::cout << (e->insert(278)) << std::endl;
*a=*e;
std::cout << (e->remove(74)) << std::endl;
std::cout << (c->insert(499)) << std::endl;
std::cout << (d->remove(44)) << std::endl;
*c=*b;
std::cout << (d->insert(278)) << std::endl;
*b=*a;
std::cout << (b->insert(278)) << std::endl;
d->printPretty();
*b=*d;
std::cout << (b->remove(463)) << std::endl;
std::cout << (e->remove(327)) << std::endl;
*c=*a;
std::cout << (d->insert(284)) << std::endl;
std::cout << (c->insert(202)) << std::endl;
*d=*e;
*d=*d;
std::cout << (d->insert(499)) << std::endl;
*d=*a;
*a=*e;
std::cout << (a->insert(278)) << std::endl;
std::cout << (e->insert(269)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
d->printPretty();
std::cout << (a->remove(278)) << std::endl;
*d=*e;
std::cout << (c->insert(202)) << std::endl;
std::cout << (a->remove(499)) << std::endl;
std::cout << (c->insert(74)) << std::endl;
std::cout << (b->remove(499)) << std::endl;
b->printPretty();
std::cout << (b->insert(480)) << std::endl;
*e=*a;
std::cout << (a->insert(146)) << std::endl;
*b=*a;
c->printPretty();
std::cout << (a->insert(146)) << std::endl;
std::cout << (b->remove(146)) << std::endl;
std::cout << (c->remove(499)) << std::endl;
std::cout << (d->remove(269)) << std::endl;
std::cout << (b->insert(173)) << std::endl;
std::cout << (a->remove(282)) << std::endl;
a->printPretty();
std::cout << (b->insert(3)) << std::endl;
c->printPretty();
*c=*a;
std::cout << (d->remove(278)) << std::endl;
std::cout << (c->insert(294)) << std::endl;
std::cout << (b->insert(173)) << std::endl;
std::cout << (a->insert(146)) << std::endl;
*a=*d;
c->printPretty();
*c=*d;
std::cout << (b->remove(173)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
*e=*c;
std::cout << (b->insert(9)) << std::endl;
std::cout << (c->remove(269)) << std::endl;
b->printPretty();
std::cout << (b->insert(293)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (d->insert(444)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
*c=*b;
*b=*b;
std::cout << (d->insert(444)) << std::endl;
std::cout << (b->insert(293)) << std::endl;
std::cout << (c->insert(82)) << std::endl;
*e=*e;
std::cout << (b->insert(206)) << std::endl;
std::cout << (a->insert(149)) << std::endl;
std::cout << (a->insert(422)) << std::endl;
std::cout << (c->remove(445)) << std::endl;
std::cout << (d->remove(444)) << std::endl;
std::cout << (d->remove(46)) << std::endl;
*e=*d;
std::cout << (d->remove(485)) << std::endl;
std::cout << (c->remove(3)) << std::endl;
std::cout << (d->remove(236)) << std::endl;
c->printPretty();
std::cout << (a->insert(166)) << std::endl;
*e=*e;
std::cout << (a->insert(166)) << std::endl;
a->printPretty();
std::cout << (a->insert(309)) << std::endl;
*a=*b;
std::cout << (b->remove(56)) << std::endl;
a->printPretty();
b->printPretty();
e->printPretty();
d->printPretty();
std::cout << (b->remove(180)) << std::endl;
std::cout << (a->insert(9)) << std::endl;
std::cout << (b->insert(144)) << std::endl;
*e=*c;
std::cout << (e->insert(293)) << std::endl;
*e=*d;
*d=*d;
std::cout << (b->remove(18)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (c->insert(82)) << std::endl;
*e=*d;
std::cout << (a->insert(21)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (c->remove(411)) << std::endl;
b->printPretty();
std::cout << (e->insert(354)) << std::endl;
std::cout << (e->remove(360)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (c->remove(293)) << std::endl;
*c=*d;
std::cout << (e->insert(354)) << std::endl;
d->printPretty();
std::cout << (d->insert(291)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
e->printPretty();
*e=*e;
e->printPretty();
std::cout << (d->remove(155)) << std::endl;
*e=*b;
c->printPretty();
e->printPretty();
e->printPretty();
a->printPretty();
std::cout << (e->insert(293)) << std::endl;
std::cout << (b->remove(144)) << std::endl;
std::cout << (a->remove(293)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
std::cout << (d->insert(291)) << std::endl;
std::cout << (e->remove(144)) << std::endl;
b->printPretty();
std::cout << (a->remove(21)) << std::endl;
std::cout << (c->insert(417)) << std::endl;
std::cout << (b->remove(3)) << std::endl;
std::cout << (c->remove(279)) << std::endl;
std::cout << (b->insert(347)) << std::endl;
e->printPretty();
std::cout << (d->remove(353)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
*d=*a;
*e=*d;
std::cout << (e->insert(429)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
*b=*b;
std::cout << (b->remove(293)) << std::endl;
std::cout << (e->insert(167)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (c->insert(417)) << std::endl;
std::cout << (a->remove(206)) << std::endl;
std::cout << (b->insert(188)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
a->printPretty();
std::cout << (a->insert(492)) << std::endl;
*c=*e;
std::cout << (b->insert(243)) << std::endl;
std::cout << (b->remove(206)) << std::endl;
b->printPretty();
std::cout << (e->insert(429)) << std::endl;
std::cout << (c->insert(19)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
std::cout << (d->insert(9)) << std::endl;
d->printPretty();
*c=*b;
std::cout << (c->remove(472)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (e->remove(206)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (e->remove(429)) << std::endl;
std::cout << (e->remove(183)) << std::endl;
a->printPretty();
a->printPretty();
*c=*a;
std::cout << (e->remove(188)) << std::endl;
std::cout << (d->remove(402)) << std::endl;
std::cout << (d->remove(188)) << std::endl;
a->printPretty();
c->printPretty();
*a=*a;
std::cout << (e->insert(9)) << std::endl;
std::cout << (a->remove(346)) << std::endl;
std::cout << (c->remove(495)) << std::endl;
*c=*d;
std::cout << (b->remove(188)) << std::endl;
std::cout << (d->insert(15)) << std::endl;
std::cout << (d->remove(15)) << std::endl;
std::cout << (c->remove(240)) << std::endl;
*c=*a;
*c=*e;
std::cout << (a->insert(195)) << std::endl;
std::cout << (c->remove(167)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
std::cout << (a->remove(150)) << std::endl;
std::cout << (e->remove(68)) << std::endl;
std::cout << (b->remove(243)) << std::endl;
std::cout << (c->insert(9)) << std::endl;
std::cout << (e->insert(9)) << std::endl;
std::cout << (a->remove(188)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (c->insert(9)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
std::cout << (d->insert(359)) << std::endl;
std::cout << (d->remove(359)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (b->insert(408)) << std::endl;
std::cout << (c->insert(273)) << std::endl;
*c=*d;
std::cout << (a->remove(470)) << std::endl;
std::cout << (b->insert(342)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
std::cout << (e->insert(479)) << std::endl;
c->printPretty();
std::cout << (a->remove(195)) << std::endl;
*a=*e;
*b=*d;
std::cout << (e->insert(230)) << std::endl;
b->printPretty();
std::cout << (a->insert(167)) << std::endl;
std::cout << (e->insert(436)) << std::endl;
std::cout << (e->remove(363)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
b->printPretty();
d->printPretty();
a->printPretty();
b->printPretty();
std::cout << (a->insert(431)) << std::endl;
*c=*a;
std::cout << (e->insert(479)) << std::endl;
*e=*e;
std::cout << (a->insert(167)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
std::cout << (b->remove(329)) << std::endl;
d->printPretty();
*e=*b;
std::cout << (e->insert(265)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
d->printPretty();
std::cout << (e->remove(265)) << std::endl;
e->printPretty();
std::cout << (a->remove(398)) << std::endl;
std::cout << (b->insert(42)) << std::endl;
std::cout << (c->remove(323)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
e->printPretty();
d->printPretty();
*c=*b;
*d=*d;
std::cout << (b->remove(42)) << std::endl;
std::cout << (b->insert(391)) << std::endl;
std::cout << (d->remove(235)) << std::endl;
std::cout << (e->remove(337)) << std::endl;
std::cout << (d->remove(291)) << std::endl;
e->printPretty();
std::cout << (d->insert(7)) << std::endl;
std::cout << (b->insert(391)) << std::endl;
std::cout << (b->remove(391)) << std::endl;
std::cout << (a->insert(438)) << std::endl;
e->printPretty();
std::cout << (b->remove(363)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
std::cout << (a->insert(438)) << std::endl;
*d=*e;
std::cout << (c->remove(16)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (d->insert(478)) << std::endl;
std::cout << (a->remove(230)) << std::endl;
std::cout << (d->insert(436)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
*d=*a;
std::cout << (a->insert(174)) << std::endl;
c->printPretty();
std::cout << (d->insert(438)) << std::endl;
*d=*e;
*d=*e;
e->printPretty();
std::cout << (a->remove(438)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
d->printPretty();
*a=*a;
std::cout << (b->remove(98)) << std::endl;
std::cout << (a->remove(431)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (b->insert(331)) << std::endl;
std::cout << (c->insert(42)) << std::endl;
e->printPretty();
std::cout << (b->insert(331)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
std::cout << (b->remove(225)) << std::endl;
std::cout << (a->remove(9)) << std::endl;
std::cout << (b->remove(204)) << std::endl;
b->printPretty();
std::cout << (e->insert(115)) << std::endl;
std::cout << (a->insert(167)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
*b=*a;
std::cout << (d->insert(293)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
std::cout << (a->insert(100)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (c->insert(83)) << std::endl;
std::cout << (e->remove(256)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (b->insert(109)) << std::endl;
std::cout << (d->remove(204)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
std::cout << (d->insert(33)) << std::endl;
e->printPretty();
std::cout << (a->remove(5)) << std::endl;
std::cout << (a->remove(174)) << std::endl;
b->printPretty();
std::cout << (c->insert(42)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
*e=*c;
std::cout << (a->remove(443)) << std::endl;
std::cout << (d->remove(414)) << std::endl;
c->printPretty();
std::cout << (a->remove(479)) << std::endl;
*c=*a;
std::cout << (a->insert(274)) << std::endl;
std::cout << (e->insert(174)) << std::endl;
std::cout << (e->remove(83)) << std::endl;
a->printPretty();
std::cout << (b->insert(115)) << std::endl;
std::cout << (c->insert(139)) << std::endl;
std::cout << (d->remove(33)) << std::endl;
*e=*b;
c->printPretty();
std::cout << (d->remove(292)) << std::endl;
*e=*d;
std::cout << (b->insert(174)) << std::endl;
c->printPretty();
c->printPretty();
std::cout << (b->insert(109)) << std::endl;
*e=*c;
std::cout << (c->insert(442)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (b->insert(479)) << std::endl;
std::cout << (c->insert(167)) << std::endl;
std::cout << (d->remove(110)) << std::endl;
std::cout << (a->remove(159)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
std::cout << (e->remove(100)) << std::endl;
std::cout << (c->insert(442)) << std::endl;
std::cout << (b->remove(374)) << std::endl;
e->printPretty();
std::cout << (d->remove(319)) << std::endl;
std::cout << (d->insert(340)) << std::endl;
std::cout << (b->remove(167)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
c->printPretty();
*d=*a;
std::cout << (b->insert(174)) << std::endl;
*c=*b;
e->printPretty();
std::cout << (a->insert(265)) << std::endl;
std::cout << (b->remove(479)) << std::endl;
std::cout << (c->remove(479)) << std::endl;
std::cout << (c->remove(109)) << std::endl;
d->printPretty();
std::cout << (a->insert(214)) << std::endl;
std::cout << (d->insert(274)) << std::endl;
std::cout << (e->insert(166)) << std::endl;
*e=*b;
d->printPretty();
std::cout << (b->insert(174)) << std::endl;
std::cout << (a->insert(101)) << std::endl;
std::cout << (a->insert(319)) << std::endl;
std::cout << (a->insert(274)) << std::endl;
b->printPretty();
std::cout << (a->insert(52)) << std::endl;
std::cout << (a->insert(201)) << std::endl;
a->printPretty();
std::cout << (d->remove(60)) << std::endl;
*a=*a;
b->printPretty();
std::cout << (c->remove(174)) << std::endl;
std::cout << (b->insert(37)) << std::endl;
std::cout << (c->remove(115)) << std::endl;
a->printPretty();
std::cout << (b->remove(71)) << std::endl;
std::cout << (e->remove(115)) << std::endl;
std::cout << (a->remove(202)) << std::endl;
*e=*e;
std::cout << (a->remove(445)) << std::endl;
std::cout << (b->insert(109)) << std::endl;
*d=*d;
std::cout << (d->insert(479)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
std::cout << (a->remove(52)) << std::endl;
std::cout << (a->insert(100)) << std::endl;
std::cout << (d->remove(479)) << std::endl;
std::cout << (d->insert(100)) << std::endl;
std::cout << (b->insert(174)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (e->insert(109)) << std::endl;
c->printPretty();
std::cout << (d->remove(100)) << std::endl;
std::cout << (b->remove(482)) << std::endl;
c->printPretty();
e->printPretty();
a->printPretty();
*b=*b;
std::cout << (c->remove(221)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
std::cout << (c->remove(202)) << std::endl;
std::cout << (d->insert(8)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
std::cout << (b->remove(37)) << std::endl;
std::cout << (c->remove(204)) << std::endl;
std::cout << (d->remove(424)) << std::endl;
std::cout << (d->insert(167)) << std::endl;
std::cout << (d->remove(8)) << std::endl;
std::cout << (d->insert(19)) << std::endl;
std::cout << (b->remove(157)) << std::endl;
std::cout << (c->remove(174)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
std::cout << (c->insert(1)) << std::endl;
*a=*b;
std::cout << (b->insert(115)) << std::endl;
std::cout << (c->insert(218)) << std::endl;
d->printPretty();
std::cout << (a->insert(207)) << std::endl;
a->printPretty();
*c=*b;
c->printPretty();
std::cout << (a->insert(148)) << std::endl;
*c=*a;
std::cout << (a->remove(285)) << std::endl;
std::cout << (a->insert(174)) << std::endl;
b->printPretty();
std::cout << (c->remove(323)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
std::cout << (a->remove(207)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->remove(19)) << std::endl;
std::cout << (c->remove(285)) << std::endl;
a->printPretty();
std::cout << (c->insert(174)) << std::endl;
std::cout << (c->remove(305)) << std::endl;
std::cout << (a->insert(6)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (a->remove(104)) << std::endl;
*b=*b;
std::cout << (a->insert(297)) << std::endl;
std::cout << (d->insert(214)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
a->printPretty();
b->printPretty();
std::cout << (d->insert(384)) << std::endl;
std::cout << (e->insert(408)) << std::endl;
d->printPretty();
std::cout << (d->insert(16)) << std::endl;
std::cout << (b->insert(285)) << std::endl;
std::cout << (d->insert(108)) << std::endl;
std::cout << (a->insert(458)) << std::endl;
std::cout << (a->insert(434)) << std::endl;
*b=*c;
std::cout << (c->insert(174)) << std::endl;
b->printPretty();
std::cout << (b->insert(35)) << std::endl;
d->printPretty();
*e=*e;
*b=*c;
std::cout << (a->insert(224)) << std::endl;
std::cout << (e->remove(302)) << std::endl;
std::cout << (b->remove(174)) << std::endl;
c->printPretty();
std::cout << (a->remove(301)) << std::endl;
d->printPretty();
std::cout << (b->insert(207)) << std::endl;
std::cout << (d->insert(247)) << std::endl;
std::cout << (a->remove(347)) << std::endl;
c->printPretty();
*e=*c;
std::cout << (b->insert(115)) << std::endl;
*c=*c;
std::cout << (a->remove(297)) << std::endl;
std::cout << (c->insert(174)) << std::endl;
std::cout << (d->remove(64)) << std::endl;
std::cout << (a->remove(451)) << std::endl;
std::cout << (d->insert(107)) << std::endl;
std::cout << (b->remove(410)) << std::endl;
std::cout << (c->insert(141)) << std::endl;
std::cout << (b->insert(69)) << std::endl;
*b=*c;
std::cout << (b->insert(207)) << std::endl;
std::cout << (b->insert(207)) << std::endl;
std::cout << (e->remove(115)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
std::cout << (d->insert(240)) << std::endl;
*e=*b;
std::cout << (d->remove(108)) << std::endl;
std::cout << (d->insert(240)) << std::endl;
std::cout << (d->insert(240)) << std::endl;
std::cout << (c->remove(174)) << std::endl;
std::cout << (e->remove(207)) << std::endl;
std::cout << (b->insert(53)) << std::endl;
*d=*a;
*d=*b;
d->printPretty();
std::cout << (b->remove(53)) << std::endl;
std::cout << (c->insert(115)) << std::endl;
std::cout << (c->insert(187)) << std::endl;
*c=*c;
std::cout << (a->remove(21)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
std::cout << (a->remove(157)) << std::endl;
std::cout << (a->remove(155)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (a->insert(345)) << std::endl;
std::cout << (c->insert(207)) << std::endl;
std::cout << (e->remove(369)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
std::cout << (a->remove(224)) << std::endl;
std::cout << (c->insert(45)) << std::endl;
std::cout << (c->remove(45)) << std::endl;
std::cout << (e->remove(141)) << std::endl;
std::cout << (b->remove(431)) << std::endl;
std::cout << (d->remove(174)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
*d=*e;
*e=*d;
std::cout << (b->insert(174)) << std::endl;
std::cout << (c->remove(53)) << std::endl;
std::cout << (a->remove(115)) << std::endl;
c->printPretty();
std::cout << (a->insert(434)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
std::cout << (a->remove(174)) << std::endl;
c->printPretty();
std::cout << (a->remove(179)) << std::endl;
std::cout << (a->remove(126)) << std::endl;
*d=*d;
std::cout << (c->insert(141)) << std::endl;
std::cout << (d->remove(405)) << std::endl;
std::cout << (a->insert(415)) << std::endl;
d->printPretty();
std::cout << (e->remove(438)) << std::endl;
std::cout << (b->remove(313)) << std::endl;
d->printPretty();
std::cout << (d->remove(319)) << std::endl;
std::cout << (b->insert(115)) << std::endl;
std::cout << (e->insert(115)) << std::endl;
std::cout << (b->insert(281)) << std::endl;
a->printPretty();
std::cout << (e->remove(154)) << std::endl;
std::cout << (d->remove(115)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
*a=*d;
return 0;
}
