#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*b=*b;
std::cout << (b->insert(97)) << std::endl;
std::cout << (b->remove(494)) << std::endl;
std::cout << (b->insert(97)) << std::endl;
b->printPretty();
ScapegoatTree<int> *c=new ScapegoatTree<int>(*a);
*a=*c;
std::cout << (a->insert(254)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (c->insert(97)) << std::endl;
std::cout << (a->remove(462)) << std::endl;
a->printPretty();
ScapegoatTree<int> *e=new ScapegoatTree<int>;
std::cout << (c->remove(327)) << std::endl;
std::cout << (c->remove(318)) << std::endl;
std::cout << (d->insert(460)) << std::endl;
std::cout << (e->insert(305)) << std::endl;
std::cout << (e->insert(249)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
*e=*a;
a->printPretty();
std::cout << (d->remove(460)) << std::endl;
b->printPretty();
std::cout << (a->remove(254)) << std::endl;
std::cout << (a->insert(329)) << std::endl;
*d=*c;
*a=*b;
std::cout << (b->remove(476)) << std::endl;
*e=*d;
std::cout << (e->insert(97)) << std::endl;
c->printPretty();
std::cout << (d->remove(352)) << std::endl;
c->printPretty();
std::cout << (a->insert(97)) << std::endl;
d->printPretty();
*c=*c;
std::cout << (d->remove(97)) << std::endl;
std::cout << (a->remove(404)) << std::endl;
std::cout << (a->insert(217)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (c->remove(76)) << std::endl;
std::cout << (d->remove(238)) << std::endl;
d->printPretty();
*c=*d;
*a=*b;
std::cout << (c->insert(348)) << std::endl;
c->printPretty();
std::cout << (a->remove(175)) << std::endl;
std::cout << (c->remove(348)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
std::cout << (a->remove(97)) << std::endl;
std::cout << (c->remove(190)) << std::endl;
*c=*b;
std::cout << (c->insert(177)) << std::endl;
std::cout << (e->insert(97)) << std::endl;
b->printPretty();
std::cout << (a->insert(22)) << std::endl;
*c=*a;
std::cout << (e->insert(97)) << std::endl;
*d=*c;
std::cout << (c->remove(163)) << std::endl;
*d=*e;
std::cout << (e->remove(97)) << std::endl;
std::cout << (c->insert(22)) << std::endl;
a->printPretty();
std::cout << (b->insert(451)) << std::endl;
std::cout << (c->insert(22)) << std::endl;
a->printPretty();
e->printPretty();
std::cout << (a->insert(400)) << std::endl;
std::cout << (b->insert(208)) << std::endl;
std::cout << (e->remove(174)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
*d=*e;
std::cout << (e->insert(292)) << std::endl;
*d=*d;
std::cout << (b->remove(451)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
*b=*c;
*b=*c;
*b=*a;
std::cout << (e->insert(282)) << std::endl;
std::cout << (e->remove(282)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
std::cout << (e->insert(332)) << std::endl;
std::cout << (c->insert(233)) << std::endl;
std::cout << (e->remove(324)) << std::endl;
*c=*d;
std::cout << (e->remove(406)) << std::endl;
std::cout << (a->remove(436)) << std::endl;
*e=*d;
std::cout << (c->remove(223)) << std::endl;
std::cout << (a->insert(400)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->insert(223)) << std::endl;
std::cout << (c->remove(178)) << std::endl;
c->printPretty();
e->printPretty();
*c=*d;
b->printPretty();
std::cout << (e->remove(378)) << std::endl;
std::cout << (e->remove(490)) << std::endl;
std::cout << (a->insert(128)) << std::endl;
std::cout << (b->insert(457)) << std::endl;
std::cout << (d->remove(223)) << std::endl;
*c=*b;
std::cout << (a->insert(64)) << std::endl;
std::cout << (d->insert(389)) << std::endl;
std::cout << (a->remove(128)) << std::endl;
std::cout << (d->insert(389)) << std::endl;
c->printPretty();
std::cout << (c->remove(79)) << std::endl;
std::cout << (e->insert(223)) << std::endl;
std::cout << (a->insert(19)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
*e=*d;
std::cout << (d->remove(389)) << std::endl;
a->printPretty();
e->printPretty();
d->printPretty();
d->printPretty();
std::cout << (c->insert(64)) << std::endl;
e->printPretty();
std::cout << (b->insert(457)) << std::endl;
std::cout << (a->insert(38)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
c->printPretty();
std::cout << (c->remove(400)) << std::endl;
d->printPretty();
std::cout << (c->remove(64)) << std::endl;
e->printPretty();
std::cout << (c->insert(143)) << std::endl;
std::cout << (a->remove(101)) << std::endl;
std::cout << (c->insert(143)) << std::endl;
std::cout << (e->insert(34)) << std::endl;
std::cout << (a->insert(387)) << std::endl;
std::cout << (e->remove(184)) << std::endl;
std::cout << (b->remove(128)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
std::cout << (e->insert(214)) << std::endl;
a->printPretty();
std::cout << (b->remove(163)) << std::endl;
std::cout << (b->remove(400)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
b->printPretty();
std::cout << (b->remove(65)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
d->printPretty();
std::cout << (e->insert(214)) << std::endl;
*d=*c;
std::cout << (d->remove(252)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
*b=*c;
std::cout << (b->remove(216)) << std::endl;
a->printPretty();
std::cout << (e->insert(214)) << std::endl;
c->printPretty();
std::cout << (d->remove(407)) << std::endl;
*d=*a;
std::cout << (a->remove(252)) << std::endl;
std::cout << (d->insert(64)) << std::endl;
std::cout << (d->insert(38)) << std::endl;
std::cout << (a->remove(372)) << std::endl;
std::cout << (a->remove(31)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
e->printPretty();
std::cout << (c->remove(322)) << std::endl;
std::cout << (b->insert(227)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->remove(127)) << std::endl;
std::cout << (c->insert(43)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (a->remove(94)) << std::endl;
e->printPretty();
std::cout << (b->remove(265)) << std::endl;
b->printPretty();
std::cout << (c->insert(357)) << std::endl;
std::cout << (c->insert(128)) << std::endl;
*d=*e;
*a=*d;
std::cout << (b->remove(322)) << std::endl;
a->printPretty();
d->printPretty();
c->printPretty();
d->printPretty();
*d=*c;
a->printPretty();
std::cout << (b->remove(22)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
c->printPretty();
std::cout << (a->remove(389)) << std::endl;
std::cout << (d->insert(30)) << std::endl;
d->printPretty();
std::cout << (c->remove(457)) << std::endl;
e->printPretty();
std::cout << (e->insert(389)) << std::endl;
std::cout << (a->remove(203)) << std::endl;
std::cout << (d->insert(457)) << std::endl;
*a=*c;
std::cout << (a->insert(421)) << std::endl;
*e=*b;
*a=*c;
std::cout << (e->insert(11)) << std::endl;
a->printPretty();
std::cout << (c->remove(437)) << std::endl;
*a=*a;
std::cout << (b->remove(469)) << std::endl;
std::cout << (e->insert(11)) << std::endl;
c->printPretty();
std::cout << (a->insert(460)) << std::endl;
std::cout << (d->insert(357)) << std::endl;
std::cout << (a->remove(357)) << std::endl;
*b=*a;
std::cout << (d->remove(302)) << std::endl;
std::cout << (b->insert(390)) << std::endl;
std::cout << (b->remove(252)) << std::endl;
*d=*a;
std::cout << (d->insert(91)) << std::endl;
c->printPretty();
std::cout << (e->remove(11)) << std::endl;
std::cout << (e->remove(357)) << std::endl;
std::cout << (d->remove(143)) << std::endl;
std::cout << (b->insert(128)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
*e=*c;
std::cout << (b->insert(22)) << std::endl;
std::cout << (b->insert(460)) << std::endl;
std::cout << (a->insert(267)) << std::endl;
a->printPretty();
std::cout << (e->insert(128)) << std::endl;
*a=*c;
std::cout << (d->insert(128)) << std::endl;
*a=*e;
a->printPretty();
*c=*e;
c->printPretty();
std::cout << (c->remove(143)) << std::endl;
std::cout << (d->remove(88)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
std::cout << (d->remove(22)) << std::endl;
std::cout << (c->remove(247)) << std::endl;
std::cout << (d->remove(128)) << std::endl;
std::cout << (d->insert(224)) << std::endl;
d->printPretty();
std::cout << (d->insert(196)) << std::endl;
std::cout << (d->remove(43)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
*e=*c;
*b=*d;
std::cout << (e->remove(176)) << std::endl;
std::cout << (c->insert(357)) << std::endl;
std::cout << (a->insert(143)) << std::endl;
*a=*c;
std::cout << (c->insert(350)) << std::endl;
std::cout << (d->insert(407)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
std::cout << (e->remove(117)) << std::endl;
*e=*d;
std::cout << (a->remove(407)) << std::endl;
std::cout << (c->remove(22)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
std::cout << (d->remove(317)) << std::endl;
std::cout << (e->insert(91)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (d->insert(407)) << std::endl;
*a=*e;
std::cout << (c->insert(399)) << std::endl;
std::cout << (b->remove(374)) << std::endl;
a->printPretty();
a->printPretty();
b->printPretty();
std::cout << (a->insert(3)) << std::endl;
std::cout << (c->remove(500)) << std::endl;
a->printPretty();
*b=*e;
d->printPretty();
std::cout << (d->insert(196)) << std::endl;
std::cout << (a->remove(3)) << std::endl;
std::cout << (d->remove(224)) << std::endl;
std::cout << (d->insert(16)) << std::endl;
d->printPretty();
*b=*e;
std::cout << (c->insert(128)) << std::endl;
std::cout << (c->insert(43)) << std::endl;
*a=*c;
std::cout << (e->remove(13)) << std::endl;
std::cout << (e->insert(77)) << std::endl;
std::cout << (c->remove(357)) << std::endl;
std::cout << (d->remove(353)) << std::endl;
std::cout << (c->remove(350)) << std::endl;
std::cout << (a->remove(295)) << std::endl;
e->printPretty();
*a=*a;
*a=*e;
std::cout << (a->insert(156)) << std::endl;
c->printPretty();
std::cout << (c->remove(399)) << std::endl;
std::cout << (e->remove(77)) << std::endl;
std::cout << (b->remove(13)) << std::endl;
std::cout << (c->insert(30)) << std::endl;
*a=*e;
std::cout << (b->insert(460)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (e->remove(463)) << std::endl;
*a=*a;
*d=*b;
std::cout << (d->insert(58)) << std::endl;
e->printPretty();
std::cout << (a->remove(91)) << std::endl;
d->printPretty();
d->printPretty();
e->printPretty();
std::cout << (c->insert(471)) << std::endl;
*c=*a;
std::cout << (c->remove(196)) << std::endl;
*d=*b;
a->printPretty();
std::cout << (a->insert(221)) << std::endl;
std::cout << (d->remove(14)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
std::cout << (a->insert(196)) << std::endl;
std::cout << (c->insert(460)) << std::endl;
std::cout << (b->remove(224)) << std::endl;
std::cout << (a->remove(407)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
std::cout << (e->remove(108)) << std::endl;
std::cout << (c->remove(366)) << std::endl;
std::cout << (a->remove(284)) << std::endl;
std::cout << (a->insert(77)) << std::endl;
*e=*d;
*c=*a;
std::cout << (c->remove(408)) << std::endl;
std::cout << (e->insert(196)) << std::endl;
std::cout << (a->insert(317)) << std::endl;
std::cout << (c->insert(113)) << std::endl;
std::cout << (d->insert(59)) << std::endl;
*d=*d;
std::cout << (c->insert(7)) << std::endl;
c->printPretty();
std::cout << (c->remove(258)) << std::endl;
c->printPretty();
std::cout << (e->remove(224)) << std::endl;
b->printPretty();
std::cout << (b->remove(77)) << std::endl;
std::cout << (d->insert(217)) << std::endl;
*c=*a;
std::cout << (a->insert(196)) << std::endl;
c->printPretty();
d->printPretty();
a->printPretty();
std::cout << (d->insert(460)) << std::endl;
b->printPretty();
*a=*e;
std::cout << (e->insert(407)) << std::endl;
std::cout << (e->insert(418)) << std::endl;
std::cout << (c->remove(460)) << std::endl;
std::cout << (c->remove(162)) << std::endl;
*d=*b;
std::cout << (b->insert(431)) << std::endl;
c->printPretty();
std::cout << (b->remove(47)) << std::endl;
*d=*e;
std::cout << (e->insert(407)) << std::endl;
std::cout << (b->insert(343)) << std::endl;
a->printPretty();
std::cout << (b->insert(495)) << std::endl;
*e=*e;
c->printPretty();
std::cout << (d->insert(460)) << std::endl;
std::cout << (b->remove(460)) << std::endl;
std::cout << (b->remove(343)) << std::endl;
std::cout << (c->insert(161)) << std::endl;
std::cout << (b->remove(367)) << std::endl;
e->printPretty();
std::cout << (d->remove(418)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
std::cout << (c->remove(161)) << std::endl;
*c=*a;
std::cout << (c->remove(41)) << std::endl;
std::cout << (b->remove(262)) << std::endl;
std::cout << (b->remove(9)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
std::cout << (b->insert(495)) << std::endl;
std::cout << (c->insert(196)) << std::endl;
std::cout << (c->remove(407)) << std::endl;
std::cout << (c->insert(271)) << std::endl;
*c=*d;
std::cout << (e->remove(91)) << std::endl;
std::cout << (c->remove(238)) << std::endl;
std::cout << (b->remove(129)) << std::endl;
std::cout << (d->remove(496)) << std::endl;
std::cout << (c->insert(460)) << std::endl;
*c=*a;
*c=*d;
std::cout << (a->remove(478)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (e->remove(73)) << std::endl;
std::cout << (b->insert(429)) << std::endl;
b->printPretty();
std::cout << (d->insert(196)) << std::endl;
*e=*c;
std::cout << (b->insert(431)) << std::endl;
b->printPretty();
std::cout << (a->remove(196)) << std::endl;
std::cout << (d->remove(460)) << std::endl;
*b=*a;
std::cout << (d->remove(57)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
*a=*a;
std::cout << (a->insert(277)) << std::endl;
std::cout << (b->remove(91)) << std::endl;
std::cout << (e->remove(361)) << std::endl;
b->printPretty();
std::cout << (b->remove(396)) << std::endl;
*c=*c;
std::cout << (b->remove(150)) << std::endl;
*c=*d;
std::cout << (a->insert(26)) << std::endl;
c->printPretty();
e->printPretty();
std::cout << (c->remove(407)) << std::endl;
e->printPretty();
std::cout << (e->remove(460)) << std::endl;
*b=*a;
std::cout << (a->insert(26)) << std::endl;
std::cout << (e->insert(202)) << std::endl;
std::cout << (b->insert(26)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
*e=*e;
std::cout << (a->insert(463)) << std::endl;
std::cout << (e->remove(407)) << std::endl;
*d=*a;
std::cout << (a->remove(83)) << std::endl;
std::cout << (c->remove(196)) << std::endl;
std::cout << (d->insert(386)) << std::endl;
e->printPretty();
*a=*c;
std::cout << (a->remove(302)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (e->remove(202)) << std::endl;
std::cout << (b->insert(407)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
e->printPretty();
std::cout << (d->remove(374)) << std::endl;
std::cout << (d->insert(178)) << std::endl;
std::cout << (c->insert(41)) << std::endl;
std::cout << (e->insert(91)) << std::endl;
std::cout << (c->remove(347)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
d->printPretty();
std::cout << (e->insert(43)) << std::endl;
a->printPretty();
std::cout << (d->remove(429)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (c->remove(41)) << std::endl;
std::cout << (a->insert(24)) << std::endl;
a->printPretty();
std::cout << (e->remove(469)) << std::endl;
std::cout << (b->remove(277)) << std::endl;
std::cout << (c->remove(92)) << std::endl;
std::cout << (e->insert(196)) << std::endl;
std::cout << (c->remove(91)) << std::endl;
std::cout << (d->remove(294)) << std::endl;
std::cout << (a->remove(24)) << std::endl;
std::cout << (a->insert(470)) << std::endl;
std::cout << (e->insert(43)) << std::endl;
c->printPretty();
std::cout << (e->remove(196)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
std::cout << (a->insert(495)) << std::endl;
*d=*e;
std::cout << (b->insert(407)) << std::endl;
*a=*c;
std::cout << (d->insert(390)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
std::cout << (d->remove(390)) << std::endl;
std::cout << (b->remove(407)) << std::endl;
std::cout << (c->remove(405)) << std::endl;
*d=*c;
std::cout << (b->insert(91)) << std::endl;
std::cout << (b->insert(460)) << std::endl;
std::cout << (d->remove(153)) << std::endl;
*b=*b;
std::cout << (e->insert(91)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
e->printPretty();
*b=*c;
std::cout << (c->insert(141)) << std::endl;
std::cout << (c->remove(51)) << std::endl;
a->printPretty();
std::cout << (d->remove(223)) << std::endl;
*e=*c;
std::cout << (a->insert(349)) << std::endl;
std::cout << (c->remove(153)) << std::endl;
std::cout << (c->remove(141)) << std::endl;
e->printPretty();
*a=*e;
std::cout << (a->remove(141)) << std::endl;
*e=*e;
std::cout << (e->insert(173)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (d->insert(348)) << std::endl;
c->printPretty();
std::cout << (d->remove(348)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (c->insert(332)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
std::cout << (e->insert(464)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
*e=*e;
std::cout << (c->remove(332)) << std::endl;
std::cout << (d->remove(142)) << std::endl;
std::cout << (e->remove(464)) << std::endl;
std::cout << (a->remove(470)) << std::endl;
std::cout << (e->insert(483)) << std::endl;
std::cout << (b->insert(463)) << std::endl;
std::cout << (a->remove(326)) << std::endl;
*d=*c;
std::cout << (d->remove(278)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
std::cout << (c->remove(170)) << std::endl;
std::cout << (c->remove(30)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
*e=*c;
std::cout << (a->remove(230)) << std::endl;
e->printPretty();
std::cout << (c->insert(30)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
*d=*b;
std::cout << (d->insert(463)) << std::endl;
std::cout << (a->insert(85)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (c->remove(435)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
*e=*d;
std::cout << (d->remove(153)) << std::endl;
std::cout << (b->remove(140)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
std::cout << (d->insert(463)) << std::endl;
*d=*c;
std::cout << (a->insert(460)) << std::endl;
std::cout << (a->remove(85)) << std::endl;
*c=*b;
std::cout << (c->remove(463)) << std::endl;
*b=*e;
std::cout << (b->remove(323)) << std::endl;
a->printPretty();
*a=*a;
std::cout << (a->remove(460)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
std::cout << (c->remove(153)) << std::endl;
std::cout << (b->remove(392)) << std::endl;
b->printPretty();
std::cout << (d->remove(284)) << std::endl;
std::cout << (e->remove(260)) << std::endl;
std::cout << (a->insert(153)) << std::endl;
d->printPretty();
*d=*c;
b->printPretty();
*d=*b;
*b=*a;
std::cout << (b->remove(153)) << std::endl;
std::cout << (d->remove(387)) << std::endl;
std::cout << (e->remove(331)) << std::endl;
std::cout << (b->insert(223)) << std::endl;
std::cout << (d->remove(45)) << std::endl;
std::cout << (b->insert(335)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (d->insert(463)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
std::cout << (e->insert(153)) << std::endl;
*d=*d;
std::cout << (b->insert(335)) << std::endl;
std::cout << (a->remove(49)) << std::endl;
std::cout << (b->insert(380)) << std::endl;
std::cout << (e->insert(463)) << std::endl;
*c=*e;
e->printPretty();
std::cout << (c->insert(8)) << std::endl;
std::cout << (d->insert(153)) << std::endl;
std::cout << (e->remove(320)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (e->insert(29)) << std::endl;
std::cout << (b->remove(335)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
std::cout << (e->remove(153)) << std::endl;
std::cout << (e->remove(435)) << std::endl;
a->printPretty();
std::cout << (a->insert(91)) << std::endl;
*a=*d;
std::cout << (d->remove(153)) << std::endl;
std::cout << (a->remove(380)) << std::endl;
c->printPretty();
std::cout << (d->insert(463)) << std::endl;
*d=*e;
std::cout << (b->remove(380)) << std::endl;
std::cout << (d->insert(323)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
*e=*e;
std::cout << (a->remove(170)) << std::endl;
*d=*c;
std::cout << (e->remove(386)) << std::endl;
std::cout << (e->remove(148)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (a->remove(417)) << std::endl;
std::cout << (a->remove(463)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
std::cout << (a->remove(325)) << std::endl;
std::cout << (a->remove(153)) << std::endl;
std::cout << (c->insert(338)) << std::endl;
*a=*a;
e->printPretty();
std::cout << (d->insert(396)) << std::endl;
std::cout << (a->insert(208)) << std::endl;
std::cout << (b->insert(101)) << std::endl;
b->printPretty();
*d=*b;
*c=*e;
a->printPretty();
std::cout << (d->insert(283)) << std::endl;
std::cout << (a->remove(40)) << std::endl;
std::cout << (e->insert(96)) << std::endl;
std::cout << (b->remove(101)) << std::endl;
std::cout << (a->remove(205)) << std::endl;
std::cout << (b->remove(223)) << std::endl;
std::cout << (e->insert(29)) << std::endl;
std::cout << (c->remove(314)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (a->insert(205)) << std::endl;
std::cout << (d->remove(487)) << std::endl;
std::cout << (e->remove(461)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
std::cout << (d->insert(101)) << std::endl;
std::cout << (e->remove(434)) << std::endl;
b->printPretty();
std::cout << (c->remove(339)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (e->insert(294)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (a->insert(493)) << std::endl;
std::cout << (a->insert(175)) << std::endl;
std::cout << (e->insert(234)) << std::endl;
std::cout << (b->remove(98)) << std::endl;
*a=*d;
std::cout << (a->remove(101)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (b->insert(4)) << std::endl;
std::cout << (a->insert(283)) << std::endl;
std::cout << (b->remove(472)) << std::endl;
*e=*b;
std::cout << (d->remove(101)) << std::endl;
*d=*a;
*e=*b;
*e=*e;
std::cout << (c->remove(29)) << std::endl;
d->printPretty();
a->printPretty();
std::cout << (b->remove(4)) << std::endl;
std::cout << (a->insert(283)) << std::endl;
std::cout << (a->insert(223)) << std::endl;
*a=*b;
a->printPretty();
std::cout << (c->insert(96)) << std::endl;
std::cout << (d->remove(32)) << std::endl;
std::cout << (d->remove(291)) << std::endl;
std::cout << (c->remove(96)) << std::endl;
std::cout << (a->insert(62)) << std::endl;
std::cout << (d->remove(13)) << std::endl;
d->printPretty();
std::cout << (d->remove(223)) << std::endl;
std::cout << (c->insert(463)) << std::endl;
std::cout << (c->remove(267)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
a->printPretty();
std::cout << (d->remove(420)) << std::endl;
b->printPretty();
a->printPretty();
std::cout << (a->insert(62)) << std::endl;
*b=*d;
*e=*d;
std::cout << (e->remove(212)) << std::endl;
std::cout << (e->remove(283)) << std::endl;
std::cout << (d->remove(283)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
std::cout << (e->remove(271)) << std::endl;
std::cout << (d->remove(37)) << std::endl;
std::cout << (e->remove(389)) << std::endl;
d->printPretty();
std::cout << (e->remove(122)) << std::endl;
b->printPretty();
std::cout << (a->insert(137)) << std::endl;
std::cout << (e->insert(252)) << std::endl;
a->printPretty();
d->printPretty();
a->printPretty();
std::cout << (e->insert(50)) << std::endl;
std::cout << (a->remove(47)) << std::endl;
a->printPretty();
a->printPretty();
c->printPretty();
*d=*d;
b->printPretty();
return 0;
}
