#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*b;
std::cout << (b->insert(322)) << std::endl;
std::cout << (b->remove(212)) << std::endl;
std::cout << (b->insert(32)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
*a=*c;
ScapegoatTree<int> *d=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *e=new ScapegoatTree<int>;
b->printPretty();
*b=*d;
std::cout << (b->insert(177)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
a->printPretty();
std::cout << (b->insert(257)) << std::endl;
*b=*d;
d->printPretty();
*e=*d;
std::cout << (c->insert(320)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
d->printPretty();
std::cout << (a->insert(94)) << std::endl;
*c=*b;
*a=*e;
*b=*d;
*e=*d;
std::cout << (e->remove(322)) << std::endl;
std::cout << (c->insert(112)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
d->printPretty();
std::cout << (c->remove(464)) << std::endl;
*b=*d;
std::cout << (e->remove(84)) << std::endl;
std::cout << (c->insert(233)) << std::endl;
*a=*b;
std::cout << (a->remove(32)) << std::endl;
c->printPretty();
std::cout << (e->insert(296)) << std::endl;
std::cout << (e->insert(32)) << std::endl;
std::cout << (b->insert(329)) << std::endl;
*e=*b;
e->printPretty();
*b=*b;
std::cout << (a->remove(322)) << std::endl;
*b=*d;
std::cout << (c->insert(157)) << std::endl;
std::cout << (c->insert(157)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->insert(322)) << std::endl;
*b=*e;
std::cout << (b->insert(116)) << std::endl;
std::cout << (d->insert(47)) << std::endl;
std::cout << (e->remove(243)) << std::endl;
*a=*a;
std::cout << (e->remove(322)) << std::endl;
std::cout << (d->remove(32)) << std::endl;
c->printPretty();
std::cout << (c->insert(157)) << std::endl;
e->printPretty();
std::cout << (b->insert(245)) << std::endl;
std::cout << (b->insert(259)) << std::endl;
*e=*e;
*c=*d;
std::cout << (d->insert(47)) << std::endl;
*b=*b;
std::cout << (b->insert(293)) << std::endl;
*e=*b;
std::cout << (c->remove(19)) << std::endl;
*d=*b;
std::cout << (c->remove(47)) << std::endl;
*c=*d;
*e=*c;
std::cout << (c->remove(49)) << std::endl;
a->printPretty();
std::cout << (e->remove(32)) << std::endl;
std::cout << (c->insert(173)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
a->printPretty();
std::cout << (d->remove(116)) << std::endl;
std::cout << (d->insert(322)) << std::endl;
std::cout << (d->insert(297)) << std::endl;
*b=*b;
*a=*b;
std::cout << (b->remove(245)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
std::cout << (c->remove(134)) << std::endl;
std::cout << (c->remove(29)) << std::endl;
e->printPretty();
std::cout << (c->remove(395)) << std::endl;
*e=*d;
std::cout << (d->insert(2)) << std::endl;
std::cout << (a->insert(167)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (d->remove(219)) << std::endl;
std::cout << (c->insert(173)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (a->remove(329)) << std::endl;
*e=*c;
std::cout << (a->insert(32)) << std::endl;
std::cout << (e->remove(263)) << std::endl;
std::cout << (b->remove(259)) << std::endl;
*e=*d;
std::cout << (c->remove(181)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
std::cout << (b->remove(116)) << std::endl;
std::cout << (d->remove(54)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
d->printPretty();
std::cout << (e->remove(259)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
std::cout << (d->insert(242)) << std::endl;
std::cout << (b->remove(14)) << std::endl;
*b=*d;
a->printPretty();
*b=*c;
std::cout << (d->insert(245)) << std::endl;
std::cout << (b->insert(293)) << std::endl;
b->printPretty();
*b=*e;
std::cout << (c->remove(263)) << std::endl;
std::cout << (e->remove(145)) << std::endl;
std::cout << (d->insert(76)) << std::endl;
std::cout << (a->remove(32)) << std::endl;
a->printPretty();
std::cout << (e->remove(329)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
std::cout << (b->insert(162)) << std::endl;
*d=*b;
std::cout << (a->insert(309)) << std::endl;
std::cout << (e->remove(199)) << std::endl;
std::cout << (a->remove(167)) << std::endl;
std::cout << (d->insert(32)) << std::endl;
std::cout << (b->insert(309)) << std::endl;
*d=*d;
std::cout << (b->remove(162)) << std::endl;
std::cout << (e->remove(297)) << std::endl;
std::cout << (c->remove(165)) << std::endl;
std::cout << (b->insert(103)) << std::endl;
e->printPretty();
std::cout << (a->insert(309)) << std::endl;
*e=*e;
*c=*a;
*e=*d;
std::cout << (a->remove(293)) << std::endl;
c->printPretty();
std::cout << (a->remove(196)) << std::endl;
std::cout << (a->remove(116)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
std::cout << (d->remove(297)) << std::endl;
std::cout << (d->insert(388)) << std::endl;
b->printPretty();
std::cout << (d->remove(162)) << std::endl;
std::cout << (a->insert(375)) << std::endl;
std::cout << (c->insert(106)) << std::endl;
d->printPretty();
std::cout << (d->remove(245)) << std::endl;
*b=*b;
std::cout << (d->insert(322)) << std::endl;
*e=*b;
std::cout << (e->remove(2)) << std::endl;
*d=*d;
std::cout << (e->insert(188)) << std::endl;
std::cout << (a->remove(228)) << std::endl;
b->printPretty();
std::cout << (b->remove(440)) << std::endl;
std::cout << (e->remove(32)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
*c=*c;
std::cout << (a->insert(309)) << std::endl;
std::cout << (d->remove(343)) << std::endl;
std::cout << (c->remove(144)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
std::cout << (a->insert(322)) << std::endl;
*e=*d;
*a=*b;
b->printPretty();
e->printPretty();
std::cout << (b->remove(21)) << std::endl;
std::cout << (e->insert(364)) << std::endl;
*b=*a;
std::cout << (c->remove(309)) << std::endl;
std::cout << (d->remove(406)) << std::endl;
*d=*a;
std::cout << (d->insert(188)) << std::endl;
std::cout << (d->remove(103)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->insert(297)) << std::endl;
std::cout << (e->remove(214)) << std::endl;
std::cout << (b->insert(329)) << std::endl;
std::cout << (d->insert(374)) << std::endl;
std::cout << (b->remove(317)) << std::endl;
std::cout << (a->remove(395)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (b->insert(322)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (c->insert(102)) << std::endl;
b->printPretty();
std::cout << (a->insert(418)) << std::endl;
std::cout << (d->remove(358)) << std::endl;
std::cout << (b->insert(462)) << std::endl;
std::cout << (d->insert(88)) << std::endl;
*e=*c;
std::cout << (c->remove(293)) << std::endl;
std::cout << (d->remove(1)) << std::endl;
std::cout << (e->remove(102)) << std::endl;
std::cout << (b->insert(172)) << std::endl;
*e=*e;
std::cout << (c->remove(255)) << std::endl;
std::cout << (a->remove(172)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
std::cout << (d->insert(313)) << std::endl;
std::cout << (d->remove(329)) << std::endl;
*b=*e;
*d=*e;
*a=*b;
*d=*a;
std::cout << (d->insert(245)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (b->remove(216)) << std::endl;
std::cout << (d->insert(245)) << std::endl;
std::cout << (e->remove(106)) << std::endl;
std::cout << (b->insert(116)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
std::cout << (b->insert(372)) << std::endl;
std::cout << (c->insert(183)) << std::endl;
std::cout << (e->insert(259)) << std::endl;
std::cout << (d->insert(320)) << std::endl;
c->printPretty();
std::cout << (d->remove(364)) << std::endl;
*d=*e;
e->printPretty();
*e=*d;
std::cout << (e->insert(259)) << std::endl;
std::cout << (e->remove(487)) << std::endl;
std::cout << (a->insert(305)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (d->remove(322)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (a->insert(305)) << std::endl;
std::cout << (a->remove(259)) << std::endl;
*a=*e;
std::cout << (c->insert(428)) << std::endl;
*c=*d;
a->printPretty();
std::cout << (a->insert(322)) << std::endl;
std::cout << (e->remove(365)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
*e=*e;
std::cout << (b->insert(293)) << std::endl;
std::cout << (c->remove(245)) << std::endl;
std::cout << (a->remove(293)) << std::endl;
*a=*b;
std::cout << (d->remove(9)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
std::cout << (b->remove(259)) << std::endl;
std::cout << (a->insert(19)) << std::endl;
*e=*e;
a->printPretty();
std::cout << (b->insert(324)) << std::endl;
std::cout << (b->remove(368)) << std::endl;
std::cout << (d->insert(245)) << std::endl;
a->printPretty();
std::cout << (c->remove(339)) << std::endl;
std::cout << (c->remove(213)) << std::endl;
std::cout << (c->insert(314)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (d->insert(116)) << std::endl;
std::cout << (a->remove(245)) << std::endl;
*b=*e;
std::cout << (b->insert(258)) << std::endl;
*c=*c;
*b=*a;
d->printPretty();
*d=*b;
std::cout << (c->insert(116)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
*b=*c;
std::cout << (d->remove(259)) << std::endl;
std::cout << (a->insert(116)) << std::endl;
std::cout << (a->remove(462)) << std::endl;
c->printPretty();
*b=*c;
std::cout << (e->insert(112)) << std::endl;
std::cout << (a->insert(132)) << std::endl;
std::cout << (c->remove(91)) << std::endl;
*b=*d;
std::cout << (d->remove(458)) << std::endl;
*a=*c;
std::cout << (c->remove(175)) << std::endl;
*d=*e;
std::cout << (e->insert(259)) << std::endl;
std::cout << (c->remove(293)) << std::endl;
std::cout << (b->remove(322)) << std::endl;
*c=*d;
std::cout << (d->insert(490)) << std::endl;
a->printPretty();
b->printPretty();
a->printPretty();
c->printPretty();
std::cout << (c->insert(298)) << std::endl;
*e=*c;
std::cout << (a->insert(259)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
std::cout << (c->insert(245)) << std::endl;
std::cout << (c->insert(42)) << std::endl;
*d=*c;
std::cout << (d->remove(193)) << std::endl;
std::cout << (a->insert(314)) << std::endl;
std::cout << (c->remove(112)) << std::endl;
*c=*e;
std::cout << (b->remove(19)) << std::endl;
*d=*b;
*b=*e;
std::cout << (d->insert(372)) << std::endl;
d->printPretty();
std::cout << (b->insert(61)) << std::endl;
*d=*b;
std::cout << (c->remove(112)) << std::endl;
*e=*c;
std::cout << (b->insert(153)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (c->remove(61)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (c->remove(36)) << std::endl;
std::cout << (d->remove(187)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (d->insert(259)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (e->insert(256)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
*c=*b;
std::cout << (a->remove(461)) << std::endl;
d->printPretty();
std::cout << (b->insert(118)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
e->printPretty();
std::cout << (d->insert(61)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
d->printPretty();
std::cout << (c->insert(153)) << std::endl;
*a=*c;
std::cout << (d->remove(61)) << std::endl;
std::cout << (b->remove(424)) << std::endl;
*b=*e;
std::cout << (c->insert(298)) << std::endl;
std::cout << (a->remove(238)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
*e=*c;
*e=*e;
std::cout << (a->insert(36)) << std::endl;
std::cout << (d->remove(280)) << std::endl;
std::cout << (b->remove(259)) << std::endl;
std::cout << (c->insert(341)) << std::endl;
std::cout << (e->insert(149)) << std::endl;
std::cout << (a->insert(41)) << std::endl;
*d=*c;
std::cout << (a->remove(41)) << std::endl;
std::cout << (e->remove(13)) << std::endl;
*b=*b;
b->printPretty();
std::cout << (b->remove(293)) << std::endl;
a->printPretty();
std::cout << (b->remove(256)) << std::endl;
std::cout << (a->remove(332)) << std::endl;
std::cout << (b->insert(143)) << std::endl;
*c=*c;
std::cout << (b->insert(143)) << std::endl;
e->printPretty();
b->printPretty();
a->printPretty();
std::cout << (e->insert(259)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
c->printPretty();
std::cout << (c->insert(387)) << std::endl;
std::cout << (d->insert(130)) << std::endl;
std::cout << (e->remove(293)) << std::endl;
std::cout << (d->remove(116)) << std::endl;
*e=*b;
std::cout << (e->insert(498)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
std::cout << (b->remove(303)) << std::endl;
*c=*d;
std::cout << (d->insert(498)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (e->insert(91)) << std::endl;
std::cout << (d->remove(123)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (d->insert(298)) << std::endl;
std::cout << (d->remove(342)) << std::endl;
std::cout << (b->insert(245)) << std::endl;
std::cout << (b->insert(370)) << std::endl;
std::cout << (c->remove(298)) << std::endl;
std::cout << (a->remove(116)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (d->insert(182)) << std::endl;
*b=*c;
std::cout << (a->remove(171)) << std::endl;
b->printPretty();
*c=*b;
*b=*a;
std::cout << (a->remove(482)) << std::endl;
*e=*d;
std::cout << (b->remove(141)) << std::endl;
std::cout << (d->remove(348)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (d->insert(61)) << std::endl;
d->printPretty();
std::cout << (a->remove(36)) << std::endl;
std::cout << (a->insert(293)) << std::endl;
e->printPretty();
std::cout << (e->insert(112)) << std::endl;
*d=*d;
std::cout << (e->insert(265)) << std::endl;
std::cout << (d->insert(298)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (d->insert(92)) << std::endl;
*a=*d;
*e=*c;
std::cout << (e->insert(352)) << std::endl;
std::cout << (c->remove(136)) << std::endl;
std::cout << (b->remove(391)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (c->remove(153)) << std::endl;
std::cout << (a->remove(34)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (d->remove(159)) << std::endl;
e->printPretty();
std::cout << (a->insert(92)) << std::endl;
std::cout << (c->insert(27)) << std::endl;
std::cout << (c->insert(137)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
std::cout << (e->insert(85)) << std::endl;
e->printPretty();
std::cout << (e->insert(69)) << std::endl;
*e=*c;
std::cout << (c->remove(341)) << std::endl;
std::cout << (e->insert(61)) << std::endl;
*d=*a;
std::cout << (b->remove(245)) << std::endl;
std::cout << (a->insert(452)) << std::endl;
c->printPretty();
*b=*a;
std::cout << (c->remove(206)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (e->remove(27)) << std::endl;
std::cout << (e->insert(293)) << std::endl;
std::cout << (b->insert(106)) << std::endl;
std::cout << (d->remove(437)) << std::endl;
b->printPretty();
*b=*e;
std::cout << (e->remove(341)) << std::endl;
std::cout << (e->remove(61)) << std::endl;
std::cout << (e->remove(137)) << std::endl;
std::cout << (b->insert(177)) << std::endl;
a->printPretty();
std::cout << (e->remove(293)) << std::endl;
c->printPretty();
std::cout << (d->remove(298)) << std::endl;
e->printPretty();
std::cout << (b->insert(130)) << std::endl;
*a=*e;
std::cout << (e->remove(408)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (c->remove(36)) << std::endl;
a->printPretty();
std::cout << (e->remove(211)) << std::endl;
d->printPretty();
*e=*c;
std::cout << (d->remove(130)) << std::endl;
d->printPretty();
std::cout << (e->remove(309)) << std::endl;
std::cout << (d->insert(341)) << std::endl;
std::cout << (e->remove(230)) << std::endl;
*b=*b;
std::cout << (a->remove(376)) << std::endl;
*e=*d;
std::cout << (b->remove(137)) << std::endl;
std::cout << (e->remove(112)) << std::endl;
std::cout << (a->remove(244)) << std::endl;
std::cout << (c->remove(99)) << std::endl;
std::cout << (d->insert(341)) << std::endl;
a->printPretty();
std::cout << (c->remove(322)) << std::endl;
std::cout << (a->remove(352)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
b->printPretty();
std::cout << (d->remove(91)) << std::endl;
std::cout << (c->remove(259)) << std::endl;
*d=*e;
*b=*d;
std::cout << (e->remove(36)) << std::endl;
std::cout << (a->remove(112)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
*e=*d;
std::cout << (a->insert(379)) << std::endl;
std::cout << (b->insert(425)) << std::endl;
std::cout << (e->remove(259)) << std::endl;
*c=*e;
std::cout << (e->insert(175)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (b->insert(296)) << std::endl;
std::cout << (b->insert(29)) << std::endl;
std::cout << (e->insert(293)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (c->insert(61)) << std::endl;
b->printPretty();
std::cout << (d->remove(274)) << std::endl;
std::cout << (b->insert(341)) << std::endl;
std::cout << (e->remove(341)) << std::endl;
std::cout << (c->insert(92)) << std::endl;
std::cout << (c->remove(485)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
b->printPretty();
a->printPretty();
a->printPretty();
std::cout << (c->insert(411)) << std::endl;
std::cout << (a->insert(36)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (e->remove(91)) << std::endl;
std::cout << (e->insert(352)) << std::endl;
*c=*e;
*e=*a;
std::cout << (b->insert(261)) << std::endl;
a->printPretty();
*b=*d;
e->printPretty();
std::cout << (c->remove(419)) << std::endl;
std::cout << (a->insert(498)) << std::endl;
std::cout << (d->insert(293)) << std::endl;
std::cout << (e->remove(498)) << std::endl;
std::cout << (d->insert(36)) << std::endl;
std::cout << (b->remove(442)) << std::endl;
std::cout << (e->insert(36)) << std::endl;
std::cout << (d->insert(148)) << std::endl;
std::cout << (e->remove(167)) << std::endl;
e->printPretty();
*c=*d;
std::cout << (d->remove(36)) << std::endl;
*e=*a;
std::cout << (c->remove(108)) << std::endl;
a->printPretty();
std::cout << (d->insert(92)) << std::endl;
std::cout << (b->remove(427)) << std::endl;
std::cout << (c->remove(148)) << std::endl;
std::cout << (c->remove(498)) << std::endl;
std::cout << (d->insert(243)) << std::endl;
std::cout << (e->remove(36)) << std::endl;
b->printPretty();
std::cout << (c->remove(153)) << std::endl;
std::cout << (b->remove(456)) << std::endl;
std::cout << (c->remove(263)) << std::endl;
*b=*e;
std::cout << (a->remove(130)) << std::endl;
std::cout << (a->remove(379)) << std::endl;
*a=*d;
std::cout << (a->insert(148)) << std::endl;
std::cout << (c->remove(469)) << std::endl;
e->printPretty();
*d=*d;
*c=*d;
std::cout << (b->insert(285)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
b->printPretty();
std::cout << (c->insert(61)) << std::endl;
std::cout << (e->insert(498)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->remove(259)) << std::endl;
std::cout << (d->remove(498)) << std::endl;
std::cout << (b->remove(120)) << std::endl;
std::cout << (e->remove(420)) << std::endl;
*c=*d;
*b=*b;
std::cout << (e->remove(259)) << std::endl;
std::cout << (c->insert(352)) << std::endl;
std::cout << (a->remove(498)) << std::endl;
std::cout << (e->remove(138)) << std::endl;
std::cout << (b->insert(180)) << std::endl;
std::cout << (d->remove(61)) << std::endl;
std::cout << (c->insert(153)) << std::endl;
*e=*e;
std::cout << (e->remove(498)) << std::endl;
std::cout << (b->insert(498)) << std::endl;
c->printPretty();
std::cout << (e->insert(477)) << std::endl;
std::cout << (e->insert(122)) << std::endl;
a->printPretty();
std::cout << (c->insert(397)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
e->printPretty();
std::cout << (a->insert(92)) << std::endl;
*a=*c;
std::cout << (b->remove(379)) << std::endl;
std::cout << (e->remove(379)) << std::endl;
std::cout << (a->insert(259)) << std::endl;
*b=*e;
std::cout << (e->remove(72)) << std::endl;
*c=*c;
*a=*c;
std::cout << (e->insert(477)) << std::endl;
*b=*a;
*d=*d;
std::cout << (a->insert(243)) << std::endl;
*c=*b;
std::cout << (e->remove(323)) << std::endl;
std::cout << (a->insert(61)) << std::endl;
std::cout << (d->remove(270)) << std::endl;
std::cout << (c->remove(61)) << std::endl;
a->printPretty();
std::cout << (d->insert(320)) << std::endl;
std::cout << (d->insert(352)) << std::endl;
c->printPretty();
std::cout << (d->remove(218)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
std::cout << (a->insert(268)) << std::endl;
*b=*e;
*c=*d;
std::cout << (b->insert(18)) << std::endl;
std::cout << (e->insert(348)) << std::endl;
std::cout << (a->insert(357)) << std::endl;
std::cout << (c->insert(293)) << std::endl;
std::cout << (e->remove(85)) << std::endl;
c->printPretty();
std::cout << (a->remove(182)) << std::endl;
std::cout << (b->remove(130)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
std::cout << (a->remove(421)) << std::endl;
std::cout << (d->remove(92)) << std::endl;
std::cout << (b->remove(314)) << std::endl;
std::cout << (a->insert(447)) << std::endl;
std::cout << (a->insert(341)) << std::endl;
std::cout << (a->remove(208)) << std::endl;
std::cout << (d->insert(204)) << std::endl;
std::cout << (d->insert(341)) << std::endl;
std::cout << (c->remove(352)) << std::endl;
*c=*e;
std::cout << (b->remove(161)) << std::endl;
*a=*c;
*b=*d;
std::cout << (c->remove(348)) << std::endl;
*a=*d;
*d=*a;
*d=*c;
*c=*e;
std::cout << (b->remove(182)) << std::endl;
*d=*c;
std::cout << (b->remove(15)) << std::endl;
std::cout << (e->remove(122)) << std::endl;
std::cout << (c->insert(348)) << std::endl;
std::cout << (e->remove(348)) << std::endl;
std::cout << (a->remove(293)) << std::endl;
*b=*b;
a->printPretty();
*d=*a;
*c=*b;
c->printPretty();
std::cout << (b->insert(141)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
std::cout << (c->insert(442)) << std::endl;
*a=*e;
std::cout << (c->insert(65)) << std::endl;
std::cout << (c->remove(379)) << std::endl;
*b=*d;
std::cout << (c->insert(412)) << std::endl;
std::cout << (d->remove(53)) << std::endl;
*c=*e;
*c=*a;
std::cout << (d->insert(245)) << std::endl;
d->printPretty();
std::cout << (b->remove(320)) << std::endl;
std::cout << (a->remove(451)) << std::endl;
std::cout << (a->remove(123)) << std::endl;
*d=*d;
std::cout << (d->remove(93)) << std::endl;
*c=*c;
*b=*b;
std::cout << (e->remove(273)) << std::endl;
std::cout << (b->insert(84)) << std::endl;
*b=*c;
std::cout << (a->remove(146)) << std::endl;
std::cout << (b->insert(318)) << std::endl;
std::cout << (b->insert(130)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (c->remove(130)) << std::endl;
std::cout << (b->remove(318)) << std::endl;
std::cout << (e->remove(86)) << std::endl;
std::cout << (e->insert(130)) << std::endl;
std::cout << (e->insert(477)) << std::endl;
std::cout << (a->remove(74)) << std::endl;
*d=*b;
std::cout << (a->remove(130)) << std::endl;
*d=*c;
e->printPretty();
std::cout << (d->insert(477)) << std::endl;
std::cout << (b->insert(367)) << std::endl;
std::cout << (d->remove(237)) << std::endl;
std::cout << (e->insert(451)) << std::endl;
e->printPretty();
std::cout << (e->insert(477)) << std::endl;
std::cout << (b->insert(272)) << std::endl;
std::cout << (e->remove(130)) << std::endl;
std::cout << (c->remove(477)) << std::endl;
std::cout << (b->remove(272)) << std::endl;
std::cout << (c->remove(453)) << std::endl;
std::cout << (c->remove(451)) << std::endl;
std::cout << (b->remove(367)) << std::endl;
e->printPretty();
std::cout << (d->insert(8)) << std::endl;
*a=*b;
std::cout << (a->remove(475)) << std::endl;
std::cout << (a->insert(73)) << std::endl;
std::cout << (c->insert(133)) << std::endl;
std::cout << (d->insert(282)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (a->insert(73)) << std::endl;
std::cout << (c->remove(437)) << std::endl;
c->printPretty();
std::cout << (a->remove(477)) << std::endl;
*b=*b;
std::cout << (c->remove(469)) << std::endl;
std::cout << (d->insert(451)) << std::endl;
std::cout << (c->insert(428)) << std::endl;
a->printPretty();
std::cout << (a->remove(79)) << std::endl;
b->printPretty();
std::cout << (a->remove(274)) << std::endl;
a->printPretty();
std::cout << (a->insert(130)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
*c=*e;
*c=*b;
*c=*a;
std::cout << (b->insert(3)) << std::endl;
*d=*d;
d->printPretty();
*b=*d;
*e=*e;
std::cout << (a->remove(460)) << std::endl;
a->printPretty();
std::cout << (e->remove(297)) << std::endl;
return 0;
}
