#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
a->printPretty();
std::cout << (a->remove(469)) << std::endl;
a->printPretty();
std::cout << (a->remove(240)) << std::endl;
std::cout << (a->insert(396)) << std::endl;
a->printPretty();
std::cout << (a->remove(285)) << std::endl;
std::cout << (a->remove(396)) << std::endl;
std::cout << (a->remove(425)) << std::endl;
std::cout << (a->remove(495)) << std::endl;
std::cout << (a->remove(134)) << std::endl;
std::cout << (a->insert(138)) << std::endl;
std::cout << (a->insert(448)) << std::endl;
std::cout << (a->remove(96)) << std::endl;
std::cout << (a->insert(81)) << std::endl;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
std::cout << (a->remove(448)) << std::endl;
std::cout << (a->insert(138)) << std::endl;
b->printPretty();
std::cout << (a->insert(138)) << std::endl;
std::cout << (a->remove(138)) << std::endl;
a->printPretty();
std::cout << (a->insert(334)) << std::endl;
std::cout << (b->remove(23)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (a->insert(81)) << std::endl;
ScapegoatTree<int> *c=new ScapegoatTree<int>;
ScapegoatTree<int> *d=new ScapegoatTree<int>;
std::cout << (b->insert(465)) << std::endl;
*c=*b;
std::cout << (a->remove(334)) << std::endl;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
std::cout << (a->insert(81)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (c->remove(465)) << std::endl;
*e=*e;
*b=*e;
std::cout << (a->remove(217)) << std::endl;
std::cout << (e->remove(7)) << std::endl;
std::cout << (a->remove(81)) << std::endl;
*a=*a;
std::cout << (b->insert(234)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
std::cout << (d->insert(493)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
std::cout << (d->remove(493)) << std::endl;
std::cout << (d->insert(222)) << std::endl;
*a=*e;
std::cout << (b->insert(138)) << std::endl;
std::cout << (a->insert(414)) << std::endl;
std::cout << (b->insert(167)) << std::endl;
*a=*b;
*a=*d;
a->printPretty();
d->printPretty();
std::cout << (a->remove(130)) << std::endl;
c->printPretty();
std::cout << (d->remove(222)) << std::endl;
std::cout << (c->insert(374)) << std::endl;
std::cout << (a->remove(222)) << std::endl;
e->printPretty();
*e=*a;
*a=*c;
std::cout << (a->remove(441)) << std::endl;
std::cout << (b->insert(490)) << std::endl;
std::cout << (b->insert(231)) << std::endl;
std::cout << (c->remove(249)) << std::endl;
d->printPretty();
std::cout << (b->insert(491)) << std::endl;
std::cout << (e->remove(43)) << std::endl;
std::cout << (a->insert(325)) << std::endl;
std::cout << (a->remove(287)) << std::endl;
*a=*b;
c->printPretty();
std::cout << (c->insert(244)) << std::endl;
std::cout << (b->insert(91)) << std::endl;
b->printPretty();
std::cout << (c->insert(130)) << std::endl;
std::cout << (a->insert(138)) << std::endl;
std::cout << (e->remove(430)) << std::endl;
std::cout << (a->remove(361)) << std::endl;
c->printPretty();
std::cout << (c->remove(244)) << std::endl;
a->printPretty();
*a=*c;
std::cout << (a->insert(37)) << std::endl;
*e=*d;
std::cout << (b->remove(167)) << std::endl;
d->printPretty();
b->printPretty();
std::cout << (b->insert(244)) << std::endl;
std::cout << (e->remove(268)) << std::endl;
std::cout << (c->insert(130)) << std::endl;
c->printPretty();
b->printPretty();
c->printPretty();
std::cout << (a->insert(37)) << std::endl;
std::cout << (b->remove(91)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->remove(380)) << std::endl;
std::cout << (a->insert(420)) << std::endl;
d->printPretty();
*a=*e;
d->printPretty();
std::cout << (b->insert(239)) << std::endl;
std::cout << (b->insert(234)) << std::endl;
std::cout << (e->insert(196)) << std::endl;
std::cout << (e->insert(196)) << std::endl;
*e=*b;
std::cout << (e->remove(481)) << std::endl;
d->printPretty();
*b=*a;
std::cout << (c->insert(184)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
std::cout << (e->remove(234)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (e->insert(386)) << std::endl;
std::cout << (c->insert(184)) << std::endl;
*e=*e;
*a=*a;
std::cout << (c->remove(130)) << std::endl;
*d=*a;
*a=*d;
std::cout << (a->remove(104)) << std::endl;
std::cout << (e->insert(169)) << std::endl;
std::cout << (b->insert(467)) << std::endl;
std::cout << (b->remove(163)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (e->remove(283)) << std::endl;
std::cout << (b->remove(42)) << std::endl;
std::cout << (c->insert(82)) << std::endl;
std::cout << (c->remove(374)) << std::endl;
std::cout << (b->remove(150)) << std::endl;
std::cout << (e->remove(121)) << std::endl;
std::cout << (e->insert(283)) << std::endl;
std::cout << (d->remove(467)) << std::endl;
*b=*b;
c->printPretty();
std::cout << (c->remove(500)) << std::endl;
d->printPretty();
*d=*a;
std::cout << (a->remove(346)) << std::endl;
std::cout << (b->remove(81)) << std::endl;
e->printPretty();
*c=*c;
std::cout << (a->insert(17)) << std::endl;
std::cout << (c->remove(82)) << std::endl;
*a=*e;
std::cout << (e->insert(491)) << std::endl;
std::cout << (a->insert(59)) << std::endl;
*a=*b;
std::cout << (a->insert(173)) << std::endl;
std::cout << (b->remove(467)) << std::endl;
std::cout << (a->remove(17)) << std::endl;
std::cout << (e->insert(491)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (b->insert(314)) << std::endl;
std::cout << (a->insert(245)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
e->printPretty();
std::cout << (e->insert(169)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
std::cout << (a->insert(78)) << std::endl;
std::cout << (e->insert(491)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (a->remove(467)) << std::endl;
*c=*e;
std::cout << (e->insert(200)) << std::endl;
*d=*e;
*d=*a;
std::cout << (c->insert(30)) << std::endl;
std::cout << (d->insert(245)) << std::endl;
*c=*e;
b->printPretty();
std::cout << (e->remove(200)) << std::endl;
std::cout << (d->insert(476)) << std::endl;
std::cout << (b->insert(11)) << std::endl;
*a=*d;
std::cout << (b->remove(251)) << std::endl;
b->printPretty();
std::cout << (a->remove(254)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (a->remove(473)) << std::endl;
std::cout << (a->insert(238)) << std::endl;
std::cout << (c->insert(239)) << std::endl;
std::cout << (d->remove(321)) << std::endl;
d->printPretty();
std::cout << (e->remove(448)) << std::endl;
*e=*b;
std::cout << (c->remove(253)) << std::endl;
e->printPretty();
std::cout << (b->remove(190)) << std::endl;
e->printPretty();
a->printPretty();
std::cout << (d->insert(245)) << std::endl;
std::cout << (d->remove(2)) << std::endl;
std::cout << (b->insert(474)) << std::endl;
*b=*c;
std::cout << (c->insert(213)) << std::endl;
std::cout << (a->insert(150)) << std::endl;
std::cout << (b->remove(64)) << std::endl;
std::cout << (d->remove(162)) << std::endl;
std::cout << (d->remove(476)) << std::endl;
*c=*c;
std::cout << (a->remove(238)) << std::endl;
std::cout << (d->remove(278)) << std::endl;
std::cout << (d->insert(78)) << std::endl;
std::cout << (c->insert(192)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->insert(371)) << std::endl;
std::cout << (e->remove(499)) << std::endl;
std::cout << (e->remove(314)) << std::endl;
a->printPretty();
std::cout << (e->remove(266)) << std::endl;
std::cout << (e->remove(146)) << std::endl;
*e=*a;
std::cout << (e->remove(472)) << std::endl;
c->printPretty();
*d=*b;
std::cout << (d->remove(81)) << std::endl;
a->printPretty();
std::cout << (a->insert(381)) << std::endl;
d->printPretty();
*e=*b;
std::cout << (b->remove(371)) << std::endl;
*d=*a;
std::cout << (a->insert(389)) << std::endl;
*c=*d;
std::cout << (a->remove(150)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
std::cout << (a->remove(321)) << std::endl;
std::cout << (c->insert(170)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
*c=*e;
c->printPretty();
std::cout << (c->remove(155)) << std::endl;
a->printPretty();
std::cout << (b->insert(462)) << std::endl;
std::cout << (b->remove(348)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (b->insert(283)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
std::cout << (b->insert(386)) << std::endl;
*c=*c;
std::cout << (c->insert(293)) << std::endl;
e->printPretty();
std::cout << (d->remove(78)) << std::endl;
std::cout << (e->remove(169)) << std::endl;
e->printPretty();
std::cout << (d->insert(332)) << std::endl;
std::cout << (e->insert(319)) << std::endl;
*d=*e;
std::cout << (b->remove(142)) << std::endl;
std::cout << (e->remove(371)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
*c=*b;
std::cout << (b->insert(491)) << std::endl;
e->printPretty();
std::cout << (c->insert(239)) << std::endl;
*c=*b;
std::cout << (e->insert(386)) << std::endl;
std::cout << (b->remove(283)) << std::endl;
e->printPretty();
std::cout << (e->remove(456)) << std::endl;
e->printPretty();
e->printPretty();
c->printPretty();
std::cout << (e->remove(186)) << std::endl;
std::cout << (e->remove(490)) << std::endl;
*d=*c;
std::cout << (b->remove(151)) << std::endl;
*d=*a;
b->printPretty();
std::cout << (d->remove(79)) << std::endl;
std::cout << (d->insert(245)) << std::endl;
b->printPretty();
std::cout << (e->remove(284)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
*e=*b;
e->printPretty();
std::cout << (c->insert(490)) << std::endl;
std::cout << (b->remove(491)) << std::endl;
std::cout << (e->insert(239)) << std::endl;
std::cout << (d->remove(245)) << std::endl;
b->printPretty();
c->printPretty();
std::cout << (d->remove(231)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->insert(231)) << std::endl;
std::cout << (a->insert(60)) << std::endl;
std::cout << (b->insert(200)) << std::endl;
*b=*c;
*e=*a;
std::cout << (b->insert(283)) << std::endl;
std::cout << (e->insert(389)) << std::endl;
std::cout << (e->insert(245)) << std::endl;
std::cout << (b->insert(200)) << std::endl;
d->printPretty();
std::cout << (c->remove(342)) << std::endl;
std::cout << (d->remove(381)) << std::endl;
d->printPretty();
std::cout << (e->insert(158)) << std::endl;
std::cout << (d->remove(415)) << std::endl;
std::cout << (b->remove(76)) << std::endl;
std::cout << (e->insert(179)) << std::endl;
std::cout << (c->insert(404)) << std::endl;
std::cout << (a->remove(344)) << std::endl;
std::cout << (b->remove(268)) << std::endl;
c->printPretty();
std::cout << (d->remove(389)) << std::endl;
std::cout << (b->remove(32)) << std::endl;
std::cout << (b->remove(386)) << std::endl;
std::cout << (b->insert(283)) << std::endl;
std::cout << (b->insert(17)) << std::endl;
*b=*a;
std::cout << (d->insert(484)) << std::endl;
std::cout << (a->remove(111)) << std::endl;
a->printPretty();
std::cout << (b->remove(211)) << std::endl;
d->printPretty();
std::cout << (d->remove(231)) << std::endl;
e->printPretty();
std::cout << (a->insert(173)) << std::endl;
std::cout << (d->remove(448)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (b->insert(434)) << std::endl;
*c=*d;
std::cout << (b->insert(326)) << std::endl;
std::cout << (d->insert(123)) << std::endl;
a->printPretty();
std::cout << (e->remove(225)) << std::endl;
std::cout << (c->remove(41)) << std::endl;
std::cout << (a->remove(147)) << std::endl;
std::cout << (d->insert(173)) << std::endl;
std::cout << (e->remove(387)) << std::endl;
*a=*c;
std::cout << (a->insert(476)) << std::endl;
std::cout << (b->insert(446)) << std::endl;
*e=*b;
std::cout << (d->remove(285)) << std::endl;
std::cout << (c->remove(440)) << std::endl;
std::cout << (e->remove(381)) << std::endl;
std::cout << (a->insert(492)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (b->insert(15)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
std::cout << (a->remove(79)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
*d=*d;
std::cout << (c->remove(476)) << std::endl;
std::cout << (b->insert(190)) << std::endl;
std::cout << (b->insert(153)) << std::endl;
std::cout << (d->insert(123)) << std::endl;
std::cout << (d->remove(492)) << std::endl;
std::cout << (c->remove(492)) << std::endl;
c->printPretty();
std::cout << (a->insert(89)) << std::endl;
std::cout << (d->insert(484)) << std::endl;
std::cout << (e->remove(173)) << std::endl;
*d=*d;
std::cout << (c->insert(326)) << std::endl;
std::cout << (e->insert(476)) << std::endl;
std::cout << (b->remove(126)) << std::endl;
std::cout << (a->remove(277)) << std::endl;
std::cout << (a->remove(492)) << std::endl;
std::cout << (c->remove(484)) << std::endl;
std::cout << (c->remove(173)) << std::endl;
std::cout << (e->insert(181)) << std::endl;
*b=*a;
std::cout << (b->remove(173)) << std::endl;
d->printPretty();
*e=*e;
std::cout << (b->remove(333)) << std::endl;
std::cout << (a->insert(407)) << std::endl;
std::cout << (e->remove(484)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
std::cout << (e->insert(476)) << std::endl;
std::cout << (c->insert(78)) << std::endl;
*a=*e;
std::cout << (d->insert(78)) << std::endl;
std::cout << (b->remove(357)) << std::endl;
b->printPretty();
std::cout << (b->insert(78)) << std::endl;
std::cout << (b->insert(78)) << std::endl;
std::cout << (a->insert(181)) << std::endl;
*c=*b;
std::cout << (e->insert(161)) << std::endl;
b->printPretty();
std::cout << (d->remove(99)) << std::endl;
*b=*b;
std::cout << (b->remove(156)) << std::endl;
*d=*a;
std::cout << (e->insert(181)) << std::endl;
c->printPretty();
std::cout << (b->remove(40)) << std::endl;
std::cout << (b->remove(484)) << std::endl;
*d=*a;
d->printPretty();
*c=*b;
*a=*d;
std::cout << (e->remove(78)) << std::endl;
*b=*a;
std::cout << (e->insert(161)) << std::endl;
*a=*b;
b->printPretty();
std::cout << (c->remove(26)) << std::endl;
a->printPretty();
std::cout << (b->insert(273)) << std::endl;
std::cout << (e->remove(467)) << std::endl;
a->printPretty();
*c=*d;
std::cout << (c->insert(476)) << std::endl;
std::cout << (e->remove(359)) << std::endl;
std::cout << (c->remove(78)) << std::endl;
std::cout << (d->insert(483)) << std::endl;
std::cout << (b->remove(78)) << std::endl;
e->printPretty();
std::cout << (a->insert(35)) << std::endl;
std::cout << (b->insert(440)) << std::endl;
std::cout << (c->insert(220)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
std::cout << (d->insert(476)) << std::endl;
std::cout << (e->remove(161)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
std::cout << (a->remove(466)) << std::endl;
*e=*b;
std::cout << (a->insert(35)) << std::endl;
std::cout << (b->remove(404)) << std::endl;
*a=*a;
std::cout << (c->insert(119)) << std::endl;
std::cout << (a->remove(133)) << std::endl;
*c=*c;
std::cout << (c->remove(181)) << std::endl;
std::cout << (a->insert(18)) << std::endl;
*a=*a;
std::cout << (e->remove(476)) << std::endl;
std::cout << (c->insert(123)) << std::endl;
a->printPretty();
std::cout << (b->remove(247)) << std::endl;
std::cout << (d->remove(181)) << std::endl;
b->printPretty();
std::cout << (d->remove(91)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
b->printPretty();
*b=*b;
b->printPretty();
*d=*a;
std::cout << (b->remove(330)) << std::endl;
std::cout << (d->remove(301)) << std::endl;
std::cout << (d->insert(436)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
std::cout << (e->remove(181)) << std::endl;
std::cout << (e->remove(247)) << std::endl;
e->printPretty();
std::cout << (c->remove(22)) << std::endl;
std::cout << (a->insert(359)) << std::endl;
b->printPretty();
*c=*c;
std::cout << (a->insert(78)) << std::endl;
*b=*d;
std::cout << (c->insert(200)) << std::endl;
*e=*a;
std::cout << (e->insert(266)) << std::endl;
b->printPretty();
*b=*b;
*e=*a;
std::cout << (c->remove(432)) << std::endl;
std::cout << (b->insert(89)) << std::endl;
std::cout << (d->remove(393)) << std::endl;
std::cout << (b->insert(181)) << std::endl;
std::cout << (c->remove(322)) << std::endl;
std::cout << (a->remove(476)) << std::endl;
std::cout << (c->remove(278)) << std::endl;
*a=*a;
*b=*b;
std::cout << (e->remove(59)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
std::cout << (e->remove(244)) << std::endl;
std::cout << (e->remove(28)) << std::endl;
std::cout << (e->insert(18)) << std::endl;
std::cout << (a->remove(449)) << std::endl;
std::cout << (a->insert(195)) << std::endl;
std::cout << (d->remove(470)) << std::endl;
std::cout << (d->remove(293)) << std::endl;
std::cout << (e->remove(459)) << std::endl;
std::cout << (e->insert(434)) << std::endl;
std::cout << (c->insert(483)) << std::endl;
c->printPretty();
std::cout << (a->remove(293)) << std::endl;
std::cout << (d->remove(181)) << std::endl;
std::cout << (d->insert(18)) << std::endl;
std::cout << (a->insert(35)) << std::endl;
std::cout << (b->insert(222)) << std::endl;
std::cout << (c->insert(123)) << std::endl;
std::cout << (c->remove(297)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (d->remove(476)) << std::endl;
std::cout << (b->insert(101)) << std::endl;
std::cout << (e->insert(476)) << std::endl;
std::cout << (b->insert(222)) << std::endl;
std::cout << (b->insert(18)) << std::endl;
*b=*b;
*d=*d;
*e=*b;
*e=*c;
d->printPretty();
b->printPretty();
a->printPretty();
*e=*e;
*b=*e;
*a=*e;
std::cout << (b->remove(398)) << std::endl;
std::cout << (b->insert(123)) << std::endl;
std::cout << (c->remove(123)) << std::endl;
e->printPretty();
std::cout << (a->remove(499)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
std::cout << (b->remove(200)) << std::endl;
std::cout << (b->remove(296)) << std::endl;
std::cout << (e->insert(40)) << std::endl;
std::cout << (c->insert(119)) << std::endl;
c->printPretty();
a->printPretty();
std::cout << (c->remove(483)) << std::endl;
std::cout << (c->insert(46)) << std::endl;
std::cout << (a->insert(84)) << std::endl;
std::cout << (b->remove(103)) << std::endl;
std::cout << (c->remove(200)) << std::endl;
c->printPretty();
std::cout << (a->insert(356)) << std::endl;
std::cout << (e->remove(119)) << std::endl;
std::cout << (b->remove(359)) << std::endl;
*e=*c;
std::cout << (d->remove(35)) << std::endl;
c->printPretty();
*a=*b;
std::cout << (b->insert(476)) << std::endl;
std::cout << (a->insert(220)) << std::endl;
std::cout << (a->insert(162)) << std::endl;
std::cout << (d->remove(396)) << std::endl;
std::cout << (e->remove(38)) << std::endl;
d->printPretty();
c->printPretty();
std::cout << (b->insert(315)) << std::endl;
std::cout << (c->insert(183)) << std::endl;
b->printPretty();
b->printPretty();
std::cout << (d->insert(436)) << std::endl;
*e=*d;
*c=*c;
d->printPretty();
std::cout << (d->insert(429)) << std::endl;
*e=*c;
std::cout << (c->insert(476)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
a->printPretty();
std::cout << (b->remove(119)) << std::endl;
std::cout << (d->remove(69)) << std::endl;
std::cout << (b->remove(290)) << std::endl;
std::cout << (c->remove(359)) << std::endl;
e->printPretty();
*d=*c;
std::cout << (e->remove(290)) << std::endl;
std::cout << (b->remove(260)) << std::endl;
std::cout << (a->remove(483)) << std::endl;
std::cout << (a->insert(188)) << std::endl;
std::cout << (a->insert(162)) << std::endl;
a->printPretty();
c->printPretty();
std::cout << (a->remove(220)) << std::endl;
*b=*b;
std::cout << (d->insert(220)) << std::endl;
b->printPretty();
*d=*e;
std::cout << (b->remove(476)) << std::endl;
std::cout << (c->insert(473)) << std::endl;
std::cout << (e->insert(492)) << std::endl;
std::cout << (e->remove(492)) << std::endl;
std::cout << (c->remove(473)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
*a=*e;
std::cout << (d->insert(46)) << std::endl;
e->printPretty();
std::cout << (e->insert(92)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (d->insert(417)) << std::endl;
std::cout << (b->remove(123)) << std::endl;
std::cout << (b->remove(220)) << std::endl;
std::cout << (a->remove(427)) << std::endl;
*b=*a;
std::cout << (d->remove(46)) << std::endl;
*a=*a;
std::cout << (d->insert(115)) << std::endl;
*e=*d;
std::cout << (a->insert(437)) << std::endl;
*a=*a;
std::cout << (a->remove(46)) << std::endl;
std::cout << (c->insert(252)) << std::endl;
std::cout << (b->remove(119)) << std::endl;
std::cout << (b->insert(267)) << std::endl;
b->printPretty();
std::cout << (c->remove(476)) << std::endl;
std::cout << (e->remove(123)) << std::endl;
e->printPretty();
b->printPretty();
std::cout << (a->remove(109)) << std::endl;
std::cout << (e->insert(469)) << std::endl;
std::cout << (d->remove(220)) << std::endl;
std::cout << (a->remove(220)) << std::endl;
std::cout << (b->remove(220)) << std::endl;
std::cout << (a->remove(279)) << std::endl;
std::cout << (e->remove(50)) << std::endl;
e->printPretty();
std::cout << (c->insert(46)) << std::endl;
*c=*c;
b->printPretty();
std::cout << (a->insert(476)) << std::endl;
std::cout << (a->insert(183)) << std::endl;
std::cout << (d->insert(248)) << std::endl;
std::cout << (c->insert(3)) << std::endl;
std::cout << (a->remove(119)) << std::endl;
d->printPretty();
*c=*a;
std::cout << (e->remove(12)) << std::endl;
std::cout << (b->remove(4)) << std::endl;
std::cout << (c->insert(107)) << std::endl;
std::cout << (b->remove(476)) << std::endl;
std::cout << (d->insert(24)) << std::endl;
std::cout << (e->insert(220)) << std::endl;
*b=*d;
std::cout << (e->insert(188)) << std::endl;
std::cout << (a->remove(183)) << std::endl;
std::cout << (d->remove(183)) << std::endl;
*d=*b;
*d=*c;
std::cout << (d->insert(465)) << std::endl;
std::cout << (e->insert(359)) << std::endl;
*a=*e;
*a=*c;
std::cout << (c->remove(183)) << std::endl;
*b=*c;
std::cout << (b->remove(437)) << std::endl;
c->printPretty();
std::cout << (b->remove(238)) << std::endl;
d->printPretty();
std::cout << (b->insert(107)) << std::endl;
std::cout << (b->remove(469)) << std::endl;
a->printPretty();
*d=*e;
*a=*c;
*e=*a;
std::cout << (e->insert(144)) << std::endl;
b->printPretty();
std::cout << (a->insert(228)) << std::endl;
std::cout << (d->remove(417)) << std::endl;
std::cout << (d->remove(282)) << std::endl;
std::cout << (c->remove(135)) << std::endl;
std::cout << (a->remove(399)) << std::endl;
e->printPretty();
std::cout << (c->insert(352)) << std::endl;
*c=*b;
*a=*b;
std::cout << (c->insert(73)) << std::endl;
c->printPretty();
d->printPretty();
std::cout << (e->insert(494)) << std::endl;
std::cout << (c->insert(139)) << std::endl;
e->printPretty();
*e=*b;
std::cout << (b->remove(359)) << std::endl;
std::cout << (b->insert(107)) << std::endl;
std::cout << (d->remove(194)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
std::cout << (d->insert(119)) << std::endl;
std::cout << (b->insert(195)) << std::endl;
std::cout << (d->remove(331)) << std::endl;
std::cout << (a->insert(170)) << std::endl;
std::cout << (e->insert(119)) << std::endl;
std::cout << (d->remove(330)) << std::endl;
*d=*c;
std::cout << (d->remove(320)) << std::endl;
e->printPretty();
std::cout << (b->insert(476)) << std::endl;
return 0;
}
