#include <iostream>
#include "../your_code/ScapegoatTree.cpp"
int main() {
ScapegoatTree<int> *a=new ScapegoatTree<int>;
ScapegoatTree<int> *b=new ScapegoatTree<int>;
*a=*a;
ScapegoatTree<int> *c=new ScapegoatTree<int>(*b);
ScapegoatTree<int> *d=new ScapegoatTree<int>;
ScapegoatTree<int> *e=new ScapegoatTree<int>(*d);
b->printPretty();
e->printPretty();
*a=*c;
d->printPretty();
c->printPretty();
d->printPretty();
std::cout << (a->insert(449)) << std::endl;
*d=*c;
*d=*a;
a->printPretty();
std::cout << (a->remove(449)) << std::endl;
std::cout << (a->remove(387)) << std::endl;
std::cout << (d->remove(89)) << std::endl;
c->printPretty();
std::cout << (c->insert(313)) << std::endl;
std::cout << (a->remove(184)) << std::endl;
std::cout << (d->remove(449)) << std::endl;
d->printPretty();
std::cout << (a->remove(471)) << std::endl;
std::cout << (d->insert(263)) << std::endl;
std::cout << (b->insert(471)) << std::endl;
std::cout << (d->remove(466)) << std::endl;
std::cout << (b->remove(498)) << std::endl;
std::cout << (c->remove(106)) << std::endl;
std::cout << (c->remove(283)) << std::endl;
*a=*b;
std::cout << (e->remove(466)) << std::endl;
std::cout << (a->remove(272)) << std::endl;
b->printPretty();
std::cout << (c->remove(313)) << std::endl;
d->printPretty();
std::cout << (e->insert(150)) << std::endl;
c->printPretty();
*c=*c;
*d=*b;
std::cout << (e->insert(150)) << std::endl;
std::cout << (b->remove(312)) << std::endl;
std::cout << (e->remove(150)) << std::endl;
std::cout << (a->insert(471)) << std::endl;
std::cout << (d->remove(471)) << std::endl;
std::cout << (e->insert(24)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
*e=*e;
std::cout << (b->insert(471)) << std::endl;
*c=*e;
std::cout << (b->insert(74)) << std::endl;
std::cout << (b->insert(74)) << std::endl;
std::cout << (d->remove(188)) << std::endl;
b->printPretty();
std::cout << (d->insert(108)) << std::endl;
std::cout << (a->remove(471)) << std::endl;
*d=*e;
e->printPretty();
b->printPretty();
std::cout << (e->remove(43)) << std::endl;
*c=*d;
std::cout << (d->insert(24)) << std::endl;
std::cout << (d->insert(24)) << std::endl;
std::cout << (b->remove(50)) << std::endl;
std::cout << (a->insert(460)) << std::endl;
e->printPretty();
std::cout << (b->insert(265)) << std::endl;
std::cout << (e->remove(24)) << std::endl;
*b=*c;
std::cout << (d->remove(24)) << std::endl;
std::cout << (a->remove(171)) << std::endl;
std::cout << (e->remove(4)) << std::endl;
b->printPretty();
std::cout << (a->remove(460)) << std::endl;
b->printPretty();
std::cout << (c->insert(24)) << std::endl;
d->printPretty();
e->printPretty();
std::cout << (c->remove(24)) << std::endl;
std::cout << (c->remove(351)) << std::endl;
b->printPretty();
std::cout << (e->remove(78)) << std::endl;
e->printPretty();
std::cout << (c->insert(109)) << std::endl;
std::cout << (e->remove(21)) << std::endl;
d->printPretty();
std::cout << (d->insert(192)) << std::endl;
std::cout << (d->remove(323)) << std::endl;
*d=*e;
std::cout << (a->remove(201)) << std::endl;
std::cout << (a->remove(317)) << std::endl;
*d=*e;
std::cout << (b->insert(327)) << std::endl;
c->printPretty();
std::cout << (d->insert(18)) << std::endl;
std::cout << (a->insert(303)) << std::endl;
*b=*c;
std::cout << (d->remove(407)) << std::endl;
*b=*d;
std::cout << (d->insert(245)) << std::endl;
std::cout << (a->remove(303)) << std::endl;
d->printPretty();
d->printPretty();
std::cout << (b->insert(59)) << std::endl;
std::cout << (c->insert(259)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
*e=*c;
std::cout << (e->remove(259)) << std::endl;
std::cout << (e->remove(158)) << std::endl;
*d=*c;
std::cout << (b->remove(372)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
std::cout << (d->remove(105)) << std::endl;
std::cout << (e->remove(375)) << std::endl;
std::cout << (b->remove(59)) << std::endl;
*d=*c;
std::cout << (c->insert(259)) << std::endl;
*c=*c;
std::cout << (e->insert(432)) << std::endl;
std::cout << (b->insert(270)) << std::endl;
std::cout << (d->remove(259)) << std::endl;
std::cout << (d->insert(112)) << std::endl;
std::cout << (b->insert(198)) << std::endl;
*a=*d;
std::cout << (e->insert(264)) << std::endl;
e->printPretty();
*a=*e;
*c=*c;
std::cout << (e->insert(109)) << std::endl;
std::cout << (c->insert(17)) << std::endl;
std::cout << (b->remove(270)) << std::endl;
std::cout << (d->remove(100)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
std::cout << (d->remove(233)) << std::endl;
std::cout << (b->insert(357)) << std::endl;
std::cout << (e->remove(432)) << std::endl;
std::cout << (c->remove(210)) << std::endl;
*c=*c;
a->printPretty();
std::cout << (e->insert(440)) << std::endl;
std::cout << (e->insert(109)) << std::endl;
*a=*a;
std::cout << (d->remove(17)) << std::endl;
d->printPretty();
std::cout << (d->remove(112)) << std::endl;
std::cout << (b->remove(453)) << std::endl;
std::cout << (d->insert(329)) << std::endl;
std::cout << (c->remove(231)) << std::endl;
d->printPretty();
*d=*e;
std::cout << (e->remove(439)) << std::endl;
std::cout << (c->remove(17)) << std::endl;
*b=*e;
*c=*b;
std::cout << (a->remove(147)) << std::endl;
std::cout << (a->insert(264)) << std::endl;
std::cout << (d->insert(131)) << std::endl;
*c=*e;
std::cout << (d->remove(440)) << std::endl;
std::cout << (e->remove(109)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
std::cout << (e->remove(156)) << std::endl;
*b=*b;
std::cout << (b->remove(456)) << std::endl;
c->printPretty();
std::cout << (a->insert(350)) << std::endl;
*b=*b;
std::cout << (c->insert(440)) << std::endl;
std::cout << (b->insert(449)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
std::cout << (b->remove(440)) << std::endl;
*b=*b;
std::cout << (d->remove(168)) << std::endl;
e->printPretty();
std::cout << (a->insert(432)) << std::endl;
*d=*d;
std::cout << (e->insert(43)) << std::endl;
std::cout << (c->insert(440)) << std::endl;
e->printPretty();
e->printPretty();
std::cout << (b->insert(395)) << std::endl;
std::cout << (e->remove(194)) << std::endl;
std::cout << (b->remove(395)) << std::endl;
std::cout << (c->insert(484)) << std::endl;
std::cout << (e->remove(205)) << std::endl;
std::cout << (e->remove(294)) << std::endl;
std::cout << (b->remove(242)) << std::endl;
std::cout << (b->remove(449)) << std::endl;
*e=*b;
std::cout << (e->remove(109)) << std::endl;
std::cout << (b->insert(109)) << std::endl;
*d=*d;
*c=*d;
std::cout << (e->remove(249)) << std::endl;
std::cout << (d->remove(244)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (c->insert(376)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (b->remove(217)) << std::endl;
std::cout << (a->remove(106)) << std::endl;
std::cout << (e->remove(462)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (d->remove(227)) << std::endl;
*c=*c;
std::cout << (e->remove(264)) << std::endl;
d->printPretty();
std::cout << (d->remove(109)) << std::endl;
*d=*e;
std::cout << (a->insert(109)) << std::endl;
std::cout << (d->insert(312)) << std::endl;
d->printPretty();
std::cout << (b->insert(109)) << std::endl;
std::cout << (d->insert(443)) << std::endl;
std::cout << (c->insert(109)) << std::endl;
*e=*c;
*d=*c;
std::cout << (c->remove(280)) << std::endl;
std::cout << (e->insert(131)) << std::endl;
*a=*a;
*a=*d;
std::cout << (d->remove(172)) << std::endl;
std::cout << (a->remove(109)) << std::endl;
*e=*e;
std::cout << (a->insert(33)) << std::endl;
std::cout << (b->remove(361)) << std::endl;
b->printPretty();
std::cout << (e->insert(273)) << std::endl;
std::cout << (a->insert(33)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
*c=*c;
std::cout << (b->remove(442)) << std::endl;
std::cout << (a->insert(104)) << std::endl;
std::cout << (c->insert(131)) << std::endl;
std::cout << (b->insert(109)) << std::endl;
*c=*e;
std::cout << (e->insert(264)) << std::endl;
a->printPretty();
std::cout << (c->insert(394)) << std::endl;
std::cout << (a->insert(131)) << std::endl;
std::cout << (a->insert(22)) << std::endl;
*a=*d;
*c=*b;
std::cout << (e->insert(376)) << std::endl;
c->printPretty();
std::cout << (b->remove(109)) << std::endl;
*a=*e;
std::cout << (d->insert(376)) << std::endl;
*c=*a;
std::cout << (c->remove(447)) << std::endl;
std::cout << (c->insert(474)) << std::endl;
std::cout << (b->insert(33)) << std::endl;
*d=*a;
std::cout << (a->insert(376)) << std::endl;
std::cout << (b->insert(208)) << std::endl;
c->printPretty();
std::cout << (d->insert(273)) << std::endl;
std::cout << (c->remove(486)) << std::endl;
std::cout << (c->insert(474)) << std::endl;
std::cout << (a->insert(376)) << std::endl;
d->printPretty();
std::cout << (c->remove(388)) << std::endl;
std::cout << (e->insert(226)) << std::endl;
*d=*d;
std::cout << (c->insert(224)) << std::endl;
std::cout << (c->remove(335)) << std::endl;
std::cout << (b->remove(264)) << std::endl;
std::cout << (c->insert(320)) << std::endl;
std::cout << (b->remove(33)) << std::endl;
std::cout << (c->remove(320)) << std::endl;
std::cout << (b->insert(247)) << std::endl;
*b=*d;
std::cout << (e->insert(209)) << std::endl;
std::cout << (b->remove(109)) << std::endl;
*a=*d;
c->printPretty();
*a=*e;
e->printPretty();
c->printPretty();
*e=*d;
std::cout << (e->remove(279)) << std::endl;
d->printPretty();
*d=*a;
e->printPretty();
d->printPretty();
std::cout << (a->insert(376)) << std::endl;
e->printPretty();
std::cout << (a->insert(428)) << std::endl;
std::cout << (c->remove(474)) << std::endl;
std::cout << (b->insert(131)) << std::endl;
std::cout << (c->remove(292)) << std::endl;
std::cout << (b->insert(226)) << std::endl;
*c=*b;
std::cout << (d->remove(376)) << std::endl;
a->printPretty();
std::cout << (e->insert(272)) << std::endl;
std::cout << (b->remove(156)) << std::endl;
std::cout << (e->insert(264)) << std::endl;
std::cout << (b->insert(319)) << std::endl;
std::cout << (b->remove(428)) << std::endl;
std::cout << (d->remove(109)) << std::endl;
std::cout << (b->remove(279)) << std::endl;
b->printPretty();
d->printPretty();
std::cout << (c->remove(226)) << std::endl;
e->printPretty();
d->printPretty();
std::cout << (d->insert(273)) << std::endl;
std::cout << (c->remove(273)) << std::endl;
a->printPretty();
a->printPretty();
std::cout << (a->insert(194)) << std::endl;
std::cout << (b->insert(199)) << std::endl;
std::cout << (a->remove(152)) << std::endl;
c->printPretty();
std::cout << (b->insert(131)) << std::endl;
*a=*e;
std::cout << (c->insert(264)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (b->remove(35)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
std::cout << (a->insert(272)) << std::endl;
std::cout << (b->remove(53)) << std::endl;
std::cout << (d->remove(413)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (e->insert(257)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (e->remove(257)) << std::endl;
std::cout << (a->remove(131)) << std::endl;
d->printPretty();
std::cout << (b->remove(56)) << std::endl;
*a=*e;
*a=*d;
std::cout << (e->remove(175)) << std::endl;
*a=*b;
std::cout << (d->insert(306)) << std::endl;
std::cout << (b->remove(493)) << std::endl;
e->printPretty();
std::cout << (e->insert(264)) << std::endl;
std::cout << (c->remove(131)) << std::endl;
std::cout << (b->remove(131)) << std::endl;
std::cout << (b->remove(264)) << std::endl;
*d=*d;
std::cout << (b->remove(227)) << std::endl;
std::cout << (c->insert(264)) << std::endl;
std::cout << (c->remove(376)) << std::endl;
std::cout << (e->insert(273)) << std::endl;
std::cout << (c->remove(264)) << std::endl;
*e=*a;
*a=*b;
std::cout << (d->insert(191)) << std::endl;
*a=*c;
std::cout << (b->insert(199)) << std::endl;
*a=*e;
std::cout << (c->insert(276)) << std::endl;
std::cout << (c->insert(276)) << std::endl;
std::cout << (a->insert(252)) << std::endl;
std::cout << (d->remove(78)) << std::endl;
*c=*c;
std::cout << (e->remove(9)) << std::endl;
std::cout << (c->remove(334)) << std::endl;
*b=*e;
std::cout << (e->remove(131)) << std::endl;
*b=*a;
*c=*a;
std::cout << (d->remove(131)) << std::endl;
d->printPretty();
*c=*d;
std::cout << (a->insert(114)) << std::endl;
std::cout << (a->insert(200)) << std::endl;
std::cout << (e->remove(500)) << std::endl;
std::cout << (c->remove(306)) << std::endl;
*c=*e;
std::cout << (d->insert(394)) << std::endl;
std::cout << (a->remove(264)) << std::endl;
*c=*a;
std::cout << (b->insert(319)) << std::endl;
*e=*d;
d->printPretty();
std::cout << (e->remove(68)) << std::endl;
*b=*e;
c->printPretty();
std::cout << (a->insert(58)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
std::cout << (d->insert(285)) << std::endl;
std::cout << (d->remove(285)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
std::cout << (b->remove(394)) << std::endl;
std::cout << (c->insert(322)) << std::endl;
std::cout << (a->insert(199)) << std::endl;
std::cout << (e->insert(394)) << std::endl;
*b=*a;
std::cout << (e->remove(442)) << std::endl;
a->printPretty();
std::cout << (d->insert(209)) << std::endl;
std::cout << (e->remove(273)) << std::endl;
e->printPretty();
std::cout << (e->insert(325)) << std::endl;
*e=*a;
std::cout << (c->remove(328)) << std::endl;
*c=*b;
*b=*b;
std::cout << (d->remove(226)) << std::endl;
std::cout << (a->remove(464)) << std::endl;
std::cout << (b->remove(495)) << std::endl;
std::cout << (d->remove(463)) << std::endl;
*e=*a;
std::cout << (c->remove(91)) << std::endl;
std::cout << (e->insert(369)) << std::endl;
*b=*e;
std::cout << (c->remove(273)) << std::endl;
*e=*d;
std::cout << (c->remove(363)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
std::cout << (b->insert(32)) << std::endl;
*c=*d;
b->printPretty();
std::cout << (a->insert(58)) << std::endl;
std::cout << (b->remove(114)) << std::endl;
b->printPretty();
*c=*e;
std::cout << (d->insert(480)) << std::endl;
std::cout << (e->remove(296)) << std::endl;
std::cout << (b->insert(131)) << std::endl;
*e=*c;
std::cout << (a->insert(319)) << std::endl;
std::cout << (e->insert(121)) << std::endl;
std::cout << (c->remove(346)) << std::endl;
*e=*a;
std::cout << (a->remove(252)) << std::endl;
c->printPretty();
std::cout << (b->insert(131)) << std::endl;
*a=*c;
std::cout << (a->remove(394)) << std::endl;
std::cout << (e->remove(376)) << std::endl;
*c=*a;
*b=*a;
*c=*c;
c->printPretty();
std::cout << (e->remove(486)) << std::endl;
a->printPretty();
std::cout << (c->insert(40)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
std::cout << (d->insert(273)) << std::endl;
std::cout << (c->insert(40)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (b->insert(264)) << std::endl;
*e=*a;
b->printPretty();
std::cout << (c->insert(282)) << std::endl;
std::cout << (a->insert(311)) << std::endl;
std::cout << (e->insert(468)) << std::endl;
std::cout << (d->remove(480)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
std::cout << (e->remove(172)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
std::cout << (d->insert(198)) << std::endl;
std::cout << (c->remove(39)) << std::endl;
std::cout << (a->insert(354)) << std::endl;
b->printPretty();
std::cout << (c->insert(209)) << std::endl;
std::cout << (b->remove(122)) << std::endl;
std::cout << (d->insert(264)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
e->printPretty();
std::cout << (a->remove(318)) << std::endl;
std::cout << (e->insert(118)) << std::endl;
*b=*b;
b->printPretty();
std::cout << (c->remove(306)) << std::endl;
a->printPretty();
std::cout << (e->insert(297)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
d->printPretty();
std::cout << (d->remove(88)) << std::endl;
*d=*c;
std::cout << (b->remove(478)) << std::endl;
d->printPretty();
std::cout << (a->insert(311)) << std::endl;
std::cout << (c->remove(40)) << std::endl;
*b=*e;
*d=*c;
std::cout << (e->insert(191)) << std::endl;
std::cout << (b->insert(209)) << std::endl;
std::cout << (a->insert(338)) << std::endl;
*a=*a;
*d=*d;
std::cout << (a->insert(230)) << std::endl;
std::cout << (c->insert(282)) << std::endl;
*b=*a;
std::cout << (c->insert(209)) << std::endl;
std::cout << (a->insert(209)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
std::cout << (d->insert(299)) << std::endl;
std::cout << (a->remove(311)) << std::endl;
std::cout << (a->insert(442)) << std::endl;
std::cout << (a->insert(57)) << std::endl;
std::cout << (d->remove(299)) << std::endl;
std::cout << (c->remove(282)) << std::endl;
*b=*b;
*e=*b;
std::cout << (c->remove(294)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (d->remove(438)) << std::endl;
*b=*a;
std::cout << (d->remove(264)) << std::endl;
*c=*d;
*b=*b;
d->printPretty();
*d=*b;
std::cout << (b->insert(459)) << std::endl;
std::cout << (c->remove(209)) << std::endl;
std::cout << (b->remove(230)) << std::endl;
*c=*e;
std::cout << (a->insert(442)) << std::endl;
std::cout << (e->insert(152)) << std::endl;
std::cout << (b->remove(15)) << std::endl;
std::cout << (b->insert(36)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
*e=*c;
std::cout << (b->remove(138)) << std::endl;
std::cout << (b->remove(354)) << std::endl;
std::cout << (c->insert(311)) << std::endl;
std::cout << (c->remove(189)) << std::endl;
std::cout << (e->remove(206)) << std::endl;
std::cout << (a->remove(209)) << std::endl;
std::cout << (d->remove(163)) << std::endl;
std::cout << (c->remove(233)) << std::endl;
*e=*d;
std::cout << (a->remove(191)) << std::endl;
std::cout << (a->remove(48)) << std::endl;
std::cout << (d->insert(375)) << std::endl;
std::cout << (b->remove(457)) << std::endl;
std::cout << (e->insert(297)) << std::endl;
std::cout << (d->insert(445)) << std::endl;
*d=*e;
a->printPretty();
std::cout << (b->insert(263)) << std::endl;
std::cout << (e->insert(209)) << std::endl;
std::cout << (d->remove(354)) << std::endl;
std::cout << (a->remove(230)) << std::endl;
std::cout << (d->remove(338)) << std::endl;
std::cout << (d->remove(4)) << std::endl;
std::cout << (a->remove(265)) << std::endl;
e->printPretty();
*d=*b;
std::cout << (d->remove(264)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
std::cout << (a->remove(93)) << std::endl;
d->printPretty();
std::cout << (a->remove(338)) << std::endl;
*e=*c;
*e=*a;
*e=*c;
std::cout << (b->remove(209)) << std::endl;
*a=*c;
std::cout << (e->insert(97)) << std::endl;
c->printPretty();
std::cout << (e->insert(97)) << std::endl;
std::cout << (d->insert(191)) << std::endl;
*d=*d;
*d=*e;
std::cout << (a->insert(306)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (a->remove(497)) << std::endl;
std::cout << (b->remove(11)) << std::endl;
std::cout << (e->insert(97)) << std::endl;
std::cout << (b->insert(338)) << std::endl;
std::cout << (b->remove(459)) << std::endl;
std::cout << (e->remove(191)) << std::endl;
*a=*b;
std::cout << (d->insert(273)) << std::endl;
std::cout << (b->remove(306)) << std::endl;
b->printPretty();
std::cout << (e->insert(338)) << std::endl;
std::cout << (d->insert(287)) << std::endl;
*b=*c;
std::cout << (b->insert(338)) << std::endl;
std::cout << (c->remove(354)) << std::endl;
std::cout << (a->insert(266)) << std::endl;
std::cout << (a->remove(57)) << std::endl;
*c=*b;
*d=*e;
*a=*e;
std::cout << (a->remove(193)) << std::endl;
std::cout << (c->remove(438)) << std::endl;
std::cout << (b->insert(67)) << std::endl;
std::cout << (b->remove(315)) << std::endl;
std::cout << (e->insert(311)) << std::endl;
std::cout << (a->insert(297)) << std::endl;
std::cout << (a->insert(311)) << std::endl;
*a=*c;
std::cout << (a->insert(427)) << std::endl;
c->printPretty();
std::cout << (b->remove(306)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
std::cout << (d->remove(311)) << std::endl;
std::cout << (a->remove(239)) << std::endl;
c->printPretty();
std::cout << (c->insert(297)) << std::endl;
b->printPretty();
std::cout << (e->insert(380)) << std::endl;
std::cout << (e->insert(154)) << std::endl;
*e=*e;
std::cout << (d->remove(6)) << std::endl;
std::cout << (d->insert(306)) << std::endl;
b->printPretty();
std::cout << (d->remove(439)) << std::endl;
std::cout << (e->insert(380)) << std::endl;
std::cout << (b->insert(273)) << std::endl;
std::cout << (d->insert(230)) << std::endl;
c->printPretty();
c->printPretty();
*a=*e;
*a=*a;
std::cout << (d->insert(495)) << std::endl;
std::cout << (e->insert(230)) << std::endl;
a->printPretty();
std::cout << (c->insert(481)) << std::endl;
*e=*e;
std::cout << (c->remove(392)) << std::endl;
a->printPretty();
*b=*d;
*b=*c;
std::cout << (b->insert(209)) << std::endl;
a->printPretty();
std::cout << (a->insert(203)) << std::endl;
a->printPretty();
std::cout << (a->remove(203)) << std::endl;
std::cout << (c->remove(191)) << std::endl;
std::cout << (d->insert(354)) << std::endl;
std::cout << (e->remove(451)) << std::endl;
*d=*e;
std::cout << (e->insert(311)) << std::endl;
std::cout << (c->insert(86)) << std::endl;
std::cout << (b->remove(273)) << std::endl;
b->printPretty();
std::cout << (d->remove(209)) << std::endl;
std::cout << (b->remove(264)) << std::endl;
std::cout << (b->remove(481)) << std::endl;
std::cout << (e->remove(97)) << std::endl;
std::cout << (e->insert(311)) << std::endl;
std::cout << (e->remove(354)) << std::endl;
std::cout << (d->insert(184)) << std::endl;
std::cout << (b->insert(356)) << std::endl;
std::cout << (d->remove(273)) << std::endl;
b->printPretty();
*c=*b;
std::cout << (b->remove(191)) << std::endl;
std::cout << (a->insert(97)) << std::endl;
std::cout << (d->remove(189)) << std::endl;
std::cout << (b->remove(338)) << std::endl;
std::cout << (c->insert(191)) << std::endl;
std::cout << (d->remove(16)) << std::endl;
e->printPretty();
std::cout << (b->remove(421)) << std::endl;
std::cout << (e->insert(39)) << std::endl;
std::cout << (e->remove(311)) << std::endl;
std::cout << (c->remove(311)) << std::endl;
std::cout << (e->remove(380)) << std::endl;
std::cout << (b->remove(423)) << std::endl;
std::cout << (a->insert(115)) << std::endl;
*a=*b;
*c=*b;
std::cout << (b->insert(311)) << std::endl;
std::cout << (b->insert(311)) << std::endl;
std::cout << (e->remove(338)) << std::endl;
std::cout << (e->remove(195)) << std::endl;
e->printPretty();
std::cout << (e->insert(464)) << std::endl;
c->printPretty();
std::cout << (c->remove(311)) << std::endl;
e->printPretty();
std::cout << (a->insert(354)) << std::endl;
std::cout << (c->insert(306)) << std::endl;
*a=*c;
std::cout << (a->remove(26)) << std::endl;
std::cout << (e->remove(409)) << std::endl;
std::cout << (a->insert(39)) << std::endl;
std::cout << (c->insert(378)) << std::endl;
std::cout << (e->insert(39)) << std::endl;
std::cout << (b->insert(59)) << std::endl;
c->printPretty();
std::cout << (d->remove(50)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
*c=*b;
std::cout << (c->insert(306)) << std::endl;
std::cout << (a->remove(354)) << std::endl;
std::cout << (d->insert(338)) << std::endl;
std::cout << (a->insert(193)) << std::endl;
std::cout << (d->remove(354)) << std::endl;
a->printPretty();
std::cout << (d->remove(491)) << std::endl;
b->printPretty();
std::cout << (c->remove(297)) << std::endl;
d->printPretty();
std::cout << (d->insert(297)) << std::endl;
std::cout << (a->insert(356)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (c->insert(230)) << std::endl;
d->printPretty();
e->printPretty();
*d=*e;
std::cout << (b->insert(356)) << std::endl;
std::cout << (a->insert(380)) << std::endl;
std::cout << (b->insert(297)) << std::endl;
std::cout << (b->remove(311)) << std::endl;
*e=*b;
a->printPretty();
*e=*d;
std::cout << (a->remove(263)) << std::endl;
std::cout << (c->insert(59)) << std::endl;
e->printPretty();
c->printPretty();
std::cout << (b->insert(118)) << std::endl;
std::cout << (b->insert(94)) << std::endl;
std::cout << (a->remove(472)) << std::endl;
std::cout << (c->remove(42)) << std::endl;
std::cout << (a->insert(74)) << std::endl;
*a=*c;
*e=*a;
std::cout << (c->insert(59)) << std::endl;
std::cout << (d->remove(264)) << std::endl;
std::cout << (e->insert(282)) << std::endl;
b->printPretty();
std::cout << (e->remove(306)) << std::endl;
std::cout << (b->insert(306)) << std::endl;
std::cout << (e->insert(307)) << std::endl;
std::cout << (d->insert(183)) << std::endl;
std::cout << (d->remove(439)) << std::endl;
d->printPretty();
*d=*c;
std::cout << (a->remove(230)) << std::endl;
std::cout << (c->remove(129)) << std::endl;
std::cout << (b->insert(354)) << std::endl;
std::cout << (e->insert(282)) << std::endl;
std::cout << (b->insert(429)) << std::endl;
std::cout << (d->remove(230)) << std::endl;
c->printPretty();
std::cout << (b->insert(354)) << std::endl;
return 0;
}
